### PR TITLE
sql: Fix negative fractional timestamp handling

### LINKED ISSUE #16610: `to_timestamp` truncates the fractional part of pre-1970 timestamps.
### What version of Materialize are you using?

main

### How did you install Materialize?

bin/environmentd

### What is the issue?

```
materialize=> SELECT to_timestamp(-0.1::float8);
      to_timestamp      
------------------------
 1970-01-01 00:00:00+00
(1 row)

```

The culprit is this line: https://github.com/MaterializeInc/materialize/blob/bb6b6ef7d/src/expr/src/scalar/func/impls/float64.rs#L433-L433 .

Invoking `as` on a negative `f64` when converting to an unsigned integer just saturates to 0.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jkosh44**
Previously, the `to_timestamp` function would mistakenly convert any negative nanoseconds to 0. This commit fixes this issue so they're properly handled.

Fixes #16610

### Motivation
This PR fixes a recognized bug.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - `to_timestamp()` now returns an error instead of null when the timestamp is out of range. This matches PostgreSQL's behavior.

### CODE REVIEW

File: src/expr/src/scalar/func/impls/float64.rs [hunk 1]
```diff
@@ -440,14 +440,20 @@ sqlfunc!(
         if !f.is_finite() {
             None
         } else {
-            let secs = f.trunc() as i64;
+            let mut secs = f.trunc() as i64;
```
Comment (mjibson) [inline src/expr/src/scalar/func/impls/float64.rs:443]: I'd like to see all of the `as` removed instead of rejiggering them, because it's still pretty unclear what's going on.

Comment (jkosh44) [reply src/expr/src/scalar/func/impls/float64.rs:443]: I just removed all the integer to integer conversions using `as`. Unfortunately, as far as I'm aware there is no lossy conversion from `f64` to `i64` without using `as`.

Comment (mjibson) [reply src/expr/src/scalar/func/impls/float64.rs:443]: Indeed! Can you move this logic into ore then? From Nikhil:

> Over time, we should wrap up every as conversion into a descriptively named and documented method in mz_ore::cast (e.g., cast_usize_to_f64_lossy), and remove all the lint exceptions across the codebase.

Comment (umanwizard) [reply src/expr/src/scalar/func/impls/float64.rs:443]: f64's range is greater than i64, and this will just saturate to the max i64 value in that case. Should we return an error in that case?

Comment (jkosh44) [reply src/expr/src/scalar/func/impls/float64.rs:443]: Good point, I'll do that now.

Comment (mjibson) [reply src/expr/src/scalar/func/impls/float64.rs:443]: The desired behavior (error, saturate) might depend on each caller's needs. The cast fn might need to return an Option or enum to allow callers to decide what to do if it doesn't fit. ("not fit" probably means specific things for the fractional part, too, maybe that can be explicitly ignored by the cast fn, and force callers to care about it themselves?)

This specific sql function probably should error, especially because we don't support the infinite timestamps.

Comment (jkosh44) [reply src/expr/src/scalar/func/impls/float64.rs]: Just updated to use the `ore` cast and return errors if we get out of the timestamp range.

File: src/expr/src/scalar/func/impls/float64.rs [hunk 2]
```diff
@@ -434,25 +435,35 @@ sqlfunc!(
...
-            let secs = f.trunc() as i64;
+            let mut secs = f64_to_i64(f.trunc()).ok_or(EvalError::TimestampOutOfRange)?;
             // NOTE(benesch): PostgreSQL has microsecond precision in its timestamps,
             // while chrono has nanosecond precision. While we normally accept
             // nanosecond precision, here we round to the nearest microsecond because
             // f64s lose quite a bit of accuracy in the nanosecond digits when dealing
             // with common Unix timestamp values (> 1 billion).
-            let nanosecs = ((f.fract() * 1_000_000.0).round() as u32) * 1_000;
-            match NaiveDateTime::from_timestamp_opt(secs as i64, nanosecs as u32) {
+            let mut nanosecs = f64_to_i64(((f.fract() * 1_000_000.0).round()) * 1_000.0)
```
Comment (umanwizard) [inline src/expr/src/scalar/func/impls/float64.rs:451]: I think `nanosecs` can be equal to 1 billion here, if `f` is very close to an integer. Say `f` is 1.999999999, then `secs` will be 1 and `nanosecs` will be 1bn -- should it be 2 and 0, instead?

Comment (jkosh44) [reply src/expr/src/scalar/func/impls/float64.rs]: Updated to address this and added a test too.

**Review by umanwizard — APPROVED** [review]
