### PR TITLE
coord: add integer_datetimes server var

### LINKED ISSUE #4117: Materialize returns wrong date when using prepared statement multiple times
### What version of Materialize are you using?

```
$ materialized -v

```
materialized v0.5.0-dev (b58133f48a2458e8298d169b13fd74cf968ca668)

### How did you install Materialize?

* [x] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [x] macOS release tarball
* [ ] Homebrew tap
* [ ] Built from source

### What was the issue?
When running a query using a prepared statement that returns a timestamp, on the 6th iteration of the query (and all following iterations), the timestamp `2000-01-01 00:00:00` is returned instead of the expected timestamp. 

Note: I have reproduced the issue using a materialize table in the attached zip file but I initially came across this using a materialized view.
[materialize-prepared-statement-issue.zip](https://github.com/MaterializeInc/materialize/files/5152804/materialize-prepared-statement-issue.zip)

### Is the issue reproducible? If so, please provide reproduction instructions.
Yes, see attached zip file. 

### Please attach any applicable log files.
No logs were produced.

### PR DESCRIPTION
**Pull request by mjibson**
This variable has been hardcoded to on since postgres 10. It affects how
jdbc (and perhaps other drivers) interpret binary encoded timestamps. The
encoding we are using corresponds to the hardcoded on setting.

Fixes #4117

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4132)

### CODE REVIEW

File: src/coord/src/session/session.rs [hunk 1]
```diff
@@ -300,6 +315,11 @@ impl Session {
         *self.extra_float_digits.value()
     }
 
+    /// Returns the value of the `integer_datetimes` configuration parameter.
+    pub fn integer_datetimes(&self) -> bool {
```
Comment (ruchirK) [inline src/coord/src/session/session.rs:319]: this function looks unused but that seems to be the pattern in this file. not a big deal either way

**Comment by ruchirK** [comment]
Reviewed everything but the java regression test -- looks good to me!

File: test/lang/java/smoketest/SmokeTest.java [hunk 2]
```diff
@@ -54,4 +60,17 @@ void testParamInt() throws SQLException {
         rs.close();
         stmt.close();
     }
+
+    // Regression for #4117.
+    @Test
+    void testBinaryTimestamp() throws SQLException, ClassNotFoundException {
```
Comment (JLDLaughlin) [inline test/lang/java/smoketest/SmokeTest.java:66]: 🎉

**Comment by benesch** [comment]
Beautiful catch, tyvm!
