### PR TITLE
storage: fix graceful sink restarts

### LINKED ISSUE #17543: panic: u689: [...] cannot serve requested as_of Antichain [...]
Sentry Issue: [DATABASE-BACKEND-2HR](https://materializeinc.sentry.io/issues/3893147949/?referrer=github_integration)

Submitted by @antiguru.

```
panic: u689: s28cf64c2-e1bd-4804-9d54-87990504c352 cannot serve requested as_of Antichain { elements: [1675466370000] }: Since(Antichain { elements: [] })
  File "panicking.rs", line 575, in rust_begin_unwind
  File "lib.rs", line 237, in mz_persist_client::operators::shard_source::shard_source_descs::
  File "lib.rs", line 237, in mz_persist_client::operators::shard_source::shard_source_descs::
  File "async_stream.rs", line 53, in <async_stream::async_stream::AsyncStream<core::result::Result<mz_persist_client::read::ListenEvent<mz_repr::timestamp::Timestamp, mz_persist_client::fetch::LeasedBatchPart<mz_repr::timestamp::Timestamp>>, mz_persist::location::ExternalError>, core::futu...
  File "next.rs", line 32, in <futures_util[44237e77a01ea30]::stream::stream::next::Next<core::pin::Pin<alloc::boxed::Box<async_stream::async_stream::AsyncStream<core::result::Result<mz_persist_client::read::ListenEvent<mz_repr::timestamp::Timestamp, mz_persist_client::fetch::Leased...
...
(41 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by aljoscha**
Before, we were not updating the `as_of` of the `StorageSinkDesc` when internally (internal to the timely cluster/replica) restarting a sink. This lead to "cannot serve requested as_of" panics, which would restart the whole timely cluster/replica.

Now, we go through the async worker to update the `as_of`, similar to how we update the resumption frontier for sources using the same path.

Fixes #17543

NOTE: We still haven't removed the equivalent code from `rehydration.rs`, same as for sources. Though we should do that soon.

### CODE REVIEW

**Review by bkirwi — APPROVED** [review]
I like it! Makes sense to move this decision out of environmentd / rehydration.

File: src/storage/src/storage_state.rs [hunk 1]
```diff
@@ -550,13 +550,24 @@ impl<'w, A: Allocate> Worker<'w, A> {
...
+                internal_cmd_tx
+                    .broadcast(InternalStorageCommand::CreateSinkDataflow(id, sink_desc));
+            }
         }
     }
 
     /// Entry point for applying an internal storage command.
     pub fn handle_internal_storage_command(
         &mut self,
-        internal_cmd_tx: &mut dyn InternalCommandSender,
```
Comment (bkirwi) [inline src/storage/src/storage_state.rs:559]: Maybe we should declare that all future commands go via the async worker? Seems less susceptible to races if all commands take the same path and get processed in order...

File: src/storage/src/storage_state.rs [hunk 2]
```diff
@@ -550,13 +550,24 @@ impl<'w, A: Allocate> Worker<'w, A> {
                     resumption_frontier,
                 });
             }
+            AsyncStorageWorkerResponse::UpdatedSinkDesc(id, sink_desc) => {
+                // NOTE: If we want to share the load of async processing we
+                // have to change `handle_storage_command` and change this
+                // assert.
+                assert!(
```
Comment (antiguru) [inline src/storage/src/storage_state.rs:557]: Nit: `assert_eq`

File: src/storage/src/storage_state/async_storage_worker.rs [hunk 3]
```diff
@@ -100,6 +109,44 @@ impl<T: Timestamp + Lattice + Codec64> AsyncStorageWorker<T> {
...
+                        match res {
+                            Ok(_) => {
+                                // All's well!
+                            }
+                            Err(_err) => {
+                                // Receiver must have hung up.
+                                break;
+                            }
+                        }
+                    }
```
Comment (antiguru) [inline src/storage/src/storage_state/async_storage_worker.rs:121]: Maybe use `if let Err(_) = res { break; }`?

File: src/storage/src/storage_state.rs (hunk 1 above)
Comment (aljoscha) [reply src/storage/src/storage_state.rs:559]: I like that! Though I'd like to get other peoples opinion on that as well. @petrosagg?

File: src/storage/src/storage_state.rs (hunk 2 above)
Comment (aljoscha) [reply src/storage/src/storage_state.rs:557]: 👌

File: src/storage/src/storage_state/async_storage_worker.rs (hunk 3 above)
Comment (aljoscha) [reply src/storage/src/storage_state/async_storage_worker.rs:121]: will do!
