### PR TITLE
adapter: Properly load indexes on system objects

### LINKED ISSUE #16289: Indexes on system tables vanish after environmentd restart
### What version of Materialize are you using?

v0.32.3 (c57b88d08)

### How did you install Materialize?

Materialize Cloud

### What is the issue?

Indexes created on system tables don't seem to fully survive environmentd restarts.

To reproduce on cloud, you need K8s access to your env (e.g. via k9s), so you can kill pods.

1. Connect to Materialize using psql and create an index on a system table.
    ```
    materialize=> create default index on mz_views;
    CREATE INDEX

    materialize=> select * from mz_indexes where id like 'u%';
     id |  oid  |         name         | on_id | cluster_id
    ----+-------+----------------------+-------+------------
     u1 | 20373 | mz_views_primary_idx | s275  | u1
    (1 row)
    ```
2. Force the environmentd pod to restart, e.g., by killing it in k9s.
3. Reconnect with psql and observe that the index you created previously is (almost) gone:
    ```
    materialize=> select * from mz_indexes where id like 'u%';
     id | oid | name | on_id | cluster_id
    ----+-----+------+-------+------------
    (0 rows)

    materialize=> create default index on mz_views;
    ERROR:  catalog item 'mz_views_primary_idx' already exists

    materialize=> select * from mz_objects where name = 'mz_views_primary_idx';
     id | oid | schema_id | name | type
    ----+-----+-----------+------+------
    (0 rows)

    materialize=> drop index mz_views_primary_idx;
    ERROR:  unknown catalog item 'mz_views_primary_idx'
    ```

This can also be reproduce locally, just replace the second step by `kill -9`-ing environmentd and starting it again.

Indexes on user tables are re-created correctly, as far as I can tell.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jkosh44**
Materialize allows users to create indexes on system objects to help speed up debugging queries. Unless otherwise specified, these indexes get created in the ambient database in the same schema as the underlying object.

When loading user objects from the stash, we ignore objects from the ambient schema. This caused Materialize to ignore certain indexes on system objects when it restarted.

This commit updates the user object loading logic to not ignore objects in the ambient database.

Fixes #16289

### Motivation
This PR fixes a recognized bug.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

File: src/adapter/src/catalog/storage.rs [hunk 1]
```diff
@@ -1000,19 +1001,21 @@ impl<'a, S: Append> Transaction<'a, S> {
...
-                Some(id) => id,
-                None => return,
-            };
-            let _database = match databases.get(&DatabaseKey { id: database_id }) {
-                Some(database) => database,
-                None => return,
+            let database_spec = match schema.database_id {
+                Some(id) => {
+                    if databases.get(&DatabaseKey { id }).is_none() {
+                        error!("unknown database id {id}");
```
Comment (mjibson) [inline src/adapter/src/catalog/storage.rs:1007]: Under what circumstances can this error occur?

Comment (jkosh44) [reply src/adapter/src/catalog/storage.rs:1007]: If I had to guess, if this error is hit or the return on line 1002 are hit, then something really bad must have happened.

I just wasn't sure if they were included for a specific reason and therefore didn't want to change the existing behavior because I didn't really understand it.

Should I just turn them both into panics?

Comment (jkosh44) [reply src/adapter/src/catalog/storage.rs:1007]: For example I think this would happen if a database was deleted but an object in the database wasn't deleted, in which the stash is likely corrupted somehow.

Comment (mjibson) [reply src/adapter/src/catalog/storage.rs:1007]: I'm in favor of panicing if this is the case.

Comment (jkosh44) [reply src/adapter/src/catalog/storage.rs]: Done

**Review by mjibson — APPROVED** [review]
