### PR TITLE
Revisit single-time dataflow test

### LINKED ISSUE #19290: Monotonic one-shot `SELECT` feature fails to get activated in serializable mode with source that emits the empty frontier
### What version of Materialize are you using?

v0.55.0-dev (196fa12a5)

### What is the issue?

We have recently introduced a feature to use monotonic operators in one-shot `SELECT`s, gated behind the feature flag `enable_monotonic_oneshot_selects` (part of epic #14442, PR #18546). When the feature flag is enabled, monotonic operator selection for one-shot `SELECT`s works as expected with `transaction_isolation` equal to `strict serializable`. However, the same is not true when `serializable` is chosen and we use a TPC-H load generator source without updates.

To reproduce this behavior, firstly enable the feature flag with `mz_system`:

```sql
sol:materialize vmarcos$ psql -U mz_system -h 127.0.0.1 -p 6877 materialize
psql (14.7 (Homebrew), server 9.5.0)
Type "help" for help.

materialize=> alter system set enable_monotonic_oneshot_selects = on;
ALTER SYSTEM
materialize=> show enable_monotonic_oneshot_selects;
 enable_monotonic_oneshot_selects 
----------------------------------
 on
(1 row)

```

Subsequently, log in normally, create a TPC-H source without updates, and wait for it to hydrate::

```sql
CREATE SOURCE lgtpch FROM LOAD GENERATOR TPCH (SCALE FACTOR 0.1) FOR ALL TABLES WITH (SIZE = '1');
SELECT count(*) > 0 FROM lineitem; -- repeat this statement until it returns true
```

Now, execute the following statements:
```sql
EXPLAIN PHYSICAL PLAN FOR SELECT DISTINCT ON(l_linenumber) l_linenumber, l_discount FROM lineitem ORDER BY l_linenumber, l_orderkey;
SET transaction_isolation = serializable;
EXPLAIN PHYSICAL PLAN FOR SELECT DISTINCT ON(l_linenumber) l_linenumber, l_discount FROM lineitem ORDER BY l_linenumber, l_orderkey;
```
We would expect the output for the two `EXPLAIN` statements above to be the same. However, the following output was observed instead:

```sql
materialize=> EXPLAIN PHYSICAL PLAN FOR SELECT DISTINCT ON(l_linenumber) l_linenumber, l_discount FROM lineitem ORDER BY l_linenumber, l_orderkey;
SET transaction_isolation = serializable;
EXPLAIN PHYSICAL PLAN FOR SELECT DISTINCT ON(l_linenumber) l_linenumber, l_discount FROM lineitem ORDER BY l_linenumber, l_orderkey;
                                    Physical Plan                                    
-------------------------------------------------------------------------------------
 Explained Query:                                                                   +
   Finish order_by=[#3 asc nulls_last, #0 asc nulls_last] output=[#3, #6]           +
     TopK::MonotonicTop1 group_by=[#3] order_by=[#0 asc nulls_last] must_consolidate+
       Get::PassArrangements materialize.public.lineitem                            +
         raw=true                                                                   +
 
(1 row)

SET
                              Physical Plan                               
--------------------------------------------------------------------------
 Explained Query:                                                        +
   Finish order_by=[#3 asc nulls_last, #0 asc nulls_last] output=[#3, #6]+
     TopK::Basic group_by=[#3] order_by=[#0 asc nulls_last] limit=1      +
       Get::PassArrangements materialize.public.lineitem                 +
         raw=true                                                        +
 
(1 row)
```

Above, we observe the use of `TopK::Basic` when `transaction_isolation` is `serializable`.

I could only reproduce this outcome with the TPC-H load generator source so far, so it may be connected to the source emitting the empty frontier when no updates are generated. Here is the output of `EXPLAIN TIMESTAMP` in `strict serializable` and `serializable` modes:

```sql
materialize=> EXPLAIN TIMESTAMP FOR SELECT DISTINCT ON(l_linenumber) l_linenumber, l_discount FROM lineitem ORDER BY l_linenumber, l_orderkey;
                                 Timestamp                                 
---------------------------------------------------------------------------
                 query timestamp: 18446744073709551615                    +
 largest not in advance of upper: 18446744073709551615                    +
                           upper:[]                                       +
                           since:[1684163317000 (2023-05-15 15:08:37.000)]+
         can respond immediately: true                                    +
                        timeline: Some(EpochMilliseconds)                 +
                                                                          +
 source materialize.public.lineitem (u2, storage):                        +
                   read frontier:[1684163317000 (2023-05-15 15:08:37.000)]+
                  write frontier:[]                                       +
 
(1 row)

materialize=> show transaction_isolation;
 transaction_isolation 
-----------------------
 serializable
(1 row)

materialize=> SET transaction_isolation = 'strict serializable';
SET
materialize=> EXPLAIN TIMESTAMP FOR SELECT DISTINCT ON(l_linenumber) l_linenumber, l_discount FROM lineitem ORDER BY l_linenumber, l_orderkey;
                                 Timestamp                                 
---------------------------------------------------------------------------
                 query timestamp: 1684163491134 (2023-05-15 15:11:31.134) +
           oracle read timestamp: 1684163491134 (2023-05-15 15:11:31.134) +
 largest not in advance of upper: 18446744073709551615                    +
                           upper:[]                                       +
                           since:[1684163317000 (2023-05-15 15:08:37.000)]+
         can respond immediately: true                                    +
                        timeline: Some(EpochMilliseconds)                 +
                                                                          +
 source materialize.public.lineitem (u2, storage):                        +
                   read frontier:[1684163317000 (2023-05-15 15:08:37.000)]+
                  write frontier:[]                                       +
 
(1 row)

```

The issue appears to be that `until` cannot be equal to `as_of + 1` when the `as_of` is chosen as the maximum possible value.

### PR DESCRIPTION
**Pull request by vmarcos**
This PR revisits the test that determines whether a dataflow is evaluated over a single time. The test previously did not consider a corner case where the `as_of` would contain the maximum integer value for the timestamp and the `until` would be empty. In this case, it was incorrectly determined that the dataflow was not single-time, as illustrated in #19290. A fix is provided along with a regression test.

Fix #19290. 

### Motivation

  * This PR fixes a recognized bug. https://github.com/MaterializeInc/materialize/issues/19290

### Tips for reviewer

Please consider https://github.com/MaterializeInc/materialize/issues/19290#issuecomment-1599099028. The PR takes the path of keeping the semantics of `until` unchanged, and only patching the single-time test to fix the issue. I would argue that this be of significantly lower effort to derive a fix than changing the semantics of `until`.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20230421_stabilize_monotonic_select.md).
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label. N/A
- [X] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)). N/A
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note): N/A (since monotonic one-shot `SELECT`s are still gated behind a feature flag.

### CODE REVIEW

File: src/compute-client/src/types/dataflows.rs [hunk 1]
```diff
@@ -67,17 +67,18 @@ pub struct DataflowDescription<P, S: 'static = (), T = mz_repr::Timestamp> {
...
-            }
-            _ => false,
-        }
+        let Some(as_of) = self.as_of.as_ref() else { return false; };
+        !as_of.is_empty()
+            && as_of
+                .as_option()
+                .and_then(|as_of| as_of.checked_add(1))
+                .as_ref()
+                == self.until.as_option()
```
Comment (teskje) [inline src/compute-client/src/types/dataflows.rs:81]: Is the `!as_of.is_empty()` check correct? If `as_of` is empty that means we will always ever only flow as single time through the dataflow, so shouldn't we return `true` in that case?

Assuming my reasoning checks out, I'd like to propose this version for improved readability:
```rust
        let Some(as_of) = self.as_of.as_ref() else { return false };
        let as_of_plus_one = as_of.as_option().and_then(|t| t.checked_add(1));
        as_of_plus_one.as_ref() == self.until.as_option()
```

**Review by teskje — APPROVED** [review]
Thanks!

File: src/compute-client/src/types/dataflows.rs (hunk 1 above)
Comment (vmarcos) [reply src/compute-client/src/types/dataflows.rs:81]: Recording here a discussion through another channel: A pTVC is defined in the interval of `[since, upper)`. My understanding when writing the condition was that when we spin a dataflow, we’d like it to process pTVCs that are valid in the interval `[as_of, until)`. So if the `as_of` is empty (i.e., the top element of the frontier poset), we can only have an interval with no times at all, not a single time.

This understanding can be checked by looking at the `as_of` that is picked when we query a constant collection:
```sql
materialize=> explain timestamp for select * from (values(1));
                       Timestamp                       
-------------------------------------------------------
                 query timestamp: 18446744073709551615+
 largest not in advance of upper: 18446744073709551615+
                           upper:[]                   +
                           since:[            0]      +
         can respond immediately: true                +
                        timeline: None                +
 
(1 row)

Time: 9.593 ms
```
We see that `u64::MAX` is selected for the query timestamp, not empty, matching the understanding above.
