### PR TITLE
sql: pack apd datums into rows using raw parts + the reverse

### LINKED ISSUE #6877: apd: wrong result with UNION, EXCEPT, DISTINCT, GROUP BY
### What version of Materialize are you using?

```
v0.7.4-dev (519d7ab07)
```

### What was the issue?

The ```UNION EXCEPT``` and the rest of the operations does not work properly with the APD data type.

### Is the issue reproducible? If so, please provide reproduction instructions.

```
CREATE TABLE insertions (f1 APD) ;
CREATE TABLE deletions (f1 APD) ;
INSERT INTO insertions VALUES ('1'::APD);
INSERT INTO deletions VALUES ('1'::APD);
SELECT * FROM insertions EXCEPT ALL SELECT * FROM deletions;

 f1 
----
 1 <- wrong, no rows should have been returned.
(1 row)
```

```
materialize=> 
materialize=> DROP TABLE IF EXISTS t1;
DROP TABLE
materialize=> CREATE TABLE t1 (f1 APD);
CREATE TABLE
materialize=> INSERT INTO t1 VALUES ('1'::APD);
INSERT 0 1
materialize=> INSERT INTO t1 VALUES ('1'::APD);
INSERT 0 1
materialize=> SELECT DISTINCT f1 FROM t1;
 f1 
----
 1
 1 <- wrong, duplicates should have been removed
(2 rows)
```

### LINKED ISSUE #6883: apd: packed representation should be smaller
The new APD type does not pack itself into a `Row` as tightly as it could. We should change the implementation of its arm in [`push_datum`](https://github.com/MaterializeInc/materialize/blob/e78101947cc570fe772aca6621a5e2071fb7ffc9/src/repr/src/row.rs#L538) 
to use [`to_raw_parts`](https://docs.rs/dec/0.4.0/dec/struct.Decimal.html#method.to_raw_parts) and only write out the elements in `lsu` that are actually present according to the `digits` field. We can also use a much smaller type for `exponent` and `digits` (probably `u8`). That should cut down substantially on memory usage in arrangements. We'd need to add another `from_raw_parts` API, I think, but that makes sense to have in `rust-dec` independently of this request!

This would have the effect of fixing #6877, although there's underlying memory unsafety there too, the fixing of which _also_ fixes #6877. The point is both of these issues are worth fixing independently of #6877, and fixing either will also fix #6877!

(For context: `Row` is a low-level type that is meant to use as little memory as possible, and it's therefore ok to use tricks to pack the data as tightly as possible.)

### PR DESCRIPTION
**Pull request by sploiselle**
Fixes #6877, #6912
Closes #6883

### CODE REVIEW

File: src/repr/src/row.rs [hunk 1]
```diff
@@ -533,9 +546,29 @@ fn push_datum<T: Bytes>(data: &mut T, datum: Datum) {
...
+            // There should be no unaligned elements in the prefix or suffix.
+            assert!(prefix.is_empty() && suffix.is_empty());
             data.push(Tag::APD as u8);
-            push_copy!(data, n, OrderedDecimal<Apd>);
+            // Digits cannot exceed 39
+            push_copy!(data, u8::try_from(digits).unwrap(), u8);
+            // Exponent cannot exceed +/-39
+            push_copy!(data, i8::try_from(exponent).unwrap(), i8);
+            data.push(bits);
+            push_untagged_bytes(data, &lsu);
```
Comment (benesch) [inline src/repr/src/row.rs:571]: Since the length of LSU is entirely determined by `digits`, it’ll be better just to blat down the LSU bytes directly here. (`push_untagged_bytes` will unnecessarily write the bytes down again with an 8 byte length prefix, if I’m reading it right.)

File: src/repr/src/row.rs [hunk 2]
```diff
@@ -375,8 +376,20 @@ unsafe fn read_datum<'a>(data: &'a [u8], offset: &mut usize) -> Datum<'a> {
...
-            let n = read_copy::<OrderedDecimal<Apd>>(data, offset);
-            Datum::APD(n)
+            let digits = read_copy::<u8>(data, offset);
+            let exponent = read_copy::<i8>(data, offset);
+            let bits = read_copy::<u8>(data, offset);
+            let lsu = read_untagged_bytes(data, offset);
+            // SAFETY: `lsu`'s data originated as a `&[u16]`, before being
+            // transmuted into a `&[u8]`; this transmute returns it to its
+            // original form.
+            let (prefix, lsu, suffix) = lsu.align_to::<u16>();
```
Comment (benesch) [inline src/repr/src/row.rs:386]: This seems a little fishy to me. I think it’s possible that LSU gets written into a row in a way that it is not aligned to a two byte boundary. (E.g. if written to a row with a one byte string before the decimal.) It might actually be easiest if to_raw_parts and from_raw_parts dealt in u8 slices instead of u16 slices because that’s a very natural point for the copy into a properly aligned type to occur.

File: src/repr/src/row.rs [hunk 3]
```diff
@@ -375,8 +376,20 @@ unsafe fn read_datum<'a>(data: &'a [u8], offset: &mut usize) -> Datum<'a> {
...
+            // LSU should have essentially ceil(digits / 3) elements.
+            assert!(lsu.len() == (usize::try_from(digits).unwrap() + 2) / 3);
```
Comment (philip-stoev) [inline src/repr/src/row.rs:388]: I am afraid I am hitting this assertion:

```
CREATE TABLE t1 (f1 APD) ;
SELECT COUNT(*)::TEXT::APD AS f1 FROM t1;
```

```
materialized v0.7.4-dev (a312dde63) listening on 0.0.0.0:6875...
2021-06-07T06:36:44.848484Z ERROR panic: assertion failed: lsu.len() == (usize::try_from(digits).unwrap() + 2) / 3
thread: timely:work-0
location: src/repr/src/row.rs:388:13
version: 0.7.4-dev (a312dde635788108186d4407d1ab12fb261fb659)
backtrace:
   0: materialized::handle_panic
             at src/materialized/src/bin/materialized/main.rs:710:21
   1: core::ops::function::Fn::call
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:70:5
   2: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:495:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   5: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   6: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   7: core::panicking::panic
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:50:5
   8: repr::row::read_datum
             at src/repr/src/row.rs:388:13
   9: <repr::row::DatumListIter as core::iter::traits::iterator::Iterator>::next
             at src/repr/src/row.rs:1121:27
      core::iter::traits::iterator::Iterator::fold
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/iter/traits/iterator.rs:2123:29
      core::iter::traits::iterator::Iterator::count
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/iter/traits/iterator.rs:251:9
      repr::row::Row::unpack
             at src/repr/src/row.rs:765:19
  10: dataflow::render::<impl dataflow::render::context::Context<G,expr::relation::MirRelationExpr,repr::row::Row,u64>>::ensure_rendered::{{closure}}
             at src/dataflow/src/render/mod.rs:602:46
      differential_dataflow::collection::Collection<G,D,R>::map::{{closure}}
```

**Review by philip-stoev — APPROVED** [review]
Apart from the assertion, this looks good with randomized workloads that involve a lot of SUM[DISTINCT] as well as DISTINCT/EXCEPT/UNION[ALL].

- no other issues regarding trailing zeroes
- all instances of result differences from Postgres could be attributed to loss of precision inherent to the bounded scale available . This was sometimes seen in chained SUM operations where some values were really large and others really small. I assume this is unavoidable and expected;
- SUM() in the face of retractions appears to work as expected

File: src/repr/src/row.rs (hunk 1 above)
Comment (sploiselle) [reply src/repr/src/row.rs]: Implemented this suggestion

File: src/repr/src/row.rs (hunk 2 above)
Comment (sploiselle) [reply src/repr/src/row.rs]: believe I fixed this by virtue of MaterializeInc/rust-dec#42 + other minor changes

File: src/repr/src/row.rs (hunk 3 above)
Comment (sploiselle) [reply src/repr/src/row.rs]: This PR now includes MaterializeInc/rust-dec#42, which obviated the need for this assertion, but seems to have resolved the underlying issue that caused this panic

**Comment by sploiselle** [comment]
@philip-stoev This last iteration was a significant change to the pack/unpack logic here; can I get you to re-run your test suite? I'll work on rewriting the `apd-sum.td` test to use the `EXCEPT` clauses you've been using, but didn't want that to hold up merging/reviewing the PR.

File: test/testdrive/apd-sum.td [hunk 4]
```diff
@@ -232,28 +232,30 @@ $ file-append path=scaled_values.csv
 > CREATE MATERIALIZED VIEW apd_scaled_values_sum AS
     SELECT sum(a)::apd(39, 3) AS sum_a FROM apd_scaled_values;
 
+# Even though the sum is supposed to be rescaled to 3 decimals, the reudction
+# before packing the values into a row trims the trailing zeroes. However, the # rescale still works because the values are rounded to 3 units of scale.
```
Comment (benesch) [inline test/testdrive/apd-sum.td:236]: super minor but this comment looks like it got a bit misformatted; also "reudction"

**Review by benesch — APPROVED** [review]
This looks so good!

File: test/testdrive/apd-sum.td (hunk 4 above)
Comment (sploiselle) [reply test/testdrive/apd-sum.td:236]: oh derp, ty--on a different PC today and fighting with vscode

**Comment by sploiselle** [comment]
@philip-stoev rewrote `apd-sum.td` to use "retractions" in this PR, so this is all ready

**Review by philip-stoev — APPROVED** [review]
Thank you, it all looks good. The assertion is now gone. Thank you for the test!
