### PR TITLE
interchange: don't crash on invalid Avro field/record names

### LINKED ISSUE #16372: Avro schema generation can create an invalid schema
### What version of Materialize are you using?

v0.32.3

### How did you install Materialize?

Materialize Cloud

### What is the issue?

In the log lines below, `<name>` starts with a number, which points to a `CREATE SINK` that spits out a warning, then crashes envd. Validation here should not crash, and we should not make it to avro parsing before spitting out an error to user about naming requirements.

### Relevant log output

```source
2022-11-29T15:30:59.756466Z  WARN mz_sql::plan::statement::ddl: Verification of upsert key disabled for sink '<sink_name>' via 'NOT ENFORCED'. This is potentially dangerous and can lead to crashing materialize when the specified key is not in fact a unique key of the sinked view.
thread 'coordinator' panicked at 'valid schema constructed: ParseSchema(ParseSchemaError("Invalid name. Must start with [A-Za-z_] and subsequently only contain [A-Za-z0-9_]. Found: <name>"))', src/interchange/src/avro/encode.rs:138:56
```

### PR DESCRIPTION
**Pull request by benesch**
Not super sure who owns this code right now, so requested review from @umanwizard (because Avro) and @bkirwi (because sinks).

----

When creating an Avro schema for a Kafka sink, we were using user-supplied field and record names, but not validating that they were actually valid for use as a name in an Avro schema, resulting in a panic.

This commit makes two changes:

  * Column names that are not directly usable as field names in an Avro record are munged to be valid. Leading numbers are prefixed with an underscore, and any other invalid characters are replaced with an underscore. If this results in duplicate names, the names are suffixed with an incrementing number, as in "foo", "foo1", "foo2".

  * The AVRO KEY FULLNAME and AVRO VALUE FULLNAME options are gracefully rejected if they are not directly valid as Avro names.

Fix #16372.

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - Gracefully return an error rather than crashing if the value of the `AVRO KEY FULLNAME` or `AVRO VALUE FULLNAME` option in an Avro-formatted Kafka sink is not a valid Avro name.

### CODE REVIEW

File: src/avro/src/schema.rs [hunk 1]
```diff
@@ -579,18 +580,52 @@ impl fmt::Debug for FullName {
...
-    /// No `namespace` nor `aliases` will be defined.
-    pub fn new(name: &str) -> Name {
-        Name {
-            name: name.to_owned(),
-            namespace: None,
-            aliases: None,
+    /// Reports whether the given string is a valid Avro name.
+    pub fn is_valid(name: &str) -> bool {
+        static MATCHER: Lazy<Regex> =
+            Lazy::new(|| Regex::new(r"(^[A-Za-z_][A-Za-z0-9_]*)$").unwrap());
```
Comment (guswynn) [inline src/avro/src/schema.rs:586]: if there is avro docs that describe this regex, it would be great to link to them here!

File: src/avro/src/schema.rs [hunk 2]
```diff
@@ -579,18 +580,52 @@ impl fmt::Debug for FullName {
...
+                )).into())
+            }
+        }
+    }
+
+    /// Rewrites `name` to be valid.
+    ///
+    /// Any non alphanumeric characters are replaced with underscores. If the
+    /// name begins with a number, it is prefixed with `_`.
+    pub fn make_valid(name: &str) -> String {
```
Comment (guswynn) [inline src/avro/src/schema.rs:607]: The way we munge these should be documented in the user-facing avro format docs!

File: src/avro/src/schema.rs [hunk 3]
```diff
@@ -579,18 +580,52 @@ impl fmt::Debug for FullName {
...
+            }
+            _ => out.push('_'),
+        }
+        for ch in chars {
+            match ch {
+                '0'..='9' | 'a'..='z' | 'A'..='Z' => out.push(ch),
+                _ => out.push('_'),
+            }
         }
+        out
```
Comment (guswynn) [inline src/avro/src/schema.rs:624]:
```suggestion
        // assert our munging worked
		Self::validate(&out).unwrap();
        out
```

File: src/avro/src/schema.rs [hunk 4]
```diff
@@ -579,18 +580,52 @@ impl fmt::Debug for FullName {
...
+            Some(ch @ '0'..='9') => {
+                out.push('_');
+                out.push(ch);
+            }
+            _ => out.push('_'),
+        }
+        for ch in chars {
+            match ch {
+                '0'..='9' | 'a'..='z' | 'A'..='Z' => out.push(ch),
+                _ => out.push('_'),
```
Comment (guswynn) [inline src/avro/src/schema.rs:621]: we assert later on that these names are still unique right?

**Review by guswynn — COMMENTED** [review]
I have a few nits, but @umanwizard probably needs to look at this!

File: src/avro/src/schema.rs (hunk 1 above)
Comment (benesch) [reply src/avro/src/schema.rs:588]: Done.

File: src/avro/src/schema.rs (hunk 3 above)
Comment (benesch) [reply src/avro/src/schema.rs:633]: Done, via a debug assert.

File: src/avro/src/schema.rs (hunk 4 above)
Comment (benesch) [reply src/avro/src/schema.rs:626]: Er, we don't assert, but we restore the uniqueness by appending `1`, `2`, and so on.

**Review by umanwizard — APPROVED** [review]
Thanks, good catch!

File: src/avro/src/schema.rs (hunk 2 above)
Comment (benesch) [reply src/avro/src/schema.rs]: Agreed, but we don't document _anything_ about the SQL -> Avro conversion right now, so there's nowhere good to put it. :/
