### PR TITLE
*: introduce halting as a softer way to panic

### LINKED ISSUE #15771: mz_compute::server::Worker<T>::reconcile panic: assertion failed: `(left == right)`
Sentry Issue: [DATABASE-BACKEND-140](https://sentry.io/organizations/materializeinc/issues/3693430872/?referrer=github_integration)

```
panic: assertion failed: `(left == right)`
  left: `Some(InstanceConfig { replica_id: 3, logging: Some(LoggingConfig { interval_ns: 1000000000, active_logs: {Timely(Operates): System(362), Timely(Channels): System(361), Timely(Elapsed): System(371), Timely(Histogram): System(372), Timely(Addresses): System(363), Timely(Parks): System(373), Timely(MessagesSent): System(368), Timely(MessagesReceived): System(367), Timely(Reachability): System(364), Differential(ArrangementBatches): System(359), Differential(ArrangementRecords): System(360), Differential(Sharing): System(358), Compute(DataflowCurrent): System(365), Compute(DataflowDependency): System(366), Compute(FrontierCurrent): System(374), Compute(PeekCurrent): System(369), Compute(PeekDuration): System(370), Compute(FrontierDelay): System(376), Compute(SourceFrontierCurrent): System(375)}, log_logging: false, sink_logs: {Timely(Operates): (System(468), CollectionMetadata { persist_location: PersistLocation { blob_uri: "s3://mzcloud-production-us-east-1-persistence-ca68ca6c/system:serviceaccount:environment-04917b47-fc31-489e-baf9-008892ab474a-0:environment-04917b47-fc31-489e-baf9-008892ab474a-0", consensus_uri: "postgres://environment_04917b47fc31489ebaf9008892ab474a0:YbB6aQsql9LoD0rP2bbnu9ST2TyyVZqZ@pa-us-east-1-0-763.aws-us-east-1.cockroachlabs.cloud:26257/environment_04917b47fc31489ebaf9008892ab474a0?options=--search_path=consensus" }, remap_shard: ShardId(12aee2d1-bf10-4c84-97fb-8f10cf95013e), data_shard: ShardId(758fb0a9-e747-4574-b1fc-5a8f15601c0a), status_shard: None }), Timely(Channels): (System(469), CollectionMetadata { persist_location: PersistLocation { blob_uri: "s3://mzcloud-production-us-east-1-persistence-ca68ca6c/system:serviceaccount:environment-04917b47-fc31-489e-baf9-008892ab474a-0:environment-04917b47-fc31-489e-baf9-008892ab474a-0", consensus_uri: "postgres://environment_04917b47fc31489ebaf9008892ab474a0:YbB6aQsql9LoD0rP2bbnu9ST2TyyVZqZ@pa-us-east-1-0-763.aws-us-east-1.cockroachlabs.cloud:26257/environment_04917b47fc31489ebaf9008892ab474a0?options=--search_path=consensus" }, remap_shard: ShardId(8d1d62d4-b2c0-4965-b994-0f26222f3d81), data_shard: ShardId(c6500d89-1aba-4031-bbf8-8c8ca25b988f), status_shard: None }), Timely(Elapsed): (System(470), CollectionMetadata { persist_location: PersistLocation { blob_uri: "s3://mzcloud-production-us-east-1-persistence-ca68ca6c/system:serviceaccount:environment-04917b47-fc31-489e-baf9-008892ab474a-0:environment-04917b47-fc31-489e-baf9-008892ab474a-0", consensus_uri: "postgres://environment_04917b47fc31489ebaf9008892ab474a0:YbB6aQsql9LoD0rP2bbnu9ST2TyyVZqZ@pa-us-east-1-0-763.aws-us-east-1.cockroachlabs.cloud:26257/environment_04917b47fc31489ebaf9008892ab474a0?options=--search_path=consensus" }, remap_shard: ShardId(26bb8663-9e4a-40b2-94f5-793d62580c24), data_shard: ShardId(780c46be-2dc2-4570-a658-8a8d4786ec3b), status_shard: None }), Timely(Histogram): (System(471), CollectionMetadata { persist_location: PersistLocation { blob_uri: "s3://mzcloud-production-us-east-1-persistence-ca68ca6c/system:serviceaccount:environment-04917b47-fc31-489e-baf9-008892ab474a-0:environment-04917b47-fc31-489e-baf9-008892ab474a-0", consensus_uri: "postgres://environment_04917b47fc31489ebaf9008892ab474a0:YbB6aQsql9LoD0rP2bbnu9ST2TyyVZqZ@pa-us-east-1-0-763.aws-us-east-1.cockroachlabs.cloud:26257/environment_04917b47fc31489ebaf9008892ab474a0?options=--search_path=consensus" }, remap_shard: ShardId(08c52546-fd66-42c6-8710-5a2766a40cfe), data_shard: ShardId(6d8bb714-59e5-4e92-a2f6-582d75e1d5e0), status_shard: None }), Timely(Addresses): (System(472), CollectionMetadata { persist_location: PersistLocation { blob_uri: "s3://mzcloud-production-us-east-1-persistence-ca68ca6c/system:serviceaccount:environment-04917b47-fc31-489e-baf9-008892ab474a-0:environment-04917b47-fc31-489e-baf9-008892ab474a-0", consensus_uri: "postgres://environment_04917b47fc31489ebaf9008892ab474a0:YbB6aQsql9LoD0rP2bbnu9ST2TyyVZqZ@pa-us-east-1-0-763.aws-us-east-1.cockroachlabs.cloud:26257/environment_04917b47fc31489ebaf9008892ab474a0?options=--search_path=consensus" }, remap_shard: ShardId(3cf5a786-663b-4e16-8eba-0cf381097e68), data_shard: ShardId(8387c087-4c04-42bc-9360-0383dee553e3), status_shard: None }), Timely(Parks): (System(473), CollectionMetadata { persist_location: PersistLocation { blob_uri: "s3://mzcloud-production-us-east-1-persistence-ca68ca6c/system:serviceaccount:environment-04917b47-fc31-489e-baf9-008892ab474a-0:environment-04917b47-fc31-489e-baf9-008892ab474a-0", consensus_uri: "postgres://environment_04917b47fc31489ebaf9008892ab474a0:YbB6aQsql9LoD0rP2bbnu9ST2TyyVZqZ@pa-us-east-1-0-763.aws-us-east-1.cockroachlabs.cloud:26257/environment_04917b47fc31489ebaf9008892ab474a0?options=--search_path=consensus" }, remap_shard: ShardId(27d5cc2f-0029-4ec4-b848-5c3eecaf889e), data_shard: ShardId(655c317a-ad64-4b35-b224-6c7dc154d12d), status_shard: None }), Timely(MessagesSent): (System(474), CollectionMetadata { persist_location: PersistLocation { blob_uri: "s3://mzcloud-production-us-east-1-persistence-ca68ca6c/system:serviceaccount:environment-04917b47-fc31-489e-baf9-008892ab474a-0:environment-04917b47-fc31-489e-baf9-008892ab474a-0", consensus_uri: "postgres://environment_04917b47fc31489ebaf9008892ab474a0:YbB6aQsql9LoD0rP2bbnu9ST2TyyVZqZ@pa-us-east-1-0-763.aws-us-east-1.cockroachlabs.cloud:26257/environment_04917b47fc31489ebaf9008892ab474a0?options=--search_path=consensus" }, remap_shard: ShardId(037ae484-3d96-4b66-bc31-537c9336d754), data_shard: ShardId(61d6e9c5-2170-48cc-ac23-0858bd256743), status_shard: None }), Timely(MessagesReceived): (System(475), CollectionMetadata { persist_location: PersistLocation { blob_uri: "s3://mzcloud-production-us-east-1-persistence-ca68ca6c/system:serviceaccount:environment-04917b47-fc31-489e-baf9-008892ab474a-0:environment-04917b47-fc31-489e-baf9-008892ab474a-0", consensus_uri: "postgres://environment_04917b47fc31489ebaf9008892ab474a0:YbB6aQsql9LoD0rP2bbnu9ST2TyyVZqZ@pa-us-east-1-0-763.aws-us-east-1.cockroachlabs.cloud:26257/environment_04917b47fc31489ebaf9008892ab474a0?options=--search_path=consensus" }, remap_shard: ShardId(759e7484-1d27-45ae-8349-a8cd6a24ea8a), data_shard: ShardId(f762ebb5-2ddc-4216-9682-11e558acb7b9), status_shard: None }), Timely(Reachability): (System(476), CollectionMetadata { persist_location: PersistLocation { blob_uri: "s3://mzcloud-production-us-east-1-persistence-ca68ca6c/system:serviceaccount:environment-04917b47-fc31-489e-baf9-008892ab474a-0:environment-04917b47-fc31-489e-baf9-008892ab474a-0", consensus_uri: "postgres://environment_04917b47fc31489ebaf9008892ab474a0:YbB6aQsql9LoD0rP2bbnu9ST2TyyVZqZ@pa-us-east-1-0-763.aws-us-east-1.cockroachlabs.cloud:26257/environment_04917b47fc31489ebaf9008892ab474a0?options=--search_path=consensus" }, remap_shard: ShardId(a32ca926-f0ca-4727-a705-3278b62b81ce), data_shard: ShardId(3cd99abf-466f-45dc-9979-a9cd37097f8e), status_shard: None }), Differential(ArrangementBatches): (System(477), CollectionMetadata { persist_location: PersistLocation { blob_uri: "s3://mzcloud-production-us-east-1-persistence-ca68ca6c/system:serviceaccount:environment-04917b47-fc31-489e-baf9-008892ab474a-0:environment-04917b47-fc31-489e-baf9-008892ab474a-0", consensus_uri: "postgres://environment_04917b47fc31489ebaf9008892ab474a0:YbB6aQsql9LoD0rP2bbnu9ST2TyyVZqZ@pa-us-east-1-0-763.aws-us-east-1.cockroachlabs.cloud:26257/environment_04917b47fc31489ebaf9008892ab474a0?options=--search_path=consensus" }, remap_shard: ShardId(f42840e5-eaaf-4136-b550-46bf7f182e67), data_shard: ShardId(9ed9ee2f-4425-4978-9339-ddc74c2f16e9), status_shard: None }), Differential(ArrangementRecords): (System(478), CollectionMetadata { persist_location: PersistLocation { blob_uri: "s3://mzcloud-production-us-east-1-persistence-ca68ca6c/system:serviceaccount:environment-04917b47-fc31-489e-baf9-008892ab474a-0:environment-04917b47-fc31-489e-baf9-008892ab474a-0", consensus_uri: "postgres://environment_04917b47fc31489ebaf9008892ab474a0:YbB6aQsql9LoD0rP2bbnu9ST2TyyVZqZ@pa-us-east-1-0-763.aws-us-east-1.cockroachlabs.cloud:26257/environment_04917b47fc31489ebaf9008892ab474a0?options=--search_path=consensus" }, remap_shard: ShardId(1efdf89e-e972-...
  File "panicking.rs", line 584, in rust_begin_unwind
  File "server.rs", line 747, in mz_compute::server::Worker<T>::reconcile
  File "server.rs", line 498, in mz_compute::server::Worker<T>::run_client
  File "server.rs", line 484, in mz_compute::server::Worker<T>::setup_channel_and_run_client
  File "server.rs", line 349, in mz_compute::server::Worker<T>::run
...
(21 additional frame(s) were not displayed)
```

### LINKED ISSUE #15772: mz_storage::storage_state::Worker<T>::reconcile panic: assertion failed: `(left == right)`
Sentry Issue: [DATABASE-BACKEND-PM](https://sentry.io/organizations/materializeinc/issues/3690241293/?referrer=github_integration)

```
panic: assertion failed: `(left == right)`
  left: `IngestionDescription { desc: SourceDesc { connection: Kafka(KafkaSourceConnection { connection: KafkaConnection { brokers: ["0.rp-05be438.1c7ee32.byoc.vectorized.cloud:32336"], progress_topic: None, security: Some(Sasl(SaslConfig { mechanisms: "SCRAM-SHA-256", username: Secret(User(29)), password: User(30), tls_root_cert: Some(Secret(User(31))) })) }, connection_id: User(35), options: {"isolation.level": String("read_committed"), "statistics.interval.ms": String("1000")}, topic: "external.commerce.sales.order", start_offsets: {}, group_id_prefix: None, environment_id: "aws-us-east-1-7fa40647-423c-4156-ab1d-04f1b580e307-0", include_timestamp: None, include_partition: None, include_topic: None, include_offset: None, include_headers: None }), encoding: KeyValue { key: DataEncoding { force_nullable_columns: false, inner: Bytes }, value: DataEncoding { force_nullable_columns: false, inner: Bytes } }, envelope: Upsert(UpsertEnvelope { source_arity: 2, style: Default(Named("key")), key_indices: [0] }), metadata_columns: [], timestamp_interval: 1s }, source_imports: {}, ingestion_metadata: CollectionMetadata { persist_location: PersistLocation { blob_uri: "s3://mzcloud-production-us-east-1-persistence-ca68ca6c/system:serviceaccount:environment-7fa40647-423c-4156-ab1d-04f1b580e307-0:environment-7fa40647-423c-4156-ab1d-04f1b580e307-0", consensus_uri: "postgres://environment_7fa40647423c4156ab1d04f1b580e3070:0BikJCHahka2Ciy3nxuRrHPN8cVkaMJD@pa-us-east-1-0-763.aws-us-east-1.cockroachlabs.cloud:26257/environment_7fa40647423c4156ab1d04f1b580e3070?options=--search_path=consensus" }, remap_shard: ShardId(137764c0-e66b-465a-b860-0e150838f613), data_shard: ShardId(55282de2-6235-4d91-9229-d3e62939c592), status_shard: None }, source_exports: {User(77): SourceExport { output_index: 0, storage_metadata: CollectionMetadata { persist_location: PersistLocation { blob_uri: "s3://mzcloud-production-us-east-1-persistence-ca68ca6c/system:serviceaccount:environment-7fa40647-423c-4156-ab1d-04f1b580e307-0:environment-7fa40647-423c-4156-ab1d-04f1b580e307-0", consensus_uri: "postgres://environment_7fa40647423c4156ab1d04f1b580e3070:0BikJCHahka2Ciy3nxuRrHPN8cVkaMJD@pa-us-east-1-0-763.aws-us-east-1.cockroachlabs.cloud:26257/environment_7fa40647423c4156ab1d04f1b580e3070?options=--search_path=consensus" }, remap_shard: ShardId(137764c0-e66b-465a-b860-0e150838f613), data_shard: ShardId(55282de2-6235-4d91-9229-d3e62939c592), status_shard: None } }}, host_config: Managed { allocation: StorageHostResourceAllocation { memory_limit: Some(MemoryLimit(17.2 GB)), cpu_limit: Some(CpuLimit { millicpus: 2000 }), workers: 1 }, size: "xsmall" } }`,
 right: `IngestionDescription { desc: SourceDesc { connection: Kafka(KafkaSourceConnection { connection: KafkaConnection { brokers: ["0.rp-05be438.1c7ee32.byoc.vectorized.cloud:32336"], progress_topic: None, security: Some(Sasl(SaslConfig { mechanisms: "SCRAM-SHA-256", username: Secret(User(29)), password: User(30), tls_root_cert: Some(Secret(User(31))) })) }, connection_id: User(35), options: {"isolation.level": String("read_committed"), "statistics.interval.ms": String("1000")}, topic: "external.commerce.sales.order", start_offsets: {}, group_id_prefix: None, environment_id: "aws-us-east-1-7fa40647-423c-4156-ab1d-04f1b580e307-0", include_timestamp: None, include_partition: None, include_topic: None, include_offset: None, include_headers: None }), encoding: KeyValue { key: DataEncoding { force_nullable_columns: false, inner: Bytes }, value: DataEncoding { force_nullable_columns: false, inner: Bytes } }, envelope: Upsert(UpsertEnvelope { source_arity: 2, style: Default(Named("key")), key_indices: [0] }), metadata_columns: [], timestamp_interval: 1s }, source_imports: {}, ingestion_metadata: CollectionMetadata { persist_location: PersistLocation { blob_uri: "s3://mzcloud-production-us-east-1-persistence-ca68ca6c/system:serviceaccount:environment-7fa40647-423c-4156-ab1d-04f1b580e307-0:environment-7fa40647-423c-4156-ab1d-04f1b580e307-0", consensus_uri: "postgres://environment_7fa40647423c4156ab1d04f1b580e3070:0BikJCHahka2Ciy3nxuRrHPN8cVkaMJD@pa-us-east-1-0-763.aws-us-east-1.cockroachlabs.cloud:26257/environment_7fa40647423c4156ab1d04f1b580e3070?options=--search_path=consensus" }, remap_shard: ShardId(137764c0-e66b-465a-b860-0e150838f613), data_shard: ShardId(55282de2-6235-4d91-9229-d3e62939c592), status_shard: None }, source_exports: {User(77): SourceExport { output_index: 0, storage_metadata: CollectionMetadata { persist_location: PersistLocation { blob_uri: "s3://mzcloud-production-us-east-1-persistence-ca68ca6c/system:serviceaccount:environment-7fa40647-423c-4156-ab1d-04f1b580e307-0:environment-7fa40647-423c-4156-ab1d-04f1b580e307-0", consensus_uri: "postgres://environment_7fa40647423c4156ab1d04f1b580e3070:0BikJCHahka2Ciy3nxuRrHPN8cVkaMJD@pa-us-east-1-0-763.aws-us-east-1.cockroachlabs.cloud:26257/environment_7fa40647423c4156ab1d04f1b580e3070?options=--search_path=consensus" }, remap_shard: ShardId(137764c0-e66b-465a-b860-0e150838f613), data_shard: ShardId(55282de2-6235-4d91-9229-d3e62939c592), status_shard: None } }}, host_config: Managed { allocation: StorageHostResourceAllocation { memory_limit: Some(MemoryLimit(257.7 GB)), cpu_limit: Some(CpuLimit { millicpus: 30000 }), workers: 1 }, size: "large" } }`: New ingestion with same ID User(77)
  File "panicking.rs", line 584, in rust_begin_unwind
  File "storage_state.rs", line 334, in mz_storage::storage_state::Worker<T>::reconcile::{{closure}}
  File "storage_state.rs", line 328, in mz_storage::storage_state::Worker<T>::reconcile
  File "storage_state.rs", line 118, in mz_storage::storage_state::Worker<T>::run_client
  File "storage_state.rs", line 110, in mz_storage::storage_state::Worker<T>::run
...
(23 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by benesch**
Introduce the concept of "halting", which a middle ground between gracefully exiting a process and panicking. A halt indicates an error has occurred that is severe enough to require shutting down the process, but not severe enough to be considered a crash. Halts are not intended to be reported to error tracking tools (e.g., Sentry).

There are two common classes of errors that trigger a halt:

  * An error that indicates a new process has taken over (e.g., an error indicating that the process's leader epoch has expired).

  * A retriable error where the retry logic is too difficult to write correctly. Sometimes the easiest way to retry an error is to tear down the process and allow a new process to start from scratch.

Halts are initiated via a new `halt!` macro in the `ore` crate.  Several expected panics in the `persist`, `compute`, `storage`, and `adapter` crates are downgraded to `halt`s, so that they don't unnecessarily accumulate in Sentry.

Fix #15771.
Fix #15772.

### Motivation

  * This PR adds a known-desirable feature.

  Part of the stability sprint, to make it easier to find unexpected panics in Sentry.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - n/a

### CODE REVIEW

File: src/ore/src/process.rs [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+///   * A retriable error where the retry logic is too difficult to write
+///     correctly. Sometimes the easiest way to retry an error is to tear down
+///     the process and allow a new process to start from scratch.
+///
+#[cfg_attr(nightly_doc_features, doc(cfg(feature = "tracing")))]
+#[cfg(feature = "tracing")]
+#[macro_export]
+macro_rules! halt {
+    ($($arg:expr),* $(,)?) => {{
+        $crate::__private::tracing::warn!("halting process: {}", format!($($arg),*));
```
Comment (guswynn) [inline src/ore/src/process.rs:42]: in the interest of not regressing, can we capture a `Backtrace` (https://docs.rs/backtrace/latest/backtrace/struct.Backtrace.html#method.new) and (debug) print it here?

Comment (guswynn) [reply src/ore/src/process.rs:42]: Ideally we would also `tracing::error` with a `mz_halt` target as well, and use the new filtering to have one spot to control whether or not we want the error logs in production

**Review by guswynn — APPROVED** [review]
i have a few suggestions but looks good!

**Comment by guswynn** [comment]
https://github.com/MaterializeInc/materialize/blob/7482a5f78f0e58a37a7d63af40bdfd585bf2b695/src/storage/src/source/postgres.rs#L418-L421 is also haltable

File: src/ore/src/process.rs [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+/// the process, but not severe enough to be considered a crash. Halts are not
+/// intended to be reported to error tracking tools (e.g., Sentry).
+///
+/// There are two common classes of errors that trigger a halt:
+///
+///   * An error that indicates a new process has taken over (e.g., an error
+///     indicating that the process's leader epoch has expired).
+///
+///   * A retriable error where the retry logic is too difficult to write
+///     correctly. Sometimes the easiest way to retry an error is to tear down
```
Comment (danhhz) [inline src/ore/src/process.rs:34]: nit: I'd call out something like "or difficult enough that it's not worth writing yet" but take it or leave it

**Review by danhhz — APPROVED** [review]
this is great, thanks for typing it up!

**Review by mjibson — APPROVED** [review]

File: src/ore/src/process.rs (hunk 2 above)
Comment (benesch) [reply src/ore/src/process.rs]: Done, thanks!

**Comment by benesch** [comment]
I had to jam in an `AtomicBool` called `PANIC_ON_HALT` to allow persist's test framework to continue to assert on the occurrence of `halt`s. I don't love this solution, but I couldn't figure out how to do anything else with the way that libtest works. Going to merge so that this can make the release tomorrow, but would very happily field post-merge review on how to improve the `PANIC_ON_HALT` thing.

**Comment by danhhz** [comment]
Do you recall offhand which persist test was the problem? Maybe we can just fix the test

**Comment by danhhz** [comment]
> how about we make check_applier_version switch on whether it calls panic! vs halt! on either cfg(debug_assertions) or cfg(test) (probably the latter?)

oh, taking this a step further. given that the issue is compatibility with libtest, another spicier option is to switch the internal behavior of `halt!` and make it a `panic!` when `#[cfg(test)]`

**Comment by benesch** [comment]
`cfg(test)` is a big ol’ footgun though, since it’s only active in the top level crate. If you want to test that a halt occurs in another crate that you depend on, you’re out of luck. Maybe that’s fine, though… no strong feelings!
