### PR TITLE
adapter: subsource retain history propagation

### LINKED ISSUE #26650: adapter: retain history does not appear to be working after restart
From @chaas:

I'm seeing a strange behavior testing retain history locally. I create a source w/ retain history of 1 hour. When I kill and restart materialize locally (without reset), Materialize seems to forgotten the retain history.
I get  `ERROR: Timestamp (1712871330076) is not valid for all inputs: [Antichain { elements: [1712871735000] }]` , which implies the source is back to compacting at 1 second.

Realized I can't inspect the value w/o this info in catalog tables, that's something we should still fast follow with

```
> show create source auction_house;
```

returns the correct DDL

`CREATE SOURCE "materialize"."public"."auction_house" IN CLUSTER "quickstart" FROM LOAD GENERATOR AUCTION (TICK INTERVAL = '1s') FOR TABLES ("mz_load_generators"."auction"."accounts" AS "materialize"."public"."accounts", "mz_load_generators"."auction"."auctions" AS "materialize"."public"."auctions", "mz_load_generators"."auction"."bids" AS "materialize"."public"."bids", "mz_load_generators"."auction"."organizations" AS "materialize"."public"."organizations", "mz_load_generators"."auction"."users" AS "materialize"."public"."users") EXPOSE PROGRESS AS "materialize"."public"."auction_house_progress" WITH (RETAIN HISTORY = FOR '1hr')`

### PR DESCRIPTION
**Pull request by maddyblue**
If a subsource has not set its retain history but the parent source has, use the parent source's retain history.

Fixes #26650

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

### CODE REVIEW

**Comment by maddyblue** [comment]
Tests are insufficient here because they were insufficient before! We don't have a way yet to discover the retain history or installed read policies so testing would have to use testdrive trickery without retries to figure out if this is working or not.

I'm planning on adding a new `mz_internal.mz_retain_histories` or something that exposes this information, after which I can add a test. We could choose to wait for that to merge before merging this PR, at which time fuller tests could be added.

File: src/adapter/src/catalog/state.rs [hunk 1]
```diff
@@ -2383,6 +2383,55 @@ impl CatalogState {
...
+                continue;
+            }
+            let entry = self.get_entry(&id);
+            let source = entry.source().expect("must be source");
+            let source_cw = source.custom_logical_compaction_window.unwrap_or_default();
+            match source.data_source {
+                DataSourceDesc::Ingestion(_) => {
+                    // For sources, look up each dependent subsource and propagate.
+                    cws.entry(source_cw).or_default().insert(id);
+                    ids.extend(entry.used_by());
```
Comment (ParkMyCar) [inline src/adapter/src/catalog/state.rs:2411]: naively I thought `used_by()` would return Views that reference the source, but maybe not?

File: src/adapter/src/coord.rs [hunk 2]
```diff
@@ -1506,14 +1506,29 @@ impl Coordinator {
...
             match entry.item() {
                 // Currently catalog item rebuild assumes that sinks and
                 // indexes are always built individually and does not store information
                 // about how it was built. If we start building multiple sinks and/or indexes
                 // using a single dataflow, we have to make sure the rebuild process re-runs
                 // the same multiple-build dataflow.
-                CatalogItem::Source(_) => {
+                CatalogItem::Source(source) => {
+                    // Propagate source compaction windows to subsources if needed.
+                    if source.custom_logical_compaction_window.is_none() {
```
Comment (ParkMyCar) [inline src/adapter/src/coord.rs:1518]: What if the compaction window for a source `is_some` but does not equal that of the source? Should we not update the compaction window then?

**Review by ParkMyCar — APPROVED** [review]

File: src/adapter/src/catalog/state.rs (hunk 1 above)
Comment (maddyblue) [reply src/adapter/src/catalog/state.rs:2411]: Good find! Added a test for this that panic'd. Fixed.

File: src/adapter/src/coord.rs (hunk 2 above)
Comment (maddyblue) [reply src/adapter/src/coord.rs:1518]: Talked in person: this is working as intended. Subsources inherit only if they do not have their own rh set.
