### PR TITLE
storage: shard write work in `persist_sink`

### LINKED ISSUE #13496: recorded views over upsert sources: "Invalid data in source, saw retractions (1) for row that does not exist" after restarts
### What version of Materialize are you using?

v0.26.1-dev (889df4949)

### How did you install Materialize?

Docker image

### What is the issue?

A test that creates recorded views over Kafka upsert sources and performs restarts of the complete Mz instance will eventually reach this situation:

```
materialize=> select * from view8;
ERROR:  Invalid data in source, saw retractions (1) for row that does not exist: [Null, Null, Int64(0), Int64(0)]
```

Curiously, the problem is reproducible even if we only ever ingest 1 message into the kafka topic. There are no upsert updates or deletions.

Note that to my understanding, kafka upsert sources will currently re-ingest the entire topic when starting up rather than starting from where they left off pre-restart.

@petrosagg 

### Relevant log output

_No response_

### LINKED ISSUE #14919: regression: zippy: materialized view reports "Invalid data in source, saw retractions" even though view sources are all good
### Buildkite link

https://buildkite.com/materialize/tests/builds/41777#01836170-6267-4f7a-9973-81c0aa735b7c

### Relevant log output

```source
> SELECT * FROM sink5_view /* 0 1071670 1071671 1071671 */ ;
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 113ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 49s 74s 111s 166s 34s
<stdin>:2:1: error: non-matching rows: expected:
[["0", "1071670", "1071671", "1071671"]]
got:
[["0", "401061", "401061", "401061"]]
Poor diff:
- 0 1071670 1071671 1071671
+ 0 401061 401061 401061
 
     |
   1 |
   2 | > SELECT * FROM sink5_view /* 0 1071670 1071671 1071671 */ ;
     | ^
!!! Error Report
1 errors were encountered during execution
files involved: -
mzcompose: test case workflow-default failed: running docker compose failed (exit status 1)
==> Uploading report for suite 'mzcompose' to Buildkite Test Analytics
202 {'id': '07cae776-b578-4421-a5a2-ec997904fc1e', 'run_id': '2d7d4de9-25fc-410d-8979-be7ede59e79d', 'queued': 1, 'skipped': 0, 'errors': [], 'run_url': 'https://buildkite.com/organizations/materialize/analytics/suites/mzcompose/runs/2d7d4de9-25fc-410d-8979-be7ede59e79d'}
mzcompose: error: at least one test case failed
🚨 Error: The command exited with status 1
user command error: The plugin mzcompose command hook exited with status 1
```

### Additional thoughts

A couple other instances:

- https://buildkite.com/materialize/tests/builds/41769#01836122-871f-4ee0-ab03-a3e10891db89
- https://buildkite.com/materialize/tests/builds/41770#01836126-f670-4f52-ba99-ec4b9c3a5c41

### PR DESCRIPTION
**Pull request by aljoscha**
### Motivation

Opening this PR early to showcase the approach/gather feedback.

Epic that somewhat tracks this: https://github.com/MaterializeInc/materialize/issues/13884

Fixes #14919
Fixes #13496

### Tips for reviewer

Especially the changes that were required in `persist`, around turning a `Batch` into a `HollowBatch` and back again need to be done the right way before merging this.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

File: src/compute/src/sink/persist_sink.rs [hunk 1]
```diff
@@ -52,92 +58,300 @@ where
...
+            // not necessarily correct for times not greater or equal to this
+            // frontier.
+            let mut current_frontier = as_of;
+            let mut cap_set = CapabilitySet::from_elem(cap);
+
+            move |input, output: &mut OutputHandle<u64, _, Tee<u64, _>>| {
+                while let Some((_time, _data)) = input.next() {
+                    // Just read away data.
+                    // WIP: Is this idiomatic timely?
+                }
```
Comment (antiguru) [inline src/compute/src/sink/persist_sink.rs:242]: This works, but under the hood, the operator receives a full copy of the input stream and immediately discards it. I think there might be a way around this by using [shared](https://github.com/TimelyDataflow/timely-dataflow/blob/master/timely/src/dataflow/operators/rc.rs#L24) operator and consuming the stream of `Rc`s in `mint_batch_boundaries` and `write_batches`.

Comment (antiguru) [reply src/compute/src/sink/persist_sink.rs:242]: The alternative to avoiding this allocation is to have something like https://github.com/TimelyDataflow/timely-dataflow/pull/439, but that hasn't landed yet.

File: src/compute/src/sink/persist_sink.rs [hunk 2]
```diff
@@ -147,117 +361,365 @@ where
...
+                desired_input.for_each(|_cap, data| {
+                    data.swap(&mut buffer);
+                    correction.append(&mut buffer);
+                });
+
+                // Extract persist rows as negative contributions to `correction`.
+                persist_input.for_each(|_cap, data| {
+                    data.swap(&mut buffer);
+                    correction.extend(buffer.drain(..).map(|(d, t, r)| (d, t, -r)));
+                });
```
Comment (antiguru) [inline src/compute/src/sink/persist_sink.rs:384]: Consider changing `correction` to a `Vec<Vec<_>>` instead of a flat `Vec<_>`. The reason for this is that with a flat vector, all data needs to be located in a single allocation, while the nested approach doesn't have this requirement. However, it might make the code further below harder to write, especially consolidating across batches doesn't exist.

File: src/compute/src/sink/persist_sink.rs [hunk 3]
```diff
@@ -52,92 +58,300 @@ where
...
+/// Writes `desired_stream - persist_stream` to persist, but only for updates
+/// that fall into batch boundaries that we get via `batch_boundaries`. This
+/// forwards a `HollowBatch` for any batch of updates that was written.
+fn write_batches<G>(
+    sink_id: GlobalId,
+    operator_name: String,
+    target: &CollectionMetadata,
+    batch_boundaries: &Stream<G, (Antichain<Timestamp>, Antichain<Timestamp>)>,
+    desired_stream: &Stream<G, (Result<Row, DataflowError>, Timestamp, Diff)>,
+    persist_stream: &Stream<G, (Result<Row, DataflowError>, Timestamp, Diff)>,
```
Comment (antiguru) [inline src/compute/src/sink/persist_sink.rs:283]: I just realized, multiplexing `Row` with `DataflowError` is pretty bad. A `Row` should have 32 bytes, but a `DataflowError` occupies 96 bytes. Using the multiplexing we inflate the amount of data on the common path by a factor of more than three (32 to 96 bytes, plus the `Result` tag of 8 bytes due to alignment), which is likely to have negative performance implications. If this kind of multiplexing is absolutely necessary, we could consider boxing the error.

File: src/persist-client/src/batch.rs [hunk 4]
```diff
@@ -156,6 +157,23 @@ where
         self.mark_consumed();
         ret
     }
+
+    /// Turns this [`Batch`] into a [`WriterEnrichedHollowBatch`], which can be
+    /// used to transfer this batch across process boundaries, for example when
+    /// exchanging data between timely workers.
```
Comment (danhhz) [inline src/persist-client/src/batch.rs:163]: make a note in the doc about losing track of this resulting in leaked state in durable storage and that the caller is responsible for ensuring it's turned back into a Batch

File: src/persist-client/src/impl/encoding.rs [hunk 5]
```diff
@@ -493,6 +495,45 @@ impl<T: Timestamp + Codec64> RustType<ProtoReadEnrichedHollowBatch>
...
+impl<T: Timestamp + Codec64> From<WriterEnrichedHollowBatch<T>> for SerdeWriterEnrichedHollowBatch {
+    fn from(x: WriterEnrichedHollowBatch<T>) -> Self {
+        SerdeWriterEnrichedHollowBatch(x.into_proto().encode_to_vec())
+    }
+}
+
+impl<T: Timestamp + Codec64> From<SerdeWriterEnrichedHollowBatch> for WriterEnrichedHollowBatch<T> {
+    fn from(x: SerdeWriterEnrichedHollowBatch) -> Self {
+        let proto = ProtoWriteEnrichedHollowBatch::decode(x.0.as_slice())
+            .expect("internal error: could not decode writer-enriched HollowBatch");
```
Comment (danhhz) [inline src/persist-client/src/impl/encoding.rs:510]: nit: s/writer-enriched HollowBatch/WriterEnrichedHollowBatch/

**Review by danhhz — COMMENTED** [review]
src/persist* changes LGTM!

File: src/compute/src/sink/persist_sink.rs [hunk 6]
```diff
@@ -130,111 +593,471 @@ where
...
-                    .flat_map(|(_ts, updates)| updates.iter());
-
-                if PartialOrder::less_than(&*shared_frontier.borrow(), &input_frontier) {
-                    // We always append, even in case we don't have any updates, because appending
-                    // also advances the frontier.
-                    let lower = shared_frontier.borrow().clone();
-                    // TODO(aljoscha): Figure out how errors from this should be reported.
-                    write
-                        .append(updates, lower, input_frontier.clone())
+                    .filter(|(lower, _upper)| !PartialOrder::less_equal(batches_frontier, lower))
```
Comment (teskje) [inline src/compute/src/sink/persist_sink.rs:966]: Out of curiosity: How do you decide when to use the negated version over the equivalent non-negated one (`PartialOrder::less_than(lower, batches_frontier)` in this case). Assuming I'm not missing something and they are indeed equivalent, I would always consider the non-negated one more readable. But that might be because my brain has not yet adapted to timely :)

**Comment by aljoscha** [comment]
The zippy failure is this one: https://github.com/MaterializeInc/materialize/issues/14754#issuecomment-1253013894

**Review by teskje — APPROVED** [review]
Compute parts LGTM! The code is beautifully written, reviewing it has been a pleasure :D

I just have a couple nits and general questions.

Apart from that, how certain are we that this will not introduce a performance degradation? The idle CPU load of `computed` goes up from ~10% to ~30% with this change, but this doesn't say much about non-idle workloads. Do we have any benchmarks we can run?

File: src/environmentd/tests/server.rs [hunk 7]
```diff
@@ -604,7 +604,7 @@ fn test_cancel_dataflow_removal() -> Result<(), Box<dyn Error>> {
         cancel_token.cancel_query(postgres::NoTls).unwrap();
     });
 
-    match client1.simple_query("SELECT * FROM t AS OF 18446744073709551615") {
+    match client1.simple_query("SELECT * FROM t AS OF 9223372036854775807") {
```
[the remark this answers is not in the document]
Comment (aljoscha) [reply src/environmentd/tests/server.rs:607]: I mentioned it in the commit but you probably only looked at the overall diff, sorry about that 🙈 

https://github.com/MaterializeInc/materialize/pull/14001/commits/977a843397c4eef777ffa4d94cbfc3f6874aed22

File: src/compute/src/sink/persist_sink.rs [hunk 8]
```diff
@@ -40,68 +49,209 @@ where
...
-            err_collection,
+            desired_collection,
+            sink.as_of.frontier.clone(),
             compute_state,
-            false,
         )
     }
 }
 
 pub(crate) fn persist_sink<G>(
```
[the remark this answers is not in the document]
Comment (aljoscha) [reply src/compute/src/sink/persist_sink.rs:72]: I thought about that. We should be able to use the same implementation but we have to create a `persist_source` that doesn't read the snapshot and filters out everything beyond the resume frontier. For a source, `desired` will only contain new updates from the source, not the entire "history".

This will also mean that for sources the `persist_sink` will only be self-correcting from the resume timestamp forward. What do you think?

File: src/environmentd/tests/server.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (teskje) [reply src/environmentd/tests/server.rs:607]: Ah, thanks for pointing that out!

**Comment by aljoscha** [comment]
> Apart from that, how certain are we that this will not introduce a performance degradation? The idle CPU load of computed goes up from ~10% to ~30% with this change, but this doesn't say much about non-idle workloads. Do we have any benchmarks we can run?

I'm not at all certain, and this is likely a pessimisation for cases where the additional parallelism doesn't buy us much. We are strictly doing more complicated things but those will pay off when we need that parallelism.

Did you see this increase in idle load for debug or release builds? I did check that a while ago and didn't see a big increase in idle load but I'll have to double check.

Regarding benchmarks. We don't have much yet but I was hoping to rig up a change that uses this sharded `persist_sink` for sources, and then we could drag race it against the current impl and see how fast it can ingest from a filled Kafka topic.

Thanks a lot for the review, btw! 😊

File: src/compute/src/sink/persist_sink.rs [hunk 9]
```diff
@@ -130,111 +593,471 @@ where
...
+        vec![Antichain::new()],
+    );
+
+    // Dropping this token signals that the operator should shut down cleanly.
+    let token = Rc::new(());
+    let token_weak = Rc::downgrade(&token);
+
+    // This operator accepts the current and desired update streams for a `persist` shard.
+    // It attempts to write out updates, starting from the current's upper frontier, that
+    // will cause the changes of desired to be committed to persist.
```
[the remark this answers is not in the document]
Comment (aljoscha) [reply src/compute/src/sink/persist_sink.rs:859]: yes! 🙈

File: src/compute/src/sink/persist_sink.rs [hunk 10]
```diff
@@ -130,111 +593,471 @@ where
...
+                    return;
                 }
 
-                if !active_write_worker
-                    || token_weak.upgrade().is_none()
-                    || shared_frontier.borrow().is_empty()
-                {
-                    return;
+                if !active_worker {
+                    continue;
```
[the remark this answers is not in the document]
Comment (aljoscha) [reply src/compute/src/sink/persist_sink.rs:905]: There was a bug in the async operator implementation that meant we have to stay alive, otherwise our peer operators would not see the frontier advance anymore. I don't know if this is still true but will double check.

File: src/compute/src/sink/persist_sink.rs (hunk 6 above)
Comment (aljoscha) [reply src/compute/src/sink/persist_sink.rs:966]: Here sometimes my old ways with `Antichain::less_than` come through. With `Antichain` and a single timestamp you can't just do the inverse comparison. So I don't have a good answer here and I might turn it into `PartialOrder::less_than(lower, batches_frontier)`

File: src/compute/src/sink/persist_sink.rs (hunk 10 above)
[the remark this answers is not in the document]
Comment (teskje) [reply src/compute/src/sink/persist_sink.rs:905]: If it turns out this is still necessary to ensure correct behavior, a comment mentioning this would be great!

File: src/compute/src/sink/persist_sink.rs (hunk 8 above)
[the remark this answers is not in the document]
Comment (teskje) [reply src/compute/src/sink/persist_sink.rs:72]: I think that sounds sensible, but I'm also very uninformed about storage/source details, so definitely don't trust me on this!

**Comment by teskje** [comment]
> Did you see this increase in idle load for debug or release builds? I did check that a while ago and didn't see a big increase in idle load but I'll have to double check.

Ah, I totally forgot about release builds for a moment! With a release build, the CPU usage of an idle computed goes from ~2% to ~8%, so I agree this doesn't seem too bad.

File: src/compute/src/sink/persist_sink.rs [hunk 11]
```diff
@@ -40,68 +49,209 @@ where
...
-    let token = Rc::new(());
-    let token_weak = Rc::downgrade(&token);
+    let mut scope = desired_collection.inner.scope();
+
+    // The append operator keeps capabilities that it downgrades to match the
+    // current upper frontier of the persist shard. This frontier can be
+    // observed on the persist_feedback_stream. This is used by the minter
+    // operator to learn about the current persist frontier, driving it's
+    // decisions on when to mint new batches.
+    let (persist_feedback_handle, persist_feedback_stream) = scope.feedback(Timestamp::default());
```
Comment (guswynn) [inline src/compute/src/sink/persist_sink.rs:169]: might want to document why its safe to have the summary timestamp 0 here!

Comment (aljoscha) [reply src/compute/src/sink/persist_sink.rs:172]: adding :ok_hand:
