### PR TITLE
Report on errors when parsing CSV streams

### LINKED ISSUE #5923: Report on errors parsing CSV files
Currently, when materialized encounters bad data in a source file, we print an error message to the logfile. However, we would like to make it so that queries against the source fail. This requires reading the error stream from CSV decoding and passing the output into the right places. This is a specific instance of #4327.

### PR DESCRIPTION
**Pull request by cirego**
When CSV parsing encounters an error, report the errors via the error stream. This will cause the error to propagate to the user when they try to use the data from the source. Add test drive scenario to validate that malformed CSVs show the proper error handling.

Fixes #5923 

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5974)

### CODE REVIEW

**Review by frankmcsherry — APPROVED** [review]
Looks good to me! Seems very idiomatic.

File: src/dataflow/src/decode/csv.rs [hunk 1]
```diff
@@ -114,14 +116,13 @@ where
                                     csv_core::ReadRecordResult::Record => {
                                         if bounds_valid != n_cols {
                                             events_error += 1;
-                                            error!(
-                                                "CSV error: expected {} columns, got {}. Ignoring row.",
-                                                n_cols, bounds_valid,
-                                            );
+                                            session.give((Err(DataflowError::DecodeError(
+                                                DecodeError::Text(format!("CSV error: expected {} columns, got {}. Ignoring row.", n_cols, bounds_valid))
```
Comment (umanwizard) [inline src/dataflow/src/decode/csv.rs:120]: "Ignoring row" might be confusing to the user because it suggests that there is some way to get the other rows with this one filtered out. Which right now... there isn't. So even though it's true from an internal system perspective, we should probably avoid this sort of language from a user perspective.

**Review by umanwizard — APPROVED** [review]

File: src/dataflow/src/decode/csv.rs (hunk 1 above)
Comment (cirego) [reply src/dataflow/src/decode/csv.rs:120]: I will update the language on this! Perhaps just dropping `ignoring row`?

Comment (cirego) [reply src/dataflow/src/decode/csv.rs]: I think we can put the line number in the error message as well. I'll update with that too.

Comment (frankmcsherry) [reply src/dataflow/src/decode/csv.rs]: I predict: 1. ^ is a good local improvement but 2. folks are going to want it changed again, and again, to report the .. line number, the line itself, stuff like that. The PR does a good job linking up errors with the output, and allows folks to iterate on the error content.
