### PR TITLE
persist: remove pub from maybe_heartbeat_reader

### LINKED ISSUE #14265: persist: more precise since/seqno/heartbeating of handles
On prod we saw a problematic behavior where a crash looping writer causes the frontier of a shard to stall, but the storage controller's read handle would continue to heartbeat and accumulate unbounded amounts of consensus state, due to its seqno hold. 

But! A heartbeating writer doesn't _need_ a seqno hold, so it seems like we can work around this problem by moving around our since/seqno/heartbeat handling to narrow the scope of when seqnos/gc can be held back.

Copy and pasting some of Dan's initial thoughts:

> the only thing that needs a seqno hold is snapshot, so I think we simply need to revisit the publicly available combos of downgrade_since/downgrade_seqno/heartbeat
> 
> active listens want all three, active snapshots want only heartbeat, read handles in environmentd want downgrade_seqno+heartbeat
> 
> active snapshots want only heartbeat -> "only heartbeat" is the dangerous one, so I think this method needs to be uncallable from outside persist. then we can make sure that the only way to call it is by actively progressing on a snapshot

### PR DESCRIPTION
**Pull request by danhhz**
The semantics of maybe_heartbeat_reader come from snapshots, which want
to keep a capability on seqno. The only thing that needs a seqno hold is
snapshot, so this PR revisits the publicly available combos of
"downgrade since" vs "downgrade seqno" vs "heartbeat reader_id" (the
concepts, not corresponding to methods in code).

Active listens want all three, active snapshots want only heartbeat,
read handles in environmentd want all three (possibly with a no-op
downgrade_since for the tick loop in persist_read_handles).

The "only heartbeat" one for snapshots (currently called
maybe_heartbeat_reader) is the dangerous one because it holds back the
seqno, so I've changed this method to be private to persist. Instead,
use the idempotence of downgrade_since to make a no-op call for
persist_read_handles's tick loop.

Fixes #14265

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [N/A] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [N/A] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

### CODE REVIEW

File: src/storage/src/controller.rs [hunk 1]
```diff
@@ -1456,7 +1457,10 @@ mod persist_read_handles {
                             let futs = FuturesUnordered::new();
                             for (_id, read) in read_handles.iter_mut() {
                                 if let Some(read) = read.as_mut() {
-                                    futs.push(read.maybe_heartbeat_reader());
+                                    // downgrade_since is idempotent, so downgrading to the minimum
+                                    // element is a no-op and can be used as a lease liveness
+                                    // heartbeat.
```
Comment (pH14) [inline src/storage/src/controller.rs:1462]: using the min-element seems like something that should be in the downgrade_since docs. right now we only reference using `read.since()` to no-op heartbeat

File: src/storage/src/controller.rs [hunk 2]
```diff
@@ -1456,7 +1457,10 @@ mod persist_read_handles {
...
+                                    futs.push(read.maybe_downgrade_since(&antichain_minimum_element));
```
Comment (pH14) [inline src/storage/src/controller.rs:1463]: I wonder if we want this to be `maybe_downgrade_since_and_seqno`, I find the desired behavior here very subtle -- intentionally calling `downgrade_since` to not advance `since` but progress `seqno`

**Review by pH14 — APPROVED** [review]
nit: PR desc references `downgrade_seqno` which doesn't exist 😄 

Function-wise, this seems like it should work -- mostly I think we can clarify some of the naming and docs. Seems like something we can get in for this week's release!

File: src/storage/src/controller.rs (hunk 1 above)
Comment (danhhz) [reply src/storage/src/controller.rs:1462]: 👍 will do

File: src/storage/src/controller.rs (hunk 2 above)
Comment (danhhz) [reply src/storage/src/controller.rs:1463]: I feel that seqno as a concept shouldn't be exposed to persist users. Maybe the real answer is reintroducing a public `maybe_heartbeat_reader` that internally has these semantics? I'd like to keep this diff small and obvious though, given how close we are to cutting this week's release. How about I leave that as a TODO?

**Review by danhhz — COMMENTED** [review]
TFTR!

> nit: PR desc references downgrade_seqno which doesn't exist 😄

hmm I meant it as a reference to the concept, none of them were referencing the calls (e.g. by downgrade_since, I was trying to talk about _just_ the since part of the 3 things that call does). any ideas how to make this more obvious?

File: src/storage/src/controller.rs (hunk 2 above)
Comment (pH14) [reply src/storage/src/controller.rs:1463]: TODO is fine, just something to capture what's actually happening here

**Comment by pH14** [comment]
> hmm I meant it as a reference to the concept, none of them were referencing the calls (e.g. by downgrade_since, I was trying to talk about just the since part of the 3 things that call does). any ideas how to make this more obvious?

Oh maybe just remove the underscores so they aren't interpreted as a symbol from the code

File: src/storage/src/controller.rs (hunk 1 above)
Comment (danhhz) [reply src/storage/src/controller.rs:1462]: done!

File: src/storage/src/controller.rs (hunk 2 above)
Comment (danhhz) [reply src/storage/src/controller.rs:1467]: done!

**Review by danhhz — COMMENTED** [review]
TFTR!

> Oh maybe just remove the underscores so they aren't interpreted as a symbol from the code
