### PR TITLE
storage: simplify postgres progress tracking

### LINKED ISSUE #20295: pg sources: source restarts PG process when inert
### What version of Materialize are you using?

8e1d5a825149ee1837b7aef77355f870a0bc9904

### What is the issue?

Materialize relies on the PG function `pg_logical_slot_peek_binary_changes` to inspect the state of its replication slot, primarily to assess if there is replication lag and if the slot's `write`/`flush`/`apply_lsn`s can/should be forwarded.

Calling this function ~10 times causes the PG process to restart. Unfortunately, this is not "10 successive times," or "10 times in an hour," but just 10 times since the last time the server cleared an internal cache (which I am only sure happens on connection). After some number of calls, the PG server encounters a fatal error:

> `“out of relcache_callback_list slots`

The issue is discussed [here](https://www.postgresql.org/message-id/OSZPR01MB631004A78D743D68921FFAD3FDA79%40OSZPR01MB6310.jpnprd01.prod.outlook.com) and has been resolved in PG [15.3](https://www.postgresql.org/docs/current/release-15-3.html):

 > Avoid leaking cache callback slots in the pgoutput logical decoding plugin (Shi Yu)
> 
> Multiple cycles of starting up and shutting down the plugin within a single session would eventually lead to an “out of relcache_callback_list slots” error.

I haven't verified that this works yet, but irrespective of it being fixed or not, I have reproed the issue on 15.2. It is easiest to trigger with this diff:

```diff
diff --git a/src/storage/src/source/postgres/replication.rs b/src/storage/src/source/postgres/replication.rs
index e39d2b2b45..fef59b4118 100644
--- a/src/storage/src/source/postgres/replication.rs
+++ b/src/storage/src/source/postgres/replication.rs
@@ -89,7 +89,7 @@ const FEEDBACK_INTERVAL: Duration = Duration::from_secs(30);
 
 /// The maximum amount of waiting for a transaction to appear in the replication stream before
 /// checking for replication lag.
-const TX_TIMEOUT: Duration = Duration::from_secs(30);
+const TX_TIMEOUT: Duration = Duration::from_secs(1);
 
 // A request to rewind a snapshot taken at `snapshot_lsn` to the initial LSN of the replication
 // slot. This is accomplished by emitting `(data, 0, -diff)` for all updates `(data, lsn, diff)`
@@ -215,8 +215,10 @@ pub(crate) fn render<G: Scope<Timestamp = MzOffset>>(
                 let mut container = Vec::new();
                 let max_capacity = timely::container::buffer::default_capacity::<((u32, Result<Vec<Option<Bytes>>, DefiniteError>), MzOffset, Diff)>();
 
+                tracing::info!("outer stream");
                 while let Ok(_) = tokio::time::timeout(TX_TIMEOUT, stream.as_mut().peek()).await {
                     let mut new_upper = *data_cap.time();
+                    tracing::info!("inner stream");
                     while let Some(event) = stream.as_mut().peek().now_or_never() {
                         match event {
                             Some(Ok(LogicalReplicationMessage::Begin(begin))) => {
@@ -258,11 +260,13 @@ pub(crate) fn render<G: Scope<Timestamp = MzOffset>>(
                             None => break,
                         }
                     }
+                    tracing::info!("exit inner stream");
                     data_output.give_container(data_cap, &mut container).await;
                     upper_cap.downgrade(&new_upper);
                     data_cap.downgrade(&new_upper);
                     rewinds.retain(|_, (_, req)| data_cap.time() <= &req.snapshot_lsn);
                 }
+                tracing::info!("exit outer stream");
             }
         })
     });
```

Whoever is interested in trying this out can set the timeout that matches their patience.

## Proposal

To fix this issue, we need to remove the calls to `pg_logical_slot_peek_binary_changes`. Those calls are used to handle replication lag in the face of an inert publication while the reset of the system made progress, so we have to find an alternative methodology.

 I recommend we do what a number of other developers do and perform trivial modifications to the upstream PG database co force its WAL to advance.

One of the warts in this is that we need to see not only that the WAL advanced, but that it inserts a `BEGIN` statement in the replication slot's publication (this is the only way that we can be sure that we meaningfully encounter the value).

Without the ability to repeatedly inspect the state of the replication slot, I don't know of any other way we can possibly ensure that the stream is active.

We could also require all users of PG sources upgrade to version 15.3. That seems like a challenging requirement to enforce on all users forevermore.

### PR DESCRIPTION
**Pull request by petrosagg**
### Motivation

In the absence of transactions the only available piece of information in the replication stream are keepalive messages. Keepalive messages are documented[1] to contain the current end of WAL on the server. That is a useless number when it comes to progress tracking because there might be pending messages at LSNs between the last received commit_lsn and the current end of WAL.

Fortunatelly for us, the documentation for PrimaryKeepalive messages is wrong and it actually contains the last *sent* LSN[2]. Here "sent" doesn't necessarily mean sent over the wire, but sent to the upstream process that is handling producing the logical stream. Therefore, if we receive a keepalive with a particular LSN we can be certain that there are no other replication messages at previous LSNs, because they would have been already generated and received. We therefore connect the keepalive messages directly to our capability.

[1] https://www.postgresql.org/docs/15/protocol-replication.html#PROTOCOL-REPLICATION-START-REPLICATION
[2] https://www.postgresql.org/message-id/CAFPTHDZS9O9WG02EfayBd6oONzK%2BqfUxS6AbVLJ7W%2BKECza2gg%40mail.gmail.com

Fixes #20295

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by sploiselle** [comment]
Verified that this PR works on PG 14.7 and 15.2 on RDS (`md5.large`) instances using `pgbench`:
- Scale 100 (`pgbench -i -s 100`)
- 100 clients running 1000 txns each (`pgbench -c 100 -t 1000`) w/o vacuuming

To perform the test:
- Initialized database
- Built MZ locally in release mode
- Created source ingesting all tables
- Built materialized view of counts of rows in tables
- Ran the non-initializing PG bench (i.e. the txns)
- Verified that database and MZ had same row counts for each table

The goal if this was largely to ensure that using `KeepAlive` messages to handle progress worked properly; if there were issues here the volume of transactions would have likely tripped something.

File: src/storage/src/source/postgres/replication.rs [hunk 1]
```diff
@@ -33,6 +33,41 @@
 //!       │ updates      │ output
 //!       v              v
 //! ```
+//!
+//! # Progress tracking
+//!
+//! In order avoid causing excessive resource usage in the upstream server it's important to
```
Comment (guswynn) [inline src/storage/src/source/postgres/replication.rs:39]:
```suggestion
//! In order to avoid causing excessive resource usage in the upstream server it's important to
```

File: src/storage/src/source/postgres/replication.rs [hunk 2]
```diff
@@ -33,6 +33,41 @@
...
+//! track the LSN that we have successfully committed to persist and communicate that back to
+//! PostgreSQL. Under normal operation this gauge of progress is provided by the presence of
+//! transactions themselves. Since at a given LSN offset there can be only a single message, when a
+//! transaction is received and processed we can infer that we have seen all the messages that are
+//! not beyond `commit_lsn + 1`.
+//!
+//! Things are a bit more complicated in the absence of transcations though because even though we
```
Comment (guswynn) [inline src/storage/src/source/postgres/replication.rs:46]:
```suggestion
//! Things are a bit more complicated in the absence of transactions though because even though we
```

File: src/storage/src/source/postgres/replication.rs [hunk 3]
```diff
@@ -33,6 +33,41 @@
...
+//! If we fail to detect this situation and don't send LSN feedback in a timely manner the server
+//! will be forced to keep around WAL data that can eventually lead to disk space exhaustion.
+//!
+//! In the absence of transactions the only available piece of information in the replication
+//! stream are keepalive messages. Keepalive messages are documented[1] to contain the current end
+//! of WAL on the server. That is a useless number when it comes to progress tracking because there
+//! might be pending messages at LSNs between the last received commit_lsn and the current end of
+//! WAL.
+//!
+//! Fortunatelly for us, the documentation for PrimaryKeepalive messages is wrong and it actually
```
Comment (guswynn) [inline src/storage/src/source/postgres/replication.rs:62]:
```suggestion
//! Fortunately for us, the documentation for PrimaryKeepalive messages is wrong and it actually
```

File: src/storage/src/source/postgres/replication.rs [hunk 4]
```diff
@@ -33,6 +33,41 @@
...
+//! contains the last *sent* LSN[2]. Here sent doesn't necessarily mean sent over the wire, but sent
+//! to the upstream process that is handling producing the logical stream. Therefore, if we receive
+//! a keepalive with a particular LSN we can be certain that there are no other replication
+//! messages at previous LSNs, because they would have been already generated and received. We
+//! therefore connect the keepalive messages directly to our capability.
```
Comment (guswynn) [inline src/storage/src/source/postgres/replication.rs:67]: can we add a TODO to fix the documentation upstream? I would hate for it to justify them changing this behavior in the future...

File: src/storage/src/source/postgres/snapshot.rs [hunk 5]
```diff
@@ -382,6 +382,14 @@ async fn export_snapshot(client: &Client) -> Result<(String, MzOffset), Transien
...
     let snapshot = row.get("pg_export_snapshot").unwrap().to_owned();
 
+    // When creating a replication slot postgres returns the LSN of its consistent point, which is
+    // the LSN that must be passed to `START_REPLICATION` to cleanly transition from the snapshot
+    // phase to the replication phase. `START_REPLICATION` includes all transactions that commit at
+    // LSNs *greater than or equal* to the passed LSN. Therefore the snapshot phase must happen at
+    // the greatest LSN that is not beyond the consistent point. That LSN is `consistent_point - 1`
+    let consistent_point = u64::from(consistent_point)
+        .checked_sub(1)
+        .expect("consistent point is always non-zero");
```
Comment (guswynn) [inline src/storage/src/source/postgres/snapshot.rs:392]: is this change backward compatible with existing pg sources? I assume it is, and is actually strictly more correct?

**Review by guswynn — APPROVED** [review]
this seems reasonable to me! getting rid of the weird top-level loop is great!

File: src/storage/src/source/postgres/replication.rs (hunk 4 above)
Comment (sploiselle) [reply src/storage/src/source/postgres/replication.rs:67]: I am working on this unless Petros beats me to it

File: src/storage/src/source/postgres/snapshot.rs (hunk 5 above)
Comment (sploiselle) [reply src/storage/src/source/postgres/snapshot.rs:392]: I am writing up the doc examining if this is compatible and what we need to do to ensure its compatibility.

File: src/storage/src/source/postgres/replication.rs [hunk 6]
```diff
@@ -173,97 +204,98 @@ pub(crate) fn render<G: Scope<Timestamp = MzOffset>>(
...
+                                data_cap.downgrade(&new_upper);
                             }
-                            None => break,
-                        }
+                        },
+                        _ => return Err(TransientError::BareTransactionEvent),
+                    }
+                    Ok(PrimaryKeepAlive(keepalive)) => {
+                        trace!(%id, "timely-{worker_id} received keepalive lsn={}", keepalive.wal_end());
+                        new_upper = std::cmp::max(new_upper, keepalive.wal_end().into());
```
Comment (sploiselle) [inline src/storage/src/source/postgres/replication.rs:283]: I need to do some digging to validate this, but my current understanding is that this is equivalent to having received a txn whose commit LSN is this value, so we should add 1--this value is likely to become the `confirmed_flush_lsn`, and we don't want to theoretically ingest a txn with this LSN.

```suggestion
                        new_upper = std::cmp::max(new_upper, MzOffset::from(keepalive.wal_end()) + 1);
```

I'll note that I think this point is somewhat moot because this message explicitly states that we won't see a txn at this time unless we already have––but for stepping through the logic of the program and reverse-engineering the semantics, I think it's helpful.

**Comment by sploiselle** [comment]
Petros and I were chatting about the potential implications of merging this
change on top of PG sources that were previously running.

I will give an example of how processing through the replication stream used to
work, show what will happen now, try to generalize the transition, and pose a
few options for how we can safely merge this change.

# Current `main` behavior

On `main`, there are two concepts we need to attend to:
- The `confirmed_flush_lsn` of the replication slot
- The upper we commit data at (i.e. the data capability when we give data to the
  data output).

To show the current behavior, we'll go through a series of state changes. We'll
use the notation:

```
- P: <in-memory committed LSN>/<physically committed LSN>
- M: <data capability time>/<upper feedback>
```

If a value is unknown, we'll mark it as `???`. If we known the value by
induction but the "local observer" of the problem does not, we'll put it in
parentheses.

This scenario is greatly simplified but I believe is complex enough to
encapsulate the ingestion's interface with the PG database.

## New sources

1. Create a source.
	- P:	???
	- M:	0/0
1. Call `advance_upper`, which advances our LSN to the first txn we saw whose
   LSN is geq the upper. Imagine it's `100`.

	- P:	<=100/???
	- M:	100/0
1. Start the replication slot. Whenever we did this, we moved the upper back 1,
	so we start at 1 less than the slot's actual confirmed LSN, and PG only
	returns transactions with commits greater than the LSN (i.e. you could
	probably start 0 to always get everything).
	
	- P:	100/???
	- M:	100/0
1. Observe the actual txn with the LSN we saw during `advance_upper`. Imagine we
   commit this value immediately, e.g. our `max_capacity` is `1`. Whenever we do
   this, we add 1 to the commit LSN we saw.
	- P:	100/???
	- M:	101/100
1. When Materialize closes an upper, it sends feedback which we process within
   the stream. When communicating that we have committed this LSN to PG, we
   subtract 1.
	- P:	100/100
	- M:	101/101

## Existing sources restarting w/ new txns
1. Imagine MZ restarts and we re-enter the ingestion
	- P:	???(100)
	- M:	101/101
1. Call `advance_upper`, which advances our LSN to the first txn we saw whose
   LSN is geq the upper.
   
   Note that there is a hidden complexity here that this function read LSNs from
   PG, but compared them directly to the _modified_ LSN we treat as the upper.
   This meant that we always skipped any txn we encountered whose commit LSN was
   equal to the `confirmed_flush_lsn`. I believe this was intentional, albeit
   undocumented in the current iteration of the code on `main`.

   The important point here is that this is the mechanism which lets us ensure
   that we don't see transactions whose commit LSN is the `confirmed_flush_lsn`
   and "skip" over them. A further note that this isn't really ideal to be
   accounting in this way.

   This is fine as long as the replication slot we use for snapshotting is
   beyond the `confirmed_flush_lsn`. However, if the `confirmed_flush_lsn` is
   equal to the `consistent_point` of the snapshotting replication slot, we
   would have skipped over the first txn where they met. That this ever occurred
   is somewhere between unlikely and impossible.

   As we'll see in the committing case, we always left one byte left "unread" in
   the LSN, which is also why this skipping over `confirmed_flush_lsn` value
   itself has been fine.

   In our example, we'll pretend that the first offset we find a `Begin`
   statement has a `commit_lsn` of `108`.

	- P:	<=108?/???(100)
	- M:	108/101
1. Start the replication slot, at `M - 1`

	- P:	107/???
	- M:	108/101
1. Observe the actual txn with the LSN we saw during `advance_upper`, imagining
   we commit it immediately.

	- P:	107/???
	- M: 	109/109
1. Close the upper and send feedback to PG, using upper -1

	- P:	108/108
	- M:	109/109

## Existing sources restarting, having seen end of WAL
1. Imagine MZ restarts and we re-enter the ingestion
	- P:	???(108)
	- M:	109/109
1. Call `advance_upper`, which advances our LSN to the first txn we saw whose
   LSN is geq the upper.

   This function also checks the very end of the WAL; if we find no txn with a
   commit LSN geq our upper, we set the upper to 1 + the WAL end.

   Imagine this is the case.
	- P:	<=108/???
	- M:	109/109
1. Start the replication slot at upper - 1.

	- P: 108/???
	- M: 109/109

	In this case, the streams will never start up and we will just cycle around
	`advance_upper` and checking the stream every 30 seconds until, finally, we call
	`pg_logical_slot_peek_binary_changes` this sixth time and kill the process
	serving our connection. We then restart, etc.

1. When we send feedback to PG, it will be at upper -1.

	- P: 108/108
	- M: 109/109

# New world

Ok, now imagine we transition from the old state of the world (i.e. `main`) to
this new world.

1. Imagine MZ restarts and we re-enter the ingestion

	- P: 	???
	- M: 	109/108

1. Start the replication slot at the resume_lsn, which is the meet of our
   uppers, i.e. the upper we've been discussing.

	- P:	109/???
	- M: 	109/108

1. We see the first txn with a commit <= the `resume_lsn`. Imagine we it was at
   LSN 112 immediately commit it, downgrading the capability to 113 (LSN + 1).

	- P: 	109/???
	- M: 	113/108

1. Close the upper and send feedback to PG, using upper (_not_ - 1)

	- P:	113/113
	- M:	113/112

1. Now imagine we enter a period of inactivity while the rest of the system
   continues making progress on other collections. In this situation, we'll
   receive `KeepAlive` messages that contain the LSN up to which we've seen all
   txns, confusingly named `wal_end`.

   Here we can derive a new upper from `wal_end` + 1. Imagine `wal_end` is 120

	- P:	113/113
	- M:	121/112

1. Close the upper and send feedback to PG, using upper (_not_ - 1)

	- P:	121/121
	- M:	121/120

Now, the next time we restart, we'll begin with the first txn whose LSN is <=
121.

# Bridging old to new

The fears we have in the transition from the current state on `main` to this
state are:

- Losing transactions by skipping over their LSNs
- Double-counting transactions by looking at LSNs that we've already committed.

## Can we lose transactions?

We could lose transactions if we start our replication slot ahead of the first
unseen txn's LSN.

However, we know that we are actually only interested in txns that begin beyond
our upper (i.e. with LSNs <= our upper). We know that in the prior world, we
kept the `confirmed_flush_lsn` further back than was necessary, meaning we are
always guaranteed to be able to get the txns starting at our upper.

The only way that we could have lost transactions is if the slot was
overcompacted, which we already have panics in place to detect.

## Can we double-count transactions

Given that the slot's `confirmed_flush_lsn` on its first boot will be behind the
upper, can we ensure that we do not see any txns available in the replication
slot at times before the upper? Yes––this is the enabled by the LSN specified in
`START_REPLICATION`.

If we were to just read transactions from the replication slot, we would get
value we'd already seen (e.g. `pg_logical_slot_peek_binary_changes`)––however,
that is not what we do or what we must do.

# Paths forwards

I believe this code is good to merge as-is. I have one outstanding comment on it
that I don't think makes a material change to the code itself, but might make
the semantics more legible.

_However_, if we wanted to be _very_ certain that nothing goes awry, on boot, we
could advance the `confirmed_flush_lsn` to the upper. This would often by a
no-op, but does ensure that we can never view any txns before our upper.

File: src/storage/src/source/postgres/replication.rs (hunk 6 above)
Comment (petrosagg) [reply src/storage/src/source/postgres/replication.rs:283]: My understanding is that the `sentPtr` already contains the `+1` in it so we shouldn't do it twice here. I had the `+1` in the begining and I observed panics in the local version of this PR which had aggressive asserts on every message on the modified postgres that spammed the stream with keepalives.

I did some extra digging now and also found [this](https://github.com/postgres/postgres/blob/REL_16_STABLE/src/include/access/xlogreader.h#L207) in the source code of postgres which says `EndRecPtr` is `end + 1` and [this](https://github.com/postgres/postgres/blob/REL_16_STABLE/src/backend/replication/walsender.c#L3083) which sets the `sentPtr` to `EndRecPtr`, which is what eventually makes into the keepalive value.

Comment (sploiselle) [reply src/storage/src/source/postgres/replication.rs:283]: Convincing links––I hadn't gotten to look at the PG source code yet. Thanks for being ahead of that.

**Review by sploiselle — APPROVED** [review]

**Comment by petrosagg** [comment]
@sploiselle thank you for the analysis of the various scenarios! I was also convinced that this PR is good to merge as-is
