### PR TITLE
adapter: Cancel `insert .. select`

### LINKED ISSUE #18715: `INSERT ... SELECT`s are not cancelled on session disconnect
### What version of Materialize are you using?

main

### How did you install Materialize?

Built from source

### What is the issue?

When one performs an `INSERT ... SELECT` statement with a long-running `SELECT` query, and then disconnects the session, adapter does not cancel the in-progress peek.

To reproduce ([courtesy of @philip-stoev](https://github.com/MaterializeInc/materialize/pull/18442#issuecomment-1501709415)):

1. Start a long-running `INSERT ... SELECT`, e.g.:
    ```sql
    CREATE TABLE t1 (f1 INTEGER);
    INSERT INTO t1 WITH MUTUALLY RECURSIVE flip(x INTEGER) AS (VALUES(1) EXCEPT ALL SELECT * FROM flip) SELECT * FROM flip;
    ```

    Note that this example uses WMR, which needs to be enable through `--unsafe-mode` or the feature flag, to produce a divergent query that will never return. Any other slow query works too.

2. Forcefully disconnect the session from another terminal, e.g.:
    ```
    $ killall psql
    ```

Observe that adapter is not immediately cancelling the in-progress peek with the compute controller. The cancellation only happens when the statement timeout occurs. This behavior is different than for regular `SELECT` queries, which are cancelled immediately on session disconnect.

Note that the bug might be difficult to observe, depending on your test query. For example, the above divergent WMR query will never stop running regardless of whether the peek was cancelled or not (#16800). I suggest you instrument the code to print when the compute controller receives a `CancelPeeks` command.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by andrewrodriguez-m**
### Motivation

Fixes #18715

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

File: src/adapter/src/client.rs [hunk 1]
```diff
@@ -482,52 +484,77 @@ impl SessionClient {
...
+                            .commands
+                            .with_label_values(&[typ, status, name_hint.as_str()])
+                            .inc();
+                    }
+                    self.session = Some(res.session);
+                    return res.result
+                },
+                _err = &mut cancel_future, if !cancelled => {
+                    cancelled = true;
+                    self.inner_mut().cancel_request(conn_id, secret_key);
```
Comment (ParkMyCar) [inline src/adapter/src/client.rs:554]: Do we need to maintain the `cancelled` flag? After calling `cancel_request(...)` can we eagerly return with an error instead of waiting for rx to close and take the above path? That should also allow us to eliminate the need for a `loop`?

Comment (andrewrodriguez-m) [reply src/adapter/src/client.rs:554]: I think so yeah. cancel_request is asking controller to cancel but some things aren't cancellable (like an insert or an `insert .. select` that's completed the select part but not the insert part) so we want to give the real return in those cases. In the case of things that can be cancelled, `rx` will eventually return some cancelled-like error.

The reason for the `if !cancelled` is that the cancel future will panic if polled after successfully returning. Not sure if there's a better idiom for expressing this

File: src/environmentd/tests/server.rs [hunk 2]
```diff
@@ -437,6 +436,118 @@ fn test_cancel_dataflow_removal() {
...
+#[cfg_attr(miri, ignore)] // unsupported operation: can't call foreign function `epoll_wait` on OS `linux`
+fn test_cancel_insert_select() {
+    test_cancellation_cancels_dataflows("INSERT INTO t WITH MUTUALLY RECURSIVE flip(x INTEGER) AS (VALUES(1) EXCEPT ALL SELECT * FROM flip) SELECT * FROM flip;");
+}
+
+fn test_closing_connection_cancels_dataflows(query: String) {
+    let config = util::Config::default().unsafe_mode();
+    let server = util::start_server(config).unwrap();
+
+    let mut cmd = Command::new("psql");
```
Comment (mjibson) [inline src/environmentd/tests/server.rs:462]: This may need to get moved into mzcompose/testdrive to work? That'd require rewriting this in python, but I think that's reasonable. Testdrive already has retry functionality when running testdrive code.

**Review by mjibson — APPROVED** [review]
Adding psql to docker lgtm

File: src/adapter/src/client.rs (hunk 1 above)
Comment (ParkMyCar) [reply src/adapter/src/client.rs:554]: Ahhh that totally makes sense. Sorry I didn't comment sooner, but I think [`FutureExt::fuse`](https://docs.rs/futures/latest/futures/future/trait.FutureExt.html#method.fuse) would fit this use case perfectly! IMO no need to go back and change it though, the `cancelled` flag works just fine
