### PR TITLE
expr: don't overcount byte result size of last batch

### LINKED ISSUE #22724: adapter: finishing over counts result sizes with limit present
The query `SELECT x FROM (VALUES ('{"row": 1}')) AS a (x), generate_series(1, 50000) LIMIT 1;` has its byte accounting at 50,000 x (byte size of `{"row": 1}`. The console sets a 1MB max_query_result_size, which exceeds this limit and returns an error. This is wrong because the limit means that we will never actually exceed this. Oddly, the max query result calculation is done twice in the finishing logic. I think the first one is wrong (this bug) and the second one is not needed.

The first one should be changed to never add more rows than are left in the limit.

### PR DESCRIPTION
**Pull request by mjibson**
During finishing we were overcounting the bytes of the last batch if there were more rows in the count than the remaining limit. This would cause the max_query_result_size error to occur when it should not have.

The first accounting also incorrectly did not account for projections, so a large ordering key could also cause incorrect max result size errors.

Fix both by reverting #17968, but adding a check before the Vec allocation to avoid anything too large.

Fixes #22724

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - Fix an incorrect occurrence of `result exceeds max size` that could occur in queries with `LIMIT`.

### CODE REVIEW

File: src/expr/src/relation/mod.rs [hunk 1]
```diff
@@ -3077,13 +3080,6 @@ impl RowSetFinishing {
                         .extend(self.project.iter().map(|i| &datums[*i]));
                     row_buf.clone()
                 };
-                total_bytes += new_row.byte_len();
-                if total_bytes > max_result_size {
-                    return Err(format!(
-                        "result exceeds max size of {}",
-                        ByteSize::b(u64::cast_from(max_result_size))
-                    ));
-                }
```
Comment (umanwizard) [inline src/expr/src/relation/mod.rs:3086]: If this is getting removed, what actually causes us to return early in the case where the result exceeds the max size?

**Review by umanwizard — CHANGES_REQUESTED** [review]

File: src/expr/src/relation/mod.rs (hunk 1 above)
Comment (umanwizard) [reply src/expr/src/relation/mod.rs:3086]: Nevermind, I see it's in the earlier loop.

**Review by umanwizard — APPROVED** [review]

File: src/expr/src/relation/mod.rs (hunk 1 above)
Comment (frankmcsherry) [reply src/expr/src/relation/mod.rs:3086]: I think the theory is that the earlier return near the other modified code would do the return, and this code is "dead" in that any time this would return, that earlier code would also return.

It would be a lot easier to understand without two loops doing the same logic, though.

Comment (frankmcsherry) [reply src/expr/src/relation/mod.rs:3086]: The earlier block is documented as returning early if we would exceed the limit, and assuming it holds to that documentation this code should not have to return early in that case.

Comment (frankmcsherry) [reply src/expr/src/relation/mod.rs:3086]: I read this more, and @mjibson I think there's a gotcha here that this accounting respects `self.project` and the accounting up above does not. It's .. probably just a bug that the one above does not respect `self.project`, but it does mean that these could reach different conclusions.

Comment (teskje) [reply src/expr/src/relation/mod.rs:3086]: Looks like we want to avoid a panic in `Vec::with_capacity`: https://github.com/MaterializeInc/materialize/pull/17968

**Comment by mjibson** [comment]
Please have another look. This has been reworked to account for projections and #17968. cc @ParkMyCar

File: src/expr/src/relation/mod.rs [hunk 2]
```diff
@@ -3035,31 +3035,40 @@ impl RowSetFinishing {
...
+        // for (_, count) in &rows[offset_nth_row..] {
+        //     total += count.get();
+        // }
+        // let return_size = std::cmp::min(total, limit);
+        //
+        // but it breaks early if the limit is reached, instead of scanning the entire code.
+        let return_row_count = rows[offset_nth_row..]
+            .iter()
+            .try_fold(0, |sum, (_, count)| {
+                let new_sum = sum + count.get();
```
Comment (ParkMyCar) [inline src/expr/src/relation/mod.rs:3050]: Just to be safe could you use `saturating_add` here?

**Review by ParkMyCar — APPROVED** [review]
Looks good to me!

File: src/expr/src/relation/mod.rs (hunk 2 above)
Comment (mjibson) [reply src/expr/src/relation/mod.rs:3050]: Done.
