### PR TITLE
environmentd: improve long-lived connection logic for websockets

### LINKED ISSUE #20262: Websocket cancel subscribe puts user in a weird transaction state
### What version of Materialize are you using?

v0.59.0-dev (01f9bdca5)

### What is the issue?

When cancelling subscribes, the `ReadyForQuery` message says the user is in a transaction state. However, if you type "commit;", it says the user is not in a transaction state, and will send a `ReadyForQuery` message saying the user isn't in a transaction state. Then when you run any query, it says:
```
Error: SUBSCRIBE in transactions must be the only read statement
```

Steps to reproduce:
1. SUBSCRIBE(SELECT * FROM mz_secrets);
2. COMMIT;
3. SUBSCRIBE(SELECT * FROM mz_secrets);
4. SUBSCRIBE(SELECT * FROM mz_secrets);
5. SUBSCRIBE(SELECT * FROM mz_secrets);

Video:
https://github.com/MaterializeInc/materialize/assets/29664023/5719ef55-7aad-49ec-8858-0b2e4aecda8a

Websocket message log:
```
{"type":"ParameterStatus","payload":{"name":"TimeZone","value":"UTC"}}	70	
18:28:05.356
{"type":"ParameterStatus","payload":{"name":"IntervalStyle","value":"postgres"}}	80	
18:28:05.356
{"type":"ParameterStatus","payload":{"name":"cluster","value":"default"}}	73	
18:28:05.356
{"type":"ParameterStatus","payload":{"name":"cluster_replica","value":""}}	74	
18:28:05.356
{"type":"ParameterStatus","payload":{"name":"database","value":"materialize"}}	78	
18:28:05.365
{"type":"ParameterStatus","payload":{"name":"mz_version","value":"v0.59.0-dev (01f9bdca5)"}}	92	
18:28:05.365
{"type":"BackendKeyData","payload":{"conn_id":12,"secret_key":1423016183}}	74	
18:28:05.365
{"type":"ReadyForQuery","payload":"I"}	38	
18:28:05.372
{"query":"SUBSCRIBE(SELECT * FROM mz_secrets);"}	48	
18:28:06.334
{"type":"CommandStarting","payload":{"has_rows":true,"is_streaming":true}}	74	
18:28:06.711
{"type":"Rows","payload":["mz_timestamp","mz_diff","id","oid","schema_id","name","owner_id","privileges"]}	106	
18:28:06.729
{"type":"Row","payload":["1688077685657",1,"u1",20506,"u3","secret_1","u1",["u1=U/u1"]]}	88	
18:28:06.729
{"type":"Row","payload":["1688077685657",1,"u5",20507,"u3","mz_rds_password","u1",["u1=U/u1"]]}	95	
18:28:06.729
{"type":"Error","payload":{"message":"query canceled","code":"XX000"}}	70	
18:28:11.104
{"type":"Notice","payload":{"message":"query was automatically run on the \"mz_introspection\" cluster","severity":"debug"}}	124	
18:28:11.124
{"type":"ReadyForQuery","payload":"T"}	38	
18:28:11.133
{"query":"COMMIT;"}	19	
18:28:25.410
{"type":"CommandStarting","payload":{"has_rows":false,"is_streaming":false}}	76	
18:28:25.435
{"type":"CommandComplete","payload":"COMMIT"}	45	
18:28:25.445
{"type":"Notice","payload":{"message":"there is no transaction in progress","severity":"warning"}}	98	
18:28:25.455
{"type":"ReadyForQuery","payload":"I"}	38	
18:28:25.464
{"query":"SUBSCRIBE(SELECT * FROM mz_secrets);"}	48	
18:28:28.800
{"type":"CommandStarting","payload":{"has_rows":true,"is_streaming":true}}	74	
18:28:28.884
{"type":"Rows","payload":["mz_timestamp","mz_diff","id","oid","schema_id","name","owner_id","privileges"]}	106	
18:28:28.899
{"type":"Error","payload":{"message":"query canceled","code":"XX000"}}	70	
18:28:28.899
{"type":"Notice","payload":{"message":"query was automatically run on the \"mz_introspection\" cluster","severity":"debug"}}	124	
18:28:28.912
{"type":"ReadyForQuery","payload":"T"}	38	
18:28:28.922
{"query":"SUBSCRIBE(SELECT * FROM mz_secrets);"}	48	
18:28:39.702
{"type":"CommandStarting","payload":{"has_rows":false,"is_streaming":false}}	76	
18:28:39.732
{"type":"Error","payload":{"message":"SUBSCRIBE in transactions must be the only read statement","code":"XX000"}}	113	
18:28:39.745
{"type":"Notice","payload":{"message":"query was automatically run on the \"mz_introspection\" cluster","severity":"debug"}}	124	
18:28:39.759
{"type":"ReadyForQuery","payload":"I"}	38	
18:28:39.769
{"query":"SUBSCRIBE(SELECT * FROM mz_secrets);"}	48	
18:28:41.338
{"type":"CommandStarting","payload":{"has_rows":true,"is_streaming":true}}	74	
18:28:41.502
{"type":"Rows","payload":["mz_timestamp","mz_diff","id","oid","schema_id","name","owner_id","privileges"]}	106	
18:28:41.527
{"type":"Error","payload":{"message":"query canceled","code":"XX000"}}	70	
18:28:41.528
{"type":"Notice","payload":{"message":"query was automatically run on the \"mz_introspection\" cluster","severity":"debug"}}	124	
18:28:41.542
{"type":"ReadyForQuery","payload":"T"}	38	
18:28:41.554
```

### PR DESCRIPTION
**Pull request by mjibson**
The adapter client handling was initially written only for single-shot HTTP endpoints and so didn't do various things done in the pgwire protocol. But since websockets exist we need this logic but never wrote tests for it.

Teach websockets to correctly close implicit transactions and also reset the client state at the beginning of each message.

Fixes #20262

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

### CODE REVIEW

File: src/environmentd/src/http/sql.rs [hunk 1]
```diff
@@ -138,7 +140,29 @@ async fn run_ws(state: &WsState, mut ws: WebSocket) {
...
 
     loop {
-        let msg = match ws.recv().await {
+        // Handle timeouts first so we don't execute any statements when there's a pending timeout.
+        let msg = select! {
+            biased;
+
+            // `recv_timeout()` is cancel-safe as per it's docs.
+            Some(timeout) = client.client.recv_timeout() => {
+             //   let error_response = ErrorResponse::from_adapter_error(Severity::Fatal, timeout.into());
```
Comment (jkosh44) [inline src/environmentd/src/http/sql.rs:149]: Did you mean to leave this in?

**Review by jkosh44 — APPROVED** [review]

File: src/environmentd/src/http/sql.rs (hunk 1 above)
Comment (mjibson) [reply src/environmentd/src/http/sql.rs]: No, removed.

**Comment by mjibson** [comment]
This ended up changing the `post` tests because we now commit implicit transactions per group, which more closely mirrors the pgwire transaction handling.
