### PR TITLE
Prevent paninc on Interval negation

### LINKED ISSUE #10729: Interval Overflow when negating i32::MIN
### What version of Materialize are you using?

v0.20.1-dev (f24b21515)

### How did you install Materialize?

Built from source

### What was the issue?

If you try and negate an interval with a month field of `i32::MIN` it will cause a panic. This is because you can't negate i32::MIN. Instead some Interval out of range error should be thrown.

The error happens right here: https://github.com/MaterializeInc/materialize/blob/13c1f7c81fdd2470cec6d14ec76fd24decf288ed/src/repr/src/adt/interval.rs#L44-L52

### Relevant log output

```source
materialize=> SELECT -INTERVAL '-2147483648 months';
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

### PR DESCRIPTION
**Pull request by jkosh44**
Fixes #10729

Negating interval fields was not being checked for overflow, this
commit adds a check and throws an appropriate error.

### Motivation
This PR fixes a recognized bug: #10729

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

File: src/repr/src/adt/interval.rs [hunk 1]
```diff
@@ -41,12 +41,14 @@ impl Default for Interval {
...
-impl std::ops::Neg for Interval {
-    type Output = Self;
-    fn neg(self) -> Self {
-        Self {
-            months: -self.months,
-            duration: -self.duration,
+impl num_traits::ops::checked::CheckedNeg for Interval {
+    fn checked_neg(&self) -> Option<Self> {
+        if let (Some(months), Some(duration)) =
+            (self.months.checked_neg(), self.duration.checked_neg())
```
Comment (sploiselle) [inline src/repr/src/adt/interval.rs:47]: Because the MIN/MAX values for duration are not equal w/ an `abs` operation,  this ought to go through `repr::adt::Interval::new()`, i.e.

here's the max:

```
SELECT INTERVAL '2147483647 days 2147483647 hours 59 minutes 59.999999 seconds';
            interval             
---------------------------------
 2236962132 days 07:59:59.999999
```

here's the min:
```
materialize=> SELECT INTERVAL '-2147483648 days -2147483648 hours -59 minutes -59.999999 seconds';
             interval              
-----------------------------------
 -2236962133 days -08:59:59.999999
```

here's the negated min:

```
SELECT -INTERVAL '-2147483648 days -2147483648 hours -59 minutes -59.999999 seconds';
            ?column?             
---------------------------------
 2236962133 days 08:59:59.999999
```

2236962133 days from the negated min exceeds the 2236962132 days from the max.

This should likely be a test, as well.

**Review by sploiselle — CHANGES_REQUESTED** [review]
tysm for hopping on this so quickly! needs just a smidge more work. this type is so fraught

File: src/repr/src/adt/interval.rs (hunk 1 above)
Comment (jkosh44) [reply src/repr/src/adt/interval.rs:47]: Good catch, just added the fix and test.

**Review by sploiselle — APPROVED** [review]
tysm!
