### PR TITLE
storage: correctly calculate the times to reclock to

### LINKED ISSUE #16318: thread 'timely:work-0' panicked at 'failed to create a delayed capability, the current set does not have an element less than or equal to
### What version of Materialize are you using?

v0.33.0-dev (ce99778ab)

### How did you install Materialize?

Docker image

### What is the issue?

A Zippy test immediately panics with:
```
thread 'timely:work-0' panicked at 'failed to create a delayed capability, the current set does not have an element less than or equal to 1669620038000', /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/dataflow/operators/capability.rs:446:13
```

and then proceeds to repeatedly panic in the same fashion **tens of thousands of times** per 24h test . The test does make progress though, even though very slowly and eventually it will report that some source never converged to the expected result  even if given 10 min to do so .

To reproduce:

```
cd test/zippy
./mzcompose run default --scenario KafkaSourcesLarge
```

and in a separate console do:

```
docker logs zippy-materialized-1 --follow
```

and observe the panics as they go by. 

### Relevant log output

```source
thread 'timely:work-0' panicked at 'failed to create a delayed capability, the current set does not have an element less than or equal to 1669620038000', /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/dataflow/operators/capability.rs:446:13
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: timely::dataflow::operators::capability::CapabilitySet<T>::delayed::delayed_panic
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/dataflow/operators/capability.rs:446:13
   3: timely::dataflow::operators::capability::CapabilitySet<T>::delayed::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/dataflow/operators/capability.rs:454:32
   4: core::option::Option<T>::unwrap_or_else
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:825:21
   5: timely::dataflow::operators::capability::CapabilitySet<T>::delayed
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/dataflow/operators/capability.rs:453:9
   6: mz_storage::source::source_reader_pipeline::handle_message
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a1897808505617a3-1/materialize/tests/src/storage/src/source/source_reader_pipeline.rs:1623:18
   7: mz_storage::source::source_reader_pipeline::reclock_operator::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a1897808505617a3-1/materialize/tests/src/storage/src/source/source_reader_pipeline.rs:1434:25
   8: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/dataflow/operators/generic/builder_rc.rs:123:31
   9: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/dataflow/operators/generic/builder_rc.rs:162:26
  10: <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/dataflow/operators/generic/builder_raw.rs:204:9
  11: timely::progress::subgraph::PerOperatorState<T>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/progress/subgraph.rs:684:30
  12: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/progress/subgraph.rs:344:26
  13: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/progress/subgraph.rs:310:17
  14: timely::progress::subgraph::PerOperatorState<T>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/progress/subgraph.rs:684:30
  15: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/progress/subgraph.rs:344:26
  16: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/progress/subgraph.rs:310:17
  17: timely::worker::Wrapper::step::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/worker.rs:754:57
  18: core::option::Option<T>::map
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:929:29
  19: timely::worker::Wrapper::step
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/worker.rs:754:26
  20: timely::worker::Worker<A>::step_or_park
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/worker.rs:396:38
  21: mz_storage::storage_state::Worker<A>::run_client
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a1897808505617a3-1/materialize/tests/src/storage/src/storage_state.rs:219:17
  22: mz_storage::storage_state::Worker<A>::run
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a1897808505617a3-1/materialize/tests/src/storage/src/storage_state.rs:195:33
  23: mz_storage::server::serve::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a1897808505617a3-1/materialize/tests/src/storage/src/server.rs:94:9
  24: timely::execute::execute::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/execute.rs:287:22
  25: timely_communication::initialize::initialize_from::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/communication/src/initialize.rs:316:33
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
environmentd: 2022-11-28T07:20:39.755327Z  WARN mz_storage_client::controller::rehydration: storage host produced error, reconnecting: status: Unknown, message: "error reading a body from connection: broken pipe", details: [], metadata: MetadataMap { headers: {} }
environmentd: 2022-11-28T07:20:39.761795Z ERROR mz_orchestrator_process: storage-u4 exited: Ok(ExitStatus(unix_wait_status(6))); relaunching in 5s
```

### PR DESCRIPTION
**Pull request by petrosagg**
### Motivation

The logic in `ReclockOperator::reclock_time`, even though it was thoroughly documented and passed numerous tests, was not correct and could end up reclocking `FromTime` times earlier than they should. Its fatal flaw was that it was assuming that one of these two cases must always hold:
  * When `src_ts` changes from being beyond the `FromTime` frontier to not beyond we will observe a triplet with a positive diff whose `from_ts` is not beyond `src_ts`.
  * When the frontier represented by the remap collection advances but it `src_ts` remains beyond it we will observe a triplet with a positive diff whose `from_ts` is beyond `src_ts`.

Both of the above assumptions turn out to be incorrect.

The first assumption is not true if the `FromTime` frontier ever advances to the empty antichain. In that case there is no positive diff to observe since there are no timestamps left in the frontier. We have not observed this happening because all production sources never reach the empty antichain.

The second assumption is not true if the `FromTime` frontier advances but in an unrelated to `src_ts` way. For example, if `src_ts` is about partition 0 of a Kafka topic it's possible that we see a lot of remap updates for a different partition. The current code would incorrectly reclock `src_ts` to one of these irrelevant frontier advancements because it would assume that the whole frontier moved past `src_ts` since `src_ts` was not beyond all of the updates that happened. This was the cause of #16318.

In retrospect, the implementation that filtered diffs and used `i64::MIN` was very sucpicious but the extensive unit tests of the reclock logic and a green CI convinced me of its correctness.

The new logic implemented in this PR seems much more "natural" without relying on weird minimum values or filtering diffs. It works correctly on both of the edge cases illustrated above and passed all previous tests without modification.

Fixes #16318

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Comment by petrosagg** [comment]
@philip-stoev zippy no longer fails locally but feel free to run more tests on this

File: src/storage/src/source/reclock.rs [hunk 1]
```diff
@@ -185,29 +186,64 @@ where
...
+        // timestamps `from_ts` that are less than or equal to `src_ts` and occur at IntoTime times
+        // with a positive diff. We also know that `src_ts` is not beyond the upper frontier,
+        // therefore all the positive diffs of the witness times must be retracted at subsequent
+        // IntoTime times.
         //
-        // Once we have considered all the diffs we will end up with a mutable antichain that
-        // contains timestamps with frequency 1 for all the IntoTimes times that `src_ts` might be
-        // reclocked to and timestamps with frequency Diff::MIN for all the IntoTimes that `src_ts`
-        // definitely is not reclocked to.
+        // This cycle may be repeated an arbitrary amount of times until the final retraction. The
```
Comment (guswynn) [inline src/storage/src/source/reclock.rs:197]: is "cycle" the write word here? its most like "these facts may be repeated

File: src/storage/src/source/reclock.rs [hunk 2]
```diff
@@ -185,29 +186,64 @@ where
...
-        // `src_ts`:
-        // * If it is, then the `FromTime` frontier at `ts` *must* be less than or equal to
-        //   `src_ts` and so we know that `src_ts` should *not* be reclocked at `ts` because it is
-        //   beyond the frontier. We codify that by adding `ts` into a mutable antichain with the
-        //   minimum frequency.
-        // * If it is not, then the `FromTime` frontier at `ts` *may* be less than or equal to
-        //   `src_ts` so `src_ts` *may* be reclocked to `ts`. We codify that by adding `ts` into a
-        //   mutable antichain with a frequency of 1.
+        // We also know that `src_ts` is beyond the since frontier, therefore there exist witness
+        // timestamps `from_ts` that are less than or equal to `src_ts` and occur at IntoTime times
```
Comment (guswynn) [inline src/storage/src/source/reclock.rs:192]: I would call it `witness_from_ts`

File: src/storage/src/source/reclock.rs [hunk 3]
```diff
@@ -185,29 +186,64 @@ where
...
+        // with a positive diff. We also know that `src_ts` is not beyond the upper frontier,
+        // therefore all the positive diffs of the witness times must be retracted at subsequent
```
Comment (guswynn) [inline src/storage/src/source/reclock.rs:194]: what if the trace is compacted to a single value, which is `==` to `src_ts`? Doesn't that mean no witness time exists? we have a positive diff for `src_ts` but no retractions at all?

File: src/storage/src/source/reclock.rs [hunk 4]
```diff
@@ -995,6 +1028,37 @@ mod tests {
...
+
+        // First mint bindings for PART0 at timestamp 1000
+        let source_upper = partitioned_frontier([(PART0, MzOffset::from(50))]);
+        follower.push_trace_batch(operator.mint(source_upper.borrow()).await);
+
+        // Then only for PART1 at timestamp 2000
+        let source_upper =
+            partitioned_frontier([(PART0, MzOffset::from(50)), (PART1, MzOffset::from(50))]);
+        follower.push_trace_batch(operator.mint(source_upper.borrow()).await);
+
```
Comment (guswynn) [inline src/storage/src/source/reclock.rs:1046]: id assert here that we correctly reclock `PART0` to `1000` as well

File: src/storage/src/source/reclock.rs [hunk 5]
```diff
@@ -185,29 +186,64 @@ where
         // We need to compute the answer by iterating over the consolidated remap trace which will
```
Comment (guswynn) [inline src/storage/src/source/reclock.rs:186]: I think it would be prudent to mention here a poignant detail, that is depended on by all the below logic:

"Note that D is reclockable _only if it is not beyond the source_upper`, which we check above. Otherwise, we cannot make make conclusions about what time it maps to that can't be later violated by the presence of more data for FromTimes that are known to be greater than D."

(please check my logic; its possible that i am being too detailed here; in some sense, the given remap collections can't really exists without the uppers being pushed ahead as well, but i want to drive home the point that `D` has to a time known to be closed, otherwise we can't reclock it. perhaps we can come up with an example.

**Review by guswynn — APPROVED** [review]
I think @aljoscha probably wants to take a look here as well; For the most part this seems reasonable, though it does do some advanced `MutableAntichain` stuff

left some small comments

**Comment by philip-stoev** [comment]
>  green CI 

The panics were present in the CI, but the process orchestrator kept restarting the storageds, thus masking the failure. In a separate PR I am going to make all panics fatal in CI, which would have exposed this issue either before or immediately after the original PR was merged.

File: src/storage/src/source/reclock.rs (hunk 3 above)
Comment (petrosagg) [reply src/storage/src/source/reclock.rs:194]: The function checks that `src_ts` is beyond the since and not beyond the upper before continuing which means that the trace must have at least two frontiers at two distinct timestamps so we can't ever have this situtation

File: src/storage/src/source/reclock.rs (hunk 5 above)
Comment (petrosagg) [reply src/storage/src/source/reclock.rs:186]: That is correct and I will add this comment, being more explicit doesn't hurt. The tests already test for this case because it's when we return `ReclockError::BeyondUpper(..)`

File: src/storage/src/source/reclock.rs (hunk 1 above)
Comment (aljoscha) [reply src/storage/src/source/reclock.rs:197]: maybe "cycle" or "pattern. I'd also maybe change "final" -> "last" or "last such"

**Review by aljoscha — APPROVED** [review]
nice! this reminds me of "Carmack's Reverse", an algorithm for computing shadows in 3D rendering (http://academickids.com/encyclopedia/index.php/Carmack%27s_Reverse, and more in-depth: http://archive.gamedev.net/archive/columns/hardcore/shadowvolume/default.html

**Comment by petrosagg** [comment]
I'll merge this to get the release process going on time and will open a separate PR to fix up the comments

**Comment by petrosagg** [comment]
@guswynn @aljoscha comments addressed here https://github.com/MaterializeInc/materialize/pull/16354
