### PR TITLE
storage/source/kafka: don't seek

### LINKED ISSUE #28016: Kafka source connected to redpanda sometimes can't recover after disruption
### What version of Materialize are you using?

64b857786a9b

### What is the issue?

Seen in https://buildkite.com/materialize/test/builds/85053#01907515-1f5b-4329-ba2f-9adbba7b9884
```
5:1: error: non-matching rows: expected:
[["2"]]
got:
[["1"]]
Poor diff:
+ 1
- 2

     |
   4 | 
   5 | > SELECT COUNT(*) FROM source1;
     | ^
+++ !!! Error Report
1 errors were encountered during execution
source: /var/lib/buildkite-agent/builds/buildkite-aarch64-small-d306b64-i-02999b8e9837166dd-1/materialize/test/test/source-sink-errors/mzcompose.py:225
```
In the logs:
```
source-sink-errors-materialized-1  | cluster-u1-replica-u1-gen-0: 2024-07-02T20:44:39.075714Z  WARN mz_kafka_util::client: failed to parse kafka error original_error="[thrd:main]: TxnCoordinator/0: Failed to add partition \"testdrive-progress-topic-2035293839\" [0] to transaction: Broker: Producer attempted to use a producer id which is not currently assigned to its transactional id"
source-sink-errors-materialized-1  | cluster-u1-replica-u1-gen-0: 2024-07-02T20:44:39.075739Z  WARN librdkafka: error: ADDPARTS [thrd:main]: TxnCoordinator/0: Failed to add partition "testdrive-progress-topic-2035293839" [0] to transaction: Broker: Producer attempted to use a producer id which is not currently assigned to its transactional id
source-sink-errors-materialized-1  | cluster-u1-replica-u1-gen-0: 2024-07-02T20:44:39.075811Z  WARN mz_kafka_util::client: failed to parse kafka error original_error="[thrd:main]: Current transaction failed in state BeginCommit: Failed to add partition(s) to transaction on broker TxnCoordinator/0: Broker: Producer attempted to use a producer id which is not currently assigned to its transactional id (after 1 ms) (INVALID_PRODUCER_ID_MAPPING, requires epoch bump)"
source-sink-errors-materialized-1  | cluster-u1-replica-u1-gen-0: 2024-07-02T20:44:39.075820Z  WARN librdkafka: error: TXNERR [thrd:main]: Current transaction failed in state BeginCommit: Failed to add partition(s) to transaction on broker TxnCoordinator/0: Broker: Producer attempted to use a producer id which is not currently assigned to its transactional id (after 1 ms) (INVALID_PRODUCER_ID_MAPPING, requires epoch bump)
```
Edit: The same logs also happen in successful runs.
I'm trying to repro with `while true; do bin/mzcompose --find source-sink-errors down && bin/mzcompose --find source-sink-errors run default kill-redpanda || break; done`. Edit: Can be reproduced easily, stays in a bad state and the source is even shown as running!:
```aterialize=> SELECT COUNT(*) FROM source1;
 count
-------
     1
(1 row)

materialize=> SELECT status, error
                  FROM mz_internal.mz_source_statuses
                  WHERE name = 'source1';
 status  | error
---------+-------
 running |
(1 row)

```

I'll try to verify if this is a regression.

ci-regexp: Disruption 'kill-redpanda' in workflow_default

### PR DESCRIPTION
**Pull request by benesch**
This commit fixes a flake observed in the source-sink-errors test
(#28016).

Here's what was happening:

  * The source would read the message with offset 1 from Kafka.
  * The source would emit the message to its data output.
  * The test would turn Redpanda off.
  * librdkafka would notice the broken connection and, incorrectly,
    redeliver the message with offset 1. (This is a known problem with
    librdkafka, and something the code already protects against.)
  * The source would seek to offset 2, thus marking its position within
    librdkafka as "invalid".
  * The source would fail to downgrade its capability to offset 2
    because librdkafka was no longer reporting a valid offset.
  * The test would turn Redpanda on.
  * librdkafka would successfully reconnect but not update the offset
    for the partition.
  * The source would not downgrade its capability to offset 2 because
    librdkafka was still not reporting a valid offset.

If a new message was written to Kafka at offset 2, then librdkafka
*would* emit the message and report a valid offset of 3, at which point
the source would downgrade its capability to offset 3, and both the
message at offset 1 and the message at offset 2 would become visible.

The flake started occurring after the upgrade to librdkafka v2.4. It's
not clear whether there was a behavior change inside of librdkafka, or
whether its simply a timing condition that always existed and somehow
became more common in the new version.

Regardless, the fix is straightforward: don't attempt to seek the
partition. librdkafka has only been observed to redeliver a single
message at a time, so there is no need to seek forward to skip messages.
We can simply receive and discard the errant messages normally.

Fix #28016.

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

### CODE REVIEW

File: src/storage/src/source/kafka.rs [hunk 1]
```diff
@@ -729,40 +729,32 @@ impl SourceRender for KafkaSourceConnection {
...
-                            // The `.position()` of the consumer represents what offset we have
-                            // read up to.
-                            snapshot_staged += offset.try_into().unwrap_or(0u64);
-                            // This will always be `Some` at this point.
-                            if let Some(snapshot_total) = snapshot_total {
-                                // We will eventually read past the snapshot total, so we need
-                                // to bound it here.
-                                snapshot_staged = std::cmp::min(snapshot_staged, snapshot_total);
-                            }
+                for (pid, last_offset) in &reader.last_offsets {
```
Comment (benesch) [inline src/storage/src/source/kafka.rs:734]: This diff is easier to read with whitespace suppressed. @petrosagg any subtlety here that I'm missing?

Comment (benesch) [reply src/storage/src/source/kafka.rs]: Had to ditch this approach. Predictably, there was a subtlety here: transaction control messages. We need to look at librdkafka's position to determine whether we've skipped over some offsets that represent transaction control messages.

File: src/storage/src/source/kafka.rs [hunk 2]
```diff
@@ -736,32 +736,40 @@ impl SourceRender for KafkaSourceConnection {
...
+                            // data capability is not beyond the progress capability and therefore a
+                            // normal downgrade would panic. Once it catches up though the data
+                            // capbility is what's pushing the progress capability forward.
+                            let _ = part_cap.progress.try_downgrade(&upper);
+                        }
+                        _ => {
+                            let partition = position.partition();
+                            let last_offset = reader.last_offsets[&partition];
+                            reader.fast_forward_consumer(partition, last_offset + 1);
+                        }
```
Comment (benesch) [inline src/storage/src/source/kafka.rs:772]: This diff is easier to read with whitespace suppressed.

**Review by def- — COMMENTED** [review]
I'm running the reproducer locally: `while true; do bin/mzcompose --find source-sink-errors down && bin/mzcompose --find source-sink-errors run default kill-redpanda || break; done` Will notify if it fails, but looking good so far.

**Comment by def-** [comment]
I didn't see the original issue, but apparently the test now runs into a different issue in the same location:
```
$ docker compose up --detach --wait redpanda
[+] Running 1/1
 ✔ Container source-sink-errors-redpanda-1  Healthy                                                  1.9s
$ docker compose exec -T testdrive testdrive --kafka-addr=kafka:9092 --schema-registry-url=http://schema-registry:8081 --materialize-url=postgres://materialize@materialized:6875 --materialize-internal-url=postgres://materialize@materialized:6877 --aws-endpoint=http://minio:9000 --var=aws-endpoint=http://minio:9000 --aws-access-key-id=minioadmin --var=aws-access-key-id=minioadmin --aws-secret-access-key=minioadmin --var=aws-secret-access-key=minioadmin --no-reset --default-timeout=360s --seed=2604355113 --persist-blob-url=file:///mzdata/persist/blob --persist-consensus-url=postgres://root@materialized:26257?options=--search_path=consensus --initial-backoff=1s --backoff-factor=0 --source=/home/deen/git/materialize2/test/source-sink-errors/mzcompose.py:226
Ingesting data into Kafka topic testdrive-source-topic-2604355113 with start_iteration = 0, repeat = 1
> SELECT COUNT(*) FROM source1;
rows didn't match; sleeping to see if dataflow catches up 1s
```
And then it's eternally stuck. Other queries against the same Mz still work though, even running the same query again. This is different from https://github.com/MaterializeInc/materialize/issues/27835 where other queries against the source would hang too. logs in case it helps: https://gist.github.com/def-/921758d350497610af9f49eb25bf777b

**Comment by def-** [comment]
Maybe that new issue is an unrelated flake though. I couldn't get it to happen again within 2 hours.

**Comment by benesch** [comment]
Yeah, I'm inclined to call that an unrelated flake. I similarly left the local reproducer running for a while and didn't observe any failures in 71 runs.

File: src/storage/src/source/kafka.rs [hunk 3]
```diff
@@ -1102,7 +1032,7 @@ impl KafkaSourceReader {
                 source_id = self.id.to_string(),
                 worker_id = self.worker_id,
                 num_workers = self.worker_count,
-                "kafka message before expected offset, skipping: \
+                "kafka message before expected offset: \
```
Comment (rjobanp) [inline src/storage/src/source/kafka.rs:1035]: the comment above `        // If we see an "old" offset, we ast-forward the consumer and skip that message` needs updating -- I couldn't comment on that line directly

**Review by rjobanp — APPROVED** [review]
this seems safe to me and your explanation aligns with the in-code comments!
