### PR TITLE
Verify that requested sink keys are a valid primary (unique) key for the sinked source/view

### LINKED ISSUE #5826: Crash on creating upsert sink
### What version of Materialize are you using?

0.7.1 dev

### How did you install Materialize?

Compiled from source

### What was the issue?

Mz crash on creating an upsert sink

### Is the issue reproducible? If so, please provide reproduction instructions.

Unsure

### Please attach any applicable log files.

materialize=> select count(1) from repl_test_v;
  count   
----------
 16777216
(1 row)

-- Looks like the error message below could be better. I missed http for the schema registry. 

materialize=> create sink sink_repl_test from repl_test_v into kafka broker 'compute2:9092' topic 'sink_repl_test_topic' with("partition_count"=1) format avro using confluent schema registry 'compute2:8081' envelope upsert with snapshot;
ERROR:  error registering kafka topic for sink: unable to publish value schema to registry in kafka sink: transport: builder error for url (compute2:%2Fsubjects/sink_repl_test_topic-u74-1613582123-10664451505501098025-value/versions): URL scheme is not allowed: builder error for url (compute2:%2Fsubjects/sink_repl_test_topic-u74-1613582123-10664451505501098025-value/versions): URL scheme is not allowed: URL scheme is not allowed

materialize=> create sink sink_repl_test from repl_test_v into kafka broker 'compute2:9092' topic 'sink_repl_test_topic' with("partition_count"=1) format avro using confluent schema registry 'http://compute2:8081' envelope upsert with snapshot;
CREATE SINK

On the kafka side, I see 2 topics for the sink. Not sure why.

2021-02-19T23:18:35.887312Z ERROR panic: primary key error: expected at most one DiffPair per timestamp
thread: timely:work-1
location: /home/mz/mz_binaries/materialize/src/ore/src/collections.rs:58:18
version: 0.7.1-dev (473f7c3c0bb5a65a3e86bbb26263a146379a1445)
backtrace:
   0: materialized::handle_panic
             at /home/mz/mz_binaries/materialize/src/materialized/src/bin/materialized/main.rs:612:21
   1: core::ops::function::Fn::call
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:70:5
   2: std::panicking::rust_panic_with_hook
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:597:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:499:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141:18
   5: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   6: std::panicking::begin_panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:437:5
   7: <T as ore::collections::CollectionExt<T>>::expect_element
             at /home/mz/mz_binaries/materialize/src/ore/src/collections.rs:58:18
   8: interchange::envelopes::upsert_format
             at /home/mz/mz_binaries/materialize/src/interchange/src/envelopes.rs:145:14
   9: dataflow::render::<impl dataflow::render::context::Context<timely::dataflow::scopes::child::Child<G,<G as timely::dataflow::scopes::ScopeParent>::Timestamp>,expr::relation::MirRelationExpr,repr::row::Row,u64>>::export_sink::{{closure}}
             at /home/mz/mz_binaries/materialize/src/dataflow/src/render/mod.rs:760:29
      differential_dataflow::collection::Collection<G,D,R>::map::{{closure}}
             at /home/mz/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/2b12f29/src/collection.rs:83:46
      <timely::dataflow::stream::Stream<S,D> as timely::dataflow::operators::map::Map<S,D>>::map::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/dataflow/operators/map.rs:57:78
      core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:280:13
      core::option::Option<T>::map
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/option.rs:453:29
      <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/iter/adapters/mod.rs:924:9
      timely::dataflow::channels::pushers::buffer::Session<T,D,P>::give_iterator
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/dataflow/channels/pushers/buffer.rs:105:21
      <timely::dataflow::stream::Stream<S,D> as timely::dataflow::operators::map::Map<S,D>>::map::{{closure}}::{{closure}}::{{closure}}
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/dataflow/operators/map.rs:57:17
      timely::dataflow::operators::generic::handles::InputHandle<T,D,P>::for_each
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/dataflow/operators/generic/handles.rs:92:13
      <timely::dataflow::stream::Stream<S,D> as timely::dataflow::operators::map::Map<S,D>>::map::{{closure}}::{{closure}}
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/dataflow/operators/map.rs:55:13
      <timely::dataflow::stream::Stream<G,D1> as timely::dataflow::operators::generic::operator::Operator<G,D1>>::unary::{{closure}}::{{closure}}
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/dataflow/operators/generic/operator.rs:402:17
      timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/dataflow/operators/generic/builder_rc.rs:123:31
      timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/dataflow/operators/generic/builder_rc.rs:163:26
      <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/dataflow/operators/generic/builder_raw.rs:203:9
  10: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/progress/subgraph.rs:655:30
  11: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/progress/subgraph.rs:338:26
      <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/progress/subgraph.rs:304:17
  12: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/progress/subgraph.rs:655:30
  13: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/progress/subgraph.rs:338:26
      <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/progress/subgraph.rs:304:17
  14: timely::worker::Wrapper::step::{{closure}}
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/worker.rs:693:57
      core::option::Option<T>::map
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/option.rs:453:29
      timely::worker::Wrapper::step
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/worker.rs:693:26
  15: timely::worker::Worker<A>::step_or_park
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/worker.rs:375:38
  16: dataflow::server::Worker<A>::run
             at /home/mz/mz_binaries/materialize/src/dataflow/src/server.rs:436:13
  17: dataflow::server::serve::{{closure}}
             at /home/mz/mz_binaries/materialize/src/dataflow/src/server.rs:197:13
      timely::execute::execute::{{closure}}
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/execute.rs:284:22
      timely_communication::initialize::initialize_from::{{closure}}
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/communication/src/initialize.rs:285:33
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:125:18
  18: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/thread/mod.rs:474:17
      <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panic.rs:322:9
      std::panicking::try::do_call
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:381:40
      std::panicking::try
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:345:19
      std::panic::catch_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panic.rs:396:14
      std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/thread/mod.rs:473:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:227:5
  19: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/unix/thread.rs:71:17
  20: start_thread
  21: __clone
    
[mz@compute1vm2 logs]$

### LINKED ISSUE #6526: Kafka sink with ENVELOPE UPSERT cannot handle multiple updates at the same timestamp
When using the RT timestamper and ingesting a lot of data at once it can happen that messages with the same key get assigned the same timestamps. The sink currently panics on those: https://github.com/MaterializeInc/materialize/blob/3dc3354a649993ae739626dfa9b84a754b884462/src/interchange/src/envelopes.rs#L145

For testing, it's even enough to just have two messages in the input topic that have the same key. Also, the key here refers to the `KEY` that is configured on the sink.

I believe the reason for this is that the `combine_at_timestamp()` consumes raw change batches:
https://github.com/MaterializeInc/materialize/blob/9218c98f8577c705db86d410c2e3b2244a425fb1/src/dataflow/src/render/sinks.rs#L97

These don't go through consolidation/arrangement, I think.

Source/sink definitions, for reference, I find it easiest to test things using testdrive:
```
> CREATE SOURCE source_insertavrotest
  FROM KAFKA BROKER '${testdrive.kafka-addr}'
  TOPIC 'upsertavrotest-big'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
  ENVELOPE NONE

> CREATE SINK kafka_sink FROM source_insertavrotest
  INTO KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'output-sink-${testdrive.seed}'
  KEY (a)
  WITH (consistency=true)
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
  ENVELOPE UPSERT
```

Input are simple messages with schema `(a BIGINT, b BIGINT)`.

### PR DESCRIPTION
**Pull request by aljoscha**
Individual commits have meaningful commit messages.

The interesting parts are:
 - I'm changing the `kafka-verify` testdrive action to allow `NULL` keys. The syntax for that might seem iffy and an explicit `{"key": 1} NULL` could be better.
 - Until now, we didn't have tests for UPSERT sinks. Most of the code paths are shared with DEBEZIUM sinks. I created tests for UPSERT based on the DEBEZIUM tests but only duplicated those tests where UPSERT behaviour differs. We could consider fully pulling those tests apart, maybe even parameterising the common tests with an UPSERT/DEBEZIUM parameter, though we don't have the infra for that right now.
 - There is some interesting behaviour for DEBEZIUM, when it comes to keys, that the tests now also pin.
 - The actual check for whether the key is correct

This closes #6526.
This closes #5826.

### CODE REVIEW

**Comment by aljoscha** [comment]
also cc @philip-stoev for the new tests.

File: src/sql/src/plan/statement/ddl.rs [hunk 1]
```diff
@@ -1387,6 +1387,34 @@ pub fn plan_create_sink(
                         Ok(name_idx)
                     })
                     .collect::<Result<Vec<_>, _>>()?;
+                let is_valid_key =
+                    desc.typ().keys.iter().any(|key_columns| {
+                        key_columns.iter().all(|column| indices.contains(column))
+                    });
```
Comment (umanwizard) [inline src/sql/src/plan/statement/ddl.rs:1393]: Why is it necessary to do this check for non-upsert sources? I don't believe our other sources rely on the property of the Kafka key being a primary key.

Comment (aljoscha) [reply src/sql/src/plan/statement/ddl.rs:1393]: They don't rely on it, yes. I went for simplicity/uniformity but I think you're right that we shouldn't remove this allowed behaviour for other sinks.

Comment (aljoscha) [reply src/sql/src/plan/statement/ddl.rs:1393]: On second thought: does this make sense?

```
> CREATE MATERIALIZED SOURCE input_keyed2
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-input-keyed2-${testdrive.seed}'
  FORMAT AVRO USING SCHEMA '${schema}' ENVELOPE DEBEZIUM

> CREATE VIEW maxes2 AS SELECT a, max(b) AS b FROM input_keyed2 GROUP BY a

> CREATE SINK output_keyed2 FROM maxes2
  INTO KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'output-sink-keyed2-${testdrive.seed}'
  KEY (b)
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}' ENVELOPE DEBEZIUM

$ kafka-ingest format=avro topic=input-keyed2 schema=${schema} timestamp=1
{"before": null, "after": {"row": {"a": 1, "b": 1}}}
{"before": null, "after": {"row": {"a": 1, "b": 2}}}
{"before": null, "after": {"row": {"a": 1, "b": 3}}}

$ kafka-verify format=avro sink=materialize.public.output_keyed2
{"b": 3} {"before": null, "after": {"row": {"a": 1, "b": 3}}}

$ kafka-ingest format=avro topic=input-keyed2 schema=${schema} timestamp=1
{"before": {"row": {"a": 1, "b": 3}}, "after": null}
{"before": {"row": {"a": 1, "b": 2}}, "after": null}
{"before": null, "after": {"row": {"a": 2, "b": 1}}}

$ kafka-verify format=avro sink=materialize.public.output_keyed2
{"b": 1} {"before": null, "after": {"row": {"a": 1, "b": 1}}}
{"b": 1} {"before": null, "after": {"row": {"a": 2, "b": 1}}}
```

If you key by `a` the updates contained in the sink propose a different view of the world, which intuitively seems to make more sense to me:

```
> CREATE MATERIALIZED SOURCE input_keyed
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-input-keyed-${testdrive.seed}'
  FORMAT AVRO USING SCHEMA '${schema}' ENVELOPE DEBEZIUM

> CREATE VIEW maxes AS SELECT a, max(b) AS b FROM input_keyed GROUP BY a

> CREATE SINK output_keyed FROM maxes
  INTO KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'output-sink-keyed-${testdrive.seed}'
  KEY (a)
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}' ENVELOPE DEBEZIUM

$ kafka-ingest format=avro topic=input-keyed schema=${schema} timestamp=1
{"before": null, "after": {"row": {"a": 1, "b": 1}}}
{"before": null, "after": {"row": {"a": 1, "b": 2}}}
{"before": null, "after": {"row": {"a": 1, "b": 3}}}

$ kafka-verify format=avro sink=materialize.public.output_keyed
{"a": 1} {"before": null, "after": {"row": {"a": 1, "b": 3}}}

$ kafka-ingest format=avro topic=input-keyed schema=${schema} timestamp=1
{"before": {"row": {"a": 1, "b": 3}}, "after": null}
{"before": {"row": {"a": 1, "b": 2}}, "after": null}
{"before": null, "after": {"row": {"a": 2, "b": 1}}}

$ kafka-verify format=avro sink=materialize.public.output_keyed sort-messages=true
{"a": 2} {"before": null, "after": {"row": {"a": 2, "b": 1}}}
{"a": 1} {"before": {"row": {"a": 1, "b": 3}}, "after": {"row": {"a": 1, "b": 1}}}

```

Comment (aljoscha) [reply src/sql/src/plan/statement/ddl.rs:1393]: Ah sorry, the output for that first case is also correct: I forgot to check for the last update, which is:
```
$ kafka-verify format=avro sink=materialize.public.output_keyed2
{"b": 1} {"before": null, "after": {"row": {"a": 1, "b": 1}}}
{"b": 1} {"before": null, "after": {"row": {"a": 2, "b": 1}}}
{"b": 3} {"before": {"row": {"a": 1, "b": 3}}, "after": null}
```

It just feels a bit weird.

Comment (aljoscha) [reply src/sql/src/plan/statement/ddl.rs:1393]: Also: probably just ignore my last comments. I think it's good to just allow arbitrary keys for DEBEZIUM.

**Comment by aljoscha** [comment]
I changed this to only check on UPSERT sinks. I also pulled the tests apart further into a "generic avro sinks" part, a DEBEZIUM part and an UPSERT part.

Could you please take another look?

**Review by umanwizard — APPROVED** [review]

File: test/testdrive/kafka-avro-upsert-sinks.td [hunk 2]
```diff
@@ -0,0 +1,252 @@
...
+  USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}' ENVELOPE UPSERT
+Invalid upsert key: (b), valid keys are: (a)
+
+> CREATE VIEW input_keyed_ab AS SELECT a, b FROM input GROUP BY a, b
+
+! CREATE SINK invalid_sub_key FROM input_keyed_ab
+  INTO KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'input-sink' KEY (a)
+  WITH (consistency = true) FORMAT AVRO
+  USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}' ENVELOPE UPSERT
+Invalid upsert key: (a), valid keys are: (a, b)
```
Comment (philip-stoev) [inline test/testdrive/kafka-avro-upsert-sinks.td:252]: Thank you for the tests! If you can, can you please add some for multi-part keys, that is, a source has a multi-part key and the sink should fail if the requested key is not strictly identical to the source key (so not a prefix of, a subset/superset or permutation thereof). That would be much appreciated!

Comment (aljoscha) [reply test/testdrive/kafka-avro-upsert-sinks.td:252]: You mean to use an actual source in addition to using a `VIEW` as I do here? I can do that, for sure!

Regarding keys, we explicitly allows specifying a key `(a, b)` for the sink when the collection is keyed only by `(a)` because that will also be a unique key. And in this test right here we test that `(a)` is not accepted when the unique key is `(a, b)`. Should I add a test to verify that `(b)` is also rejected?

Comment (philip-stoev) [reply test/testdrive/kafka-avro-upsert-sinks.td:252]: Yes, I think a test with a multi-part source would be nice. Multi-part keys of any kind are usually underrepresented in tests  but are actually seen in real life (with up to 5  parts nonetheless!) so lets add them whenever possible.

Yes you are right, (a, b) should be accepted. If you can add a test for (b) that would be much appreciated.

**Review by philip-stoev — APPROVED** [review]
Thanks!

**Comment by aljoscha** [comment]
It seems we might have gone a bit over board with this: @krishmanoh2 reported cases where he was surprised by the new stricter checking not allowing UPSERT sinks that he as a user knows should work.

The problem is (as @umanwizard pointed out before) that the optimizer is not good at knowing what a primary key of a view will be. For example, assume we have a `user_ids` table that has `user_id` as primary key. We cannot sinks this view into an UPSERT sink even though we know that this will work:

```
CREATE view users_view AS select ids.user_id, u.name FROM users_ids ids, users u WHERE ids.user_id = u.user_id;
```

That's very unfortunate because this fixed https://github.com/MaterializeInc/materialize/issues/5826, which is sneaky and can work at runtime until you encounter a case where there's two matching upserts at the same timestamp. Failing at runtime after a sink is already created is not a good experience.

I can roll back the strict checking but keep some of the refactoring of this PR. This re-opens the two linked issues and I don't yet know of a better fix other than an improved error message.

**Comment by frankmcsherry** [comment]
How does this connect to #6780 which I thought was a relaxation of this (use user-specified keys if available)?
