### PR TITLE
adapter: Fix panic on query cancel

### LINKED ISSUE #15179: adapter: panic: `Result::unwrap()` on an `Err` value: InstanceMissing(1)'
1. Started everything locally.
2. In terminal A, run `create table t (); select * from t as of 18446744073709551615;` and let it hang
3. In terminal B, run `drop cluster default`
4. In terminal A, press ctrl^c to cancel the select.

envd panics:

```
thread 'coordinator' panicked at 'called `Result::unwrap()` on an `Err` value: InstanceMissing(1)', /home/mjibson/materialize/src/adapter/src/coord/peek.rs:606:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1814:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1107:23
   4: mz_adapter::coord::peek::<impl mz_adapter::coord::Coordinator<S>>::cancel_pending_peeks::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/peek.rs:602:17
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
   6: mz_adapter::coord::peek::<impl mz_adapter::coord::Coordinator<S>>::cancel_pending_peeks::{{closure}}
             at ./src/adapter/src/coord/peek.rs:592:5
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
   8: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_cancel::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:513:52
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  10: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_command::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:93:56
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  12: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_command::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:165:33
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  14: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_command::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:162:5
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  16: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_message::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:40:63
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  18: mz_adapter::coord::Coordinator<S>::serve::{{closure}}
             at ./src/adapter/src/coord.rs:801:37
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  20: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:54
  21: tokio::coop::with_budget::{{closure}}
             at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:102:9
  22: std::thread::local::LocalKey<T>::try_with
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:445:16
  23: std::thread::local::LocalKey<T>::with
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:421:9
  24: tokio::coop::with_budget
             at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:95:5
  25: tokio::coop::budget
             at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:72:5
  26: tokio::park::thread::CachedParkThread::block_on
             at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:31
  27: tokio::runtime::enter::Enter::block_on
             at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/enter.rs:151:13
  28: tokio::runtime::handle::Handle::block_on
             at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/handle.rs:296:9
  29: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./src/adapter/src/coord.rs:946:17
```

### PR DESCRIPTION
**Pull request by jkosh44**
Previously, if a cluster was dropped mid-query, the query would hang forever and would then panic if it gets cancelled. This commit fixes the panic, however the query still hangs forever until it's canceled.

Fixes #15179

### Motivation
This PR fixes a recognized bug.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Comment by jkosh44** [comment]
I'm actually having trouble even writing a rust test for this. I have the following, which is very close:
```Rust
#[test]
fn test_cancel_on_dropped_cluster() {
    let config = util::Config::default().unsafe_mode();
    let server = util::start_server(config).unwrap();
    let mut read_client = server.connect(postgres::NoTls).unwrap();
    let read_client_cancel = read_client.cancel_token();

    let handle = thread::spawn(move || {
        read_client.batch_execute("CREATE TABLE t ()").unwrap();
        read_client
            .query_one("SELECT * FROM t AS OF 18446744073709551615", &[])
            .unwrap();
    });

    let mut drop_client = server.connect(postgres::NoTls).unwrap();
    drop_client.batch_execute("DROP CLUSTER default").unwrap();
    read_client_cancel.cancel_query(postgres::NoTls).unwrap();
    handle.join().unwrap();
}
```

However we need to somehow block the `DROP CLUSTER` until after the `SELECT * FROM t AS OF 18446744073709551615` has started. I'm not sure how to accomplish that without adding a sleep and crossing my fingers.

File: src/adapter/src/coord/peek.rs [hunk 1]
```diff
@@ -490,10 +490,14 @@ impl<S: Append + 'static> crate::coord::Coordinator<S> {
                 inverse.entry(*compute_instance).or_default().insert(*uuid);
             }
             for (compute_instance, uuids) in inverse {
-                self.controller
+                // It's possible that this compute instance no longer exists because it was dropped
+                // while the peek was in progress. In this case we ignore the error and move on
+                // because the dataflow no longer exists.
+                // TODO(jkosh44) Dropping a cluster should actively cancel all pending queries.
```
Comment (jkosh44) [inline src/adapter/src/coord/peek.rs:496]: FYI, I played around with this locally for a bit. It's very possible that this isn't possible because `psql` doesn't know how to handle query cancelled responses that weren't initiated by `psql`. In fact it may be against the pgwire protocol since no cancel request was sent in the first place.

Another option would be to send a notice to the query that it should try and cancel because the cluster no longer exists.

Comment (mjibson) [reply src/adapter/src/coord/peek.rs:496]: I'm not sure how psql works under the covers here, but I would imagine that it's able to handle cancel query requests coming from anything, because they present as a regular error response. Was that not your experience? Also you showed me some postgres session txn timeout code earlier where the timeout would send a cancelled error, which is the same error as from a cancel request connection.

**Review by mjibson — APPROVED** [review]
> However we need to somehow block the DROP CLUSTER until after the SELECT * FROM t AS OF 18446744073709551615 has started. I'm not sure how to accomplish that without adding a sleep and crossing my fingers.

Can we do this using a retry loop on one of the mz_catalog or mz_internal tables that track pending peeks (is there even such a table or am I making this up?).

File: src/adapter/src/coord/peek.rs (hunk 1 above)
Comment (jkosh44) [reply src/adapter/src/coord/peek.rs:496]: Oh yeah that's a good point, I must  have been doing something wrong then. When I tried the query was just hanging. I'll open an issue after merging this to cancel outstanding queries.
