### PR TITLE
compute: report errors through subscribe sinks

### LINKED ISSUE #6292: Errors not propagated to SUBSCRIBE
### What version of Materialize are you using?

```
v0.7.2-dev (375d3a5a7)
```

### What was the issue?

If a client does a TAIL on a source that has errored out, the error is never reported to the client. Tail proceeds as if the error never happened at all. I think this is wrong.

### Is the issue reproducible? If so, please provide reproduction instructions.

In testdrive, create a source that has an error:

```
$ set null={"type": "record", "name": "field_null", "fields": [ {"name": "f1", "type": "null"} ] }
$ set int={"type": "record", "name": "field_int", "fields": [ {"name": "f1", "type": "int"} ] }

$ kafka-create-topic topic=tail-source-error

$ kafka-ingest format=avro topic=tail-source-error schema=${int} timestamp=1
{"f1": 123}

> CREATE MATERIALIZED SOURCE source_error
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-tail-source-error-${testdrive.seed}'
  FORMAT AVRO USING SCHEMA '${int}'
  ENVELOPE NONE

$ kafka-ingest format=avro topic=tail-source-error schema=${null} timestamp=1
{"f1": null}

$ kafka-ingest format=avro topic=tail-source-error schema=${int} timestamp=1
{"f1": 234}

! SELECT * FROM source_error;
avro deserialization error: IO error: UnexpectedEof
```

As you can see, SELECT-ing from such a source produces an error, as expected. Then ,in the postgesql client, do:

```
materialize=> COPY (TAIL source_error) TO STDOUT;
1617266299000	1	123
1617266299000	1	234
```

Rows ingested before and after the error are returned as if the error never happened. I think the TAIL should have errored out.

### PR DESCRIPTION
**Pull request by teskje**
Prior to this change, subscribe sinks did not know how to handle dataflow errors in their input and simply ignored them. This could potentially cause correctness issues, since it is not clear what semantics a dataflow's `ok` collection has when the `err` collection is not empty.

This commit makes the subscribe sink handle errors by piggy-backing on the existing subscribe error reporting support originally introduced to error on too-large results. This way of error reporting is somewhat unsatisfactory, since it does not allow retraction of errors. At the moment this is fine, since adapter aborts subscribes upon seeing the first error anyway. Better subscribe error reporting is tracked in issue #17781.

### Motivation

  * This PR fixes a recognized bug.

Fixes #6292.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - Change `SUBSCRIBE` to report and abort on errors discovered in the target collection.

### CODE REVIEW

File: src/compute/src/sink/subscribe.rs [hunk 1]
```diff
@@ -95,48 +96,76 @@ fn subscribe<G>(
...
-                            as_of.frontier.less_than(&time)
-                        } else {
-                            as_of.frontier.less_equal(&time)
-                        };
-                        let should_emit = should_emit_as_of && !up_to.less_equal(&time);
-                        if should_emit {
-                            results.push((time, row, diff));
+
+                let mut frontier = ok_input.frontier().frontier().to_owned();
+                frontier.extend(err_input.frontier().frontier().iter().copied());
```
Comment (teskje) [inline src/compute/src/sink/subscribe.rs:119]: Is this the best way of computing the meet of two `MutableAntichain`s?

**Review by vmarcos — APPROVED** [review]
This seems fine to me, given that the follow-up work is already tracked in #17781. One minor typo comment below.

**Comment by teskje** [comment]
TFTR!
