### PR TITLE
explain: support `mz_now()` on select from indexed table

### LINKED ISSUE #19148: explain: OneShot plan has temporal constraints
### What version of Materialize are you using?

main

### What is the issue?

Minimal reproduction:

```sql
materialize=> create table t (a timestamp);
CREATE TABLE
materialize=> create default index on t;
CREATE INDEX
materialize=> explain select * from t where a < mz_now();
ERROR:  OneShot plan has temporal constraints
```

The query itself works as expected, so this is only an issue in our EXPLAIN code.

### Initial Diagnosis

The issue occurs in the explain sequencing code where we check whether the target query uses the fast path: https://github.com/MaterializeInc/materialize/blob/1edab459b447bbd7bdc114e434f3dd58497ded2f/src/adapter/src/coord/sequencer/inner.rs#L2687

`create_fast_path_plan` calls `permute_oneshot_mfp_around_index`:
https://github.com/MaterializeInc/materialize/blob/1edab459b447bbd7bdc114e434f3dd58497ded2f/src/adapter/src/coord/peek.rs#L218

... which in turn expects the passed MFP to not contain any non-temporal expressions:
https://github.com/MaterializeInc/materialize/blob/1edab459b447bbd7bdc114e434f3dd58497ded2f/src/adapter/src/coord/peek.rs#L164-L165

It seems like the explain sequencing code needs to do the work of replacing `mz_now()` expressions before calling `create_fast_path_plan`, as the peek sequencing code does.

### PR DESCRIPTION
**Pull request by aalexandrov**
Opening this for discussion as a possible fix for #19148.

### Motivation

  * This PR fixes a recognized bug.

Fixes #19148 in a somewhat ad-hoc way. Hopefully we can arrive at a more stable solution as an outcome of #18089 and #18496.

### Tips for reviewer

1. I am calling `self.sequence_peek_timestamp` if the explainee is a `Query`.
2. The call hard-codes `when = &QueryWhen::Immediately` and `real_time_recency_ts = None`. I am not aware of contexts where this might be causing explain output that is inconsistent with the `sequence_~` logic.
3. I am also passing an extra `target_cluster: TargetCluster` to `sequence_explain` / `sequence_explain_plan` (this is needed in order to faithfully compute the `cluster_id` for one-shot selects).

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - The `EXPLAIN` output now inlines values of unmaterializable functions for fast path plans rendered for the `EXPLAIN OPTIMIZED PLAN` stage and physical plans rendered for the `EXPLAIN PHYSICAL PLAN` stage.

### CODE REVIEW

File: src/adapter/src/coord/sequencer/inner.rs [hunk 1]
```diff
@@ -2694,7 +2694,30 @@ impl Coordinator {
 
             // Determine if fast path plan will be used for this explainee
             let fast_path_plan = match explainee {
-                Explainee::Query => peek::create_fast_path_plan(&mut dataflow, GlobalId::Explain)?,
+                Explainee::Query => {
+                    let timestamp_context = self
```
[the remark this answers is not in the document]
Comment (jkosh44) [reply src/adapter/src/coord/sequencer/inner.rs:2698]: We recently refactored peek into multiple stages, see `sequence_peek_stage` in this file. I'm assuming that `EXPLAIN` should behave identically to peek, except stop executing at a certain point. For example `EXPLAIN QUERY` stops right before sending the dataflow to compute (I just made this up, I'm not familiar with the actual explain stages). I think that `EXPLAIN` should use the same peek stages as peeks, but selectively opt out of certain stages.

[the remark this answers is not in the document]
Comment (jkosh44) [reply src/adapter/src/coord/sequencer/inner.rs:2698]: In that case I still think it makes sense for `EXPLAIN`s with a `SELECT` `EXPLAINEE` to re-use the peek stages to generate the appropriate metadata for the select. Otherwise we should just copy and past the logic.

[the remark this answers is not in the document]
Comment (aalexandrov) [reply src/adapter/src/coord/sequencer/inner.rs:2722]: I managed to get this working.

Overall, keeping the compilation pipeline for the `sequence_<do something>` and `sequence_explain_plan` for that same thing in sync is getting a bit unwieldy. We have some tracking issues for the main problem from our side #18089, and hopefully some of those can be addressed by #18496. Hopefully we can allocate some time for that in the next months.

File: test/sqllogictest/explain/optimized_plan_as_text.slt [hunk 2]
```diff
@@ -753,3 +753,26 @@ Source materialize.public.r
...
+CREATE TABLE t(a TIMESTAMP);
+
+statement ok
+CREATE DEFAULT INDEX ON t;
+
+query T multiline
+EXPLAIN SELECT * FROM t WHERE a < mz_now();
+----
+Explained Query (fast path):
+  Filter (timestamp_to_mz_timestamp(#0) < 1683652808481)
```
Comment (mjibson) [inline test/sqllogictest/explain/optimized_plan_as_text.slt:772]: I find this output a bit odd because we have actually executed part of this query, and are not explaining it. I assume the underlying problem is we can't keep this as `mz_now()`?

Comment (aalexandrov) [reply test/sqllogictest/explain/optimized_plan_as_text.slt:772]: > I find this output a bit odd

Me too!

> I assume the underlying problem is we can't keep this as `mz_now()`?

Yes. More precisely the `create_fast_path_plan` that we call to get the output of this test expects to see a `SafeMfp` which is only possible if we inline the value of `mz_now()`.

Comment (aalexandrov) [reply test/sqllogictest/explain/optimized_plan_as_text.slt:772]: Urgh, it's even worse - this test will always produce a different output on each run...

Comment (aalexandrov) [reply test/sqllogictest/explain/optimized_plan_as_text.slt:772]: I might be able to do a super ugly hack and just replace whatever the current TS is with `mz_now()` in the emitted fast path explain output.

File: src/adapter/src/coord/sequencer/inner.rs [hunk 3]
```diff
@@ -2694,7 +2718,30 @@ impl Coordinator {
...
+                        .sequence_peek_timestamp(
+                            session,
+                            &QueryWhen::Immediately,
+                            cluster_id,
+                            timeline_context,
+                            &id_bundle,
+                            &source_ids,
+                            None, // no real-time recency
```
Comment (jkosh44) [inline src/adapter/src/coord/sequencer/inner.rs:2730]: This is somewhat of a lie, if the user has real-time recency enabled, then I'd expect that to be reflected in `EXPLAIN SELECT ... ` and `SELECT ...`.

Probably not a huge deal right now since real-time recency isn't finished.

File: test/sqllogictest/explain/optimized_plan_as_text.slt (hunk 2 above)
Comment (mjibson) [reply test/sqllogictest/explain/optimized_plan_as_text.slt:772]: You can also use testdrive with a regex replace to support changing timestamps.

File: test/sqllogictest/explain/optimized_plan_as_text.slt [hunk 4]
```diff
@@ -753,3 +753,26 @@ Source materialize.public.r
   filter=((#0) IS NOT NULL AND (#2) IS NOT NULL AND (#3) IS NOT NULL AND (#4) IS NOT NULL AND (#6) IS NOT NULL AND (#8) IS NOT NULL AND (#9) IS NOT NULL AND (#11) IS NOT NULL AND (#12) IS NOT NULL AND (#13) IS NOT NULL AND (#15) IS NOT NULL AND (#16) IS NOT NULL)
 
 EOF
+
+
+# Regression test for #19148: EXPLAIN path should refle
```
Comment (teskje) [inline test/sqllogictest/explain/optimized_plan_as_text.slt:758]: This comment got cut.

File: test/sqllogictest/explain/optimized_plan_as_text.slt (hunk 2 above)
Comment (teskje) [reply test/sqllogictest/explain/optimized_plan_as_text.slt:772]: I find this format fine. At least in my mental model, the explain output reflects what is executed in the compute dataflow (module some parts like `Finishing`) and the dataflow does not invoke `mz_now()`. It's also in line with other instances where the optimizer evaluates expressions during optimization, e.g.:
```sql
materialize=> explain select max(i) from (values (1), (2), (3)) as t(i);
        Optimized Plan
------------------------------
 Explained Query (fast path):+
   Constant                  +
     - (3)                   +
```

But I appreciate that my mental model doesn't necessary match that of our users.

File: src/adapter/src/coord/sequencer/inner.rs (hunk 3 above)
Comment (aalexandrov) [reply src/adapter/src/coord/sequencer/inner.rs:2730]: I'll see if I can enable this.

**Review by teskje — APPROVED** [review]
This looks like a reasonable fix for the bug. I agree that we'll want to come up with a way to unify the explain pipeline with the regular planning pipeline in the long-term.

File: test/sqllogictest/explain/optimized_plan_as_text.slt (hunk 2 above)
Comment (aalexandrov) [reply test/sqllogictest/explain/optimized_plan_as_text.slt]: > Urgh, it's even worse - this test will always produce a different output on each run...

I changed the test to run only `statement ok` (it is enough to prevent the regression from the resolved issue).

File: src/adapter/src/coord/sequencer/inner.rs (hunk 3 above)
Comment (jkosh44) [reply src/adapter/src/coord/sequencer/inner.rs:2731]: > I can either make everything up to `sequence_explain` async

I think this is probably a bad idea, it will do the waiting on the main coord thread which will block everything else from running. 

> leave the code as is.

I think this is the best solution for now as long as we're ok not keeping `EXPLAIN` and `SELECT` in synce.

**Review by jkosh44 — APPROVED** [review]

File: src/adapter/src/coord/sequencer/inner.rs (hunk 3 above)
Comment (mjibson) [reply src/adapter/src/coord/sequencer/inner.rs:2731]: I concur with Joe, but would say it even more strongly: absolutely do not do the above thing by calling await on the recent_timestamp future. If we do need this in the future, it's gotta use the off thread machinery.
