### PR TITLE
storage: abort sink task when dataflow is dropped

### LINKED ISSUE #25833: storage/sinks/kafka: failing kafka/ssh sink can crashloop replica [incident 100]
In incident 100, we saw a cluster with a Kafka-over-SSH sink that was failing to publish its schema to the schema registry cause the cluster to enter a very slow OOM loop—about once every two hours. There were actually three sinks on the cluster, and I _think_ they were all in the same schema registry fail loop

Our investigation indicated that librdkafka threads and sockets were piling up. See the Slack conversation for details: https://materializeinc.slack.com/archives/C06NCJ8B23W/p1709763502099829

My hunch is that we're leaking rdkafka handles during suspend and restart events. Not sure whether the SSH tunnels are relevant.

### PR DESCRIPTION
**Pull request by petrosagg**
The code to determinte the upper that a sink should resume at was spawning at task whose "lifetime" was independent of its parent task. This could lead to a whole lot of long running tasks that were not aborted on time.
Fixes #25833

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by sploiselle** [comment]
cc @def-

**Review by guswynn — APPROVED** [review]
pretty clean!

**Comment by def-** [comment]
I'm checking if I can still get the OoM with https://github.com/MaterializeInc/materialize/pull/25849#issuecomment-1985470258 and this PR.

File: src/storage-client/src/sink.rs [hunk 1]
```diff
@@ -634,7 +634,7 @@ pub async fn determine_sink_resume_upper(
         // the high water mark, and therefore `last_timestamp` contains the
         // most recent timestamp for the sink under consideration.
         Ok(last_upper)
-    }).await.unwrap().check_ssh_status(&ctx)
+    }).abort_on_drop().await.unwrap().check_ssh_status(&ctx)
```
Comment (benesch) [inline src/storage-client/src/sink.rs:637]: Does this have any effect? The docs on `spawn_blocking` have this to say:

> Closures spawned using spawn_blocking cannot be cancelled abruptly; there is no standard low level API to cause a thread to stop running. However, a useful pattern is to pass some form of “cancellation token” into the thread. This could be an [AtomicBool](https://doc.rust-lang.org/nightly/core/sync/atomic/struct.AtomicBool.html) that the task checks periodically. Another approach is to have the thread primarily read or write from a channel, and to exit when the channel closes; assuming the other side of the channel is dropped when cancellation occurs, this will cause the blocking task thread to exit soon after as well.

> When you shut down the executor, it will wait indefinitely for all blocking operations to finish. You can use [shutdown_timeout](https://docs.rs/tokio/latest/tokio/runtime/struct.Runtime.html#method.shutdown_timeout) to stop waiting for them after a certain timeout. Be aware that this will still not cancel the tasks — they are simply allowed to keep running after the method returns. It is possible for a blocking task to be cancelled if it has not yet started running, but this is not guaranteed.

**Comment by def-** [comment]
> I'm checking if I can still get the OoM with [#25849 (comment)](https://github.com/MaterializeInc/materialize/pull/25849#issuecomment-1985470258) and this PR.

Memory consumption seems to stay < 4 GB now, so seems to be fixed! (Will keep it running for a bit though and report if memory unexpectedly increases)

File: src/storage-client/src/sink.rs (hunk 1 above)
Comment (guswynn) [reply src/storage-client/src/sink.rs:637]: Oh I though this was a normal tokio task; yeah I don't think this does anything

Comment (petrosagg) [reply src/storage-client/src/sink.rs:637]: duh, thanks for catching this! I wired up a cancellation token as the docs suggest. But also, why do blocking tasks have an `.abort()` method that does nothing? What is this, Javascript?

**Comment by petrosagg** [comment]
@def- I think I wired it up correctly now

File: src/storage-client/src/sink.rs (hunk 1 above)
Comment (guswynn) [reply src/storage-client/src/sink.rs]: @petrosagg its because they share the `JoinHandle` type, and fixing that is a breaking change :(

**Comment by def-** [comment]
I'm still seeing my test OoM, so maybe it is not actually showing what this is fixing?

**Comment by sploiselle** [comment]
@def- Incident 100 was caused by a sink getting partitioned away from the CSR so it was never able to publish its schema and was continually restarting. I'm wondering if your test is a way that we fall over when we try to perform a snapshot that's too large to successfully commit?

**Comment by def-** [comment]
I did check that my check was hitting CSR periodically to try and republish (and fail), but still possible I guess.

File: src/storage-client/src/sink.rs [hunk 2]
```diff
@@ -451,8 +452,15 @@ pub async fn determine_sink_resume_upper(
     .await
     .add_context("error registering kafka progress topic for sink")?;
 
+    // We are about to spawn a blocking task that cannot be aborted by simply calling .abort() on
+    // its handle but we must be able to cancel it prompty so as to not leave long running
+    // operations around when interest to this task is lost. To accomplish this we create a dummy
+    // channel whose connectivity (i.e existence of a sending end) signals interest in the
+    // computation and the computation regularly checks whether the channel is still connected,
+    // aborting its computation when that ceases to be the case.
+    let (tx, rx) = std::sync::mpsc::channel::<()>();
```
[the remark this answers is not in the document]
Comment (petrosagg) [reply src/storage-client/src/sink.rs:461]: I mean.. it should be a `zeroshot` if one wants to be pedantic. It doesn't really matter, it's a ZST channel that never sends anything

**Review by benesch — APPROVED** [review]
This seems worth doing, but I'm dubious that it fixes https://github.com/MaterializeInc/materialize/issues/25833. I don't think we have any particular evidence that this was the cause of #25833, do we?

**Comment by sploiselle** [comment]
@benesch The memory profile [linked to in Slack when the bug occurred](https://materializeinc.slack.com/archives/C06NCJ8B23W/p1709763502099829) showed that we were spending a lot of time in a `BaseConsumer` thread which, in the context of a sink, only gets created in `determine_sink_resume_upper`. This realization was how Petros found that we weren't properly closing the function's interior tasks when dropping the sink's dataflow.

**Comment by benesch** [comment]
Ah, ok. That _is_ fairly compelling...

**Comment by benesch** [comment]
Alright, I think I have the final piece of the puzzle. (Apologies if this was already known to y'all.) I've been scratching my head trying to figure out why the `determine_sink_resume_upper` wouldn't exit reasonably promptly. After all, completion of that task is required for the sink to initialize, so how long could it really be taking?

Well, logs from the affected sink at the time of the incident indicate that there are _50 million_ progress records!

```
fetching latest progress record for mz-sink-uXXXX, lo/hi: 0/50720773
```

That could easily take multiple minutes—enough time for the sink to restart repeatedly, resulting in several of these tasks piling up, and ultimately overwhelming the cluster.

**Comment by benesch** [comment]
@petrosagg @guswynn what do y'all think about adding Prometheus metrics here for the low and high water mark of each Kafka connection, updated whenever we fetch watermarks in `determine_sink_resume_upper`? That will give us some internal visibility into whether compaction is properly enabled for a given sink's progress topic. Those metrics, coupled with the fix in this PR, will make me _very_ comfortable calling #25833 complete.

**Comment by benesch** [comment]
Probably also want a metric for number of seconds spent in `determine_sink_resume_upper`.

**Comment by guswynn** [comment]
@benesch all 3 of those metrics seem worth the effort!

File: src/storage-client/src/sink.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (petrosagg) [reply src/storage-client/src/sink.rs]: I changed this to be a pair of `Arc<()>` and `Weak<()>`

File: src/storage-client/src/sink.rs [hunk 3]
```diff
@@ -584,57 +606,86 @@ pub async fn determine_sink_resume_upper(
...
         let mut last_upper = None;
-        while get_position()? < hi {
-            let message = match progress_client_read_committed.poll(progress_record_fetch_timeout) {
-                Some(Ok(message)) => message,
-                Some(Err(KafkaError::PartitionEOF(_))) => {
-                    // No message, but the consumer's position may have advanced
-                    // past a transaction control message that positions us at
-                    // or beyond the high water mark. Go around the loop again
-                    // to check.
+        const CHUNK_SIZE: i64 = 2048;
```
Comment (petrosagg) [inline src/storage-client/src/sink.rs:610]: Any takes for what is a sensible value for this parameter?

Comment (guswynn) [reply src/storage-client/src/sink.rs:611]: This seems like a good start!

can you make it a `dyncfg`? `mz_storage_types::dyncfgs` should make this way easier than the past

Comment (benesch) [reply src/storage-client/src/sink.rs:611]: Yeah agreed on making this a dyncfg! Then we don't need to think about it too deeply to start.

**Review by benesch — APPROVED** [review]
I can't find any faults with the new logic. I'm still a bit nervous to change it, given how many bugs we had to squash in it previously, and I don't feel _great_ about the complexity given that it doesn't help speed up the case of a new sink, which is the moment you're most likely to be paying attention. On the other hand, it does mitigate the latency of recovery after the maintenance window or a cluster crash... but then on the other other hand maybe it's _good_ to have sink startup be universally slow when the topic is uncompacted, rather than sporadically slow, to incentivize people to just enable compaction for the progress topic.

Also, IIRC, the bugs in seek we were seeing previously were only in conjunction with split partition queues. We're not using those here, and indeed the rdkafka.h docs on seek indicate that it is guaranteed to complete or produce an error as long as you provide a nonzero timeout.

I don't feel strongly! I'm convinced enough of the correctness here that I'm good with whatever you decide.

**Review by benesch — DISMISSED** [review]
Oh, wait, I approved, but I’d love to request that we also add the metrics for low and high water marks, and possibly also a metric for sink initialization time. If you’d prefer to do in a separate PR, that’s fine, but can you either file a follow up issue or put up a placeholder PR so we don’t forget? (And then feel free to dismiss this request changes.)

**Comment by petrosagg** [comment]
@benesch I added a single metric called `outstanding_progress_records` that tracks `high_watermark - position` over time during initialization. For any given sink we can determine how fast or slow it is initializing by looking at this metric so I don't need we need a second one.

File: src/storage/src/sink/kafka.rs [hunk 4]
```diff
@@ -805,8 +805,16 @@ async fn determine_sink_resume_upper(
     .await
     .add_context("error registering kafka progress topic for sink")?;
 
+    // We are about to spawn a blocking task that cannot be aborted by simply calling .abort() on
+    // its handle but we must be able to cancel it prompty so as to not leave long running
+    // operations around when interest to this task is lost. To accomplish this we create a shared
+    // token of which a weak reference is given to the task and a strong reference is held by the
+    // parent task. The task periodically checks if its weak reference is still valid before
+    // continuing its work.
+    let parent_token = Arc::new(());
```
Comment (guswynn) [inline src/storage/src/sink/kafka.rs:821]: note that if we ever need async checking for cancellation we may want to use https://docs.rs/tokio-util/latest/tokio_util/sync/struct.CancellationToken.html#

**Review by guswynn — APPROVED** [review]
a metric with the outstanding amount seems sufficient to me!

File: src/storage/src/sink/kafka.rs (hunk 4 above)
Comment (petrosagg) [reply src/storage/src/sink/kafka.rs:821]: very nice! Didn't know this existed
