### PR TITLE
sql: disallow null in range flag of create_range

### LINKED ISSUE #18036: [SQLsmith] thread 'timely:work-0' panicked at 'Datum::unwrap_string called on Null', src/expr/src/scalar/func.rs:5932:50
### What version of Materialize are you using?

v0.46.0-dev (ea8e22a62)

### How did you install Materialize?

Docker image

### What is the issue?

I couldn't find the responsible query for this since only clusterd panicked, but environmentd didn't report this failure:
```
thread 'timely:work-0' panicked at 'Datum::unwrap_string called on Null', src/expr/src/scalar/func.rs:5932:50
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/panicking.rs:64:14
   2: mz_repr::scalar::Datum::unwrap_str
             at ./src/repr/src/scalar.rs:631:18
   3: mz_expr::scalar::func::create_range
             at ./src/expr/src/scalar/func.rs:5932:40
   4: mz_expr::scalar::func::VariadicFunc::eval
             at ./src/expr/src/scalar/func.rs:6522:49
   5: mz_expr::scalar::MirScalarExpr::eval
             at ./src/expr/src/scalar/mod.rs:1753:60
   6: <T as mz_expr::scalar::func::LazyUnaryFunc>::eval
             at ./src/expr/src/scalar/func.rs:3748:41
   7: mz_expr::scalar::func::UnaryFunc::eval
             at ./src/expr/src/scalar/func/macros.rs:289:41
   8: mz_expr::scalar::MirScalarExpr::eval
             at ./src/expr/src/scalar/mod.rs:1749:56
   9: mz_compute_client::plan::join::JoinClosure::apply
             at ./src/compute-client/src/plan/join/mod.rs:136:23
  10: mz_compute::render::join::linear_join::differential_join_inner::{{closure}}
             at ./src/compute/src/render/join/linear_join.rs:290:22
  11: <differential_dataflow::operators::arrange::arrangement::Arranged<G,T1> as differential_dataflow::operators::join::JoinCore<G,<T1 as differential_dataflow::trace::TraceReader>::Key,<T1 as differential_dataflow::trace::TraceReader>::Val,<T1 as differential_dataflow::trace::TraceReader>::R>>::join_core::{{closure}}
             at /home/deen/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/cc88469/src/operators/join.rs:382:13
  12: <differential_dataflow::operators::arrange::arrangement::Arranged<G,T1> as differential_dataflow::operators::join::JoinCore<G,<T1 as differential_dataflow::trace::TraceReader>::Key,<T1 as differential_dataflow::trace::TraceReader>::Val,<T1 as differential_dataflow::trace::TraceReader>::R>>::join_core_internal_unsafe::{{closure}}::{{closure}}::{{closure}}
             at /home/deen/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/cc88469/src/operators/join.rs:578:43
  13: differential_dataflow::operators::join::Deferred<K,T,R,C1,C2,D>::work::{{closure}}
             at /home/deen/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/cc88469/src/operators/join.rs:724:42
  14: differential_dataflow::operators::join::JoinThinker<V1,V2,T,R1,R2>::think::{{closure}}::{{closure}}
             at /home/deen/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/cc88469/src/operators/join.rs:778:21
  15: differential_dataflow::operators::EditList<V,T,R>::map
             at /home/deen/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/cc88469/src/operators/mod.rs:77:17
  16: differential_dataflow::operators::join::JoinThinker<V1,V2,T,R1,R2>::think::{{closure}}
             at /home/deen/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/cc88469/src/operators/join.rs:777:17
  17: differential_dataflow::operators::EditList<V,T,R>::map
             at /home/deen/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/cc88469/src/operators/mod.rs:77:17
  18: differential_dataflow::operators::join::JoinThinker<V1,V2,T,R1,R2>::think
             at /home/deen/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/cc88469/src/operators/join.rs:776:13
  19: differential_dataflow::operators::join::Deferred<K,T,R,C1,C2,D>::work
             at /home/deen/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/cc88469/src/operators/join.rs:722:21
  20: <differential_dataflow::operators::arrange::arrangement::Arranged<G,T1> as differential_dataflow::operators::join::JoinCore<G,<T1 as differential_dataflow::trace::TraceReader>::Key,<T1 as differential_dataflow::trace::TraceReader>::Val,<T1 as differential_dataflow::trace::TraceReader>::R>>::join_core_internal_unsafe::{{closure}}::{{closure}}
             at /home/deen/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/cc88469/src/operators/join.rs:576:21
  21: <timely::dataflow::stream::StreamCore<G,D1> as timely::dataflow::operators::generic::operator::Operator<G,D1>>::binary_frontier::{{closure}}::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/generic/operator.rs:434:17
  22: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/generic/builder_rc.rs:133:31
  23: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/generic/builder_rc.rs:172:26
  24: <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/generic/builder_raw.rs:204:9
  25: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:699:30
  26: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:346:26
  27: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:312:17
  28: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:699:30
  29: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:346:26
  30: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:312:17
  31: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:699:30
  32: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:346:26
  33: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:312:17
  34: timely::worker::Wrapper::step::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/worker.rs:754:57
  35: core::option::Option<T>::map
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/option.rs:972:29
  36: timely::worker::Wrapper::step
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/worker.rs:754:26
  37: timely::worker::Worker<A>::step_or_park
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/worker.rs:396:38
  38: mz_compute::server::Worker<A>::run_client
             at ./src/compute/src/server.rs:347:13
  39: mz_compute::server::Worker<A>::setup_channel_and_run_client
             at ./src/compute/src/server.rs:321:9
  40: mz_compute::server::Worker<A>::run
             at ./src/compute/src/server.rs:181:21
  41: <mz_compute::server::Config as mz_cluster::types::AsRunnableWorker<mz_compute_client::protocol::command::ComputeCommand,mz_compute_client::protocol::response::ComputeResponse>>::build_and_run
             at ./src/compute/src/server.rs:162:9
  42: mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<C,R,<Worker as mz_cluster::types::AsRunnableWorker<C,R>>::Activatable>,C,R>,Worker,C,R>::build_timely::{{closure}}::{{closure}}
             at ./src/cluster/src/server.rs:178:13
  43: timely::execute::execute_from::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/execute.rs:388:22
  44: timely_communication::initialize::initialize_from::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/communication/src/initialize.rs:316:33
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
environmentd: 2023-03-09T19:18:41.396586Z ERROR mz_orchestrator_process: cluster-u1-replica-1-0 exited: ExitStatus(unix_wait_status(6)); relaunching in 5s
```
Since it happened inside of a join and was in create_range, my guess was something like this:
```
select tstzrange(nullif(now(), now()), null) from users join region on True;
```
It would be easier for me if we could print out the failed query when environmentd restarts clusterd.

ci-regexp: Datum::unwrap_string called on Null

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by sploiselle**
### Motivation

  * This PR fixes a recognized bug. fixes #18036

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by guswynn — APPROVED** [review]
nice!

**Review by def- — APPROVED** [review]
Thanks for the quick fix!

File: src/expr/src/scalar/func.rs [hunk 1]
```diff
@@ -5928,8 +5928,16 @@ fn create_range<'a>(
     datums: &[Datum<'a>],
     temp_storage: &'a RowArena,
 ) -> Result<Datum<'a>, EvalError> {
-    let (lower_inclusive, upper_inclusive) =
-        range::parse_range_bound_flags(datums[2].unwrap_str())?;
+    let flags = match datums[2] {
```
Comment (mjibson) [inline src/expr/src/scalar/func.rs:5931]: I thought NULLs were prevented from even getting here?

Comment (aalexandrov) [reply src/expr/src/scalar/func.rs:5931]: > I thought NULLs were prevented from even getting here?

Where would this be specified?

Comment (sploiselle) [reply src/expr/src/scalar/func.rs:5931]: @mjibson Yeah that was my mistake, as well––this is often the case, but this function was not set to propgate nulls (nor should it, apparently).

@aalexandrov This is defined as `propagates_nulls` on `UnaryFunc`, `BinaryFunc`, `VariadicFunc`.
