### PR TITLE
sql: prevent creating views with duplicate column names

### LINKED ISSUE #9158: Duplicate columns are allowed in materialized views?
### What version of Materialize are you using?

```
materialized v0.9.10 (8d7b550fb)
```

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [x] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [ ] Built from source
* [ ] Materialize Cloud

### What was the issue?

Materialize allows multiple columns with the same name. E.g.:

```
materialize=> create materialized view test as id, id, id from posts;
CREATE VIEW
materialize=> select * from test;
 id | id | id 
----+----+----
  1 |  1 |  1 
  2 |  2 |  2
  3 |  3 |  3
```

This prevents selecting the duplicate column:

```
materialize=> select id from test;
ERROR:  column name "id" is ambiguous
```

I'm relatively new to Postgres, but it looks like this isn't allowed in Postgres:

```
foo=# create materialized view test as id, id, id from posts;
ERROR:  column "id" specified more than once
```

### Is the issue reproducible? If so, please provide reproduction instructions.

The queries above consistently repro.

### Please attach any applicable log files.

Nothing relevant

### PR DESCRIPTION
**Pull request by sploiselle**
### Motivation

This PR fixes a recognized bug. Fixes #9158

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR adds a release note for any
  [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

File: src/sql/src/plan/statement/ddl.rs [hunk 1]
```diff
@@ -1217,6 +1214,11 @@ pub fn plan_view(
         finishing,
         depends_on,
     } = query::plan_root_query(scx, query.clone(), QueryLifetime::Static)?;
+
+    if let Some(dup) = desc.iter_names().filter_map(|c| c).duplicates().next() {
```
Comment (quodlibetor) [inline src/sql/src/plan/statement/ddl.rs:1218]: micronit: this [could be flatten](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=16ae10e1fa0117217a83a0cb39fcbe27):

```suggestion
    if let Some(dup) = desc.iter_names().flatten().duplicates().first() {
```

**Review by quodlibetor — APPROVED** [review]

**Review by mjibson — APPROVED** [review]

File: src/sql/src/plan/statement/ddl.rs (hunk 1 above)
Comment (sploiselle) [reply src/sql/src/plan/statement/ddl.rs:1218]: Ah, I knew I had derped this. ty!

Comment (quodlibetor) [reply src/sql/src/plan/statement/ddl.rs]: ah I didn't mean to include that `first`, it's not legal :-/

```rust
    if let Some(dup) = desc.iter_names().flatten().duplicates().next() {
```
