### PR TITLE
catalog: Optimize 0dt builtin item migrations

### LINKED ISSUE #28605: 0dt upgrade: thread 'main' panicked at src/environmentd/src/bin/environmentd/main.rs:569:9: environmentd: fatal: Catalog fenced during builtin table migrations
### What version of Materialize are you using?

37472f451d

### What is the issue?

Failed in [Checks 0dt upgrade across two versions](https://buildkite.com/materialize/nightly/builds/8846#0190f3f7-fb7d-406b-9b54-24d3bebfc3d5):
```
environmentd: 2024-07-27T11:48:59.801504Z  INFO mz_environmentd::deployment::preflight: all clusters hydrated
environmentd: 2024-07-27T11:48:59.801528Z  INFO mz_environmentd::deployment::preflight: announced as ready to promote; waiting for promotion
thread 'main' panicked at src/environmentd/src/bin/environmentd/main.rs:569:9:
environmentd: fatal: Catalog fenced during builtin table migrations
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: environmentd::main
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-021d940ac906aeda5-1/materialize/test/src/environmentd/src/bin/environmentd/main.rs:569:9
   3: <fn() as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Is this something we should ignore? The test still succeeded:
```
==> mzcompose: test case workflow-default succeeded
```
cc @aljoscha 
ci-regexp: Catalog fenced during builtin table migrations

### PR DESCRIPTION
**Pull request by jkosh44**
This commit optimizes 0dt builtin item migrations by only writing to the migration shard when there is a migration. Previously, the migrations would always write to the migration shard, and commit an empty write if there are no migrations. Additionally, removing the empty write reduces some contention on the migration shard, for example when a read-only instance is starting up at the same time as a writeable instance.

Resolves #28605

### Motivation
This PR fixes a CI flake.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - There are no user-facing behavior changes.

### CODE REVIEW

File: src/adapter/src/catalog/open/builtin_item_migration.rs [hunk 1]
```diff
@@ -365,14 +369,20 @@ async fn migrate_builtin_items_0dt(
...
-                    .await;
-            if let Err(e) = res {
-                error!("Unable to remove old entries from migration shard: {e:?}");
+            if !updates.is_empty() {
+                // Ignore any errors, these shards will get cleaned up in the next upgrade.
+                // It's important to use `next_upper` here. If there was another concurrent write at
+                // `next_upper`, then `updates` are no longer valid.
+                let res = write_to_migration_shard(
+                    updates,
+                    next_upper,
```
Comment (maddyblue) [inline src/adapter/src/catalog/open/builtin_item_migration.rs:378]: I'm not clear on the requirements for `next_upper`. Is this write correct for both branches where `next_upper` is set above? `next_upper` is a function of `migrated_shard_updates.is_empty()`, and this branch is a function of `migration_shards_to_finalize`.

**Review by maddyblue — APPROVED** [review]
