### PR TITLE
persist: forward timestamps to since when read through snapshot (bugfix)

### LINKED ISSUE #8303: Panic: Non-positive accumulation in reduce
### What version of Materialize are you using?

materialized v0.9.5-dev (1adbb1e7a) 

### How did you install Materialize?

Built from source

### What was the issue?

After stopping, Mz fails to restart:

```
2021-09-16T08:40:33.541589Z ERROR dataflow::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[]}, 11876133)        value: [Row{[TimestampTz(2021-09-16T08:39:34.287Z)]}, Row{[TimestampTz(2021-09-16T08:39:34.287Z)]}]     count: -1158
2021-09-16T08:40:33.541815Z ERROR dataflow::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[]}, 11876133)        value: [Row{[TimestampTz(2021-09-16T08:39:34.287Z)]}, Row{[TimestampTz(2021-09-16T08:39:34.287Z)]}]     count: -1158
2021-09-16T08:40:33.543114Z ERROR dataflow::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[]}, 341797)  value: [Row{[TimestampTz(2021-09-16T08:39:34.287Z)]}, Row{[TimestampTz(2021-09-16T08:39:34.287Z)]}]     count: -1158
2021-09-16T08:40:33.543299Z ERROR dataflow::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[]}, 14117)   value: [Row{[TimestampTz(2021-09-16T08:39:34.287Z)]}, Row{[TimestampTz(2021-09-16T08:39:34.287Z)]}]     count: -1158
2021-09-16T08:40:33.543444Z ERROR dataflow::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[]}, 1829)    value: [Row{[TimestampTz(2021-09-16T08:39:34.287Z)]}, Row{[TimestampTz(2021-09-16T08:39:34.287Z)]}]     count: -1158
2021-09-16T08:40:33.543586Z ERROR dataflow::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[]}, 37)      value: [Row{[TimestampTz(2021-09-16T08:39:34.287Z)]}, Row{[TimestampTz(2021-09-16T08:39:34.287Z)]}]     count: -1158
2021-09-16T08:40:33.543675Z ERROR dataflow::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[]}, 5)       value: [Row{[TimestampTz(2021-09-16T08:39:34.287Z)]}, Row{[TimestampTz(2021-09-16T08:39:34.287Z)]}]     count: -1158
2021-09-16T08:40:33.543798Z ERROR dataflow::render::reduce: [customer-data] Negative accumulation in ReduceMinsMaxes: [Row{[TimestampTz(2021-09-16T08:39:34.287Z)]}, Row{[TimestampTz(2021-09-16T08:39:34.287Z)]}] with count -1158
2021-09-16T08:40:34.219413Z ERROR panic: called `Option::unwrap()` on a `None` value
```

Stack trace:
```
thread: timely:work-1
location: src/dataflow/src/render/reduce.rs:820:65
version: 0.9.5-dev (1adbb1e7a42564ef7486c3e8f4656908df59c1a9)
backtrace:
   0: materialized::handle_panic
             at src/materialized/src/bin/materialized/main.rs:772:21
   1: core::ops::function::Fn::call
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:70:5
   2: std::panicking::rust_panic_with_hook
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:626:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:517:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
   5: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   6: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   7: core::panicking::panic
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:50:5
   8: dataflow::render::reduce::build_collation::{{closure}}
      differential_dataflow::operators::reduce::ReduceCore::reduce_abelian::{{closure}}
             at /home/moritz/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/7f1133a/src/operators/reduce.rs:282:21
      <differential_dataflow::operators::reduce::history_replay::HistoryReplayer<V1,V2,T,R1,R2> as differential_dataflow::operators::reduce::PerKeyCompute<V1,V2,T,R1,R2>>::compute
             at /home/moritz/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/7f1133a/src/operators/reduce.rs:937:29
   9: <differential_dataflow::operators::arrange::arrangement::Arranged<G,T1> as differential_dataflow::operators::reduce::ReduceCore<G,K,V,R>>::reduce_core::{{closure}}::{{closure}}
             at /home/moritz/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/7f1133a/src/operators/reduce.rs:529:49
  10: <timely::dataflow::stream::Stream<G,D1> as timely::dataflow::operators::generic::operator::Operator<G,D1>>::unary_frontier::{{closure}}::{{closure}}
             at /home/moritz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/4c2886b/timely/src/dataflow/operators/generic/operator.rs:352:17
      timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
             at /home/moritz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/4c2886b/timely/src/dataflow/operators/generic/builder_rc.rs:124:31
      timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
             at /home/moritz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/4c2886b/timely/src/dataflow/operators/generic/builder_rc.rs:163:26
      <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
             at /home/moritz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/4c2886b/timely/src/dataflow/operators/generic/builder_raw.rs:205:9
  11: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /home/moritz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/4c2886b/timely/src/progress/subgraph.rs:684:30
  12: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /home/moritz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/4c2886b/timely/src/progress/subgraph.rs:344:26
      <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /home/moritz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/4c2886b/timely/src/progress/subgraph.rs:310:17
  13: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /home/moritz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/4c2886b/timely/src/progress/subgraph.rs:684:30
  14: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /home/moritz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/4c2886b/timely/src/progress/subgraph.rs:344:26
      <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /home/moritz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/4c2886b/timely/src/progress/subgraph.rs:310:17
  15: timely::worker::Wrapper::step::{{closure}}
             at /home/moritz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/4c2886b/timely/src/worker.rs:749:57
      core::option::Option<T>::map
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/option.rs:489:29
      timely::worker::Wrapper::step
             at /home/moritz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/4c2886b/timely/src/worker.rs:749:26
  16: timely::worker::Worker<A>::step_or_park
             at /home/moritz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/4c2886b/timely/src/worker.rs:396:38
  17: dataflow::server::Worker<A>::run
             at src/dataflow/src/server.rs:587:13
      dataflow::server::serve::{{closure}}
             at src/dataflow/src/server.rs:290:13
      timely::execute::execute::{{closure}}
             at /home/moritz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/4c2886b/timely/src/execute.rs:285:22
  18: timely_communication::initialize::initialize_from::{{closure}}
             at /home/moritz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/4c2886b/communication/src/initialize.rs:291:33
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:125:18
  19: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/mod.rs:481:17
      <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:347:9
      std::panicking::try::do_call
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
      std::panicking::try
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
      std::panic::catch_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
      std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/mod.rs:480:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  20: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys/unix/thread.rs:71:17
  21: start_thread
             at ./nptl/./nptl/pthread_create.c:477:8
  22: __clone
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

### Is the issue reproducible? If so, please provide reproduction instructions.

I can't seem to reproduce the issue, but here's what I did:
1. Clear `mzdata`
2. `cargo run --release --bin materialized -- --workers 16 --introspection-frequency 1s --metrics-scraping-interval 1s --retain-prometheus-metrics 1s`
3. `cargo run --release --bin testdrive -- test/testdrive/prometheus.td`
4. Ctrl+C materialized
5. `cargo run --release --bin materialized -- --workers 4` -> Crashed

### Please attach any applicable log files.

[mzdata.tar.gz](https://github.com/MaterializeInc/materialize/files/7176311/mzdata.tar.gz)

### PR DESCRIPTION
**Pull request by danhhz**
The contract of since is that all lesser timestamps will be forwarded to it. We
do this physically during compaction, but don't have hard guarantees about how
long that takes, so we have to account for un-forwarded batches on reads.

Closes #8303

### Motivation

  * This PR fixes a recognized bug. #8303

### Checklist

- [x] This PR has adequate test coverage.
- [x] This PR adds a release note for any user-facing behavior changes.

### CODE REVIEW

File: src/persist/src/indexed/mod.rs [hunk 1]
```diff
@@ -1401,19 +1401,57 @@ mod tests {
...
         Ok(())
     }
+
+    #[test]
+    fn regression_8303_snapshot_forward_since() -> Result<(), Error> {
+        let mut i = MemRegistry::new().indexed_no_reentrance()?;
+        let id = block_on(|res| i.register("0", "", "", res))?;
+
+        // Introduce some data, seal it, forward since. Intentionally don't call
+        // step so that we don't have a chance to compact it (which did produce
```
Comment (ruchirK) [inline src/persist/src/indexed/mod.rs:1426]: I'm a little bit confused by the text in parentheses - is that saying "most of the time in the past we did get around to compacting everything and therefore didn't see the bug" or something else?

File: src/persist/src/indexed/runtime.rs [hunk 2]
```diff
@@ -583,10 +583,27 @@ impl<K: Codec, V: Codec> Snapshot<Result<K, String>, Result<V, String>> for Deco
         &mut self,
         buf: &mut E,
     ) -> Result<bool, Error> {
+        let since = self.since();
         let ret = self.snap.read(&mut self.buf)?;
-        buf.extend(self.buf.drain(..).map(|((k, v), ts, diff)| {
+        buf.extend(self.buf.drain(..).map(|((k, v), mut ts, diff)| {
             let k = K::decode(&k);
             let v = V::decode(&v);
+            // The contract of since is that all lesser timestamps will be
```
Comment (ruchirK) [inline src/persist/src/indexed/runtime.rs:591]: should we add asserts on this invariant elsewhere e.g. in the source operator?

**Review by ruchirK — APPROVED** [review]
LGTM! I feel a little bit uncomfortable with the phrasing of "the contract of since is that all lesser timestamps will be forwarded to it" because that's a little bit different from the contract of since in trace / differential where its more like "since represents the lower bound of times you can get correct answers for", but I do think that for snapshot implementations specifically the way you phrased it is more true. Maybe just changing the phrasing slightly to clarify that this is the contract of since only in this specific situation, and not generally would help?

Also not sure about "lesser" - elsewhere in the code we use the wordy "not at or in advance of" but I don't really care about that too much. Thanks a ton for jumping on this!

File: src/persist/src/indexed/runtime.rs [hunk 3]
```diff
@@ -583,10 +584,23 @@ impl<K: Codec, V: Codec> Snapshot<Result<K, String>, Result<V, String>> for Deco
...
+            // compaction, but don't have hard guarantees about how long that
+            // takes, so we have to account for un-advanced batches on reads.
+            //
+            // TODO: This adjustment should logically live in IndexedSnapshot
+            // (where it could be lazy about only doing this on the relevant
+            // batches) but in the short-term it's much easier to do here. I'm
+            // hoping to clean up how snapshots work soon and make them more
+            // like iterators, at which point it will be much simpler to push
+            // this logic where it belongs.
+            ts.advance_by(since.borrow());
```
Comment (danhhz) [inline src/persist/src/indexed/runtime.rs:603]: fyi @ruchirK there's a method for this that does the right thing if the timestamp is actually partially ordered

Comment (ruchirK) [reply src/persist/src/indexed/runtime.rs:603]: oh good to know thanks
