### PR TITLE
sql: Include system indexes in read transactions

### LINKED ISSUE #9374: Timedomain error triggered by LIST type on Metabase
### What version of Materialize are you using?

From the shell:

```
materialize=> select mz_version();
       mz_version
-------------------------
 v0.10.1-dev (d68ab011e)
(1 row)
```
(#9366 as of some moment yesterday)

### How did you install Materialize?

* [x] Built from source

### What was the issue?

When trying to visualize a table or view which contains a column with the LIST type, the following error is returned:
```
Detail: The following relations in the query are outside the transaction's time domain: "pg_catalog.pg_namespace" "pg_catalog.pg_type" Only the following relations are available: "mz_catalog. [snipped]
```

### Is the issue reproducible? If so, please provide reproduction instructions.

Try to open `mz_catalog. mz_dataflow_operator_addresses` on Metabase.

### Please attach any applicable log files.

[Gist with pgwire=trace logs](https://gist.github.com/andrioni/eca100713ffa5ecd93e365519f89487b)

Select fragment of the queries being executed from the gist above:
```sql
BEGIN READ ONLY;

-- Metabase:: userID: 1 queryType: MBQL queryHash: 8095bed5fef1db0ed1f2a22cc64a98d10eb12e64155b6e70012947474d15a5fd
SELECT "mz_catalog"."mz_dataflow_operator_addresses"."id" AS "id", "mz_catalog"."mz_dataflow_operator_addresses"."worker" AS "worker", "mz_catalog"."mz_dataflow_operator_addresses"."address" AS "address" FROM "mz_catalog"."mz_dataflow_operator_addresses" LIMIT 2000;

SELECT n.nspname = ANY(current_schemas(true)), n.nspname, t.typname FROM pg_catalog.pg_type t JOIN pg_catalog.pg_namespace n ON t.typnamespace = n.oid WHERE t.oid = $1;
-- raw_params: [Some([0, 0, 64, 0])]

error code=25000 message=Transactions can only reference objects in the same timedomain. See https://materialize.com/docs/sql/begin/#same-timedomain-error
```

### LINKED ISSUE #9375: Timedomain error triggered by RECORD type on ad hoc query on Metabase
### What version of Materialize are you using?

From the shell:

```
materialize=> select mz_version();
       mz_version
-------------------------
 v0.10.1-dev (d68ab011e)
(1 row)
```
(#9366 as of some moment yesterday)

### How did you install Materialize?

* [x] Built from source

### What was the issue?

When trying to visualize the results of a query with a RECORD type, the following error is returned:
```
ERROR: Transactions can only reference objects in the same timedomain. See https://materialize.com/docs/sql/begin/#same-timedomain-error Detail: The following relations in the query are outside the transaction's time domain: "mz_catalog.mz_array_types_primary_idx" "mz_catalog.mz_base_types_primary_idx" "mz_catalog.mz_list_types_primary_idx" "mz_catalog.mz_map_types_primary_idx" "mz_catalog.mz_pseudo_types_primary_idx" "mz_catalog.mz_schemas_primary_idx" "mz_catalog.mz_types_primary_idx" "pg_catalog.pg_namespace" "pg_catalog.pg_type" No relations are available.
```

### Is the issue reproducible? If so, please provide reproduction instructions.

Open the SQL query editor on Metabase and try to run the following query:
```sql
select row(1,2);
```

### Please attach any applicable log files.

[Gist with pgwire=trace logs](https://gist.github.com/andrioni/a09b54d624a87bea4806acb3cc23d069)

Select fragment of the queries being executed from the gist above:
```sql
BEGIN READ ONLY;

-- Metabase:: userID: 1 queryType: native queryHash: 2806754769dff89c5948e655117ca719dbfc3bb650b48341e49a9a299f675086
select row(1,2);

SELECT n.nspname = ANY(current_schemas(true)), n.nspname, t.typname FROM pg_catalog.pg_type t JOIN pg_catalog.pg_namespace n ON t.typnamespace = n.oid WHERE t.oid = $1
-- raw_params: [Some([0, 0, 8, 201])]

error code=25000 message=Transactions can only reference objects in the same timedomain. See https://materialize.com/docs/sql/begin/#same-timedomain-error
```

### LINKED ISSUE #21815: sql: acquire read holds for catalogs during txns
The commit https://github.com/MaterializeInc/materialize/pull/9366/commits/cf1271c1c0bddeee4890744faa1e0646257b8030 purported to include system indexes in read txns, but I incorrectly committed some tiny rename refactor instead. We should do what that commit said because it regularly breaks drivers.

### PR DESCRIPTION
**Pull request by jkosh44**
cf1271c1c0bddeee4890744faa1e0646257b8030 claimed to have already completed this, however, due to an unfortunate git typo the original contents of that commit were replaced with a small refactor. This commit applies the original contents of
cf1271c1c0bddeee4890744faa1e0646257b8030. The original commit message is copied below.

System views from pg_catalog and mz_catalog are sometimes used by applications (for example Metabase if it doesn't recognize a data type) after the first query of a transaction. This previously would cause a timedomain error. One solution to this is to always include system indexes in read transactions. The cost is mostly that system indexes can now be held back from compaction more than previously. This seems ok because they don't change quickly, so should hopefully not cause memory issues.

Fixes #9375
Fixes #9374
Fixes #21815

### Motivation
This PR adds a known-desirable feature.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - Allow pg_catalog objects in all read transactions.

### CODE REVIEW

File: src/adapter/src/coord/timeline.rs [hunk 1]
```diff
@@ -840,6 +840,12 @@ impl Coordinator {
         let mut id_bundle: CollectionIdBundle = self
             .index_oracle(compute_instance)
             .sufficient_collections(item_ids.iter());
+        // Queries may get auto-routed to the mz_introspection cluster, so we include indexes on
+        // that cluster.
+        let system_id_bundle = self
+            .index_oracle(*self.catalog().get_mz_introspections_cluster_id())
+            .sufficient_collections(item_ids.iter());
```
Comment (jkosh44) [inline src/adapter/src/coord/timeline.rs:847]: Even if `item_ids` only contain items from the Postgres catalog schemas, `sufficient_collections` will still return indexes in the `mz_catalog` schema. So I just decided to always include all catalog schemas.

File: src/adapter/src/coord/timeline.rs [hunk 2]
```diff
@@ -840,6 +840,12 @@ impl Coordinator {
         let mut id_bundle: CollectionIdBundle = self
             .index_oracle(compute_instance)
             .sufficient_collections(item_ids.iter());
+        // Queries may get auto-routed to the mz_introspection cluster, so we include indexes on
```
Comment (mjibson) [inline src/adapter/src/coord/timeline.rs:843]: What happens if they aren't auto routed. Does this over guess and do something wrong?

File: src/adapter/src/coord/timeline.rs [hunk 3]
```diff
@@ -805,27 +805,27 @@ impl Coordinator {
...
+                &SchemaSpecifier::Id(self.catalog().get_pg_catalog_schema_id().clone()),
             ),
             (
                 &ResolvedDatabaseSpecifier::Ambient,
-                &SchemaSpecifier::Id(self.catalog().get_mz_internal_schema_id().clone()),
+                &SchemaSpecifier::Id(self.catalog().get_information_schema_id().clone()),
             ),
         ];
-        if system_schemas.iter().any(|s| schemas.contains(s)) {
+        if !schemas.is_empty() {
```
[the remark this answers is not in the document]
Comment (jkosh44) [reply src/adapter/src/coord/timeline.rs:828]: `schemas` is a list of references, so the actual owned values must exist somewhere outside of `schemas` AND live as long as `schemas` (i.e. longer that this if block). I'll try converting it to `CoW`s to try and optimize this.

File: src/adapter/src/coord/timeline.rs (hunk 2 above)
Comment (jkosh44) [reply src/adapter/src/coord/timeline.rs:843]: There's some weird interactions with timedomains and clusters, I just started a discussion here: https://materializeinc.slack.com/archives/C02FWJ94HME/p1695214693135449

This change makes it so that indexes in BOTH the active cluster and the `mz_introspection` cluster are included in the timedomain. Previously, only indexes in the active cluster were included in the timedomain. Without this change, the issue is that if you're query is auto-routed to `mz_introspection` and hits an index, then it will be aborted because that index is outside of the timedomain.

> What happens if they aren't auto routed. Does this over guess and do something wrong?

If they aren't auto-routed, then we have the same behavior as before this change. The query will use the current cluster, which also has it's indexes in the timedomain (if we haven't switched clusters). The read holds on the indexes in `mz_introspection` end up being wasteful because we don't use them, but we don't do anything wrong.

File: src/adapter/src/coord/timeline.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (jkosh44) [reply src/adapter/src/coord/timeline.rs:814]: The CoW change worked and I just pushed it.

File: test/sqllogictest/github-8241.slt [hunk 4]
```diff
@@ -39,3 +39,138 @@ DETAIL: The following relations in the query are outside the transaction's time
 "materialize.public.i2"
 Only the following relations are available:
 "materialize.public.i1"
+"materialize.public.t1"
```
[the remark this answers is not in the document]
Comment (jkosh44) [reply test/sqllogictest/github-8241.slt:42]: I didn't take a close look at this change, but I'm actually a bit baffled by this. Why wasn't `materialize.public.t1` included in the timedomain previously? It's in the same schema as `materialize.public.i1`. Also, why did my changes cause it to be included? My changes only added system schemas, it didn't touch user schemas. I'll have to look into this.

Anyway, to answer your questions directly:

> Do we have data on how expensive it is to add all these read holds?

I don't have any data on this, but it's expensiveness would depend on how long the transaction is held open.

>  Is it mostly just adding to a btreemap so it's very cheap?

My feeling is that it's rather expensive on the system indexes since compaction is stopped and they will just accumulate in-memory in the clusters.

> Also having system and user id'd indexes seems not great, as that will balloon as users add many objects across many clusters.

We only include indexes in the active cluster and the `mz_introspection` cluster. So adding indexes across many clusters won't cause the read holds of a single transaction to balloon to include all of those indexes. 

I think we have to at least sometimes mix user and system indexes. A query like `SELECT * FROM t, mz_views` already includes system indexes (the introspection sources of the current cluster) and user indexes (any indexes in the active cluster). This change just makes that the default behavior.

> One of the arguments for only including pg_catalog is that it would limit this list of included indexes to a known set that doesn't change based on user created objects.

I'm not sure I'm following this. Are you suggesting to exclude user indexes from the timedomain? That would prevent users from using user indexes in a transaction which doesn't seem ideal. Or are you suggesting to exclude the introspection sources? Either way, I think you're right about only including `pg_catalog` by default. We can re-visit later if the other schemas are needed.

[the remark this answers is not in the document]
Comment (jkosh44) [reply test/sqllogictest/github-8241.slt:42]: > Why wasn't materialize.public.t1 included in the timedomain previously? It's in the same schema as materialize.public.i1. Also, why did my changes cause it to be included?

Ok I figured this out. A relation will be excluded from the timedomain, if there is an index on that relation in the timedomain.

**Comment by jkosh44** [comment]
@mjibson This is ready for another review. I restricted the catalog schemas to only include `pg_catalog` by default, which contains no indexes. Additionally I removed the code that always adds indexes from `mz_introspection`.

File: src/adapter/src/coord/timeline.rs [hunk 5]
```diff
@@ -805,28 +805,34 @@ impl Coordinator {
...
-                &ResolvedDatabaseSpecifier::Ambient,
-                &SchemaSpecifier::Id(self.catalog().get_mz_internal_schema_id().clone()),
-            ),
         ];
+
         if system_schemas.iter().any(|s| schemas.contains(s)) {
+            // If any of the system schemas is specified, add the rest of the
+            // system schemas.
             schemas.extend(system_schemas);
+        } else if !schemas.is_empty() {
```
Comment (mjibson) [inline src/adapter/src/coord/timeline.rs:832]: I like having both of these if blocks. Feels like the right tradeoff.

**Review by mjibson — APPROVED** [review]

File: src/adapter/src/coord/timeline.rs (hunk 5 above)
Comment (jkosh44) [reply src/adapter/src/coord/timeline.rs:832]: Agreed.

File: src/adapter/src/coord/introspection.rs [hunk 6]
```diff
@@ -144,6 +144,11 @@ pub fn auto_run_on_introspection<'a, 's, 'p>(
         return TargetCluster::Active;
     }
 
+    // Auto-routing mid transaction can cause an abort due to an invalid timedomain.
```
Comment (mjibson) [inline src/adapter/src/coord/introspection.rs:147]: Does one of the added tests cover this?

Comment (jkosh44) [reply src/adapter/src/coord/introspection.rs:147]: Just added one. I meant to comment that some tests were failing without this because a bunch of pg_catalog queries get auto-routed and then fail mid-transaction.

**Comment by jkosh44** [comment]
The current test error is also due to auto-routing. Here's a rough sketch of what's going on:

1. `BEGIN`
2. Query system tables.
3. Query is auto-routed to mz_introspection.
4. Time domain contains indexes from mz_introspection but not the underlying tables because of the indexes.
5. Query system tables with a function.
6. Query is not auto-routed to mz_introspection because it contains a function.
7. Current cluster has no indexes so we go to the underlying tables.
8. Tables are not in the timedomain so we fail.

To fix this, we need to set the cluster at the start of the transaction and not allow anyone to change it.

**Comment by mjibson** [comment]
> To fix this, we need to set the cluster at the start of the transaction and not allow anyone to change it.

Encouragement to do all that in another PR.

**Comment by jkosh44** [comment]
I pulled in https://github.com/MaterializeInc/materialize/pull/21854 which is a blocker for this PR. I'll wait for that to merge before merging this PR.

File: test/sqllogictest/transactions.slt [hunk 7]
```diff
@@ -799,3 +825,108 @@ simple
...
+
+## Auto-routing doesn't select mz_introspection in the middle of a transaction.
+
+# Since mz_views uses custom types, the postgres client will look it up in the catalog on
+# first use. If the first use happens to be in a transaction, then we can get unexpected time
+# domain errors. This is an annoying hack to load the information in the postgres client before
+# we start any transactions.
+statement ok
+SELECT * FROM mz_views LIMIT 0
+----
```
Comment (jkosh44) [inline test/sqllogictest/transactions.slt:910]: This is still required with this change due to https://github.com/MaterializeInc/materialize/issues/21815#issuecomment-1729712813, which is very unfortunate (CC @mjibson).
