### PR TITLE
expr,sql: correct many bugs in float casts and rounding

### LINKED ISSUE #5688: Attempting arithmetic with the result of EXTRACT results in NULL on overflow
### What version of Materialize are you using?

```
$ materialized -v
materialized v0.7.1-dev (9c81b7e07) listening on 0.0.0.0:6875...
```

### What was the issue?

Attempting to insert ```EXTRACT('epoch' FROM CAST('2000-01-01' AS TIMESTAMP))*1000``` into an ```INTEGER``` field results in a ```NULL``` value being inserted. Due to #5275 one can expect that an unchecked overflow would occur, but inserting a ```NULL``` is suspicious on its own merits so I am opening a separate ticket.

### Is the issue reproducible? If so, please provide reproduction instructions.

```
materialize=> DROP TABLE one_ts;
DROP TABLE
materialize=> CREATE TABLE one_ts (ts INTEGER);
CREATE TABLE
materialize=> INSERT INTO one_ts VALUES (EXTRACT('epoch' FROM CAST('2000-01-01' AS TIMESTAMP))*1000);
INSERT 0 1
materialize=> SELECT ts is null FROM one_ts;
 ?column? 
----------
 t
(1 row)
```

### PR DESCRIPTION
**Pull request by benesch**
Import most of the PostgreSQL tests for the float4 and float8 types and
shake out most of the resulting bugs:

  * Floats round ties to the nearest even number, in conformance
    with IEEE 754 and PostgreSQL.

  * Overflow and underflow when casting to and from floats is reported
    as in PostgreSQL.

The upshot is that arithmetic on the result of `extract` properly
handles overflow, so fixes #5688.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5727)

### CODE REVIEW

File: src/repr/src/strconv.rs [hunk 1]
```diff
@@ -125,48 +131,108 @@ where
...
+        _ => Ok(f),
+    }
+}
+
+fn format_float<F, Fl>(buf: &mut F, f: Fl) -> Nestable
+where
+    F: FormatBuffer,
+    Fl: NumFloat + RyuFloat,
+{
+    // Use ryu rather than the standard library. ryu uses scientific notation
```
Comment (sploiselle) [inline src/repr/src/strconv.rs:176]: just wanted to say that these comments are gold

**Review by sploiselle — COMMENTED** [review]
very cool to see the subtlety of these bugs. I gave the Rust a once-over but it's late and I am out next week, so consider this only +1

**Review by philip-stoev — APPROVED** [review]
Thank you for bringing all those tests in! I checked a couple of random things -- trailing and leading spaces, the original EXTRACT test case, and they all seem to work as expected. So I am good.

File: doc/user/data/sql_funcs.yml [hunk 2]
```diff
@@ -111,11 +111,14 @@
     description: "`x % y`"
 
   - signature: 'round(x: N) -> N'
-    description: "`x` rounded to the nearest whole number; halves are rounded up"
+    description: >-
+      `x` rounded to the nearest whole number.
+      If `N` is `real` or `double precision`, rounds ties to the nearest even number.
+      If `N` is `numeric`, rounds ties away from zero.
```
Comment (mjibson) [inline doc/user/data/sql_funcs.yml:117]: These release note changes for numerics are not correct (the following run from this branch):

```
materialize=> select round(0.5::float8), round(0.5::numeric);
 round | round 
-------+-------
     0 |     0
```

Postgres:

```
mjibson=# select round(0.5::float8), round(0.5::numeric);
 round | round 
-------+-------
     0 |     1
```

**Review by mjibson — APPROVED** [review]
Float changes LGTM, but decimals are still wrong. They were already wrong though, so this shouldn't block anything. I'm fine with the round docs being slightly incorrect until we fix decimals for real.

File: doc/user/data/sql_funcs.yml (hunk 2 above)
Comment (benesch) [reply doc/user/data/sql_funcs.yml:117]: Oh, hah, great catch. I guess the documented behavior of decimals was wrong. Will address.

Comment (benesch) [reply doc/user/data/sql_funcs.yml:117]: Wait, no, this is just a nice footgun in Materialize. The default decimal scale is 0 so the decimal component of your input there just got dropped on the floor. Here's how it looks if one keeps their foot intact:

```
materialize=> create table t (f float8, n numeric(10, 5));
CREATE TABLE
materialize=> insert into t values (0.5, 0.5), (1.5, 1.5), (-0.5, -0.5), (-1.5, -1.5);
INSERT 0 4
materialize=> select f, round(f), round(n) from t;
  f   | round |  round   
------+-------+----------
  0.5 |     0 |  1.00000
 -0.5 |    -0 | -1.00000
  1.5 |     2 |  2.00000
 -1.5 |    -2 | -2.00000
(4 rows)

```

Maybe another bug in the way we handle rounding when converting to a numeric in the first place, but I think the release notes are actually ok as is.
