### PR TITLE
explain: further align explain path with oneshot execution path

### LINKED ISSUE #19214: thread 'coordinator' panicked at 'Expression in join plan is not bound at time of use', src/compute-client/src/plan/join/linear_join.rs:257:34
### What version of Materialize are you using?

1319936

### What is the issue?

```
--- [SQLsmith] Broken 08000: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
 (16 occurences)
From 23:36:06 until 00:10:52
[redacted unrelated query]
```
environmentd logs:
```
sqlsmith-mz_2-1  | thread 'coordinator' panicked at 'Expression in join plan is not bound at time of use', src/compute-client/src/plan/join/linear_join.rs:257:34
sqlsmith-mz_2-1  | stack backtrace:
sqlsmith-mz_2-1  |    0: rust_begin_unwind
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
sqlsmith-mz_2-1  |    1: core::panicking::panic_fmt
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
sqlsmith-mz_2-1  |    2: core::panicking::panic_display
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:147:5
sqlsmith-mz_2-1  |    3: core::panicking::panic_str
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:131:5
sqlsmith-mz_2-1  |    4: core::option::expect_failed
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/option.rs:1924:5
sqlsmith-mz_2-1  |    5: <core::option::Option<mz_expr::scalar::MirScalarExpr>>::expect
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/option.rs:786:21
sqlsmith-mz_2-1  |    6: <mz_compute_client::plan::join::linear_join::LinearJoinPlan>::create_from::{closure#3}::{closure#0}
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/compute-client/src/plan/join/linear_join.rs:257:34
sqlsmith-mz_2-1  |    7: core::iter::adapters::map::map_fold::<&mz_expr::scalar::MirScalarExpr, mz_expr::scalar::MirScalarExpr, (), <mz_compute_client::plan::join::linear_join::LinearJoinPlan>::create_from::{closure#3}::{closure#0}, core::iter::traits::iterator::Iterator::for_each::call<mz_expr::scalar::MirScalarExpr, <alloc::vec::Vec<mz_expr::scalar::MirScalarExpr>>::extend_trusted<core::iter::adapters::map::Map<core::slice::iter::Iter<mz_expr::scalar::MirScalarExpr>, <mz_compute_client::plan::join::linear_join::LinearJoinPlan>::create_from::{closure#3}::{closure#0}>>::{closure#0}>::{closure#0}>::{closure#0}
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/iter/adapters/map.rs:84:28
sqlsmith-mz_2-1  |    8: <core::slice::iter::Iter<mz_expr::scalar::MirScalarExpr> as core::iter::traits::iterator::Iterator>::fold::<(), core::iter::adapters::map::map_fold<&mz_expr::scalar::MirScalarExpr, mz_expr::scalar::MirScalarExpr, (), <mz_compute_client::plan::join::linear_join::LinearJoinPlan>::create_from::{closure#3}::{closure#0}, core::iter::traits::iterator::Iterator::for_each::call<mz_expr::scalar::MirScalarExpr, <alloc::vec::Vec<mz_expr::scalar::MirScalarExpr>>::extend_trusted<core::iter::adapters::map::Map<core::slice::iter::Iter<mz_expr::scalar::MirScalarExpr>, <mz_compute_client::plan::join::linear_join::LinearJoinPlan>::create_from::{closure#3}::{closure#0}>>::{closure#0}>::{closure#0}>::{closure#0}>
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/iter/traits/iterator.rs:2438:21
sqlsmith-mz_2-1  |    9: <core::iter::adapters::map::Map<core::slice::iter::Iter<mz_expr::scalar::MirScalarExpr>, <mz_compute_client::plan::join::linear_join::LinearJoinPlan>::create_from::{closure#3}::{closure#0}> as core::iter::traits::iterator::Iterator>::fold::<(), core::iter::traits::iterator::Iterator::for_each::call<mz_expr::scalar::MirScalarExpr, <alloc::vec::Vec<mz_expr::scalar::MirScalarExpr>>::extend_trusted<core::iter::adapters::map::Map<core::slice::iter::Iter<mz_expr::scalar::MirScalarExpr>, <mz_compute_client::plan::join::linear_join::LinearJoinPlan>::create_from::{closure#3}::{closure#0}>>::{closure#0}>::{closure#0}>
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/iter/adapters/map.rs:124:9
sqlsmith-mz_2-1  |   10: <core::iter::adapters::map::Map<core::slice::iter::Iter<mz_expr::scalar::MirScalarExpr>, <mz_compute_client::plan::join::linear_join::LinearJoinPlan>::create_from::{closure#3}::{closure#0}> as core::iter::traits::iterator::Iterator>::for_each::<<alloc::vec::Vec<mz_expr::scalar::MirScalarExpr>>::extend_trusted<core::iter::adapters::map::Map<core::slice::iter::Iter<mz_expr::scalar::MirScalarExpr>, <mz_compute_client::plan::join::linear_join::LinearJoinPlan>::create_from::{closure#3}::{closure#0}>>::{closure#0}>
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/iter/traits/iterator.rs:837:9
sqlsmith-mz_2-1  |   11: <alloc::vec::Vec<mz_expr::scalar::MirScalarExpr>>::extend_trusted::<core::iter::adapters::map::Map<core::slice::iter::Iter<mz_expr::scalar::MirScalarExpr>, <mz_compute_client::plan::join::linear_join::LinearJoinPlan>::create_from::{closure#3}::{closure#0}>>
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/vec/mod.rs:2885:17
sqlsmith-mz_2-1  |   12: <alloc::vec::Vec<mz_expr::scalar::MirScalarExpr> as alloc::vec::spec_extend::SpecExtend<mz_expr::scalar::MirScalarExpr, core::iter::adapters::map::Map<core::slice::iter::Iter<mz_expr::scalar::MirScalarExpr>, <mz_compute_client::plan::join::linear_join::LinearJoinPlan>::create_from::{closure#3}::{closure#0}>>>::spec_extend
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/vec/spec_extend.rs:26:9
sqlsmith-mz_2-1  |   13: <alloc::vec::Vec<mz_expr::scalar::MirScalarExpr> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<mz_expr::scalar::MirScalarExpr, core::iter::adapters::map::Map<core::slice::iter::Iter<mz_expr::scalar::MirScalarExpr>, <mz_compute_client::plan::join::linear_join::LinearJoinPlan>::create_from::{closure#3}::{closure#0}>>>::from_iter
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
sqlsmith-mz_2-1  |   14: <alloc::vec::Vec<mz_expr::scalar::MirScalarExpr> as alloc::vec::spec_from_iter::SpecFromIter<mz_expr::scalar::MirScalarExpr, core::iter::adapters::map::Map<core::slice::iter::Iter<mz_expr::scalar::MirScalarExpr>, <mz_compute_client::plan::join::linear_join::LinearJoinPlan>::create_from::{closure#3}::{closure#0}>>>::from_iter
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/vec/spec_from_iter.rs:33:9
sqlsmith-mz_2-1  |   15: <alloc::vec::Vec<mz_expr::scalar::MirScalarExpr> as core::iter::traits::collect::FromIterator<mz_expr::scalar::MirScalarExpr>>::from_iter::<core::iter::adapters::map::Map<core::slice::iter::Iter<mz_expr::scalar::MirScalarExpr>, <mz_compute_client::plan::join::linear_join::LinearJoinPlan>::create_from::{closure#3}::{closure#0}>>
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/vec/mod.rs:2753:9
sqlsmith-mz_2-1  |   16: <core::iter::adapters::map::Map<core::slice::iter::Iter<mz_expr::scalar::MirScalarExpr>, <mz_compute_client::plan::join::linear_join::LinearJoinPlan>::create_from::{closure#3}::{closure#0}> as core::iter::traits::iterator::Iterator>::collect::<alloc::vec::Vec<mz_expr::scalar::MirScalarExpr>>
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/iter/traits/iterator.rs:1860:9
sqlsmith-mz_2-1  |   17: <mz_compute_client::plan::join::linear_join::LinearJoinPlan>::create_from::{closure#3}
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/compute-client/src/plan/join/linear_join.rs:262:26
sqlsmith-mz_2-1  |   18: <core::option::Option<(alloc::vec::Vec<mz_expr::scalar::MirScalarExpr>, alloc::collections::btree::map::BTreeMap<usize, usize>, alloc::vec::Vec<usize>)>>::unwrap_or_else::<<mz_compute_client::plan::join::linear_join::LinearJoinPlan>::create_from::{closure#3}>
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/option.rs:873:21
sqlsmith-mz_2-1  |   19: <mz_compute_client::plan::join::linear_join::LinearJoinPlan>::create_from
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/compute-client/src/plan/join/linear_join.rs:242:17
sqlsmith-mz_2-1  |   20: <mz_compute_client::plan::Plan>::from_mir_stack_safe
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/compute-client/src/plan/mod.rs:1258:46
sqlsmith-mz_2-1  |   21: <mz_compute_client::plan::Plan>::from_mir_inner::{closure#0}
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/compute-client/src/plan/mod.rs:974:38
sqlsmith-mz_2-1  |   22: stacker::maybe_grow::<core::result::Result<(mz_compute_client::plan::Plan, mz_compute_client::plan::AvailableCollections), alloc::string::String>, <mz_compute_client::plan::Plan>::from_mir_inner::{closure#0}>
sqlsmith-mz_2-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
sqlsmith-mz_2-1  |   23: mz_ore::stack::maybe_grow::<<mz_compute_client::plan::Plan>::from_mir_inner::{closure#0}, core::result::Result<(mz_compute_client::plan::Plan, mz_compute_client::plan::AvailableCollections), alloc::string::String>>
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/ore/src/stack.rs:100:5
sqlsmith-mz_2-1  |   24: <mz_compute_client::plan::Plan>::from_mir_inner
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/compute-client/src/plan/mod.rs:974:9
sqlsmith-mz_2-1  |   25: <mz_compute_client::plan::Plan>::from_mir_stack_safe
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/compute-client/src/plan/mod.rs:1086:38
sqlsmith-mz_2-1  |   26: <mz_compute_client::plan::Plan>::from_mir_inner::{closure#0}
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/compute-client/src/plan/mod.rs:974:38
sqlsmith-mz_2-1  |   27: stacker::maybe_grow::<core::result::Result<(mz_compute_client::plan::Plan, mz_compute_client::plan::AvailableCollections), alloc::string::String>, <mz_compute_client::plan::Plan>::from_mir_inner::{closure#0}>
sqlsmith-mz_2-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
sqlsmith-mz_2-1  |   28: mz_ore::stack::maybe_grow::<<mz_compute_client::plan::Plan>::from_mir_inner::{closure#0}, core::result::Result<(mz_compute_client::plan::Plan, mz_compute_client::plan::AvailableCollections), alloc::string::String>>
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/ore/src/stack.rs:100:5
sqlsmith-mz_2-1  |   29: <mz_compute_client::plan::Plan>::from_mir_inner
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/compute-client/src/plan/mod.rs:974:9
sqlsmith-mz_2-1  |   30: <mz_compute_client::plan::Plan>::from_mir_stack_safe
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/compute-client/src/plan/mod.rs:1086:38
sqlsmith-mz_2-1  |   31: <mz_compute_client::plan::Plan>::from_mir_inner::{closure#0}
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/compute-client/src/plan/mod.rs:974:38
sqlsmith-mz_2-1  |   32: stacker::maybe_grow::<core::result::Result<(mz_compute_client::plan::Plan, mz_compute_client::plan::AvailableCollections), alloc::string::String>, <mz_compute_client::plan::Plan>::from_mir_inner::{closure#0}>
sqlsmith-mz_2-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
sqlsmith-mz_2-1  |   33: mz_ore::stack::maybe_grow::<<mz_compute_client::plan::Plan>::from_mir_inner::{closure#0}, core::result::Result<(mz_compute_client::plan::Plan, mz_compute_client::plan::AvailableCollections), alloc::string::String>>
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/ore/src/stack.rs:100:5
sqlsmith-mz_2-1  |   34: <mz_compute_client::plan::Plan>::from_mir_inner
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/compute-client/src/plan/mod.rs:974:9
sqlsmith-mz_2-1  |   35: <mz_compute_client::plan::Plan>::from_mir
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/compute-client/src/plan/mod.rs:957:9
sqlsmith-mz_2-1  |   36: <mz_compute_client::plan::Plan>::lower_dataflow
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/compute-client/src/plan/mod.rs:1678:32
sqlsmith-mz_2-1  |   37: <mz_compute_client::plan::Plan>::finalize_dataflow
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/compute-client/src/plan/mod.rs:1623:28
sqlsmith-mz_2-1  |   38: <mz_adapter::coord::Coordinator>::sequence_explain_plan::{closure#0}::{closure#6}
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:2751:17
sqlsmith-mz_2-1  |   39: <mz_adapter::coord::Coordinator>::sequence_explain_plan::catch_unwind::<mz_compute_client::types::dataflows::DataflowDescription<mz_compute_client::plan::Plan>, mz_adapter::error::AdapterError, <mz_adapter::coord::Coordinator>::sequence_explain_plan::{closure#0}::{closure#6}>
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:2644:17
sqlsmith-mz_2-1  |   40: <mz_adapter::coord::Coordinator>::sequence_explain_plan::{closure#0}
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:2750:33
sqlsmith-mz_2-1  |   41: tracing_core::dispatcher::with_default::<core::result::Result<(alloc::vec::Vec<mz_repr::global_id::GlobalId>, core::option::Option<mz_adapter::coord::peek::FastPathPlan>), mz_adapter::error::AdapterError>, <mz_adapter::coord::Coordinator>::sequence_explain_plan::{closure#0}>
sqlsmith-mz_2-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.30/src/dispatcher.rs:257:5
sqlsmith-mz_2-1  |   42: <mz_adapter::explain::optimizer_trace::OptimizerTrace>::collect_trace::<core::result::Result<(alloc::vec::Vec<mz_repr::global_id::GlobalId>, core::option::Option<mz_adapter::coord::peek::FastPathPlan>), mz_adapter::error::AdapterError>, <mz_adapter::coord::Coordinator>::sequence_explain_plan::{closure#0}>
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/adapter/src/explain/optimizer_trace.rs:77:9
sqlsmith-mz_2-1  |   43: <mz_adapter::coord::Coordinator>::sequence_explain_plan
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:2655:31
sqlsmith-mz_2-1  |   44: <mz_adapter::coord::Coordinator>::sequence_explain
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:2592:17
sqlsmith-mz_2-1  |   45: <mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}::{closure#0}
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/adapter/src/coord/sequencer.rs:278:17
sqlsmith-mz_2-1  |   46: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}::{closure#0}> as core::future::future::Future>::poll
sqlsmith-mz_2-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
sqlsmith-mz_2-1  |   47: <mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/adapter/src/coord/sequencer.rs:54:5
sqlsmith-mz_2-1  |   48: <mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}::{closure#0}
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/adapter/src/coord/command_handler.rs:558:78
sqlsmith-mz_2-1  |   49: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}::{closure#0}> as core::future::future::Future>::poll
sqlsmith-mz_2-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
sqlsmith-mz_2-1  |   50: <mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/adapter/src/coord/command_handler.rs:360:5
sqlsmith-mz_2-1  |   51: <mz_adapter::coord::Coordinator>::handle_execute::{closure#0}::{closure#0}
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/adapter/src/coord/command_handler.rs:357:61
sqlsmith-mz_2-1  |   52: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_execute::{closure#0}::{closure#0}> as core::future::future::Future>::poll
sqlsmith-mz_2-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
sqlsmith-mz_2-1  |   53: <mz_adapter::coord::Coordinator>::handle_execute::{closure#0}
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/adapter/src/coord/command_handler.rs:300:5
sqlsmith-mz_2-1  |   54: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_execute::{closure#0}> as core::future::future::Future>::poll
sqlsmith-mz_2-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
sqlsmith-mz_2-1  |   55: <mz_adapter::coord::Coordinator>::handle_command::{closure#0}
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/adapter/src/coord/command_handler.rs:79:21
sqlsmith-mz_2-1  |   56: <mz_adapter::coord::Coordinator>::message_command::{closure#0}::{closure#0}
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/adapter/src/coord/message_handler.rs:253:33
sqlsmith-mz_2-1  |   57: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::message_command::{closure#0}::{closure#0}> as core::future::future::Future>::poll
sqlsmith-mz_2-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
sqlsmith-mz_2-1  |   58: <mz_adapter::coord::Coordinator>::message_command::{closure#0}
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/adapter/src/coord/message_handler.rs:250:5
sqlsmith-mz_2-1  |   59: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/adapter/src/coord/message_handler.rs:45:63
sqlsmith-mz_2-1  |   60: <mz_adapter::coord::Coordinator>::serve::{closure#0}
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/adapter/src/coord.rs:1353:37
sqlsmith-mz_2-1  |   61: <tokio::runtime::park::CachedParkThread>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}
sqlsmith-mz_2-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:63
sqlsmith-mz_2-1  |   62: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}>
sqlsmith-mz_2-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:107:5
sqlsmith-mz_2-1  |   63: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}>
sqlsmith-mz_2-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:73:5
sqlsmith-mz_2-1  |   64: <tokio::runtime::park::CachedParkThread>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
sqlsmith-mz_2-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:31
sqlsmith-mz_2-1  |   65: <tokio::runtime::context::BlockingRegionGuard>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
sqlsmith-mz_2-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/context.rs:315:13
sqlsmith-mz_2-1  |   66: <tokio::runtime::handle::Handle>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
sqlsmith-mz_2-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/handle.rs:264:9
sqlsmith-mz_2-1  |   67: mz_adapter::coord::serve::{closure#0}::{closure#1}
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a85f93bcdc3fcaec-1/materialize/tests/src/adapter/src/coord.rs:1568:17
sqlsmith-mz_2-1  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

There was a similar issue: https://github.com/MaterializeInc/materialize/issues/17993

From https://buildkite.com/materialize/nightlies/builds/2338
Only happens with explain it seems. I couldn't reproduce it locally. There were 16 crashes in a single hour though, so this seems to be a regression.

ci-regexp: Expression in join plan is not bound at time of use

### PR DESCRIPTION
**Pull request by aalexandrov**
More changes to `sequence_explain_path` to align it with the current code with `sequence_peek_stage`.

### Motivation

  * This PR fixes a recognized bug.

Fixes #19214 (this is a fix for one of the two independently discovered bugs).

### Tips for reviewer

I found quite a few places where the current `sequence_explain_plan` implementation was diverging from the "source of truth" (which at the moment I consider to be `sequence_peek_stage`). I tried to align those, but I will follow up with a design doc that explains the general problem so @MaterializeInc/surfaces and @MaterializeInc/compute can agree on the actual problem and on a long-term solution path. The current solution is not stable because:

1. Nothing stops the two methods from diverging again in the future,
2. In the future, we want to be able to faithfully reproduce the query lifecycle of not only `SELECT`, but also `CREATE INDEX` / `CREATE VIEW` / `CREATE MATERIALIZED VIEW`.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - There are no user-facing behavior changes.

### CODE REVIEW

File: src/adapter/src/coord/sequencer/inner.rs [hunk 1]
```diff
@@ -2702,8 +2701,20 @@ impl Coordinator {
...
+            builder.import_view_into_dataflow(&explainee_id, &optimized_plan, &mut dataflow)?;
+
+            // Resolve all unmaterializable function calls except mz_now(), because we don't yet have a
+            // timestamp.
+            let style = ExprPrepStyle::OneShot {
+                logical_time: EvalTime::Deferred,
+                session,
+            };
+            let state = self.catalog().state();
+            dataflow.visit_children(
```
Comment (aalexandrov) [inline src/adapter/src/coord/sequencer/inner.rs:2714]: The source of the bug was that I forgot to add this call in #19190.

File: src/adapter/src/coord/sequencer/inner.rs [hunk 2]
```diff
@@ -2746,15 +2757,22 @@ impl Coordinator {
...
+                // By default, `until` will be `Antichain::new()`, which prevents no updates and is safe.
+                if let Some(as_of) = dataflow.as_of.as_ref() {
+                    if !as_of.is_empty() {
+                        if let Some(next) = as_of.as_option().and_then(|as_of| as_of.checked_add(1))
+                        {
+                            dataflow.until = timely::progress::Antichain::from_elem(next);
+                        }
+                    }
+                }
+            }
```
Comment (teskje) [inline src/adapter/src/coord/sequencer/inner.rs:2771]: This part might be interesting to @vmarcos: It will make it so that the EXPLAIN output will contain the monotonic operators when the "monotonic one-shot SELECTs" feature flag is set.

**Review by teskje — APPROVED** [review]

File: src/adapter/src/coord/sequencer/inner.rs (hunk 2 above)
Comment (aalexandrov) [reply src/adapter/src/coord/sequencer/inner.rs:2771]: I'm now running `sqllogictest` to see if this changes any plans at the moment.

**Review by ggevay — APPROVED** [review]
LGTM, but let's wait for @vmarcos.

**Comment by mjibson** [comment]
It'd be amazing if the individual stage functions could be re-used in the explain code to prevent these kinds of problems. Probably not a priority now, but a reasonable goal.

**Review by vmarcos — APPROVED** [review]
LGTM! When the `enable_monotonic_oneshot_selects` feature flag is on, this change will allow us to see plan differences for one-shot `SELECT`s with `EXPLAIN PHYSICAL PLAN`. So it is for me quite a convenient change until we get to revisit the options in #18089.
