### PR TITLE
sql: Implement date_part for Time data type

### LINKED ISSUE #5701: EXTRACT/DATE_PART/DATE_TRUNC of DATE parts allowed on TIME values
```
$ materialized -v
materialized v0.7.1-dev (c682e6b3a) 

```

### What was the issue?

One is allowed to extract DATE parts out of of TIME values

### Is the issue reproducible? If so, please provide reproduction instructions.

```
                                                         ^
materialize=> select extract(year from cast('11:11:11' as time));
 date_part 
-----------
         0 <- incorrect value returned
(1 row)
```

Contrast with postgresql:

```
pstoev=# select extract(year from cast('11:11:11' as time));
ERROR:  "time" units "year" not recognized
```

The time unit is only recognized if the second argument of EXTRACT / DATE_TRUNC is of a type that that has that information.

### PR DESCRIPTION
**Pull request by jkosh44**
The date_part_* functions internally implements the EXTRACT SQL
function. The Time data type didn't have any date_part implementations,
however the Interval data type did have an implementation. This caused
the Time type to be coerced into a Interval type whenever EXTRACT was
called with Time. Date related fields (such as Year, Month, Day, etc)
are valid for Interval types, therefore they become valid for Time
types too instead of returning an error.

This commit implements a date_part function for the Time data type that
returns an error for all date related fields. Now EXTRACT doesn't
coerce Time types to Interval and instead uses the Time implementation
directly.

Fixes #5701

### Motivation

This PR fixes a recognized bug: https://github.com/MaterializeInc/materialize/issues/5701

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

File: src/sql/src/func.rs [hunk 1]
```diff
@@ -1458,6 +1458,7 @@ lazy_static! {
             },
             "date_part" => Scalar {
                 params!(String, Interval) => BinaryFunc::DatePartInterval, 1172;
+                params!(String, Time) => BinaryFunc::DatePartTime, 1385;
```
Comment (jkosh44) [inline src/sql/src/func.rs:1461]: https://github.com/postgres/postgres/blob/c9105dd3660f4a801e6f87a1ed68189bd30576bf/src/include/catalog/pg_proc.dat#L2837-L2839

File: src/expr/src/scalar/func.rs [hunk 2]
```diff
@@ -1365,18 +1365,49 @@ fn ascii<'a>(a: Datum<'a>) -> Datum<'a> {
     }
 }
 
+/// A timestamp with only a time component.
+pub trait TimeLike: chrono::Timelike {
```
Comment (jkosh44) [inline src/expr/src/scalar/func.rs:1369]: This may not be the best abstraction to be honest, because it doesn't handle truncation or binning, but from what I can tell binning and truncation are not currently supported with the `Time` data type anyway. So it might be best to handle that in a separate issue. Let me know your thoughts.

## Trunc
```
materialize=> select date_trunc('hour', TIME '11:12:42.666');
ERROR:  Cannot call function date_trunc(unknown, time): arguments cannot be implicitly cast to any implementation's parameters; try providing explicit casts

materialize=> SELECT date_trunc('hour', TIMESTAMP '2001-02-16 20:38:40');
     date_trunc      
---------------------
 2001-02-16 20:00:00
(1 row)

postgres=# select date_trunc('hour', TIME '11:12:42.666');
 date_trunc 
------------
 11:00:00
(1 row)
```

## Binning
```
materialize=> SELECT date_bin('15 minutes', TIME '15:44:17', TIME '00:02:30');
ERROR:  Cannot call function date_bin(unknown, time, time): arguments cannot be implicitly cast to any implementation's parameters; try providing explicit casts

materialize=> SELECT date_bin('15 minutes', TIMESTAMP '2020-02-11 15:44:17', TIMESTAMP '2001-01-01 00:02:30');
      date_bin       
---------------------
 2020-02-11 15:32:30
(1 row)
```
(For some reason I can't get `date_bin` to run on my local postgres installation. I think because it was added in v14 but I only have v13).

File: src/expr/src/scalar/func.rs [hunk 3]
```diff
@@ -1750,6 +1755,49 @@ fn date_part_interval_inner(
...
+        | DateTimeUnits::Day
+        | DateTimeUnits::Millennium
+        | DateTimeUnits::Century
+        | DateTimeUnits::Decade
+        | DateTimeUnits::Quarter
+        | DateTimeUnits::Month
+        | DateTimeUnits::DayOfWeek
+        | DateTimeUnits::DayOfYear
+        | DateTimeUnits::IsoDayOfWeek
+        | DateTimeUnits::IsoDayOfYear => Err(EvalError::UnknownUnits(format!("{}", units))),
```
Comment (jkosh44) [inline src/expr/src/scalar/func.rs:1791]: Let me know if `UnknownUnits` is an appropriate error here. I was also thinking maybe `InvalidParameterValue`, but I wasn't sure.

Comment (benesch) [reply src/expr/src/scalar/func.rs:1791]: Whatever matches PostgreSQL is the way to go, even if that means introducing a new error variant!

**Review by benesch — COMMENTED** [review]
Nice! I’ve requested review from some folks on the SQL team but left a few starter comments inline.

File: src/expr/src/scalar/func.rs (hunk 3 above)
Comment (jkosh44) [reply src/expr/src/scalar/func.rs:1791]: Ok, so I looked around a bit and I think that `UnkownUnits` is the correct error. In materialize `UnknownUnits` is used for unit errors in the `date_part`, `date_trunc`, and `date_bin` functions.

In Materialize this error message ends up looking like: `ERROR: unkown units '{unit}'` (ex: 
```
materialize=> SELECT date_trunc('hoourr', TIMESTAMP '2001-02-16 20:38:40');
ERROR:  unknown units 'hoourr'
```
)

In postgres this error message ends up looking like `ERROR:  {type} units "{unit}" not recognized` (ex:
```
postgres=# SELECT date_trunc('hoourr', TIMESTAMP '2001-02-16 20:38:40');
ERROR:  timestamp units "hoourr" not recognized
```
)

If it's a small change I'll try and make the error message in Materialize include the type so that it matches postgres. Otherwise it might be best fixed in a followup issue/PR.

As a side note sometimes Postgres includes quotes (") around the type, ex: `ERROR:  timestamp units "hoourr" not recognized` vs `ERROR:  "time" units "hoourr" not recognized`. I'm not sure why they have this difference and I've only ever noticed the quotes when the type is `time`. Doesn't seem important enough to replicate exactly, though let me know if you disagree.

File: src/expr/src/scalar/func.rs (hunk 2 above)
Comment (jkosh44) [reply src/expr/src/scalar/func.rs:1369]: Just downloaded v14 and it looks like `date_bin` isn't supported for `TME`

```
$ psql
psql (14.1 (Ubuntu 14.1-2.pgdg20.04+1))
Type "help" for help.

postgres=# SELECT date_bin('15 minutes', TIME '15:44:17', TIME '00:02:30');
ERROR:  function date_bin(unknown, time without time zone, time without time zone) does not exist
LINE 1: SELECT date_bin('15 minutes', TIME '15:44:17', TIME '00:02:3...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

postgres=# SELECT date_bin('15 minutes', TIMESTAMP '2020-02-11 15:44:17', TIMESTAMP '2001-01-01 00:02:30');
      date_bin       
---------------------
 2020-02-11 15:32:30
(1 row)
```

Postgres docs seem to support this as well: https://www.postgresql.org/docs/devel/functions-datetime.html
> source is a value expression of type timestamp or timestamp with time zone. (Values of type date are cast automatically to timestamp.)

File: src/expr/src/scalar/func.rs (hunk 3 above)
Comment (benesch) [reply src/expr/src/scalar/func.rs:1791]: Huh! Good eye. Yeah, as long as you're using the error type that *should* match PostgreSQL, that's good enough for this PR. Matching error messages exactly is pretty far down on the list of important PostgreSQL compat stuff.

The quoting of `"time"` and `"time with time zone"` appears to be just an inconsistency in the PostgreSQL error messages: https://github.com/postgres/postgres/blob/95ab1e0a9db321dd796344d526457016eada027f/src/backend/utils/adt/date.c#L2208

Comment (jkosh44) [reply src/expr/src/scalar/func.rs:1791]: Sounds good, thanks for the feedback. In that case I'll resolve this conversation.

Comment (sploiselle) [inline src/expr/src/scalar/func.rs:1791]: I think including the type for which these are unrecognized units (i.e. matching PG) would be nice here because this represents the first type with units disjoint from the others. As Nikhil points out elsewhere, not a big deal to match things _so_ specifically, but this would be a nice piece of UX polish no one is likely to do at a later point in time.

File: test/sqllogictest/dates-times.slt [hunk 4]
```diff
@@ -751,6 +751,24 @@ SELECT (INTERVAL '1-3' YEAR TO MONTH)::text
...
+query RRRRR
+SELECT EXTRACT(hour from TIME '11:12:42.666'),
+    EXTRACT(minute from TIME '11:12:42.666'),
+    EXTRACT(second from TIME '11:12:42.666'),
+    EXTRACT(milliseconds from TIME '11:12:42.666'),
+    EXTRACT(microseconds from TIME '11:12:42.666')
+----
+11 12 42.666 42666 42666000
+
+query error
```
Comment (sploiselle) [inline test/sqllogictest/dates-times.slt:763]: I much prefer to include some part of the error message to make the test more legible in the future.

```diff
diff --git a/test/sqllogictest/dates-times.slt b/test/sqllogictest/dates-times.slt
index 7d8323659..3eb8c473f 100644
--- a/test/sqllogictest/dates-times.slt
+++ b/test/sqllogictest/dates-times.slt
@@ -760,13 +760,13 @@ SELECT EXTRACT(hour from TIME '11:12:42.666'),
 ----
 11 12 42.666 42666 42666000
 
-query error
+query error unknown units 'year'
 SELECT EXTRACT(year from TIME '11:12:42.666')
 
-query error
+query error unknown units 'month'
 SELECT EXTRACT(month from TIME '11:12:42.666')
 
-query error
+query error unknown units 'day'
 SELECT EXTRACT(day from TIME '11:12:42.666')
 
 query RR
```

File: src/expr/src/scalar/func.rs (hunk 2 above)
Comment (sploiselle) [reply src/expr/src/scalar/func.rs:1369]: Given that this is a re-specification of the existing abstraction, I think it's a-ok.

**Review by sploiselle — APPROVED** [review]
LGTM modulo request to include type in `EvalError::UnknownUnits`, though that isn't strictly necessary. Thanks so much for this, @jkosh44.

File: test/sqllogictest/dates-times.slt (hunk 4 above)
Comment (jkosh44) [reply test/sqllogictest/dates-times.slt]: Added the error messages.

File: src/expr/src/scalar/func.rs (hunk 3 above)
Comment (jkosh44) [reply src/expr/src/scalar/func.rs]: I found yet another inconsistency in Postgres error messages, sometimes they say "not supported" instead of "not recognized". Ex:
```
postgres=# SELECT EXTRACT(seccoond FROM DATE '2006-01-01');
ERROR:  date units "seccoond" not recognized
postgres=# SELECT EXTRACT(second FROM DATE '2006-01-01');
ERROR:  date units "second" not supported
```
I decided to add this as a separate error message because I thought that it conveyed more clearly that the unit type is known, just not supported for the given type.

File: src/expr/src/scalar/func.rs [hunk 5]
```diff
@@ -1365,18 +1365,51 @@ fn ascii<'a>(a: Datum<'a>) -> Datum<'a> {
...
+    }
+
+    fn extract_microsecond(&self) -> f64 {
+        let s = f64::from(self.second() * 1_000_000);
+        let ns = f64::from(self.nanosecond()) / 1e3;
+        s + ns
+    }
+}
+
+impl TimeLike for chrono::NaiveTime {}
```
Comment (jkosh44) [inline src/expr/src/scalar/func.rs:1397]: If there's a more concise method of these 3 lines, let me know.

File: src/repr/src/scalar.rs [hunk 6]
```diff
@@ -606,6 +606,33 @@ impl<'a> Datum<'a> {
         }
         is_instance_of_scalar(self, &column_type.scalar_type)
     }
+
+    /// Returns the name of the type
+    pub fn type_name(&self) -> &'static str {
```
Comment (jkosh44) [inline src/repr/src/scalar.rs:611]: Just adding a comment here so it's not missed, since it was added after the PR was approved.

Comment (sploiselle) [reply src/repr/src/scalar.rs:611]: Ah, rather than this I was imagining simply using `"time".to_string()` in the error message.

This function is not as comprehensive as it seems because of e.g. custom types, which would need to return their specified names, which requires catalog access, which we don't have at this point. Additionally, complex types lose the declaration of their inner types, etc. We don't plan to support custom time-related types _and_ time is simple, though, so I don't think there's much risk in including the type name in the error message above. However, given that this isn't actually generalizable, don't think an apparently-general solution is quite right.

Welcome to the wonders of SQL :D

Comment (jkosh44) [reply src/repr/src/scalar.rs:611]: Got it. I was originally nervous about hardcoding the type because while `date_part_time_inner` is only accessible for the `Time` type, other functions like `date_part_timestamp_inner` are accessible through multiple types. Though since for now the error is only returned in places were the type is certain, it's probably not a big deal.

File: src/expr/src/scalar/func.rs (hunk 3 above)
Comment (benesch) [reply src/expr/src/scalar/func.rs]: Yeah turns out it's an intentional deviation, per Tom Lane: https://www.postgresql.org/message-id/flat/CAPWqQZRa58atSHDgbDraAAo2371zBdmcAej7e-%3D8g%2BYxJa35uA%40mail.gmail.com#cd1c7e5dc7c7ee8364920af6cc1801ab. Since they use different error codes using distinct error variants is exactly right.

If that patch goes in then the error messages will change to:

    unit "second" not supported for type date

and:

    unit "second" not recognized for type date

But feel free to dump any of that work into #9853 if you want to get on with your life. :)

File: src/expr/src/scalar/func.rs (hunk 5 above)
Comment (benesch) [reply src/expr/src/scalar/func.rs]: This is about as concise as it gets with Rust. :)

File: test/sqllogictest/dates-times.slt (hunk 4 above)
Comment (benesch) [reply test/sqllogictest/dates-times.slt]: Just wanted to note that it's actually much more important than just legibility! If you don't include the error message, it's very easy to typo the test, e.g.:

```
query error
SELECT EXTRACT (YEAR FROM TIEM '11:12:42.666')
```

SLT will happily stamp that test as a success, but what you're really testing there is that `TIEM` is recognized as a typo. 

(...speaking as someone who's done this more than a few times.)

File: src/expr/src/scalar/func.rs (hunk 3 above)
Comment (jkosh44) [reply src/expr/src/scalar/func.rs]: I'll include it in this PR, since it's so small. Though for the not recognized error we don't have a good way of deriving the type in the general case so I'll leave it out for now. 

As a follow up I noticed some other inconsistencies in our date-time functions from Postgres. I'm planning on detailing them in an issue after this.

Comment (jkosh44) [reply src/expr/src/scalar/func.rs]: Also if your interested in some more postgres inconsistencies, here's an interesting one I noticed related to this PR. The date-time docs can be found here: https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-EXTRACT


As per the `EXTRACT` docs, `EXTRACT` is implemented for `time`, so you cannot try and extract a date related field from `time`.
> source must be a value expression of type timestamp, time, or interval. (Expressions of type date are cast to timestamp and can therefore be used as well.)
```
postgres=# SELECT EXTRACT(month FROM time '20:38:40');
ERROR:  "time" units "month" not recognized
```


As per the `DATE_TRUNC` docs, `DATE_TRUNC` is not implemented for `time`. Instead `time` gets cast to `interval`. Since date related fields are valid for `interval`, you can trunc a `time` using date related fields.
> source is a value expression of type timestamp, timestamp with time zone, or interval. (Values of type date and time are cast automatically to timestamp or interval, respectively.) 
```
postgres=# SELECT DATE_TRUNC('month', time '20:38:40');
 date_trunc 
------------
 00:00:00
(1 row)
```


As per the `EXTRACT` docs, `EXTRACT` is not implemented for `date`. Instead `date` gets cast to `timestamps`. Using the logic before, since time related fields are valid for `timestamp`, then you should be able to extract time related fields from `date`.
> source must be a value expression of type timestamp, time, or interval. (Expressions of type date are cast to timestamp and can therefore be used as well.)
```
postgres=# SELECT EXTRACT(second FROM date '2001-02-16');
ERROR:  date units "second" not supported
```
However as you can see you can't.


As per the `DATE_TRUNC` docs, `DATE_TRUNC` is not implemented for `date`. Instead `date` gets cast to `timestamp`. Now using the logic before it's unclear whether or not you can trunc a `date` using time related fields.
>  source is a value expression of type timestamp, timestamp with time zone, or interval. (Values of type date and time are cast automatically to timestamp or interval, respectively.) 
```
postgres=# SELECT DATE_TRUNC('second', date '2001-02-16');
       date_trunc       
------------------------
 2001-02-16 00:00:00-05
(1 row)
```
However it seems like you can.


Not really sure how to reconcile these inconsistencies, maybe it's just a bug.

Comment (jkosh44) [reply src/expr/src/scalar/func.rs]: Mystery solved. The documentation seems to be incorrect. `EXTRACT` actually is implemented for the `date` type (https://github.com/postgres/postgres/blob/dfe67c0e85a5a613f802f78641ccc1c48845076e/src/backend/utils/adt/date.c#L1068-L1242). So it validates the units.

`DATE_PART` however is not implemented for the `date` type. so it doesn't validate the units.
```
postgres=#  SELECT EXTRACT(second FROM date '2000-12-16 12:21:13');
ERROR:  date units "second" not supported

postgres=#  SELECT DATE_PART('second', date '2000-12-16 12:21:13');
 date_part 
-----------
         0
(1 row)

```

**Comment by benesch** [comment]
Tyvm!
