### PR TITLE
Fix subscribe tracking

### LINKED ISSUE #15181: ActiveReplication client fails to forward SubscribeResponse::DroppedAt messages
### What version of Materialize are you using?

main

### How did you install Materialize?

Built from source

### What is the issue?

Reported by @benesch [in Slack](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1664898663247959):

The active replication client does not properly produce `SubscribeResponse::DroppedAt` messages. It’s easy to see this by dropping in some `println!`s. This probably causes a small memory leak in the coordinator, and also makes the [metric @bensch just added to track the number of active subscribes](https://github.com/MaterializeInc/materialize/pull/15161) to never decrease.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by teskje**
This PR fixes two issues related to tracking of SUBSCRIBE progress in compute:

1. `ActiveReplication` swallows `SubscribeResponse::DroppedAt` because `frontier_tracking` has already removed all tracking state for a subscribe before we see this response from our replicas.

    This is fixed by `ActiveReplication` immediately emitting a `DroppedAt` response upon seeing a command that causes us to cease tracking a subscribe frontier. This is in line with how we emit `PeekResponse::Canceled` immediately after seeing a `CancelPeeks` command in `ActiveReplication`. It means that we are not waiting for replicas to report that they are actually finished processing a subscribe. But even before this change we didn't wait for all replicas, just for the first one.

2. `computed` emits a `FrontierUppers` in response to receiving an `AllowCompaction([])` for a subscribe. Subscribe frontiers are tracked through `SubscribeResponse::Batch`es, we shouldn't emit `FrontierUppers` responses for them. 

    This is fixed by adding a check in `computed`'s `AllowCompaction` handler.

### Motivation

  * This PR fixes a recognized bug.

Fixes #15181.

### Tips for reviewer

Look at the commits separately:

* Commit 1 just re-arranges some code in `replicated.rs`, to reduce the amount of indentation there.
* Commit 2 addresses issue 1 described above.
* Commit 3 addresses issue 2 described above.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

File: src/compute-client/src/controller/replicated.rs [hunk 1]
```diff
@@ -447,12 +469,15 @@ where
                 //    information as a `FrontierUppers` response.
 
                 let old_upper_bound = entry.bounds.upper.clone();
-                if !entry.update(replica_id, upper) {
+                if !entry.update(replica_id, upper.clone()) {
```
Comment (antiguru) [inline src/compute-client/src/controller/replicated.rs:472]: Nit: It seems we could avoid the `clone` by remembering only if the frontier is empty.

**Review by antiguru — APPROVED** [review]
Looks fine! Thanks.

**Comment by teskje** [comment]
TFTR!

> I'm still weirded out by us returning `FrontierUppers` at all in response to `AllowCompaction`

Your concerns have been noted and are tracked in https://github.com/MaterializeInc/materialize/issues/15104!
