### PR TITLE
coord: change more logging views to consistent catalog views

### LINKED ISSUE #2576: Lag between logging sources and catalog changes
We recently introduced `mz_kafka_sinks` and `mz_avro_ocf_sinks` as two logging sources that maintain metadata for kafka and avro ocf sinks respectively. However, these (and potentially other logging sources) have the potential to be inconsistent with catalog changes -- specifically if a catalog entry is deleted and reinserted, we can repeatedly see stale metadata that should have been deleted.

I wasn't able to reproduce this manually (perhaps I'm too slow of a typer) but I can reliably reproduce this with this diff to the avro ocf testdrive test
```
altaria-2:materialize Test$ git diff
diff --git a/test/testdrive/avro-ocf.td b/test/testdrive/avro-ocf.td
index 573de754..d94b03f3 100644
--- a/test/testdrive/avro-ocf.td
+++ b/test/testdrive/avro-ocf.td
@@ -165,19 +165,19 @@ ts            NO      timestamp
 ts_tz         NO      timestamp
 mz_obj_no     NO      int8

-> CREATE SINK basic_sink_${testdrive.seed} FROM basic
+> CREATE SINK basic_sink FROM basic
   INTO AVRO OCF '${testdrive.temp-dir}/basic-sink.ocf'

-$ avro-ocf-verify sink=materialize.public.basic_sink_${testdrive.seed}
+$ avro-ocf-verify sink=materialize.public.basic_sink
 {"before": null, "after": {"a": 1, "b": 2, "mz_obj_no": 1}}
 {"before": null, "after": {"a": 3, "b": 4, "mz_obj_no": 2}}

 > CREATE VIEW dateish AS
   SELECT d FROM timestamp_source

-> CREATE SINK date_sink_${testdrive.seed} FROM dateish
+> CREATE SINK date_sink FROM dateish
   INTO AVRO OCF '${testdrive.temp-dir}/date-sink.ocf'

-$ avro-ocf-verify sink=materialize.public.date_sink_${testdrive.seed}
+$ avro-ocf-verify sink=materialize.public.date_sink
 {"before": null, "after": {"d": 10988}}
 {"before": null, "after": {"d": 10957}}
altaria-2:materialize Test$
```

This diff changes it so sink names are identical across repeat runs of the test (as they should be)

When you run this test it will pass the first time but fail the second time with an error like

```
test/testdrive/avro-ocf.td:171:1: error: reading sink file /var/folders/jp/0_nyxpyj4vxg8x4c1kx1vhl80000gn/T/.tmplwBXdj/basic-sink-u46-1586210039-8060089200439147410.ocf: No such file or directory (os error 2)
     |
 170 |
 171 | $ avro-ocf-verify sink=materialize.public.basic_sink
     | ^
altaria-2:materialize Test$ git diff
```

Note the `basic-sink-u46` in the file name -- this is telling us that its mapping a sink named `basic-sink` to global id `u46`

but if you look at the log output you will see that `basic-sink` was dropped along with its source

```
Apr 06 17:55:20.148  INFO catalog: drop index materialize.public.basic_primary_idx (u37)
Apr 06 17:55:20.148  INFO catalog: drop sink materialize.public.basic_sink (u46)
Apr 06 17:55:20.148  INFO catalog: drop source materialize.public.basic (u36)
```

and currently `basic-sink` is bound to a different global id

```
Apr 06 17:55:20.839  INFO catalog: create sink materialize.public.basic_sink (u59)
```

### PR DESCRIPTION
**Pull request by benesch**
This commit moves the following logging views over to the new catalog
view framework:

  * mz_avro_ocf_sinks
  * mz_catalog_names
  * mz_view_foreign_keys
  * mz_view_keys

These views are often queried immediately after a catalog-altering
operation, so it makes for a much better user experience if they are
guaranteed to be up-to-date with respect to catalog changes. For
example, we are able to remove several retry loops from our sink test
code, instead relying on the newly-guaranteed consistency of these
views.

Only one usage of SequencedCommand::AppendLog remains, for frontier
information. Porting this over to a catalog view is tricky, as it
results in runaway CPU usage: if it's a catalog view, updating a catalog
view results in new frontier information, which results in more updates
to the catalog view...

Fix #2576.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/3682)

### CODE REVIEW

File: demo/billing/src/mz_client.rs [hunk 1]
```diff
@@ -136,21 +118,16 @@ impl MzClient {
...
-
-            log::debug!("received a topic name {:?}", topic_name);
-            Ok(topic_name)
-        })
-        .await
+        // Get the topic for the newly-created sink.
+        let row = self
+            .0
+            .query_one(
+                "SELECT topic FROM mz_kafka_sinks NATURAL JOIN mz_catalog_names \
```
Comment (ruchirK) [inline demo/billing/src/mz_client.rs:125]: !!

**Comment by benesch** [comment]
Ok, great! I'll file a follow up issue about the frontiers thing.
