### PR TITLE
compute: use `ReadHold` in the controller

### LINKED ISSUE #24266: Refactor controller read hold API
The current API provided by the controller around read holds is confusing. These are some of the issues:

* There is an `implied_capability` and a set of `read_capabilities`. It is not obvious which one to use when querying the read frontier of a collection.
* Read holds can be taken using `update_read_capabilities` (modifying `read_capabilities` directly) but also by setting a read policy (modifying `implied_capability`).
* When setting a read policy to attempt to take a read hold before `implied_capability`, nothing happens because the capability is not allowed to regress. The caller is not informed about this fact. So if you set a read policy to install a read hold, it might be that this fails without you noticing.

We should come up with a better API that's less confusing and not as much of a footgun. I suspect that some of the current timestamp selection bugs in Compute could be avoided that way.

[In Slack](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1700550352787449) @aljoscha and @petrosagg proposed this:

* The read policy should be either `NoPolicy` or `LagWriteFrontier`. It should not be possible to install read holds by changing the policy. (Perhaps it shouldn't even be possible to change the policy at all.)
* The controller should not expose `implied_capability` or `read_capabilities`.
* Instead it should expose an `acquire_read_hold` method that returns a `ReadHold` object that behaves like a Timely `Capability`. You can:
    * Clone it.
    * Downgrade it to allow compaction to some new read frontier.
    * Drop it to uninstall the read hold.
    * Query it for its time to get a valid read frontier of the collection.

### PR DESCRIPTION
**Pull request by teskje**
The PR moves the compute controller from manually manipulating collection's `read_capabilities` to using `ReadHold` objects instead. The result of this is significantly simplified code, since the various places that maintain read holds are now immediately recognizable by grepping for uses of the `ReadHold` type, and downgrading a read hold is now a single method call, rather than a multi-line `ChangeSet` application. Another benefit is now that parts that need to keep read holds are no longer tightly coupled to the `Instance` state, as they don't need access to `Instance::update_read_capabilities` anymore. This, for example, opens up the opportunity to attempt to factor out the replication logic in a follow up.

Another cool thing is that for debugging frontier issues, we can now use the coordinator's dump endpoint (`<internal-http-port>/api/coordinator/dump`, which also dumps the compute controller state) to see which read holds the compute controller is holding for what purposes, on which collections, for which times.

### Motivation

  * This PR adds a known-desirable feature.

Closes #24266

### Tips for reviewer

This PR is much more digestible when reviewed commit by commit. I added a couple comments to clarify some of the changes too.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

File: src/compute-client/src/controller.rs [hunk 1]
```diff
@@ -144,7 +145,7 @@ impl ComputeReplicaLogging {
 }
 
 /// A controller for the compute layer.
-pub struct ComputeController<T> {
+pub struct ComputeController<T: Timestamp> {
```
Comment (teskje) [inline src/compute-client/src/controller.rs:148]: `ReadHold<T>` includes this bound in the struct definition (it has to because its `Drop` impl requires the `Timestamp` bound), so every type that stores a `ReadHold` also needs to have the bound. You'll see this a bunch in this PR.

File: src/compute-client/src/controller/instance.rs [hunk 2]
```diff
@@ -1800,40 +1739,29 @@ where
...
-            for dep_id in &collection.storage_dependencies {
-                storage_updates
-                    .entry(*dep_id)
-                    .or_insert_with(ChangeBatch::new)
-                    .extend(update.iter().cloned());
+            for read_hold in collection.storage_dependencies.values_mut() {
+                read_hold
+                    .try_downgrade(new_since.clone())
+                    .expect("frontiers don't regress");
             }
```
Comment (teskje) [inline src/compute-client/src/controller/instance.rs:1571]: Note that these downgrades only get picked up the next time `apply_read_hold_changes` is invoked, so dependency downgrades now propagate slower than before. A later commit fixes that by inlining `update_read_capabilities` into `apply_read_hold_changes`.

File: src/compute-client/src/controller/instance.rs [hunk 3]
```diff
@@ -334,18 +334,38 @@ impl<T: ComputeControllerTimestamp> Instance<T> {
...
         let metrics = self.metrics.for_replica(id);
         let mut replica =
             ReplicaState::new(id, client, config, metrics, self.introspection_tx.clone());
 
         // Add per-replica collection state.
         for (collection_id, collection) in &self.collections {
+            // Skip log collections not maintained by this replica.
+            if collection.log_collection && !log_ids.contains(collection_id) {
+                continue;
+            }
```
Comment (teskje) [inline src/compute-client/src/controller/instance.rs:367]: I think it was an oversight that we weren't doing this before.

File: src/compute-client/src/controller/instance.rs [hunk 4]
```diff
@@ -492,42 +505,6 @@ impl<T: ComputeControllerTimestamp> Instance<T> {
...
-        if collection.hydrated() {
-            return;
-        }
-
-        // If the observed frontier is greater than the collection's as-of, the collection has
-        // produced some output and is therefore hydrated now.
-        if PartialOrder::less_than(&collection.as_of, frontier) {
-            collection.set_hydrated();
-        }
-    }
```
Comment (teskje) [inline src/compute-client/src/controller/instance.rs:510]: Moved into `ReplicaCollectionState::update_output_frontier`.

File: src/compute-client/src/controller/instance.rs [hunk 5]
```diff
@@ -492,42 +505,6 @@ impl<T: ComputeControllerTimestamp> Instance<T> {
         self.deliver_introspection_updates(IntrospectionType::ComputeDependencies, updates);
     }
 
-    /// Update the tracked hydration status for the given collection and replica according to an
-    /// observed frontier update.
-    fn update_hydration_status(
```
Comment (teskje) [inline src/compute-client/src/controller/instance.rs:478]: Moved into `ReplicaCollectionState::update_output_frontier`.

File: src/compute-client/src/controller/instance.rs [hunk 6]
```diff
@@ -1528,173 +1468,48 @@ where
...
-
-    /// Apply replica write frontier updates.
+    /// Advance the global write frontier of the given collection.
     ///
-    /// # Panics
-    ///
-    /// Panics if any of the `updates` references an absent collection.
-    /// Panics if any of the `updates` regresses an existing replica write frontier.
-    #[mz_ore::instrument(level = "debug")]
-    fn update_replica_write_frontiers(
```
Comment (teskje) [inline src/compute-client/src/controller/instance.rs:1611]: Moved into `ReplicaCollectionState::update_write_frontier`.

File: src/compute-client/src/controller/instance.rs [hunk 7]
```diff
@@ -1528,173 +1468,48 @@ where
...
-    /// Apply replica input frontier updates.
+    /// Frontier regressions are gracefully ignored.
     ///
     /// # Panics
     ///
-    /// Panics if any of the `updates` references an absent collection.
-    /// Panics if any of the `updates` regresses an existing replica input frontier.
+    /// Panics if the identified collection does not exist.
     #[mz_ore::instrument(level = "debug")]
-    fn update_replica_input_frontiers(
```
Comment (teskje) [inline src/compute-client/src/controller/instance.rs:1641]: Moved into `ReplicaCollectionState::update_input_frontier`.

File: src/compute-client/src/controller/instance.rs [hunk 8]
```diff
@@ -1838,55 +1657,37 @@ where
...
-
-        // Apply an output frontier advancement.
         if let Some(new_frontier) = frontiers.output_frontier {
-            self.update_hydration_status(id, replica_id, &new_frontier);
+            replica_collection.update_output_frontier(new_frontier.clone());
+        }
+        if let Some(new_frontier) = frontiers.write_frontier {
+            replica_collection.update_write_frontier(new_frontier.clone());
+            self.maybe_update_global_write_frontiers(&[(id, new_frontier)].into());
         }
```
Comment (teskje) [inline src/compute-client/src/controller/instance.rs:1660]: Moved to the bottom just to satisfy the borrow checker.

File: src/compute-client/src/controller/instance.rs [hunk 9]
```diff
@@ -219,6 +221,16 @@ pub(super) struct Instance<T> {
     wallclock_lag: WallclockLagFn<T>,
     /// Dynamic system configuration.
     dyncfg: Arc<ConfigSet>,
+
+    /// Sender for updates to collection read holds.
+    ///
+    /// Copies of this sender are given to [`ReadHold`]s that are created in
+    /// [`Instance::acquire_read_hold`].
+    read_holds_tx: mpsc::UnboundedSender<(GlobalId, ChangeBatch<T>)>,
```
Comment (petrosagg) [inline src/compute-client/src/controller/instance.rs:234]: There aren't any `async` usages right? If so we can just use std's channels here

File: src/compute-client/src/controller/instance.rs [hunk 10]
```diff
@@ -1097,88 +1082,39 @@ where
...
-        // read capabilities manually.
-        //
-        // TODO: Instead of acquiring these and then dropping later, we should
-        // instead store them and don't "manually" acquire read holds using
-        // `update_read_capabilities`.
-        let mut storage_read_holds = Vec::new();
+        // When we install per-replica input read holds, we cannot use the `as_of` because of
+        // reconciliation: Existing slow replicas might be reading from the inputs at times before
+        // the `as_of` and we would rather not crash them by allowing their inputs to compact too
+        // far. So instead we take read holds at the least time available.
```
Comment (petrosagg) [inline src/compute-client/src/controller/instance.rs:1088]: I didn't follow this comment. Don't we get feedback from clusters about their read frontiers? I would expect that we can get a precise read hold by looking at what was the last read frontier update we last received across all replicas. Also, how do we determine the "least time available"? Afaik persist doesn't have a guaranteed way of giving you the global since of a shard

File: src/compute-client/src/controller/instance.rs [hunk 11]
```diff
@@ -1559,226 +1447,85 @@ where
...
+    fn apply_read_hold_changes(&mut self) {
+        let mut allowed_compaction = BTreeMap::new();
+
+        while let Ok((id, mut update)) = self.read_holds_rx.try_recv() {
             let Some(collection) = self.collections.get_mut(&id) else {
-                tracing::error!(
-                    %id, ?update,
-                    "received read capability update for an unknown collection",
+                soft_panic_or_log!(
+                    "read hold change for absent collection (id={id}, changes={update:?})"
```
Comment (petrosagg) [inline src/compute-client/src/controller/instance.rs:1528]: Now that updates come through a channel what guarantees that this won't produce false positives where a collection is dropped and then later we process the downgrades? Is the cleanup logic actually in this function (and therefore it won't run until we observe an empty read frontier)?

File: src/compute-client/src/controller/instance.rs [hunk 12]
```diff
@@ -1559,226 +1447,85 @@ where
...
-
-        // We must not rely on any specific relative ordering of `GlobalId`s.
-        // That said, it is reasonable to assume that collections generally have greater IDs than
-        // their dependencies, so starting with the largest is a useful optimization.
-        while let Some((id, mut update)) = updates.pop_last() {
+    /// Apply collection read hold changes pending in `read_holds_rx`.
+    fn apply_read_hold_changes(&mut self) {
+        let mut allowed_compaction = BTreeMap::new();
+
+        while let Ok((id, mut update)) = self.read_holds_rx.try_recv() {
```
Comment (petrosagg) [inline src/compute-client/src/controller/instance.rs:1525]: This is a slight behavior change in that the old code was processing items in decreasing global id order which agrees with the reverse topological order of dependencies, which results in the maximum number of implications propagated. I don't know how important that property is

File: src/compute-client/src/controller/instance.rs (hunk 9 above)
Comment (teskje) [reply src/compute-client/src/controller/instance.rs:234]: `ReadHold::new` expects a `tokio::sync::mpsc::UnboundedSender`, so we need to use one here too. It's also used by storage, which listens on the receiver in a `select!` so we can't just change the channel type.

File: src/compute-client/src/controller/instance.rs (hunk 10 above)
Comment (teskje) [reply src/compute-client/src/controller/instance.rs:1088]: The problematic scenario is when the controller just starts up and hasn't yet reconciled with the replicas. At that point it hasn't received frontier information from the replicas yet, so we can't assume anything except that the previous instance of the controller did have read holds sufficiently far in the past for what's required by the existing replicas.

> Also, how do we determine the "least time available"?

This is just the least-downgraded read hold we can get from the storage controller. It's fundamentally best effort. If storage decides to give out a read hold that is downgraded too far, there is nothing we can do except hope that the existing replicas' reader leases don't expire.

> Afaik persist doesn't have a guaranteed way of giving you the global since of a shard

I think during bootstrap we are guaranteed to initialize the read frontiers of storage collections with the current persist sinces? If we are not then I don't see how any of the bootstrap as-of selection could work. For example, an MV dataflow needs to continue where it left off, but if we would initialize storage collections to arbitrary values greater than the persist sinces, that wouldn't always be possible.

File: src/compute-client/src/controller/instance.rs (hunk 11 above)
Comment (teskje) [reply src/compute-client/src/controller/instance.rs:1528]: We only remove collection state once there are no read capabilities on that collection anymore: https://github.com/teskje/materialize/blob/406a4c827190b40dbd65af1712eaf999362cb138/src/compute-client/src/controller/instance.rs#L660. If there are no read capabilities anymore, seeing updates would be a bug, as updates may only clone or downgrade existing capabilities.

File: src/compute-client/src/controller/instance.rs (hunk 12 above)
Comment (teskje) [reply src/compute-client/src/controller/instance.rs:1525]: It affects performance but shouldn't affect correctness. I also can't say how significant the performance difference is in practice. But it should be a small change to process batches of received updates, rather than a single update at a time, so can't hurt to just do it.

File: src/compute-client/src/controller/instance.rs (hunk 10 above)
Comment (petrosagg) [reply src/compute-client/src/controller/instance.rs:1088]: > I think during bootstrap we are guaranteed to initialize the read frontiers of storage collections with the current persist sinces? If we are not then I don't see how any of the bootstrap as-of selection could work.

We are initializing them to the SinceHandle of the controller but I was thinking that a slow replica could hold onto a leased reader that is further behind the controller's read handle, since the latter is updated through movement of the upper, which follows the faster replica.

**Review by ggevay — APPROVED** [review]
I really like the PR, there are many simplifications!

**Comment by ggevay** [comment]
Btw. for the Nightly RQG failure
"Fixpoint `fixpoint_logical_cleanup_pass_01` detected a loop of length 2 after 2 iterations",
I think we should add an ignore for this problem, so that this doesn't fail CI. (In fact, I thought we already had one, but maybe I misremembered.)

**Review by petrosagg — APPROVED** [review]
Talked through the last remaining questions, lgtm!

File: src/compute-client/src/controller.rs [hunk 13]
```diff
@@ -942,46 +952,50 @@ pub struct CollectionState<T> {
...
+    /// should modify read capabilities directly. Instead, collection users should manage read
+    /// holds through [`ReadHold`] objects acquired through [`Instance::acquire_read_hold`].
+    ///
+    /// TODO(teskje): Restructure the code to enforce the above in the type system.
     read_capabilities: MutableAntichain<T>,
-    /// The implicit capability associated with collection creation.
-    implied_capability: Antichain<T>,
-    /// A capability held to enable dataflow warmup.
+    /// A read hold maintaining the implicit capability associated with collection creation.
+    implied_read_hold: ReadHold<T>,
```
[the remark this answers is not in the document]
Comment (teskje) [reply src/compute-client/src/controller.rs:965]: The description and name predates my time at Mz, but I understand them like this: When you create a collection, you implicitly gain the capability to read it, even without installing any additional read holds. And when you drop all read holds, there is still a capability to read it around, which you can use to request new read holds.

I have thought about names for this as well, but I haven't come up with anything. Maybe we should say "the implicit capability of the collection" (strike the "creation" part)? Or call it `inherent_capability`? But changing the name would mean we'd move away from the storage controller, when we'd like to move the two closer. We could of course change the name in the storage controller as well, but I'm not sure that's worth attempting when we don't have one that's clearly better.

> I think the policy and the write frontier is what determines this, right?

Yeah, you could reframe it as "this is the capability" we keep to satisfy the read policy. But I'm not sure how to translate that to a good name either :/

File: src/compute-client/src/controller.rs [hunk 14]
```diff
@@ -942,46 +952,50 @@ pub struct CollectionState<T> {
...
     /// Introspection state associated with this collection.
     collection_introspection: CollectionIntrospection<T>,
 }
 
-impl<T> CollectionState<T> {
+impl<T: Timestamp> CollectionState<T> {
     /// Reports the current read capability.
     pub fn read_capability(&self) -> &Antichain<T> {
-        &self.implied_capability
+        self.implied_read_hold.since()
```
[the remark this answers is not in the document]
Comment (teskje) [reply src/compute-client/src/controller.rs:998]: I think it's mainly named this because I didn't want to leak the "implied" thing to adapter code. It's bad enough that we have to know what it means :D The thinking is that this is the frontier at which you are capable of reading, i.e. at which you can still get a read hold. There is also `read_frontier` which is the actual read frontier of the collection, but that's only for writing it down to introspection relations, you are not guaranteed to get a read hold at this frontier. Yes, it's confusing.

>  Could we maybe rename it?

Sure, but finding a name is again difficult!

There is a follow-up I want to do that refactors adapter's `read_policy.rs` to only store compute and storage `ReadHold`s, rather than manually creating its own surrogates. I hope that if we do that, adapter doesn't need to call this `read_capability` method anymore and we can just delete it.

File: src/compute-client/src/controller/instance.rs [hunk 15]
```diff
@@ -2373,9 +2115,33 @@ struct ReplicaCollectionState<T> {
     as_of: Antichain<T>,
     /// Tracks hydration state for this collection.
     hydration_state: HydrationState,
+    /// Read holds on storage inputs to this collection.
+    ///
+    /// These read holds are kept to ensure that the replica is able to read from storage inputs at
+    /// all times it hasn't read yet. We only need to install read holds for storage inputs since
+    /// compaction of compute inputs is implicitly held back by Timely/DD.
+    input_read_holds: Vec<ReadHold<T>>,
```
[the remark this answers is not in the document]
Comment (teskje) [reply src/compute-client/src/controller/instance.rs:2123]: I also like the shorter name, just because it's shorter! Hopefully most readers don't have to concern themselves about what read holds are in here exactly.

> I'm not sure I understand what exactly makes it not necessary here if we do it there.

Read holds on compute collections (i.e. indexes) generally need to be taken when you want to read that index at some time. Except that Timely/DD ensures that active readers of an arrangement can continue to read, so you don't need to take extra read holds just for ensuring that. This is the only thing the replica input read holds want to ensure, so we can skip them for compute collections. In fact, it would be bad to install them because it'd mean that a single slow replica could hold back the read frontier of an index, causing it to grow in memory size on all other active replicas. That happens for storage collections too, but is much less problematic because their history isn't kept in memory.

All the read holds we do explicitly take in the compute controller on compute inputs fulfill some other purpose than allowing installed dataflows to continue reading from indexes. I think currently `compute_dependencies` are the only such case. We need them to keep the `since`s of depended-on indexes far enough back that we can spin up a new replica and hydrate our dataflow from its current `since` frontier. When we spin up a new replica we also re-install the depended-on indexes on that replica, so we don't need the read holds to ensure we can physically read the arrangements on existing replicas. But we need it to (a) hold back the dataflow `as_of`s in the `ComputeCommandHistory` and (b) hold back the transitive storage dependencies of those compute inputs.

File: src/compute-client/src/controller.rs (hunk 13 above)
[the remark this answers is not in the document]
Comment (ggevay) [reply src/compute-client/src/controller.rs:965]: Ok, then maybe let's not change the name now; just making this clear in the comment would be good.

File: src/compute-client/src/controller/instance.rs [hunk 16]
```diff
@@ -2390,6 +2156,67 @@ impl<T> ReplicaCollectionState<T> {
...
+                "replica collection write frontier regression (old={:?}, new={new_frontier:?})",
+                self.write_frontier,
+            );
+            return;
+        } else if new_frontier == self.write_frontier {
+            return;
+        }
+
+        self.write_frontier = new_frontier;
+    }
```
[the remark this answers is not in the document]
Comment (teskje) [reply src/compute-client/src/controller/instance.rs:2173]: In `update_input_frontier` (and `update_output_frontier`) we do some additional work we can skip when the frontier didn't change. You are right that in `update_write_frontier` it doesn't matter, but I think it's still nice to keep the structure of the three methods consistent. Plus if there is ever some work to do when a write frontier advances, you can just put that at the end now. But yeah, no strong opinion on this.

[the remark this answers is not in the document]
Comment (ggevay) [reply src/compute-client/src/controller/instance.rs:2173]: Ok, then it's fine as it is!

File: src/compute-client/src/controller/instance.rs (hunk 15 above)
[the remark this answers is not in the document]
Comment (ggevay) [reply src/compute-client/src/controller/instance.rs:2123]: Ok, thanks for the explanation!

File: src/compute-client/src/controller.rs (hunk 13 above)
[the remark this answers is not in the document]
Comment (teskje) [reply src/compute-client/src/controller.rs:971]: Sure, I've added a blurb!

**Comment by teskje** [comment]
TFTRs!
