### PR TITLE
persist: fix bug making compaction too aggressive when under high request load

### LINKED ISSUE #8253: perist: persisting the system tables creates excessive I/O under simple SELECT workload
### What version of Materialize are you using?

```
v0.9.4-dev (42c8871dc)
```

### What was the issue?

If a workload is applied that just runs `SELECT * FROM t1` against Mz in 1 connection, persisting the system tables causes excessive I/O:

- strace reports:
 ** 300 (three hundred) files being opened within 1-second period
 ** 80 renames 
 ** 100 unlinks
- iostat reports 8Mb written every second
- iotop reports:

```
Total DISK READ:         0.00 B/s | Total DISK WRITE:      1166.47 K/s
Current DISK READ:       0.00 B/s | Current DISK WRITE:       6.26 M/s
```

The difference between "Total" and "Current" I take to mean that the metadata operations against the filesystem cause massive write amplification.

With more concurrent connections, the I/O consumption increases to 12Mb/s -- I think it would have gone higher had ,Mz  been able to scale linearly.

### Is the issue reproducible? If so, please provide reproduction instructions.

Just run a simple `SELECT` workload using your favorite tool.

### PR DESCRIPTION
**Pull request by danhhz**
### Motivation

  * This PR fixes a recognized bug. #8253

### Description

HACK: This rate limits how much we call step in response to workloads consisting entirely of write, seal, and allow_compaction (which is exactly what we expect in the common/steady state). At the moment, step is too aggressive about compaction if called in a tight loop, causing excess disk usage. This is exactly what happens if coord is getting steady read traffic over indexes derived directly or indirectly from tables (it continually seals).

The downside to this rate limiting is that it introduces artificial latency into filling the response futures we returned to the client as well as to updating listeners. The former blocks literally no critical paths in the initial persisted system tables test. The latter holds up reading from the system tables being persisted, which is considered an acceptable tradeoff for the short-term. In the long-term, we'll do something better (probably by using Buffer).

Closes #8253

### Checklist

- [x] This PR has adequate test coverage.
- [x] This PR adds a release note for any user-facing behavior changes.

### CODE REVIEW

**Comment by danhhz** [comment]
I'm going to keep testing this more overnight, but this seems to do the trick. I tried hard to keep it (a) as simple as possible and (b) as easy to reason about as possible while still (c) fixing the issue.

File: src/persist/src/indexed/runtime.rs [hunk 1]
```diff
@@ -62,23 +70,39 @@ where
...
-    let handle = thread::Builder::new()
+    let impl_handle = thread::Builder::new()
         .name(format!("persist-runtime-{}", id.0))
         .spawn(runtime_f)?;
-    let handle = Mutex::new(Some(handle));
+    let ticker_tx = tx.clone();
+    let ticker_handle = thread::Builder::new()
+        .name(format!("persist-ticker"))
+        .spawn(move || {
+            let tick_interval = config.min_step_interval / 10;
```
Comment (ruchirK) [inline src/persist/src/indexed/runtime.rs:88]: I'm not really sure about the / 10 here. It seems like it gets entirely defeated by the fact that we check whether the `min_step_interval` has elapsed since the last step and so this makes us send 9 additional `tick`s that are no-ops. I think the intent is to provide a stronger guarantee that `step` will definitely get called within the requested interval, but it's not clear to me that dividing by 2 is any worse than dividing by 10 (because of the check mentioned above). At the very least the rationale here could use a comment

File: src/persist/src/indexed/runtime.rs [hunk 2]
```diff
@@ -705,17 +792,51 @@ impl<L: Log, B: Blob> RuntimeImpl<L, B> {
...
+        // strategy.
+        let need_step = step_start.duration_since(self.prev_step) > self.min_step_interval;
+
+        // BONUS HACK: If pending_responses is empty, then we know nothing has
+        // changed and step would be a no-op. Unfortunately, step is not yet
+        // smart about actually being a no-op and will still write out meta
+        // (three times, in fact).
+        //
+        // TODO: Make step smarter and remove this hack.
+        let need_step = need_step && !self.indexed.pending_responses.is_empty();
```
Comment (ruchirK) [inline src/persist/src/indexed/runtime.rs:824]: So we would enter this state iff the only command we received was a `Tick` under normal operations (where we see sequences of `Write`, `Seal`, `AllowCompaction`, and `Tick` in steady state right?)

I'm trying to wrap my head around why `need_step` would be true, and `pending_responses` would be empty. I don't have a good intuition for how frequently `coord` calls `seal` or `allow_compaction` anymore and my sense is that for `mz_metrics` coord calls `write` every 30 seconds.

But if I'm understanding everything correctly it seems like -- let's say the tick interval is 1s, then we'll send ticks every 100 ms according to the code above, but then if we see `seal`s every 10 ms, say because someone is hitting mz with 100 selects a second (dunno if that's even possible) then most of the time the bonus hack won't help us at all (because we'll have pending seals to respond to every time we're actually allowed to call `step`)

Sorry if I'm missing something simple here, but its hard for me to see concretely what workloads the bonus hack is actually useful in.

**Review by ruchirK — APPROVED** [review]
Mostly lgtm! I have some questions around the bonus hack - having a hard time seeing when it is useful and how useful it will be, but other than that everything else seems totally reasonable!

File: src/persist/src/indexed/runtime.rs (hunk 2 above)
Comment (ruchirK) [reply src/persist/src/indexed/runtime.rs:824]: I guess the bonus hack is useful in cases when seals / allow compactions and writes are all performed less frequently than the step interval. in those cases, tick might tell us "hey you need to call step its been one second" but if we havent received any seals, allow compactions or writes in the past second, we can ignore the tick. Is that right?

Comment (danhhz) [reply src/persist/src/indexed/runtime.rs:841]: Yes, you got in exactly right in the followup. Added a comment. Fwiw, this optimization applies to all of our current release load tests :)

> I don't have a good intuition for how frequently coord calls seal or allow_compaction anymore and my sense is that for mz_metrics coord calls write every 30 seconds.

Added a comment with this info

**Review by danhhz — COMMENTED** [review]
TFTR and welcome back! :D
