### PR TITLE
expr,sql: give every aggregate function an identity

### LINKED ISSUE #3872: Panic while running `jsonb_agg` with `filter`
### What version of Materialize are you using?

Commit d96243df8

### How did you install Materialize?
* [x] Built from source

### What was the issue?
Materialize panics and exits after running the following query `jsonb_agg` and `filter`:
```sql
select jsonb_agg(val) filter (where filter)
from (values (1, true), (2, true), (3, false)) as t (val, filter);
```

I also managed to make a similar query fail with `ERROR:  internal error: column 2 is not of expected type jsonb?: [null, "2020-01-16T13:59:00.557Z"]`, but when trying to reproduce it without actual data, I hit the panic instead.

### Is the issue reproducible? If so, please provide reproduction instructions.
Run the following query:
```sql
select jsonb_agg(val) filter (where filter)
from (values (1, true), (2, true), (3, false)) as t (val, filter);
```

### Please attach any applicable log files.
The stack trace was:

```
 thread: <unnamed>
message: Expected datum of type ColumnType { nullable: false, scalar_type: Jsonb }, got value List([Float64(OrderedFloat(1.0)), Float64(OrderedFloat(2.0)), Null])
   0: materialized::handle_panic
             at /home/ec2-user/materialize/src/materialized/src/bin/materialized.rs:388
   1: core::ops::function::Fn::call
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/ops/function.rs:72
   2: std::panicking::rust_panic_with_hook
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/panicking.rs:490
   3: rust_begin_unwind
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/panicking.rs:388
   4: std::panicking::begin_panic_fmt
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/panicking.rs:342
   5: expr::relation::RelationExpr::typ
             at /home/ec2-user/materialize/src/expr/src/relation/mod.rs:216
   6: transform::reduction::FoldConstants::action
             at /home/ec2-user/materialize/src/transform/src/reduction.rs:40
   7: expr::relation::RelationExpr::try_visit_mut::{{closure}}
             at /home/ec2-user/materialize/src/expr/src/relation/mod.rs:860
      expr::relation::RelationExpr::try_visit1_mut
             at /home/ec2-user/materialize/src/expr/src/relation/mod.rs:804
      expr::relation::RelationExpr::try_visit_mut
             at /home/ec2-user/materialize/src/expr/src/relation/mod.rs:860
   8: <transform::reduction::FoldConstants as transform::Transform>::transform
             at /home/ec2-user/materialize/src/transform/src/reduction.rs:33
   9: transform::Optimizer::transform
             at /home/ec2-user/materialize/src/transform/src/lib.rs:168
      transform::Optimizer::optimize
             at /home/ec2-user/materialize/src/transform/src/lib.rs:269
  10: coord::coord::Coordinator<C>::sequence_peek
             at /home/ec2-user/materialize/src/coord/src/coord.rs:1305
      coord::coord::Coordinator<C>::sequence_plan
             at /home/ec2-user/materialize/src/coord/src/coord.rs:815
  11: coord::coord::Coordinator<C>::serve_core
             at /home/ec2-user/materialize/src/coord/src/coord.rs:504
  12: coord::coord::Coordinator<C>::serve::{{closure}}
             at /home/ec2-user/materialize/src/coord/src/coord.rs:398
      tokio::runtime::context::enter
             at /home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/context.rs:72
  13: tokio::runtime::handle::Handle::enter
             at /home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:76
      coord::coord::Coordinator<C>::serve
             at /home/ec2-user/materialize/src/coord/src/coord.rs:398
  14: materialized::serve::{{closure}}
             at /home/ec2-user/materialize/src/materialized/src/lib.rs:294
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/sys_common/backtrace.rs:130
  15: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/thread/mod.rs:475
      <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/panic.rs:318
      std::panicking::try::do_call
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/panicking.rs:297
      std::panicking::try
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/panicking.rs:274
      std::panic::catch_unwind
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/panic.rs:394
      std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/thread/mod.rs:474
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/ops/function.rs:232
  16: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/liballoc/boxed.rs:1076
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/liballoc/boxed.rs:1076
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/sys/unix/thread.rs:87
  17: start_thread
  18: thread_start
```

### PR DESCRIPTION
**Pull request by benesch**
In order to transform a SQL expression of the form

    <agg>(<expr>) FILTER (WHERE <cond>)

into

    <agg>(CASE WHEN <cond> THEN <expr> ELSE <identity>)

every aggregate function must have an identity. The transformation was
previously assuming that null was the identity for every aggregate
function, which was wrong. For example, the identity for ANY is false,
not null.

There are two big changes in this commit:

  * AggregateFunc::CountAll is removed. There was *no* identity for
    this function, because it did not look at its input. Its usage is
    replaced by Count(true).

    This has the potential to make count(*) a bit slower, but I can't
    imagine the extra null check being that expensive in practice.

  * AggregateFunc::JsonbAgg learns to treat null as the identity.
    These are not the semantics that SQL wants, but the SQL layer can
    easily recover those semantics with a coalesce shim. (Shimming
    an identity onto the old semantics, by contrast, is not possible.)

Fix #3872.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/3879)

### CODE REVIEW

File: src/transform/src/nonnullable.rs [hunk 1]
```diff
@@ -117,14 +116,3 @@ fn scalar_nonnullable(expr: &mut ScalarExpr, metadata: &RelationType) {
...
-/// Transformations to aggregation functions, based on nonnullability of columns.
-fn aggregate_nonnullable(expr: &mut AggregateExpr, metadata: &RelationType) {
-    // An aggregate that is a count of non-nullable data can be replaced by a countall.
-    if let (AggregateFunc::Count, ScalarExpr::Column(c)) = (&expr.func, &expr.expr) {
-        if !metadata.column_types[*c].nullable && !expr.distinct {
-            expr.func = AggregateFunc::CountAll;
-            expr.expr = ScalarExpr::literal_null(ColumnType::new(ScalarType::Bool, true));
-        }
-    }
-}
```
Comment (frankmcsherry) [inline src/transform/src/nonnullable.rs:130]: I might be confused, but I think we might still want this optimization. At least, something like it would be able to turn
```
select count(field)
```
into
```
select count(true)
```
which could then simplify through e.g. demand analysis.

File: test/sqllogictest/tpch.slt [hunk 2]
```diff
@@ -161,7 +161,7 @@ ORDER BY
 %0 =
 | Get materialize.public.lineitem (u21)
 | Filter (#10 <= 1998-12-01)
-| Reduce group=(#8, #9) sum(#4) sum(#5) sum((#5 * (100dec - #6))) sum(((#5 * (100dec - #6)) * (100dec + #7))) countall(null) countall(null) sum(#6) countall(null) countall(true)
+| Reduce group=(#8, #9) sum(#4) sum(#5) sum((#5 * (100dec - #6))) sum(((#5 * (100dec - #6)) * (100dec + #7))) count(#4) count(#5) sum(#6) count(#6) count(true)
```
Comment (frankmcsherry) [inline test/sqllogictest/tpch.slt:164]: This might be an example of that optimization, where previously we were able to remove the dependence on `#4` and `#5` but now do not. We obvs still need them (in earlier aggregations) but if we ditched them we could deduplicate the aggregations more easily (I guess we don't do that, though!).

File: test/sqllogictest/tpch.slt [hunk 3]
```diff
@@ -1233,7 +1233,7 @@ WHERE
 | Join %4 %5 (= #0 #2)
 | | implementation = DeltaQuery %4 %5.(#1) | %5 %4.(#0)
 | | demand = (#0, #5)
-| Reduce group=(#0) sum(#5) countall(null)
+| Reduce group=(#0) sum(#5) count(#5)
```
Comment (frankmcsherry) [inline test/sqllogictest/tpch.slt:1236]: Another example! :D

File: test/sqllogictest/tpch.slt [hunk 4]
```diff
@@ -1725,7 +1725,7 @@ ORDER BY
 %1 =
 | Get materialize.public.customer (u15)
 | Filter (((((((substr(#4, 1, 2) = "13") || (substr(#4, 1, 2) = "31")) || (substr(#4, 1, 2) = "23")) || (substr(#4, 1, 2) = "29")) || (substr(#4, 1, 2) = "30")) || (substr(#4, 1, 2) = "18")) || (substr(#4, 1, 2) = "17")), (#5 > 0dec)
-| Reduce group=() sum(#5) countall(null)
+| Reduce group=() sum(#5) count(#5)
```
Comment (frankmcsherry) [inline test/sqllogictest/tpch.slt:1728]: Last one!

File: test/sqllogictest/tpch.slt (hunk 2 above)
Comment (benesch) [reply test/sqllogictest/tpch.slt]: Ooo, great catch! I didn't look at this plan movement very in depth because I figured it would be just like the chbench movement, but evidently not.

The optimization is restored with the approach you suggest and seems to be working great now!
