### PR TITLE
computed,storaged,materialized: simplify and unify panic handling

### LINKED ISSUE #12583: computed: panicking worker does not bring down computed
### What version of Materialize are you using?

v0.26.1-dev (c5e09ac91)

### How did you install Materialize?

Built from source

### What is the issue?

If you panic a timely worker (e.g. perform a panicking `SELECT`), the entire computed instance does not appear to go down.

using `bin/materialized` or `bin/cluster-dev`, run the following series of commands in a sql client:

```
create cluster foo replica bar (size '1');
set cluster to foo;
CREATE TABLE log_table (f1 TEXT);
CREATE TABLE panic_table (f1 TEXT);
INSERT INTO panic_table VALUES ('panic!');
INSERT INTO log_table SELECT mz_internal.mz_panic(f1) FROM panic_table;
```

Observe the logs from the replica `foo.bar`, and you will see something akin to:

```
┌────────────────────────────── Logs(default/compute-cluster-2-replica-2-0:default)[1m] ───────────────────────────────┐
│                           Autoscroll:On     FullScreen:Off     Timestamps:Off     Wrap:Off                           │
│ computed: 2022-05-19T14:27:13.576709Z  INFO computed: about to bind to "0.0.0.0:2100"                                │
│ computed: 2022-05-19T14:27:13.576811Z  INFO computed: listening for coordinator connection on 0.0.0.0:2100...        │
│ computed: 2022-05-19T14:27:13.576830Z  INFO computed: serving computed HTTP server on 0.0.0.0:6875                   │
│ computed: 2022-05-19T14:27:13.577144Z  INFO mz_storage::boundary::tcp_boundary::client: About to connect to "storage │
│ computed: 2022-05-19T14:27:13.578379Z  INFO mz_storage::boundary::tcp_boundary::client: Connected to storage server  │
│ computed: 2022-05-19T14:27:43.099426Z  INFO computed: coordinator connection accepted                                │
│ thread 'timely:work-0' panicked at 'panic!', src/expr/src/scalar/func/impls/string.rs:717:9                          │
│ note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                        │
│ computed: 2022-05-19T14:28:20.261174Z  WARN mz_storage::boundary::tcp_boundary::client: Receiver hung up             │
│ computed: 2022-05-19T14:28:20.262756Z  INFO computed: coordinator connection gone; lingering                         │
│ computed: 2022-05-19T14:28:20.267009Z  INFO computed: coordinator connection accepted
```

The trailing lines indicate that the `computed` instance did not crash. If you monitor the status through K8s, you'll see:

```
NAMESPACE     NAME                               READY   STATUS    RESTARTS      AGE
default       compute-cluster-1-replica-1-0      1/1     Running   0             65m
default       compute-cluster-2-replica-2-0      1/1     Running  4              64m
```

irrespective of the length of the run, i.e. `compute-cluster-2-replica-2-0 ` (the replica was panicked) never restarted.

Now perform the same set of operations with the following patch:

```diff
diff --git a/src/compute/src/server.rs b/src/compute/src/server.rs
index b34fac761..bdb1348fa 100644
--- a/src/compute/src/server.rs
+++ b/src/compute/src/server.rs
@@ -157,6 +157,7 @@ where
 {
     /// Draws from `dataflow_command_receiver` until shutdown.
     fn run(&mut self) {
+        mz_ore::panic::set_abort_on_panic();
         let mut shutdown = false;
         while !shutdown {
             // Enable trace compaction.
 ```

Monitoring the `foo.bar` logs in `k9s`, you'll see:

```
┌───────────────────────────────────────────────────────────────────────────────────────────────────────── Logs(default/compute-cluster-2-replica-2-0:default)[1m] ──────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                      Autoscroll:On     FullScreen:Off     Timestamps:Off     Wrap:Off                                                                                                      │
│ computed: 2022-05-19T18:28:03.276397Z  INFO computed: about to bind to "0.0.0.0:2100"                                                                                                                                                                                      │
│ computed: 2022-05-19T18:28:03.276496Z  INFO computed: listening for coordinator connection on 0.0.0.0:2100...                                                                                                                                                              │
│ computed: 2022-05-19T18:28:03.276509Z  INFO computed: serving computed HTTP server on 0.0.0.0:6875                                                                                                                                                                         │
│ computed: 2022-05-19T18:28:03.276791Z  INFO mz_storage::boundary::tcp_boundary::client: About to connect to "storage-runtime-0.storage-runtime.default.svc.cluster.local:2101"                                                                                             │
│ computed: 2022-05-19T18:28:03.278251Z  INFO mz_storage::boundary::tcp_boundary::client: Connected to storage server                                                                                                                                                        │
│ computed: 2022-05-19T18:28:32.859906Z  INFO computed: coordinator connection accepted                                                                                                                                                                                      │
│ thread 'timely:work-0' panicked at 'panic!', src/expr/src/scalar/func/impls/string.rs:717:9                                                                                                                                                                                │
│ note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                                                                                                                                                                              │
│ Stream closed EOF for default/compute-cluster-2-replica-2-0 (default)
```

and the status of the pod in K8s will begin showing restarts/CrashLoopBackoff
```
│ NAMESPACE NAME                            ... RESTARTS    ...
│ default   compute-cluster-1-replica-1-0   ... 0           ...
│ default   compute-cluster-2-replica-2-0   ... 2           ...
```

However, this approach wedges K8s in some way because you can no longer observe the pods' logs.

### PR DESCRIPTION
**Pull request by benesch**
Remove all of the custom panic handling code from materialized. It never
worked quite right anyway. In particular, the code to print backtraces
on SIGSEGV often both failed to print a backtrace *and* inhibited using GDB to
get a backtrace.

Instead, this commit changes our three core services to call
`ore::panic::set_abort_on_panic` and nothing more. This ensures that a
crash in any thread will bring down the entire process, which is a much
better default than limping along with a panicked thread, which is what
Rust does by default.

What we lose is the nice message asking for a bug report, but that's
not nearly as important in a cloud native world--plus that message
tended to get lost in the spew of log messages when computed, storaged,
and materialized all simultaneously crash.

Fix #12583.

### Motivation

  * This PR fixes a recognized bug.

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - n/a

### CODE REVIEW

**Comment by benesch** [comment]
FYI @philip-stoev! I suspect this makes your life better, not worse, but I wanted to double check.

**Review by antiguru — APPROVED** [review]
Thanks!

File: src/materialized/src/bin/materialized/main.rs [hunk 1]
```diff
@@ -23,24 +23,20 @@ use std::ffi::CStr;
...
 use std::process;
 use std::sync::atomic::{AtomicUsize, Ordering};
-use std::sync::{Arc, Mutex};
+use std::sync::Arc;
 use std::thread;
 use std::time::Duration;
 
-use anyhow::{bail, Context};
-use backtrace::Backtrace;
+use anyhow::{bail, Context}F;
```
Comment (antiguru) [inline src/materialized/src/bin/materialized/main.rs:33]: Stray `F`.

**Comment by petrosagg** [comment]
Just to make sure I understand the source code of `set_abort_on_panic`, the first stacktrace still gets printed, right?

**Review by sploiselle — APPROVED** [review]
Nice--tysm.

**Review by philip-stoev — APPROVED** [review]
>  limping along with a panicked thread, which is what Rust does by default.

wut?

Anyway, so the stack trace will now come from `RUST_BACKTRACE=1`, right? If so, we should set this to be the default across the board, all types of builds, all binaries.

**Comment by benesch** [comment]
> Anyway, so the stack trace will now come from RUST_BACKTRACE=1, right? If so, we should set this to be the default across the board, all types of builds, all binaries.

Yessir! I'll do that in a follow up commit.
