### PR TITLE
adapter: Fix timedomain errors

### LINKED ISSUE #16469: panic: thread 'coordinator' panicked at 'Dataflow temp-view-t251 requested `as_of`
### What version of Materialize are you using?

v0.33.3 (2982e6bca)

### How did you install Materialize?

Materialize Cloud

### What is the issue?

Environmentd panics and crashes if you try to select from two different schemas in the same transactions, repro steps:

```sql
materialize=> create table t1 (f1 int);
CREATE TABLE
materialize=> insert into t1 values (1);
INSERT 0 1

materialize=> begin;
BEGIN
materialize=*> select * from t1;
 f1 
----
  1
(1 row)

materialize=*> select * from mz_views;
SSL SYSCALL error: EOF detected
The connection to the server was lost. Attempting reset: Failed.
The connection to the server was lost. Attempting reset: Failed.
!?> 
```

Related log from HC below:

### Relevant log output

```source
thread 'coordinator' panicked at 'Dataflow temp-view-t251 requested as_of (Antichain { elements: [1670242331152] }) not >= since (Antichain { elements: [1670242334000] })', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/dataflows.rs:161:13

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord.rs:1170:17
  45: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/handle.rs:264:9
  44: tokio::runtime::handle::Handle::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/context.rs:255:13
  43: tokio::runtime::context::BlockingRegionGuard::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/park.rs:272:31
  42: tokio::runtime::park::CachedParkThread::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:68:5
  41: tokio::runtime::coop::budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:102:5
  40: tokio::runtime::coop::with_budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/park.rs:272:63
  39: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  38: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord.rs:1002:37
  37: mz_adapter::coord::Coordinator<S>::serve::{{closure}}
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  36: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/message_handler.rs:40:63
  35: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_message::{{closure}}
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  34: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/message_handler.rs:146:5
  33: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_command::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  32: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  31: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/message_handler.rs:149:33
  30: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_command::{{closure}}::{{closure}}
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  29: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/command_handler.rs:64:21
  28: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_command::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  27: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/command_handler.rs:231:5
  25: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  24: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/command_handler.rs:258:61
  22: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute::{{closure}}::{{closure}}
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/command_handler.rs:261:5
  20: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute_inner::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  19: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/command_handler.rs:457:78
  17: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute_inner::{{closure}}::{{closure}}
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/sequencer.rs:94:5
  15: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_plan::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  14: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/sequencer.rs:274:63
  12: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_plan::{{closure}}::{{closure}}
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/sequencer.rs:2089:5
  10: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_peek::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
   9: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/sequencer.rs:2148:29
   7: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_peek::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/sequencer.rs:2360:25
   6: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::plan_peek
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/peek.rs:264:25
   5: mz_adapter::coord::peek::<impl mz_adapter::coord::Coordinator<S>>::create_peek_plan
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:1023:21
   4: core::option::Option<T>::map_or_else
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/peek.rs:267:32
   3: mz_adapter::coord::peek::<impl mz_adapter::coord::Coordinator<S>>::create_peek_plan::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/dataflows.rs:161:13
   2: mz_adapter::coord::dataflows::<impl mz_adapter::coord::Coordinator<S>>::finalize_dataflow
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   1: core::panicking::panic_fmt
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   0: rust_begin_unwind
```

### PR DESCRIPTION
**Pull request by jkosh44**
The adapter recently re-ordered logic in sequence_peek so that creating the dataflow happens before the timedomain validation checks. However, creating a dataflow may panic if the dataflow is in a different timedomain than previous peeks in the same transaction.

This commit re-orders the timedomain validation to happen before creating the dataflow to avoid panics.

Fixes #16469

### Motivation
This PR fixes a recognized bug.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

File: src/adapter/src/coord/sequencer.rs [hunk 1]
```diff
@@ -2315,6 +2269,51 @@ impl<S: Append + 'static> Coordinator<S> {
                 .timestamp
         };
 
+        if in_immediate_multi_stmt_txn {
+            if let Some(txn_reads) = self.txn_reads.get(&session.conn_id()) {
+                // Verify that the references and indexes for this query are in the
+                // current read transaction.
+                let allowed_id_bundle = txn_reads.read_holds.id_bundle();
+                if !allowed_id_bundle.is_empty() || !txn_reads.timestamp_independent {
```
Comment (jkosh44) [inline src/adapter/src/coord/sequencer.rs:2277]: See https://github.com/MaterializeInc/materialize/pull/16470#discussion_r1039728321

Comment (mjibson) [reply src/adapter/src/coord/sequencer.rs:2277]: If the id bundle is empty shouldn't this produce an error, because the ids from the current query haven't had their compaction held back and will panic when queried at the txn's timestamp?

Comment (jkosh44) [reply src/adapter/src/coord/sequencer.rs:2277]: This is starting to get convoluted/complicated and I think we should maybe think about simplifying peeks. However, the idea here is that IF the bundle is empty and the reads were timestamp independent, THEN the timestamp will be re-determined and a new read hold will be taken. This happens when the previous query is something constant like `SELECT 1`.

Comment (jkosh44) [reply src/adapter/src/coord/sequencer.rs:2277]: When the query is `SELECT 1` we end up taking an empty read hold and then throwing it away later. We probably shouldn't be doing this in the first place.

Comment (mjibson) [reply src/adapter/src/coord/sequencer.rs:2277]: Ah right. I forgot about the timestamp independent stuff. Agree this is getting quite complicated.

**Review by mjibson — APPROVED** [review]
