### PR TITLE
adapter: cleanup orphaned secrets at bootstrap

### LINKED ISSUE #13579: adapter: don't forget to garbage collect secrets
The [design of the `SecretsController`](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20220303_secrets.md#transaction-integration) can result in secrets that fail to clean up if a crash occurs at the wrong time:

> The above integration is designed so that failures result in orphaned secrets in the secrets controller; i.e., secrets that exist in the secrets controller but have no corresponding entry in the catalog. (The inverse would not be permissible: a secret that exists in the catalog must be known to the secrets controller.) The coordinator will periodically attempt to garbage collect orphaned secrets, either at startup or in a background task.

We need to add this loop to clean up any such orphaned secrets.

### PR DESCRIPTION
**Pull request by mjibson**
Add a list method to the secrets controller to determine orphaned secrets.

Fixes #13579

### Motivation

  * This PR adds a known-desirable feature.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

### CODE REVIEW

**Comment by benesch** [comment]
In theory: cloudtest! You might need to write the first such secrets using cloudtest, but should be similar to the cloudtests that do exist!

File: src/environmentd/tests/util.rs [hunk 1]
```diff
@@ -275,8 +286,12 @@ pub fn start_server(config: Config) -> Result<Server, anyhow::Error> {
     let persist_clients = PersistClientCache::new(persist_cfg, &metrics_registry);
     let persist_clients = Arc::new(Mutex::new(persist_clients));
     let postgres_factory = StashFactory::new(&metrics_registry);
-    let secrets_controller = Arc::clone(&orchestrator);
-    let connection_context = ConnectionContext::for_tests(orchestrator.reader());
+    let secrets_controller = config.secrets_controller.unwrap_or_else(|| {
+        let sc = Arc::clone(&orchestrator);
+        let sc: Arc<dyn SecretsController> = sc;
+        sc
+    });
```
Comment (benesch) [inline src/environmentd/tests/util.rs:293]: This seems a little funny. What about this?

```diff
diff --git a/src/environmentd/tests/util.rs b/src/environmentd/tests/util.rs
index 90b92d8165..8d00715931 100644
--- a/src/environmentd/tests/util.rs
+++ b/src/environmentd/tests/util.rs
@@ -82,7 +82,6 @@ use std::time::Duration;
 use std::{env, thread};
 
 use anyhow::anyhow;
-use mz_orchestrator::Orchestrator;
 use once_cell::sync::Lazy;
 use postgres::error::DbError;
 use postgres::tls::{MakeTlsConnect, TlsConnect};
@@ -286,11 +285,9 @@ pub fn start_server(config: Config) -> Result<Server, anyhow::Error> {
     let persist_clients = PersistClientCache::new(persist_cfg, &metrics_registry);
     let persist_clients = Arc::new(Mutex::new(persist_clients));
     let postgres_factory = StashFactory::new(&metrics_registry);
-    let secrets_controller = config.secrets_controller.unwrap_or_else(|| {
-        let sc = Arc::clone(&orchestrator);
-        let sc: Arc<dyn SecretsController> = sc;
-        sc
-    });
+    let secrets_controller = config
+        .secrets_controller
+        .unwrap_or_else(|| Arc::<ProcessOrchestrator>::clone(&orchestrator));
     let connection_context = ConnectionContext::for_tests(secrets_controller.reader());
     let inner = runtime.block_on(mz_environmentd::serve(mz_environmentd::Config {
         adapter_stash_url,
@@ -349,10 +346,6 @@ pub fn start_server(config: Config) -> Result<Server, anyhow::Error> {
     Ok(server)
 }
 
-trait OrchestratorSecretsController: Orchestrator + SecretsController {}
-
-impl<T: Orchestrator + SecretsController> OrchestratorSecretsController for T {}
-
 pub struct Server {
     pub inner: mz_environmentd::Server,
     pub runtime: Arc<Runtime>,

```

**Review by benesch — COMMENTED** [review]
Code LGTM modulo nit, but a cloudtest would be great! You could use a failpoint to introduce a crash after creating a secret in Kubernetes but before writing it to the catalog, and test that it is properly cleaned up on restart.

**Review by jkosh44 — APPROVED** [review]

File: src/environmentd/tests/util.rs (hunk 1 above)
Comment (mjibson) [reply src/environmentd/tests/util.rs:293]: cc @guswynn ^ this works too

**Comment by mjibson** [comment]
Whoa I have not heard of the failpoints machinery before, this is so great. Thanks.

**Comment by mjibson** [comment]
Failpoints greatly simplified this.

File: test/cloudtest/test_secrets.py [hunk 2]
```diff
@@ -56,3 +58,29 @@ def test_secrets(mz: MaterializeApplication) -> None:
...
+    secret = f"user-managed-{id}"
+
+    # The failpoint should cause this to fail.
+    try:
+        mz.environmentd.sql("DROP SECRET orphan")
+        raise Exception("Unexpected success")
+    except InterfaceError:
+        pass
+
+    describe = mz.kubectl("describe", "secret", secret)
```
Comment (benesch) [inline test/cloudtest/test_secrets.py:82]: Is this racy? Isn't `environmentd` restarting in the background and possibly deleting this secret at any point?

**Review by benesch — COMMENTED** [review]
So clean!

File: test/cloudtest/test_secrets.py (hunk 2 above)
Comment (mjibson) [reply test/cloudtest/test_secrets.py:82]: Yes! Is there a way to disable the restart attempt?

Comment (mjibson) [reply test/cloudtest/test_secrets.py:82]: Nevermind: added another failpoint to prevent orphan cleanup before we want it.

**Comment by benesch** [comment]
Nice! LGTM if you can figure out the cloudtest failure.

**Comment by mjibson** [comment]
It's a real bug! SSH manages secrets differently than other stuff, and it's getting deleted on bootstrap. Kinda scary.

**Comment by mjibson** [comment]
Problem was it was filtering by user secrets, not all secrets. Added a all secrets function that should fix.

File: src/adapter/src/coord.rs [hunk 3]
```diff
@@ -1056,6 +1057,23 @@ impl Coordinator {
         // state with what it has learned from the adapter.
         self.controller.storage.reconcile_state().await;
 
+        // Cleanup orphaned secrets. Errors during list() or delete() do not
+        // need to prevent bootstrap from succeeding; we will retry next
+        // startup.
+        if let Ok(controller_secrets) = self.secrets_controller.list().await {
+            let user_secrets: BTreeSet<GlobalId> =
+                self.catalog.secrets().map(|entry| entry.id()).collect();
```
Comment (benesch) [inline src/adapter/src/coord.rs:1065]: So this is weird, but secrets can be either:

1. Associated with a secret object in the catalog.
2. Associated with a connection object (specifically an SSH tunnel connection, but maybe other connection types in the future).

So I think you want to get IDs of secrets _and_ connections here, and that'll fix the SSH test.

Comment (mjibson) [reply src/adapter/src/coord.rs:1065]: Indeed. Removing `id.is_user()` from the filter didn't help. Maybe `.is_secret()` should be taught about connections? This API is real easy to misuse.

Comment (benesch) [reply src/adapter/src/coord.rs:1065]: No, `is_secret` should unambiguously refer to whether the entry is a secret in the catalog. The conflation occurs at a lower layer (the secrets controller layer), in which a secrets controller secret is associated with a catalog connection.

Comment (mjibson) [reply src/adapter/src/coord.rs]: Made a `fn secrets_and_connections` that passes tests. Should be ok now.

Comment (mjibson) [reply src/adapter/src/coord.rs]: Ah much better. Done.

**Review by benesch — APPROVED** [review]
Beautiful!
