### PR TITLE
txn-wal: fix persist schema hygiene

### LINKED ISSUE #28146: persist: Re-enable assert that checks we only push empty Rows into `SourceDataRowColumnarEncoder::EmptyRow`
### What version of Materialize are you using?

v0.108.0-dev

### What is the issue?

Currently for the new columnar encoder implemented with `Schema2` we disable the check that the row we're pushing into `SourceDataRowColumnarEncoder::EmptyRow` is empty. This is because there is a known race with `txn-wal` having the correct schema.

### PR DESCRIPTION
**Pull request by danhhz**
This closes the "cursed txn-wal TODO" \o/!

Before, we would sometimes fall back to a default "placeholder" schema
in txn-wal (in prod, an empty RelationDesc), but this causes issues with
the soon-to-be-rolled out persist columnar work (see #28146).

Now, we make sure to keep track of data shard write handles that are
handed directly to `register` and use only those for `commit` calls.
This ensures that only a real schema is used to encode batches.

For additional sanity, when applying a batch, use the matching schema by
fetching it from persist if necessary. This fixes issues with background
compaction work spawned as a result of the CaA call.

Closes #28146

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

File: src/txn-wal/src/txn_write.rs [hunk 1]
```diff
@@ -285,7 +296,10 @@ where
                                     .commit_bytes
                                     .inc_by(u64::cast_from(batch.encoded_size_bytes()));
                             }
-                            handle.datas.put_write(data_write);
+                            let prev = handle
+                                .data_write_commit
+                                .insert(data_write.0.shard_id(), data_write);
+                            assert!(prev.is_none());
```
Comment (ParkMyCar) [inline src/txn-wal/src/txn_write.rs:302]: note: I added an `assert_none!` macro recently to `ore` which debug prints the `Some(...)` value

File: src/txn-wal/src/txns.rs [hunk 2]
```diff
@@ -415,11 +420,9 @@ where
                 }
             }
 
-            // Note: Ordering here matters, we want to generate the Tidy work _before_ removing the
-            // handle because the work will create a handle to the shard.
```
Comment (ParkMyCar) [inline src/txn-wal/src/txns.rs:419]: Is this no longer true? I remember generating the tidy work after removing the handle would prevent finalizing shards because `txn-wal` would end up holding a write handle indefinitely

File: src/txn-wal/src/txns.rs [hunk 3]
```diff
@@ -109,11 +110,13 @@ where
...
     C: TxnsCodec,
 {
+    pub(crate) dyncfgs: ConfigSet,
     pub(crate) metrics: Arc<Metrics>,
     pub(crate) txns_cache: TxnsCache<T, C>,
     pub(crate) txns_write: WriteHandle<C::Key, C::Val, T, i64>,
     pub(crate) txns_since: SinceHandle<C::Key, C::Val, T, i64, O>,
-    pub(crate) datas: DataHandles<K, V, T, D>,
+    pub(crate) data_write_apply: DataHandles<K, V, T, D>,
+    pub(crate) data_write_commit: BTreeMap<ShardId, DataWriteCommit<K, V, T, D>>,
```
Comment (ParkMyCar) [inline src/txn-wal/src/txns.rs:119]: Do you mind adding a comment explaining the difference between these two? Mainly when would a handle existing in `data_write_apply` and not `data_write_commit`, or vice versa? Could a shard ever have a write handle in both?

**Review by ParkMyCar — COMMENTED** [review]
Love it! Just a question around `data_write_apply` vs `data_write_commit`

**Comment by danhhz** [comment]
Okay cool, sounds like the framing I tried here is a bit confusing. Will think again on how to make it more obvious!

**Comment by danhhz** [comment]
Unfortunately, it seems like this is [still getting the same panic](https://buildkite.com/materialize/nightly/builds/8873#01910433-39fd-439f-8f48-3612d1a03352)

Looking at the timestamps, it seems to have happened in alter-sink.td. The stacktrace is coming out of a task and so unfortunately loses the relevant info on where the batch write is coming from (e.g. is it compaction?). I'll keep poking at it, but I don't yet have a non-CI repro, so it might take a while

**Comment by danhhz** [comment]
Okay, I finally managed to get a repro on a bin/scratch machine. It was indeed this command that Parker provided (which I've cut down a tiny bit), but I had to skill up enough again on mzcompose to get it running 🙈.

> ./bin/mzcompose --find testdrive down -v; ./bin/mzcompose --find testdrive --dev run default --redpanda --system-param=persist_part_decode_format=row_with_validate --system-param=persist_batch_columnar_format=both_v2 kafka-avro-debezium-sinks.td kafka-avro-sinks-defaults.td kafka-avro-sinks-doc-comments.td

File: src/txn-wal/src/txn_write.rs (hunk 1 above)
Comment (danhhz) [reply src/txn-wal/src/txn_write.rs:302]: Done!

File: src/txn-wal/src/txns.rs (hunk 3 above)
Comment (danhhz) [reply src/txn-wal/src/txns.rs:119]: Done!

File: src/txn-wal/src/lib.rs [hunk 4]
```diff
@@ -467,6 +478,43 @@ async fn apply_caa<K, V, T, D>(
...
+                        )
+                        .await
+                        .expect("codecs shouldn't change");
+                    tracing::info!(
+                        "updated {} write handle from {} to {} to apply batches",
+                        data_id,
+                        handle_schema,
+                        batch_schema
+                    );
+                    *data_write = new_data_write
```
[the remark this answers is not in the document]
Comment (danhhz) [reply src/txn-wal/src/lib.rs:512]: > Is the expectation here that `new_data_write.schema_id() == Some(batch_schema)`?

Yup! Added an assert

> I didn't closely follow the schema registry work, but is there any concern here that a new schema was registered after creating the batches?

Nope, the get schema call returns the exact schema used to encode this particular batch (slash set of batches).

**Review by danhhz — COMMENTED** [review]
@jkosh44 This should be ready for another look!

I figured out the issue I posted above, it turned out to be that we thought the persist schema registry was turned on in CI but it wasn't. Also the kafka testdrive failures that Parker was original getting was a different bug (of exactly the same shape) in shard finalization. However, the 0dt CI failure we got yesterday on the release candidate _was_ this, so we can use that as a measure for this working

File: src/txn-wal/src/txns.rs [hunk 5]
```diff
@@ -684,8 +692,21 @@ impl Tidy {
...
+    /// See [DataWriteAppend].
+    ///
+    /// This is lazily populated with the set of shards touched by `apply_le`.
+    data_write_for_apply: BTreeMap<ShardId, DataWriteApply<K, V, T, D>>,
+    /// See [DataWriteCommit].
+    ///
+    /// This contains the set of data shards registered but not yet forgotten
+    /// with this particular write handle.
+    ///
+    /// NB: In the common case, this and `_for_commit` will contain the same set
```
Comment (jkosh44) [inline src/txn-wal/src/txns.rs:706]:
```suggestion
    /// NB: In the common case, this and `_for_apply` will contain the same set
```

File: src/txn-wal/src/txns.rs [hunk 6]
```diff
@@ -697,27 +718,190 @@ where
...
+            .insert(data_write.shard_id(), data_write);
+        assert!(prev.is_none());
+    }
+}
+
+/// A newtype wrapper around [WriteHandle] indicating that it has a real schema
+/// registered by the user.
+///
+/// The txn-wal user declares which schema they'd like to use for committing
+/// batches by passing it in (as part of the WriteHandle] in the call to
```
Comment (jkosh44) [inline src/txn-wal/src/txns.rs:781]:
```suggestion
/// batches by passing it in (as part of the WriteHandle) in the call to
```

**Review by jkosh44 — APPROVED** [review]
LGTM

File: src/txn-wal/src/txns.rs (hunk 6 above)
Comment (danhhz) [reply src/txn-wal/src/txns.rs]: Done!

File: src/txn-wal/src/txns.rs (hunk 5 above)
Comment (danhhz) [reply src/txn-wal/src/txns.rs]: Whoops

**Review by danhhz — COMMENTED** [review]
TFTR! Gonna run a nightlies before merging
