### PR TITLE
dataflow,sinks: continuously write out END records when updating write frontier

### LINKED ISSUE #7344: Continuous timestamp compaction breaks exactly-once Kafka sinks
Turns out https://github.com/MaterializeInc/materialize/pull/7232 has broken exactly-once output when using realtime timestamping with binding compaction.

It goes roughly like this:

1. current timestamp is `1`
2. sink writes data and an `END(1)` record. The `END(1)` records are used to gate writes when restarting the sink
3. the write frontier is continuously updated, say to `5`
4. timestamp binding compaction will compact timestamp bindings up to `5` (roughly)
5. **shutdown and restart**
6. the sink emits the previously read data, but now at timestamp `5`
7. sink writes that data again because it's beyond the gate timestamp of `1`

I see two solutions:

1. Disable continuous timestamp compaction, basically reverting #7232 
2. Write "dummy" `END()` records continuously, to update the gate timestamp in line with compaction

### PR DESCRIPTION
**Pull request by aljoscha**
When restarting, the Kafka sink determines the gate timestamp (the
timestamp used to filter out previously written records) based on the
END records in the consistency topic.

We therefore need to ensure that the latest timestamp in those records
advances in lockstep with the write frontier, which is used to compact
timestamp bindings.

All commits have proper descriptions.

- 9a2e22a is the main change
- 85abb62 changes the exactly-once test to catch the problem and simplifies the test
- fff9c48 changes the timestamp compaction logic, please carefully look a the rationale, I'm quite possibly wrong there.

This fixes #7344.

### CODE REVIEW

**Comment by aljoscha** [comment]
Side note: I could, as an additional change, rename `s.` to `sink_state` as well. :sweat_smile:

**Comment by aljoscha** [comment]
I didn't introduce any knobs for controlling when/how we write out `END` records. This can already be controlled via the timestamping frequency (for RT sources), and I didn't want to introduce any additional settings.

**Comment by ruchirK** [comment]
Will review this later tonight or tomorrow sorry for the delay!

**Comment by ruchirK** [comment]
reviewing now!

File: src/dataflow/src/sink/kafka.rs [hunk 1]
```diff
@@ -307,90 +511,34 @@ pub fn produce_to_kafka<G>(
...
-        KafkaSink {
-            name,
-            shutdown_flag: shutdown_flag.clone(),
-            metrics,
-            producer,
-            activator,
-            txn_timeout: Duration::from_secs(5),
-        }
-    };
+    // Keep track of whether this operator/worker ever received updates. We
```
Comment (ruchirK) [inline src/dataflow/src/sink/kafka.rs:531]: this really feels like we want to pass a boolean that says `active_worker` or something like that at sink render time to indicate which operator should be the writer instead of making it implicit with the hashing

File: test/kafka-exactly-once/mzcompose.yml [hunk 2]
```diff
@@ -76,7 +76,7 @@ services:
       --data-directory=/share/mzdata
       -w1
       --disable-telemetry
-      --logical-compaction-window=off
+      --logical-compaction-window=1ms
```
Comment (ruchirK) [inline test/kafka-exactly-once/mzcompose.yml:79]: nit: i don't think you need to specify this because its the default

File: src/dataflow/src/sink/kafka.rs [hunk 3]
```diff
@@ -198,6 +214,8 @@ impl KafkaSinkState {
             pending_rows: HashMap::new(),
             ready_rows: VecDeque::new(),
             send_state: SendState::Init,
+            latest_progress_ts: Timestamp::MIN,
```
Comment (ruchirK) [inline src/dataflow/src/sink/kafka.rs:217]: should this be set to the gate timestamp if that exists on restart?

File: src/dataflow/src/sink/kafka.rs [hunk 4]
```diff
@@ -416,10 +525,20 @@ where
...
+    // Keep track of whether this operator/worker ever received updates. We
+    // use this to control who should send continuous END progress records
+    // to Kafka below.
+    let mut received_data = false;
+
     let mut vector = Vec::new();
 
+    // keep the latest progress updates, if any, in order to update
+    // our internal state after the send loop
+    let mut progress_updates = Vec::new();
```
Comment (ruchirK) [inline src/dataflow/src/sink/kafka.rs:540]: I feel like this can be an `Option<Timestamp>` or something. ideally you would just call `maybe_update_progress` in the main loop but it seems like borrow checker doesn't like that

**Review by ruchirK — APPROVED** [review]
I think this all makes sense!

My only question is: is emitting END records after every frontier update acceptable from a perf pov?

File: src/dataflow/src/sink/kafka.rs (hunk 4 above)
Comment (aljoscha) [reply src/dataflow/src/sink/kafka.rs:540]: Yes, this is for getting around borrow checking! :sweat_smile: 
I had an `Option` here first, but I think we can emit multiple `END` records in one invocation. And a `Vec` should be fine since we're reusing the allocation. Could still change it, of course.

File: src/dataflow/src/sink/kafka.rs (hunk 3 above)
Comment (aljoscha) [reply src/dataflow/src/sink/kafka.rs:217]: :+1:

File: src/dataflow/src/sink/kafka.rs (hunk 1 above)
Comment (aljoscha) [reply src/dataflow/src/sink/kafka.rs:531]: I did it like this because it's less fragile than relying on knowing how timely hashes and exchanges data to workers. But I'm happy to change it since we already have that dependency for the write frontier stuff.

**Comment by aljoscha** [comment]
> My only question is: is emitting END records after every frontier update acceptable from a perf pov?

I wrote this one before:
> I didn't introduce any knobs for controlling when/how we write out END records. This can already be controlled via the timestamping frequency (for RT sources), and I didn't want to introduce any additional settings.

I'm also not sure about it, though. With BYO timestamping, you get one `END` record in the output per `END` record in the input. With RT timestamping you get an `END` record per minted binding, which is controllable by the user. (and defaults to one per second)

File: test/kafka-exactly-once/mzcompose.yml (hunk 2 above)
Comment (aljoscha) [reply test/kafka-exactly-once/mzcompose.yml:79]: I wanted to make it explicit, in case the default ever changes. But I'm happy to remove.

File: src/dataflow/src/sink/kafka.rs (hunk 4 above)
Comment (ruchirK) [reply src/dataflow/src/sink/kafka.rs:550]: yeah but you only ever update the internal field to the max anyway right? I guess maybe another question to ask: is it ever legit for `maybe_update_progress` to not update the last_progress_ts? as far as I can understand that would only happen if we emit times out of order which we don't want to do?

File: src/dataflow/src/sink/kafka.rs (hunk 1 above)
Comment (ruchirK) [reply src/dataflow/src/sink/kafka.rs:541]: > > My only question is: is emitting END records after every frontier update acceptable from a perf pov?
> 
> I wrote this one before:
> 
> > I didn't introduce any knobs for controlling when/how we write out END records. This can already be controlled via the timestamping frequency (for RT sources), and I didn't want to introduce any additional settings.
> 
> I'm also not sure about it, though. With BYO timestamping, you get one `END` record in the output per `END` record in the input. With RT timestamping you get an `END` record per minted binding, which is controllable by the user. (and defaults to one per second)

Oh right sorry! yeah I think that reasoning makes sense

File: src/dataflow/src/sink/kafka.rs (hunk 4 above)
Comment (aljoscha) [reply src/dataflow/src/sink/kafka.rs:550]: I had a future in mind where we do allow emitting timestamps out of order. But I can turn it into an `Option` for now. 👌
