### PR TITLE
sql: error instead of panic when failing to lower casts

### LINKED ISSUE #26100: sentry: panic: lower_uncorrelated should not fail given that there is no correlation in the input col_expr: Unst...
Sentry Issue: [DATABASE-BACKEND-3BG](https://materializeinc.sentry.io/issues/5079526995/?referrer=github_integration)

```
panic: lower_uncorrelated should not fail given that there is no correlation in the input col_expr: Unstructured("unexpected ScalarExpr in uncorrelated plan: Select(Map { input: Constant { rows: [Row{[]}], typ: RelationType { column_types: [], keys: [] } }, scalars: [If { cond: CallUnary { func: IsNull(IsNull), expr: Column(ColumnRef { level: 1, column: 3 }) }, then: Literal(Row{[Null]}, ColumnType { scalar_type: RegType, nullable: true }), els: If { cond: CallVariadic { func: And, exprs: [Literal(Row{[True]}, ColumnType { scalar_type: Bool, nullable: false }), CallVariadic { func: And, exprs: [CallBinary { func: Gte, expr1: CallVariadic { func: Substr, exprs: [Column(ColumnRef { level: 1, column: 3 }), Literal(Row{[Int32(1)]}, ColumnType { scalar_type: Int32, nullable: false }), Literal(Row{[Int32(1)]}, ColumnType { scalar_type: Int32, nullable: false })] }, expr2: Literal(Row{[String(\"0\")]}, ColumnType { scalar_type: String, nullable: false }) }, CallBinary { func: Lte, expr1: CallVariadic { func: Substr, exprs: [Column(ColumnRef { level: 1, column: 3 }), Literal(Row{[Int32(1)]}, ColumnType { scalar_type: Int32, nullable: false }), Literal(Row{[Int32(1)]}, ColumnType { scalar_type: Int32, nullable: false })] }, expr2: Literal(Row{[String(\"9\")]}, ColumnType { scalar_type: String, nullable: false }) }] }] }, then: CallUnary { func: CastOidToRegType(CastOidToRegType), expr: CallUnary { func: CastStringToOid(CastStringToOid), expr: Column(ColumnRef { level: 1, column: 3 }) } }, els: Select(Project { input: Join { left: CallTable { func: TabletizedScalar { name: \"mz_error_if_null\", relation: RelationType { column_types: [ColumnType { scalar_type: String, nullable: false }], keys: [] } }, exprs: [CallVariadic { func: ErrorIfNull, exprs: [Select(Distinct { input: Project { input: Project { input: Filter { input: Join { left: Join { left: Map { input: Constant { rows: [Row{[]}], typ: RelationType { column_types: [], keys: [] } }, scalars: [Select(Project { input: Map { input: Constant { rows: [Row{[]}], typ: RelationType { column_types: [], keys: [] } }, scalars: [CallBinary { func: ParseIdent, expr1: Column(ColumnRef { level: 4, column: 3 }), expr2: Literal(Row{[True]}, ColumnType { scalar_type: Bool, nullable: false }) }, If { cond: CallUnary { func: IsNull(IsNull), expr: Column(ColumnRef { level: 4, column: 3 }) }, then: Literal(Row{[Null]}, ColumnType { scalar_type: Array(String), nullable: true }), els: If { cond: CallBinary { func: Gt, expr1: CallBinary { func: ArrayLength, expr1: Column(ColumnRef { level: 0, column: 0 }), expr2: CallUnary { func: CastInt32ToInt64(CastInt32ToInt64), expr: Literal(Row{[Int32(1)]}, ColumnType { scalar_type: Int32, nullable: false }) } }, expr2: Literal(Row{[Int32(3)]}, ColumnType { scalar_type: Int32, nullable: false }) }, then: CallVariadic { func: ErrorIfNull, exprs: [Literal(Row{[Null]}, ColumnType { scalar_type: Array(String), nullable: true }), CallBinary { func: TextConcat, expr1: Literal(Row{[String(\"improper relation name (too many dotted names): \")]}, ColumnType { scalar_type: String, nullable: false }), expr2: Column(ColumnRef { level: 4, column: 3 }) }] }, els: CallBinary { func: ArrayArrayConcat, expr1: CallVariadic { func: ArrayFill { elem_type: String }, exprs: [Literal(Row{[Null]}, ColumnType { scalar_type: String, nullable: true }), CallVariadic { func: ArrayCreate { elem_type: Int32 }, exprs: [CallBinary { func: SubInt32, expr1: Literal(Row{[Int32(3)]}, ColumnType { scalar_type: Int32, nullable: false }), expr2: CallBinary { func: ArrayLength, expr1: Column(ColumnRef { level: 0, column: 0 }), expr2: CallUnary { func: CastInt32ToInt64(CastInt32ToInt64), expr: Literal(Row{[Int32(1)]}, ColumnType { scalar_type: Int32, nullable: false }) } } }] }] }, expr2: Column(ColumnRef { level: 0, column: 0 }) } } }] }, outputs: [1] })] }, right: Project { input: Map { input: Distinct { input: Project { input: Map { input: Filter { input: Join { left: Join { left: Join { left: Reduce { input: Map { input: Filter { input: Join { left: Get { id: Global(System(487)), typ: RelationType { column_types: [ColumnType { scalar_type: String, nullable: false }, ColumnType { scalar_type: Oid, nullable: false }, ColumnType { scalar_type: String, nullable: false }, ColumnType { scalar_type: String, nullable: false }, ColumnType { scalar_type: String, nullable: false }, ColumnType { scalar_type: String, nullable: false }, ColumnType { scalar_type: Array(MzAclItem), nullable: true }], keys: [] } }, right: Get { id: Global(System(486)), typ: RelationType { column_types: [ColumnType { scalar_type: String, nullable: false }, ColumnType { scalar_type: String, nullable: false }], keys: [[0]] } }, on: CallBinary { func: Eq, expr1: Column(ColumnRef { level: 0, column: 4 }), expr2: Column(ColumnRef { level: 0, column: 7 }) }, kind: Inner }, predicates: [CallVariadic { func: And, exprs: [CallBinary { func: Eq, expr1: Column(ColumnRef { level: 0, column: 3 }), expr2: CallVariadic { func: ArrayIndex { offset: 0 }, exprs: [Column(ColumnRef { level: 1, column: 0 }), CallUnary { func: CastInt32ToInt64(CastInt32ToInt64), expr: Literal(Row{[Int32(3)]}, ColumnType { scalar_type: Int32, nullable: false }) }] } }, CallBinary { func: Eq, expr1: Column(ColumnRef { level: 0, column: 8 }), expr2: Literal(Row{[String(\"regtype\")]}, ColumnType { scalar_type: String, nullable: false }) }] }] }, scalars: [Column(ColumnRef { level: 0, column: 0 }), Column(ColumnRef { level: 0, column: 2 }), Column(ColumnRef { level: 0, column: 3 })] }, group_key: [9, 10, 11], aggregates: [AggregateExpr { func: Count, expr: Literal(Row{[True]}, ColumnType { scalar_type: Bool, nullable: false }), distinct: false }], expected_group_size: None }, right: Get { id: Global(System(442)), typ: RelationType { column_types: [ColumnType { scalar_type: String, nullable: false }, ColumnType { scalar_type: Oid, nullable: false }, ColumnType { scalar_type: String, nullable: true }, ColumnType { scalar_type: String, nullable: false }, ColumnType { scalar_type: String, nullable: false }, ColumnType { scalar_type: Array(MzAclItem), nullable: false }], keys: [] } }, on: CallBinary { func: Eq, expr1: Column(ColumnRef { level: 0, column: 1 }), expr2: Column(ColumnRef { level: 0, column: 4 }) }, kind: Inner }, right: CallTable { func: UnnestArray { el_typ: String }, exprs: [If { cond: CallUnary { func: IsNull(IsNull), expr: CallVariadic { func: ArrayIndex { offset: 0 }, exprs: [Column(ColumnRef { level: 2, column: 0 }), CallUnary { func: CastInt32ToInt64(CastInt32ToInt64), expr: Literal(Row{[Int32(2)]}, ColumnType { scalar_type: Int32, nullable: false }) }] } }, then: If { cond: Literal(Row{[True]}, ColumnType { scalar_type: Bool, nullable: false }), then: CallUnmaterializable(CurrentSchemasWithSystem), els: CallUnmaterializable(CurrentSchemasWithoutSystem) }, els: CallVariadic { func: ArrayCreate { elem_type: String }, exprs: [CallVariadic { func: ArrayIndex { offset: 0 }, exprs: [Column(ColumnRef { level: 2, column: 0 }), CallUnary { func: CastInt32ToInt64(CastInt32ToInt64), expr: Literal(Row{[Int32(2)]}, ColumnType { scalar_type: Int32, nullable: false }) }] }] } }] }, on: CallBinary { func: Eq, expr1: Column(ColumnRef { level: 0, column: 10 }), expr2: Column(ColumnRef { level: 0, column: 7 }) }, kind: Inner }, right: Union { base: Project { input: Get { id: Global(System(441)), typ: RelationType { column_types: [ColumnType { scalar_type: String, nullable: false }, ColumnType { scalar_type: Oid, nullable: false }, ColumnType { scalar_type: String, nullable: false }, ColumnType { scalar_type: String, nullable: false }, ColumnType { scalar_type: Array(MzAclItem), nullable: false }], keys: [] } }, outputs: [0, 2] }, inputs: [Map { input: Filter { input: Constant { rows: [Row{[]}], typ: RelationType { column_types: [], keys: [] } }, predicates: [Select(Reduce { input: Project { input: Get { id: Global(System(441)), typ: RelationType { column_types: [ColumnType { scalar_type: String, nullable: false }, ColumnType { scalar_type: Oid, nullable: false }, ColumnType { scalar_type: String, nullable: false }, ColumnType { scalar_type: String, nullable: false }, ColumnType { scalar_type: Ar...
  File "panicking.rs", line 645, in rust_begin_unwind
  File "ddl.rs", line 955, in mz_sql::plan::statement::ddl::plan_create_source
  File "statement.rs", line 325, in mz_sql::plan::statement::plan
  File "sql.rs", line 40, in mz_adapter::coord::Coordinator::plan_statement
  File "message_handler.rs", line 494, in mz_adapter::coord::Coordinator::message_purified_statement_ready::{closure#0}::{closure#0}
...
(34 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by sploiselle**
Fixes #26100

### Motivation

 This PR fixes a recognized bug.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - Error when trying to set up a PostgreSQL source asking MZ to ingest `regtype`, `regclass`, or `regproc` data. MZ does not yet offer enough support for those types to let us ingest them and, additionally, user-specified objects' OIDs cannot be meaningfully used in Materialize.

### CODE REVIEW

File: src/sql/src/plan/statement/ddl.rs [hunk 1]
```diff
@@ -955,10 +955,32 @@ pub fn plan_create_source(
...
-                    let mir_cast = cast.lower_uncorrelated().expect(
-                        "lower_uncorrelated should not fail given that there is no correlation \
-                            in the input col_expr",
-                    );
+                    // We expect only reg* types to encounter this issue. Users
+                    // can ingest the data as text if they need to ingest it.
+                    // This is acceptable because we don't expect the OIDs from
+                    // an external PG source to be unilaterally usable in
+                    // resolving item names in MZ.
+                    let mir_cast = cast.lower_uncorrelated().map_err(|_e| {
```
Comment (benesch) [inline src/sql/src/plan/statement/ddl.rs:963]: Handling the error gracefully is a nice way of protecting ourselves from this in the future! 🙌🏽

**Review by benesch — APPROVED** [review]
Beaut, thank you!
