### PR TITLE
coord: improve timestamp determination to avoid no complete timestamps

### LINKED ISSUE #3122: Improving "No complete timestamp" message
Following discussion with Arjun:

Error: No complete timestamp is potentially misleading and may not reflect the fact that the system is making progress/this is an "expected" state for loading. 

A better solution would be to convey some progress metrics

### LINKED ISSUE #8163: At least one input has no complete timestamps yet
Hi, I am testing materialized with a very simple set of data, one table consisting of point of sale (POS) and another branch table. Both the table are in Postgres. I am trying to create a materialized view of POS joining with the branch but when I try to query the materialized table I always get - _**At least one input has no complete timestamps yet error.**_ What does this error mean? Please advice.

### PR DESCRIPTION
**Pull request by mjibson**
Previously we would require a valid upper to be available and error with
"no complete timestamps" if it was not available. Instead, change the
order in which we determine timestamps:

1. Initialize to the timestamp minimum.
2. Advance to the since.
3. Advance to the upper.

Each "advance" step can possibly do nothing if the current canditate
timestamp is already in advance of the argument.

As a result, we no longer produce the no complete timestamps error. The
previous case where it occurred, when the upper was 0, will leave the
candidate timestamp at the since. If the since is also 0, that is fine,
because we assume the source is correctly declaring 0 to be the first
time at which it will produce results.

Closes #8163
Fixes #3122

### Motivation

Which of the following best describes the motivation behind this PR?

  * This PR adds a known-desirable feature: #3122
  * I no longer wish to be mocked by this error message.

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - Remove the "no complete timestamps" error. Queries will now wait for initial data instead of erroring and requiring users to run their query in a loop until it succeeds.

### CODE REVIEW

**Comment by JLDLaughlin** [comment]
> I no longer wish to be mocked by this error message.
😂

File: src/coord/src/coord.rs [hunk 1]
```diff
@@ -3417,50 +3417,43 @@ impl Coordinator {
...
+                let mut candidate = Timestamp::minimum();
+                candidate.advance_by(since.borrow());
+
+                // Compute a timestamp to which we should advance the candidate (if it is in
+                // advance).
+                let advance_to: Timestamp =
+                    if uses_ids.iter().any(|id| self.catalog.uses_tables(*id)) {
+                        // If the view depends on any tables, we enforce
+                        // linearizability by choosing the latest input time.
+                        self.get_local_read_ts()
```
Comment (frankmcsherry) [inline src/coord/src/coord.rs:3430]: I'm not sure of the logic around here, but do we also need to make sure to advance the `read_ts` based on what we conclude here? Or is that logic elsewhere?

**Review by frankmcsherry — APPROVED** [review]
I like how this looks, subject to a question about enforcing linearizability of reads.

I do want to call out, not sure where to record for posterity, that 

> If the since is also 0, that is fine, because we assume the source is correctly declaring 0 to be the first time at which it will produce results.

... is maybe overly optimistic at the moment. It may be all fine, but STORAGE is not yet the source of truth on `since` values, and it means we are relying on the coordinator to put the right `since` value in place on e.g. source and index creation. That may be the case, but I'd double check it too (I will as the next thing I do, but it would be great to have you check to in order to get double coverage). 

In the future, `create_source` and `create_dataflow` will come back with the initial `since` values for the coordinator.

File: src/coord/src/coord.rs (hunk 1 above)
Comment (mjibson) [reply src/coord/src/coord.rs:3430]: We already weren't doing that. Previously we'd take `get_local_read_ts` and advance it to since, then not do anything if we did some advancing. I believe this PR comes up with the same timestamp just in a different order, but equally doesn't worry about telling table linearizability about it.

My take: table linearizability ensures that all table writes are seen by table reads, and that's it. It does not interact with other sources (which is the only way that we would bump the timestamp to be in advance of get_local_read_ts), and that can be done in our larger linearizability work.

Comment (frankmcsherry) [reply src/coord/src/coord.rs:3430]: Ah, lemme give more detail then and lmk what you think:

1. `my_source` has a since of `10` and contains `source_val1` at `10`.
2. `my_table` has a since of `5` and contains `table_val1` at `5` and `table_val2` at `7`.

When we go and pick a timestamp of the union, we advance to `10` to get a legit read from `my_source`. When we query just `my_table` we start at `5` and that works great. Maybe .. are you maybe saying "we will always go at least to `7` because of `upper`"? That checks out, but seems like maybe a new constraint (must always advance to max `upper` to maintain linearizability).

Comment (mjibson) [reply src/coord/src/coord.rs:3430]: `my_table` cannot have a since of 5 if it has a value at 7.

Comment (mjibson) [reply src/coord/src/coord.rs:3430]: If the since for `my_table` is 5, the query timestamp will be at least `7` because of the call to `get_local_read_ts`. I actually think the table stuff and upper stuff should be separated, and could both trigger.

Comment (mjibson) [reply src/coord/src/coord.rs:3430]: (I deleted an incorrect comment.)

Comment (mjibson) [reply src/coord/src/coord.rs:3446]: I have a new take! In the case that the candidate is already in advance of the table read time, the peek will be put into pending until something closes that table timestamp, and once that read is served table writes can't be done before it. So I think we're ok?

Comment (mjibson) [reply src/coord/src/coord.rs:3454]: I've added a comment describing this. PTAL.

**Comment by mjibson** [comment]
Hrm this frequently times out some tests so I wonder if it has some other side effect I'm not aware of. Haven't been able to repro locally yet though.
