### PR TITLE
Use timely fabric to forward ComputeCommands

### LINKED ISSUE #13603: Multi-process compute clusters can be out-of-sync on controller restarts
While re-working the command reconciliation logic for the coordinator-compute boundary, @frankmcsherry noticed that we have a potential problem of de-synchronizing cluster members. When the connection to a cluster fails while broadcasting a command, it could happen that some receive the command while others don't. Many bad things can follow: partially constructed dataflows, partial peeks and so on.

On restart, the controller does not know which subset of the processes received what instructions, which makes it impossible to provide a correct sequence of commands to bring them in a known-good state.

Related: [Discussion on Slack](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1657694466677869)

## Suggestions to solve this issue
1. On connection, each process advertises its received command history back to the coordinator, from which the coordinator can at least learn if everyone is in sync (and if not, restart the group).
2. The controller just speaks with one process, who broadcasts the commands to other workers using timely's Sequencer dataflow (a built-in broadcast, whose failure results in the mesh failing).
3. The controller uses a more reliable mechanism to deliver the commands, such as recording them in a DB or putting them in Kafka.
4. The command reconciliation logic asserts that `num_workers == 1` on restart. This causes the compute cluster to restart, which leaves it in a clean state, at the cost of dropping maintained resources.

### PR DESCRIPTION
**Pull request by lluki**
This PR implements option 2) of #13603 : Environmentd sends command only to the first process, which then uses timely internally to disseminate the command. Responses are still sent over the network from each process.

Fixes #13603

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - None

### CODE REVIEW

File: src/storage/src/protocol/client.rs [hunk 1]
```diff
@@ -376,10 +376,10 @@ impl<T> PartitionedState<StorageCommand<T>, StorageResponse<T>> for PartitionedS
 where
     T: timely::progress::Timestamp,
 {
-    fn split_command(&mut self, command: StorageCommand<T>) -> Vec<StorageCommand<T>> {
+    fn split_command(&mut self, command: StorageCommand<T>) -> Vec<Option<StorageCommand<T>>> {
         self.observe_command(&command);
 
-        vec![command; self.parts]
+        vec![command; self.parts].into_iter().map(Some).collect()
```
Comment (antiguru) [inline src/storage/src/protocol/client.rs:382]:
```suggestion
        vec![Some(command); self.parts]
```

File: src/compute/src/server.rs [hunk 2]
```diff
@@ -185,14 +243,149 @@ impl<'w, A: Allocate> Worker<'w, A> {
...
+            self.timely_worker.dataflow::<u64, _, _>(move |scope| {
+                let src = source(scope, "Command source", |mut cap, info| {
+                    let activator = scope.sync_activator_for(&info.address[..]);
+                    {
+                        *rx_activator.lock().unwrap() = Some(activator);
+                    }
+
+                    move |output| {
+                        //println!("w{:?} Calling non-blocking recv", &idx);
+                        if idx == 0 {
```
Comment (antiguru) [inline src/compute/src/server.rs:324]: This is a suspenseful moment, because
1. We don't drop `cap` if `idx != 0`
2. What happens to commands received by a different process than process 0? It seems we would enqueue them indefinitely with this change.

File: src/compute/src/server.rs [hunk 3]
```diff
@@ -185,14 +243,149 @@ impl<'w, A: Allocate> Worker<'w, A> {
...
+
+            self.timely_worker.dataflow::<u64, _, _>(move |scope| {
+                let src = source(scope, "Command source", |mut cap, info| {
+                    let activator = scope.sync_activator_for(&info.address[..]);
+                    {
+                        *rx_activator.lock().unwrap() = Some(activator);
+                    }
+
+                    move |output| {
+                        //println!("w{:?} Calling non-blocking recv", &idx);
```
Comment (antiguru) [inline src/compute/src/server.rs:323]: Stray

File: src/compute/src/server.rs [hunk 4]
```diff
@@ -185,14 +243,149 @@ impl<'w, A: Allocate> Worker<'w, A> {
...
+                        if idx == 0 {
+                            // We turn the TryRecvError into an Option type, as it doesnt
+                            // implemenet the right traits to fulfill Timelys ExchangeData
+                            //
+                            match command_rx.try_recv() {
+                                Ok(cmd) => {
+                                    // get some data and send it.
+                                    let time = cap.time().clone();
```
Comment (antiguru) [inline src/compute/src/server.rs:331]: This will assign a new timestamp to every command, which could be a bit overwhelming if there are many small commands received. I think a better approach is to collect all data available at the current time (i.e., collect the output from `try_recv` in a loop, and send all that data at the same timestamp.)

File: src/compute/src/server.rs [hunk 5]
```diff
@@ -185,14 +243,149 @@ impl<'w, A: Allocate> Worker<'w, A> {
...
+                let src = source(scope, "Command source", |mut cap, info| {
+                    let activator = scope.sync_activator_for(&info.address[..]);
+                    {
+                        *rx_activator.lock().unwrap() = Some(activator);
+                    }
+
+                    move |output| {
+                        //println!("w{:?} Calling non-blocking recv", &idx);
+                        if idx == 0 {
+                            // We turn the TryRecvError into an Option type, as it doesnt
```
Comment (antiguru) [inline src/compute/src/server.rs:325]: You could use the empty frontier as an indicator that the source hung up instead of multiplexing over `Option`.

File: src/compute/src/server.rs [hunk 6]
```diff
@@ -185,14 +243,149 @@ impl<'w, A: Allocate> Worker<'w, A> {
...
+                        .collect::<Vec<_>>()
+                })
+                .exchange(|(dest, _)| *dest as u64)
+                .inspect(move |(_, cmd)| {
+                    println!("w{:?}, cmd={:?}", idx, cmd);
+                    (*cmd_queue).borrow_mut().push_back(match &*cmd {
+                        Some(x) => Ok(x.clone()),
+                        None => Err(TryRecvError::Disconnected),
+                    });
+                });
```
Comment (antiguru) [inline src/compute/src/server.rs:371]: Here, I'd recommend to write this in terms of `unary_frontier` so that the operator can supply its own exchange function to avoid the `exchange` operator, and that it gets to take ownership of the data it receives. It could reconstruct the `TryRecvError::Disconnected` from an empty frontier.

File: src/storage/src/protocol/server.rs [hunk 7]
```diff
@@ -135,8 +136,15 @@ pub fn serve(
                 .send(channels)
                 .expect("worker should not drop first");
         }
-        let client =
-            LocalClient::new_partitioned(response_rxs, command_txs, worker_threads.clone());
+        let rx_activators: Vec<Arc<Mutex<Option<SyncActivator>>>> = (0..config.workers)
+            .map(|_| Arc::new(Mutex::new(None::<SyncActivator>)))
```
Comment (antiguru) [inline src/storage/src/protocol/server.rs:140]: Might not need the type annotations here?

File: src/compute/src/server.rs [hunk 8]
```diff
@@ -156,6 +174,43 @@ pub fn serve(
...
+        match b.pop_front() {
+            Some(Ok(cmd)) => Ok(cmd),
+            Some(Err(e)) => Err(e),
+            None => Err(TryRecvError::Empty),
+        }
+    }
+
+    fn recv<A: Allocate>(&mut self, worker: &mut Worker<A>) -> Result<ComputeCommand, RecvError> {
+        // This takes the worker, so it can step timely while no result
+        // is available.
```
Comment (antiguru) [inline src/compute/src/server.rs:193]: I wonder if there's an alternative design where we broadcast the initialization commands to all workers and only unicast once the initialization is done? This might have the downside of added complexity and making it harder to recover from errors during initialization.

File: src/service/src/client.rs [hunk 9]
```diff
@@ -125,7 +125,10 @@ where
     async fn send(&mut self, cmd: C) -> Result<(), anyhow::Error> {
         let cmd_parts = self.state.split_command(cmd);
         for (shard, cmd_part) in self.parts.iter_mut().zip(cmd_parts) {
-            shard.send(cmd_part).await?;
+            match cmd_part {
+                Some(cmd_part) => shard.send(cmd_part).await?,
+                None => {}
+            }
```
Comment (antiguru) [inline src/service/src/client.rs:131]:
```suggestion
            if let Some(cmd_part) = cmd_part {
                shard.send(cmd_part).await?;
            }
```

File: src/compute/src/server.rs [hunk 10]
```diff
@@ -185,14 +243,149 @@ impl<'w, A: Allocate> Worker<'w, A> {
...
+                    (0..peers)
+                        .zip(match x {
+                            Some(x) => Self::split_command(peers, x)
+                                .into_iter()
+                                .map(Some)
+                                .collect(),
+                            None => vec![None; peers],
+                        })
+                        .collect::<Vec<_>>()
+                })
```
Comment (antiguru) [inline src/compute/src/server.rs:363]: This could be inlined with the source above.

**Review by antiguru — COMMENTED** [review]
This looks mostly fine. I think there are some cases that can be simplified, and we want to preserve the behavior that commands are acted on in batches.

**Comment by lluki** [comment]
Thanks @antiguru, I first figure out what goes wrong with the tests then address your comments

File: src/compute/src/server.rs (hunk 8 above)
Comment (lluki) [reply src/compute/src/server.rs:188]: I think that's a possibility. Also regarding #14379 . It might make the cloud deployment easier if computed's start as "empty shell" and receive their configuration in the CreateInstance. If we do this, broadcasting the CreateInstance is a requirement.

File: src/compute/src/server.rs [hunk 11]
```diff
@@ -166,6 +221,9 @@ struct Worker<'w, A: Allocate> {
     /// The channel over which communication handles for newly connected clients
     /// are delivered.
     client_rx: crossbeam_channel::Receiver<(CommandReceiver, ResponseSender)>,
+    /// Upon insertion of a message to the CommandReceiver, this activator should be
+    /// invoked.
+    rx_activator: Arc<Mutex<Option<SyncActivator>>>,
```
[the remark this answers is not in the document]
Comment (lluki) [reply src/compute/src/server.rs:221]: Hm, how does clone help here?

What I think would be nicer is: 
 * Use another channel to transfer the SyncActivator over another channel after [this line ](https://github.com/MaterializeInc/materialize/blob/a406990739e14a421c1b4fc564440fa40e7059ae/src/storage/src/protocol/server.rs#L136)
 * Get rid of the rx_activator completely
 * Change the LocalClient `tx_activator: Arc<Mutex<Option<SyncActivator>>>,`  to `tx_activator: SyncActivator,`
 * And while we're at it, remove `thread` from LocalClient

File: src/compute/src/server.rs (hunk 2 above)
Comment (lluki) [reply src/compute/src/server.rs]: I changed this now to panic if `idx != 0` receives a message.

**Comment by lluki** [comment]
I'm thinking of [these lines (server.rs:382)](https://github.com/MaterializeInc/materialize/pull/14485/files#diff-92523f43f209ba78dfc13fd42b9bc9fe68f066ac53b76e2c979dc0d3c7235391L199-L215).

I'm pretty confident we  can replaced them with a simple `step_or_park`. The race with the initial recv() does not exist anymore, as the sending back of the activator acts as a barrier.

File: src/compute/src/server.rs [hunk 12]
```diff
@@ -172,14 +219,154 @@ impl<'w, A: Allocate> Worker<'w, A> {
...
+                            let time = cap.time().clone();
+                            let mut session = output.session(&cap);
+
+                            loop {
+                                match command_rx.try_recv() {
+                                    Ok(cmd) => {
+                                        // Commands must never be sent to another worker. This
+                                        // implementation does not guarantee an ordering of events
+                                        // sent to different workers.
+                                        assert!(idx == 0);
```
Comment (teskje) [inline src/compute/src/server.rs:314]: Nit: I assume `assert_eq!` would provide nicer output if the assert fails.

File: src/compute/src/server.rs [hunk 13]
```diff
@@ -172,14 +219,154 @@ impl<'w, A: Allocate> Worker<'w, A> {
...
+                        }
+                    }
+                })
+                .unary_frontier::<Vec<()>, _, _, _>(
+                    Exchange::new(|(idx, _)| *idx as u64),
+                    "CmdReceiver",
+                    |_, _| {
+                        move |input, _| {
+                            let mut queue = cmd_queue.borrow_mut();
+                            if input.frontier().frontier().len() == 0 {
```
Comment (teskje) [inline src/compute/src/server.rs:342]: I think this is the same as: `input.frontier().is_empty()`

File: src/compute/src/server.rs [hunk 14]
```diff
@@ -172,14 +219,154 @@ impl<'w, A: Allocate> Worker<'w, A> {
...
+
+                            loop {
+                                match command_rx.try_recv() {
+                                    Ok(cmd) => {
+                                        // Commands must never be sent to another worker. This
+                                        // implementation does not guarantee an ordering of events
+                                        // sent to different workers.
+                                        assert!(idx == 0);
+                                        session.give_iterator(
+                                            Self::split_command(cmd, peers).into_iter().enumerate(),
```
Comment (teskje) [inline src/compute/src/server.rs:316]: Is the `enumerate()` here necessary? Looks like you ignore the index on line 346 anyway.

File: src/compute/src/server.rs [hunk 15]
```diff
@@ -172,14 +219,154 @@ impl<'w, A: Allocate> Worker<'w, A> {
...
+                    "CmdReceiver",
+                    |_, _| {
+                        move |input, _| {
+                            let mut queue = cmd_queue.borrow_mut();
+                            if input.frontier().frontier().len() == 0 {
+                                queue.push_back(Err(TryRecvError::Disconnected))
+                            }
+                            while let Some((_, cmds)) = input.next() {
+                                for (_, cmd) in cmds.iter() {
+                                    queue.push_back(Ok(cmd.clone()));
```
Comment (teskje) [inline src/compute/src/server.rs:347]: The usual pattern is to potentially avoid cloning by using [`RefOrMut::swap`](https://docs.rs/timely/latest/timely/communication/message/enum.RefOrMut.html#method.swap) to swap the input data into a local buffer and then `.drain(..)` that. Would that be possible here as well?

**Review by teskje — COMMENTED** [review]
I had a couple small comments. I think I need to spend a Friday learning about the computed server before I'm able to understand the changes there though!

**Comment by teskje** [comment]
I'm not sure about removing the `step_or_park` workaround. Even if the specific race condition that caused this to be added doesn't exist anymore, do we have any guarantee that we won't add a new one in the future? If not, it might be useful to keep this as a safety measure and just change the comment to remove the outdated reference to `recv`.

File: src/compute/src/server.rs (hunk 14 above)
Comment (lluki) [reply src/compute/src/server.rs:316]: It is yes, the `Exchange::new(...)` of the `unary_frontier` is looking at the index

Comment (teskje) [reply src/compute/src/server.rs:316]: Ah, missed that!

File: src/compute/src/server.rs (hunk 15 above)
Comment (lluki) [reply src/compute/src/server.rs:347]: Ah yes, thx

File: src/compute/src/server.rs [hunk 16]
```diff
@@ -111,34 +120,33 @@ pub fn serve(
...
-            client_tx
-                .send(channels)
-                .expect("worker should not drop first");
-        }
-        let client =
-            LocalClient::new_partitioned(response_rxs, command_txs, worker_threads.clone());
+            .zip(command_rxs)
+            .zip(response_txs)
+            .map(|((client_tx, cmd_rx), resp_tx)| {
+                let (activator_tx, activator_rx) = std::sync::mpsc::channel();
```
Comment (antiguru) [inline src/compute/src/server.rs:140]: Nit: `crossbeam_channel`, like above :)

File: src/compute/src/server.rs [hunk 17]
```diff
@@ -176,14 +220,154 @@ impl<'w, A: Allocate> Worker<'w, A> {
...
+                            let mut queue = cmd_queue.borrow_mut();
+                            if input.frontier().is_empty() {
+                                queue.push_back(Err(TryRecvError::Disconnected))
+                            }
+                            while let Some((_, cmds)) = input.next() {
+                                for (_, cmd) in cmds.replace(Vec::new()).drain(..) {
+                                    queue.push_back(Ok(cmd));
+                                }
+                            }
+                        }
```
Comment (antiguru) [inline src/compute/src/server.rs:351]: Hold on the allocation instead of creating a new vector on each invocation:
```suggestion
                        let mut container = Default::default();
                        move |input, _| {
                            let mut queue = cmd_queue.borrow_mut();
                            if input.frontier().is_empty() {
                                queue.push_back(Err(TryRecvError::Disconnected))
                            }
                            while let Some((_, data)) = input.next() {
                                data.swap(&mut container);
                                for (_, cmd) in container.drain(..) {
                                    queue.push_back(Ok(cmd));
                                }
                            }
                        }
```

File: src/compute-client/src/service.rs [hunk 18]
```diff
@@ -179,51 +179,11 @@ impl<T> PartitionedState<ComputeCommand<T>, ComputeResponse<T>> for PartitionedC
...
-                dataflows_parts
-                    .into_iter()
-                    .map(ComputeCommand::CreateDataflows)
-                    .collect()
-            }
-            command => vec![command; self.parts],
-        }
+        let mut r = vec![None; self.parts];
+        r[0] = Some(command);
+        r
```
Comment (antiguru) [inline src/compute-client/src/service.rs:186]: I think I would have use iterator magic (once(command).chain(repeat(None, self.parts-1)) or something like this, but your version does the same job.

**Review by antiguru — APPROVED** [review]
I think this looks good. Thanks!
