### PR TITLE
coord: batch timestamp compactions in same transaction

### LINKED ISSUE #10582: loss of interactivity - 100% CPU in timely when multiple materialized sources point to the same Kafka topic
### What version of Materialize are you using?

b1b54fb719c8ebbf162c4cb5ad7934618e918bf7

### How did you install Materialize?

Docker image

### What was the issue?

If the timestamp frequency is low and multiple materialized persisted sources point to the same Kafka topic, Mz grinds to a halt with no new SQL connections being accepted. Timely spins at 100%  .

The issue is:
- causes loss of interactivity in addition to the CPU usage
- reproducible both on bare metal and in a container
- very reproducible with timestamp frequency 100ms, somewhat reproducible at 500ms and not reproducible at the default of 1s
- reproducible with --workers 4 on a 8CPU/16thread machine 

git bisect reports that the test below, part of the Nightly limits test, passed before the following commit:

```
commit b1b54fb719c8ebbf162c4cb5ad7934618e918bf7 (HEAD)
Author: Frank McSherry <fmcsherry@me.com>
Date:   Sat Feb 5 15:01:07 2022 -0500

    Hold back source frontiers to durable bindings (#10453)
    
    * hold back source frontiers to durable bindings
    
    * Teach TimstampBindings to activate operators
    
    * Allow durability capability to be crushed like grape
    
    * Teach create_source_simple to discard durability capability
    
    * dial down timestamping frequency
```

To reproduce, run the .td test belowq with `materialized --timestamp-frequency=100ms --persistent-kafka-sources` . You will observe progressive degradation in the speed of the individual `CREATE MATERIALIZED SOURCE` statements until no further progress is made. While the test is struggling, it would not be possible to connect to the Mz instance using psql. 

<details>
```
#
# <class 'mzcompose.KafkaSourcesSameTopic'>
#

> DROP SCHEMA IF EXISTS public CASCADE;
> CREATE SCHEMA public /* <class 'mzcompose.KafkaSourcesSameTopic'> */;
$ set key-schema={"type": "string"}
$ set value-schema={"type": "record", "name": "r", "fields": [{"name": "f1", "type": "string"}]}
$ kafka-create-topic topic=topic
$ kafka-ingest format=avro topic=topic key-format=avro key-schema=${key-schema} schema=${value-schema} publish=true
"123" {"f1": "123"}
> CREATE MATERIALIZED SOURCE s1
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s2
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s3
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s4
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s5
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s6
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s7
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s8
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s9
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s10
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s11
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s12
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s13
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s14
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s15
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s16
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s17
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s18
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s19
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s20
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s21
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s22
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s23
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s24
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s25
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s26
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s27
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s28
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s29
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s30
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s31
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s32
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s33
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s34
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s35
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s36
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s37
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s38
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s39
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s40
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s41
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s42
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s43
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s44
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s45
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s46
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s47
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s48
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s49
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> CREATE MATERIALIZED SOURCE s50
              FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-topic-${testdrive.seed}'
              FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
              ENVELOPE NONE;
              
> SELECT * FROM s1;
123
> SELECT * FROM s2;
123
> SELECT * FROM s3;
123
> SELECT * FROM s4;
123
> SELECT * FROM s5;
123
> SELECT * FROM s6;
123
> SELECT * FROM s7;
123
> SELECT * FROM s8;
123
> SELECT * FROM s9;
123
> SELECT * FROM s10;
123
> SELECT * FROM s11;
123
> SELECT * FROM s12;
123
> SELECT * FROM s13;
123
> SELECT * FROM s14;
123
> SELECT * FROM s15;
123
> SELECT * FROM s16;
123
> SELECT * FROM s17;
123
> SELECT * FROM s18;
123
> SELECT * FROM s19;
123
> SELECT * FROM s20;
123
> SELECT * FROM s21;
123
> SELECT * FROM s22;
123
> SELECT * FROM s23;
123
> SELECT * FROM s24;
123
> SELECT * FROM s25;
123
> SELECT * FROM s26;
123
> SELECT * FROM s27;
123
> SELECT * FROM s28;
123
> SELECT * FROM s29;
123
> SELECT * FROM s30;
123
> SELECT * FROM s31;
123
> SELECT * FROM s32;
123
> SELECT * FROM s33;
123
> SELECT * FROM s34;
123
> SELECT * FROM s35;
123
> SELECT * FROM s36;
123
> SELECT * FROM s37;
123
> SELECT * FROM s38;
123
> SELECT * FROM s39;
123
> SELECT * FROM s40;
123
> SELECT * FROM s41;
123
> SELECT * FROM s42;
123
> SELECT * FROM s43;
123
> SELECT * FROM s44;
123
> SELECT * FROM s45;
123
> SELECT * FROM s46;
123
> SELECT * FROM s47;
123
> SELECT * FROM s48;
123
> SELECT * FROM s49;
123
> SELECT * FROM s50;
123

```

</details>

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by benesch**
This doesn't resolve #10582 on its own, but seems obviously worth doing.

### Motivation

  * This PR works towards fixing a recognized bug.

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - N/A

### CODE REVIEW

**Review by ruchirK — APPROVED** [review]
LGTM

File: src/coord/src/coord.rs [hunk 1]
```diff
@@ -942,12 +943,14 @@ impl Coordinator {
...
-                        self.catalog
-                            .compact_timestamp_bindings(source_id, compaction_ts)
-                            .expect("compacting timestamp bindings cannot fail");
+                        timestamp_compactions.push((source_id, compaction_ts));
                     }
                 }
 
+                self.catalog
+                    .compact_timestamp_bindings(&timestamp_compactions)
+                    .expect("compacting timestamp bindings cannot fail");
```
Comment (frankmcsherry) [inline src/coord/src/coord.rs:952]: if non-empty? or is it cheap to do a no-op transaction?

**Review by antiguru — APPROVED** [review]

**Comment by ruchirK** [comment]
I don't see anything that changed between when I first reviewed and now, so still LGTM! Not sure why gh pinged me again for another review

**Review by ruchirK — APPROVED** [review]

File: src/coord/src/coord.rs (hunk 1 above)
Comment (benesch) [reply src/coord/src/coord.rs:952]: Ah yeah, should be super cheap. The `if` statement is probably a good idea, but I'm just going to merge as is because CI is green.
