### PR TITLE
adapter: Fix serializable read-then-writes

### LINKED ISSUE #16507: "Invalid data in source, saw retractions" after UPDATE on a table with index , serializable isolation level
### What version of Materialize are you using?

 v0.34.0-dev (b7ca2f48c)

### How did you install Materialize?

Docker image

### What is the issue?

```
materialize=> CREATE TABLE t1( x INTEGER);
materialize=> SET transaction_isolation=serializable;
INSERT INTO t1 VALUES(1);
CREATE INDEX t1i1 ON t1(x);
UPDATE t1 SET x=1;
UPDATE t1 SET x=2;
UPDATE t1 SET x=3;
UPDATE t1 SET x=4;
SELECT * FROM t1;
ERROR:  Invalid data in source, saw retractions (1) for row that does not exist: [Int32(1)]
```

Note that `UPDATE t1 SET x=1;` above returned `UPDATE 0`, which means no rows were updated. I guess this is expected given that we have no "read your writes" guarantee. However, the table should not become borked. Dropping the index does not cause the error to go away. 

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jkosh44**
Previously, how we picked a read timestamp for read-then-write queries depended on what transaction isolation level that we were in. The result of that read was then used to retract values from the underlying table. If the read was performed in Serializable mode, then we may have accidently read stale data and retracted stale data. This would permanently corrupt the table making it unreadable.

This commit changes the timestamp selection process so that we always pick a timestamp with the freshest data for read-then-write queries.

Fixes #16507

### Motivation
This PR fixes a recognized bug.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

File: src/adapter/src/coord/timestamp_selection.rs [hunk 1]
```diff
@@ -161,14 +158,22 @@ impl<S: Append + 'static> Coordinator<S> {
...
-            let timestamp_oracle = self.get_timestamp_oracle(timeline);
-            oracle_read_ts = Some(timestamp_oracle.read_ts());
-            candidate.join_assign(&oracle_read_ts.unwrap());
-        } else if when.advance_to_upper() {
+        if let Some(timeline) = &timeline {
+            if (isolation_level == &vars::IsolationLevel::StrictSerializable
+                && when.can_advance_to_global_ts())
+                || when.must_advance_to_global_ts()
+            {
+                let timestamp_oracle = self.get_timestamp_oracle(timeline);
```
Comment (mjibson) [inline src/adapter/src/coord/timestamp_selection.rs:166]: The functions have `global_ts` in their names, but this uses the timeline's oracle. Can the names be changed to accurately describe the requirements? Or maybe code needs to be added somewhere that only does this if the timeline is epochms?

File: src/adapter/src/coord/timestamp_selection.rs [hunk 2]
```diff
@@ -161,14 +158,22 @@ impl<S: Append + 'static> Coordinator<S> {
...
+                oracle_read_ts = Some(timestamp_oracle.read_ts());
+                candidate.join_assign(&oracle_read_ts.unwrap());
+            } else if when.can_advance_to_upper() {
+                candidate.join_assign(&largest_not_in_advance_of_upper);
```
Comment (mjibson) [inline src/adapter/src/coord/timestamp_selection.rs:170]: This function is called like this 3 times, and the logic to follow why it should be called is hard to understand. Specifically, I'm trying to answer the question "when isn't this function called?" and can't do it convincingly. An idea that I don't like: make a `let advance_to_upper: bool = when.can_advance_to_upper()` that gets set to `false` in the oracle ts case, then do `if advance_to_upper|| when.must_advance_to_upper() { candidate.join_assign(&largest_not_in_advance_of_upper); }`. This would make it so advancing to an upper happens in exactly one place, and will maybe ease understanding of the design we're trying to achieve.

Also, I no longer recall why the if block here was "either do use_timestamp_oracle or use the upper", and wished there were a comment describing why we don't care about the upper in the oracle ts case.

File: src/adapter/src/coord/timestamp_selection.rs (hunk 1 above)
Comment (jkosh44) [reply src/adapter/src/coord/timestamp_selection.rs]: Good point, I've changed the name of these functions.

File: src/adapter/src/coord/timestamp_selection.rs (hunk 2 above)
Comment (jkosh44) [reply src/adapter/src/coord/timestamp_selection.rs]: I tried to clean this up and add comments, let me know what you think of it now.

**Comment by philip-stoev** [comment]
I will test this a bit with a randomized workload as soon as the branch compiles.

**Comment by jkosh44** [comment]
> I will test this a bit with a randomized workload as soon as the branch compiles.

Oops, sorry. I thought I'd change one small thing last night and never checked that it still compiled. I just fixed it

File: src/adapter/src/coord/timestamp_selection.rs [hunk 3]
```diff
@@ -161,14 +158,33 @@ impl<S: Append + 'static> Coordinator<S> {
...
+                oracle_read_ts = Some(timestamp_oracle.read_ts());
+                candidate.join_assign(&oracle_read_ts.unwrap());
+            }
+        }
+
+        // We advance to the upper in the following scenarios:
+        // - The isolation level is Serializable and the `when` allows us to advance to upper (ex:
+        //   queries with no AS OF). We avoid using the upper in Strict Serializable to prevent
+        //   reading source data that is being written to in the future.
+        // - The isolation level is Strict Serializable but there is no timelines and the `when`
```
Comment (mjibson) [inline src/adapter/src/coord/timestamp_selection.rs:181]: What's the upper of a thing with no timeline? Are there things with no timeline that have a non-empty id_bundle?

**Review by mjibson — APPROVED** [review]

**Review by philip-stoev — APPROVED** [review]
No wrong results, panics or table corruptions with a randomized DML workload

**Comment by jkosh44** [comment]
> No wrong results, panics or table corruptions with a randomized DML workload

Thanks for finding this and helping with testing @philip-stoev!
