### PR TITLE
interchange: reject recursive protobuf messages

### LINKED ISSUE #5609: Stack Overflow when creating a source with a protobuf schema with a recursively-defined type. (It should error instead).
### What version of Materialize are you using?

```
$ materialized -v
materialized v0.6.1 (3247686f8)
```

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [x] Built from source

### What was the issue?

When trying to run `CREATE SOURCE`, materialized crashes with the following output:

```sh
thread '<unknown>' has overflowed its stack
fatal runtime error: stack overflow
fish: './materialized -w 3' terminated by signal SIGABRT (Abort)
```

Here's the offending SQL (protobuf file attached below):

```sql
CREATE SOURCE messages
FROM KAFKA BROKER '<broker omitted>' TOPIC '<topic omitted>'
FORMAT PROTOBUF MESSAGE '.repro.Status' USING SCHEMA FILE 'StatusSchema';
```

You may notice that I omitted the kafka broker and topic. I tested what would happen if I gave junk values for both (so values pointed to no real broker or topic) and still got the stack overflow.

Also, note that the examples on the documentation site for `CREATE SOURCE` for `Kafka+protobuf` are not entirely correct. It's missing `FROM` and just has `USING '[path to schema]'` rather than `USING SCHEMA FILE '[path to schema]'`. Therefore, I'm not sure if there's a mistake with my sql but I'm pretty sure regardless materialized should not crash.

### Is the issue reproducible? If so, please provide reproduction instructions.

1. `protoc --include_imports --descriptor_set_out=StatusSchema Status.proto` (assuming `Status.proto` is in current dir. Proto file attached below)
2. `materialized -w 3`
3. `psql -h localhost -p 6875 materialize`
4. Run the SQL from above

### Please attach any applicable log files.

[materialized.log](https://github.com/MaterializeInc/materialize/files/5927961/materialized.log)
[Status.txt](https://github.com/MaterializeInc/materialize/files/5927988/Status.txt) (Github only allows attachments of certain file types so just rename this from `.txt` to `.proto`

### PR DESCRIPTION
**Pull request by benesch**
We can't presently handle recursive types, so we need to reject Protobuf
messages that are recursively defined.

Fix #5609.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5791)

### CODE REVIEW

File: src/interchange/src/protobuf.rs [hunk 1]
```diff
@@ -55,9 +61,14 @@ fn validate_proto_field(field: &FieldDescriptor, descriptors: &Descriptors) -> R
                 FieldType::String => ScalarType::String,
                 FieldType::Bytes => ScalarType::Bytes,
                 FieldType::Message(m) => {
+                    if seen_messages.contains(m.name()) {
+                        bail!("Recursive messages are not supported: {}", m.name());
```
Comment (umanwizard) [inline src/interchange/src/protobuf.rs:65]: In avro.rs we use:

```
                        bail!(
                            "Recursively defined type in schema: {}",
                            v.get_human_name(schema.root)
                        );
```

We should probably make the messages match.

**Review by umanwizard — APPROVED** [review]

File: src/interchange/src/protobuf.rs (hunk 1 above)
Comment (benesch) [reply src/interchange/src/protobuf.rs]: Ack, changed both to "Recursive types are not supported: {}". Error messages that are statements of fact ("Recursive type in schema: {}") are a bit of a pet peeve of mine because they only _imply_ that the error is that recursive types are unsupported; they don't tell you outright. 

I think the best error message here would be one that uses the new detail/hint setup, because the current phrasing is still awkward. Something like:

```
ERROR: recursive type detected in schema
DETAIL: The following cycle was detected:
  Message1
  Message2
  Message3
  Message1
```

But, not gonna shave that yak presently.

**Review by quodlibetor — APPROVED** [review]

File: src/interchange/src/avro.rs [hunk 2]
```diff
@@ -1109,7 +1109,7 @@ fn validate_schema_2(
                 if let Some(named_idx) = named_idx {
                     if !seen_avro_nodes.insert(named_idx) {
                         bail!(
-                            "Recursively defined type in schema: {}",
+                            "Recursive types are not supported: {}",
```
Comment (umanwizard) [inline src/interchange/src/avro.rs:1112]: You missed a spot, on line 1137.

Comment (benesch) [reply src/interchange/src/avro.rs:1112]: Blugh, thanks, fixed.
