### PR TITLE
Reconnect all partitions at once

### LINKED ISSUE #12386: Ensure that all shards in a partitioned client come from the same incarnation.
### What version of Materialize are you using?

main

### How did you install Materialize?

Built from source

### What was the issue?

Related to #12233 , but that will not be fixed without also fixing the cancellation-safety issues raised in #12385 .

Currently, when a TcpClient's connection is broken, it attempts to reconnect. Because of the shared-fate model, when one timely process goes down, they _all_ will, and the connection logic only works properly if all the TcpClients reconnect to processes in the same incarnation of the timely cluster.

This might not happen, for a few reasons:

1. Currently we don't close the process's TcpListener at all, so it might accept a second connection after the first one has been torn down but before the process has fully terminated.

This can be fixed rather easily by closing the listener immediately after accepting one connection.

2. When we turn on `--linger`, the fix above obviously isn't possible, because the whole point is to re-establish connections.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by umanwizard**
This should fix https://github.com/MaterializeInc/materialize/issues/12386 by the strategy discussed in https://github.com/MaterializeInc/materialize/issues/12386#issuecomment-1125625715

### Motivation

(Probabilistically) fixes #12386 

### Testing

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

File: src/dataflow-types/src/client.rs [hunk 1]
```diff
@@ -736,6 +736,13 @@ pub type LocalStorageClient = LocalClient<StorageCommand, StorageResponse>;
 /// A [`LocalClient`] for the compute layer.
 pub type LocalComputeClient = LocalClient<ComputeCommand, ComputeResponse>;
 
+/// Trait for clients that can be disconnected and reconnected.
+#[async_trait]
+pub trait Reconnect {
```
Comment (benesch) [inline src/dataflow-types/src/client.rs:741]: This probably should inherit from `GenericClient`, yeah?

```suggestion
pub trait Reconnect<C, R>: GenericClient<C, R> {
```

File: src/dataflow-types/src/client.rs [hunk 2]
```diff
@@ -768,7 +775,7 @@ where
     pub async fn connect(&mut self) {
         // TODO: initiate connections concurrently.
         for remote in self.client.parts.iter_mut() {
-            remote.connect().await;
+            remote.reconnect().await;
         }
     }
```
Comment (benesch) [inline src/dataflow-types/src/client.rs:780]: Can this move to an implementation of `Reconnect` for `RemoteClient`?

File: src/dataflow-types/src/client.rs (hunk 1 above)
Comment (umanwizard) [reply src/dataflow-types/src/client.rs:741]: That doesn't gain you anything, but requires putting a bunch of random unnecessary trait bounds on e.g. the TcpClient impl (because its GenericClient impl has those bounds...)

I can add it if you want, seems like stylistic preference though.

Comment (benesch) [reply src/dataflow-types/src/client.rs:844]: Yeah I guess it doesn't much matter since the definition of `Reconnect` doesn't need to reference anything about `GenericClient`.

**Review by benesch — APPROVED** [review]
🙌🏽
