### PR TITLE
test: add some JavaScript tests

### LINKED ISSUE #2610: Test pgwire with invalid inputs
Prior to #2593, the following node program would crash materialize:
```
const { Client } = require('pg')
const client = new Client({
  host: 'localhost',
  port: 6875,
});

client.connect();

client.query({
  text: 'select $1::int + $2::int',
  values: [1],
}, (err, res) => {
  console.log(err);
  console.log(res);
  client.end()
});
```

Recreating this test in rust is a pain, since the rust postgres driver does a safety check here client-side. Figure out a way to test this appropriately.

### PR DESCRIPTION
**Pull request by benesch**
The rust-postgres client is a bit too helpful in doing client-side
validations, making it difficult to test things like a query with an
incorrect number of bind parameters. The JavaScript Postgres driver is
far less strict about this, so add support for writing tests in
JavaScript.

We'll likely want to expand our support for testing in other languages,
so I've set up a new test/lang directory to facilitate future expansion
of these non-Rust test suites.

Fix #2610.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/2623)

### CODE REVIEW

File: src/pgwire/protocol.rs [hunk 1]
```diff
@@ -504,13 +504,16 @@ where
         };
 
         let param_types = stmt.param_types();
-        if param_types.len() > raw_params.len() {
+        if param_types.len() != raw_params.len() {
```
Comment (justinj) [inline src/pgwire/protocol.rs:507]: I haven't actually tested PG's behaviour here, but providing more than required should be fine, shouldn't it? I'm imagining a scenario where someone is mechanically constructing a query that winds up, by whatever means, omitting a reference to a given placeholder. It shouldn't cease to be valid to send the entire set of placeholders in that case.

Comment (benesch) [reply src/pgwire/protocol.rs:507]: Possibly this is true, but real Postgres rejects queries with too many parameters. I developed the test suite against real Postgres by accident (forgot to override the default connection params), and then just fixed up materialized to match. Probably best to err on the more restrictive side, since loosening restrictions will be backwards compatible but the reverse is not?

Comment (justinj) [reply src/pgwire/protocol.rs:507]: Yeah totally, if that's what Postgres does then no objections!
