### PR TITLE
persist: write META atomically

### LINKED ISSUE #7924: persistence: "persistence error: invalid meta at key: META" fatal error on startup
### What version of Materialize are you using?

```
ed424518a
```

### What was the issue?

After loading some data and then killing and restarting Mz a couple of times, it no longer starts up:

```
2021-08-19T10:42:00.735792Z  INFO materialized: booting server
materialized v0.9.1-dev (ed424518a)
OpenSSL 1.1.1k  25 Mar 2021
librdkafka v1.6.1
invoked as: MZ_DEV=1 target/release/materialized --experimental --persistent-user-tables --log-file stderr
os: Ubuntu 20.04 (focal) [64-bit]
cpus: 16 logical, 8 physical, 8 useful
cpu0: AMD Ryzen 7 3700X 8-Core Processor 2179MHz
memory: 67438780KB total, 3758265KB used
swap: 34325131KB total, 132580KB used    
materialized: persistence error: invalid meta at key: META
```
and that is it.

### Is the issue reproducible? If so, please provide reproduction instructions.

1. Load the DDL and INSERT statements from the archive gh7924.zip](https://github.com/MaterializeInc/materialize/files/7013835/gh7924.zip)

2. Once done. use Ctrl+C to kill Mz and then restart it, killing it repeatedly during statup. Shortly you will see the error above.
I have also attached the `mzdata` directory.

### PR DESCRIPTION
**Pull request by danhhz**
Fixes bug where an interrupted write to META (e.g. through an unclean
shutdown) would prevent the persistence runtime from starting up again
on restart.

Closes #7924

### CODE REVIEW

File: src/persist/src/file.rs [hunk 1]
```diff
@@ -322,16 +323,27 @@ impl Blob for FileBlob {
...
+            let mut tmp_name = file_path.clone();
+            debug_assert_eq!(tmp_name.extension(), None);
+            tmp_name.set_extension(UNIX_EPOCH.elapsed().unwrap().as_nanos().to_string());
+            let mut file = OpenOptions::new()
+                .write(true)
+                .create_new(true)
+                .open(&tmp_name)?;
+            file.write_all(&value[..])?;
+            file.sync_all()?;
+            fs::rename(tmp_name, &file_path)?;
```
Comment (ruchirK) [inline src/persist/src/file.rs:338]: i _think_ you have to also fsync the parent directory to persist the rename correctly (at least on some file systems). that being said, you probably also have to do that on file create time. I'm ok leaving it as a todo / to figure out later for now.

**Review by ruchirK — APPROVED** [review]
LGTM!

My one minor thought is that if you named the tmp file say `META_tmp` and `create`d it instead of create new then there would never be any orphaned partial meta writes and after a restart the tmp file would just get overwritten the next time we write to meta. I don't think its a huge deal to leave this as-is for now

File: src/persist/src/file.rs (hunk 1 above)
Comment (danhhz) [reply src/persist/src/file.rs:338]: yeah you're right. I don't see anything in the stdlib for this, so added the TODO for now

**Review by danhhz — COMMENTED** [review]
> My one minor thought is that if you named the tmp file say META_tmp and created it instead of create new then there would never be any orphaned partial meta writes and after a restart the tmp file would just get overwritten the next time we write to meta.

Great suggestion! Done

**Comment by danhhz** [comment]
TFTR!
