### PR TITLE
storage-types: trait-ify AlterCompatible

### LINKED ISSUE #22948: thread 'timely:work-0' panicked at 'only alter compatible ingestions permitted: InvalidAlterSource { id: User(5) }'
### What version of Materialize are you using?

04305fbed2

### What is the issue?

Seen in https://buildkite.com/materialize/nightlies/builds/4991#018b9786-2dc0-4cf7-822a-ca8bc396aa88
```
2023-11-03T23:36:28.259920Z  WARN mz_storage_types::sources: IngestionDescription incompatible:
self:
IngestionDescription {
    desc: SourceDesc {
        connection: Postgres(
            PostgresSourceConnection {
                connection_id: User(
                    2,
                ),
                connection: PostgresConnection {
                    host: "postgres",
                    port: 5432,
                    database: "postgres",
                    user: String(
                        "postgres",
                    ),
                    password: Some(
                        User(
                            1,
                        ),
                    ),
                    tunnel: Direct,
                    tls_mode: Disable,
                    tls_root_cert: None,
                    tls_identity: None,
                },
                table_casts: {
                    1: [
                        CallVariadic {
                            func: ErrorIfNull,
                            exprs: [
                                CallUnary {
                                    func: CastStringToInt32(
                                        CastStringToInt32,
                                    ),
                                    expr: Column(
                                        0,
                                    ),
                                },
                                Literal(
                                    Ok(
                                        Row{[
                                            String(
                                                "PG column public.t1.f1 contained NULL data, despite having NOT NULL constraint",
                                            ),
                                        ]},
                                    ),
                                    ColumnType {
                                        scalar_type: String,
                                        nullable: false,
                                    },
                                ),
                            ],
                        },
                        CallUnary {
                            func: CastStringToInt32(
                                CastStringToInt32,
                            ),
                            expr: Column(
                                1,
                            ),
                        },
                        Column(
                            2,
                        ),
                    ],
                },
                publication: "mz_source",
                publication_details: PostgresSourcePublicationDetails {
                    tables: [
                        PostgresTableDesc {
                            oid: 16385,
                            namespace: "public",
                            name: "t1",
                            columns: [
                                PostgresColumnDesc {
                                    name: "f1",
                                    col_num: Some(
                                        1,
                                    ),
                                    type_oid: 23,
                                    type_mod: -1,
                                    nullable: false,
                                },
                                PostgresColumnDesc {
                                    name: "f2",
                                    col_num: Some(
                                        2,
                                    ),
                                    type_oid: 23,
                                    type_mod: -1,
                                    nullable: true,
                                },
                                PostgresColumnDesc {
                                    name: "f3",
                                    col_num: Some(
                                        3,
                                    ),
                                    type_oid: 25,
                                    type_mod: -1,
                                    nullable: true,
                                },
                            ],
                            keys: {
                                PostgresKeyDesc {
                                    oid: 16393,
                                    name: "t1_pkey",
                                    cols: [
                                        1,
                                    ],
                                    is_primary: true,
                                    nulls_not_distinct: false,
                                },
                            },
                        },
                    ],
                    slot: "materialize_69144fd9dd6c4371b3f53915fec804cf",
                },
            },
        ),
        encoding: Single(
            DataEncoding {
                force_nullable_columns: false,
                inner: RowCodec(
                    RelationDesc {
                        typ: RelationType {
                            column_types: [],
                            keys: [],
                        },
                        names: [],
                    },
                ),
            },
        ),
        envelope: None(
            NoneEnvelope {
                key_envelope: None,
                key_arity: 0,
            },
        ),
        timestamp_interval: 1s,
    },
    source_imports: {},
    ingestion_metadata: CollectionMetadata {
        persist_location: PersistLocation {
            blob_uri: "file:///mzdata/persist/blob",
            consensus_uri: "postgresql://root@2994a170b3c1:26257?options=--search_path=consensus",
        },
        remap_shard: Some(
            ShardId(4912fe34-af1f-498e-95a5-e8fea37629d9),
        ),
        data_shard: ShardId(4d149733-4d48-4a7f-8634-330c96fbbe45),
        status_shard: Some(
            ShardId(24772af5-e220-49f4-be5a-baf1c15f8686),
        ),
        relation_desc: RelationDesc {
            typ: RelationType {
                column_types: [],
                keys: [],
            },
            names: [],
        },
        txns_shard: None,
    },
    source_exports: {
        User(
            3,
        ): SourceExport {
            output_index: 1,
            storage_metadata: CollectionMetadata {
                persist_location: PersistLocation {
                    blob_uri: "file:///mzdata/persist/blob",
                    consensus_uri: "postgresql://root@2994a170b3c1:26257?options=--search_path=consensus",
                },
                remap_shard: None,
                data_shard: ShardId(78f0702d-a3b4-4a2a-8dc5-d618a6034d9e),
                status_shard: Some(
                    ShardId(24772af5-e220-49f4-be5a-baf1c15f8686),
                ),
                relation_desc: RelationDesc {
                    typ: RelationType {
                        column_types: [
                            ColumnType {
                                scalar_type: Int32,
                                nullable: false,
                            },
                            ColumnType {
                                scalar_type: Int32,
                                nullable: true,
                            },
                            ColumnType {
                                scalar_type: String,
                                nullable: true,
                            },
                        ],
                        keys: [
                            [
                                0,
                            ],
                        ],
                    },
                    names: [
                        ColumnName(
                            "f1",
                        ),
                        ColumnName(
                            "f2",
                        ),
                        ColumnName(
                            "f3",
                        ),
                    ],
                },
                txns_shard: None,
            },
        },
        User(
            5,
        ): SourceExport {
            output_index: 0,
            storage_metadata: CollectionMetadata {
                persist_location: PersistLocation {
                    blob_uri: "file:///mzdata/persist/blob",
                    consensus_uri: "postgresql://root@2994a170b3c1:26257?options=--search_path=consensus",
                },
                remap_shard: Some(
                    ShardId(4912fe34-af1f-498e-95a5-e8fea37629d9),
                ),
                data_shard: ShardId(4d149733-4d48-4a7f-8634-330c96fbbe45),
                status_shard: Some(
                    ShardId(24772af5-e220-49f4-be5a-baf1c15f8686),
                ),
                relation_desc: RelationDesc {
                    typ: RelationType {
                        column_types: [],
                        keys: [],
                    },
                    names: [],
                },
                txns_shard: None,
            },
        },
    },
    instance_id: User(
        2,
    ),
    remap_collection_id: User(
        4,
    ),
}

other
IngestionDescription {
    desc: SourceDesc {
        connection: Postgres(
            PostgresSourceConnection {
                connection_id: User(
                    2,
                ),
                connection: PostgresConnection {
                    host: "postgres",
                    port: 5432,
                    database: "postgres",
                    user: String(
                        "postgres",
                    ),
                    password: Some(
                        User(
                            1,
                        ),
                    ),
                    tunnel: Direct,
                    tls_mode: Disable,
                    tls_root_cert: None,
                    tls_identity: None,
                },
                table_casts: {
                    1: [
                        CallVariadic {
                            func: ErrorIfNull,
                            exprs: [
                                CallUnary {
                                    func: CastStringToInt32(
                                        CastStringToInt32,
                                    ),
                                    expr: Column(
                                        0,
                                    ),
                                },
                                Literal(
                                    Ok(
                                        Row{[
                                            String(
                                                "PG column public.t1.f1 contained NULL data, despite having NOT NULL constraint",
                                            ),
                                        ]},
                                    ),
                                    ColumnType {
                                        scalar_type: String,
                                        nullable: false,
                                    },
                                ),
                            ],
                        },
                        CallUnary {
                            func: CastStringToInt32(
                                CastStringToInt32,
                            ),
                            expr: Column(
                                1,
                            ),
                        },
                        Column(
                            2,
                        ),
                    ],
                },
                publication: "mz_source",
                publication_details: PostgresSourcePublicationDetails {
                    tables: [
                        PostgresTableDesc {
                            oid: 16385,
                            namespace: "public",
                            name: "t1",
                            columns: [
                                PostgresColumnDesc {
                                    name: "f1",
                                    col_num: Some(
                                        1,
                                    ),
                                    type_oid: 23,
                                    type_mod: -1,
                                    nullable: false,
                                },
                                PostgresColumnDesc {
                                    name: "f2",
                                    col_num: Some(
                                        2,
                                    ),
                                    type_oid: 23,
                                    type_mod: -1,
                                    nullable: true,
                                },
                                PostgresColumnDesc {
                                    name: "f3",
                                    col_num: Some(
                                        3,
                                    ),
                                    type_oid: 25,
                                    type_mod: -1,
                                    nullable: true,
                                },
                            ],
                            keys: {
                                PostgresKeyDesc {
                                    oid: 16393,
                                    name: "t1_pkey",
                                    cols: [
                                        1,
                                    ],
                                    is_primary: true,
                                    nulls_not_distinct: false,
                                },
                            },
                        },
                    ],
                    slot: "materialize_69144fd9dd6c4371b3f53915fec804cf",
                },
            },
        ),
        encoding: Single(
            DataEncoding {
                force_nullable_columns: false,
                inner: RowCodec(
                    RelationDesc {
                        typ: RelationType {
                            column_types: [],
                            keys: [],
                        },
                        names: [],
                    },
                ),
            },
        ),
        envelope: None(
            NoneEnvelope {
                key_envelope: None,
                key_arity: 0,
            },
        ),
        timestamp_interval: 1s,
    },
    source_imports: {},
    ingestion_metadata: CollectionMetadata {
        persist_location: PersistLocation {
            blob_uri: "file:///mzdata/persist/blob",
            consensus_uri: "postgresql://root@1097ab88655f:26257?options=--search_path=consensus",
        },
        remap_shard: Some(
            ShardId(4912fe34-af1f-498e-95a5-e8fea37629d9),
        ),
        data_shard: ShardId(4d149733-4d48-4a7f-8634-330c96fbbe45),
        status_shard: Some(
            ShardId(24772af5-e220-49f4-be5a-baf1c15f8686),
        ),
        relation_desc: RelationDesc {
            typ: RelationType {
                column_types: [],
                keys: [],
            },
            names: [],
        },
        txns_shard: None,
    },
    source_exports: {
        User(
            3,
        ): SourceExport {
            output_index: 1,
            storage_metadata: CollectionMetadata {
                persist_location: PersistLocation {
                    blob_uri: "file:///mzdata/persist/blob",
                    consensus_uri: "postgresql://root@1097ab88655f:26257?options=--search_path=consensus",
                },
                remap_shard: None,
                data_shard: ShardId(78f0702d-a3b4-4a2a-8dc5-d618a6034d9e),
                status_shard: Some(
                    ShardId(24772af5-e220-49f4-be5a-baf1c15f8686),
                ),
                relation_desc: RelationDesc {
                    typ: RelationType {
                        column_types: [
                            ColumnType {
                                scalar_type: Int32,
                                nullable: false,
                            },
                            ColumnType {
                                scalar_type: Int32,
                                nullable: true,
                            },
                            ColumnType {
                                scalar_type: String,
                                nullable: true,
                            },
                        ],
                        keys: [
                            [
                                0,
                            ],
                        ],
                    },
                    names: [
                        ColumnName(
                            "f1",
                        ),
                        ColumnName(
                            "f2",
                        ),
                        ColumnName(
                            "f3",
                        ),
                    ],
                },
                txns_shard: None,
            },
        },
        User(
            5,
        ): SourceExport {
            output_index: 0,
            storage_metadata: CollectionMetadata {
                persist_location: PersistLocation {
                    blob_uri: "file:///mzdata/persist/blob",
                    consensus_uri: "postgresql://root@1097ab88655f:26257?options=--search_path=consensus",
                },
                remap_shard: Some(
                    ShardId(4912fe34-af1f-498e-95a5-e8fea37629d9),
                ),
                data_shard: ShardId(4d149733-4d48-4a7f-8634-330c96fbbe45),
                status_shard: Some(
                    ShardId(24772af5-e220-49f4-be5a-baf1c15f8686),
                ),
                relation_desc: RelationDesc {
                    typ: RelationType {
                        column_types: [],
                        keys: [],
                    },
                    names: [],
                },
                txns_shard: None,
            },
        },
    },
    instance_id: User(
        2,
    ),
    remap_collection_id: User(
        4,
    ),
}
thread 'timely:work-0' panicked at 'only alter compatible ingestions permitted: InvalidAlterSource { id: User(5) }', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-08e960feb1ea4ec70-1/materialize/tests/src/storage/src/storage_state.rs:1020:34
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: <mz_storage::server::Config as mz_cluster::types::AsRunnableWorker<mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>>::build_and_run::<timely_communication::allocator::generic::Generic>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```
This assertion was added in https://github.com/MaterializeInc/materialize/pull/19310 (CC @sploiselle) This seems to be a regression in bounded-memory's `pg-cdc-update` scenario, which was not changed recently. So considering this a release blocker. It fails reliably in CI, potential changes which could have caused this regression: https://github.com/MaterializeInc/materialize/compare/6dce29c56e...04305fbed2 @dan Do you think any of your PRs could be responsible for this? (https://github.com/MaterializeInc/materialize/pull/22903, https://github.com/MaterializeInc/materialize/pull/22902) Assigning you for now since that's the best guess I have.

ci-regexp: panicked at 'only alter compatible ingestions permitted: InvalidAlterSource

### PR DESCRIPTION
**Pull request by sploiselle**
To express "alter compatibility" for structs w/ generic fields in ways more complex than relying on the PartialEq impl, we need a trait.

This commit does that, in addition to expressing that a CollectionMetadata's persist location may change.

### Motivation

Fixes #22948 -- this does not _need_ to panic because if the persist URI meaningfully changes (i.e. we are unexpectedly connected to a new cockroach cluster), there will be other more serious symptoms than this check.

Further, Cockroach allows you to connect to query many replicas in the cluster, so querying some new replica does not necessarily imply that anything has meaningfully changed.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

File: src/storage-types/src/lib.rs [hunk 1]
```diff
@@ -85,3 +85,23 @@ pub mod parameters;
 pub mod shim;
 pub mod sinks;
 pub mod sources;
+
+/// Explicitly states the contract between storage and higher levels of
+/// Materialize w/r/t which facets of objects managed by storage (e.g. sources,
+/// sinks, connections) may be altered.
+///
+/// n.b. when implementing this trait, leave a warning log with more details as
+/// to what the problem was, given that the returned error is scant on details.
```
Comment (ParkMyCar) [inline src/storage-types/src/lib.rs:94]: If tracing a warn is very important, maybe we should make it required that `fn alter_compatible(...)` returns a message? e.g.
```
fn alter_compatible(...) -> Result<(), (String, StorageError)> { ... }
```
Up to you!

**Review by ParkMyCar — APPROVED** [review]

File: src/storage-types/src/sources.rs [hunk 2]
```diff
@@ -133,7 +132,9 @@ impl<S: Debug + Eq + PartialEq> IngestionDescription<S> {
 
         let compatibility_checks = [
```
Comment (moulimukherjee) [inline src/storage-types/src/sources.rs:133]: nit: I think the checks with desc like `(remap_shard == &other.remap_shard, "remap_shard"),` above was nice. Is that possible to do it here?

**Review by moulimukherjee — APPROVED** [review]
lgtm! Had a nit, but not blocking.

File: src/storage-types/src/lib.rs (hunk 1 above)
Comment (sploiselle) [reply src/storage-types/src/lib.rs:94]: Good call––hadn't considered that patter.

File: src/storage-types/src/sources.rs (hunk 2 above)
Comment (sploiselle) [reply src/storage-types/src/sources.rs:133]: Oh yes, I have all of those in another PR and didn't port them over here, but I should.

File: src/storage-types/src/lib.rs (hunk 1 above)
Comment (sploiselle) [reply src/storage-types/src/lib.rs:94]: Ah, this makes nesting the logs annoying so leaving as-is but I appreciate the suggestion.
