### PR TITLE
Propagate inotify related errors in file sources

### LINKED ISSUE #6114: "failed to initialize inotify" and related errors not propagated to SQL client
### What version of Materialize are you using?

```
v0.7.2-dev (c14eabd85)
```
### What was the issue?

If ```inotify``` can not be initialized, the following error is printed in the log:

```
materialized_1     | 2021-03-17T12:13:12.645063Z ERROR dataflow::source::file: file source: failed to initialize inotify: Bad file descriptor (os error 9)    
```

However, the error is not propagated to the affected materialized views, so selecting against them returns no rows.

### Is the issue reproducible? If so, please provide reproduction instructions.

Yes, see test case in #6115

### PR DESCRIPTION
**Pull request by cirego**
Instead of ignoring errors from inotify, raise the errors on the source stream. This will cause views to error out instead of returning empty results.

Fixes #6114

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/6218)

### CODE REVIEW

**Comment by cirego** [comment]
@philip-stoev, this test case is hard to automate. Are you willing to test this manually?

I'm going to think about how we can automate testing this. Once this PR is done, I'll start looking at #6115 to make sure we correctly cleanup resources.

**Review by philip-stoev — APPROVED** [review]
I tested this manually and it works as advertised.

With respect to an automated test, I do not think it is worth having a separate mzcompose file just for this corner case. Instead, what I am going to do it open a ticket for myself to create a general "database limits" test that will make sure you can safely have 100s of file sources, 100s of tables, etc.

File: src/dataflow/src/source/file.rs [hunk 1]
```diff
@@ -257,37 +299,40 @@ pub fn read_file_task<Ctor, I, Out, Err>(
...
-                        path.display()
-                    );
-                    return;
-                }
-                let path = path.clone();
+                let mut inotify = Inotify::init()
+                    .with_context(|| format!("file source: failed to initialize inotify"))?;
+                inotify
+                    .add_watch(&_path, WatchMask::ALL_EVENTS)
+                    .with_context(|| format!("failed to add watch for file {}", _path.display()))?;
```
Comment (philip-stoev) [inline src/dataflow/src/source/file.rs:306]: Can we get the underlying OS error message in here as well:

```
inotify.td:8:1: error: executing query failed: db error: ERROR: Source error: File IO: failed to add watch for file /tmp/.tmps0gOpN/dynamic.csv
```

The previous code had ```..."file source: failed to add watch for file: {:#} (path: {})", err,...``` which provided that information.

File: src/dataflow/src/source/file.rs [hunk 2]
```diff
@@ -225,13 +225,55 @@ pub fn read_file_task<Ctor, I, Out, Err>(
     }) {
         Ok(file) => file,
         Err(err) => {
-            let _ = tx.send(Err(err));
+            if let Err(send_e) = tx.send(Err(err)) {
+                error!("Failed to send error when opening file: {:#}", send_e);
```
Comment (umanwizard) [inline src/dataflow/src/source/file.rs:229]: This isn't an error; we should leave it as is. IIRC (though my memory is a bit hazy) there is a race where when we drop the source, the receiver on the other end of this channel might go away before this task is stopped, so some spurious messages might be sent, in which case this call will error.

That's why previously we were dropping the error on the floor.

File: src/dataflow/src/source/file.rs [hunk 3]
```diff
@@ -225,13 +225,55 @@ pub fn read_file_task<Ctor, I, Out, Err>(
...
+            }
             return;
         }
     };
 
-    let file: Box<dyn AvroRead + Send> = match read_style {
-        FileReadStyle::ReadOnce => Box::new(file),
+    let file_stream = match open_file_stream(path.clone(), file, read_style) {
+        Ok(f) => f,
+        Err(err) => {
```
Comment (umanwizard) [inline src/dataflow/src/source/file.rs:237]: same here

File: src/dataflow/src/source/file.rs (hunk 2 above)
Comment (cirego) [reply src/dataflow/src/source/file.rs:229]: Okay, I will change this back then, with a comment. I was over-eager to catch all the bugs!

File: src/dataflow/src/source/file.rs (hunk 3 above)
Comment (cirego) [reply src/dataflow/src/source/file.rs:237]: 👍🏻

File: src/dataflow/src/source/file.rs (hunk 1 above)
Comment (cirego) [reply src/dataflow/src/source/file.rs:303]: Hi Philip, it looks like it's a real pain to add this context back into the error message in a way that is printed by our current error handling. I believe I know how to have this error message printed, but it requires updating tests that read error messages. I'm going to file a bug to track getting this error message printed correctly.

Comment (philip-stoev) [reply src/dataflow/src/source/file.rs:303]: @cirego No problem, thanks for opening the new ticket.
