### PR TITLE
Remove panic from reduce collation

### LINKED ISSUE #15496: MZ stopped suddenly after submitting queries
### What version of Materialize are you using?

v0.26.4

### How did you install Materialize?

APT package

### What is the issue?

I'm using MZ as linux systemd service and consuming debezium envelope sources. I submitted some queries in Materialize to my materialized views. Suddenly, service stopped. Syslogs output can be found below. There were some personal data, so I replaced them with XXXXX and YYYYY

### Relevant log output

```source
2022-10-18T08:45:40.975210Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("XXXXXXXXXXXXXX")]}, 224484257)#011value: [Row{[Int64(18149279)]}, Row{[Int64(18149279)]}]#011count: -1
2022-10-18T08:45:40.977636Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("YYYYYYYYYYYYYY")]}, 109985839)#011value: [Row{[Int64(18080830)]}, Row{[Int64(18080830)]}]#011count: -1
2022-10-18T08:45:40.996350Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("XXXXXXXXXXXXXX")]}, 6380449)#011value: [Row{[Int64(18149279)]}, Row{[Int64(18149279)]}]#011count: -1
2022-10-18T08:45:40.997029Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("YYYYYYYYYYYYYY")]}, 9322543)#011value: [Row{[Int64(18080830)]}, Row{[Int64(18080830)]}]#011count: -1
2022-10-18T08:45:41.003159Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("XXXXXXXXXXXXXX")]}, 88993)#011value: [Row{[Int64(18149279)]}, Row{[Int64(18149279)]}]#011count: -1
2022-10-18T08:45:41.003812Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("YYYYYYYYYYYYYY")]}, 933935)#011value: [Row{[Int64(18080830)]}, Row{[Int64(18080830)]}]#011count: -1
2022-10-18T08:45:41.013893Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("XXXXXXXXXXXXXX")]}, 23457)#011value: [Row{[Int64(18149279)]}, Row{[Int64(18149279)]}]#011count: -1
2022-10-18T08:45:41.014682Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("YYYYYYYYYYYYYY")]}, 16431)#011value: [Row{[Int64(18080830)]}, Row{[Int64(18080830)]}]#011count: -1
2022-10-18T08:45:41.018395Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("XXXXXXXXXXXXXX")]}, 2977)#011value: [Row{[Int64(18149279)]}, Row{[Int64(18149279)]}]#011count: -1
2022-10-18T08:45:41.019040Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("YYYYYYYYYYYYYY")]}, 47)#011value: [Row{[Int64(18080830)]}, Row{[Int64(18080830)]}]#011count: -1
2022-10-18T08:45:41.021987Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("XXXXXXXXXXXXXX")]}, 161)#011value: [Row{[Int64(18149279)]}, Row{[Int64(18149279)]}]#011count: -1
2022-10-18T08:45:41.022661Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("YYYYYYYYYYYYYY")]}, 47)#011value: [Row{[Int64(18080830)]}, Row{[Int64(18080830)]}]#011count: -1
2022-10-18T08:45:41.024761Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("XXXXXXXXXXXXXX")]}, 1)#011value: [Row{[Int64(18149279)]}, Row{[Int64(18149279)]}]#011count: -1
2022-10-18T08:45:41.025384Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("YYYYYYYYYYYYYY")]}, 15)#011value: [Row{[Int64(18080830)]}, Row{[Int64(18080830)]}]#011count: -1
2022-10-18T08:45:41.026985Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Negative accumulation in ReduceMinsMaxes: [Row{[Int64(18149279)]}, Row{[Int64(18149279)]}] with count -1
2022-10-18T08:45:41.027870Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Negative accumulation in ReduceMinsMaxes: [Row{[Int64(18080830)]}, Row{[Int64(18080830)]}] with count -1
2022-10-18T08:45:43.735913Z ERROR panic: called `Option::unwrap()` on a `None` value
thread: timely:work-0
location: src/dataflow/src/compute/render/reduce.rs:346:65
version: 0.26.5 (8d61044d9fa2ae92e74fca378b6cd7e34dd5ed7e)
backtrace:
   0: materialized::handle_panic
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033030de59e0a1b31-1/materialize/tests/src/materialized/src/bin/materialized/main.rs:1010:21
   1: core::ops::function::Fn::call
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:70:5
   2: std::panicking::rust_panic_with_hook
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:610:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:500:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
   5: rust_begin_unwind
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   6: core::panicking::panic_fmt
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   7: core::panicking::panic
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:48:5
   8: mz_dataflow::compute::render::reduce::build_collation::{{closure}}
      differential_dataflow::operators::reduce::ReduceCore::reduce_abelian::{{closure}}
             at cargo/git/checkouts/differential-dataflow-d065d23d797aa027/27492f2/src/operators/reduce.rs:291:21
      <differential_dataflow::operators::reduce::history_replay::HistoryReplayer<V1,V2,T,R1,R2> as differential_dataflow::operators::reduce::PerKeyCompute<V1,V2,T,R1,R2>>::compute
             at cargo/git/checkouts/differential-dataflow-d065d23d797aa027/27492f2/src/operators/reduce.rs:946:29
   9: <differential_dataflow::operators::arrange::arrangement::Arranged<G,T1> as differential_dataflow::operators::reduce::ReduceCore<G,K,V,R>>::reduce_core::{{closure}}::{{closure}}
             at cargo/git/checkouts/differential-dataflow-d065d23d797aa027/27492f2/src/operators/reduce.rs:538:49
  10: <timely::dataflow::stream::StreamCore<G,D1> as timely::dataflow::operators::generic::operator::Operator<G,D1>>::unary_frontier::{{closure}}::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/dataflow/operators/generic/operator.rs:351:17
      timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/dataflow/operators/generic/builder_rc.rs:123:31
      timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/dataflow/operators/generic/builder_rc.rs:162:26
      <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/dataflow/operators/generic/builder_raw.rs:204:9
  11: timely::progress::subgraph::PerOperatorState<T>::schedule
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/progress/subgraph.rs:684:30
  12: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/progress/subgraph.rs:344:26
      <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/progress/subgraph.rs:310:17
  13: timely::progress::subgraph::PerOperatorState<T>::schedule
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/progress/subgraph.rs:684:30
  14: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/progress/subgraph.rs:344:26
      <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/progress/subgraph.rs:310:17
  15: timely::worker::Wrapper::step::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/worker.rs:754:57
      core::option::Option<T>::map
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/option.rs:883:29
      timely::worker::Wrapper::step
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/worker.rs:754:26
  16: timely::worker::Worker<A>::step_or_park
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/worker.rs:396:38
  17: mz_dataflow::server::Worker<A,SC,CR>::run
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033030de59e0a1b31-1/materialize/tests/src/dataflow/src/server.rs:297:13
  18: mz_dataflow::server::serve_boundary::{{closure}}
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033030de59e0a1b31-1/materialize/tests/src/dataflow/src/server.rs:175:9
      timely::execute::execute::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/execute.rs:287:22
      timely_communication::initialize::initialize_from::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/communication/src/initialize.rs:316:33
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:123:18
  19: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/mod.rs:477:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
      std::panicking::try
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
      std::panic::catch_unwind
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
      std::thread::Builder::spawn_unchecked::{{closure}}
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/mod.rs:476:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
  20: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/boxed.rs:1854:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/boxed.rs:1854:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys/unix/thread.rs:108:17
  21: <unknown>
  22: <unknown>
materialized encountered an internal error and crashed.
We rely on bug reports to diagnose and fix these errors. Please
copy and paste the above details and file a report at:
    https://materialize.com/s/bug
```

### PR DESCRIPTION
**Pull request by vmarcos**
This PR removes the panic call in the rendering of a reduce collation, which would be triggered if wrong input data were presented to the collation reduction operator. Instead, the strategy now adopted makes the reduce collation behave like other aggregates currently do: Upon being presented invalid accumulations or data, the operator reports an error to the logs and produces best-effort query results by ignoring the invalid input data.

The PR also includes a regression test for the panic, which checks the logs of the compute replica for an appropriate error. To make the regression test ignore soft assertions, however, it was necessary to make an adaptation to the service configuration in the testing framework.

Fixes #15496.

### Motivation

  * This PR fixes a recognized bug. https://github.com/MaterializeInc/materialize/issues/15496

### Tips for reviewer

Note that this PR is not intended to resolve the ongoing discussion of how to handle invalid accumulations in reductions ([Slack thread](https://materializeinc.slack.com/archives/CM7ATT65S/p1675355385487949), [tracking issue](https://github.com/MaterializeInc/materialize/issues/17178)). Rather, the PR addresses inconsistent behavior in the rendering of a reduce collation and the rendering of other aggregates, which log errors and suppress invalid data instead of causing a crash. Additionally, there seems to be some consensus that avoiding panics in these situations is desirable. 

Note that the code now tries to protect against the following: (a) Negative multiplicities; (b) Mismatched numbers or types of aggregates presented to the collation; (c) Rows that contain more aggregate values than requested by the reduce collation. When these conditions are observed, errors are logged and output is not produced. 

Note that this PR gets the behavior of the reduce collation to match more closely the join semantics advocated in PR https://github.com/MaterializeInc/materialize/pull/17013. Until we remove the reduce collation, however, fixing the present code seems to be an appropriate interim measure.

I would suggest omitting whitespace when looking at the changes.

The test scenario is the repro in https://github.com/MaterializeInc/materialize/issues/15496#issuecomment-1415766444.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
  A test has been added to validate the absence of the previous panic.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
N/A
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note): N/A

### CODE REVIEW

File: src/compute/src/render/reduce.rs [hunk 1]
```diff
@@ -345,42 +352,69 @@ where
...
-                for ((reduction_type, row), _) in input.iter() {
-                    match reduction_type {
-                        ReductionType::Accumulable => {
-                            accumulable = row.iter();
-                        }
-                        ReductionType::Hierarchical => {
-                            hierarchical = row.iter();
+                if input.iter().any(|(_val, cnt)| cnt < &0) {
+                    for (val, cnt) in input.iter() {
+                        // XXX: This reports user data, which we perhaps should not do!
```
Comment (aalexandrov) [inline src/compute/src/render/reduce.rs:357]: nit: maybe ping @ggnall regarding that...

File: misc/python/materialize/mzcompose/services.py [hunk 2]
```diff
@@ -170,10 +170,16 @@ def __init__(
     ) -> None:
         environment = [
             "CLUSTERD_LOG_FILTER",
-            "MZ_SOFT_ASSERTIONS=1",
```
Comment (aalexandrov) [inline misc/python/materialize/mzcompose/services.py:173]: IIRC the environment variables are defined in that order, meaning that you can just keep 
```bash
MZ_SOFT_ASSERTIONS=1
```
here and override with
```
MZ_SOFT_ASSERTIONS=0
```
in `environment_extra`. For example, see how the `replica-isolation` test overrides the `CLUSTERD_LOG_FILTER`.

File: misc/python/materialize/mzcompose/services.py [hunk 3]
```diff
@@ -170,10 +170,16 @@ def __init__(
...
             *environment_extra,
         ]
 
+        # check if environment_extra contains override for MZ_SOFT_ASSERTIONS
```
Comment (aalexandrov) [inline misc/python/materialize/mzcompose/services.py:176]: I don't think that these extra lines are needed (see my comment above).

File: test/cluster/regression/github-15496.td [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+> INSERT INTO base VALUES (1, 1);
+
+> INSERT INTO base VALUES (1, -1), (1, -1);
+
+# Run a query that would generate a panic before the fix. Note that
+# we expect the query to succeed for now, but follow-up work might
+# eventually lead us to favor a SQL-level error for such a query, as
+# tracked by https://github.com/MaterializeInc/materialize/issues/17178
+> SELECT SUM(data), MAX(data) FROM data;
+<null> <null>
```
Comment (aalexandrov) [inline test/cluster/regression/github-15496.td:29]: Is the best-effort handling of aggregate now going to introduce `null` values in places where before those were not possible (for example `SELECT SUM(y) FROM t GROUP BY x`)?

File: test/cluster/regression/github-15496.td [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+#
+# As of the Change Date specified in that file, in accordance with
+# the Business Source License, use of this software will be governed
+# by the Apache License, Version 2.0.
+
+# Regression test for https://github.com/MaterializeInc/materialize/issues/15496
+# This test is special in that it requires MZ_SOFT_ASSERTIONS=0 at present.
+
+# Set data for test up
+> SET cluster = cluster1;
```
Comment (aalexandrov) [inline test/cluster/regression/github-15496.td:14]: This file is not self-contained because `cluster1` is created in the enclosing test. It might be better to just run the 6 statements directly from the python file as the other `workflow_test_github_~` do. 

```python
c.testdrive(
    dedent(
        f"""
        # Set data for test up
        > SET cluster = cluster1;
        
        > CREATE TABLE base (data bigint, diff bigint);
        
        // ...
        """
    )
)
```

**Review by aalexandrov — CHANGES_REQUESTED** [review]
Some minor comments regarding the test org...

File: misc/python/materialize/mzcompose/services.py (hunk 2 above)
Comment (vmarcos) [reply misc/python/materialize/mzcompose/services.py]: Sounds great, thanks!

File: test/cluster/regression/github-15496.td (hunk 5 above)
Comment (vmarcos) [reply test/cluster/regression/github-15496.td]: Cool, revised.

**Review by teskje — APPROVED** [review]
LGTM!

File: test/cluster/regression/github-15496.td (hunk 4 above)
Comment (vmarcos) [reply test/cluster/regression/github-15496.td]: Outside of the reduce collation, the behavior was already to avoid outputting when we had negative accumulations. Here is the handling in hierarchical aggregates: https://github.com/MaterializeInc/materialize/blob/0cf899f8358c7daa19d5fa146b1c6c220f4a18e2/src/compute/src/render/reduce.rs#L613 as well as https://github.com/MaterializeInc/materialize/blob/0cf899f8358c7daa19d5fa146b1c6c220f4a18e2/src/compute/src/render/reduce.rs#L660

And here is the handing in basic aggregates: https://github.com/MaterializeInc/materialize/blob/0cf899f8358c7daa19d5fa146b1c6c220f4a18e2/src/compute/src/render/reduce.rs#L530

So AFAICT the change is transforming a crash into eliminating output, and only in the case of reduce collations.

File: src/compute/src/render/reduce.rs (hunk 1 above)
Comment (vmarcos) [reply src/compute/src/render/reduce.rs:357]: @ggnall To clarify, the behavior to output customer data to Sentry in the case of invalid accumulations in reductions is something that was introduced long before this PR. So this PR does not change this situation. The extra logging was requested since it is pretty hard to track these errors down when they do occur. The Slack thread for reference is [this one](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1670493167314799).

Fixing the approach taken in `src/compute/src/render/reduce.rs` is the subject of epic #17178. It is not straightforward to come up with a solution, but my personal preference would be to convert these error logs into SQL-level errors (design doc forthcoming).

**Review by philip-stoev — APPROVED** [review]
Thank you, the test looks good.

File: src/compute/src/render/reduce.rs (hunk 1 above)
Comment (philip-stoev) [reply src/compute/src/render/reduce.rs:357]: Regarding the reporting of user data, see discussion at https://materializeinc.slack.com/archives/CM7ATT65S/p1668169080723029
