### PR TITLE
Fix compute reconciliation by better as_of selection

### LINKED ISSUE #17594: Compute reconciliation is not efficient
### What version of Materialize are you using?

main

### How did you install Materialize?

Built from source

### What is the issue?

The metrics added in #17576 show that compute reconciliation caused by environmentd restarting fails to fulfill its intended purpose currently: (almost?) all existing dataflows are dropped and re-created during reconciliation, even though it should be possible to reuse them.

### Reproduction

The issue can be reproduced on staging by:

1. Installing some dataflows (indexes, materialized views) in a cluster.
2. Killing the environmentd pod, causing the orchestrator to restart it.
3. Checking the `mz_compute_reconciliation_*` metrics.

The metrics will show that (most?) dataflows are replaced instead of reused.

I think it might be possible for reconciliation to work correctly in rare cases, hence my parenthetical use of modifiers above.

### Diagnosis

I haven't checked this yet, but I strongly suspect that this issue is caused by our selection of dataflow `as_of`s during coordinator bootstrap.

* For indexes, we choose the least valid read time (i.e. the maximum/join of `since`s) of all input collections: https://github.com/MaterializeInc/materialize/blob/4fade0a936c32ca511a3a4d2306b3fc493c1539d/src/adapter/src/coord/dataflows.rs#L238
* For materialized views, we do the same: https://github.com/MaterializeInc/materialize/blob/4fade0a936c32ca511a3a4d2306b3fc493c1539d/src/adapter/src/coord.rs#L831

These least valid read times are ultimately informed by the `since`s of persist shards the dataflows read from, because these are the only `since`s we persist durably. So a dataflow's `as_of` is selected to be the join of the `since`s of all persist shards that feed the dataflow.

Storage delays compaction of persist shards to reduce communication overhead. Which means that when the compute controller tells the storage controller that compacting an input storage collection is allowed, the advancement of the underlying persist shard's `since` can be delayed. On the other hand, the compute replicas are informed about allowed compaction immediately (via the `AllowCompaction` command).

Assume that a replica maintains an index `D` reading from a persist shard `S`. `D` has been compacted to time `t2`, whereas `S` has only been compacted to `t1` (with `t1 < t2`) due to the compaction rate limiting mentioned above. Now environmentd restarts but the replica does not. The coordinator performs bootstrapping, as part of which it instructs the compute controller to create a dataflow `D'` with the same definition as `D` but an `as_of` of `t1`. The compute controller sends that dataflow description to the replica, which performs reconciliation. During reconciliation, the replica checks if its existing dataflow `D` is compatible with `D'` and can therefore be reused. It notices that `D`'s `as_of` (`t2`) is beyond `D'`'s `as_of` (`t1`) and [consequently decides that `D` cannot be used in place of `D'`](https://github.com/MaterializeInc/materialize/blob/4fade0a936c32ca511a3a4d2306b3fc493c1539d/src/compute-client/src/types/dataflows.rs#L294-L295). So it drops `D` and creates a new dataflow instead.

### Fixes

Assuming the above diagnosis is correct, the fundamental issue is that after an environmentd restart the replica is instructed to re-create a dataflow with an `as_of` that is before the frontier the dataflow has already been allowed to compact to. The issue can therefore be solved by ensuring that the compute controller always re-creates dataflows with `as_of`s that are beyond the frontiers these dataflows have been allowed to compact to previously.

One option is having the compute controller durably store information about previous compaction commands it has sent, and use that information on a restart to inform dataflow `as_of`s. This is part of what [compute command durability](#13222) would provide.

It is currently not clear if and how we want to implement durability in the compute controller. In the interest of fixing reconciliation in a timely manner, we could alternatively adjust the coordinators' bootstrapping to use the minimum/meet of `upper`s (rather than the maximum/join of `since`s) of all input collections when selecting `as_of`s for compute dataflows. These frontiers should always be beyond the what we allowed compaction to before the restart, assuming that we allow compaction only up to the current `upper`.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by teskje**
This PR makes compute reconciliation efficient again by using a different strategy for selecting `as_of` frontiers during dataflow bootstrapping. Instead of always choosing the least possible frontier, we now attempt to choose one that we think should be greater or equal to how far the previous incarnation of the compute controller could have the replicas allowed to compact their indexes/MVs. We have to be careful to not advance the `as_of` too far, since that would either produce outputs at incorrect times (for MVs) or unnecessarily delay the time at which an index becomes readable.

In the compute controller, we now have to install per-replica read holds differently when creating a dataflow, since we can't rely on the fact anymore that the `as_of` is early enough to hold back compaction sufficiently for all running replicas that might already have the dataflow installed. The strategy we choose here is to install per-replica read holds at the join of all input `since`s. This is a good change to make regardless of the adapter change, since it makes the compute controller stop depending on an implicit assumption about how dataflow `as_of`s are selected by its clients.

See https://github.com/MaterializeInc/materialize/issues/17594#issuecomment-1451681483 for more discussion about the strategy chosen here.

### Motivation

  * This PR fixes a recognized bug.

Fixes #17594.

### Tips for reviewer

Look at the commit separately!

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - N/A

### CODE REVIEW

**Comment by teskje** [comment]
Nightlies run: https://buildkite.com/materialize/nightlies/builds/2991

File: src/adapter/src/coord.rs [hunk 1]
```diff
@@ -1487,6 +1495,77 @@ impl Coordinator {
...
+            .sink_exports
+            .keys()
+            .exactly_one()
+            .expect("MV dataflow must export a sink");
+        let write_frontier = &self
+            .controller
+            .storage
+            .collection(*sink_id)
+            .expect("storage collection must exist")
+            .write_frontier;
```
Comment (antiguru) [inline src/adapter/src/coord.rs:1560]: This seems to be very similar to `least_valid_write` with an `id_bundle` of `sink_id`. Might use it to avoid code duplication?

File: src/adapter/src/coord.rs [hunk 2]
```diff
@@ -1487,6 +1495,77 @@ impl Coordinator {
...
+    ) -> Antichain<Timestamp> {
+        // All inputs must be readable at the chosen `as_of`, so it must be at least the join of
+        // the `since`s of all dependencies.
+        let storage_ids = dataflow.source_imports.keys().copied().collect();
+        let compute_ids = dataflow.index_imports.keys().copied().collect();
+        let id_bundle = CollectionIdBundle {
+            storage_ids,
+            compute_ids: btreemap! {cluster_id => compute_ids},
+        };
+        let mut as_of = self.least_valid_read(&id_bundle);
```
Comment (antiguru) [inline src/adapter/src/coord.rs:1512]: Some parts of the `bootstrap_*_as_of` functions are shared, which seems like a good opportunity to factor it out?

File: src/adapter/src/coord.rs [hunk 3]
```diff
@@ -1487,6 +1495,77 @@ impl Coordinator {
...
+
+        // For compute reconciliation to recognize that an existing dataflow can be reused, we want
+        // to advance the `as_of` far enough that it is beyond the `as_of`s of all dataflows that
+        // might still be installed on replicas, but ideally not much farther as that would just
+        // increase the wait time until the index becomes readable. We advance the `as_of` to the
+        // meet of the `upper`s of all dependencies, as we know that no replica can have produced
+        // output for that time, so we can assume that no replica `as_of` has been adanced beyond
+        // this time either.
+        let write_frontier = self.least_valid_write(&id_bundle);
+        // Things go wrong if we try to create a dataflow with `as_of = []`, so avoid that.
```
Comment (antiguru) [inline src/adapter/src/coord.rs:1522]: Not sure if this is the right place to mention it, but what confused me more than once is which objects have a `[]` write frontier. The answer seems to be constant collections.

**Review by antiguru — APPROVED** [review]
This looks great! I left some nits, but overall I think we should go ahead and merge it.

File: src/adapter/src/coord.rs (hunk 1 above)
Comment (teskje) [reply src/adapter/src/coord.rs:1560]: That would turn out like this:
```rust
        let sink_id = dataflow
            .sink_exports
            .keys()
            .exactly_one()
            .expect("MV dataflow must export a sink");
        let id_bundle = CollectionIdBundle {
            storage_ids: [*sink_id].into(),
            compute_ids: Default::default(),
        };
        let write_frontier = self.least_valid_write(&id_bundle);
```

I think this is less obvious than getting the write frontier from the storage controller directly.

However, looking at `least_valid_write` I realized that I can get the storage frontier using `self.storage_write_frontier(*sink_id)`, which is indeed nicer!

File: src/adapter/src/coord.rs (hunk 3 above)
Comment (teskje) [reply src/adapter/src/coord.rs:1522]: Constant collections are one example. Another are load generator sources that produce a bunch of data and then shut down (I think TPC-H does this). There might be other cases now or in the future, so it's hard to come up with and exhaustive enumeration that isn't at the risk of becoming outdated.

File: src/adapter/src/coord.rs (hunk 2 above)
Comment (teskje) [reply src/adapter/src/coord.rs:1512]: I copied this code from `finalize_dataflow`, so there is certainly a refactoring opportunity here!

File: src/adapter/src/coord.rs (hunk 3 above)
Comment (antiguru) [reply src/adapter/src/coord.rs:1518]: Thanks for the explanation!

**Review by vmarcos — APPROVED** [review]
LGTM!

**Review by mjibson — APPROVED** [review]
