### PR TITLE
adapter: drop linked cluster if sink fails to create

### LINKED ISSUE #17061: regression: implicitly-created cluster left behind after a failed CREATE SINK statement; environmentd panic when attempting to DROP it
### What version of Materialize are you using?

 v0.40.0-dev (4b8e18e75)

### How did you install Materialize?

Docker image

### What is the issue?

The `kafka-sink-errors.td` attempts to create various sinks and expect them to fail. In particular, it does:

```
! CREATE SINK invalid_acks FROM v1
  INTO KAFKA CONNECTION kafka_conn (ACKS = foo, TOPIC 'testdrive-kafka-sink-errors-${testdrive.seed}')
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY CONNECTION csr_conn
  ENVELOPE DEBEZIUM
contains:Invalid value for configuration property "request.required.acks" acks foo
```

The problem is that the implicitly-created cluster that was created to serve this sink was left behind:

```
materialize=> show clusters;
              name               
---------------------------------
 default
 materialize_public_invalid_acks <- HERE
 mz_introspection
 mz_system
(4 rows)
```

and yet the sink , as expected, does not really exist:

```
materialize=> show sinks;
 name | type | size 
------+------+------
(0 rows)
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by benesch**
If a sink fails to create in the external system (e.g., because the Kafka broker rejects the topic configuration), we need to remove both the sink *and* the linked cluster associated with the sink. Teach the sink cleanup code path to handle this.

Fix #17061.

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a
  companion cloud PR to account for those changes that is tagged with
  the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - n/a (bug was never released)

### CODE REVIEW

**Review by philip-stoev — APPROVED** [review]
Thank you for the test!

**Comment by philip-stoev** [comment]
Do we care to also not panic on the "no entry found for key", even if it is not expected to happen any longer? Seems like an error that could be propagated back to the SQL user instead.

**Comment by benesch** [comment]
> Do we care to also not panic on the "no entry found for key", even if it is not expected to happen any longer? Seems like an error that could be propagated back to the SQL user instead.

It's very difficult to prevent. The catalog ended up in an inconsistent state as a result of this bug. There are number of APIs that panic on that inconsistent state. In theory they could all be APIs that returned errors rather than panicking, but that would be a major refactor.

**Review by guswynn — APPROVED** [review]
Looks good to me!

File: src/adapter/src/coord/message_handler.rs [hunk 1]
```diff
@@ -465,9 +465,10 @@ impl<S: Append + 'static> Coordinator<S> {
             Err(e) => {
                 // Drop the placeholder sink if still present.
                 if self.catalog.try_get_entry(&id).is_some() {
+                    let ops = self.catalog.drop_items_ops(&[id]);
```
Comment (guswynn) [inline src/adapter/src/coord/message_handler.rs:468]: Its important to note that the sink _uses_ an underlying connection, whereas cascading here drops anything that are _used_by_ the sink....which is nothing because it does not yet exist; This allows us to drop the sink and the cluster;

However, if we crash/restart before we actually run this code, i think we will still leak some objects and/or a cluster; definitely a followup here, but there is probably no way to cleanup transactionally?
