### PR TITLE
sql: fix CREATE OR REPLACE VIEW bug

### LINKED ISSUE #5272: "corrupt catalog: failed to deserialize item" after creating a circular view with CREATE OR REPLACE VIEW
### What version of Materialize are you using?

```
$ materialized -v
materialized v0.6.0 (9ed7c170f)
```

### How did you install Materialize?

* [ ] Linux release tarball

### What was the issue?

Using CREATE OR REPLACE VIEW, one can create a circular view dependency. This causes immediate panic:

```
Jan 12 11:07:35.947 ERROR panic: <unnamed>: Catalog: missing dependent catalog item u5 while installing philips.public.v1
   0: materialized::handle_panic
             at /var/lib/buildkite-agent/builds/buildkite-builders-i-0a30a3e1288ddae4e-1/materialize/tests/src/materialized/src/bin/materialized/main.rs:544:65
   1: core::ops::function::Fn::call
             at /usr/local/lib/rustlib/src/rust/library/core/src/ops/function.rs:70:5
   2: std::panicking::rust_panic_with_hook
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:581:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484:9
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153:18
   5: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483:5
   6: std::panicking::begin_panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437:5
   7: coord::catalog::Catalog::insert_item
             at /var/lib/buildkite-agent/builds/buildkite-builders-i-0a30a3e1288ddae4e-1/materialize/tests/src/coord/src/catalog.rs:865:25
   8: coord::catalog::Catalog::transact::{{closure}}
             at /var/lib/buildkite-agent/builds/buildkite-builders-i-0a30a3e1288ddae4e-1/materialize/tests/src/coord/src/catalog.rs:1275:22
   9: core::iter::adapters::map_fold::{{closure}}
             at /usr/local/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:905:28
      core::iter::traits::iterator::Iterator::fold
             at /usr/local/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2023:21
      <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /usr/local/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:945:9
  10: core::iter::traits::iterator::Iterator::for_each
             at /usr/local/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:678:9
      <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend
             at /usr/local/lib/rustlib/src/rust/library/alloc/src/vec.rs:2378:17
      <alloc::vec::Vec<T> as alloc::vec::SpecFromIterNested<T,I>>::from_iter
             at /usr/local/lib/rustlib/src/rust/library/alloc/src/vec.rs:2152:9
      <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
             at /usr/local/lib/rustlib/src/rust/library/alloc/src/vec.rs:2267:20
      <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /usr/local/lib/rustlib/src/rust/library/alloc/src/vec.rs:2002:9
      core::iter::traits::iterator::Iterator::collect
             at /usr/local/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1670:9
      coord::catalog::Catalog::transact
             at /var/lib/buildkite-agent/builds/buildkite-builders-i-0a30a3e1288ddae4e-1/materialize/tests/src/coord/src/catalog.rs:1225:12
  11: coord::coord::Coordinator<C>::catalog_transact::{{closure}}
             at /var/lib/buildkite-agent/builds/buildkite-builders-i-0a30a3e1288ddae4e-1/materialize/tests/src/coord/src/coord.rs:2444:22
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /usr/local/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  12: coord::coord::Coordinator<C>::sequence_create_view::{{closure}}
             at /var/lib/buildkite-agent/builds/buildkite-builders-i-0a30a3e1288ddae4e-1/materialize/tests/src/coord/src/coord.rs:1757:15
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /usr/local/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
      coord::coord::Coordinator<C>::sequence_plan::{{closure}}
             at /var/lib/buildkite-agent/builds/buildkite-builders-i-0a30a3e1288ddae4e-1/materialize/tests/src/coord/src/coord.rs:1308:17
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /usr/local/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
      coord::coord::Coordinator<C>::serve::{{closure}}
             at /var/lib/buildkite-agent/builds/buildkite-builders-i-0a30a3e1288ddae4e-1/materialize/tests/src/coord/src/coord.rs:495:25
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /usr/local/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
      tokio::runtime::enter::Enter::block_on::{{closure}}
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/enter.rs:160:58
      tokio::coop::with_budget::{{closure}}
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:127:9
      std::thread::local::LocalKey<T>::try_with
             at /usr/local/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
      std::thread::local::LocalKey<T>::with
             at /usr/local/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
      tokio::coop::with_budget
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:120:5
      tokio::coop::budget
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:96:5
      tokio::runtime::enter::Enter::block_on
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/enter.rs:160:35
  15: tokio::runtime::handle::Handle::block_on::{{closure}}
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:277:17
      tokio::runtime::context::enter
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/context.rs:72:5
  16: tokio::runtime::handle::Handle::enter
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:76:9
      tokio::runtime::handle::Handle::block_on
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:275:13
      coord::coord::serve::{{closure}}::{{closure}}
             at /var/lib/buildkite-agent/builds/buildkite-builders-i-0a30a3e1288ddae4e-1/materialize/tests/src/coord/src/coord.rs:3068:21
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /usr/local/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137:18
  17: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /usr/local/lib/rustlib/src/rust/library/std/src/thread/mod.rs:464:17
      <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /usr/local/lib/rustlib/src/rust/library/std/src/panic.rs:308:9
      std::panicking::try::do_call
             at /usr/local/lib/rustlib/src/rust/library/std/src/panicking.rs:381:40
      std::panicking::try
             at /usr/local/lib/rustlib/src/rust/library/std/src/panicking.rs:345:19
      std::panic::catch_unwind
             at /usr/local/lib/rustlib/src/rust/library/std/src/panic.rs:382:14
      std::thread::Builder::spawn_unchecked::{{closure}}
             at /usr/local/lib/rustlib/src/rust/library/std/src/thread/mod.rs:463:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /usr/local/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  18: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042:9
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/unix/thread.rs:87:17
  19: start_thread
  20: __clone
```
Followed by an inability to restart:

```
materialized: corrupt catalog: failed to deserialize item u7 (philips.public.v1): unknown catalog item 'philips.public.v1'
```

### Is the issue reproducible? If so, please provide reproduction instructions.
```
create table t1 (f1 integer);
create materialized view v1 as select * from t1;
create or replace materialized view v1 as select * from v1;

server closed the connection unexpectedly
```

### PR DESCRIPTION
**Pull request by JLDLaughlin**
Fixes #5272.

A user found that views created by `CREATE OR REPLACE VIEW` statements
are currently able to depend on the view that is about to be dropped.

The fix is to check during planning if the new view is attempting to
depend on the view that is about to be dropped, and throw an error if
so.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5380)

### CODE REVIEW

**Comment by JLDLaughlin** [comment]
Just as a note, this also fails in Postgres:
```
jessicalaughlin=# create view v1 as select 1;
CREATE VIEW
jessicalaughlin=# create or replace view v1 as select * from v1;
CREATE VIEW
jessicalaughlin=# select * from v1;
ERROR:  infinite recursion detected in rules for relation "v1"
```

(I still think we should fix it)

File: src/sql/src/plan/statement/ddl.rs [hunk 1]
```diff
@@ -712,8 +712,21 @@ pub fn plan_create_view(
...
+        query::plan_root_query(scx, query.clone(), QueryLifetime::Static)?;
+    relation_expr.bind_parameters(&params)?;
+    //TODO: materialize#724 - persist finishing information with the view?
+    relation_expr.finish(finishing);
+    let relation_expr = relation_expr.decorrelate();
     let replace = if *if_exists == IfExistsBehavior::Replace {
         if let Ok(item) = scx.catalog.resolve_item(&name.clone().into()) {
+            if relation_expr.global_uses().contains(&item.id()) {
+                bail!(
+                    "cannot replace {0}view {1}: depended upon by new {1} definition",
```
Comment (sploiselle) [inline src/sql/src/plan/statement/ddl.rs:725]: useless, but are the positional references in the format string necessary here?

File: src/sql/src/plan/statement/ddl.rs [hunk 2]
```diff
@@ -712,8 +712,21 @@ pub fn plan_create_view(
     } else {
         scx.allocate_name(normalize::object_name(name.to_owned())?)
     };
+    let (mut relation_expr, mut desc, finishing) =
+        query::plan_root_query(scx, query.clone(), QueryLifetime::Static)?;
+    relation_expr.bind_parameters(&params)?;
+    //TODO: materialize#724 - persist finishing information with the view?
+    relation_expr.finish(finishing);
+    let relation_expr = relation_expr.decorrelate();
```
Comment (sploiselle) [inline src/sql/src/plan/statement/ddl.rs:720]: Could `let relation_expr = relation_expr.decorrelate();` be moved after the `replace` check? I don't know if it impacts the `global_uses`, but if not, it'll give the user an error a fraction of a second more quickly.

File: doc/user/content/release-notes.md [hunk 3]
```diff
@@ -51,6 +51,12 @@ Wrap your release notes at the 80 character mark.
 - Commit consumed offsets to Kafka to facilitate source ingest progress
   monitoring.
 
+- Fix a bug that would cause `DROP` statements targeting multiple objects to fail
+  when those objects had dependent objects in common {{% gh 5316 %}}.
+
+- Fix a bug that would allow `CREATE OR REPLACE` statements to create dependencies
```
Comment (sploiselle) [inline doc/user/content/release-notes.md:57]: For variety, this could be rephrased to start with `Prevent...`––totally optional!

**Review by sploiselle — APPROVED** [review]

File: src/sql/src/plan/statement/ddl.rs (hunk 1 above)
Comment (benesch) [reply src/sql/src/plan/statement/ddl.rs:725]: (They allow you to refer to `item.name()` twice despite providing it as an argument just once.)

File: src/sql/src/plan/statement/ddl.rs [hunk 4]
```diff
@@ -712,8 +712,21 @@ pub fn plan_create_view(
...
     let replace = if *if_exists == IfExistsBehavior::Replace {
         if let Ok(item) = scx.catalog.resolve_item(&name.clone().into()) {
+            if relation_expr.global_uses().contains(&item.id()) {
+                bail!(
+                    "cannot replace {0}view {1}: depended upon by new {1} definition",
+                    if *materialized { "materialized " } else { "" },
```
Comment (benesch) [inline src/sql/src/plan/statement/ddl.rs:726]: I would actually drop this bit of logic as you can call `CREATE OR REPLACE MATERIALIZED VIEW v` on a `v` that is not actually materialized, which will make this error message a little confusing. Arguably we should reject `CREATE OR REPLACE MATERIALIZED VIEW v` and force everyone through `CREATE OR REPLACE VIEW`, but possibly there are weird backwards compatibility implications there... not sure.

File: src/sql/src/plan/statement/ddl.rs (hunk 2 above)
Comment (benesch) [reply src/sql/src/plan/statement/ddl.rs:720]: Yeah, `global_uses` is only a thing on `::expr::RelationExpr`s.

**Review by benesch — APPROVED** [review]
🎉

File: src/sql/src/plan/statement/ddl.rs (hunk 1 above)
Comment (sploiselle) [reply src/sql/src/plan/statement/ddl.rs:725]: Oh derp, I skipped over the `{1}` in the middle there!
