### PR TITLE
sql: fix correctness bug in VOJ lowering

### LINKED ISSUE #26352: Wrong results with `enable_variadic_left_join_lowering`
### What version of Materialize are you using?

v0.95.0-dev (b9883d40a)

### What is the issue?

Dimension table NULL keys are currently not filtered filtered out. Here is a repro:

```sql
create table t(x int, y int);
create table d(x int, z int);

insert into t values (1, 5), (2, 7), (null, 8);
insert into d values (1, 9), (null, 2), (3, 4);

select * from t left join d as d1 on(t.x = d1.x) left join d as d2 on (t.x = d2.x);
```

In Materialize (wrong), this results in:
```text
 x | y | x | z | x | z 
---+---+---+---+---+---
 2 | 7 |   |   |   |  
   | 8 |   | 2 |   | 2
 1 | 5 | 1 | 9 | 1 | 9
```
and in Postgres (correct), in:
```text
 x | y | x | z | x | z 
---+---+---+---+---+---
 1 | 5 | 1 | 9 | 1 | 9
 2 | 7 |   |   |   |  
   | 8 |   |   |   |  
```

### PR DESCRIPTION
**Pull request by aalexandrov**
Fixes #26352

### Motivation

  * This PR fixes a recognized bug.

### Tips for reviewer

This fixes the bug by adding a `Filter (#c1 IS NOT NULL AND ... #cn IS NOT NULL)` filter on top of the `$A` and `$B` inputs  (which reference the `right` side) of the `augmented` value, which currently has the following structure:

```text
Union
  $A
  Map (<nulls>)
    Threshold
      Union
        Negate
          $B
        Distinct project=[<keys>]
          $C
```

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

File: src/sql/src/plan/lowering/variadic_left.rs [hunk 1]
```diff
@@ -255,12 +262,17 @@ pub(crate) fn attempt_left_join_magic(
             // so that after the join is done we can overwrite all values for `right` with null values.
             // This is a quirk of how outer joins work: the matched columns are left as null.
 
+            let aug_value = MirRelationExpr::union(
+                bindings[index + 1].1.clone().filter(
```
Comment (aalexandrov) [inline src/sql/src/plan/lowering/variadic_left.rs:266]: I feel like this can be simplified because `bindings[index + 1].1.clone()` will always be equal to `get_right` here, so one can probably already construct `get_right` to have the filter on top here

```rust
let get_right = MirRelationExpr::local_get(id, right_type.clone());
```

or sometime later, probably immediately after

```rust
let equations = if let Some(list) = decompose_equations(&on) {
    list
}
```

as it seems that `bindings` doesn't ever read the second position of the value tuple:

```rust
while let Some((id, _get, value)) = bindings.pop() {

}
```

**Review by frankmcsherry — APPROVED** [review]
Seems good to me, except it would help to add comments in the code explaining the rationale behind the lines (for some future clean-up). The comments are not generally great at the moment (I wrote a bunch of them), but no time to start like the present.
