### PR TITLE
sql: refactor Interval's duration to be i128

### LINKED ISSUE #2800: EXTRACT returns positive values for negative durations
How to reproduce:
```
materialize=> select EXTRACT(EPOCH from INTERVAL '-1' MINUTE);
 ?column? 
----------
       60
(1 row)

materialize=> select EXTRACT(MINUTE from INTERVAL '-1' MINUTE);
 ?column? 
----------
        1
(1 row)
```

In contrast, here are the PostgreSQL results:
```
andiwang=# select EXTRACT(EPOCH from INTERVAL '-1' MINUTE) from timetest;
 date_part 
-----------
       -60
(1 row)

andiwang=# select EXTRACT(MINUTE from INTERVAL '-1' MINUTE) from timetest;
 date_part 
-----------
        -1
(1 row)
```

### PR DESCRIPTION
**Pull request by sploiselle**
Per the conversation in #3151, I reimplemented `Interval`'s duration field as an
`i128`; this design greatly reduces the complexity of supporting negative
intervals in a way that plays nicely with all layers of Materialize.

### Caveats

Disregard what was here before: Frank found a fantastic workaround.

### Questions

- Should we be more principled in the length of duration we accept? I tried to
gate this by limiting `Interval::new` to accepting `i64`s for seconds and nanos,
but wasn't sure if we should make it harder to use more of the `i128` than we
reasonably expect users to, e.g. when creating `Intervals` directly.

- Avro encoding doesn't support ours or Postgres' intervas--no negative values, and the max number of days is only `u32`. I made some changes to ameliorate the differences but they seem a slightly intractable.
  - I found the Avro encoding, but where do these values get decoded into `Interval`?
- I also made a change to our PG encoding and decoding that--maybe!--improves their compatibility. Does this get tested anywhere?

### Misc.

- Removed duplicative implementation of `seconds_multiplier` in
  `repr/scalar/datetime.rs`
- @justinj 🤠

    ```
    materialize=> SELECT * from (values (interval '-1' day + interval '1' day)) union (values (interval '1' day + interval '-1' day));
     column1
    ----------
     00:00:00
    (1 row)
    ```

Closes #2800  #2812

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/3172)

### CODE REVIEW

**Comment by frankmcsherry** [comment]
> Namely chrono::Duration doesn't have an API that both accepts nanoseconds, and allows for more than i64 nanoseconds—even though we might have up to i128 of them.

Maybe silly, but what about something like
```rust
use chrono::Duration;
fn nanos_to_duration(nanos: i128) -> Duration {
    // TODO: use conversion other than `as`.
    let subsec_nanos = (nanos % 1000000000) as i64;
    let seconds = (nanos / 1000000000) as i64;
    Duration::nanoseconds(subsec_nanos) + Duration::seconds(seconds)
}
```

File: src/expr/scalar/func.rs [hunk 1]
```diff
@@ -583,30 +581,22 @@ fn add_date_interval<'a>(a: Datum<'a>, b: Datum<'a>) -> Datum<'a> {
...
-    let date = match chrono::Duration::from_std(interval.duration) {
-        Ok(d) => d,
-        Err(_) => return Datum::Null,
-    };
 
-    let time = if interval.is_positive_dur {
-        let (t, _) = time.overflowing_add_signed(date);
-        t
+    // TODO(sploiselle): Convert this into https://github.com/chronotope/chrono/pull/426
+    let dur = if interval.duration > std::i64::MAX as i128 {
```
Comment (frankmcsherry) [inline src/expr/scalar/func.rs:592]: Would this want to check `interval.duration < std::i64::MIN` also?

File: src/interchange/avro.rs [hunk 2]
```diff
@@ -929,12 +929,15 @@ impl Encoder {
...
                     ScalarType::Interval => Value::Fixed(12, {
                         let iv = datum.unwrap_interval();
                         let mut buf = Vec::with_capacity(12);
+                        let days = iv.days() as i128;
+                        let sub_day_ns = iv.duration % (days * 24 * 60 * 60 * 1_000_000_000);
                         buf.extend(&(iv.months as i32).to_le_bytes());
-                        buf.extend(&0i32.to_le_bytes());
-                        buf.extend(&(iv.duration.as_millis() as i32).to_le_bytes());
+                        buf.extend(&(days as i32).to_le_bytes());
+                        buf.extend(&((sub_day_ns / 1_000_000) as i32).to_le_bytes());
```
Comment (frankmcsherry) [inline src/interchange/avro.rs:940]: it seems possibly (locally, at least) that this could exceed an `i32` if `days` is large. I'm not sure what `days` is, but some notes on why this is all ok here would help me out!

**Comment by frankmcsherry** [comment]
There is a test in `row.rs` based on the `datum_size` method that I think we'll want to update. Specifically, it currently reads:
```
/// Number of bytes required by the datum.
///
/// This is used to optimistically pre-allocate buffers for packing rows.
pub fn datum_size(datum: &Datum) -> usize {
    match datum {
        ...
        Datum::Interval(_) => {
            1 + size_of::<i64>() + size_of::<u64>() + size_of::<u32>() + size_of::<bool>()
        }
        ...
    }
}
```
The test that tests this ... might be passing through crazy luck (maybe the size hasn't changed) but probably best to change this to a (I think)
```
        Datum::Interval(_) => {
            1 + size_of::<i64>() + size_of::<i128>()
        }
```

File: src/expr/scalar/func.rs [hunk 3]
```diff
@@ -425,11 +426,8 @@ fn cast_interval_to_string<'a>(a: Datum<'a>, temp_storage: &'a RowArena) -> Datu
 
 fn cast_interval_to_time<'a>(a: Datum<'a>) -> Datum<'a> {
     let mut i = a.unwrap_interval();
-    if !i.is_positive_dur {
-        i = i + repr::Interval {
-            duration: std::time::Duration::from_secs(86400),
-            ..Default::default()
-        };
+    if i.duration < 0 {
+        i = i + repr::Interval::new(0, 86400, 0);
```
Comment (frankmcsherry) [inline src/expr/scalar/func.rs:430]: This looks like what was here before, but is it easy to explain the logic? It seems like we add one day if the interval is negative, but we might still be negative once that is done. Is that ok?

File: src/interchange/avro.rs (hunk 2 above)
Comment (sploiselle) [reply src/interchange/avro.rs]: Annoyingly, this looks like it's going to be bad for Avro for the time being because it actually only supports `u32`--glad you made this note. `i32` suffices because it matches the maximum number of days Postgres allows for intervals, though, which is good. At any rate, I left a note that will need to be cleaned up a bit once we determine what to do here.

File: src/expr/scalar/func.rs (hunk 3 above)
Comment (sploiselle) [reply src/expr/scalar/func.rs]: Great catch; thank you. Fixed this and added a test.

**Comment by sploiselle** [comment]
@frankmcsherry tftr; I hadn't even considered adding the `chrono::Duration`s together; that's a great solution

File: src/interchange/avro.rs [hunk 4]
```diff
@@ -929,12 +929,27 @@ impl Encoder {
...
+                        dur /= 24 * 60 * 60 * 1_000_000_000;
+                        // We assume 30 days per month like in Postgres because
+                        // there aren't more details about the Avro
+                        // implementation.
+                        let days = dur % 30;
+                        dur /= 30;
+                        let months = iv.months.abs() + dur as i64;
+                        buf.extend(&(months as u32).to_le_bytes());
+                        buf.extend(&(days as u32).to_le_bytes());
+                        buf.extend(&((ns / 1_000_000) as u32).to_le_bytes());
```
Comment (benesch) [inline src/interchange/avro.rs:952]: I think this was more correct in one dimension before, although the overflow was definitely a problem. Specifically the Avro spec has this to say:

> The duration logical type represents an amount of time defined by a number of months, days and milliseconds. This is not equivalent to a number of milliseconds, because, depending on the moment in time from which the duration is measured, the number of days in the month and number of milliseconds in a day may differ.

In other words the months, days, and seconds fields are all actually different dimensions of the interval, much like we separate out months and nanoseconds. Converting nanoseconds to days/months will change the meaning of the interval, by the letter of the spec.

That said... it turns out the Java Avro client doesn't even support (!!!!) this type. https://issues.apache.org/jira/browse/AVRO-2123. So probably we should just ditch using this format and make up our own extremely convenient format instead. Either the string representation or just blatting down the two ints, probably.

But given that almost certainly no one is using this, doesn't need to block this PR!

File: src/pgrepr/src/value/interval.rs [hunk 5]
```diff
@@ -38,10 +37,14 @@ impl ToSql for Interval {
...
-        );
-        out.put_i32(0);
+        let days = self.0.days() as i128;
+        let sub_day_ns = self.0.duration % (24 * 60 * 60 * 1_000_000_000);
+
+        out.put_i64((sub_day_ns / 1000) as i64);
+        // Postgres' max days is 106,751,991,167,300, which is exactly `i64::MAX
+        // / (60 * 60 * 24)`. Because we avail to keep `Interval` seconds within
+        // i64, this shouldn't compress values.
+        out.put_i32(days as i32);
```
Comment (sploiselle) [inline src/pgrepr/src/value/interval.rs:47]: @benesch I had a momentary lapse of sense and overlooked that the same problem that affects the Avro encoding also affects the PG encoding; `i32` days is nowhere near sufficient to express the max number of days that PG allows. What do you think we should do here?

Comment (sploiselle) [reply src/pgrepr/src/value/interval.rs:47]: Note here that I mis-referenced this twice. I stated that PG's max days is > `i32`; that isn't true. _Our_ max days is > `i32`. PG's is, as makes perfect sense, == `i32:::MAX`.

Comment (benesch) [reply src/pgrepr/src/value/interval.rs:47]: I'm not sure I understand how we manage to get away with not having a separate days field, like Postgres? So my mental model here might be way off. Do we diverge on semantics?

Comment (sploiselle) [reply src/pgrepr/src/value/interval.rs:47]: Not having a day field doesn't meaningfully differentiate our behavior from PG. The only notable difference is that we display hours in excess of 24 as days, where PG does not:

```
pg=# select interval '25 hours';
 interval
----------
 25:00:00
```
```
mz=> select interval '25 hours';
    ?column?
----------------
 1 day 01:00:00
```

PG stores the day in a separate int than the hour:minute:seconds, but rolls over every 24 hours into a day, which means its calculations and ours are identical:

```
pg=# select timestamp '2001-01-01 02:03:04' +  interval '1 day 2147483647 hours';
       ?column?
-----------------------
 246984-10-10 09:03:04
```
```
mz=> select timestamp '2001-01-01 02:03:04' +  interval '1 day 2147483647 hours';
        ?column?
------------------------
 246984-10-10 09:03:04
````

Really, it just seems like Postgres' differentiation of day from the smaller fields is just a matter of compression for them; there's no semantic meaning in that separation like there is for months.

Comment (benesch) [reply src/pgrepr/src/value/interval.rs:47]: Ah got it. 128-bit side types aren’t common in C, and probably didn’t exist at all when PostgreSQL was written. Can we just clamp our max interval to the Postgres max interval? Would that solve the issue?

Comment (frankmcsherry) [reply src/pgrepr/src/value/interval.rs:47]: We should probably establish some philosophy at some point about whether our goal is to inherit all of Postgres' limitations, or to build something that could be better / as good as more modern systems. It sort of feels like if you wrote a query that returns a large but totally reasonable interval, and when converting to types pgwire understands it doesn't fit, that moment is where the error occurs?

Comment (benesch) [reply src/pgrepr/src/value/interval.rs:47]: I actually thought we were all aligned on the philosophy of doing things the Postgres way unless there are very clear and specific benefits to deviating? Almost every time we've deviated I've regretted it. Even our different decimal implementation causes a lot of headaches, although I think the justification for that one is sound (in-place differential aggregates). If you have concerns about this philosophy, Frank, perhaps we should try to sync up with product and nail down something more concrete?

> It sort of feels like if you wrote a query that returns a large but totally reasonable interval, and when converting to types pgwire understands it doesn't fit, that moment is where the error occurs?

Strictly speaking, yes, though having data we can represent internally but not via pgwire definitely feels a bit weird, considering pgwire is the only "mature" interface to Materialize today.

In this specific case, the maximum interval that Postgres supports is pretty darn massive. Most programming languages I'm aware of represent durations as a type with less range than Postgres, so users don't typically feel the pain.

Perhaps a way of looking at this that is more palatable is that we are choosing types that are likely to be immediately useful to users in other programming languages? There are existing Postgres drivers that know how to take an interval in the Postgres range and map it to something sensible in that driver's language. If we invent a better interval type, we are now on the hook for writing that code in every language that people want to use Materialize with, or at least telling folks how to perform the conversion.

Down the road when we have more resources, I expect that there may be types where we want to provide a Materialize variant, like perhaps a `MaterializeInterval` and a `PostgresInterval`. Sophisticated users in the know could then opt-in to the new types, and write the necessary support glue for their drivers, while everyone else could use the Postgres compatible types.

Comment (sploiselle) [reply src/pgrepr/src/value/interval.rs:47]: Made newly-created Intervals PG compatible; still need to propagate this change across all operators, but this shows it in action. Resolving this convo, but glad to revisit if anyone has unvoiced concerns.

File: src/interchange/avro.rs (hunk 4 above)
Comment (sploiselle) [reply src/interchange/avro.rs]: YOLO'ed our own format in here.
