### PR TITLE
adapter: handle 0dt deploys in orphaned secrets cleanup

### LINKED ISSUE #28570: 0dt upgrade: ERROR: No such file or directory (os error 2) in CREATE SOURCE mysql_source2_false
### What version of Materialize are you using?

e5c5348ee3

### What is the issue?

[Checks 0dt upgrade, whole-Mz restart](https://buildkite.com/materialize/nightly/builds/8835#0190f018-71bd-4ee8-bafb-09975855ff3c) and the other 0dt upgrade tests started failing:
```
13:1: error: executing query failed: db error: ERROR: No such file or directory (os error 2): ERROR: No such file or directory (os error 2)
     |
   2 | $[version>=5200] pos ... [rest of line truncated for security]
   5 | $ mysql-connect name ... [rest of line truncated for security]
  12 | 
  13 | > CREATE SOURCE mysql_source2_false
     | ^
```
My guess is that this could be related to the already fixed https://github.com/MaterializeInc/materialize/pull/28285 occurring in MySQL connection now while we were still on the old version. This fits with the error not happening in the [Checks 0dt restart of the entire Mz](https://buildkite.com/materialize/nightly/builds/8835#0190f018-71bc-4054-b79d-7593b137e99c). What doesn't make sense to me though is that it happens during CREATE SOURCE now, not when dropping.

The services.log talks about a file in /tmp missing, in relation to connecting to a process:
```
platform-checks-mz_1-1              | cluster-u30-replica-u34-gen-0: 2024-07-26T17:45:05.846759Z  INFO mz_cluster::communication: error connecting to process at /tmp/b709efed244790b682f2e6bfb9ce147d5622e2f0: No such file or directory (os error 2); will retry process=1
```
Discussion on Slack: https://materializeinc.slack.com/archives/C071VTZS1M5/p1722029728874599
ci-regexp: ERROR: No such file or directory (os error 2)

### PR DESCRIPTION
**Pull request by benesch**
The existing code to cleanup orphaned secrets during coordinator bootstrap was not properly handling 0dt deployments, and could inappropriately remove secrets that were added by the old environment during the deployment process. The race worked like this:

  * New 0dt deployment created.
  * New envd begins booting in read-only mode.
  * New envd loads catalog and begins bootstrapping coordinator.
  * Old envd creates a secret.
  * New envd finishes bootstrapping.
  * New envd cleans up orphaned secrets based on now-stale catalog and removes the secret that the old envd just added.

This patch adds two safeguards:

  1. The orphaned secrets cleanup is careful to never delete secrets that have a global ID that is larger than the largest global ID known to the catalog.

     This protects not just against the aforementioned race, but also against a theoretical race in which an envd boots up in non-read-only mode and loads its catalog and then, right before starting orphaned secrets cleanup, loses its leadership to a *new* envd that manages to create a secret.

  2. Orphaned secrets cleanup is no longer run in read-only mode.

     While (1) is sufficient to prevent all races on its own, cleaning up secrets is a mutating operation, and so it philosophically should not run in read-only mode.

### Motivation

  * This PR fixes a recognized bug.
  
    Fixes #28570.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

**Comment by benesch** [comment]
I have read the Contributor License Agreement (CLA) and I hereby sign the CLA.

File: src/adapter/src/catalog.rs [hunk 1]
```diff
@@ -584,6 +584,15 @@ impl Catalog {
             .err_into()
     }
 
+    /// Get the next user item ID without allocating it.
+    pub async fn get_next_user_item_id(&self) -> Result<u64, Error> {
```
Comment (aljoscha) [inline src/adapter/src/catalog.rs:588]: Only bother changing this when pushing a change anyways, but I often find a name like `peek_next_user_item_id` to better conveying the semantics.

**Review by aljoscha — APPROVED** [review]
excellent!

**Review by def- — APPROVED** [review]
Looking good so far, haven't seen the failure yet, without the fix it always happened in this timespan. Will keep the test running just in case.

**Comment by benesch** [comment]
Sweeeet! Merging for now, but holler if you do see a failure and we need to revisit.

**Comment by nrainer-materialize** [comment]
This change broke the AWS (Localstack): https://buildkite.com/materialize/nightly/builds/8982#01912ba0-9a2b-41ec-a23c-99ed7528ad61

```
File "/var/lib/buildkite-agent/builds/buildkite-aarch64-small-d306b64-i-0f58c6910f9c86c6c-1/materialize/nightly/test/aws-localstack/mzcompose.py", line 179, in workflow_secrets_manager
  assert orphan_1_name not in secrets
```

@benesch, is this a test issue? If so, can you give me a hint how to fix it?

**Comment by benesch** [comment]
Ah, thanks for the flag. https://github.com/MaterializeInc/materialize/pull/28848 is a fix. (Sorry, figuring out what the problem required just doing the fix.)

**Comment by nrainer-materialize** [comment]
Thank you!
