### PR TITLE
Properly clean up timestamper state when we DROP DATABASE

### LINKED ISSUE #6094: Consistency topic reader state persists after the source is dropped
To reproduce, one can simply run a test that uses consistency topics multiple times e.g. with

```
cargo run --bin testdrive -- test/testdrive/timestamps-debezium-kafka.td
```

the first time I run it the test creates a consistency topic

```
Creating Kafka topic testdrive-consistency-2703821702 with partition count of 1
```

and the second time I run it the test deletes the previous sources and topic

```
Run 1 ...
> DROP DATABASE materialize
> DROP VIEW IF EXISTS "join" CASCADE
> DROP VIEW IF EXISTS bar CASCADE
> DROP VIEW IF EXISTS foo CASCADE
> DROP SOURCE IF EXISTS data_bar CASCADE
> DROP SOURCE IF EXISTS data_foo CASCADE
Deleting stale Kafka topics testdrive-bar-2703821702
Deleting stale Kafka topics testdrive-foo-2703821702
Deleting stale Kafka topics testdrive-consistency-2703821702
```

but in the logs I see:

```
2021-03-16T14:06:39.595060Z ERROR rdkafka::client: librdkafka: Global error: UnknownTopicOrPartition (Broker: Unknown topic or partition): testdrive-consistency-2703821702 [0]: topic does not exist (Broker: Unknown topic or partition)
```

repeatedly. cc: @philip-stoev

### PR DESCRIPTION
**Pull request by ruchirK**
Fixes #6094

Previously we were not informing the timestamper about source drops after a DROP DATABASE, which lead to lots of logs complaining about being unable to read from stale consistency topics in testdrive tests

This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/6098)

### CODE REVIEW

**Review by mjibson — APPROVED** [review]
LGTM, with the caveat that I haven't spent time with the catalog code.

**Review by benesch — APPROVED** [review]
Ooh, nice catch, thanks!

File: src/coord/src/coord.rs [hunk 1]
```diff
@@ -3053,6 +3035,9 @@ impl Coordinator {
                                 -1,
                             )
                             .await;
+                            if let Some(tables) = &mut self.persisted_tables {
```
Comment (philip-stoev) [inline src/coord/src/coord.rs:3038]: Ok so ```DROP DATABASE``` is not simply an iteration over the objects dropping them individually? I would expect that the loop that is dropping the individual tables would cause their persisted representations to be removed.

If so, understood, I will make sure that I have tests that call  ```DROP DATABASE```  explicitly.
