### PR TITLE
coord: add timeout to read operations during read-then-writes

### LINKED ISSUE #12251: computed: table inserts fail across the board if one cluster has gone down
### What version of Materialize are you using?

v0.26.1-dev (aa0c81852)

### How did you install Materialize?

Docker image

### What was the issue?

If one cluster has panicked , INSERT statements will hang . 

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by sploiselle**
### Motivation

Fixes #12251

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - Fix a bug that prevented writes to tables if a cluster replica crashed during the read portion of `UPDATE`, `DELETE`, or `INSERT...SELECT`.
  - Introduce a timeout to `UPDATE`, `DELETE`, or `INSERT...SELECT` operations. The timeout defaults to 10 seconds, but is configurable with `SET read_then_write_timeout = <timeout>`.

### CODE REVIEW

File: src/coord/src/error.rs [hunk 1]
```diff
@@ -98,6 +98,8 @@ pub enum CoordError {
     ReadOnlyTransaction,
     /// The specified session parameter is read-only.
     ReadOnlyParameter(&'static (dyn Var + Send + Sync)),
+    /// The read in a ReadThenWrite exceeded our default timeout.
```
Comment (mjibson) [inline src/coord/src/error.rs:101]: nit: might not be the "default" timeout.

File: src/coord/src/error.rs [hunk 2]
```diff
@@ -297,6 +302,9 @@ impl CoordError {
             CoordError::NoClusterReplicasAvailable(_) => {
                 Some("You can create cluster replicas using CREATE CLUSTER REPLICA".into())
             }
+            CoordError::ReadThenWriteTimeoutExceeded(..) => Some(
+                "You can control this timeout with SET read_then_write_timeout = <timeout>".into(),
```
Comment (mjibson) [inline src/coord/src/error.rs:306]: Users need to know a unit for `<timeout>`.

File: src/coord/src/session/vars.rs [hunk 3]
```diff
@@ -113,6 +113,12 @@ const QGM_OPTIMIZATIONS: ServerVar<bool> = ServerVar {
     description: "Enables optimizations based on a Query Graph Model (QGM) query representation.",
 };
 
+const READ_THEN_WRITE_TIMEOUT: ServerVar<u64> = ServerVar {
+    name: static_uncased_str!("read_then_write_timeout"),
+    value: &10u64,
+    description: "Sets the timeout for INSERT...SELECT, UPDATE, and DELETE operations.",
```
Comment (mjibson) [inline src/coord/src/session/vars.rs:119]: maybe add the units here

File: src/coord/src/session/vars.rs [hunk 4]
```diff
@@ -538,6 +552,11 @@ impl Vars {
         *self.qgm_optimizations.value()
     }
 
+    /// Returns the value of the `cluster` configuration parameter.
```
Comment (mjibson) [inline src/coord/src/session/vars.rs:555]: cluster needs fixing

File: test/cluster/mzcompose.py [hunk 5]
```diff
@@ -58,7 +61,8 @@
 
 
 def workflow_default(c: Composition) -> None:
-    test_cluster(c, "smoke/*.td")
+    # test_cluster(c, "smoke/*.td")
```
Comment (mjibson) [inline test/cluster/mzcompose.py:64]: This looks like debugging leftover.

**Review by mjibson — APPROVED** [review]

**Comment by philip-stoev** [comment]
Item No 1. This statement does not seem to be governed by the timeout. Is that expected?

```
materialize=> insert into t1 select mz_internal.mz_sleep(100) from t1;
```

**Comment by philip-stoev** [comment]
A simpler test case for item No 2:

```
create table t1 (f1 integer);
insert into t1 values (100);
insert into t1 select mz_internal.mz_sleep(f1)::text::integer from t1;
select * from t1;
```

**Comment by philip-stoev** [comment]
Item No 3. Hitting Ctrl+C on the hanging `SELECT` statement above results in :+1: 
```
2022-05-13T12:23:13.003356Z  WARN mz_dataflow_types::client::replicated: Rehydrating replica "cluster-1-replica-1"
materialized v0.26.1-dev (062e4ef75) listening on 127.0.0.1:6875...
2022-05-13T12:23:44.226274Z  INFO mz_coord::catalog: create table materialize.public.t1 (u1)
2022-05-13T12:24:48.221486Z ERROR panic: Peek endpoint terminated prematurely: SendError(Canceled)
thread: coordinator
location: /home/pstoev/sploiselle-rtw-timeout/src/coord/src/coord.rs:1499:30
version: 0.26.1-dev (062e4ef756248f120231f90941dda54f4c39938f)
backtrace:
   0: materialized::handle_panic
   1: core::ops::function::Fn::call
   2: std::panicking::rust_panic_with_hook
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:702:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
   5: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   6: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   7: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
   8: mz_coord::coord::Coordinator<S>::message_command::{{closure}}
   9: mz_coord::coord::Coordinator<S>::serve::{{closure}}
  10: tokio::park::thread::CachedParkThread::block_on
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys/unix/thread.rs:108:17
  14: start_thread
             at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
  15: clone
             at /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

materialized encountered an internal error and crashed.
```

**Comment by philip-stoev** [comment]
Simplified test case for Item No 3:

```
create table t1 (f1 integer);
CREATE TABLE
insert into t1 values (1000);
insert into t1 select mz_internal.mz_sleep(f1)::text::int from t1;
```

and then hit Ctrl+C . This does not panic on `main`.

**Comment by sploiselle** [comment]
@philip-stoev 

[Item No. 1](https://github.com/MaterializeInc/materialize/pull/12427#issuecomment-1125979559): agreed

[Item No. 2](https://github.com/MaterializeInc/materialize/pull/12427#issuecomment-1126000847)'s lack of responsiveness seems to come from some thread still blocking on the evaluation of the sleep, i.e. if i configure it to only sleep for 10 seconds, it comes back relatively quickly, while a value of 100 does take a while. I'm also able to repro this behavior on `main`.

[Item No. 3](https://github.com/MaterializeInc/materialize/pull/12427#issuecomment-1126001842): fixed by ensuring when we return this error we perform a cancellation. @mjibson Do you have a sense of the right/best move here?

**Comment by philip-stoev** [comment]
Item No 4. In case they were accidentally left behind,  you have added 3 `println!`-s in the code that I see in STDOUT

**Comment by philip-stoev** [comment]
Yes, Item No 2 turns out to be https://github.com/MaterializeInc/materialize/issues/12331 . Apologies for the false alarm.

**Comment by philip-stoev** [comment]
Item No 5. Unfortunately even with 79437d4bd230a0cd6ed875117105a7b40ba87503 I am getting a panic:

```
2022-05-17T13:02:05.951591Z ERROR panic: Peek endpoint terminated prematurely: SendError(Rows([(Row{[Float64(OrderedFloat(10485760.0))]}, 1),
```
The entire error message is 400Mb.

To reproduce, use the SQL below. This test case succeeds in the parent commit of this PR.

```
\timing on
drop table if exists t1;
create table t1 (f1 DOUBLE);
insert into t1 SELECT generate_series FROM generate_series(1,1000000);
update t1 set f1 = f1 + 1000000;
insert into t1 SELECT generate_series FROM generate_series(1,10000000);
update t1 set f1 = f1 + 10000000;
SET read_then_write_timeout = 1;
update t1 set f1 = f1 + 10000000;
SET read_then_write_timeout = 2;
update t1 set f1 = f1 + 10000000;
SET read_then_write_timeout = 3;
update t1 set f1 = f1 + 10000000;
SET read_then_write_timeout = 4;
update t1 set f1 = f1 + 10000000;
SET read_then_write_timeout = 5;
update t1 set f1 = f1 + 10000060;
SET read_then_write_timeout = 7;
update t1 set f1 = f1 + 10000000;
SET read_then_write_timeout = 8;
update t1 set f1 = f1 + 10000000;
SET read_then_write_timeout = 9;
update t1 set f1 = f1 + 10000000;
SET read_then_write_timeout = 10;
update t1 set f1 = f1 + 10000000;
SET read_then_write_timeout = 11;
update t1 set f1 = f1 + 10000000;
SET read_then_write_timeout = 12;
update t1 set f1 = f1 + 10000000;
SET read_then_write_timeout = 13;
update t1 set f1 = f1 + 10000000;
SET read_then_write_timeout = 14;
update t1 set f1 = f1 + 10000000;
SET read_then_write_timeout = 15;
update t1 set f1 = f1 + 10000000;
SET read_then_write_timeout = 16;
update t1 set f1 = f1 + 10000000;
SET read_then_write_timeout = 17;
update t1 set f1 = f1 + 10000000;
SET read_then_write_timeout = 18;
update t1 set f1 = f1 + 10000000;
SET read_then_write_timeout = 19;
update t1 set f1 = f1 + 10000000;
SET read_then_write_timeout = 20;
update t1 set f1 = f1 + 10000000;
```

File: src/coord/src/coord.rs [hunk 6]
```diff
@@ -1437,15 +1443,32 @@ impl<S: Append + 'static> Coordinator<S> {
...
+    }
+
+    /// Cancel any ongoing, interactive work for the named `conn_id`.
+    ///
+    /// # Parameters
+    /// - `secret_key` must be `Some` when handling client-initiated cancels,
+    /// but can be `None` to permit the system to force a cancellation.
+    /// - `send_response` must be false when dealing with a forced cancellation
+    ///   because the client is already set to receive another response.
+    async fn cancel_inner(&mut self, conn_id: u32, secret_key: Option<u32>, send_response: bool) {
```
Comment (mjibson) [inline src/coord/src/coord.rs:1463]: Can the secret key checking be handled by `handle_cancel` so that this doesn't have to know about it?

Comment (benesch) [inline src/coord/src/coord.rs:1463]: I recommend refactoring this to have the following signature:

```
async fn cancel_inner(&mut self, conn_id: u32) -> Vec<RowTx> {

}
```

Then you won't need `force_cancel_cleanup`, and can just call `cancel_inner` directly and ignore the response. `handle_cancel` can handle checking the secret key and sending the PeekResponse::Canceled to all the returned `rows_tx`s.

File: src/coord/src/coord.rs [hunk 7]
```diff
@@ -954,6 +955,11 @@ impl<S: Append + 'static> Coordinator<S> {
                 );
             }
             Err(e) => {
+                if matches!(e, CoordError::ReadThenWriteTimeoutExceeded(..)) {
```
Comment (mjibson) [inline src/coord/src/coord.rs:958]: I don't like sniffing for a sentinel here because it feels easy for something to break in the future, and having boolean parameters in functions (cancel_inner here) is a known bad pattern. I've had a variety of ideas that are not good for some reasons, but we need to be able to send a nice error message to the user (not just "peek cancelled"). Is it possible to send a CancelRequest message right above where the ReadThenWriteTimeoutExceeded is created? Or something where we aren't communicating an expected side effect via a specific error message?

**Review by mjibson — APPROVED** [review]
I'm LGTM on merging this if we just want to move along. I'm only theoretically worried about what I wrote.

File: src/coord/src/coord.rs [hunk 8]
```diff
@@ -954,6 +955,11 @@ impl<S: Append + 'static> Coordinator<S> {
...
+                    // Clean up any state that might get left behind from e.g. a
+                    // forced cancellation due to a timeout.
+                    self.force_cancel_cleanup(session.conn_id()).await;
```
Comment (benesch) [inline src/coord/src/coord.rs:961]: Minor, but this technically cancels too much. It probably wants to cancel only the one peek involved in the read-then-write op that failed, rather than other portals that are live.

File: src/coord/src/session/vars.rs [hunk 9]
```diff
@@ -113,6 +113,12 @@ const QGM_OPTIMIZATIONS: ServerVar<bool> = ServerVar {
     description: "Enables optimizations based on a Query Graph Model (QGM) query representation.",
 };
 
+const READ_THEN_WRITE_TIMEOUT: ServerVar<u64> = ServerVar {
+    name: static_uncased_str!("read_then_write_timeout"),
+    value: &10u64,
+    description: "Sets the timeout in seconds for INSERT...SELECT, UPDATE, and DELETE operations.",
+};
```
Comment (benesch) [inline src/coord/src/session/vars.rs:120]: Would love to avoid introducing a Materialize-specific session parameter here. I think you can use PostgreSQL's existing `idle_in_transaction_session_timeout` parameter here? Seems to be more or less exactly what we want.

Comment (benesch) [reply src/coord/src/session/vars.rs:120]: Also, these `*_timeout` session parameters are a bit funny. They take a string that can contain units:

```
benesch=# set idle_in_transaction_session_timeout = '1 minute';
ERROR:  invalid value for parameter "idle_in_transaction_session_timeout": "1 minute"
HINT:  Valid units for this parameter are "us", "ms", "s", "min", "h", and "d".
```

If you don't specify units, the implied unites are `ms`. We should definitely try to match PostgreSQL here, whatever name we choose for the parameter.

**Comment by sploiselle** [comment]
@philip-stoev I'm unable to repro a panic on my threadripper, even running the test 5 times on the same running instances. This is using `bin/materialized`.

Looking at the memory visualizer on `storaged`, these are the stats I get:

```
Allocated: 1.54 GiB
In active pages: 1.55 GiB
Allocated for allocator metadata: 35.74 MiB
Bytes unused, but retained by allocator: 1.26 GiB
```

Where/how were you collecting the memory usage so I can try to repro more  exactly?

File: src/coord/src/session/vars.rs (hunk 9 above)
Comment (sploiselle) [reply src/coord/src/session/vars.rs:120]: Ah, Joe proposed a similar variable above and my apprehension with it is that to adhere to PG semantics, we need to plumb this timeout elsewhere (e.g. `implement_fast_path_peek`, which seems a little more complicated).

I'm down to modify the parsing to make the API consistent, but is there any appetite for getting this fix in before embarking on adding timeouts for all reads? Or are you comfortable with having the session variable's name have different semantics than it does in PG?

**Comment by philip-stoev** [comment]
The memory was visible in the `RSS` column of `top` . I will recompile from scratch tomorrow and will attempt to reproduce on a bin/scratch machine

File: src/coord/src/session/vars.rs (hunk 9 above)
Comment (benesch) [reply src/coord/src/session/vars.rs:120]: I’m extremely in favor of using that parameter and just having slightly different semantics! Sorry, didn't mean to suggest doing more work to match the semantics exactly.

**Comment by philip-stoev** [comment]
@sploiselle The panic is readily reproducible on a CI-sized instance such as the one that is already running `i-0b24571a86715b066` . It panics on the second or third `UPDATE` statement that times out, so there is not enough time for the memory leak to form. I guess once the panic is moved out of the way we will be able to see if the memory leak remains.

I will be at the NY office today so am available in case you continue to have issues reproducing.

**Comment by sploiselle** [comment]
@philip-stoev I'm unable to repro the panic with these now commits, which is good. Can you see if the same is true for you?

However, I can't repro the `cluster-isolation` test failure using either `bin/materialized` or `bin/cluster-dev`. Reading from tables loses interactivity irrespective of the cluster you're connected to, but when I perform the test operations by hand, the system is very responsive (assume you're not connected to the crash-looping replica). If you have any suggestions here, I'd be very interested.

**Comment by sploiselle** [comment]
@philip-stoev Got the local testing issue figured out (wasn't properly setting the cluster targets). I need to clean this up a bit still, but could I get you to take another look at this for the memory leak issue you were seeing previously?

**Comment by philip-stoev** [comment]
Yes, I am on it. Apologies for the delay.

**Review by philip-stoev — APPROVED** [review]
I was able to reproduce the memory leak on the parent commit using vanilla Ctrl+Cs.

I also got another panic:

```
2022-05-20T15:21:19.524775Z ERROR panic: called `Result::unwrap()` on an `Err` value: ClientError(client is reconnecting)
thread: coordinator
location: /home/ubuntu/materialize/src/coord/src/coord.rs:815:14
version: 0.26.1-dev (c5e09ac9158ec6bde448dd3f328a9bdc95e9dad4)
```

But I will assume that it is also not related to this PR, so will open tickets for both of those issues separately.

I think this PR is good to go.

**Comment by sploiselle** [comment]
@mjibson PTAL again!

File: src/coord/src/session/vars.rs [hunk 10]
```diff
@@ -773,6 +794,139 @@ impl Value for i32 {
...
+            // Default unit is milliseconds
+            "ms" | "" => (Duration::from_millis, 1),
+            "s" => (Duration::from_secs, 1),
+            "min" => (Duration::from_secs, SEC_TO_MIN),
+            "h" => (Duration::from_secs, SEC_TO_HOUR),
+            "d" => (Duration::from_secs, SEC_TO_DAY),
+            _ => return Err(()),
+        };
+
+        let d = if d == 0 {
```
Comment (mjibson) [inline src/coord/src/session/vars.rs:828]: Why does 0 map to MAX? Is it wrong to leave 0 as 0?

File: src/coord/src/session/vars.rs [hunk 11]
```diff
@@ -773,6 +794,139 @@ impl Value for i32 {
...
+                    format!(
+                        "{} ms",
+                        self.as_secs() * 1000 + u64::from(ms / MICRO_TO_MILLI)
+                    )
+                }
+                us => format!("{} us", self.as_secs() * 1_000_000 + u64::from(us)),
+            }
+        } else {
+            match self.as_secs() {
+                zero if zero == u64::MAX => "0".to_string(),
```
Comment (mjibson) [inline src/coord/src/session/vars.rs:854]: I feel like this should still get a unit? Or is 0 a special duration in postgres that we're emulating?

File: src/coord/src/session/vars.rs (hunk 10 above)
Comment (sploiselle) [reply src/coord/src/session/vars.rs:828]: Zero means disabled, which I'm emulating by letting the timeout run for `u64::MAX` seconds.

File: src/coord/src/coord.rs [hunk 12]
```diff
@@ -1139,6 +1137,29 @@ impl<S: Append + 'static> Coordinator<S> {
...
+                    for (compute_instance, uuids) in inverse {
+                        self.dataflow_client
+                            .compute_mut(compute_instance)
+                            .unwrap()
+                            .cancel_peeks(&uuids)
+                            .await
+                            .unwrap();
+                    }
+                    for (uuid, _) in uuids {
+                        self.pending_peeks.remove(&uuid);
```
[the remark this answers is not in the document]
Comment (sploiselle) [reply src/coord/src/coord.rs:1159]: Sending a `PeekResponse::Canceled` causes some malformed behavior with the PG client used in `mzcompose`. I didn't dig into what specifically the issue was, but avoiding sending the response fixed it. I can add comments to `RemovePendingPeeks` explaining the invariant that it holds.

File: test/cluster/mzcompose.py [hunk 13]
```diff
@@ -109,3 +113,38 @@ def test_cluster(c: Composition, *glob: str) -> None:
...
+    c.up("computed_1")
+    c.sql(
+        """
+        DROP CLUSTER IF EXISTS cluster1 CASCADE;
+        CREATE CLUSTER cluster1 REPLICA replica1 (REMOTE ('computed_1:2100'));
+        SET cluster = cluster1;
+        """
+    )
+    start_time = time.process_time()
+    try:
```
[the remark this answers is not in the document]
Comment (sploiselle) [reply test/cluster/mzcompose.py:131]: Added and passes locally

**Comment by benesch** [comment]
I’m extremely in favor of using that parameter and just having slightly
different semantics! Sorry, didn't mean to suggest doing more work to match
the semantics exactly.
