### PR TITLE
adapter: serialize DDL

### LINKED ISSUE #27821: parallel-workload: thread 'coordinator' panicked at src/adapter/src/catalog/apply.rs:806:30: invalid persisted SQL: PlanError(Catalog(UnknownSchema("s-0_';alert(123);t='")))
### What version of Materialize are you using?

4de738a9be

### What is the issue?

Seen in https://buildkite.com/materialize/nightly/builds/8192#019044df-b053-4ac1-b15a-e7df93382e82
```
thread 'coordinator' panicked at src/adapter/src/catalog/apply.rs:806:30:
invalid persisted SQL: PlanError(Catalog(UnknownSchema("s-0_';alert(123);t='")))
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at ./rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at ./rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1654:5
   3: <core::result::Result<mz_catalog::memory::objects::CatalogItem, mz_adapter::error::AdapterError>>::expect
             at ./rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1034:23
   4: <mz_adapter::catalog::state::CatalogState>::apply_item_update
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00325d45c2f1c1d7b-1/materialize/test/src/adapter/src/catalog/apply.rs:804:44
   5: <mz_adapter::catalog::state::CatalogState>::apply_update
   6: <mz_adapter::catalog::state::CatalogState>::apply_updates_inner
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00325d45c2f1c1d7b-1/materialize/test/src/adapter/src/catalog/apply.rs:156:21
   7: <mz_adapter::catalog::state::CatalogState>::apply_updates
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00325d45c2f1c1d7b-1/materialize/test/src/adapter/src/catalog/apply.rs:126:17
   8: <mz_adapter::catalog::Catalog>::transact_inner::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00325d45c2f1c1d7b-1/materialize/test/src/adapter/src/catalog/transact.rs:505:44
   9: <tracing::instrument::Instrumented<<mz_adapter::catalog::Catalog>::transact_inner::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  10: <mz_adapter::catalog::Catalog>::transact_inner::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00325d45c2f1c1d7b-1/materialize/test/src/adapter/src/catalog/transact.rs:438:5
  11: <mz_adapter::catalog::Catalog>::transact::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00325d45c2f1c1d7b-1/materialize/test/src/adapter/src/catalog/transact.rs:399:10
  12: <tracing::instrument::Instrumented<<mz_adapter::catalog::Catalog>::transact::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  13: <mz_adapter::catalog::Catalog>::transact::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00325d45c2f1c1d7b-1/materialize/test/src/adapter/src/catalog/transact.rs:335:5
  14: <mz_adapter::coord::Coordinator>::catalog_transact_inner::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00325d45c2f1c1d7b-1/materialize/test/src/adapter/src/coord/ddl.rs:529:14
  15: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::catalog_transact_inner::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  16: <mz_adapter::coord::Coordinator>::catalog_transact_inner::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00325d45c2f1c1d7b-1/materialize/test/src/adapter/src/coord/ddl.rs:181:5
  17: <mz_adapter::coord::Coordinator>::catalog_transact_with_side_effects::<<mz_adapter::coord::Coordinator>::create_index_finish::{closure#0}::{closure#0}::{closure#1}, <mz_adapter::coord::Coordinator>::create_index_finish::{closure#0}::{closure#0}::{closure#1}::{closure#0}>::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00325d45c2f1c1d7b-1/materialize/test/src/adapter/src/coord/ddl.rs:95:14
  18: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::catalog_transact_with_side_effects<<mz_adapter::coord::Coordinator>::create_index_finish::{closure#0}::{closure#0}::{closure#1}, <mz_adapter::coord::Coordinator>::create_index_finish::{closure#0}::{closure#0}::{closure#1}::{closure#0}>::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  19: <mz_adapter::coord::Coordinator>::catalog_transact_with_side_effects::<<mz_adapter::coord::Coordinator>::create_index_finish::{closure#0}::{closure#0}::{closure#1}, <mz_adapter::coord::Coordinator>::create_index_finish::{closure#0}::{closure#0}::{closure#1}::{closure#0}>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00325d45c2f1c1d7b-1/materialize/test/src/adapter/src/coord/ddl.rs:82:5
  20: <mz_adapter::coord::Coordinator>::create_index_finish::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00325d45c2f1c1d7b-1/materialize/test/src/adapter/src/coord/sequencer/inner/create_index.rs:527:14
  21: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::create_index_finish::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  22: <mz_adapter::coord::Coordinator>::create_index_finish::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00325d45c2f1c1d7b-1/materialize/test/src/adapter/src/coord/sequencer/inner/create_index.rs:410:5
  23: <mz_adapter::coord::CreateIndexStage as mz_adapter::coord::Staged>::stage::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00325d45c2f1c1d7b-1/materialize/test/src/adapter/src/coord/sequencer/inner/create_index.rs:56:69
  24: <tracing::instrument::Instrumented<<mz_adapter::coord::CreateIndexStage as mz_adapter::coord::Staged>::stage::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  25: <mz_adapter::coord::Coordinator>::sequence_staged::<mz_adapter::coord::CreateIndexStage>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00325d45c2f1c1d7b-1/materialize/test/src/adapter/src/coord/sequencer/inner.rs:189:18
  26: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00325d45c2f1c1d7b-1/materialize/test/src/adapter/src/coord/message_handler.rs:163:60
  27: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_message::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  28: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/future/future.rs:123:9
  29: <mz_adapter::coord::Coordinator>::serve::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00325d45c2f1c1d7b-1/materialize/test/src/adapter/src/coord.rs:2876:48
  30: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/future/future.rs:123:9
  31: <tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  32: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  33: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  34: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  35: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  36: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  37: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:310:22
  38: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::handle::Handle>::block_on<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>::{closure#0}, ()>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  39: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:309:9
  40: mz_adapter::coord::serve::{closure#0}::{closure#2}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00325d45c2f1c1d7b-1/materialize/test/src/adapter/src/coord.rs:3451:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
The last query seems to have been responsible:
```
environmentd: 2024-06-23T11:40:20.425453Z  INFO coord::handle_message{kind="command-execute"}:message_command:coord::handle_execute{session="c52ec159-8e64-4b00-8978-8f893f054589"}:coord::handle_execute_inner{stmt="CREATE INDEX \"idx_t-1_<a href=\"\"javascr_859452129737233483\" ON \"db-pw-1719142701-0_×‘\u{5b0}\u{5bc}×¨\u{5b5}××©\u{5b4}\".\"s-0_';alert(123);t='\".\"t-1_<a href=\"\"javascr\" (\"c-1-time_ABC<div style=\"\"x\", \"c-0-bytea_INF\", \"c-7-oid_ç”°ä¸­ã•ã‚“ã«\", \"c-5-float4_@{[system \"\"touch\", \"c-2-numeric(38,3)_-1E2\", \"c-8-uint2_\"\"`'><script>\\xE2\", \"c-4-bytea_+++ATH0\", \"c-3-bytea_<img\\x13src=x on\", \"c-6-float8_<img src\\x47=x o\")"}:sequence_create_index:create_index_finish:coord::catalog_transact_with_side_effects:coord::catalog_transact_inner:catalog::transact:catalog::transact_inner:transact_op: mz_adapter::catalog::transact: create index db-pw-1719142701-0_×‘Ö°Ö¼×¨Öµ××©Ö´.s-0-1_1'000'000.00.idx_t-1_<a href="javascr_859452129737233483 (u24)
```

What looks suspicious is the two `ALTER SCHEMA`s that were running in parallel:
```
[worker_6] ALTER SCHEMA "db-pw-1719142701-0_בְּרֵאשִ"."s-0_';alert(123);t='" RENAME TO "s-0-1_1'000'000.00";
[worker_8] ALTER SCHEMA "db-pw-1719142701-0_בְּרֵאשִ"."s-0_';alert(123);t='" RENAME TO "s-0-1_1'000'000.00";
```

There seems to be an out of data schema name while renaming the schema and having a create index running at the same time.

All queries that ran:
[parallel-workload-queries.log](https://github.com/user-attachments/files/15949876/parallel-workload-queries.log)

Potentially related PR: https://github.com/MaterializeInc/materialize/pull/27667 which would make this a v0.105 regression, so tentatively marking as a regression while I try to reproduce it in a simpler way. Edit: This is caused by https://github.com/MaterializeInc/materialize/pull/27607 instead

ci-regexp: invalid persisted SQL: PlanError

### PR DESCRIPTION
**Pull request by maddyblue**
Serialize all DDL by queueing DDL while another is executing.

Fixes #27821

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

### CODE REVIEW

**Comment by maddyblue** [comment]
TODO: DDL benchmark with and without this to observe perf impact.

**Comment by nrainer-materialize** [comment]
> TODO: DDL benchmark with and without this to observe perf impact.

If there is a performance impact, this will also impact the parallel workload. FYI @def-

**Comment by nrainer-materialize** [comment]
Please trigger a nightly build or notify me when the PR is ready and the test pipeline green. Thank you!

File: src/adapter/src/coord/validity.rs [hunk 1]
```diff
@@ -52,74 +57,95 @@ impl PlanValidity {
         }
     }
 
+    /// Sets the required `transient_revision` of the catalog. Should only be used be serialized
```
Comment (jkosh44) [inline src/adapter/src/coord/validity.rs:60]:
```suggestion
    /// Sets the required `transient_revision` of the catalog. Should only be used by serialized
```

File: src/adapter/src/session.rs [hunk 2]
```diff
@@ -1063,15 +1063,16 @@ impl<T: TimestampManipulation> TransactionStatus<T> {
...
     }
 
-    /// Adds operations to the current transaction. An error is produced if
-    /// they cannot be merged (i.e., a timestamp-dependent read cannot be
-    /// merged to an insert).
+    /// Adds operations to the current transaction. An error is produced if they cannot be merged
+    /// (i.e., a timestamp-dependent read cannot be merged to an insert).
+    ///
+    /// The `DDL` variant is an exception and does not merge operations, but instead overwrites the
+    /// old ops with the new ops.
```
Comment (jkosh44) [inline src/adapter/src/session.rs:1070]: Looks like this is existing behavior, but it'd probably be useful to explain why this is correct.

File: src/environmentd/tests/sql.rs [hunk 3]
```diff
@@ -3909,3 +3909,74 @@ async fn test_builtin_schemas() {
...
+    let client1 = server.connect().await.unwrap();
+    let client2 = server.connect().await.unwrap();
+    let client3 = server.connect().await.unwrap();
+    let cancel1 = client1.cancel_token();
+    let cancel3 = client3.cancel_token();
+
+    let handle = task::spawn(|| "test", async move {
+        // Wait hopefully enough time for the other create to start. This could flake if 100ms isn't
+        // enough time in CI, in which case increase this time.
+        tokio::time::sleep(Duration::from_millis(100)).await;
```
Comment (jkosh44) [inline src/environmentd/tests/sql.rs:3933]: This seems like it will be very difficult to maintain. I don't think we need to explicitly test that DDL is executed serially, just that the behavior identically to some serial order. Here's an idea for a test:
1. Start with some database state `s`.
2. Generate `n` DDL statements that are valid on `s`, but each create a state `s'` where no other DDL is valid on `s'`.
3. Assert that `1` DDL statement was successful and `n-1` statements errored.

For example the following psuedo code would accomplish that.

```Rust
let mut handles = Vec::new();
let n = 10;

for i in 0..n {
    let handle = task::spawn(|| execute(format!("CREATE VIEW v AS SELECT {i}")));
    handles.push(handle);
}

let mut successes = 0;
let mut errors = 0;
for handle in handles {
    let result = handle.join();
    match result {
        Ok(_) => successes += 1;
        Err(_) => errors += 1;
    }
}

assert_eq!(successes, 1);
assert_eq!(errors, n-1);
```

That's the simplest example I could think of, but if we wanted to we could make this more complicated. The general idea being, come up with some DDL that we run concurrently where there is an enumerable number of valid end states. Then we can assert that the end state is one of the valid states.

File: src/adapter/src/coord/command_handler.rs [hunk 4]
```diff
@@ -502,6 +505,46 @@ impl Coordinator {
         params: Params,
         mut ctx: ExecuteContext,
     ) {
+        // This comment describes the various ways DDL can execute, all of which are managed by this
+        // function. DDL has three notable properties that all partially interact.
+        //
+        // 1. Most DDL statements (and a few others) support single-statement transaction delayed
+        //    execution. This occurs when a session executes `BEGIN`, a single DDL, then `COMMIT`.
+        //    We announce success of the single DDL when it is executed, but do not attempt to
```
Comment (jkosh44) [inline src/adapter/src/coord/command_handler.rs:513]: > We announce success of the single DDL when it is executed

Is there a different word than "execute" we can use here? I think this might be confusing to people unfamiliar with the implementation because we announce success before it's actually executed.

File: src/adapter/src/coord/command_handler.rs [hunk 5]
```diff
@@ -502,6 +505,46 @@ impl Coordinator {
...
+        //    the transaction except `COMMIT`. Additionally, this will cause `handle_execute_inner`
+        //    to stop further processing (no planning, etc.) of the statement.
+        // 2. A few other DDL statements (`ALTER .. RENAME/SWAP`) enter the `DDL` ops which allows
+        //    any number of only these DDL statements to be executed in a transaction. At statement
+        //    execution time these are executed with the `Op::TransactionDryRun` catalog op. When
+        //    executed with `catalog_transact`, that op will always produce the `TransactionDryRun`
+        //    error. The `catalog_transact_with_ddl_transaction` function intercepts that error and
+        //    reports success to the user, but nothing is yet committed to the real catalog. At
+        //    `COMMIT` all of the ops but without dry run are applied. The purpose of this is to
+        //    allow multiple, atomic renams in the same transaction.
```
Comment (jkosh44) [inline src/adapter/src/coord/command_handler.rs:528]:
```suggestion
        //    allow multiple, atomic renames in the same transaction.
```

File: src/adapter/src/coord/command_handler.rs [hunk 6]
```diff
@@ -665,6 +708,29 @@ impl Coordinator {
             }
         }
 
+        // DDLs must be planned and sequenced serially. We do not rely on PlanValidity checking
+        // variaous IDs because we have incorrectly done that in the past. Attempt to acquire the
+        // ddl lock. The lock is stashed in the ConnMeta which is dropped at transaction end. If
+        // acquired, proceed with sequencing. If not, enque, start a waiter task, and return.
```
Comment (jkosh44) [inline src/adapter/src/coord/command_handler.rs:714]: > start a waiter task

Where is this happening?

File: src/adapter/src/coord.rs [hunk 7]
```diff
@@ -1611,6 +1617,20 @@ pub struct Coordinator {
     /// it manually.
     advance_timelines_interval: tokio::time::Interval,
 
+    /// Generic deferred statements.
```
Comment (jkosh44) [inline src/adapter/src/coord.rs:1620]: It's a bit confusing that this is described as generic for all statements, but we also have 
```Rust
/// Holds plans deferred due to write lock.
write_lock_wait_group: VecDeque<Deferred>,
```
above, which are for deferred inserts, which is a type of statement. Maybe we can add a note that inserts are excluded because they predate deferred statements. Also there seems to be some overlap in `DeferredPlan`

```Rust
/// This is the struct meant to be paired with [`Message::WriteLockGrant`], but
/// could theoretically be used to queue any deferred plan.
#[derive(Derivative)]
#[derivative(Debug)]
pub(crate) struct DeferredPlan {
    #[derivative(Debug = "ignore")]
    pub ctx: ExecuteContext,
    pub plan: Plan,
    pub validity: PlanValidity,
}
```

and `DeferredStatement` which both claim to be generic over any statement/plan type.

**Comment by maddyblue** [comment]
Need to care about:

- source validation doing off-thread work. maybe can make purification not serialized because it doesn't depend on catalog for anything including name resolution
- care about cluster reconfiguration with long timeouts

File: src/adapter/src/coord/command_handler.rs (hunk 4 above)
Comment (maddyblue) [reply src/adapter/src/coord/command_handler.rs:513]: I rejiggered this entire comment. "execute" tries to mean a user sent it, and I increased usage of "sequenced" and "applied" (for txn ops) so that execute has mostly one usage.

File: src/environmentd/tests/sql.rs (hunk 3 above)
Comment (maddyblue) [reply src/environmentd/tests/sql.rs]: Good idea, done.

**Comment by maddyblue** [comment]
RFAL. Reworked with more tests and support for the RENAME/SWAP transactions that required some additional logic paths. I'm not a fan of the current API because it's spread out over a few places and opt-in (so easy to forget to call unless there's a test that happens to exercise something).

File: src/adapter/src/coord/sequencer.rs [hunk 8]
```diff
@@ -283,6 +285,28 @@ impl Coordinator {
                 | Plan::AbortTransaction(AbortTransactionPlan {
                     ref transaction_type,
                 }) => {
+                    // Serialize DDL transactions.
+                    if ctx.session().transaction().is_ddl() {
```
Comment (jkosh44) [inline src/adapter/src/coord/sequencer.rs:289]: Do we need to further check that `must_serialize_ddl()` is true?

File: src/adapter/src/coord/sequencer/inner/cluster.rs [hunk 9]
```diff
@@ -70,23 +68,17 @@ impl Coordinator {
...
     ) -> Result<ClusterStage, AdapterError> {
-        let validity = PlanValidity::new(
-            self.catalog().transient_revision(),
-            BTreeSet::new(),
-            Some(plan.id.clone()),
-            None,
-            session.role_metadata().clone(),
-        );
+        let validity =
+            PlanValidity::require_transient_revision(self.catalog().transient_revision());
```
Comment (jkosh44) [inline src/adapter/src/coord/sequencer/inner/cluster.rs:81]: I thought that we weren't serializing `ALTER CLUSTER`?

File: src/adapter/src/coord/sequencer.rs (hunk 8 above)
Comment (maddyblue) [reply src/adapter/src/coord/sequencer.rs:289]: No, because that only checks Statements not Plans. However I've added doc strings scaring people into making sure that users of the DDL mode always return false in must_serialize_ddl(). I hope that's sufficient for now.

File: src/adapter/src/coord/sequencer/inner/cluster.rs (hunk 9 above)
Comment (maddyblue) [reply src/adapter/src/coord/sequencer/inner/cluster.rs:81]: Good catch. Reverted.

**Review by jkosh44 — APPROVED** [review]

**Comment by maddyblue** [comment]
Started a nightly build at https://buildkite.com/materialize/nightly/builds/8653

**Comment by maddyblue** [comment]
Parallel DDL nightlies detected a problem because of a bad assumption I made in PlanValidity::RequireRevision. Things like ALTER SECRET don't get the lock so are able to bump the revision even with the serialized lock already held, which would fail in that check. I wrote a new long comment describing why it's ok to ignore that check now, and also some tech debt we should pay down later that would make it programmatically safer. Re-running the nightlies.

**Comment by maddyblue** [comment]
There did seem to be a bit of perf decrease for DDL workloads involving materialized views: https://buildkite.com/organizations/materialize/pipelines/nightly/builds/8653/jobs/0190c6ed-c603-48af-bb35-baa5017bce19/artifacts/0190c73e-acef-4f9e-b088-374d34bf9202

But it looks not terrible to me? Can testing take a look at the Scalability benchmark (DDL) tests there and comment?

Previous run above, new run at https://buildkite.com/materialize/nightly/builds/8664

**Comment by def-** [comment]
The DDL performance was already not great before, now it is slightly worse. I would of course be happier if we could run more DDLs in parallel, but I wouldn't block this PR.
