### PR TITLE
sql: Normalize create secret statements

### LINKED ISSUE #17665: cannot migrate from catalog version 0.43.0-dev to version 0.43.0-dev (earlier versions might still work): Expected identifier, found number "1.00"
### What version of Materialize are you using?

v0.43.0-dev (1c9960719)

### How did you install Materialize?

Built from source

### What is the issue?

With the code in https://github.com/MaterializeInc/materialize/pull/17614/commits/b25e08c0d64ccf08252f01b754f1b116fff17955 I introduce a new `Identifiers` check. Restarting Materialize fails with a secret created like this:

```
CREATE SECRET "1.00" as '1.00_value';
```

It seems like we are not serializing/deserializing the `"1.00"` secret name correctly and it gets reinterpreted as a number instead of a string.

Can be reproduced with:
```
$ cd ~/git/materialize
$ git checkout b25e08c0d64ccf08252f01b754f1b116fff17955
$ bin/mzcompose --find platform-checks down -v && bin/mzcompose --find platform-checks run default --scenario=RestartEntireMz --check=Identifiers
```

### Relevant log output

```source
platform-checks-materialized-1 | environmentd: cannot migrate from catalog version 0.43.0-dev to version 0.43.0-dev (earlier versions might still work): Expected identifier, found number "1.00"
```

ci-regexp: Expected identifier, found operator

### PR DESCRIPTION
**Pull request by jkosh44**
Previously, CREATE SECRET statements were not being properly normalized during creation. This led to the un-normalized statement being saved in the stash. On restart, these un-normalized statements would sometimes fail to parse.

This commit normalizes the CREATE SECRET statements before saving them to the stash.

Fixes #17665

### Motivation
This PR fixes a recognized bug.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by jkosh44** [comment]
@def- Is there anyway to port your existing secret tests to this PR or should I write my own?

File: src/adapter/src/catalog/migrate.rs [hunk 1]
```diff
@@ -60,9 +61,12 @@ pub(crate) async fn migrate(catalog: &mut Catalog) -> Result<(), anyhow::Error>
     // it. You probably should be adding a basic AST migration above, unless
     // you are really certain you want one of these crazy migrations.
     let cat = Catalog::load_catalog_items(&mut tx, catalog)?;
-    let _conn_cat = cat.for_system_session();
+    let conn_cat = cat.for_system_session();
 
-    rewrite_items(&mut tx, |_item| Ok(()))?;
+    rewrite_items(&mut tx, |item| {
+        normalize_create_secrets(&conn_cat, item)?;
```
Comment (jkosh44) [inline src/adapter/src/catalog/migrate.rs:67]: Unfortunately, I think that if a broken secret was committed to the stash, then it will be broken forever. For example, consider the secret: 
  `materialize.public.1.00`. 
Is the schema name `public` and the secret name `1.00` or is the schema name `public.1` and the secret name `00`? There's no way for us to correctly parse and normalize this.

**Comment by jkosh44** [comment]
> @def- Is there anyway to port your existing secret tests to this PR or should I write my own?

I just pulled in your commit, I'll see if anything is broken tomorrow.

**Comment by def-** [comment]
I had to rework the commit I previously provided yesterday. I force-pushed the enabled checks to this PR so that we can see the result, hope that's fine.

**Comment by jkosh44** [comment]
> I had to rework the commit I previously provided yesterday. I force-pushed the enabled checks to this PR so that we can see the result, hope that's fine.

Yep that's fine, thanks for the help!

File: src/adapter/src/catalog/migrate.rs [hunk 2]
```diff
@@ -142,3 +146,28 @@ fn csr_url_path_rewrite(stmt: &mut mz_sql::ast::Statement<Raw>) {
 // ****************************************************************************
 // Semantic migrations -- Weird migrations that require access to the catalog
 // ****************************************************************************
+
+/// Add normalization to all CREATE SECRET statements.
```
Comment (mjibson) [inline src/adapter/src/catalog/migrate.rs:150]: Can you add a doc comment for if/when this migration can be removed?

**Review by mjibson — APPROVED** [review]
Light preference for a more explicit test for this regression.

File: src/adapter/src/catalog/migrate.rs (hunk 2 above)
Comment (jkosh44) [reply src/adapter/src/catalog/migrate.rs:150]: Done

File: src/adapter/src/catalog/migrate.rs (hunk 1 above)
Comment (philip-stoev) [reply src/adapter/src/catalog/migrate.rs:67]: Indeed , the Nightly upgrade tests are now failing with:

```
environmentd: cannot migrate from catalog version 0.43.0 to version 0.44.0-dev (earlier versions might still work): Expected identifier, found operator "-"
```

which I assume is a demonstration of the impossibility to have a migration that fixes things?

Comment (def-) [reply src/adapter/src/catalog/migrate.rs:67]: @philip-stoev  Can we detect the base version in the check itself? If so, we could not create such secrets for older base versions.

Comment (philip-stoev) [reply src/adapter/src/catalog/migrate.rs:67]: No, this is currently not possible out of the box. [This ](https://github.com/MaterializeInc/materialize/issues/17636) is the ticket about creating the required enhancement to the testing framework.

Comment (def-) [reply src/adapter/src/catalog/migrate.rs:67]: Oh right, I even assigned it to myself without reading it properly yet. Will work on that after the buildkite annotations.

Comment (philip-stoev) [reply src/adapter/src/catalog/migrate.rs:67]: No need to disable anything I think, since as soon as the new version is released this week the test will start passing again.

Comment (def-) [reply src/adapter/src/catalog/migrate.rs:67]: The magic of cloud. I'm still getting used to not having to support 3 year old versions. ;)
