### PR TITLE
storage: Refactor table drop lifecycle

### LINKED ISSUE #24963: sentry: panic: cannot fail to apply appends: InvalidUppers([System(446)])
Sentry Issue: [DATABASE-BACKEND-39B](https://materializeinc.sentry.io/issues/4942492039/?referrer=github_integration)

```
panic: cannot fail to apply appends: InvalidUppers([System(446)])
  File "panicking.rs", line 597, in rust_begin_unwind
  File "appends.rs", line 376, in mz_adapter::coord::Coordinator::group_commit_initiate::{closure#0}::{closure#0}::{closure#6}
  File "instrument.rs", line 272, in tracing::instrument::Instrumented<T>::poll
  File "instrument.rs", line 272, in tracing::instrument::Instrumented<T>::poll
  File "core.rs", line 334, in tokio::runtime::task::core::Core<T>::poll::{closure#0}
...
(63 additional frame(s) were not displayed)
```

ci-regexp: cannot fail to apply appends: InvalidUppers

### LINKED ISSUE #25962: persist-txn: logical_upper races ahead of the timestamp oracle
### What version of Materialize are you using?

v0.91.0-dev

### What is the issue?

Whenever we forget a shard it appears as though we bump the logical upper of the txn's shard. If you forget a lot of shards all at once then it seems possible that the txn shard's logical upper can race ahead of the timestamp oracle. This causes [environmentd to halt](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/coord/appends.rs#L375-L381) when running a group commit, because the timestmap we commit at is no longer valid.

Related to https://github.com/MaterializeInc/materialize/issues/24963

### PR DESCRIPTION
**Pull request by jkosh44**
Previously, dropping a table looked something like the following:

  1. Queue a persist command to downgrade the read frontier of the
     table to the empty antichain.
  2. Queue a compaction command to compact the table to the empty
     antichain.
  3. At some later point the storage controller processes all the
     pending compaction commands.
  4. The table shard is forgotten from the persist txn shard.
  5. Once the shard is forgotten and compacted, a command is queued to
     finalize the shard.

This commit updates this logic so that step (4) is done first. The
logic now looks like the following:

  1. The table shard is forgotten from the persist txn shard.
  2. Queue a persist command to downgrade the read frontier of the
     table to the empty antichain.
  3. Queue a compaction command to compact the table to the empty
     antichain.
  4. At some later point the storage controller processes all the
     pending compaction commands.
  5. Once the shard is forgotten and compacted, a command is queued to
     finalize the shard.

This change in logic allows us to make the following improvements:

  - Use a timestamp from the timestamp oracle to forget the table's
    shard from the persist txn shard.
  - Batch the table shard forgets.

The timestamp improvement fixes a correctness issue where the txn shard
upper would get out of sync from the timestamp oracle. The adapter
makes the assumption that all table uppers are in sync with the
timestamp oracle. Previously, this assumption was broken because
forgets were making up their own timestamps inside the storage
controller, and then advancing the upper of all tables to this
timestamp.

The batch improvement is purely a performance optimization.

Fixes #25962
Fixes #24963

### Motivation
This PR fixes a recognized bug.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - There are no user-facing behavior changes.

### CODE REVIEW

File: src/storage-controller/src/lib.rs [hunk 1]
```diff
@@ -1164,6 +1168,40 @@ where
...
+            let drop_notif = async move {
+                let _ = rx.recv();
+            }
+            .boxed();
+            self.pending_table_handle_drops.insert(*id, drop_notif);
+        }
+        mz_ore::task::spawn(|| "table-cleanup".to_string(), async move {
+            drop_notif.await;
+            let _ = tx.send(());
+        });
```
Comment (jkosh44) [inline src/storage-controller/src/lib.rs:1201]: This is pretty gross, so all suggestions are welcome. If you want to look at a cleaner alternative that I tried, but didn't work, you can see this commit: https://github.com/MaterializeInc/materialize/pull/26291/commits/01bbb0224430f4e001b883e05dd5804177e696ee. 

The issue is that we cannot finalize a shard until it has both been dropped from the persist table worker and it has been downgraded by the persist read worker. We need to wait for the shard drop because part of dropping a shard from persist involves advancing the upper of that shard which would fail if the shard has been finalized. I'm less clear about why we need to wait for the downgrade, but if we don't wait the following panic happens:

1. Create table.
2. Subscribe to table.
3. Drop table.
4. Drop shard via persist table worker.
5. Finalize shard.
6. Subscribe is cancelled and attempts to downgrade it's read hold on the table.
7. Subscribe panics because it cannot find the table.

Another approach would be to plumb the `drop_notif` via a new field in `PendingCompactionCommand`. That would require optionally passing a timestamp to `Controller::update_read_capabilities` and `Controller::set_read_policy`, which felt a bit more invasive to me.

File: src/storage-controller/src/lib.rs [hunk 2]
```diff
@@ -1164,6 +1168,40 @@ where
         Ok(())
     }
 
+    fn drop_tables(
```
Comment (jkosh44) [inline src/storage-controller/src/lib.rs:1171]: I have mixed feelings about having a separate method for this vs combining this method with `drop_sources`. So let me know if you have a strong opinion.

**Comment by def-** [comment]
The nightly failure in instance size limits is coming from my new test code: https://buildkite.com/materialize/nightlies/builds/7107#018e81a3-c59b-4c0b-b7f2-eb0749ff3df8
I'll push a fix in here. The rest looks fine.

**Comment by petrosagg** [comment]
>  Shard finalization is designed to queue shards that are not fully downgraded and finalize them at a later point. 

Can you point me to where this is defined to be the case? (either docs or code works)

**Comment by jkosh44** [comment]
> > Shard finalization is designed to queue shards that are not fully downgraded and finalize them at a later point.
> 
> Can you point me to where this is defined to be the case? (either docs or code works)

Oops, this whole commit message was for the old approach and I forgot to change it. The most recent commit no longer relies on shard finalization being retried because it waits for the downgrade to complete. I've just updated the description to reflect this.

Though FWIW my understanding of the following code is that the shard is not removed from the shard finalization WAL unless it's in a finalized state (i.e. since has been downgraded to empty antichain). https://github.com/MaterializeInc/materialize/blob/f74fe1d2f186b1e5e6b6c2aa35b98e8cfd920f83/src/storage-controller/src/lib.rs#L3074-L3177 Since it's not removed, we will just retry next time we attempt to finalize shards.

**Comment by jkosh44** [comment]
@aljoscha and I talked about this and there's some improvements I'm going to try to make today/tomorrow.

File: src/adapter/src/coord/message_handler.rs [hunk 3]
```diff
@@ -72,9 +72,11 @@ impl Coordinator {
                     self.message_command(cmd).instrument(span).await
                 }
                 Message::ControllerReady => {
+                    // TODO(jkosh44) Avoid clone.
+                    let storage_metadata = self.catalog().state().storage_metadata().clone();
                     if let Some(m) = self
                         .controller
-                        .process()
+                        .process(&storage_metadata)
```
Comment (jkosh44) [inline src/adapter/src/coord/message_handler.rs:79]: Can someone with a bigger brain than me explain why this requires a `clone()` but no other usages of `storage_metadata()` requires a clone, even though they're passed to methods that take `mut &self` on the controller?

Comment (jkosh44) [reply src/adapter/src/coord/message_handler.rs]: Never mind, I figured it out.

**Comment by jkosh44** [comment]
> @aljoscha and I talked about this and there's some improvements I'm going to try to make today/tomorrow.

@aljoscha @petrosagg this is ready for another look.

**Review by mjibson — COMMENTED** [review]
Are the various test changes supposed to be here? Webhooks and balancerd don't seem related to table dropping.


Adapter parts lgtm.

**Comment by jkosh44** [comment]
> Are the various test changes supposed to be here? Webhooks and balancerd don't seem related to table dropping.

Yes, @def- added them. They were previously failing so we couldn't merge them and this PR fixes the underlying issue and allows us to merge the tests.

File: src/storage-controller/src/lib.rs [hunk 4]
```diff
@@ -196,6 +197,9 @@ pub struct Controller<T: Timestamp + Lattice + Codec64 + From<EpochMillis> + Tim
     /// Compaction commands to send during the next call to
     /// `StorageController::process`.
     pending_compaction_commands: Vec<PendingCompactionCommand<T>>,
+    /// Channel for table handle drops.
+    #[derivative(Debug = "ignore")]
+    pending_table_handle_drops: VecDeque<oneshot::Receiver<Vec<GlobalId>>>,
```
Comment (aljoscha) [inline src/storage-controller/src/lib.rs:202]: Couldn't we use a channel for this? Then `pending_table_handle_drops` would become a `UnboundedReceiver<GlobalId>`, and the task in `drop_tables` would not need a fresh `tx, rx` pair but just a handle to this channel here and it sends to it.

File: src/storage-controller/src/lib.rs [hunk 5]
```diff
@@ -1726,6 +1760,15 @@ where
         // IDs of sources (and subsources) whose statistics should be cleared.
         let mut source_statistics_to_drop = vec![];
 
+        while let Some(Ok(dropped_ids)) = self
```
Comment (aljoscha) [inline src/storage-controller/src/lib.rs:1763]: With my suggestion above, this would just become a `try_recv()` on the channel of ready table drops.

**Review by aljoscha — COMMENTED** [review]
I have one suggestion, but otherwise this looks pretty good!

File: src/storage-controller/src/lib.rs (hunk 4 above)
Comment (jkosh44) [reply src/storage-controller/src/lib.rs]: Good idea, just updated this to a channel.

File: src/storage-controller/src/lib.rs (hunk 5 above)
Comment (jkosh44) [reply src/storage-controller/src/lib.rs]: Done

**Comment by jkosh44** [comment]
Nightlies: https://buildkite.com/materialize/nightlies/builds/7278

**Review by aljoscha — APPROVED** [review]
Looks very good after those changes!
