### PR TITLE
adapter: Add deterministic audit event timestamps

### LINKED ISSUE #17331: Allow mocking out system timestamp for audit events purposes
## Motivation
The main consumer of the audit events table is our billing system. Validating our billing ahead of launch has been a multi-week process and while we are confident that our billing is correct right now, we will need ongoing automated regression testing to have that confidence over the long term.

The existing billing tests are both hard to update and not protective enough. The tests run against PostgreSQL, not Materialize and therefore risk missing real bugs in the interaction between the usage exporter and Materialize, or in Materialize itself.

We have a [proposed design for a v2 test harness](https://github.com/MaterializeInc/cloud/issues/5155) that will make it easier to update the test assertions in the case of desirable changes, and also provide nearly end-to-end coverage of the whole pipeline.

A key requirement for this pipeline to work without waiting for real time to elapse is the ability mock out the system timestamp in `mz_audit_events` records. Using this capability, we could create test cases with precise control over the timestamps of records, enabling us to efficiently test numerous aspects of the usage exporter that converts raw `mz_audit_event` rows into metering data.

## Proposal

We should be able to mock out the system timestamp oracle, for the purpose of comprehensively testing audit events. Suggested implementation, after conversing with @benesch:

- Add a system parameter whose value is the overridden timestamp, and which can be set with `ALTER SYSTEM`. For example, `ALTER SYSTEM SET audit_timestamp_override 1699284893`
- In the audit log write path, if this parameter is set, use its value as the timestamp; otherwise use the system timestamp oracle

### PR DESCRIPTION
**Pull request by jkosh44**
This commit adds a toggle that allows users specify what timestamp will be used for audit events. When the toggle is off, the system will choose timestamps normally. This toggle is only available in unsafe mode and is meant for testing purposes.

This commit also adds a toggle for all system variables that will make them only available in unsafe mode.

Resolves #17331

### Motivation
 This PR adds a known-desirable feature.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a
  companion cloud PR to account for those changes that is tagged with
  the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Review by necaris — APPROVED** [review]
Looks awesome! Thanks!

File: src/adapter/src/session/vars.rs [hunk 1]
```diff
@@ -373,6 +412,15 @@ static EMIT_TRACE_ID_NOTICE: ServerVar<bool> = ServerVar {
     description:
         "Boolean flag indicating whether to send a NOTICE specifying the trace id when available (Materialize).",
     internal: false,
+    safe: true,
+};
+
+static MOCK_AUDIT_EVENT_TIMESTAMP: ServerVar<Option<u64>> = ServerVar {
```
Comment (mjibson) [inline src/adapter/src/session/vars.rs:418]: I'm not a user of this so don't care either way, but wondering if a timestamp type instead of u64 is more easily usable.

**Review by mjibson — APPROVED** [review]

File: src/adapter/src/catalog.rs [hunk 2]
```diff
@@ -1212,7 +1221,13 @@ impl CatalogState {
         details: EventDetails,
     ) -> Result<(), Error> {
         let user = session.map(|session| session.user().name.to_string());
-        let occurred_at = oracle_write_ts.into();
```
[the remark this answers is not in the document]
Comment (jkosh44) [reply src/adapter/src/catalog.rs:1215]: @necaris Do you have an opinion on this? I was wondering the same thing but  then saw that the issue only mentioned the `mz_audit_events` table.

File: src/adapter/src/session/vars.rs (hunk 1 above)
Comment (jkosh44) [reply src/adapter/src/session/vars.rs:418]: Good call, I'll switch it to the `mz_repr::Timestamp` type

Comment (mjibson) [reply src/adapter/src/session/vars.rs:418]: If that easily parses both ints and timestamps from a `SET` command that'd be great. I don't know if it does offhand?

Comment (jkosh44) [reply src/adapter/src/session/vars.rs:418]: Oooh I see what you mean. I just checked and it does not. I'm not sure if there's a type that can parse both as an epoch timestamp and as a human readable timestamp, unless we roll something ourselves.

@necaris do you have a preference between being able to set the value using an epoch or human readable timestamp? Or would you prefer to be able to do both, in which case I'll try and implement something myself.

Comment (necaris) [reply src/adapter/src/session/vars.rs:418]: We're expecting to mostly use this from a test harness so an epoch timestamp is mildly preferable if it's a choice between the two, although ISO-formatting isn't hard either way.

File: src/adapter/src/catalog.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (necaris) [reply src/adapter/src/catalog.rs:1215]: That's a good question! We're definitely much more concerned about being able to test audit events -- among other things, I think there are more moving parts we need to take care of to thoroughly test storage usage -- but I think it would be useful to have this work for storage usage as well. @benesch any objections?

[the remark this answers is not in the document]
Comment (mjibson) [reply src/adapter/src/catalog.rs:1215]: I think due to the storage usage collection interval this might need to be a separate PR where a storage collection can be manually triggered after setting this timestamp, and the collection interval disabled if set or something.

Another concern: even if you set the main variable for this PR, all of the initial collections will have the system time for their creation, so you'll get a kinda wonky set of timestamps. It might be nice to also have this be a cli option or something so that the initial timestamps are also deterministic.

[the remark this answers is not in the document]
Comment (jkosh44) [reply src/adapter/src/catalog.rs:1215]: > Another concern: even if you set the main variable for this PR, all of the initial collections will have the system time for their creation, so you'll get a kinda wonky set of timestamps. It might be nice to also have this be a cli option or something so that the initial timestamps are also deterministic.

You can set any system variable via the `bootstrap-system-parameter` cli option
https://github.com/MaterializeInc/materialize/blob/main/src/environmentd/src/bin/environmentd/main.rs#L430-L438

[the remark this answers is not in the document]
Comment (jkosh44) [reply src/adapter/src/catalog.rs:1215]: Yeah I  think storage usage will be more complicated, so I'll go ahead and save that for a future PR should that be requested.

File: src/adapter/src/session/vars.rs (hunk 1 above)
Comment (jkosh44) [reply src/adapter/src/session/vars.rs]: I'll keep it as an epoch parsing then. Though I will switch the type to `mz_repr::Timestamp` so it better matches the actual type used in the table.

**Review by benesch — COMMENTED** [review]
@jkosh44 this is fantastic! Thanks very much!
