### PR TITLE
[storage] Heartbeat writer in storage persist sink

### LINKED ISSUE #15333: Storage sink code doesn't periodically heartbeat the write handle
### What version of Materialize are you using?

a1a8f6ca4cdd495babd2e9c1a960708bd591a08b

### How did you install Materialize?

Built from source

### What is the issue?

Persist handles need regular heartbeats so that they don't expire. This was recently fixed for compute sinks (https://github.com/MaterializeInc/materialize/pull/15198) but the same needs to be done for storage.

### Relevant log output

```source
thread 'timely:work-0' panicked at 'cannot append updates: UnknownWriter(WriterId(d5b55884-7ecc-4600-95ed-8cd373bd2f7d))', src/storage/src/render/persist_sink.rs:187:30
```
```

### PR DESCRIPTION
**Pull request by cjubb39**
Do similar to #15198 (which touched up heartbeating in compute persist sinks).   I'm not sure how to test exactly since the bug report mentions it's quite difficult to repro

### Motivation
Fixes #15333.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

File: src/storage/src/render/persist_sink.rs [hunk 1]
```diff
@@ -100,6 +104,25 @@ pub fn render<G>(
                     continue;
                 }
 
+                // Make sure that our write handle lease does not expire!
+                //
+                // We don't write to _Consensus_ but instead only write batch
```
Comment (aljoscha) [inline src/storage/src/render/persist_sink.rs:109]: This paragraph was only relevant for the (compute) `persist_sink` because it has separate writers and appenders. Here, we should just remove it. Sorry for the confusion :sweat_smile:

**Review by aljoscha — APPROVED** [review]
Looks good! modulo the comment I had about removing the unneeded paragraph

File: src/storage/src/render/persist_sink.rs (hunk 1 above)
Comment (cjubb39) [reply src/storage/src/render/persist_sink.rs:109]: lol yes of course.  I should have payed better attention to the comments I was copying 🙈

Comment (aljoscha) [reply src/storage/src/render/persist_sink.rs]: I got you! that's what reviews are for :blush:
