### PR TITLE
compute,adapter: remove dedicated sink `as_of`

### LINKED ISSUE #18042: panic: assertion failed: PartialOrder::less_equal(lower, &new_frontier) in process_subscribes
Sentry Issue: [DATABASE-BACKEND-2MR](https://materializeinc.sentry.io/issues/3990804743/?referrer=github_integration)

```
panic: assertion failed: PartialOrder::less_equal(lower, &new_frontier)
  File "panicking.rs", line 575, in rust_begin_unwind
  File "raw_vec.rs", in mz_compute::compute_state::ActiveComputeState<T>::process_subscribes
  File "server.rs", line 374, in mz_compute::server::Worker<T>::run_client
  File "server.rs", line 321, in mz_compute::server::Worker<T>::setup_channel_and_run_client
  File "server.rs", line 181, in mz_compute::server::Worker<T>::run
...
(21 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by teskje**
This PR removes the dedicated `as_of` frontier that is part of compute sink descriptions (it does not touch storage sinks). Our code sometimes makes the assumption that the sink `as_of` is greater than or equal to the dataflow `as_of` but does not thoroughly check that assumption. The assumption is sometimes violated, which caused at least one known bug (#18042) and perhaps a few unknown ones as well. The approach taken here is to remove the sink `as_of` and rely on the dataflow `as_of` in its stead, thereby also removing the need to worry about the stated assumption.

The advantage of this approach is that we don't need to introduce logic for checking and maintaining the above invariance.

The (AFAICT only) drawback of this approach is that it might make it harder to support dataflows that export multiple sinks in the future. If we want to do that at some point, and if we then need the feature that different sinks can have different `as_of`s, we will need to re-introduce the per-sink `as_of` again.

### Motivation

  * This PR fixes a recognized bug.

Fixes #18042.

### Tips for reviewer

There is a bit of a Chesterton's fence situation here in that I don't know with certainty why the per-sink `as_of` was originally introduced. Maybe it was to prepare for a future where we support multi-sink dataflows, or perhaps the storage sinks require dedicated `as_of`s.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - N/A

### CODE REVIEW

File: src/compute-client/src/types/sinks.rs [hunk 1]
```diff
@@ -29,7 +29,7 @@ pub struct ComputeSinkDesc<S: 'static = (), T = mz_repr::Timestamp> {
     pub from: GlobalId,
     pub from_desc: RelationDesc,
     pub connection: ComputeSinkConnection<S>,
-    pub as_of: SinkAsOf<T>,
+    pub with_snapshot: bool,
     pub up_to: Antichain<T>,
```
Comment (teskje) [inline src/compute-client/src/types/sinks.rs:33]: We could make a similar change with the sink `up_to`, replacing it with the dataflow `until` frontier. But I'm not sure what that entails.

**Review by jkosh44 — APPROVED** [review]

File: src/compute-client/src/types/sinks.proto [hunk 2]
```diff
@@ -21,7 +21,7 @@ message ProtoComputeSinkDesc {
     mz_repr.global_id.ProtoGlobalId from = 1;
     mz_repr.relation_and_scalar.ProtoRelationDesc from_desc = 2;
     ProtoComputeSinkConnection connection = 3;
-    ProtoSinkAsOf as_of = 4;
```
Comment (antiguru) [inline src/compute-client/src/types/sinks.proto:24]: Are we sure that's never been written down? In the future, we should instead reserve 4 and add a new number for `with_snapshot`.

**Review by antiguru — COMMENTED** [review]
Seems fine!

**Review by antiguru — APPROVED** [review]

File: src/compute-client/src/types/sinks.proto (hunk 2 above)
Comment (teskje) [reply src/compute-client/src/types/sinks.proto:24]: > Are we sure that's never been written down?

Yes, if you remove the `RustType` impl for `ComputeSinkDesk` only the `RustType` impl for `DataflowDescription` complains. And if you remove that only the grpc client complains.

> In the future, we should instead reserve 4 and add a new number for with_snapshot.

I'm wary of forcing ourselves to stay backward compatible when we don't need to. It would be fine in this case, but if we added a field with a more complex type, we would have to make that an `Option` to stay backward compatible,  in which case the surrounding code would be burdened with having to somehow handle `None` values.

**Comment by teskje** [comment]
TFTRs!
