### PR TITLE
sql: support typmods in the catalog

### LINKED ISSUE #4884: Cannot create custom types with non-zero numeric scale
In Postgres:
```
CREATE TYPE numeric_range AS RANGE (subtype = numeric(38,5));
```

In MZ:
note that the cast shown below is taken from a [branch on my fork](https://github.com/sploiselle/materialize/tree/custom-type-casts) that implements this feature)

```
materialize=> CREATE TYPE numeric_map AS MAP (key_type=text, value_type=numeric(38,2));

ERROR:  Expected right parenthesis, found left parenthesis
LINE 1: ...umeric_map AS MAP (key_type=text, value_type=numeric(38,2));

materialize=> CREATE TYPE numeric_map AS MAP (key_type=text, value_type=numeric);

CREATE TYPE

materialize=> SELECT '{a=>1.23}'::numeric_map;
 ?column?
----------
 {a=>1}
(1 row)
```

The underlying issue is that the `value_type`'s `GlobalId` refers to the generic `numeric` type, which defaults to 0 scale. And is non-configurable, anyhow.

### PR DESCRIPTION
**Pull request by mjibson**
Closes #11164
Fixes #4884

Adapted from the branch in #11164.

### Motivation

  * This PR adds a known-desirable feature.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - Allow the use of type modifiers (like `timestamp(3)`) in `CREATE TYPE`.

### CODE REVIEW

**Comment by mjibson** [comment]
New PR because it was easier to apply from scratch than rebase.

File: src/catalog/src/builtin.rs [hunk 1]
```diff
@@ -1810,7 +1818,23 @@ pub static MZ_MAP_TYPES: Lazy<BuiltinTable> = Lazy::new(|| BuiltinTable {
...
         .with_column("key_id", ScalarType::String.nullable(false))
-        .with_column("value_id", ScalarType::String.nullable(false)),
+        .with_column(
+            "key_modifiers",
+            ScalarType::List {
+                element_type: Box::new(ScalarType::Int64),
+                custom_id: None,
+            }
+            .nullable(true),
+        )
```
Comment (jkosh44) [inline src/catalog/src/builtin.rs:1828]: I can't fully remember the reason right now, but I'm pretty sure adding a new column in the middle of existing columns (i.e. not at the end) is a breaking change. That's probably fine, but let's remember to check for usages of this table in the next release.

**Review by jkosh44 — APPROVED** [review]
LGTM!

File: src/catalog/src/builtin.rs (hunk 1 above)
Comment (mjibson) [reply src/catalog/src/builtin.rs:1829]: I don't think the order matters that much. I moved the key column after the existing ones.

**Comment by mjibson** [comment]
I think I've gotten through all the test nits. One unexpected change: previously users were able to create nested lists:

```CREATE TYPE nested_list AS LIST (ELEMENT TYPE = list)```

but they would fail on any use (creating a table with a column of that type or casting a string to that type). This PR changes the `CREATE TYPE` statement to fail instead (which seems like objectively the better behavior). I've no idea why this PR caused that behavior change, and don't plan on looking more.

**Comment by benesch** [comment]
> I think I've gotten through all the test nits. One unexpected change: previously users were able to create nested lists:
> 
> `CREATE TYPE nested_list AS LIST (ELEMENT TYPE = list)`
> 
> but they would fail on any use (creating a table with a column of that type or casting a string to that type). This PR changes the `CREATE TYPE` statement to fail instead (which seems like objectively the better behavior). I've no idea why this PR caused that behavior change, and don't plan on looking more.

Oh god. That's a totally asemantic type. Disallowing that seems great.
