### PR TITLE
mz: Fix coverage CI failing cargo-test mz::local

### LINKED ISSUE #25976: coverage: cargo-test mz::local tests::test_local fails
### What version of Materialize are you using?

main

### What is the issue?

```
2024-03-12 23:02:51 UTC	Output: The profile name 'default' already exists. You can either use 'mz profile init -f' to replace it or 'mz profile init --profile <PROFILE>' to choose another name.
2024-03-12 23:02:51 UTC	
2024-03-12 23:02:51 UTC	Output: The profile name 'alternative' already exists. You can either use 'mz profile init -f' to replace it or 'mz profile init --profile <PROFILE>' to choose another name.
2024-03-12 23:02:51 UTC	
2024-03-12 23:02:51 UTC	thread 'tests::test_local' panicked at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5:
2024-03-12 23:02:51 UTC	Unexpected failure.
2024-03-12 23:02:51 UTC	code-<interrupted>
2024-03-12 23:02:51 UTC	stderr=```""```
2024-03-12 23:02:51 UTC	command=`"/mnt/build/llvm-cov-target/release/mz" "profile" "config" "get" "region" "--profile" "alternative" "--config" "/home/materialize/.cache/materialize/mz_test_config.toml"`
2024-03-12 23:02:51 UTC	code=<interrupted>
2024-03-12 23:02:51 UTC	stdout="aws/eu-west-1\n"
2024-03-12 23:02:51 UTC	stderr=""
2024-03-12 23:02:51 UTC	
2024-03-12 23:02:51 UTC	stack backtrace:
2024-03-12 23:02:51 UTC	   0: rust_begin_unwind
2024-03-12 23:02:51 UTC	             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
2024-03-12 23:02:51 UTC	   1: core::panicking::panic_fmt
2024-03-12 23:02:51 UTC	             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
2024-03-12 23:02:51 UTC	   2: core::panicking::panic_display::<assert_cmd::assert::AssertError>
2024-03-12 23:02:51 UTC	             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:196:5
2024-03-12 23:02:51 UTC	   3: <assert_cmd::assert::AssertError>::panic::<assert_cmd::assert::Assert>
2024-03-12 23:02:51 UTC	             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:26:9
2024-03-12 23:02:51 UTC	   4: <<assert_cmd::assert::AssertError>::panic<assert_cmd::assert::Assert> as core::ops::function::FnOnce<(assert_cmd::assert::AssertError,)>>::call_once
2024-03-12 23:02:51 UTC	             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
2024-03-12 23:02:51 UTC	   5: <core::result::Result<assert_cmd::assert::Assert, assert_cmd::assert::AssertError>>::unwrap_or_else::<<assert_cmd::assert::AssertError>::panic<assert_cmd::assert::Assert>>
2024-03-12 23:02:51 UTC	             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1426:23
2024-03-12 23:02:51 UTC	   6: <assert_cmd::assert::Assert>::success
2024-03-12 23:02:51 UTC	             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/assert_cmd-2.0.5/src/assert.rs:156:28
2024-03-12 23:02:51 UTC	   7: local::tests::test_local::test_impl
2024-03-12 23:02:51 UTC	             at ./tests/local.rs:151:23
2024-03-12 23:02:51 UTC	   8: local::tests::test_local::{closure#0}
2024-03-12 23:02:51 UTC	             at ./tests/local.rs:101:20
2024-03-12 23:02:51 UTC	   9: <local::tests::test_local::{closure#0} as core::ops::function::FnOnce<()>>::call_once
2024-03-12 23:02:51 UTC	             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
2024-03-12 23:02:51 UTC	  10: core::ops::function::FnOnce::call_once
2024-03-12 23:02:51 UTC	             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
2024-03-12 23:02:51 UTC	note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Seen in coverage build in https://buildkite.com/materialize/coverage/builds/392#018e34a8-85be-4805-b662-1c26eefcd298 but probably just timing dependent. This is currently blocking cargo-test from finishing in coverage tests, so pretty annoying. This code was previously written by Joaquin. @chaas Is the surfaces team the right assignee for the issue?

ci-regexp: thread 'tests::test_local' panicked

### PR DESCRIPTION
**Pull request by bobbyiliev**
As discussed in #25976 the `mz::local tests::test_local` fails in coverage CI but works locally as expected.

The only way that I was able to make the test fail was by running the test simultaneously in a few different terminals, eg. running the following in 2/3 different terminals:

```
for i in {1..100} ;do cargo test --package mz --test local -- tests --nocapture ;done
```

The idea behind this change is that the `mz` config file will no longer be shared between different tests, but a unique config file will be created which will only be used for the specific test.

Open to suggestions here.

Closes #25976

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by def- — APPROVED** [review]
Thanks!

File: src/mz/tests/local.rs [hunk 1]
```diff
@@ -94,17 +97,21 @@ mod tests {
             get_password(mock)
         );
 
-        fs::write(get_config_path(), main_config_file).unwrap();
+        fs::write(&config_path, main_config_file).expect("Failed to write config file");
     }
 
     /// Tests local commands that do not requires interacting with any API.
     #[mz_ore::test]
     #[cfg_attr(coverage, ignore)] // TODO: Reenable when #25976 is fixed
```
Comment (def-) [inline src/mz/tests/local.rs:105]: You can also remove this line, then the test will run in coverage builds again

**Review by nrainer-materialize — APPROVED** [review]
