### PR TITLE
expr: fix nullability analysis for string_agg

### LINKED ISSUE #11139: Wrong nullability analysis in MIR for string_agg
### What version of Materialize are you using?

v0.22.1-dev (f17007464)

### How did you install Materialize?

Built from source

### What was the issue?

[The way the output type is computed for string_agg](https://github.com/MaterializeInc/materialize/blob/840d55aefe49b90dfae2436dc39e60c886d0a19e/src/expr/src/relation/func.rs#L744-L799) from the input type is not handling the intermediate record wrapping its inputs, which means it always assumes string_agg returns non-null results, even though it can return a null output (on null inputs).

## Repro
```sql
create table repro(f1 int, f2 string);
insert into repro values (1, null);
create or replace view repro_v as select f1, string_agg(f2, 'a') agg from repro group by f1;
```

```
materialize=> select * from repro_v;
ERROR:  internal error: column 1 is not of expected type ColumnType { scalar_type: String, nullable: false }: Null
```

I have tested other aggregate functions, and it seems that this only happens on `string_agg`: other functions with similar implementation (e.g. `jsonb_object_agg` or order-dependent aggregates, like `json_agg`, `array_agg`) don't ignore null inputs.

[Discussion thread on Slack](https://materializeinc.slack.com/archives/C02CB7L4TCG/p1646664649643529)

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by andrioni**
`output_type` was looking at the wrapping record, and not at the underlying input type.
Close #11139.

### Motivation

  * This PR fixes a recognized bug: #11139

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - Fix issue with `string_agg` not working with NULL inputs.

### CODE REVIEW

**Comment by philip-stoev** [comment]
The documentation says:

> The string_agg(value, delimiter) aggregate function concatenates the non-null input values (i.e. value) into [text] (https://materialize.com/docs/sql/types/text). Each value after the first is preceded by its corresponding delimiter, where null values are equivalent to an empty string. The input values to the aggregate can be [filtered](https://materialize.com/docs/sql/functions/filters).

I think this implies that NULLs are not considered and `string_agg` can not return NULL?

**Comment by benesch** [comment]
If they _all_ get filtered out, then you get a NULL, it seems:

```
benesch=# select string_agg(column1, ',') is null from (values (null)) _;
 ?column? 
----------
 t
(1 row)
```

File: src/expr/src/relation/func.rs [hunk 1]
```diff
@@ -787,12 +787,22 @@ impl AggregateFunc {
...
         let nullable = match self {
             AggregateFunc::Count => false,
+            // Use the nullability of the underlying column being aggregated, not the Records wrapping it
+            AggregateFunc::StringAgg { .. } => match input_type.scalar_type {
+                // The outer Record wraps the input in the first position, and any ORDER BY expressions afterwards
+                ScalarType::Record { fields, .. } => match &fields[0].1.scalar_type {
+                    // The inner Record is a (value, separator) tuple
+                    ScalarType::Record { fields, .. } => fields[0].1.nullable,
+                    _ => unreachable!(),
+                },
```
Comment (benesch) [inline src/expr/src/relation/func.rs:803]: Ugh, this is so mind-bending. Do we not need to do this for the other order-sensitive aggregates?

Comment (andrioni) [reply src/expr/src/relation/func.rs:803]: I've checked all the other cases, and they never return nulls, so they are correct!
- `jsonb_agg`: doesn't ignore NULLs, so it returns a JSON array of NULLs.
- `array_agg`: doesn't ignore NULLs, so it returns an array of NULLs.
- `list_agg`: doesn't ignore NULLs, so it returns a list of NULLs.
- `jsonb_agg`: doesn't ignore NULLs, but it should actually _fail_ when the key is null, going to open a separate issue for it later
- `row_number`: not relevant, doesn't process the value

Technically, they should maybe be special cased like `count`, but I wanted to keep this PR more focused.
