### PR TITLE
persist: ensure there is a tokio runtime available in BlobCache

### LINKED ISSUE #10132: persist: "no reactor" panic when using s3 storage
### What version of Materialize are you using?

v0.16.1-dev (883710649)

### How did you install Materialize?

Built from source

### What was the issue?

The get_{trace,unsealed}_batch_async methods on BlobCache don't ensure that there is a tokio runtime, so this (non-deterministically?) blows up at runtime.

### Relevant log output

```source
2022-01-19T21:20:41.538068Z ERROR send_operation{operation="GetObject" service="s3"}:assume_role{op=AssumeRoleInput { role_arn: Some("arn:aws:iam::400121260767:role/admin-instance"), role_session_name: Some("persist"), policy_arns: None, policy: None, duration_seconds: None, tags: None, transitive_tag_keys: None, external_id: None, serial_number: None, token_code: None, source_identity: None }}:send_operation{operation="AssumeRole" service="sts"}: panic: there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread: <unnamed>
location: /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/context.rs:54:26
version: 0.16.1-dev (883710649f95d232ead5872518969a15c1def542)
backtrace:
   0: materialized::handle_panic
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-00198cf80d885deaa-1/materialize/tests/src/materialized/src/bin/materialized/main.rs:842:21
   1: core::ops::function::Fn::call
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:70:5
   2: std::panicking::rust_panic_with_hook
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:628:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:521:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
   5: rust_begin_unwind
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   6: core::panicking::panic_fmt
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   7: core::panicking::panic_display
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:64:5
   8: core::option::expect_failed
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/option.rs:1638:5
   9: core::option::Option<T>::expect
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/option.rs:709:21
      tokio::runtime::context::time_handle::{{closure}}
             at cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/context.rs:54:13
      std::thread::local::LocalKey<T>::try_with
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:399:16
      tokio::runtime::context::time_handle
             at cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/context.rs:52:15
  10: tokio::time::driver::sleep::sleep
  11: <aws_smithy_async::rt::sleep::TokioSleep as aws_smithy_async::rt::sleep::AsyncSleep>::sleep
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-smithy-async-0.34.1/src/rt/sleep.rs:86:20
  12: <alloc::sync::Arc<T> as aws_smithy_async::rt::sleep::AsyncSleep>::sleep
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-smithy-async-0.34.1/src/rt/sleep.rs:37:9
      <aws_config::meta::credentials::lazy_caching::LazyCachingCredentialsProvider as aws_types::credentials::provider::ProvideCredentials>::provide_credentials
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-config-0.4.1/src/meta/credentials/lazy_caching.rs:72:30
  13: <aws_config::default_provider::credentials::DefaultCredentialsChain as aws_types::credentials::provider::ProvideCredentials>::provide_credentials
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-config-0.4.1/src/default_provider.rs:491:13
  14: <alloc::sync::Arc<dyn aws_types::credentials::provider::ProvideCredentials> as aws_types::credentials::provider::ProvideCredentials>::provide_credentials
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-types-0.4.1/src/credentials/provider.rs:205:9
      <aws_types::credentials::provider::SharedCredentialsProvider as aws_types::credentials::provider::ProvideCredentials>::provide_credentials
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-types-0.4.1/src/credentials/provider.rs:243:9
  15: <alloc::sync::Arc<dyn aws_types::credentials::provider::ProvideCredentials> as aws_types::credentials::provider::ProvideCredentials>::provide_credentials
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-types-0.4.1/src/credentials/provider.rs:205:9
      <aws_types::credentials::provider::SharedCredentialsProvider as aws_types::credentials::provider::ProvideCredentials>::provide_credentials
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-types-0.4.1/src/credentials/provider.rs:243:9
  16: aws_http::auth::CredentialsStage::load_creds::{{closure}}
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-http-0.4.1/src/auth.rs:47:15
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
  17: <core::pin::Pin<P> as core::future::future::Future>::poll
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/future.rs:119:9
      <aws_smithy_http_tower::map_request::AsyncMapRequestService<S,M> as tower_service::Service<aws_smithy_http::operation::Request>>::call::{{closure}}
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-smithy-http-tower-0.34.1/src/map_request.rs:67:34
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
  18: <core::pin::Pin<P> as core::future::future::Future>::poll
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/future.rs:119:9
      <aws_smithy_http_tower::map_request::MapRequestFuture<F,E> as core::future::future::Future>::poll
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-smithy-http-tower-0.34.1/src/map_request.rs:115:35
      <aws_smithy_http_tower::map_request::MapRequestFuture<F,E> as core::future::future::Future>::poll
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-smithy-http-tower-0.34.1/src/map_request.rs:115:35
      <aws_smithy_http_tower::parse_response::ParseResponseService<InnerService,ResponseHandler,RetryPolicy> as tower_service::Service<aws_smithy_http::operation::Operation<ResponseHandler,RetryPolicy>>>::call::{{closure}}
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-smithy-http-tower-0.34.1/src/parse_response.rs:109:30
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
  19: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.29/src/instrument.rs:272:9
  20: <core::pin::Pin<P> as core::future::future::Future>::poll
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/future.rs:119:9
      <aws_smithy_client::timeout::TimeoutServiceFuture<InnerFuture> as core::future::future::Future>::poll
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-smithy-client-0.34.1/src/timeout.rs:240:70
      <tower::retry::future::ResponseFuture<P,S,Request> as core::future::future::Future>::poll
             at cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.10/src/retry/future.rs:77:41
  21: <aws_smithy_client::timeout::TimeoutServiceFuture<InnerFuture> as core::future::future::Future>::poll
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-smithy-client-0.34.1/src/timeout.rs:240:70
      aws_smithy_client::Client<C,M,R>::call_raw::{{closure}}
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-smithy-client-0.34.1/src/lib.rs:264:9
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
      aws_smithy_client::Client<C,M,R>::call::{{closure}}
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-smithy-client-0.34.1/src/lib.rs:211:9
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
  22: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.29/src/instrument.rs:272:9
  23: aws_config::sts::assume_role::AssumeRoleProvider::credentials::{{closure}}::{{closure}}
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-config-0.4.1/src/sts/assume_role.rs:185:23
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
  24: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.29/src/instrument.rs:272:9
  25: aws_config::sts::assume_role::AssumeRoleProvider::credentials::{{closure}}
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-config-0.4.1/src/sts/assume_role.rs:168:5
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
  26: <core::pin::Pin<P> as core::future::future::Future>::poll
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/future.rs:119:9
      <aws_smithy_async::future::now_or_later::NowOrLater<T,F> as core::future::future::Future>::poll
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-smithy-async-0.34.1/src/future/now_or_later.rs:135:49
      <aws_types::credentials::provider::future::ProvideCredentials as core::future::future::Future>::poll
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-types-0.4.1/src/credentials/provider.rs:178:13
  27: aws_http::auth::CredentialsStage::load_creds::{{closure}}
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-http-0.4.1/src/auth.rs:47:15
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
  28: <core::pin::Pin<P> as core::future::future::Future>::poll
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/future.rs:119:9
      <aws_smithy_http_tower::map_request::AsyncMapRequestService<S,M> as tower_service::Service<aws_smithy_http::operation::Request>>::call::{{closure}}
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-smithy-http-tower-0.34.1/src/map_request.rs:67:34
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
  29: <core::pin::Pin<P> as core::future::future::Future>::poll
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/future.rs:119:9
      <aws_smithy_http_tower::map_request::MapRequestFuture<F,E> as core::future::future::Future>::poll
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-smithy-http-tower-0.34.1/src/map_request.rs:115:35
      <aws_smithy_http_tower::map_request::MapRequestFuture<F,E> as core::future::future::Future>::poll
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-smithy-http-tower-0.34.1/src/map_request.rs:115:35
      <aws_smithy_http_tower::parse_response::ParseResponseService<InnerService,ResponseHandler,RetryPolicy> as tower_service::Service<aws_smithy_http::operation::Operation<ResponseHandler,RetryPolicy>>>::call::{{closure}}
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-smithy-http-tower-0.34.1/src/parse_response.rs:109:30
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
  30: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.29/src/instrument.rs:272:9
  31: <core::pin::Pin<P> as core::future::future::Future>::poll
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/future.rs:119:9
      <aws_smithy_client::timeout::TimeoutServiceFuture<InnerFuture> as core::future::future::Future>::poll
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-smithy-client-0.34.1/src/timeout.rs:240:70
      <tower::retry::future::ResponseFuture<P,S,Request> as core::future::future::Future>::poll
             at cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.10/src/retry/future.rs:77:41
  32: <aws_smithy_client::timeout::TimeoutServiceFuture<InnerFuture> as core::future::future::Future>::poll
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-smithy-client-0.34.1/src/timeout.rs:240:70
      aws_smithy_client::Client<C,M,R>::call_raw::{{closure}}
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-smithy-client-0.34.1/src/lib.rs:264:9
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
      aws_smithy_client::Client<C,M,R>::call::{{closure}}
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-smithy-client-0.34.1/src/lib.rs:211:9
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
      aws_sdk_s3::client::fluent_builders::GetObject<C,M,R>::send::{{closure}}
             at cargo/registry/src/github.com-1ecc6299db9ec823/aws-sdk-s3-0.4.0/src/client.rs:6250:13
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
      persist::s3::S3BlobCore::get::{{closure}}
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-00198cf80d885deaa-1/materialize/tests/src/persist/src/s3.rs:163:22
  33: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
      <persist::s3::S3Blob as persist::storage::BlobRead>::get::{{closure}}
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-00198cf80d885deaa-1/materialize/tests/src/persist/src/s3.rs:288:9
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
  34: <core::pin::Pin<P> as core::future::future::Future>::poll
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/future.rs:119:9
      futures_executor::local_pool::block_on::{{closure}}
             at cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.19/src/local_pool.rs:315:23
      futures_executor::local_pool::run_executor::{{closure}}
             at cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.19/src/local_pool.rs:90:37
      std::thread::local::LocalKey<T>::try_with
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:399:16
      std::thread::local::LocalKey<T>::with
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:375:9
  35: futures_executor::local_pool::run_executor
             at cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.19/src/local_pool.rs:86:5
      futures_executor::local_pool::block_on
             at cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.19/src/local_pool.rs:315:5
  36: persist::indexed::cache::BlobCache<B>::fetch_trace_batch_sync
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-00198cf80d885deaa-1/materialize/tests/src/persist/src/indexed/cache.rs:202:21
  37: persist::indexed::cache::BlobCache<B>::get_trace_batch_async::{{closure}}
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-00198cf80d885deaa-1/materialize/tests/src/persist/src/indexed/cache.rs:246:23
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:123:18
  38: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/mod.rs:483:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
      std::panicking::try
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
      std::panic::catch_unwind
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
      std::thread::Builder::spawn_unchecked::{{closure}}
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/mod.rs:482:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
  39: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys/unix/thread.rs:106:17
  40: start_thread
  41: clone

materialized encountered an internal error and crashed.

We rely on bug reports to diagnose and fix these errors. Please
copy and paste the above details and file a report at:

    https://materialize.com/s/bug
```
```

### PR DESCRIPTION
**Pull request by danhhz**
Fixes a panic when using s3 storage.

Before, we were making a tokio::runtime::Runtime available in the
thread-local context (tokio calls this "runtime context" but there's
already enough runtimes here) for the entirety of the execution of the
persist runtime. This was clunky (see the bit in start where we had to
make sure it was available for Indexed::new) and error prone (see the
bug this closes). Instead plumb one to BlobCache and internally use it
to make sure it's available in the thread-local context for any calls
into Blob implementations.

Additionally, there has previously been confusion around the "persist
runtime" vs the "async runtime" within src/persist. So, take this
opportunity to rename all imports within src/persist so they're now
tokio::runtime::{Runtime as AsyncRuntime}. This was already done in some
places, so this is just being more consistent about it. We also rename
all variable names of this type to be async_runtime.

Closes #10132

### Motivation

  * This PR fixes a recognized bug

### Tips for reviewer

I think I caught all the "runtime" -> "async_runtime" renames, but feel free to poke around for any I missed.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [N/A] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

File: src/persist/src/indexed/cache.rs [hunk 1]
```diff
@@ -137,8 +151,10 @@ impl<B: Blob> BlobCache<B> {
         let key = key.to_owned();
         // TODO: IO thread pool for persist instead of spawning one here.
```
Comment (danhhz) [inline src/persist/src/indexed/cache.rs:152]: I tried to do this TODO while I was in here but hit some issues I didn't feel like working through quite yet /shrug

**Comment by aljoscha** [comment]
There is one unpatched `use tokio::runtime::Runtime` in `operators/stream.rs`. :1st_place_medal:

File: src/persist/benches/writer.rs [hunk 2]
```diff
@@ -265,9 +265,15 @@ pub fn bench_writes_indexed(c: &mut Criterion) {
...
     let file_blob = new_file_blob("indexed_write_drain_blob", temp_dir.path());
 
+    let async_runtime = Arc::new(AsyncRuntime::new().unwrap());
     let metrics = Arc::new(Metrics::register_with(&MetricsRegistry::new()));
-    let blob_cache = BlobCache::new(build_info::DUMMY_BUILD_INFO, metrics.clone(), file_blob);
-    let compacter = Maintainer::new(blob_cache.clone(), Arc::new(Runtime::new().unwrap()));
+    let blob_cache = BlobCache::new(
+        build_info::DUMMY_BUILD_INFO,
+        metrics.clone(),
+        async_runtime.clone(),
```
Comment (aljoscha) [inline src/persist/benches/writer.rs:273]: nit: we should get to activating that `Arc::clone()` lint.

File: src/persist/src/indexed/cache.rs [hunk 3]
```diff
@@ -137,8 +151,10 @@ impl<B: Blob> BlobCache<B> {
...
         let _ = thread::spawn(move || {
+            let async_guard = cache.async_runtime.enter();
```
Comment (aljoscha) [inline src/persist/src/indexed/cache.rs:154]: Are the places where we spawn new threads the only places where this fixes real bugs, aside from tests where we use a `BlobCache` outside of a runtime context?

File: src/persist/src/runtime.rs [hunk 4]
```diff
@@ -88,34 +88,24 @@ where
...
-    let maintainer = Maintainer::new(blob.clone(), pool.clone());
+    let blob = BlobCache::new(build, metrics.clone(), async_runtime.clone(), blob);
+    let maintainer = Maintainer::new(blob.clone(), async_runtime.clone());
     let indexed = Indexed::new(log, blob, maintainer, metrics.clone())?;
     let mut runtime = RuntimeImpl::new(config.clone(), indexed, rx, metrics.clone());
     let id = RuntimeId::new();
-    let runtime_pool = pool.clone();
     let impl_handle = thread::Builder::new()
         .name("persist:runtime".into())
-        .spawn(move || {
```
Comment (aljoscha) [inline src/persist/src/runtime.rs:109]: We don't need to "enter" the runtime here anymore because the `BlobCache` (and maybe all other places that need a runtime) now make sure they have one themselves?

**Review by aljoscha — APPROVED** [review]
Changes look good! I had some questions to help my understanding of the bug that this fixes.

**Comment by benesch** [comment]
Just driving by, but code like 

https://github.com/MaterializeInc/materialize/pull/10153/files#diff-43953d5c975b2118e2bd1f3a7ef7e4217520254f361d533480b9f741b5ecf3d8R204

jumps out at me! Having to manually remember to enter and exit the Tokio context seems harder than just mandating that a Tokio context is always available? There's always the gotcha with `thread::spawn`, but we could think about introducing `ore::thread::spawn_preserving_tokio`... that'd be useful across the codebase.

Anyway, mostly food for thought. I'm not familiar enough with `persist` to have a real opinion here.

**Review by danhhz — COMMENTED** [review]
> There is one unpatched use tokio::runtime::Runtime in operators/stream.rs.

Done. not sure how I missed that

> Just driving by, but code like
> 
> https://github.com/MaterializeInc/materialize/pull/10153/files#diff-43953d5c975b2118e2bd1f3a7ef7e4217520254f361d533480b9f741b5ecf3d8R204
> 
> jumps out at me! Having to manually remember to enter and exit the Tokio context seems harder than just mandating that a Tokio context is always available? There's always the gotcha with thread::spawn, but we could think about introducing ore::thread::spawn_preserving_tokio... that'd be useful across the codebase.
> 
> Anyway, mostly food for thought. I'm not familiar enough with persist to have a real opinion here.

yeah, i'm aware that this isn't how the rest of the tokio ecosystem works. and i'm sympathetic that it makes persist surprising to people that are used to the tokio ecosystem. there's definitely a future world where I have to stop tilting at this windmill and just give in to the tokio way. however, I think at the moment, the current more explicit style is more obvious and easier to reason about to people who don't have existing tokio expectations

I also disagree with the premise that it's easier to remember to put guards higher up. this PR adds them to every call in BlobCache which is the entirety of the coverage we need. we had it more the way you're suggesting before this and have hit this exact issue twice now (I initially had the guard only around the runtime thread, but there's a single Blob::get call in Indexed::new before that). if anything, I'd love to go the other direction and push them down into the S3Blob impl
