### PR TITLE
persist: add efficient rewrite of timestamp in staged batches

### LINKED ISSUE #24831: Efficiently rewrite timestamps of data staged in s3
When writing to shards from multiple processes - as we expect to do more with the Persist-backed catalog and transaction system - it will be more common for compare-and-append requests to fail. We'll need a cheap way to re-issue those requests with the same data... but with timestamps advanced so they're past the previous upper.

## Action log

* *7 March 2024.* Slip expected release date to Mar 29 with medium confidence, due to prioritizing persist-txn=lazy release ahead of this work.
* *15 February 2024.* Slip expected release date to Mar 15 with medium confidence, due to prioritizing https://github.com/MaterializeInc/materialize/issues/23332 ahead of this work.
* *30 January 2024.* File issue with an expected release date of Mar 1 with medium confidence.

### PR DESCRIPTION
**Pull request by danhhz**
A Batch represents potentially large amounts of data, which may have
partly or entirely been spilled to s3. This call bulk edits the
timestamps of all data in this batch in a metadata-only operation (i.e.
without network calls).

Specifically, every timestamp in the batch is logically advanced_by the
provided frontier.

This method may be called multiple times, with later calls overriding
previous ones, but the rewrite frontier may not regress across calls.

Closes #24831

### Motivation

  * This PR adds a known-desirable feature.

### Tips for reviewer

I tried to pull as many of the mechanical bits into the first few commits as I could, so definitely easier to go commit by commit. Not intending to merge the DNM commit, it's just there to get better CI coverage of this while iterating.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by danhhz** [comment]
Did you come up with an answer for how we'd construct tight-ish lower and upper bounds on the frontier-forwarded data? I'm not sure if the additional flexibility of the idea gets us anything concrete, but willing to defer if we can solve that bit (not personally sure I see what the answer is).

**Comment by bkirwi** [comment]
> Did you come up with an answer for how we'd construct tight-ish lower and upper bounds on the frontier-forwarded data?

Convinced myself we probably don't need to do anything automatic for this, in the same way that `rewrite_ts` doesn't automatically adjust the bounds. For the special case we're interested in here (all timestamps the same) advancing to a frontier should have identical output to `rewrite_ts`, so whatever bounds you're using already should work the same.

**Comment by danhhz** [comment]
Ah! So, we'd still only allow rewriting batches with a single timestamp in them, we're just declaring the rewrite in a different way. I'd misunderstood (or misremembered) the suggestion to be more general. Yeah, I think that should work, though I'd have to type it up to be sure

**Comment by bkirwi** [comment]
> So, we'd still only allow rewriting batches with a single timestamp in them [...]

TBC - I don't think we need to _prevent_ people from rewriting batches with multiple timestamps; I think there's a range of possibilities where the frontier rewrite gives sensible behaviour where the rewrite_ts approach would give an error. I just don't think we need to be able to automatically adjust the bounds to accommodate arbitrary frontiers, since we don't bother adjusting bounds automatically for the `rewrite_ts` either, and the possibility for out-of-bounds data seems pretty equivalent in both cases.

**Comment by danhhz** [comment]
Hmm I think I'm confused again

**Comment by bkirwi** [comment]
[Concretely](https://github.com/MaterializeInc/materialize/commit/9749f7c46df04fc5d947c9396ccb571c3d21f1ca). (That doesn't compile yet, but I think is far enough along to gesture at what I'm talking about? Let me know if it would be helpful to push it along further.)

**Comment by danhhz** [comment]
Ahhh crap sorry, I meant "what would you like me to type" more in the colloquial mz sense than that I needed a literal diff.

However, I think that's helped find what may be the miscommunication! The problem I'm not sure how to solve with the frontier approach is this: given a batch that was originally written, and then rewritten to some other timestamps, how does the bit of logic in compare_and_append work to decide if we need to return `InvalidUsage::InvalidBatchBounds`?

Concretely:

**Comment by danhhz** [comment]
Ah crap sorry! When I said "type" I meant in the colloquial mz sense, didn't mean to put the burden of a literal diff on you 😔 

I think I've realized what the miscommunication is here, though! The thing I don't understand how to do for the frontiers approach is: given a batch that has had timestamps rewritten plus a compare_and_append call, determine whether we should accept the CaA or return an `InvalidUsage::InvalidBatchBounds` (the thing checked by `validate_truncate_batch`).

Specifically, at the moment:
- We require that the "batch bounds" as declared at batch construction time entirely cover the CaA range. This has always been a bit of an odd choice (common intuition is probably the opposite), but it's fallout from trying to make the batch truncation optimization for append sane
- It's unclear to me what the batch bounds should be after the call to rewrite_ts. Maybe we compute them automatically, or maybe we make the rewrite_ts caller provide them and verify. A prereq for this is understanding what times could actually be present in the batch after the rewrite_ts operation:
  - With the single-ts approach, this prereq Q at least is obvious. The batch can only contain data at `new_ts`
  - With the frontier-advance approach, this is some function of at least the rewrite frontier and the old lower and upper of the batch bounds. Not sure how the math on this works out

**Comment by danhhz** [comment]
Thought about this a bit more last night and realized that the answer to the above is much easier if we restrict ourselves to totally ordered timestamps. For a batch known to have a lower `L` and an upper `U`, if you forward all the data to a frontier `F`, then I think the new data will have a lower `L' = max(L, F)` and an upper `U' = max(U, F.step_forward())`

**Comment by bkirwi** [comment]
Yeah, that all seems true. I think the bit I'm stuck on is that the situation seems _precisely_ analogous for the swap-timestamps and the advance-to-frontier cases, so I can't figure out why this question is a sticking point for one approach but not the other.
- Both approaches could hypothetically put timestamps outside the existing bounds.
- For both approaches, adjusting the lower bound seems easy. (Advance it to the new timestamp / the provided frontier.)
- For both approaches, adjusting the upper bound seems impossible in the general case... but it's easy enough to check if the existing / some provided upper bound is good. (Checking that the provided timestamp or the frontier are strictly less than the upper bound.)
  - OTOH, if we let ourselves assume total orders / do +1s like in your last comment, we _can_ invent an upper bound in both cases.

**Comment by danhhz** [comment]
Sorry for the pings, @bkirwi! It'll probably take a few attempts to get this fully passing CI. Feel free to unsubscribe yourself and I'll give you a heads up when this is ready for a look!

File: src/persist-client/src/fetch.rs [hunk 1]
```diff
@@ -701,13 +702,6 @@ where
                 inline_desc,
                 registered_desc
             );
-            assert!(
```
Comment (danhhz) [inline src/persist-client/src/fetch.rs:710]: This had to be removed because a rewritten batch can have a registered (HollowBatch) desc that is arbitrarily far ahead of the one written to s3. We could keep this check for any cases where the rewrite feature has not been used.... except that we can't currently distinguish between "not used" vs "called with minimum timestamp". That could be fixed by switching the ts_rewrite to be an Option, but I discovered this at the last minute, so figured I'd check in again about how we feel about `None` vs `Antichain::from_elem(T::minimum())` before typing it all up.

Personally, I'm a bit sad to lose this, but not sure I particularly think it's critical.

File: src/persist-client/src/internal/state.rs [hunk 2]
```diff
@@ -335,6 +335,65 @@ impl<'a, T> Iterator for HollowBatchRunIter<'a, T> {
     }
 }
 
+impl<T: Timestamp> HollowBatch<T> {
+    pub(crate) fn rewrite_ts(
+        &mut self,
+        frontier: &Antichain<T>,
+        new_upper: Antichain<T>,
+    ) -> Result<(), String> {
+        if PartialOrder::less_equal(&new_upper, frontier) {
```
Comment (danhhz) [inline src/persist-client/src/internal/state.rs:344]: hmm maybe this needs to be `frontier !< new_upper`?

**Review by danhhz — COMMENTED** [review]
Okay @bkirwi this is ready for an initial look! Note that the last commit won't be merged as part of this PR, it's just there to get CI to exercise it more in the short term.

The one thing I haven't done here yet is figure out our forward compatibility story. One option is to merge this one release and simply not use it until at earliest the next release. Seems like we also have some options with dyncfgs, version checks, etc. Probably a good time to take a step back and figure out what we want the precedent for this to be.

**Comment by danhhz** [comment]
> The one thing I haven't done here yet is figure out our forward compatibility story. One option is to merge this one release and simply not use it until at earliest the next release. Seems like we also have some options with dyncfgs, version checks, etc. Probably a good time to take a step back and figure out what we want the precedent for this to be.

Hmm maybe I'm overthinking this with trying to set precedent. In this specific case, it's easy to keep anyone from using it until at earliest the next release, which addresses forward compatibility with no work. Maybe let's just do that? I could also introduce a version check in `Batch::rewrite_ts` if we wanted to be extra cautious

File: src/persist-client/build.rs [hunk 3]
```diff
@@ -51,6 +51,14 @@ fn main() {
...
         ]);
 
+    // Setting `emit_rerun_if_changed(false)` below causes tonic to entirely
+    // skip emitting a "rerun-if-changed", which results in us getting the
+    // default behavior for a build script: to invalidate when any file in the
+    // crate changes. This breaks the fast iteration cycle of datadriven tests
+    // (i.e. touching a tests/ file results in an unnecessary recompile). Fix by
+    // only rerunning this build script if something changes in src/ because all
+    // mz_persist_client protos are in there.
+    println!("cargo:rerun-if-changed=src/");
```
Comment (bkirwi) [inline src/persist-client/build.rs:61]: Thanks for this!

File: src/persist-client/src/fetch.rs (hunk 1 above)
Comment (bkirwi) [reply src/persist-client/src/fetch.rs:710]: > I'd check in again about how we feel about None vs Antichain::from_elem(T::minimum())

I don't feel particularly strongly! Normally I have a mild preference for the latter (since no rewrite is equivalent to the trivial rewrite in practice) but this is a good reason to care about the difference and I can imagine others.

File: src/persist-client/src/fetch.rs [hunk 4]
```diff
@@ -778,7 +767,8 @@ impl Cursor {
                 }
             };
 
-            let t = T::decode(t);
+            let mut t = T::decode(t);
+            t.advance_by(encoded.ts_rewrite.borrow());
```
Comment (bkirwi) [inline src/persist-client/src/fetch.rs:771]: I don't have a good intuition for whether truncation or advancement ought to happen first. I think it's a moot point for now since no batch should ever be written using both features... but please correct me if that's not right!

File: src/persist-client/src/internal/state.rs (hunk 2 above)
Comment (bkirwi) [reply src/persist-client/src/internal/state.rs:344]: Yeah that sounds right! (Equivalent for our timestamp type in practice, but requiring the upper to be strictly greater than the frontier makes it easier to prove that it will never advance any timestamp past the upper.)

**Review by bkirwi — COMMENTED** [review]
I need to do a second pass to review the tests, but overall this is looking good!

File: src/persist-client/src/fetch.rs (hunk 4 above)
Comment (danhhz) [reply src/persist-client/src/fetch.rs:771]: I thought about this, but forgot to write a comment. I have a strong intuition that advancement should come before truncation, but I'm not sure I have a convincing argument for why yet.

> since no batch should ever be written using both features... but please correct me if that's not right!
Ah interesting, I don't think there is anything that would disallow that. I think we'd have to add a check for it. Something like batch upper and CaA upper must be equal and `min(batch lower, batch rewrite_ts)` and CaA lower must be equal?

Comment (bkirwi) [reply src/persist-client/src/fetch.rs:771]: Ah, I meant more that "in the forseeable future" nobody needs both, so if we regret our choice we can swap it around without too much suffering.

But codifying that in an assert sounds reasonable if it's straightforward to do!

Comment (danhhz) [reply src/persist-client/src/fetch.rs:771]: Added the assert and a comment

**Review by bkirwi — APPROVED** [review]
Tests look good! No notes.

I poked CI on a SLT failure. I'm confident it was unrelated to this PR, though it seems like the kind of thing you might have to rebase past... not sure!

Approving despite the do-not-merge commit... I assume you plan to rebase that out, though I don't have any objection if you decide to keep it around!

**Comment by danhhz** [comment]
TFTR! \o/ Gonna rebase and do another nightlies before merging.

I think the DNM commit breaks forward compatibility. Should be safe to merge it in a separate PR after the release candidate gets cut this week, but the real Pv2 version will look a touch different, so may not bother quite yet
