### PR TITLE
ore: make `halt!` use `_exit` to avoid exit handler races

### LINKED ISSUE #21751: timely:work-0[184490]: segfault at 388 ip 000055eb69890d78 sp 00007f7eb6ded350 error 6 in clusterd[55eb6627c000+4672000]
### What version of Materialize are you using?

39d3f407f96761a65fcc836caf47300e416f0f68

### What is the issue?

https://buildkite.com/materialize/nightlies/builds/4013#_
Recently we started seeing segfaults in timely during data-ingest test:
```
Sep 14 15:07:21 ip-10-61-163-179.ec2.internal kernel: timely:work-0[184490]: segfault at 388 ip 000055eb69890d78 sp 00007f7eb6ded350 error 6 in clusterd[55eb6627c000+4672000] likely on CPU 5 (core 1, socket 0) 
```
We don't have coredumps in CI yet (https://github.com/MaterializeInc/materialize/pull/19961), so I'll try to reproduce this locally.

ci-regexp: timely:.*segfault
ci-regexp: tokio-runtime.*segfault
ci-regexp: SUMMARY: AddressSanitizer: double-free \(/usr/local/bin/clusterd
ci-regexp: SUMMARY: AddressSanitizer: double-free /checkout/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp

### PR DESCRIPTION
**Pull request by teskje**
This PR fixes a soundness hole introduced by multiple threads calling `halt!` at the same time, thereby invoking thread-unsafe the libc `exit` function concurrently, which would lead to use-after-frees and segfaults. The fix is to call `_exit` instead, which is thread-safe.

### Motivation

  * This PR fixes a recognized bug.

Fixes #21751

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - N/A

### CODE REVIEW

File: src/ore/src/process.rs [hunk 1]
```diff
@@ -42,6 +42,13 @@
...
-            ::std::process::exit(2);
+        $crate::process::halt();
     }}
 }
+
+/// Helper for the `halt!` macro.
+///
+/// This function exists to avoid that all callers of `halt!` have to explicitly depend on `libc`.
+pub fn halt() -> ! {
+    unsafe { libc::_exit(2) };
```
Comment (teskje) [inline src/ore/src/process.rs:53]: TODO(@teskje) some documentation about the use of `_exit` here

**Comment by teskje** [comment]
@MaterializeInc/testing The second PR re-enables the "Longer Zippy ClusterReplicas" test in the Release Qualification pipeline. Given that it failed once with an unrelated error, should I drop that commit? If I do the "references to already closed issues" check might start triggering on this.

**Comment by nrainer-materialize** [comment]
> @MaterializeInc/testing The second PR re-enables the "Longer Zippy ClusterReplicas" test in the Release Qualification pipeline. Given that it failed once with an unrelated error, should I drop that commit? If I do the "references to already closed issues" check might start triggering on this.

Go ahead, feel free to re-enable that check. We can disable it again if we see that further causes make it fail.
