### PR TITLE
 dataflow,sources: only restore timestamp bindings on workers that need them

### LINKED ISSUE #9777: persistence:  panic: offset should not go backwards, but 9 < 11
### What version of Materialize are you using?

v0.13.1-dev (6a6d7fb29)

### How did you install Materialize?

Built from source

### What was the issue?

The `test/persistence/kafka-source` test panicked as follows at the **end** of the test, where a restart of Mz is done after all the "before" and "after" testdrive files have run:

```
2021-12-28T08:00:27.045762Z  INFO coord::catalog: create sink materialize.public.exactly_once_sink (u3)    
2021-12-28T08:00:27.349187Z ERROR panic: offset should not go backwards, but 9 < 11
thread: timely:work-3
location: src/dataflow/src/source/timestamp.rs:179:9
version: 0.13.1-dev (6a6d7fb29e50f2a557621668a14fbe3c536a45a1)
backtrace:
   0: materialized::handle_panic
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-002e9c5e75f5d0d79-1/materialize/tests/src/materialized/src/bin/materialized/main.rs:842:21
   1: core::ops::function::Fn::call
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:70:5
   2: std::panicking::rust_panic_with_hook
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:628:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:521:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
   5: rust_begin_unwind
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   6: core::panicking::panic_fmt
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   7: dataflow::source::timestamp::TimestampBindingBox::add_binding
   8: dataflow::source::timestamp::TimestampBindingRc::add_binding
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-002e9c5e75f5d0d79-1/materialize/tests/src/dataflow/src/source/timestamp.rs:530:9
      dataflow::server::Worker<A>::handle_command
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-002e9c5e75f5d0d79-1/materialize/tests/src/dataflow/src/server.rs:912:25
   9: dataflow::server::Worker<A>::run
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-002e9c5e75f5d0d79-1/materialize/tests/src/dataflow/src/server.rs:487:17
  10: dataflow::server::serve::{{closure}}
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-002e9c5e75f5d0d79-1/materialize/tests/src/dataflow/src/server.rs:131:9
      timely::execute::execute::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f09f66/timely/src/execute.rs:285:22
      timely_communication::initialize::initialize_from::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f09f66/communication/src/initialize.rs:316:33
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:123:18
  11: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/mod.rs:483:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
      std::panicking::try
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
      std::panic::catch_unwind
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
      std::thread::Builder::spawn_unchecked::{{closure}}
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/mod.rs:482:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
  12: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys/unix/thread.rs:106:17
  13: start_thread
  14: clone
```

### Relevant log output

```source
2021-12-28T08:00:27.045762Z  INFO coord::catalog: create sink materialize.public.exactly_once_sink (u3)    
2021-12-28T08:00:27.349187Z ERROR panic: offset should not go backwards, but 9 < 11
```

### PR DESCRIPTION
**Pull request by aljoscha**
Before, we would restore all existing bindings to all workers, meaning
that workers that are not responsible for a given source id/partition id
combination nevertheless had bindings stored for them. This is
problematic because these workers periodically report those bindings,
meaning they potentially send old bindings to the coordinator that have
been superseded.

This lead to the situation that the timestamp bindings we store in
SQLite have bindings for lower offsets after bindings with higher
offsets, when sorted by the time at which the binding was reported to
the coordinator. This in turn, would lead to panics when restoring
timestamp bindings, because we check that offsets don't go backwards.

The problem only surfaces when restarting materialized multiple times,
which is what some of the newer persistence tests do. Although the
problem is not related to the newly added source persistence code (which
also deals with timestamp bindings).

Fixes #9777

### Tips for reviewer

The first commit adds assertions at the point where we modify timestamp bindings, this makes the problem surface more readily. Before, we needed a cycle of killing/restarting `materialized` to make it appear. I'm still wondering though, why this isn't failing in CI...

We might want to keep that first commit, but only do the checks when running in dev mode? @philip-stoev Any ideas?

The second commit slims down the tests and adds trace logging, that one is only there so you can try and reproduce the bug locally via
```
$ cd test/persistence
$ ./mzcompose run persistence
```

@ruchirK It would be good to check my rationale above about only restoring bindings on workers that need them. I'm also slightly wondering why it worker well before and/or if some of my work might have introduced this behaviour.

@philip-stoev Could you please check that this actually fixes the problem for you?

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [N/A] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/9887)

### CODE REVIEW

**Review by philip-stoev — APPROVED** [review]
The issue is no longer reproducible for me with this branch and the full complement of tests.

I have no idea why this was not caught in CI and I am afraid I can not offer any suggestion about a dedicated test beyond the tests we already have.

**Comment by ruchirK** [comment]
reviewing this now!

File: src/coord/src/catalog/storage.rs [hunk 1]
```diff
@@ -438,6 +438,33 @@ impl Transaction<'_> {
...
+                let offset = MzOffset {
+                    offset: row.get(2)?,
+                };
+
+                Ok((partition, timestamp, offset))
+            }).unwrap()
+            .collect::<Result<Vec<(PartitionId, Timestamp, MzOffset)>, _>>().unwrap();
+
+        let mut latest_offset = 0;
+        for (_pid, _ts, offset) in bindings.iter() {
```
Comment (ruchirK) [inline src/coord/src/catalog/storage.rs:457]: I think you need to reset `latest_offset` to zero when the partition changes -- like the following sequence of

(partition, time, offset) is correct iiuc but would fail the assert

(p1, t1, 100)
(p1, t2, 200)
(p2, t1, 50)

**Comment by philip-stoev** [comment]
@benesch can I try to add a debug build to nightly so that @aljoscha's validation code has a chance to run?

File: src/coord/src/catalog/storage.rs [hunk 2]
```diff
@@ -438,6 +438,33 @@ impl Transaction<'_> {
         }
     }
 
+    fn assert_timestamp_bindings(&self, source_id: &GlobalId) {
+        let bindings: Vec<(PartitionId, Timestamp, MzOffset)> = self.inner
```
Comment (cjubb39) [inline src/coord/src/catalog/storage.rs:442]: Any reason to duplicate this code instead of just calling `load_timestamp_bindings(source_id).unwrap()`?

File: src/coord/src/catalog/storage.rs [hunk 3]
```diff
@@ -528,24 +555,30 @@ impl Transaction<'_> {
...
     pub fn delete_timestamp_bindings(&self, source_id: GlobalId) -> Result<(), Error> {
-        match self
+        let result = self
             .inner
             .prepare_cached("DELETE FROM timestamps WHERE sid = ?")?
-            .execute(params![SqlVal(&source_id)])
-        {
+            .execute(params![SqlVal(&source_id)]);
+
+        self.assert_timestamp_bindings(&source_id);
```
Comment (cjubb39) [inline src/coord/src/catalog/storage.rs:579]: Do you think we might plan to add more assertions in the future? With the one currently in this PR, this assert could never fire after a delete

**Review by cjubb39 — COMMENTED** [review]
I think deciding how much we're okay with this affecting performance will inform where / when exactly we want to call `assert_timestamp_bindings`.

There are places now (e.g. in `delete_timestamp_bindings` and at the top of `compact_timestamp_bindings`) where the assert shouldn't ever be able to fire because of what we check after any inserting every binding.  But if we only run this in dev mode, then keeping them in is probably better future-proofing.

Overall, though, I'm in favor of codifying our invariants with asserts!

**Comment by aljoscha** [comment]
Sorry, I should have said this: the asserts are somewhat throwaway-ish, because I didn't think we'd want to keep them. @ruchirK and @cjubb39 noticed how bad they are... :sweat_smile: 

If we want to keep them I can clean them up, put them into a fn `validate_timestamp_bindings -> Result<(), ()>` and then slap a `debug_assert_eq!(validate_timestamp_bindings(), Ok(()))` in there. What do you think?

**Comment by ruchirK** [comment]
No worries if the asserts are throwaway. I mostly was trying to understand the specific property that was being asserted. I'm going to need a bit of time to read through this PR - I looked through everything and I still don't specifically understand what pre-existing behavior is broken because my understanding is something like:

assume 1 partition and 2 workers

worker 0 assigns

(p1, offset1, t1)
(p1, offset2, t2)

then when we restart, both worker 0 and worker 1 learn about the two bindings. 

Now, I can see how we might go backwards, if say, we compact up to t2, but then worker 1 "informs" the coordinator of (p1, offset1, t1) but i thought this was fine because we only read from sqlite on startup and we do the read in timestamp and offset order.

Maybe said a different way, I thought that broadcasting the timestamp bindings to all workers on restart was fine because writing the timestamp bindings is meant to be idempotent (theres a primary key on (source,partition, time, offset) so if you get a duplicate write sqlite deduplicates it)

Clearly I'm missing something here, because there was a real crash, I'm just not yet sure what.

**Comment by aljoscha** [comment]
The problem is timestamp compaction. This log output should help explain what's going on (keep in mind that the tests kills and restarts materialized multiple times):

```
2022-01-05T19:50:48.878322Z TRACE dataflow::server: Reporting bindings: [(User(1), Kafka(0), 1641412242800, MzOffset { offset: 9 }), (User(1), Kafka(0), 1641412243799, MzOffset { offset: 9 }), (User(1), Kafka(0), 1641412243800, MzOffset { offset: 9 })], prev_frontier: Antichain { elements: [1641412248900] }, new_frontier: Antichain { elements: [1641412248900] }
2022-01-05T19:50:48.879064Z TRACE dataflow::server: Reporting bindings: [(User(1), Kafka(0), 1641412242800, MzOffset { offset: 9 }), (User(1), Kafka(0), 1641412243799, MzOffset { offset: 9 }), (User(1), Kafka(0), 1641412243800, MzOffset { offset: 9 })], prev_frontier: Antichain { elements: [1641412248900] }, new_frontier: Antichain { elements: [1641412248900] }
```

^- These must be the bindings that were restored from the coordinator. Workers initially also report them back to the coordinator because they are new to them but that's fine since it's idempotent. Note that before restart, only one worker would be reporting these, but after one restart, that one binding is broadcast to all workers, and now suddenly all workers report the same binding back to the coordinator.

```
2022-01-05T19:50:49.880613Z TRACE dataflow::server: Reporting bindings: [(User(1), Kafka(0), 1641412249500, MzOffset { offset: 11 }), (User(1), Kafka(0), 1641412249600, MzOffset { offset: 11 }), (User(1), Kafka(0), 1641412249700, MzOffset { offset: 11 })], prev_frontier: Antichain { elements: [1641412249900] }, new_frontier: Antichain { elements: [1641412249900] }
2022-01-05T19:50:50.887650Z TRACE dataflow::server: Reporting bindings: [(User(1), Kafka(0), 1641412249900, MzOffset { offset: 11 }), (User(1), Kafka(0), 1641412250000, MzOffset { offset: 11 }), (User(1), Kafka(0), 1641412250100, MzOffset { offset: 11 }), (User(1), Kafka(0), 1641412250200, MzOffset { offset: 11 }), (User(1), Kafka(0), 1641412250300, MzOffset { offset: 11 }), (User(1), Kafka(0), 1641412250400, MzOffset { offset: 11 }), (User(1), Kafka(0), 1641412250500, MzOffset { offset: 11 }), (User(1), Kafka(0), 1641412250600, MzOffset { offset: 11 }), (User(1), Kafka(0), 1641412250700, MzOffset { offset: 11 }), (User(1), Kafka(0), 1641412250800, MzOffset { offset: 11 })], prev_frontier: Antichain { elements: [1641412250900] }, new_frontier: Antichain { elements: [1641412250900] }
2022-01-05T19:50:51.888157Z TRACE dataflow::server: Reporting bindings: [(User(1), Kafka(0), 1641412251799, MzOffset { offset: 11 }), (User(1), Kafka(0), 1641412251800, MzOffset { offset: 11 })], prev_frontier: Antichain { elements: [1641412251900] }, new_frontier: Antichain { elements: [1641412251900] }
```

^- These are just updates from the one worker that actually reads, and updates bindings.

```
2022-01-05T19:50:51.983330Z TRACE dataflow::server: Reporting bindings: [(User(1), Kafka(0), 1641412251799, MzOffset { offset: 9 })], prev_frontier: Antichain { elements: [1641412252000] }, new_frontier: Antichain { elements: [1641412252000] }
2022-01-05T19:50:52.890810Z TRACE dataflow::server: Reporting bindings: [(User(1), Kafka(0), 1641412251900, MzOffset { offset: 11 }), (User(1), Kafka(0), 1641412252000, MzOffset { offset: 11 }), (User(1), Kafka(0), 1641412252100, MzOffset { offset: 11 }), (User(1), Kafka(0), 1641412252200, MzOffset { offset: 11 }), (User(1), Kafka(0), 1641412252300, MzOffset { offset: 11 }), (User(1), Kafka(0), 1641412252400, MzOffset { offset: 11 }), (User(1), Kafka(0), 1641412252500, MzOffset { offset: 11 }), (User(1), Kafka(0), 1641412252600, MzOffset { offset: 11 }), (User(1), Kafka(0), 1641412252700, MzOffset { offset: 11 }), (User(1), Kafka(0), 1641412252800, MzOffset { offset: 11 })], prev_frontier: Antichain { elements: [1641412252900] }, new_frontier: Antichain { elements: [1641412252900] }
```

Compaction must have happened, and the "old" binding for offset 9 was advanced to the same timestamp as the correct binding for offset 11. Thus it _seems_ new to both the worker and the coordinator which tries to add it to its bindings.

```
2022-01-05T19:50:53.086526Z ERROR panic: assertion failed: `(left == right)`
  left: `Err("Unexpected offset 9 for pid 0. All bindings: [(Kafka(0), 1641412250800, MzOffset { offset: 11 }), (Kafka(0), 1641412251799, MzOffset { offset: 9 }), (Kafka(0), 1641412251799, MzOffset { offset: 11 }), (Kafka(0), 1641412251800, MzOffset { offset: 11 })]")`,
 right: `Ok(())`
```

I cut out some log lines, and this originally ran with 8 workers, so that final assert seems wrong. but this way it's easier to understand the log

**Comment by aljoscha** [comment]
@cjubb39 I cleaned up the asserts, in case we want to keep them. They're still used in places where they could never fire, though... :sweat_smile:

**Comment by cjubb39** [comment]
Let me know if I'm missing something -- it seems like the assert could only actually fire in one place: at the end of the `insert`.  Because it's just one spot, what do you think about getting rid of the rest?  If it were really mix and match where it could occur, I think it might make more sense to leave them in for the sake of future-proofing

I guess better question: where does the assert actually fire when running Philip's repro?

Because it's just running in dev mode, I think it's okay to keep the assert in if you think it'd be useful.

I'll leave the rest of the review up to ruchir / someone else that has a little more confidence in their understanding of how the workers fit together!

**Comment by aljoscha** [comment]
> I guess better question: where does the assert actually fire when running Philip's repro?

It's failing in `insert`, which is what we would expect. So yes, I'd remove all other instances of the check. Thanks!

**Comment by aljoscha** [comment]
@philip-stoev I believe this is only flaky without my eager asserts because on slow machines the restarted materialize doesn't get a chance to report the faulty timestamp bindings back to the coordinator. Even on my machine it doesn't fail for all runs. With my eager asserts, it fails deterministically, and with the fix it doesn't fail at all anymore.

**Comment by ruchirK** [comment]
reviewing this one now!

**Comment by ruchirK** [comment]
I'm sorry I thought about this one today but repeatedly got sidetracked with release stuff. Will think about this in-depth first thing tomorrow morning

**Comment by ruchirK** [comment]
Reviewing this one now! I think I'll have to run the failing test on my machine to really understand whats going on. Let me do that now, and I might hit you up in an hour if I still don't understand things

**Comment by ruchirK** [comment]
Ok. So here's the bit that I'm a little bit stuck on:

I can repro this locally and get something like

```
2022-01-11T15:18:36.335512Z ERROR panic: Unexpected offset: 9, all bindings: [(Kafka(0), 1641914312000, MzOffset { offset: 11 }), (Kafka(0), 1641914313000, MzOffset { offset: 11 }), (Kafka(0), 1641914314999, MzOffset { offset: 9 })]
```

but then when I inspect sqlite3 immediately after the crash I only see a valid sequence of timestamps

```
sqlite> select * from timestamps;
{"User":1}|0|1641914312000|11
{"User":1}|0|1641914313000|11
sqlite>
```

which makes me think that I'm missing something.

**Comment by ruchirK** [comment]
I understand why the invalid insertion doesn't show up -- the insert transaction failed. This got a lot more clear for me after I added trace logging to see what the coordinator is doing too

**Comment by ruchirK** [comment]
Alright so the sequence of events that leads to this happening are:

lets say theres two workers A and B.

worker A originally reads from a kafka source and assigns data from `p1` up to `o1` to `t1`. Great.
restart.
Now worker A and B both know about this binding. If there's no more new offsets, then the bindings will periodically be compacted, and workers A and B will both say things like:

assign all data from `(p1, o1)` to `t2` OR
assign all data from `(p1, o1) to `t3`. The workers will individually do these in order, but I think its possible for the coordinator to receive these out of order. It doesn't really matter because we only read these bindings on restart and the coordinator orders by timestamp. So far so good.

However, if there is new data then only one worker will know about it because only one worker reads the underlying data, and at that point
you could have a scenario where

worker A says to assign data from (p1, o2) to t4, while worker B says to assign data from (p1, o1) to t5. (this seems to occur when worker A is just about to assign data from (p1, o2) to t5 as well, but worker B got in front). 

I think I understand all of this now, and I think the fix makes sense, though it kind of goes against the dataflow / coord separation we're striving for at the moment. I'm not sure what other fixes would also fix this issue.

**Comment by aljoscha** [comment]
Yes, that is a good description of the failure scenario!

How does it go against the separation we're striving for? I think in general, the timestamping logic goes against that, but I don't see how the fix goes against it more.

**Comment by ruchirK** [comment]
it seems like theres more implicit communication between the coord and the dataflow layer that relies on exactly one worker doing something. I think you're right that the whole in-dataflow timestamping is the original malignant tumor here and this isn't a big increase.

**Review by ruchirK — COMMENTED** [review]
I'm making a comment here to tell the github ui that I've reviewed. Afaict, the only bits needed here before a final review pass are to get rid of the test commit and make the assertions safe for multipart topics

**Comment by aljoscha** [comment]
I cleaned this up, PTAL. :smiley:

**Comment by cjubb39** [comment]
It looks like you may have missed removing the assertions from calls other than insert.  Did you still want to do that or do you think there's a reason to keep the others around?

File: src/coord/src/catalog/storage.rs [hunk 4]
```diff
@@ -438,6 +440,29 @@ impl Transaction<'_> {
...
+    fn validate_timestamp_bindings(&self, source_id: &GlobalId) -> Result<(), String> {
+        let bindings_vec = self
+            .load_timestamp_bindings(*source_id)
+            .map_err(|e| format!("{}", e))?;
+
+        let bindings_by_pid = bindings_vec.iter().group_by(|(pid, _ts, _offset)| pid);
+
+        for (pid, bindings) in &bindings_by_pid {
+            let mut latest_offset = 0;
+            for (_pid, _ts, offset) in bindings {
```
Comment (ruchirK) [inline src/coord/src/catalog/storage.rs:452]: you might as well assert that the timestamps go up too? I know `load` does an order by, but that way you'll catch bugs in `load` too in the unlikely event that it ever happens?

**Review by ruchirK — APPROVED** [review]
LGTM!

File: src/coord/src/catalog/storage.rs (hunk 4 above)
Comment (aljoscha) [reply src/coord/src/catalog/storage.rs]: :+1:

**Comment by aljoscha** [comment]
Thanks for the reviews! And yeah, I incorporated those last two comments.

**Review by cjubb39 — APPROVED** [review]
timestamp changes look good to me!
