### PR TITLE
Retry broken connections when establishing...

### LINKED ISSUE #12800: Possibility of process crash during startup leading to split-brain cluster and crash loop
### What version of Materialize are you using?

main

### How did you install Materialize?

Materialize Cloud

### What is the issue?

With the present release of timely, the following pattern can happen. Imagine there are three processes numbered 0, 1, and 2.

1. Process 0 comes up
2. Process 1 comes up and connects to process 0
3. Process 0 crashes for whatever reason (cosmic rays, Kubernetes gremlins, OOM, whatever)
4. Kubernetes brings up process 0 again.
5. Process 2 connects to process 0.
6. Process 2 connects to process 1 -- processes 1 and 2 have now completed initialization.
7. Process 1 still has a TCP handle to the old process 0, which is now closed; it therefore crashes.
8. Process 2 learns that process 1 has crashed, and itself crashes.

To recap, the state is now:

Process 0: Alive, believes it is connected to process 2
Process 1: Dead
Process 2: Dead

9. Process 1 and 2 come up, one of them (doesn't matter which) connects to process 0.
10. Process 0 now believes it has connected to two peers, but only one of the connections is valid, so it crashes.
11. We are now back in the state we were in after step 3 above. Thus, we can now crash-loop indefinitely.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by brennanvincent**
...the initial networking infrastructure.

It still needs testing, but I believe this should fix #12800 -style issues.

We make the following changes:

* Allow a new peer connection to replace an old one (e.g., if peer `n` connects to us, and we already have a connection for peer `n`, just drop the old one)
* Periodically check that all connections are alive, and drop/retry the ones that aren't (in both the await and connect paths)

This approach has a few advantages:
* If a peer we connected to goes down, we will just drop it and wait for Kubernetes to replace it, rather than considering startup to be complete and then immediately crashing when we spin up Timely on the (dead) sockets.
* We will not hang forever trying to connect to a peer.

These properties should combine to prevent deadlocks, crash loops, etc.

### CODE REVIEW

**Comment by brennanvincent** [comment]
The caveat here is that since TCP is an in-order protocol, it's not simple to detect errors after the socket already has some data on it. But that will only happen if a peer crashes after having fully initialized and started sending data, and then it should only cause _one_ round of crashes.

**Comment by brennanvincent** [comment]
Marking as ready for review since `test_computed_shared_fate` is now passing for me locally.

**Comment by brennanvincent** [comment]
`test_computed_shared_fate` ran on scratch 28 times in a row with no errors.

File: src/compute/src/communication.rs [hunk 1]
```diff
@@ -68,46 +69,128 @@ fn create_sockets(
...
+    // We do not want to provide opportunities for the startup
+    // sequence to hang waiting for one of its peers, not noticing that another has gone down;
+    // empirically, we have found it difficult to reason
+    // about whether this results in crash loops and global deadlocks.
+    // Thus, every second, check whether a previously-established connection has
+    // gone away; if so, we clear it and retry it again later.
+    let mut i = 0;
+    while results.iter().any(|r| r.is_none()) {
+        if results[i].is_none() {
+            match TcpStream::connect_timeout(&addresses[i], Duration::from_secs(1)) {
```
Comment (benesch) [inline src/compute/src/communication.rs:154]: This seems a little dangerous. It means we'll never be able to connect if connections take more than 1s, because we restart the connection from scratch on each turn of the loop. Maybe that's okay, but I wouldn't want to bet on it. ISTM you want a separate thread that's doing the GC. Alternatively it seems it could be easier to express this logic with futures? You could `select!` on the connection future and a `time::sleep(Duration::from_secs(1))`, do the GC check, and then come back and resume `await`ing on the _same_ connection attempt.

**Review by benesch — COMMENTED** [review]
Super excited to hear that this fixed the test! One piece of concern about the use of `connect_timeout(1s)`. But I don't have much bandwidth remaining; hopefully Moritz does? Or perhaps someone else from compute?

File: src/compute/src/communication.rs (hunk 1 above)
Comment (brennanvincent) [reply src/compute/src/communication.rs:154]: If TCP connections are routinely taking longer than 1s to spin up then something is badly messed up anyway… but fair point, we might as well deal with this case since it’s not too hard to do so.

Comment (brennanvincent) [reply src/compute/src/communication.rs:154]: I would rather use a separate thread than introduce async/futures stuff where it’s not already being used, so I’ll go with that option.

Comment (brennanvincent) [reply src/compute/src/communication.rs:154]: Oh, actually I don't think we need to do either. It should be fine to just use `connect` without a timeout, here. The important thing isn't the 1s timeout, it's clearing old broken connections and retrying them.

So I think the code can be left 99% as-is, and I can just change `connect_timeout` back to `connect`.

**Review by antiguru — APPROVED** [review]
This looks good. I agree that it's probably fine not to rewrite this as an async task but rather use something similar to the existing infrastructure. I left some nits, but overall I think this is better than what we had before.

File: src/compute/src/communication.rs [hunk 2]
```diff
@@ -68,46 +68,105 @@ fn create_sockets(
...
+
+    // We do not want to provide opportunities for the startup
+    // sequence to hang waiting for one of its peers, not noticing that another has gone down;
+    // empirically, we have found it difficult to reason
+    // about whether this results in crash loops and global deadlocks.
+    // Thus, in between connection attempts, check whether a previously-established connection has
+    // gone away; if so, we clear it and retry it again later.
+    let mut i = 0;
+    while results.iter().any(|r| r.is_none()) {
+        if results[i].is_none() {
```
[the remark this answers is not in the document]
Comment (brennanvincent) [reply src/compute/src/communication.rs:133]: I don't think the round-robin order is important, so I can do this
