### PR TITLE
persist-txn: allow data shards to be forgotten

### LINKED ISSUE #22465: Flaky failure in Maelstrom persist-txn coverage
### What version of Materialize are you using?

58c5323cfd

### What is the issue?

Seen in https://buildkite.com/materialize/nightlies/builds/4745#018b3ffa-3dc6-4166-ae75-fe218ca985b4
```
INFO [2023-10-17 23:37:58,956] jepsen test runner - jepsen.core {:perf {:latency-graph {:valid? true},
        :rate-graph {:valid? true},
        :valid? true},
 :timeline {:valid? true},
 :exceptions {:valid? true},
 :stats {:valid? false,
         :count 24,
         :ok-count 0,
         :fail-count 0,
         :info-count 24,
         :by-f {:txn {:valid? false,
                      :count 24,
                      :ok-count 0,
                      :fail-count 0,
                      :info-count 24}}},
 :net {:all {:send-count 28,
             :recv-count 28,
             :msg-count 28,
             :msgs-per-op 1.1666666},
       :clients {:send-count 26, :recv-count 26, :msg-count 26},
       :servers {:send-count 2,
                 :recv-count 2,
                 :msg-count 2,
                 :msgs-per-op 0.083333336},
       :valid? true},
 :workload {:valid? :unknown,
            :anomaly-types (:empty-transaction-graph),
            :anomalies {:empty-transaction-graph true},
            :not #{},
            :also-not #{}},
 :valid? false}


Analysis invalid! (?????? ???
```
Rerun succeeded. Since nothing was changed from testing-side and this happened 3 times in 2 days (https://buildkite.com/materialize/nightlies/builds/4738#018b3d68-7201-4f2a-872f-055775917419 and https://buildkite.com/materialize/nightlies/builds/4751#018b428d-5bc7-451e-9cae-292f4882f3bd), I'm assuming this might be a regression in product, thus marking as potential release blocker.
Similar failure ~1 year ago: https://github.com/MaterializeInc/materialize/issues/14575

### PR DESCRIPTION
**Pull request by danhhz**
This is necessary to support deleting a table in mz (which requires advancing the persist shard's upper to the empty antichain).

A data shard is removed from the txns set using a `forget` operation that writes a retraction of the registration update at some `forget_ts`. After this, the shard may be used through normal means, such as direct `compare_and_append` writes or tombstone-ing it. To prevent accidental misuse, the forget operation ensures that all writes to the data shard have been applied before writing the retraction.

This PR also removes the restriction that a data shard must be registered to read it with a snapshot. That was added initially because it seems "obvious" (and because reads initially worked differently), but in practice it turns out to be unnecessary and the system is less brittle without the requirement. Specifically:

- The information necessary to read at a given timestamp is simply whether there are any unapplied writes below it.
- At times before the first registration time, there are trivially no unapplied writes.
- Because the forget operation carefully ensures that all writes have been applied before writing the retraction, this stays true for _every_ register ts, including the latest one.
- As a result, we always know the data shard has no unapplied writes up to the first unapplied write of the current registration (or progress_exclusive if there are none).
- (This will remain true when we add compaction, because it will keep the invariant that the txns shard since is held back before every write until it's known to be applied.)

Touches #22173

I think this also...

Fixes #22465

### Motivation

  * This PR adds a known-desirable feature.

### CODE REVIEW

**Comment by danhhz** [comment]
@jkosh44 I've still got a touch of cleanup left here, mind taking a quick look at the high-level and letting me know what bits are confusing?

File: src/persist-txn/src/txns.rs [hunk 1]
```diff
@@ -204,65 +202,61 @@ where
...
+                    let registered = self.txns_cache.registered_at(data_id, &txns_upper);
+                    (!registered).then_some(((key, val), &register_ts, 1))
+                })
                 .collect::<Vec<_>>();
+            // If the txns_upper has passed register_ts, we can no longer write.
+            // Return success if we have nothing left to write or an Error if we
+            // do.
+            if register_ts < txns_upper {
+                if updates.is_empty() {
+                    break;
```
Comment (jkosh44) [inline src/persist-txn/src/txns.rs:246]: I'm a little nervous about this. `updates` contains the shards that have not been registered at `txns_upper`, however the guarantee of this method is that all shards are registered at `register_ts`. If a shard was registered at a timestamps `ts` s.t. `register_ts < ts < txn_upper` I think we are breaking that guarantee.

I'm not sure if that matters at all? Still I wanted to point it out.

File: src/persist-txn/src/txns.rs [hunk 2]
```diff
@@ -289,16 +284,104 @@ where
...
+                // interval before returning, just don't write any updates.
+                vec![]
+            };
+
+            // If the txns_upper has passed forget_ts, we can no longer write.
+            // Return success if we have nothing left to write or an Error if we
+            // do.
+            if forget_ts < txns_upper {
+                if updates.is_empty() {
+                    return Ok(());
```
Comment (jkosh44) [inline src/persist-txn/src/txns.rs:328]: Like register, I'm slightly worried that this might break the guarantee of the function if the shard was forgotten at a timestamp `ts` s.t. `forget_st < ts < tx_upper`.

File: src/persist-txn/src/txns.rs [hunk 3]
```diff
@@ -318,27 +401,6 @@ where
...
-                    register_ts,
-                )
-                .await;
-                data_write
-            });
-        }
-        let data_writes = inits.collect::<Vec<_>>().await;
-        for data_write in data_writes {
-            self.datas.put_write(data_write);
-        }
```
Comment (jkosh44) [inline src/persist-txn/src/txns.rs:340]: Why are we getting rid of this?

**Review by jkosh44 — COMMENTED** [review]
I haven't looked at `txn_read.rs` or `txn_write.rs` yet but at a high level it looks good and makes sense. I'll finish looking at the rest later today.

File: src/persist-txn/src/txns.rs [hunk 4]
```diff
@@ -188,13 +188,11 @@ where
...
-    /// returned with the minimum time the data shards could be registered.
-    /// Second, the data shard will be made readable through `register_ts` by
-    /// appending empty updates to it, if necessary.
+    /// A registration entry is written to the txn shard. If it is not possible
+    /// to register the data at the requested time, an Err will be returned with
+    /// the minimum time the data shards could be registered.
     ///
-    /// This method is idempotent. Data shards registered previously to
+    /// This method is idempotent. Data shards currently registered at
     /// `register_ts` will not be registered a second time.
```
[the remark this answers is not in the document]
Comment (danhhz) [reply src/persist-txn/src/txns.rs:196]: Yup! I'll copy that into the doc (and similarly for forget)

File: src/persist-txn/src/txns.rs (hunk 1 above)
Comment (danhhz) [reply src/persist-txn/src/txns.rs:246]: No, I agree with you. This has been making me nervous, too. I think we just remove this Ok case entirely

File: src/persist-txn/src/txns.rs (hunk 2 above)
Comment (danhhz) [reply src/persist-txn/src/txns.rs:328]: Ditto

File: src/persist-txn/src/txns.rs (hunk 3 above)
Comment (danhhz) [reply src/persist-txn/src/txns.rs:340]: I realized that we no longer needed it now that we switched to the `unblock_reads` approach for reads. In a sense, I'm doing the TODO :D

This is also related to what I was (poorly) trying to explain in the sync yesterday. Once we add compaction, we lose information about the original registration timestamp (it gets compacted forward), so we'd either have to continually do empty CaAs on all registered data shards to maintain this sort of invariant or figure out how to deal without it (i.e. unblock_reads instead of "translating" the as_of)

File: src/persist-txn/src/txn_read.rs [hunk 5]
```diff
@@ -748,29 +896,29 @@ mod tests {
...
 
-        // Register a data shard. Registration advances the physical upper, so
-        // we're able to read at the register ts.
+        // Register a data shard. The paired snapshot would advance the physical
+        // upper, so we're able to read at the register ts.
         cache.push_register(d0, 4, 1);
         cache.progress_exclusive = 5;
-        assert_eq!(cache.data_listen_next(&d0, 4), Ok(ReadDataTo(5)));
-        assert_eq!(cache.data_listen_next(&d0, 5), Ok(WaitForTxnsProgress));
+        // assert_eq!(cache.data_listen_next(&d0, 4), ReadDataTo(5));
```
Comment (danhhz) [inline src/persist-txn/src/txn_read.rs:908]: Just to get ahead of this, I think the `data_listen_next` test basically needs a rewrite to make sure it's hitting all the most interesting edge cases, but I'd like to hold off until the compaction PR to avoid having to do that twice

**Review by jkosh44 — APPROVED** [review]
Overall LGTM!

File: src/persist-txn/src/txns.rs [hunk 6]
```diff
@@ -193,7 +193,10 @@ where
     /// the minimum time the data shards could be registered.
     ///
     /// This method is idempotent. Data shards currently registered at
-    /// `register_ts` will not be registered a second time.
+    /// `register_ts` will not be registered a second time. Specifically, this
+    /// method will return success when the most recent register ts `R` is
+    /// less_equal to `register_ts`` AND there is no forget ts between `R` and
```
[the remark this answers is not in the document]
Comment (danhhz) [reply src/persist-txn/src/txns.rs]: done!

File: src/persist-txn/src/txns.rs [hunk 7]
```diff
@@ -193,7 +193,10 @@ where
...
+    /// `register_ts`?
```
[the remark this answers is not in the document]
Comment (danhhz) [reply src/persist-txn/src/txns.rs]: 🙈 whoops! done

File: src/persist-txn/src/txn_read.rs [hunk 8]
```diff
@@ -198,52 +188,57 @@ impl<T: Timestamp + Lattice + TotalOrder + StepForward + Codec64, C: TxnsCodec>
     ///
     /// Returns Err if that data shard has not been registered at the given ts.
     #[allow(clippy::unused_async)]
```
[the remark this answers is not in the document]
Comment (danhhz) [reply src/persist-txn/src/txn_read.rs]: nope!

File: src/persist-txn/src/txn_read.rs [hunk 9]
```diff
@@ -121,18 +118,13 @@ impl<T: Timestamp + Lattice + TotalOrder + StepForward + Codec64, C: TxnsCodec>
...
-        let time = self
-            .datas
-            .get(data_id)
-            .and_then(|times| times.first().cloned());
-        time.ok_or(NotRegistered {
-            data_id: *data_id,
-            ts: self.progress_exclusive.clone(),
-        })
+    /// Returns whether the data shard was registered to the txns set at the
+    /// given timestamp.
```
[the remark this answers is not in the document]
Comment (danhhz) [reply src/persist-txn/src/txn_read.rs:122]: done!

File: src/persist-txn/src/txns.rs (hunk 1 above)
Comment (jkosh44) [reply src/persist-txn/src/txns.rs]: I think you could re-filter updates based on `register_ts` if you wanted to, but returning an error also seems fine.

Comment (danhhz) [reply src/persist-txn/src/txns.rs]: Ah, yeah, that's an interesting idea, but I think I'm happy with the Err. Persist-txn already has enough inherent subtlety that it's probably worth taking opportunities to be obvious when we can, and this one seems safe enough perf-wise

**Comment by danhhz** [comment]
TFTR!
