### PR TITLE
catalog: Store fingerprints in 0dt migrations

### LINKED ISSUE #28636: legacy upgrade tests fail: failed to read on-disk catalog state: cannot commit a transaction in a read-only catalog
### What version of Materialize are you using?

6fcb05b2b0

### What is the issue?

[Legacy upgrade tests (last version from git)](https://buildkite.com/materialize/nightly/builds/8866#01910369-158b-46a4-950a-3134e650de81) started failing reproducibly:
```
error: catalog inconsistency: catalog state

Caused by:
    failed to read on-disk catalog state: cannot commit a transaction in a read-only catalog

Stack backtrace:
   0: anyhow::__private::format_err
   1: mz_testdrive::run_line_reader::{closure#0}
   2: mz_testdrive::run_string::{closure#0}
   3: testdrive::main::{closure#0}
   4: <tracing::instrument::Instrumented<testdrive::main::{closure#0}> as core::future::future::Future>::poll
   5: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<testdrive::main::{closure#0}>>
   6: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::scheduler::multi_thread::MultiThread>::block_on<tracing::instrument::Instrumented<testdrive::main::{closure#0}>>::{closure#0}, ()>
   7: <tokio::runtime::runtime::Runtime>::block_on::<testdrive::main::{closure#0}>
   8: testdrive::main
   9: std::sys_common::backtrace::__rust_begin_short_backtrace::<fn(), ()>
  10: std::rt::lang_start::<()>::{closure#0}
  11: std::rt::lang_start_internal
  12: main
  13: <unknown>
  14: __libc_start_main
  15: <unknown>

+++ !!! Error Report
1 errors were encountered during execution
files involved: check-from-any_version-noop.td
```
Based on the code changes (https://github.com/MaterializeInc/materialize/compare/d8e46f7c6a...6fcb05b2b0) there seems to be one good candidate for causing this: https://github.com/MaterializeInc/materialize/pull/28583 Edit: That didn't pan out, I now believe https://github.com/MaterializeInc/materialize/pull/28436 is at fault, verifying.

Local reproducer: `bin/mzcompose --find legacy-upgrade down && bin/mzcompose --find legacy-upgrade run default --versions-source=git`. I'll verify if the PR is actually at fault.

ci-regexp: failed to read on-disk catalog state: cannot commit a transaction in a read-only catalog

### PR DESCRIPTION
**Pull request by jkosh44**
This commit fixes an issue with 0dt builtin item migrations. Materialize determines if a builtin item is migrated by comparing a compiled in fingerprint with a durably stored fingerprint. Previously, the 0dt builtin item migrations did not update the durably stored fingerprint after migrating an item. This commit fixes that issue.

Resolves #28636

### Motivation
This PR fixes a recognized bug.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - There are no user-facing behavior changes.

### CODE REVIEW

File: src/adapter/src/catalog/open/builtin_item_migration.rs [hunk 1]
```diff
@@ -175,6 +181,44 @@ async fn migrate_builtin_items_0dt(
         "txn must be in savepoint mode when read_only is true, and in writable mode when read_only is false"
     );
 
+    // 0. Update durably stored fingerprints.
```
Comment (benesch) [inline src/adapter/src/catalog/open/builtin_item_migration.rs:184]: Clever use of "0."

**Review by benesch — APPROVED** [review]
LGTM

File: src/adapter/src/catalog/open/builtin_item_migration.rs (hunk 1 above)
Comment (jkosh44) [reply src/adapter/src/catalog/open/builtin_item_migration.rs:184]: ¯\_(ツ)_/¯
