### PR TITLE
storage: in workers, add internal control dataflow

### LINKED ISSUE #16773: storage: don't use `halt!` in sources and sinks
"don't use `halt!`" here is an umbrella term for: sources and sinks must have a graceful/controlled way of restarting themselves or dealing with errors.

Failing fast was an easy way to get good error recovery in sources and sinks but we cannot do that when we want to let multiple sources and/or sinks share a storage host (or cluster). This is especially important with the long-term goal of unifying compute and storage clusters.

```[tasklist]
### Tasks
 - [x] #16958
 - [x] don't use `halt!` in sources
 - [x] #17208
 - [ ] #17207
 - [ ] (maybe) remove `panic!` in bootup of reclock operator
- [ ] https://github.com/MaterializeInc/materialize/issues/17696
```

### PR DESCRIPTION
**Pull request by aljoscha**
### Motivation

Part of #16773, alternative to #16875 and #16916.

This uses the timely `Sequencer` struct, which implements exactly what we would need out of an internal command dataflow: you can push updates at it from all workers, updates will be broadcast to all workers, and all workers will get the commands in a consistent, ordered sequence.

### Tips for reviewer

Individual commits are meaningful and the first one has a longer description:

1. commit: adds internal control fabric
2. commit: replaces `halt!` in sources by the new `SuspendAndRestart` command
3. commit: add more documentation (could probably merge into first commit...)

Follow-up work:

- Remove `halt!` in sinks
- (maybe) Remove the `panic!` in `reclock.rs`, that fires when the `since` is too advanced. I think there's a race condition between tearing down the old dataflow and calculating a resume upper for the new one. But it _is_ safe to retry that.
- Add failpoints that Philip needs for testing
- Get rid of resume upper calculation in `rehydration.rs`. We now always do that right in the worker, so don't need to do it in the controller anymore. I left it in in order to keep the diff smaller.

Left comments throughout the code. I also added bigger module-level documentation that I'll reproduce here:

```
//! One instance of a [`Worker`], along with its contained [`StorageState`], is
//! part of an ensemble of storage workers that all run inside the same timely
//! cluster. We call this worker a _storage worker_ to disambiguate it from
//! other kinds of workers, potentially other components that might be sharing
//! the same timely cluster.
//!
//! ## Controller and internal communication
//!
//! A worker receives _external_ [`StorageCommands`](StorageCommand) from the
//! storage controller, via a channel. Storage workers also share an _internal_
//! control/command fabric ([`internal_control`](crate::internal_control)).
//! Internal commands go through a `Sequencer` dataflow that ensures that all
//! workers receive all commands in the same consistent order.
//!
//! We need to make sure that commands that cause dataflows to be rendered are
//! processed in the same consistent order across all workers because timely
//! requires this. To achieve this, we make sure that only internal commands can
//! cause dataflows to be rendered. External commands (from the controller)
//! cause internal commands to be broadcast (by only one worker), to get
//! dataflows rendered.
//!
//! The internal command fabric is also used to broadcast messages from a local
//! operator/worker to all workers. For example, when we need to tear down and
//! restart a dataflow on all workers when an error is encountered.
//!
//! ## Async Storage Worker
//!
//! The storage worker has a companion [`AsyncStorageWorker`] that must be used
//! when running code that requires `async`. This is needed because a timely
//! main loop cannot run `async` code.
//!
//! ## Example flow of commands for `CreateSources`
//!
//! With external commands, internal commands, and the async worker,
//! understanding where and how commands from the controller are realized can
//! get complicated. We will follow the complete flow for `CreateSources`, as an
//! example:
//!
//! 1. Worker receives a [`StorageCommand::CreateSources`] command from the
//!    controller.
//! 2. This command is processed in [`StorageState::handle_storage_command`].
//! 3. During processing of that command, we call
//!    [`AsyncStorageWorker::calculate_resume_upper`], which causes a command to
//!    be sent to the async worker.
//! 4. We eventually get a response from the async worker:
//!    [`AsyncStorageWorkerResponse::IngestDescriptionWithResumeUpper`].
//! 5. This response is handled in [`Worker::handle_async_worker_response`].
//! 6. Handling that response causes a
//!    [`InternalStorageCommand::CreateIngestionDataflow`] to be broadcast to
//!    all workers via the internal command fabric.
//! 7. This message will be processed (on each worker) in
//!    [`Worker::handle_internal_storage_command`]. This is what will cause the
//!    required dataflow to be rendered on all workers.
```

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

File: src/storage/src/storage_state.rs [hunk 1]
```diff
@@ -230,21 +248,91 @@ impl<'w, A: Allocate> Worker<'w, A> {
...
-            let mut cmds = vec![];
+            // Worker #0 pushes external commands into the sequencer. All other
+            // workers read them away but ignore them. Instead, other workers
+            // will get commands broadcast from the sequencer.
+            //
+            // NOTE: This seems hairy, but I don't yet see an alternative. We
+            // need a consistent order/interleaving of internal and external
+            // commands, across all workers, so we can't let each worker read
+            // their own external command stream because that would be a side
+            // channel and the ordering could (will) be arbitrary.
```
Comment (teskje) [inline src/storage/src/storage_state.rs:259]: I haven't fully grokked what this PR does yet, so this might be entirely misguided, but:

It seems to me that this approach could make the various clients in the communication stack between controller and instance see responses before they see the corresponding commands. For example, consider a replica with two processes:

* Process 0 receives a `CreateSource` command. Process 1 does not receive it yet because the network is slow or whatever.
* Process 0 sends the `CreateSource` command to Process 1 via the sequencer.
* Process 1 creates its half of the source dataflow and continues flowing it.
* Process 1 sends a `FrontierUppers` response to the controller.
* The communication clients living on the instance-side (as opposed to the controller-side) of Process 1 receive the `FrontierUppers` response before they have seen the `CreateSource` response. They might or might not get confused about the update for a frontier they are not tracking.

So it seems to me that even with this change, clients on the instance-side need to expect to not see all commands (in time).

Comment (aljoscha) [reply src/storage/src/storage_state.rs:259]: yep! You're absolutely right!

I would still have to change the intermediary parts to create the necessary state when they first see a response, similar to how it's done for compute. Overall, I'm somewhat hesitant about the asymmetric messaging approach, but I don't yet see good other ways.

One idea we had initially is for our storage-internal commands to go from worker back to controller, and to then let the controller re-distribute them to all workers. But that seems somewhat complicated, and the idea of an internal control flow looked very appealing.

Comment (bkirwi) [reply src/storage/src/storage_state.rs:259]: Another approach would be to have all workers funnel frontier updates to worker #0, which coalesces them and forwards them on. You can imagine the controller _only_ connecting out to worker 0, and relying on the control dataflow such that all other communication to and from the controller will flow through that worker.

Has the advantage of shifting some of the burden out of the controller / environmentd. But I have not worked out the details.

Comment (teskje) [reply src/storage/src/storage_state.rs:259]: That drawback of Ben's idea is that it puts more of a burden on worker #0. When we introduced the asymmetric command transport, we were briefly thinking about the load skew but figured it was probably fine. If we introduced asymmetric response transport as well, it might not be fine anymore. Maybe not much of an issue for storage since I think `FrontierUppers` is the only storage response that exists right now. But our goal is to merge compute and storage eventually and compute has `PeekResponse`s and `SubscribeResponse`s that can get quite large.

I wonder if we could shard commands/responses between workers somehow. I.e. each command/response is only received/sent by a single worker, with each worker handling a subset. I guess the difficulty would lie in ensuring that responses flow back through the same worker that received the corresponding command. Otherwise the communication clients would be utterly confused :)

Comment (bkirwi) [reply src/storage/src/storage_state.rs:259]: Yeah... I feel like it's fine to have a little skew for control-plane messages, but we'd need to be a lot more careful with the data-plane stuff.

Comment (aljoscha) [reply src/storage/src/storage_state.rs:259]: hrm, it seems Github lost the message I typed up ... 😞 

Taking a step back: maybe it's a problem that `ComputeResponse` is used for _both_ control and data?

For our issue: it'd like to not change how responses are routed back, because it increases the scope of this. Plus we're not 100% whether it's a good solution for the long term.

> Has the advantage of shifting some of the burden out of the controller / environmentd. But I have not worked out the details.

@bkirwi It's already the case that the (storage) controller only has one connection to each storage host, and routing to/from individual workers happens internally. The entrypoint to that is roughly here: https://github.com/MaterializeInc/materialize/blob/6c90a5fad085ce4c359a5c7af7cdddf0d891b372/src/storage/src/server.rs#L133

Comment (petrosagg) [reply src/storage/src/storage_state.rs:259]: One thing that brings tension here is that what we want to impose a total order on is calls to `Worker::dataflow` which mints ids sequentially but this is done *as part* of `CreateSource` commands which do more than that. If we instead re-interpret these commands to mean "start reporting information for these sources" then we could have all the workers independently receiving them from the storage controller and applying them immediately, but that application would **not** install a dataflow, only start the reporting process.

Now, worker 0 will be special and in addition to reacting to these commands by starting its own reporting process it can additionally publish `CreateDataflow` (different name for clarity) internal command to the sequencer. When the other workers receive a `CreateDataflow` command they will install the dataflow, which is now totally ordered so timely is happy, and start *recording* but not *reporting* their frontiers.

This way we have two independent operations than can be interleaved arbitrarily (both create and drop) and no one gets confused. Reporting starts when each local client stack has seen the `CreateSource` command and dataflows get installed only through internal commands through the `Sequencer`. Frontier recording and frontier reporting eventually rendezvous in storage state using their `GlobalId`.

What do you think?

Comment (aljoscha) [reply src/storage/src/storage_state.rs:259]: > This way we have two independent operations than can be interleaved arbitrarily (both create and drop) and no one gets confused. Reporting starts when each local client stack has seen the CreateSource command and dataflows get installed only through internal commands through the Sequencer. Frontier recording and frontier reporting eventually rendezvous in storage state using their GlobalId.

I like this idea about turning `CreateDataflows` into an internal command! But I have some questions/comments about the test.

What would "start reporting information" mean? Is it "put the shared frontiers into `storage_state`"? Because other than that, there is nothing we do activate per source/per sink in the worker itself. The reporting machinery is just reporting on all the frontiers that are there. But in that case, we might as well just put those shared frontier bits into `storage_state` when we render the dataflow. In fact, I think we have to do that, because otherwise the shared frontier information is not there if a worker receives the internal `CreateDataflows` command before if sees the controller-issued `CreateSource` command.

If "start reporting information" was meant about the partitioned client (or whatever it's called), then the current PR is actually quite close to that. I still send all the control messages to all workers, only at the very last step are they ignored for workers that are not worker #0. So I could change the partitioned client back to only report information forward once it has seen the relevant `CreateSource` command for that worker.

I'm getting the feeling that maybe we should have a chat on Zoom about this next week. I  _do_ feel we have a pretty good understanding of the design space now, though!

Comment (petrosagg) [reply src/storage/src/storage_state.rs:259]: > The reporting machinery is just reporting on all the frontiers that are there. But in that case, we might as well just put those shared frontier bits into storage_state when we render the dataflow.

This is exactly what causes the confusion! We shouldn't report on all the frontiers that are there, we should only report the frontiers that we have received a `CreateSource` command for. Concretely, I think storage state needs to change to this:

```rust
struct StorageState {
    recorded_source_uppers: HashMap<GlobalId, Rc<RefCell<Antichain<mz_repr::Timestamp>>>>,
    reported_source_uppers: HashMap<GlobalId, Rc<RefCell<Antichain<mz_repr::Timestamp>>>>,
    ...
}
```

When we receive a `CreateDataflow` we do something like this:

```rust
// Check if the frontier is already being *reported*
let frontier = self.reported_source_uppers[id].cloned().unwrap_or(|| Rc::new(RefCell::new(Antichain::new())));
// Start *recording*
self.recorded_source_uppers.insert(id, frontier);
```

And when we receive a `CreateSource` we do something like this:

```rust
// Check if the frontier is already being *recorded*
let frontier = self.recorded_source_uppers[id].cloned().unwrap_or(|| Rc::new(RefCell::new(Antichain::new())));
// Start *reporting*
self.reported_source_uppers.insert(id, frontier);
```

This way whoever comes first just installs its own private entry. And whoever comes second also installs its own private entry, which shares the frontier via the Rc RefCell.

Agreed on having a high bandwidth zoom on the matter

File: src/storage/src/storage_state.rs [hunk 2]
```diff
@@ -4,12 +4,67 @@
...
+//! example:
+//!
+//! 1. Worker receives a [`StorageCommand::CreateSources`] command from the
+//!    controller.
+//! 2. This command is processed in [`StorageState::handle_storage_command`].
+//! 3. During processing of that command, we call
+//!    [`AsyncStorageWorker::calculate_resume_upper`], which causes a command to
+//!    be sent to the async worker.
+//! 4. We eventually get a response from the async worker:
+//!    [`AsyncStorageWorkerResponse::IngestDescriptionWithResumeUpper`].
```
Comment (bkirwi) [inline src/storage/src/storage_state.rs:53]: Is it possible that we will apply controller commands in a different order than the controller sends them, given that some may be bounced off the async storage worker and others applied immediately? (Is the controller ordering ever important?)

File: src/storage/src/storage_state.rs [hunk 3]
```diff
@@ -4,12 +4,67 @@
...
+//! operator/worker to all workers. For example, when we need to tear down and
+//! restart a dataflow on all workers when an error is encountered.
+//!
+//! ## Async Storage Worker
+//!
+//! The storage worker has a companion [`AsyncStorageWorker`] that must be used
+//! when running code that requires `async`. This is needed because a timely
+//! main loop cannot run `async` code.
+//!
+//! ## Example flow of commands for `CreateSources`
```
Comment (aljoscha) [inline src/storage/src/storage_state.rs:39]: I don't like that this is as complicated as it is, but I also don't see immediate better options. Most of the complexity comes from the extra hop through the async worker while the internal/external command split actually seems nice.

We could do more involved things where we replace the fixed-function `Sequencer` with our own dataflow that does the same thing but also has additional operators like resolving resume uppers using async and the like. I opted to not do that for now to keeps things tractable.

Comment (bkirwi) [reply src/storage/src/storage_state.rs:39]: Could we move the responsibility for polling the command stream to the async worker? (Making run-client responsible for just the timely stuff.)

It would make the command flow at least somewhat more "linear", though I can imagine ownership of the state being a little tricky...

File: src/storage/src/storage_state/async_storage_worker.rs [hunk 4]
```diff
@@ -0,0 +1,166 @@
...
+                                Err(_err) => {
+                                    // Receiver must have hung up.
+                                    break;
+                                }
+                            }
+                        }
+                    }
+                }
+            }
+            tracing::trace!("shutting down async storage worker task");
```
Comment (guswynn) [inline src/storage/src/storage_state/async_storage_worker.rs:125]: is this not `halt`-worthy?

File: src/storage/src/storage_state/async_storage_worker.rs [hunk 5]
```diff
@@ -0,0 +1,166 @@
...
+        self.send(AsyncStorageWorkerCommand::CalculateResumeFrontier(
+            id,
+            ingestion,
+            PhantomData,
+        ))
+    }
+
+    fn send(&self, cmd: AsyncStorageWorkerCommand<T>) {
+        self.tx
+            .send((tracing::Span::current(), cmd))
```
Comment (guswynn) [inline src/storage/src/storage_state/async_storage_worker.rs:149]: interesting, i would have forgotten to add the span here, what broke?

File: src/storage/src/storage_state.rs [hunk 6]
```diff
@@ -550,7 +739,110 @@ impl<'w, A: Allocate> Worker<'w, A> {
...
+                    // ordering of dataflow rendering across all workers.
+                    if worker_index == 0 {
+                        internal_cmd_tx.broadcast(InternalStorageCommand::CreateSinkDataflow(
+                            export.id,
+                            export.description,
+                        ));
+                    }
+                }
+            }
+            StorageCommand::AllowCompaction(list) => {
```
Comment (guswynn) [inline src/storage/src/storage_state.rs:832]: I think these have to be processed in order, otherwise a `SuspendAndRestart` could be interleaved with an `AllowCompaction` and leave some worker running an ingestion that should be dead

File: src/storage/src/storage_state.rs [hunk 7]
```diff
@@ -254,124 +349,208 @@ impl<'w, A: Allocate> Worker<'w, A> {
...
+                    }
+                }
+            }
+
+            // Handle any received commands.
+            {
+                let mut command_sequencer = command_sequencer.borrow_mut();
+                while let Some(internal_cmd) = command_sequencer.next() {
+                    self.handle_internal_storage_command(&mut async_worker, internal_cmd);
+                }
```
Comment (guswynn) [inline src/storage/src/storage_state.rs:409]: I think its _technically_ possible for this to starve the timely worker, as worker 0 could be producing messages faster than we can handle them; not sure if this is worth a comment saying we dont care about that edge case...

**Review by guswynn — COMMENTED** [review]
This is a doozy of a pr to read, but for the most part I think the structure is good; the 2 questions in my mind are:

- how much additional refactoring do we want to package up the various concepts to avoid abstraction leaks between the various parts of `StorageState`?
- how much of that refactoring do we want to do now?

My guess on the latter is "not much for now" which is fine; Reading the pr, I think the only place you have a `TODO` that I think is worth it to do now. Other than that, I have no real larget-scale structural comments other than that I think `AllowCompaction` needs to be sequenced as well; I have other inline nits

File: src/storage/src/internal_control.rs [hunk 8]
```diff
@@ -0,0 +1,61 @@
...
+impl InternalCommandSender for Sequencer<InternalStorageCommand> {
+    fn broadcast(&mut self, internal_cmd: InternalStorageCommand) {
+        self.push(internal_cmd);
+    }
+}
+
+impl<'w, A: Allocate> Worker<'w, A> {
+    pub(crate) fn setup_command_sequencer(&mut self) -> Sequencer<InternalStorageCommand> {
+        // TODO(aljoscha): Use something based on `mz_ore::NowFn`?
+        Sequencer::new(self.timely_worker, Instant::now())
```
[the remark this answers is not in the document]
Comment (aljoscha) [reply src/storage/src/internal_control.rs:59]: it's uses as a "rough" driver of time, but individual workers will also use an additional counter-based timestamp (to form a composite timestamp). And there is a feedback edge to make sure that workers catch up if they have to.

File: src/storage/src/source/source_reader_pipeline.rs [hunk 9]
```diff
@@ -950,8 +953,13 @@ where
 
                     last_reported_status = new_status.clone();
                 }
+                // TODO(aljoscha): Instead of threading through the
+                // `should_halt` bit, we can give an internal command sender
+                // directly to the places where `should_halt = true` originates.
+                // We should definitely do that, but this is okay for a PoC.
```
[the remark this answers is not in the document]
Comment (aljoscha) [reply src/storage/src/source/source_reader_pipeline.rs:959]: I did think about this some more, and it's actually decently tricky: if we emit the `SuspendAndRestart` message right where we emit the new source status we have the same race condition that we have before. It might be that the source dataflow is shut down before the source status makes it to this here operator and we report it.

cc @bkirwi

File: src/storage/src/storage_state.rs [hunk 10]
```diff
@@ -4,12 +4,67 @@
...
+//!
+//! One instance of a [`Worker`], along with its contained [`StorageState`], is
+//! part of an ensemble of storage workers that all run inside the same timely
+//! cluster. We call this worker a _storage worker_ to disambiguate it from
+//! other kinds of workers, potentially other components that might be sharing
+//! the same timely cluster.
+//!
+//! ## Controller and internal communication
+//!
+//! A worker receives _external_ [`StorageCommands`](StorageCommand) from the
```
[the remark this answers is not in the document]
Comment (aljoscha) [reply src/storage/src/storage_state.rs:16]: No, all workers receive external commands. I implemented something similar to what Petros suggested here: https://github.com/MaterializeInc/materialize/pull/16958#discussion_r1064014631.

This is where we make sure that we only report once we have received the _external_ command on a given worker: https://github.com/MaterializeInc/materialize/pull/16958/files?diff=split&w=0#diff-752224caae5760da0459a31cacb0fe5853e6c17de0b4027598e8da60f9c5f092R583

cc @bkirwi because this is relevant for a question you asked elsewhere

File: src/storage/src/storage_state.rs (hunk 2 above)
Comment (aljoscha) [reply src/storage/src/storage_state.rs:53]: Yes! See this comment where I try and explain it: https://github.com/MaterializeInc/materialize/pull/16958/files?diff=split&w=0#r1072847940

File: src/storage/src/storage_state.rs (hunk 3 above)
Comment (aljoscha) [reply src/storage/src/storage_state.rs:39]: > though I can imagine ownership of the state being a little tricky...

It would be decently tricky, because timely (and our usage of it) really is all in on the whole a-worker-is-only-one-thread-and-we-use-Rc-for-sharing thing.

File: src/storage/src/storage_state.rs (hunk 6 above)
Comment (aljoscha) [reply src/storage/src/storage_state.rs:832]: Good catch! They also need the split-into-internal-message treatment. Though we do have to yank the `reported_frontier` here, see this comment: https://github.com/MaterializeInc/materialize/pull/16958/files?diff=split&w=0#r1072847940

File: src/storage/src/storage_state/async_storage_worker.rs (hunk 4 above)
Comment (aljoscha) [reply src/storage/src/storage_state/async_storage_worker.rs:125]: not sure, in the past halting or panicing has turned out to be a bit over eager. I'll mull it over

File: src/storage/src/storage_state/async_storage_worker.rs (hunk 5 above)
Comment (aljoscha) [reply src/storage/src/storage_state/async_storage_worker.rs:149]: Nothing! But I also wrote the persist workers in the storage controller, and they do a similar thing. You think it's not needed?

**Comment by aljoscha** [comment]
Thanks for the review! 😊 You caught some nice problems/subtleties  

> * how much additional refactoring do we want to package up the various concepts to avoid abstraction leaks between the various parts of `StorageState`?

Yeah, I envision some. 🙈 Just to whet your appetite: should operators be allowed to send all the internal commands, or just `SuspendAndRestart`? I strongly suspect we want to restrict what they can send but didn't want to complicate this with more abstractions because there is some time pressure. (Not an excuse for cutting corners, of course!)

> * how much of that refactoring do we want to do now?
> 
> My guess on the latter is "not much for now" which is fine;

agreed

> Reading the pr, I think the only place you have a `TODO` that I think is worth it to do now.

Which `TODO` did you have in mind? Or all of them? Or did I only have one?

> Other than that, I have no real larget-scale structural comments other than that I think `AllowCompaction` needs to be sequenced as well; 

yep! that was a good catch 👍

File: src/storage/src/storage_state/async_storage_worker.rs (hunk 4 above)
Comment (guswynn) [reply src/storage/src/storage_state/async_storage_worker.rs:125]: yeah, i think its possible its fine, if the send side of the channel is gracefully shutting down...

File: src/storage/src/storage_state/async_storage_worker.rs (hunk 5 above)
Comment (guswynn) [reply src/storage/src/storage_state/async_storage_worker.rs:149]: No i think its a great addition!

File: src/storage/src/storage_state.rs (hunk 6 above)
Comment (guswynn) [reply src/storage/src/storage_state.rs:832]: glad its actually a problem I didnt catch a false negative!

**Comment by guswynn** [comment]
>  strongly suspect we want to restrict what they can send but didn't want to complicate this with more abstractions because there is some time pressure. (Not an excuse for cutting corners, of course!)

I agree with this, but would leave it as is for the merge-speed of this pr!

> Which TODO did you have in mind? Or all of them? Or did I only have one?

ugh i messed up here, I just meant the one to put a sender and an activatable in a struct!

File: src/storage/src/storage_state/async_storage_worker.rs [hunk 11]
```diff
@@ -0,0 +1,166 @@
...
+
+use mz_persist_client::cache::PersistClientCache;
+use mz_persist_types::Codec64;
+use mz_repr::GlobalId;
+use mz_service::local::Activatable;
+use mz_storage_client::controller::CollectionMetadata;
+use mz_storage_client::controller::ResumptionFrontierCalculator;
+use mz_storage_client::types::sources::IngestionDescription;
+
+/// A worker that can execute command that come in on a channel and returns
```
Comment (teskje) [inline src/storage/src/storage_state/async_storage_worker.rs:33]:
```suggestion
/// A worker that can execute commands that come in on a channel and returns
```

File: src/storage/src/storage_state/async_storage_worker.rs [hunk 12]
```diff
@@ -0,0 +1,166 @@
...
+        let (response_tx, response_rx) = crossbeam_channel::unbounded();
+
+        mz_ore::task::spawn(|| "AsyncStorageWorker", async move {
+            while let Some(cmd) = command_rx.recv().await {
+                // Peel off all available commands. This allows us to catch up
+                // if we fall behind.
+                let mut commands = vec![cmd];
+                while let Ok(cmd) = command_rx.try_recv() {
+                    commands.push(cmd);
+                }
```
Comment (teskje) [inline src/storage/src/storage_state/async_storage_worker.rs:85]: Can you explain the benefit of collecting the currently pending commands in a vec here vs. reading them one-by-one in the above while loop?

**Review by teskje — APPROVED** [review]
LGTM, I just have nits.

Have you thought about what happens when multiple workers determine the same source to be broken at roughly the same time (assuming that is possible)? We would see multiple 'suspend-and-resume' commands. I think it is fine if they all arrive before the source was re-created. And I think it is also fine if some of them arrive only after the source has already been re-created. Though in the latter case the source might be destroyed and re-created several times.

File: src/storage/src/internal_control.rs [hunk 13]
```diff
@@ -0,0 +1,61 @@
...
+//
+// Use of this software is governed by the Business Source License
+// included in the LICENSE file.
+
+//! Types for cluster-internal control messages that can be broadcast to all
+//! workers from individual operators/workers.
+
+use std::time::Instant;
+
+use mz_storage_client::types::sinks::{MetadataFilled, StorageSinkDesc};
```
[the remark this answers is not in the document]
Comment (aljoscha) [reply src/storage/src/internal_control.rs:11]: ahhh, I never managed to make neovim/rust-analyzer add imports in the right place ... :see_no_evil:

File: src/storage/src/internal_control.rs [hunk 14]
```diff
@@ -0,0 +1,61 @@
...
+/// on them.
+#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
+pub enum InternalStorageCommand {
+    /// Suspend and restart the dataflow identified by the `GlobalId`.
+    SuspendAndRestart(GlobalId),
+    /// Render an ingestion dataflow at the given resume frontier.
+    CreateIngestionDataflow(
+        GlobalId,
+        IngestionDescription<CollectionMetadata>,
+        Antichain<mz_repr::Timestamp>,
```
[the remark this answers is not in the document]
Comment (aljoscha) [reply src/storage/src/internal_control.rs:34]: it's a `resumption_frontier`, will change to named fields

File: src/storage/src/internal_control.rs (hunk 13 above)
[the remark this answers is not in the document]
Comment (teskje) [reply src/storage/src/internal_control.rs:11]: I don't think there is a way, sadly :( It should be possible to hack together a script that uses regex matching to lint import order, but that is the best idea I have so far.

**Comment by aljoscha** [comment]
> Have you thought about what happens when multiple workers determine the same source to be broken at roughly the same time (assuming that is possible)? We would see multiple 'suspend-and-resume' commands. I think it is fine if they all arrive before the source was re-created. And I think it is also fine if some of them arrive only after the source has already been re-created. Though in the latter case the source might be destroyed and re-created several times.

I have, and yes we would see multiple restarts. I think that's fine for now because these should be rare, and I didn't want to complicate things. But we might have to revisit if this becomes a problem.

File: src/storage/src/storage_state.rs [hunk 15]
```diff
@@ -254,124 +349,208 @@ impl<'w, A: Allocate> Worker<'w, A> {
                 last_stats_time = Some(Instant::now());
             }
 
+            // Worker #0 pushes external commands into the sequencer. All other
+            // workers read them away but ignore them. Instead, other workers
+            // will get commands broadcast from the sequencer.
```
[the remark this answers is not in the document]
Comment (aljoscha) [reply src/storage/src/storage_state.rs:354]: forgot to remove! :see_no_evil:

File: src/storage/src/storage_state.rs [hunk 16]
```diff
@@ -254,124 +349,208 @@ impl<'w, A: Allocate> Worker<'w, A> {
...
+            AsyncStorageWorkerResponse::IngestDescriptionWithResumeUpper(
+                id,
+                ingestion_description,
+                resume_upper,
+            ) => {
+                // Broadcast a message that makes all workers render
+                // dataflows. We broadcast this from one worker to
+                // make sure that we start at the same frontier on
+                // all workers.
+                if self.timely_worker.index() == 0 {
```
[the remark this answers is not in the document]
Comment (aljoscha) [reply src/storage/src/storage_state.rs:430]: Yes, will change to an assert, and also add a comment explaining things.

File: src/storage/src/storage_state.rs [hunk 17]
```diff
@@ -396,11 +575,16 @@ impl<'w, A: Allocate> Worker<'w, A> {
...
+            let reported_frontier = if let Some(reported_frontier) =
+                self.storage_state.reported_frontiers.get_mut(id)
+            {
+                reported_frontier
+            } else {
+                // Frontier reporting has not yet been started for this object.
+                // Potentially because this timely worker has not yet seen the
+                // `CreateSources` command.
+                continue;
+            };
```
[the remark this answers is not in the document]
Comment (aljoscha) [reply src/storage/src/storage_state.rs:587]: I had read that but I'm still not used to them :ok_hand:

**Comment by aljoscha** [comment]
I tried to address all comments. I did have to rebase on `main` to fix conflicts, but kept all changes as `fixup!` commits, so you can eyeball the changes compared to the last version. Please take another look! :pray:
