### PR TITLE
Fix date_trunc() behavior for decades, centuries and millenniums and add the ability to extract() these values out of a timestamp.

### LINKED ISSUE #5057: date_trunc() behaves incorrectly when asked to truncate to millennium, century or decade
Hi, I've been following timely/differential dataflow and Materialize (and the highly enjoyable blog posts from Frank, Arjun et al.) for a couple of months now, and finally decided to dip my toes into these projects.

I've been thinking of pitching this to the company I work at, as we already work with Kafka and the Confluent stack and this would solve many of our issues at the same time, issues that libraries we use like Kafka Streams (and ksqlDB on top of it) are either too inadequate, incorrect or inefficient to solve.

As part of this I'm setting up a demo, and it's going swimmingly with some minor hiccups, mainly related to timestamp conversion between time zones that observe daylight savings time, which is unimplemented (and I would love to assist with it).

Exploring the code base, and playing around in psql I noticed some other minor issues with timestamps so I opened up a small draft PR to fix it/add functionality, to acquaint myself with the contribution and review process.

### What version of Materialize are you using?

```
$ materialized -v

v0.5.4-dev
```

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [x] Built from source

### What was the issue?
The current date_trunc() behavior in Materialize doesn't match the behavior of postgres when truncating dates by millennium, century or decade.

Some of the timestamp extraction methods in extract() don't work.

I opened #5056 to fix these issues.

### Is the issue reproducible? If so, please provide reproduction instructions.
expected:
```
select date_trunc('millennium', timestamp '2000-01-01');
1001-01-01 00:00:00

select date_trunc('century', timestamp '1900-01-01');
1801-01-01 00:00:00

select date_trunc('millennium', timestamp '0001-01-01' - interval '1 day');
-0999-01-01 00:00:00

select date_trunc('decade', timestamp '0001-01-01' - interval '2 years');
-0010-01-01 00:00:00
```

got:
```
select date_trunc('millennium', timestamp '2000-01-01');
2001-01-01 00:00:00

select date_trunc('century', timestamp '1900-01-01');
1901-01-01 00:00:00

select date_trunc('millennium', timestamp '0001-01-01' - interval '1 day');
0001-01-01 00:00:00

select date_trunc('decade', timestamp '0001-01-01' - interval '2 years');
0000-01-01 00:00:00
```

### PR DESCRIPTION
**Pull request by zRedShift**
Fixes #5057

[Postgres implementation of truncation and extraction](https://github.com/postgres/postgres/blob/master/src/backend/utils/adt/timestamp.c)

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5056)

### CODE REVIEW

**Comment by benesch** [comment]
Thanks very much! @quodlibetor or @sploiselle, can you review? Also, we'll need to get some test cases for the new/changed behavior.

**Comment by zRedShift** [comment]
Hey @benesch, thanks for the quick consideration. I added some tests in test/sqllogictest, hopefully it's enough. The additions don't work for INTERVAL/TIME date_part()/date_trunc() functions yet, but those require more work due to being separated from timestamps, dates and date-times, so I think it should go into a separate PR.

File: src/expr/src/scalar/func.rs [hunk 1]
```diff
@@ -1448,6 +1448,30 @@ pub trait TimestampLike: chrono::Datelike + chrono::Timelike + for<'a> Into<Datu
...
+    fn extract_millennium(&self) -> f64 {
+        f64::from((self.year() + if self.year() > 0 { 999 } else { -1_000 }) / 1_000)
+    }
+
+    fn extract_century(&self) -> f64 {
+        f64::from((self.year() + if self.year() > 0 { 99 } else { -100 }) / 100)
+    }
+
+    fn extract_decade(&self) -> f64 {
+        f64::from(self.year().div_euclid(10))
```
Comment (sploiselle) [inline src/expr/src/scalar/func.rs:1472]: Euclidean division doesn't produce different results than standard division in the provided test cases. Can you let me know why you chose this method, or provide a test case that standard division fails?

Comment (zRedShift) [reply src/expr/src/scalar/func.rs:1472]: The current version of Materialize will return an error on the sqllogictest for decade extraction, "unsupported timestamp units 'decade'". PostgreSQL will return the right result, "200 200 199 0 0 -1 -1 -2".
The years obtain from self.year() are [2001, 2000, 1999, 1, 0, -1, -10, -11] in the test.
Had I implemented it as
```
fn extract_decade(&self) -> f64 {
    f64::from(self.year() / 10)
}
```

That is, using normal division, Materialize would return "200 200 199 0 0 0 -1 -1", which is not how postgres handles it.

**Comment by quodlibetor** [comment]
Thanks for this @zRedShift! The code looks reasonable, I'm trying to wrap my head around the exact semantics of this math, and it's kind of comforting that postgres has some of the same thoughts as I do:

https://github.com/postgres/postgres/blob/a58db3aa10e62e4228aa409ba006014fa07a8ca2/src/backend/utils/adt/timestamp.c#L4007-L4018

**Comment by zRedShift** [comment]
Yep, just following their logic for feature parity. If only the CE started with the year 0 most of this math could've been spared, but we're not that lucky.

You'd think, why would a real-time streaming database concern itself with timestamps of events that happened over 2 millennia ago? But having a faithful reproduction of the original behavior is still nice to have.

File: src/expr/src/scalar/func.rs (hunk 1 above)
Comment (sploiselle) [reply src/expr/src/scalar/func.rs:1472]: Ah, you are correct!

**Comment by quodlibetor** [comment]
> why would a real-time streaming database concern itself with timestamps of events that happened over 2 millennia ago?

That high-volume computational archaeology 😂 . I agree doing this right is important!

**Review by quodlibetor — APPROVED** [review]
LGTM!

Thanks again! Sorry this took awhile, I wanted to make sure that I understood it! 

I've got one nit, but if you'd rather not handle it I'm happy to merge as-is, just let me know.

File: src/repr/src/adt/datetime.rs [hunk 2]
```diff
@@ -96,7 +96,9 @@ impl FromStr for DateTimeUnits {
             "isodow" => Ok(Self::IsoDayOfWeek),
             "isodoy" => Ok(Self::IsoDayOfYear),
             "h" | "hour" | "hours" | "hr" | "hrs" => Ok(Self::Hour),
-            "microsecond" | "microseconds" => Ok(Self::Microseconds),
+            "us" | "usec" | "microsecond" | "microseconds" | "useconds" | "usecs" => {
```
[the remark this answers is not in the document]
Comment (zRedShift) [reply src/repr/src/adt/datetime.rs:99]: I agree, that's a good change. I just modelled it to have the same order as milliseconds down below. So I'll change the order for both of those.

BTW, I've seen other codebases use [burntsushi's fst](https://github.com/burntsushi/fst) when there are so many strings to match since the code generated from a match expression doesn't turn the strings into a trie, but since the statements just get parsed once I don't think there's any benefit from using it.

[the remark this answers is not in the document]
Comment (quodlibetor) [reply src/repr/src/adt/datetime.rs]: Indeed, in this case it's basically part of the query compilation step so hopefully isn't often in a hot path. We generally like to have benchmarks or other evidence for optimizations that make code meaningfully more complex (even if only under the hood). We should keep it in m ind, though, there might be some places where it would help!

**Comment by quodlibetor** [comment]
Thanks again for this!
