### PR TITLE
adapter,expr: reject unmaterializable functions in WHERE clauses

### LINKED ISSUE #15171: `current_time()` documented as unmaterializable, but is materializable
### What version of Materialize are you using?

main

### How did you install Materialize?

Materialize Cloud

### What is the issue?

The `current_timestamp()` function is (rightly) documented as unmaterializable, but can be materialized, for example like so. I have no idea what this does. 
```
materialize=> create materialized view temp as select 1 where current_timestamp() > current_timestamp();
CREATE MATERIALIZED VIEW
materialize=> 
```

Selecting from the view produces an error, which is great but probably something we should have caught at view formation time:
```
materialize=> select * from temp;
ERROR:  Evaluation error: internal error: cannot evaluate unmaterializable function: CurrentTimestamp
materialize=> 
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by benesch**
The logic in `prep_relation_expr` was not being careful to look for unmaterializable expressions in non-temporal expressions in an MfpPlan, which could allow invalid references to unmaterializable functions in WHERE clauses.
    
Also improve the error message for current_timestamp specifically to give a hint to use mz_now instead.
    
Fix #15171.

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - n/a

### CODE REVIEW

File: src/expr/src/linear.rs [hunk 1]
```diff
@@ -1703,6 +1703,18 @@ pub mod plan {
             }
         }
 
+        /// Returns an iterator over mutable references to all non-temporal
+        /// scalar expressions in the plan.
+        ///
+        /// The order of iteration is unspecified.
+        pub fn iter_nontemporal_exprs(&mut self) -> impl Iterator<Item = &mut MirScalarExpr> {
```
Comment (benesch) [inline src/expr/src/linear.rs:1710]: Kind of a gross public function to have to expose, but it does the job. Open to suggestions.

Comment (mjibson) [reply src/expr/src/linear.rs:1710]: Visitor that takes a closure that takes the current item and return whether it should be visited?

**Review by mjibson — APPROVED** [review]

**Review by frankmcsherry — APPROVED** [review]
Seems .. I don't want to say "good" but .. seems appropriate! I want a Rust visibility modifier other than `pub` that means "this can be used exactly one place in the code". :)

**Comment by benesch** [comment]
If only Rust had [`friend`](https://www.geeksforgeeks.org/friend-class-function-cpp/) methods!

I'm going to merge as-is, since you both approved. @mjibson I think a visitor-taking method instead of an iterator-returning method still has the same defect that it's a method that ought to be called in only one place.

**Comment by mjibson** [comment]
Ah. I misunderstood and thought you were asking about ways to avoid the various .chain calls!

**Comment by benesch** [comment]
> Ah. I misunderstood and thought you were asking about ways to avoid the various .chain calls!

Ah! No, I was pretty happy with the `chain` calls!
