### PR TITLE
compute: reconcile dataflows with transient IDs

### LINKED ISSUE #26155: compute: Restarting environmentd can cause unexpected re-hydrations
### What version of Materialize are you using?

v0.92.0

### What is the issue?

Recently we had to restart an instance of `environmentd`, this caused a few (but not all) `clusterd`s to restart, requiring dataflows to rehydrate. Interestingly I didn't observe any downtime from k9s, i.e. the pods themselves didn't restart, so this seems more like a compute issue than a cloud issue.

We would like to solve this because restarting `environmentd` can already be disruptive to the customer, but should only last ~1 minute. Re-hydrating dataflows on the other hand can take almost arbitrarily long and thus is _much_ more disruptive.

See more discussion around the referenced instance [here in Slack](https://materializeinc.slack.com/archives/C06Q94A843D/p1710859044755659).

### PR DESCRIPTION
**Pull request by teskje**
When the optimizer produces a `DataflowDescription` it sometimes needs to allocate transient `GlobalId`s to make objects referenceable internally. The IDs it receives when doing so depend on which commands have previously been run against the Mz instance since its last restart, so they are not deterministic. Compute reconciliation that compares `DataflowDescription`s as-is may thus fail and unnecessarily recreate dataflows because the compared `DataflowDescription`s contain different internal transient IDs, even though they might be semantically equivalent.

This PR fixes the described defect by normalizing internal transient IDs before comparing `DataflowDescription`s during reconciliation.

### Motivation

  * This PR fixes a recognized bug.

Fixes #26155

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - N/A

### CODE REVIEW

File: src/compute-types/src/dataflows.rs [hunk 1]
```diff
@@ -439,26 +439,90 @@ where
...
+    S: Clone + PartialEq,
+    T: Clone + timely::PartialOrder,
+{
     /// Determine if a dataflow description is compatible with this dataflow description.
     ///
     /// Compatible dataflows have equal exports, imports, and objects to build. The `as_of` of
     /// the receiver has to be less equal the `other` `as_of`.
     ///
     // TODO: The semantics of this function are only useful for command reconciliation at the moment.
     pub fn compatible_with(&self, other: &Self) -> bool {
```
Comment (antiguru) [inline src/compute-types/src/dataflows.rs:454]: Nit: Update documentation to mention that this call normalizes transient IDs, and that its cost is proportional to `self` and `other`.

File: src/compute-types/src/dataflows.rs [hunk 2]
```diff
@@ -439,26 +439,90 @@ where
...
+                id
+            }
+        };
+
+        let objects_to_build = self
+            .objects_to_build
+            .iter()
+            .map(|obj| BuildDesc {
+                id: maybe_replace(obj.id),
+                plan: &obj.plan,
```
Comment (antiguru) [inline src/compute-types/src/dataflows.rs:501]: Surprised to see that we don't have to replace any ID in the plan. Is this because we only use transient IDs between dataflows and sinks, or dataflows and peeks? Otherwise, there might be some part in `obj.plan` that mentions the now-replaced ID and hence would not compare correctly in the test above in `compatible_with`.

**Review by antiguru — APPROVED** [review]
This approach seems fine, thank you! I'm slightly concerned about the maintainability because someone introducing transient IDs might not be aware of this logic, and so it could break again. What about filing an issue to solve this such that objects in the catalog never use transient IDs, and the binding between dataflows and sinks uses a different mechanism?

File: src/compute-types/src/dataflows.rs (hunk 2 above)
Comment (teskje) [reply src/compute-types/src/dataflows.rs:501]: `Plan`s in `objects_to_build` either refer to objects imported through `index_imports` and `source_imports`, or to other objects in `objects_to_build`. The first group is excluded here through the `external_ids` check, so we only need to look at the second case.

AFAICT the only situation where `Plan`s reference other `objects_to_build` today is when the dataflow consists of multiple view and the top-level view draws from outputs of lower-level views. Views always have non-transient IDs, so these references should never use transient `GlobalId`s.

Of course this might change in the future. If it does, reconciliation will start failing sometimes, which fortunately only regresses performance, not correctness. Still, I'd also feel more comfortable with a more robust solution.

Comment (teskje) [reply src/compute-types/src/dataflows.rs]: I've pushed a fixup commit that also replaces IDs within the plans. The only drawback is that we now have to clone the plans, so this becomes a bit more expensive. But then again, we only call this method during reconciliation, so it's probably not a big deal.

**Comment by teskje** [comment]
TFTR!
