### PR TITLE
pg-cdc: proactively send keepalives to prevent timeouts

### LINKED ISSUE #6827: pg-cdc: replicating a large transaction causes a timeout on the Pg side, Mz fails to recover, source fails to make progress
### What version of Materialize are you using?

```
v0.7.4-dev (5e4089e4d) 
```

### What was the issue?

Deleting all rows from a table with 10M 11-byte rows causes such a huge replication event that Mz is unable to handle it.

Possibly due to an implementation issue at Postgres, an unwarranted timeout occurs.

On the Postgres side, the following messages are printed out:

```
2021-05-23 12:18:46.569 UTC [73] LOG:  starting logical decoding for slot "materialize_3e7d0a65ef9742538fa3bf6555e76938"
2021-05-23 12:18:46.569 UTC [73] DETAIL:  Streaming transactions committing after 0/2C7228C8, reading WAL from 0/2C7228C8.
2021-05-23 12:18:46.569 UTC [73] LOG:  logical decoding found consistent point at 0/2C7228C8
2021-05-23 12:18:46.569 UTC [73] DETAIL:  There are no running transactions.
2021-05-23 12:19:46.569 UTC [73] LOG:  terminating walsender process due to replication timeout
2021-05-23 12:19:46.569 UTC [73] CONTEXT:  slot "materialize_3e7d0a65ef9742538fa3bf6555e76938", output plugin "pgoutput", in the change callback, associated LSN 0/5BCA68D8
```

And on the Mz side it is :

```
2021-05-23T12:17:40.159934Z  INFO dataflow::source::postgres: replication interrupted: connection closed    
2021-05-23T12:18:43.450682Z  INFO dataflow::source::postgres: replication interrupted: connection closed    
2021-05-23T12:19:46.734792Z  INFO dataflow::source::postgres: replication interrupted: connection closed    
2021-05-23T12:20:50.018832Z  INFO dataflow::source::postgres: replication interrupted: connection closed 
```

The source fails to make progress to matter how much time it is given. The postgres log implies that replication starts over and over from the same LSN position.

The Pg timeout in question is this one:

https://www.postgresql.org/docs/current/runtime-config-replication.html#GUC-WAL-SENDER-TIMEOUT

which has a default of 60 seconds. A value of 600 seconds allows for the test below to pass.

### Is the issue reproducible? If so, please provide reproduction instructions.

1. Give ```pg-cdc``` a very large timeout:
```
diff --git a/test/pg-cdc/mzcompose.yml b/test/pg-cdc/mzcompose.yml
index b1572a019..701d9d3e7 100644
--- a/test/pg-cdc/mzcompose.yml
+++ b/test/pg-cdc/mzcompose.yml
@@ -30,6 +30,7 @@ services:
       - >-
         testdrive
         --materialized-url=postgres://materialize@materialized:6875
+        --default-timeout=6000
         $$*
       - bash
     volumes:
```
2. Run this test via ```TD_TEST```:
```
$ postgres-execute connection=postgres://postgres:postgres@postgres
ALTER USER postgres WITH replication;

DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

DROP PUBLICATION IF EXISTS mz_source;
CREATE PUBLICATION mz_source FOR ALL TABLES;

CREATE TABLE ten (f1 INTEGER);
ALTER TABLE ten REPLICA IDENTITY FULL;
INSERT INTO ten VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10);

CREATE TABLE t1 (f1 INTEGER, f2 TEXT);
ALTER TABLE t1 REPLICA IDENTITY FULL;
INSERT INTO t1 SELECT a1.f1 + a6.f1 , E'abc\nxyz' FROM ten AS a1, ten AS a2, ten AS a3, ten AS a4, ten AS a5, ten AS a6, ten AS a7;

> CREATE MATERIALIZED SOURCE mz_source
  FROM POSTGRES HOST 'host=postgres port=5432 user=postgres password=postgres sslmode=require dbname=postgres'
  PUBLICATION 'mz_source';

> SELECT COUNT(*) > 0 FROM mz_source;
true

> CREATE MATERIALIZED VIEWS FROM SOURCE mz_source;

$ postgres-execute connection=postgres://postgres:postgres@postgres
DELETE FROM t1;

> SELECT COUNT(*) = 0 FROM t1;
true
```

The test will never complete.

### PR DESCRIPTION
**Pull request by petrosagg**
fixes #6827

### CODE REVIEW

**Review by philip-stoev — APPROVED** [review]
```2021-05-24 11:05:31.099 UTC [70] LOG:  terminating walsender process due to replication timeout
2021-05-24 11:05:34.108 UTC [81] LOG:  starting logical decoding for slot "materialize_a1c9a2b9179640e6b5fc707b041b6efc"
2021-05-24 11:05:34.108 UTC [81] DETAIL:  Streaming transactions committing after 4/7124A9E0, reading WAL from 4/66D1A2D0.
2021-05-24 11:05:34.108 UTC [81] LOG:  logical decoding found consistent point at 4/66D1A2D0
2021-05-24 11:05:34.108 UTC [81] DETAIL:  There are no running transactions.
2021-05-24 11:06:34.108 UTC [81] LOG:  terminating walsender process due to replication timeout
2021-05-24 11:06:37.115 UTC [83] LOG:  starting logical decoding for slot "materialize_a1c9a2b9179640e6b5fc707b041b6efc"
2021-05-24 11:06:37.115 UTC [83] DETAIL:  Streaming transactions committing after 4/7124A9E0, reading WAL from 4/70DE1CF8.
2021-05-24 11:06:37.116 UTC [83] LOG:  logical decoding found consistent point at 4/70DE1CF8
2021-05-24 11:06:37.116 UTC [83] DETAIL:  There are no running transactions.
2021-05-24 11:07:37.116 UTC [83] LOG:  terminating walsender process due to replication timeout
2021-05-24 11:07:40.123 UTC [85] LOG:  starting logical decoding for slot "materialize_a1c9a2b9179640e6b5fc707b041b6efc"
2021-05-24 11:07:40.123 UTC [85] DETAIL:  Streaming transactions committing after 4/7124A9E0, reading WAL from 4/70DE1CF8.
2021-05-24 11:07:40.123 UTC [85] LOG:  logical decoding found consistent point at 4/70DE1CF8
2021-05-24 11:07:40.123 UTC [85] DETAIL:  There are no running transactions.
```

File: src/dataflow/src/source/postgres.rs [hunk 1]
```diff
@@ -209,11 +209,38 @@ impl PostgresSourceReader {
...
+            use ReplicationMessage::*;
+            // The upstream will periodically request keepalive responses by setting the reply field
+            // to 1. However, we cannot rely on these messages arriving on time. For example, when
+            // the upstream is sending a big transaction its keepalive messages are queued and can
+            // be delayed arbitrarily.  Therefore, we also make sure to send a proactive keepalive
+            // every 30 seconds.
+            //
+            // See: https://www.postgresql.org/message-id/CAMsr+YE2dSfHVr7iEv1GSPZihitWX-PMkD9QALEGcTYa+sdsgg@mail.gmail.com
+            if matches!(item, Ok(PrimaryKeepAlive(ref k)) if k.reply() == 1)
+                || last_keepalive.elapsed() > Duration::from_secs(30)
```
Comment (philip-stoev) [inline src/dataflow/src/source/postgres.rs:225]: A 10-second interval may be safer here if the timeout that will apply is 60 seconds.

Comment (petrosagg) [reply src/dataflow/src/source/postgres.rs:225]: Can you explain the failure scenario you have in mind? From what I understand the current code will cause a timeout only if the network has a 30 second latency, in which case a reconnect is probably a better course of action

**Review by JLDLaughlin — APPROVED** [review]
