### PR TITLE
persist: add a sentry tag to the pushdown audit panic

### LINKED ISSUE #25776: Improve tagging hygiene for persist filter pushdown panic
We panic on[ this correctness violation](https://github.com/MaterializeInc/materialize/blob/55af7ae348a5e67b2fdd6a784616e9bedae8efaf/src/storage-operators/src/persist_source.rs#L550), and monitor for it in our tooling. Right now detecting this panic relies on string-matching, which is [vulnerable](https://github.com/MaterializeInc/cloud/issues/8857#issuecomment-1977243368) to being broken by a refactor.

We should come up with a tag or metadata field that unambiguously identifies this panic as a correctness violation that we are monitoring for. This overlaps with the work the Incident Working Group is doing on alerting standards and could benefit from discussion with that group as well.

Related:
 - https://github.com/MaterializeInc/cloud/issues/8857

### PR DESCRIPTION
**Pull request by danhhz**
This will make alerts for instances of audit failures less brittle (i.e. not based on the panic message).

Closes #25776

### Motivation

  * This PR adds a known-desirable feature.

### Tips for reviewer

The tag(s) used is just a strawman. Gonna hash out the exact set in slack.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by danhhz** [comment]
Example from testing on my staging env (look for persist_foo): https://materializeinc.sentry.io/issues/5040195689/?environment=staging&query=is%3Aunresolved+panic&referrer=issue-stream&statsPeriod=1h&stream_index=0

Discussion of what the tag convention should be in https://materializeinc.slack.com/archives/C03TDG8L76V/p1709677543156939

File: src/storage-operators/src/persist_source.rs [hunk 1]
```diff
@@ -546,9 +546,20 @@ impl PendingWork {
...
                         ) {
-                            if let Some(_stats) = is_filter_pushdown_audit {
-                                // TODO: include more (redacted) information here.
-                                panic!("persist filter pushdown correctness violation! {}", name);
+                            if let Some(_stats) = &is_filter_pushdown_audit {
+                                // NB: The tag added by this scope is used for alerting. The panic
+                                // message may be changed arbitrarily, but the tag key and val must
+                                // stay the same.
+                                sentry::with_scope(
+                                    |scope| scope.set_tag("id", "persist_pushdown_audit_violation"),
```
Comment (jpepin) [inline src/storage-operators/src/persist_source.rs:554]: If we wanted to put a finer point on it, we could call this tag `alert_id`

**Review by jpepin — COMMENTED** [review]
This is a good start! I could see us wanting more tags in the future (for instance,  `team: persist`) for finer grained routing, but that probably won't be needed while we only have the single oncall rotation.

**Review by jpepin — APPROVED** [review]

**Review by guswynn — APPROVED** [review]
hellll ya `with_scope` is great

File: src/storage-operators/Cargo.toml [hunk 2]
```diff
@@ -29,6 +29,7 @@ mz-storage-types = { path = "../storage-types" }
 mz-timely-util = { path = "../timely-util" }
 prometheus = { version = "0.13.3", default-features = false }
 proptest = { version = "1.0.0", default-features = false, features = ["std"] }
+sentry = { version = "0.29.1" }
```
Comment (danhhz) [inline src/storage-operators/Cargo.toml:32]: WIP

File: src/storage-operators/src/persist_source.rs (hunk 1 above)
Comment (danhhz) [reply src/storage-operators/src/persist_source.rs]: Done!

**Review by danhhz — COMMENTED** [review]
TFTRs!
