### PR TITLE
rbac: Fix privilege requirement for create source

### LINKED ISSUE #21543: `CREATE SOURCE ... IN CLUSTER` should not need `SYSTEM` privileges
### What version of Materialize are you using?

v0.67.3 (6510d54bc)

### What is the issue?

With `RBAC`, creating a source in a specific cluster appears to require `SYSTEM` privileges. I don't feel I need any of the `SYSTEM` privileges -- `CREATEROLE` , `CREATEDB` , or `CREATECLUSTER` . If I were creating a linked cluster, that would make sense to require `CREATECLUSTER`.

Example:
```sql
CREATE SOURCE IF NOT EXISTS sales IN CLUSTER demo_sources
FROM KAFKA CONNECTION demo.public.kafka_connection 
(TOPIC 'datagen_demo_snowflakeschema_sales', START TIMESTAMP -90000000) 
KEY FORMAT BYTES 
VALUE FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY CONNECTION demo.public.csr_connection
INCLUDE TIMESTAMP as kafka_timestamp 
ENVELOPE NONE ;
```
```
Error: permission denied for SYSTEM
```

But then:
```sql
select has_cluster_privilege('chuck@materialize.com', 'demo_sources', 'CREATE');
```

```
has_cluster_privilege
true
```

### PR DESCRIPTION
**Pull request by jkosh44**
The cluster configuration of a CreateSourcePlan dictates whether the source will be created in an existing cluster, create a new cluster, or do the default behavior, which is usually to create a new cluster. However, if the source is a progress source or a sub-source, then the default behavior is to do whatever the main source does.

RBAC mistakenly interpreted the cluster configurations of progress and sub-sources to mean that a new cluster was always created and required the CREATECLUSTER system privilege.

This commit fixes the described confusion so the CREATECLUSTER system privilege is only required when a cluster is created.

Fixes #21543

### Motivation
This PR fixes a recognized bug.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - Fix create source privilege requirements.

### CODE REVIEW

File: src/sql/src/plan.rs [hunk 1]
```diff
@@ -558,7 +558,15 @@ pub enum SourceSinkClusterConfig {
...
-    /// The user did not specify a cluster behavior, so use the default.
+    /// The user did not specify a cluster behavior, so the actual behavior depends on
+    /// the context. For sources the behavior depends on the data source:
+    ///
+    ///   - Ingestion: Use the default behavior.
+    ///   - Source: Use the same cluster as the data source source.
+    ///   - Progress: Use the same cluster as the non-progress source.
+    ///   - Webhook: Does not allow undefined configs.
+    ///
+    /// For sinks, always use the default behavior.
```
Comment (jkosh44) [inline src/sql/src/plan.rs:569]: I'm not a very big fan of this variant, because it feels like more bugs are waiting to happen from misinterpreting it. However, I don't really know what to do about it right now.

**Comment by jkosh44** [comment]
Accidently closed this due to a typo in a linked issue for another PR.

**Comment by jkosh44** [comment]
I'm adding everyone as reviewers in case someone is available, because I think we want to try and create a patch release with this fix somewhat soon.

**Review by andrewrodriguez-m — APPROVED** [review]
