### PR TITLE
adapter: Refactor cascading delete statements

### LINKED ISSUE #18551: Object ownership: Can't drop object, but cascade can drop it
### What version of Materialize are you using?

v0.50.0-dev (762302a54)

### How did you install Materialize?

Built from source

### What is the issue?

```
# As mz_system
mz_system=> ALTER SYSTEM SET enable_rbac_checks TO true;
ALTER SYSTEM
# As materialize
materialize=> create role r1;
CREATE ROLE
# As r1:
materialize=> create table t (c int);
CREATE TABLE
# As materialize
materialize=> create index i on t (c);
CREATE INDEX
# As r1:
materialize=> drop index i;
ERROR:  must be owner of INDEX materialize.public.i
materialize=> drop table t;
DROP TABLE
materialize=> drop index i;
ERROR:  unknown catalog item 'i'
```

On Postgres I can directly drop the index when I own the table, even though it was created by a different role:
```
postgres=# set role r1;
SET
postgres=> drop index i;
DROP INDEX
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jkosh44**
Previously, the adapter would collect all the IDs of objects to delete as part of a cascading delete during sequencing. This commit refactors this logic so the IDs are collected during planning. This allows us to include those IDs as part of RBAC checks.

Additionally, we had to move the validation that no user was directly modifying a linked cluster to the planner.

Fixes #18551

### Motivation
This PR fixes a recognized bug.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

File: src/adapter/src/catalog.rs [hunk 1]
```diff
@@ -242,6 +242,156 @@ impl CatalogState {
         }
     }
 
+    /// Returns all the IDs of all objects that depend on `ids`, including `ids` themselves.
```
Comment (jkosh44) [inline src/adapter/src/catalog.rs:245]: These functions were all ported from the `drop_X_ops` functions.

**Review by parker-timmerman — COMMENTED** [review]
It looks good to me from a code perspective, but I'm having a hard time understanding what's actually changing, so I don't think I can confidently approve this. Hopefully someone else can review it soon, if no one does I'll take another pass 🙂

**Comment by jkosh44** [comment]
> It looks good to me from a code perspective, but I'm having a hard time understanding what's actually changing, so I don't think I can confidently approve this. Hopefully someone else can review it soon, if no one does I'll take another pass slightly_smiling_face

No worries. For your own learning here's what's happening. When you type `DROP TABLE t CASCADE`, we drop table `t` and all objects that depend on `t`, like views and indexes. Previously during sequencing we'd search through the catalog for all the items that depend on `t` that we need to drop. The issue with this was that the RBAC checks happened before sequencing and therefore wouldn't consider any of these dependents. 

This PR changes this so that we collect the dependent items during planning instead of sequencing, so that RBAC can take them into consideration.

File: src/adapter/src/coord/sequencer/inner.rs [hunk 2]
```diff
@@ -1166,12 +1166,10 @@ impl Coordinator {
             .catalog()
             .state()
             .is_system_schema_specifier(&name.qualifiers.schema_spec)
+            && !self.is_compute_cluster(cluster_id)
         {
-            self.ensure_cluster_is_not_linked(cluster_id)?;
```
Comment (mjibson) [inline src/adapter/src/coord/sequencer/inner.rs:1170]: Why did ensure_cluster_is_not_linked get removed?

**Review by mjibson — APPROVED** [review]
