### PR TITLE
kafka: immediately cleanup metadata threads on drop

### LINKED ISSUE #10843: DROP SOURCE does not cause Kafka threads to be terminated
### What version of Materialize are you using?

v0.20.0

### How did you install Materialize?

Docker image

### What was the issue?

Previously, dropping a source would cause the associated kafka threads to be removed. This does not seem to be the case anymore.

Bisection reports the problem started happening at this commit:

```
commit 03b4758bb9c51dcd3fae89cbc1db091f3eb82edc
Merge: 31da762d4 f1a08a0b5
Author: Petros Angelatos <petrosagg@gmail.com>
Date:   Fri Feb 4 22:12:35 2022 +0100

    Merge pull request #10436 from petrosagg/kafka-partition-discovery
    
    Retire timestamping thread from coordinator
```

To reproduce:

1. Run `test/testdrive/kafka-avro-sources.td`
2. Run `DROP DATABASE materialize`
2. Check the thread count:
```sudo gdb -p `pidof materialized` --batch --ex 'info threads' | wc```
(make sure you have one and only one Mz instance running on your machine, containerized or not)

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by petrosagg**
### Motivation

The metadata thread was previously checking whether the source it was
spanwed for was dropped as the first step in its polling loop.

Since the poll loop by default was 5 minutes it could cause a lot of
idle threads to linger around for a maximum of 5 minutes.

Now the thread parks itself with a timeout instead of sleeping and we
make sure to unpark it when the parent source is dropped. This way the
thread notices that it should exit immediately.

Fixes #10843

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

File: src/dataflow/src/source/kafka.rs [hunk 1]
```diff
@@ -63,6 +64,18 @@ pub struct KafkaSourceReader {
     last_stats: Option<Jsonb>,
     /// The last partition we received
     partition_info: Arc<Mutex<Option<Vec<i32>>>>,
+    /// A handle to the spawned metadata thread
+    // Drop order is important here, we want the thread to be unparked after the `partition_info`
+    // Arc has been dropped, so that the unpacked thread notices it and exits immediately
+    _metadata_thread_handle: UnpackOnDrop<()>,
```
Comment (frankmcsherry) [inline src/dataflow/src/source/kafka.rs:70]: Nit, but should this be `UnparkOnDrop`?

**Review by frankmcsherry — APPROVED** [review]
This looks good to me, though I had no idea about `park_timeout` before so maybe take this excitement with a lower confidence based on that. :D
