### PR TITLE
adapter: generate_series returns set

### LINKED ISSUE #18020: mz_functions' returns_set is incorrect for generate_series function
### What version of Materialize are you using?

v0.46.0-dev (6b03c7d6f)

### How did you install Materialize?

Built from source

### What is the issue?

```
materialize=> select * from mz_functions where name = 'generate_series';
  id  | oid  | schema_id |      name       | argument_type_ids | variadic_argument_type_id | return_type_id | returns_set
------+------+-----------+-----------------+-------------------+---------------------------+----------------+-------------
 s137 | 1067 | 2         | generate_series | {s20,s20}         |                           | s20            | f
 s137 | 1069 | 2         | generate_series | {s22,s22}         |                           | s22            | f
 s137 | 1066 | 2         | generate_series | {s20,s20,s20}     |                           | s20            | f
 s137 | 1068 | 2         | generate_series | {s22,s22,s22}     |                           | s22            | f
 s137 |  938 | 2         | generate_series | {s48,s48,s24}     |                           | s48            | f
 s137 |  939 | 2         | generate_series | {s50,s50,s24}     |                           | s50            | f
(6 rows)
```
I would expect returns_set to be true, see documentation: https://materialize.com/docs/sql/functions/#table-func
The other table functions are correctly reporting returns_set=True.
Noticed as part of https://github.com/MaterializeInc/materialize/issues/17739

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by def-**
Fixes #18020

I found further issues, see individual commits.

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

File: src/sql/src/plan/query.rs [hunk 1]
```diff
@@ -4330,10 +4330,10 @@ fn plan_function<'a>(
             )
         }
         Func::Aggregate(_) => {
-            sql_bail!("aggregate functions are not allowed in {}", ecx.name);
+            sql_bail!("aggregate functions are not allowed in {} (function {})", ecx.name, unresolved_name);
```
Comment (parker-timmerman) [inline src/sql/src/plan/query.rs:4333]: Could we update the sqllogictests to test for this new pattern? It looks like we [already have a few](https://github.com/search?q=aggregate+functions+are+not+allowed+repo%3AMaterializeInc%2Fmaterialize+extension%3Aslt&type=Code&ref=advsearch&l=&l=) that could be updated.

**Review by parker-timmerman — APPROVED** [review]
Thanks for the fix! Overall the changes look good to me, the return types seem to match those defined in Postgres ([1](https://www.postgresql.org/docs/current/functions-srf.html), [2](https://www.postgresql.org/docs/9.5/functions-json.html)).

If you could also wait for @jkosh44 to take a look though, that would be great

**Review by jkosh44 — APPROVED** [review]
LGTM modulo Parker's comment.

**Comment by mjibson** [comment]
I'm curious how the previous code passed logic tests with the specified return type differing from the actual return type.

**Comment by def-** [comment]
@mjibson It seems like the types we specify are not checked at all and different types can be expected in the actual implementation.
