### PR TITLE
Remove duplicates from indexes_to_undistribute

### LINKED ISSUE #14532: 'swap_remove index (is 2) should be < len (is 2)', library/alloc/src/vec/mod.rs:1337:13
### What version of Materialize are you using?

1f24587750b1fff661f0c4de64774c3aeff0ec06

### How did you install Materialize?

Built from source and noticed in https://buildkite.com/materialize/sql-logic-tests/builds/5337#0182ee85-313b-40b9-accf-1c6a4f36c493

### What is the issue?

Crash in optimizing a SQL query.

### Relevant log output

```source
SELECT pk FROM tab0 WHERE (((col4 >= 660.98) AND ((col4 IN (724.71,445.29,441.2,606.49) AND ((col0 > 523)) AND (((col3 > 975 OR (col3 IS NULL) AND (col1 > 259.62 OR col0 >= 896 OR col1 <= 947.3 OR col3 IS NULL OR (col3 > 788) AND ((col3 < 264)) AND col0 < 823 AND ((col0 < 164) AND col1 > 95.85) AND (col0 > 534) AND col4 > 922.46 AND col3 >= 528 AND col3 > 762 AND col0 <= 903) AND col3 IS NULL))) OR col1 < 760.15 OR ((((((col0 >= 551)))))) OR col0 IN (425,98,842,550))) OR col0 < 397 AND col4 > 32.43 AND col3 >= 13 OR col3 > 474 OR ((col1 < 746.36)) AND col1 >= 499.2 AND col0 < 362 OR ((col0 <= 979) AND ((col0 IS NULL) AND (col1 > 251.48) AND (col3 > 838 OR col3 > 529 AND col0 IN (627,345,774,557) OR ((col0 <= 992 OR (((col3 BETWEEN 277 AND 34)))) AND (col0 > 561))) AND col1 >= 912.45 OR (col0 < 4 AND (col3 <= 996 AND (col0 <= 364))) OR ((col0 < 979)) OR col1 > 599.0 OR (col4 <= 26.30 AND ((col3 = 547 AND col3 >= 799) OR (col1 BETWEEN 841.6 AND 776.13)) AND col1 > 614.41 OR col4 = 581.12))) AND col0 < 480 OR (col3 = 763 AND (col3 IS NULL)))) ORDER BY 1 DESC
thread 'coordinator' panicked at 'swap_remove index (is 2) should be < len (is 2)', library/alloc/src/vec/mod.rs:1337:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: alloc::vec::Vec<T,A>::swap_remove::assert_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/vec/mod.rs:1337:13
   3: alloc::vec::Vec<T,A>::swap_remove
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/vec/mod.rs:1342:13
   4: mz_expr::scalar::MirScalarExpr::swap_remove_multiple
             at ./src/expr/src/scalar/mod.rs:1413:25
   5: mz_expr::scalar::MirScalarExpr::undistribute_and_or
             at ./src/expr/src/scalar/mod.rs:1393:32
   6: mz_expr::scalar::MirScalarExpr::reduce::{{closure}}
             at ./src/expr/src/scalar/mod.rs:939:29
   7: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:660:50
   8: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::VisitChildren<mz_expr::scalar::MirScalarExpr>>::visit_mut_children
             at ./src/expr/src/scalar/mod.rs:1632:21
   9: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}
             at ./src/expr/src/visit.rs:660:17
  10: stacker::maybe_grow
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  11: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  12: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit
             at ./src/expr/src/visit.rs:654:9
  13: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:660:50
  14: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::VisitChildren<mz_expr::scalar::MirScalarExpr>>::visit_mut_children
             at ./src/expr/src/scalar/mod.rs:1632:21
  15: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}
             at ./src/expr/src/visit.rs:660:17
  16: stacker::maybe_grow
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  17: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  18: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit
             at ./src/expr/src/visit.rs:654:9
  19: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:660:50
  20: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::VisitChildren<mz_expr::scalar::MirScalarExpr>>::visit_mut_children
             at ./src/expr/src/scalar/mod.rs:1632:21
  21: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}
             at ./src/expr/src/visit.rs:660:17
  22: stacker::maybe_grow
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  23: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  24: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit
             at ./src/expr/src/visit.rs:654:9
  25: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:660:50
  26: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::VisitChildren<mz_expr::scalar::MirScalarExpr>>::visit_mut_children
             at ./src/expr/src/scalar/mod.rs:1632:21
  27: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}
             at ./src/expr/src/visit.rs:660:17
  28: stacker::maybe_grow
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  29: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  30: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit
             at ./src/expr/src/visit.rs:654:9
  31: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:660:50
  32: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::VisitChildren<mz_expr::scalar::MirScalarExpr>>::visit_mut_children
             at ./src/expr/src/scalar/mod.rs:1632:21
  33: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}
             at ./src/expr/src/visit.rs:660:17
  34: stacker::maybe_grow
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  35: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  36: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit
             at ./src/expr/src/visit.rs:654:9
  37: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:660:50
  38: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::VisitChildren<mz_expr::scalar::MirScalarExpr>>::visit_mut_children
             at ./src/expr/src/scalar/mod.rs:1632:21
  39: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}
             at ./src/expr/src/visit.rs:660:17
  40: stacker::maybe_grow
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  41: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  42: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit
             at ./src/expr/src/visit.rs:654:9
  43: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:660:50
  44: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::VisitChildren<mz_expr::scalar::MirScalarExpr>>::visit_mut_children
             at ./src/expr/src/scalar/mod.rs:1632:21
  45: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}
             at ./src/expr/src/visit.rs:660:17
  46: stacker::maybe_grow
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  47: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  48: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit
             at ./src/expr/src/visit.rs:654:9
  49: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:660:50
  50: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::VisitChildren<mz_expr::scalar::MirScalarExpr>>::visit_mut_children
             at ./src/expr/src/scalar/mod.rs:1632:21
  51: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}
             at ./src/expr/src/visit.rs:660:17
  52: stacker::maybe_grow
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  53: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  54: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit
             at ./src/expr/src/visit.rs:654:9
  55: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:660:50
  56: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::VisitChildren<mz_expr::scalar::MirScalarExpr>>::visit_mut_children
             at ./src/expr/src/scalar/mod.rs:1632:21
  57: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}
             at ./src/expr/src/visit.rs:660:17
  58: stacker::maybe_grow
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  59: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  60: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit
             at ./src/expr/src/visit.rs:654:9
  61: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:660:50
  62: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::VisitChildren<mz_expr::scalar::MirScalarExpr>>::visit_mut_children
             at ./src/expr/src/scalar/mod.rs:1632:21
  63: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}
             at ./src/expr/src/visit.rs:660:17
  64: stacker::maybe_grow
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  65: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  66: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit
             at ./src/expr/src/visit.rs:654:9
  67: <T as mz_expr::visit::Visit>::visit_mut_pre_post_nolimit
             at ./src/expr/src/visit.rs:403:9
  68: mz_expr::scalar::MirScalarExpr::reduce
             at ./src/expr/src/scalar/mod.rs:476:13
  69: mz_expr::relation::canonicalize::canonicalize_predicates::{{closure}}
             at ./src/expr/src/relation/canonicalize.rs:208:40
  70: <core::slice::iter::IterMut<T> as core::iter::traits::iterator::Iterator>::for_each
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/slice/iter/macros.rs:211:21
  71: mz_expr::relation::canonicalize::canonicalize_predicates
             at ./src/expr/src/relation/canonicalize.rs:208:5
  72: mz_transform::fusion::filter::Filter::action
             at ./src/transform/src/fusion/filter.rs:79:13
  73: <mz_transform::fusion::filter::Filter as mz_transform::Transform>::transform::{{closure}}
             at ./src/transform/src/fusion/filter.rs:61:48
  74: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_pre::{{closure}}
             at ./src/expr/src/visit.rs:581:13
  75: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  76: stacker::maybe_grow
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  77: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  78: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  79: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_pre
             at ./src/expr/src/visit.rs:580:9
  80: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_pre::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:582:50
  81: <mz_expr::relation::MirRelationExpr as mz_expr::visit::VisitChildren<mz_expr::relation::MirRelationExpr>>::try_visit_mut_children
             at ./src/expr/src/relation/mod.rs:1530:13
  82: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_pre::{{closure}}
             at ./src/expr/src/visit.rs:582:13
  83: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  84: stacker::maybe_grow
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  85: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  86: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  87: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_pre
             at ./src/expr/src/visit.rs:580:9
  88: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_pre::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:582:50
  89: <mz_expr::relation::MirRelationExpr as mz_expr::visit::VisitChildren<mz_expr::relation::MirRelationExpr>>::try_visit_mut_children
             at ./src/expr/src/relation/mod.rs:1530:13
  90: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_pre::{{closure}}
             at ./src/expr/src/visit.rs:582:13
  91: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  92: stacker::maybe_grow
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  93: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  94: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  95: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_pre
             at ./src/expr/src/visit.rs:580:9
  96: <T as mz_expr::visit::Visit>::try_visit_mut_pre
             at ./src/expr/src/visit.rs:367:9
  97: <mz_transform::fusion::filter::Filter as mz_transform::Transform>::transform
             at ./src/transform/src/fusion/filter.rs:61:9
  98: <mz_transform::FuseAndCollapse as mz_transform::Transform>::transform
             at ./src/transform/src/lib.rs:259:13
  99: <mz_transform::Fixpoint as mz_transform::Transform>::transform
             at ./src/transform/src/lib.rs:163:21
 100: mz_transform::Optimizer::transform
             at ./src/transform/src/lib.rs:450:13
 101: mz_transform::Optimizer::optimize
             at ./src/transform/src/lib.rs:428:9
 102: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_peek::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:2005:22
 103: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
 104: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_peek::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:1813:5
 105: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
 106: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_plan::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:238:63
 107: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
 108: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_plan::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:91:5
 109: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
 110: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute_inner::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:451:78
 111: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
 112: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute_inner::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:251:5
 113: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
 114: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:248:61
 115: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
 116: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:228:5
 117: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
 118: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
 119: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_command::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:62:38
 120: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
 121: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_command::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:138:33
 122: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
 123: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_command::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:135:5
 124: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
 125: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_message::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:37:63
 126: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
 127: mz_adapter::coord::Coordinator<S>::serve::{{closure}}
             at ./src/adapter/src/coord.rs:808:37
 128: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
 129: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:54
 130: tokio::coop::with_budget::{{closure}}
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:102:9
 131: std::thread::local::LocalKey<T>::try_with
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/local.rs:445:16
 132: std::thread::local::LocalKey<T>::with
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/local.rs:421:9
 133: tokio::coop::with_budget
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:95:5
 134: tokio::coop::budget
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:72:5
 135: tokio::park::thread::CachedParkThread::block_on
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:31
 136: tokio::runtime::enter::Enter::block_on
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/enter.rs:151:13
 137: tokio::runtime::handle::Handle::block_on
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/handle.rs:296:9
 138: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./src/adapter/src/coord.rs:945:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
```

### PR DESCRIPTION
**Pull request by ggevay**
Fixes #14532

### Motivation

  * This PR fixes a recognized bug: #14532

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - No

### CODE REVIEW

File: src/expr/src/scalar/mod.rs [hunk 1]
```diff
@@ -1372,12 +1372,15 @@ impl MirScalarExpr {
...
-                let indexes_to_undistribute = all_inner_operands
+                let mut indexes_to_undistribute = all_inner_operands
                     .iter()
                     .group_by(|(a, _i)| a)
                     .into_iter()
                     .map(|(_a, g)| g.map(|(_a, i)| *i).collect_vec())
                     .find(|g| g.len() > 1);
+                // `swap_remove_multiple` cannot handle duplicates
+                indexes_to_undistribute.as_mut().map(|vec| vec.sort());
+                indexes_to_undistribute.as_mut().map(|vec| vec.dedup());
```
Comment (antiguru) [inline src/expr/src/scalar/mod.rs:1383]: Nit: Perform sort and dedup in the same closure.

Comment (antiguru) [inline src/expr/src/scalar/mod.rs:1383]: Nit: Perform sort and dedup in the same closure.

File: src/expr/src/scalar/mod.rs [hunk 2]
```diff
@@ -1402,6 +1405,8 @@ impl MirScalarExpr {
         }
     }
 
+    /// swap_remove the elements indicated by `indexes`.
+    /// `indexes` shouldn't have duplicates.
```
Comment (antiguru) [inline src/expr/src/scalar/mod.rs:1409]: Nit: Improve doc comment to say that `swap_remove_multiple` will panic if `indexes` has duplicates. The semantics of the function aren't immediately clear from the description, maybe this would be a good opportunity to explain what the function does?

**Review by antiguru — APPROVED** [review]
Thanks for the quick fix!

File: src/expr/src/scalar/mod.rs (hunk 2 above)
Comment (ggevay) [reply src/expr/src/scalar/mod.rs]: done

File: src/expr/src/scalar/mod.rs (hunk 1 above)
Comment (ggevay) [reply src/expr/src/scalar/mod.rs]: done

Comment (ggevay) [reply src/expr/src/scalar/mod.rs]: done
