### PR TITLE
[storage] Don't panic if someone else moves table upper

### LINKED ISSUE #15949: regression: panicked at 'Table write failed: `write.upper` set to value that signals we have lost leadership'
### What version of Materialize are you using?

250e4ef

### How did you install Materialize?

Docker image

### What is the issue?

The test that restarts the postgres backend caused environmentd to panic as follows

https://buildkite.com/materialize/nightlies/builds/1339#018454a8-9a52-486a-99e2-5c560baba211

### Relevant log output

```source
platform-checks-materialized-1      | thread 'tokio:work-1' panicked at 'Table write failed: `write.upper` set to value that signals we have lost leadership', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e3e4ce48c30621d3-1/materialize/tests/src/storage-client/src/controller.rs:2195:57
platform-checks-materialized-1      | stack backtrace:
platform-checks-materialized-1      |    0: rust_begin_unwind
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
platform-checks-materialized-1      |    1: core::panicking::panic_fmt
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
platform-checks-materialized-1      |    2: mz_storage_client::controller::persist_write_handles::PersistWorker<T>::new::{{closure}}::append_work::{{closure}}::{{closure}}
platform-checks-materialized-1      |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e3e4ce48c30621d3-1/materialize/tests/src/storage-client/src/controller.rs:2195:57
platform-checks-materialized-1      |    3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
platform-checks-materialized-1      |    4: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/stream/futures_unordered/mod.rs:515:17
platform-checks-materialized-1      |    5: <futures_util::stream::stream::collect::Collect<St,C> as core::future::future::Future>::poll
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/stream/stream/collect.rs:50:26
platform-checks-materialized-1      |    6: mz_storage_client::controller::persist_write_handles::PersistWorker<T>::new::{{closure}}::append_work::{{closure}}
platform-checks-materialized-1      |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e3e4ce48c30621d3-1/materialize/tests/src/storage-client/src/controller.rs:2213:41
platform-checks-materialized-1      |    7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
platform-checks-materialized-1      |    8: mz_storage_client::controller::persist_write_handles::PersistWorker<T>::new::{{closure}}
platform-checks-materialized-1      |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e3e4ce48c30621d3-1/materialize/tests/src/storage-client/src/controller.rs:2229:106
platform-checks-materialized-1      |    9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
platform-checks-materialized-1      |   10: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:165:17
platform-checks-materialized-1      |   11: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/loom/std/unsafe_cell.rs:14:9
platform-checks-materialized-1      |   12: tokio::runtime::task::core::CoreStage<T>::poll
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:155:13
platform-checks-materialized-1      |   13: tokio::runtime::task::harness::poll_future::{{closure}}
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:480:19
platform-checks-materialized-1      |   14: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panic/unwind_safe.rs:271:9
platform-checks-materialized-1      |   15: std::panicking::try::do_call
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
platform-checks-materialized-1      |   16: std::panicking::try
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
platform-checks-materialized-1      |   17: std::panic::catch_unwind
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
platform-checks-materialized-1      |   18: tokio::runtime::task::harness::poll_future
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:468:18
platform-checks-materialized-1      |   19: tokio::runtime::task::harness::Harness<T,S>::poll_inner
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:104:27
platform-checks-materialized-1      |   20: tokio::runtime::task::harness::Harness<T,S>::poll
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:57:15
platform-checks-materialized-1      |   21: tokio::runtime::task::raw::RawTask::poll
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/raw.rs:84:18
platform-checks-materialized-1      |   22: tokio::runtime::task::LocalNotified<S>::run
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/mod.rs:381:9
platform-checks-materialized-1      |   23: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:458:21
platform-checks-materialized-1      |   24: tokio::coop::with_budget::{{closure}}
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:102:9
platform-checks-materialized-1      |   25: std::thread::local::LocalKey<T>::try_with
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/thread/local.rs:445:16
platform-checks-materialized-1      |   26: std::thread::local::LocalKey<T>::with
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/thread/local.rs:421:9
platform-checks-materialized-1      |   27: tokio::coop::with_budget
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:95:5
platform-checks-materialized-1      |   28: tokio::coop::budget
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:72:5
platform-checks-materialized-1      |   29: tokio::runtime::thread_pool::worker::Context::run_task
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:434:9
platform-checks-materialized-1      |   30: tokio::runtime::thread_pool::worker::Context::run
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:401:24
platform-checks-materialized-1      |   31: tokio::runtime::thread_pool::worker::run::{{closure}}
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:386:17
platform-checks-materialized-1      |   32: tokio::macros::scoped_tls::ScopedKey<T>::set
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/macros/scoped_tls.rs:61:9
platform-checks-materialized-1      |   33: tokio::runtime::thread_pool::worker::run
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:383:5
platform-checks-materialized-1      |   34: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:362:45
platform-checks-materialized-1      |   35: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/task.rs:42:21
platform-checks-materialized-1      |   36: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:165:17
platform-checks-materialized-1      |   37: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/loom/std/unsafe_cell.rs:14:9
platform-checks-materialized-1      |   38: tokio::runtime::task::core::CoreStage<T>::poll
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:155:13
platform-checks-materialized-1      |   39: tokio::runtime::task::harness::poll_future::{{closure}}
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:480:19
platform-checks-materialized-1      |   40: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panic/unwind_safe.rs:271:9
platform-checks-materialized-1      |   41: std::panicking::try::do_call
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
platform-checks-materialized-1      |   42: std::panicking::try
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
platform-checks-materialized-1      |   43: std::panic::catch_unwind
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
platform-checks-materialized-1      |   44: tokio::runtime::task::harness::poll_future
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:468:18
platform-checks-materialized-1      |   45: tokio::runtime::task::harness::Harness<T,S>::poll_inner
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:104:27
platform-checks-materialized-1      |   46: tokio::runtime::task::harness::Harness<T,S>::poll
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:57:15
platform-checks-materialized-1      |   47: tokio::runtime::task::raw::RawTask::poll
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/raw.rs:84:18
platform-checks-materialized-1      |   48: tokio::runtime::task::UnownedTask<S>::run
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/mod.rs:418:9
platform-checks-materialized-1      |   49: tokio::runtime::blocking::pool::Task::run
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/pool.rs:91:9
platform-checks-materialized-1      |   50: tokio::runtime::blocking::pool::Inner::run
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/pool.rs:325:17
platform-checks-materialized-1      |   51: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/pool.rs:300:13
platform-checks-materialized-1      | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by cjubb39**
The message in this panic is no longer true now that we persist sink status updates.  The panic was there (presumably?) because we thought we would no longer make progress because there was a new leader.  However, given that's not true, it should be sufficient to return an error.

It's also worth noting that, before this change, there are two different behaviors depending on whether we get an indeterminate error or not:
1) Read the upper from the writer, do a compare_and_append, get an `Upper` error because someone else advanced in the meantime, we return error from the function
2) Read the upper from the writer, do a compare_and_append, get an `Indeterminate` error, re-read the upper and notice that someone else has advanced in the meantime, we panic

### Motivation
Fixes #15949

### Tips for reviewer
I'd like a close look at this -- it seems like it could be a fix that's too simple to be correct.  I'm still working on getting a reliable repro with enough logs -- but it's possible the error would get filtered out below

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Comment by cjubb39** [comment]
I'm not yet convinced this is correct so it's still in draft mode while I run more tests

**Comment by cjubb39** [comment]
A couple notes on why I think this change is correct:
- Currently tables and also introspection sources are managed by this code.  Tables via `append` being called in `group_commit_initiate` and Introspection sources via the CollectionManager.  Every interval, the CM [ticks forward the introspection source with an empty update](https://github.com/MaterializeInc/materialize/blob/69eb6269f12d1796a8669df2345af7a1e2b3c21a/src/storage-client/src/controller.rs#L2400).  It explicitly ignores errors when it’s just pushing forward the upper.  However, when the CM passes through actual data, it panics on write contention.  The particular introspection source for the SinkHistory doesn’t every write data in this way so it’ll never panic there
- I believe a duplicate environmentd should crash in `group_commit_initiate` with an `StorageError::InvalidUppers` errors because the response from `StorageController::append` is always unwrapped

**Review by jkosh44 — APPROVED** [review]
LGTM

File: src/storage-client/src/controller.rs [hunk 1]
```diff
@@ -2175,7 +2175,7 @@ mod persist_write_handles {
                                                 // if it is still appropriate, not retrying if it has advanced
                                                 // to `new_upper`, and panicking if it is anything else.
                                                 while let Err(indeterminate) = result {
-                                                    tracing::warn!("Retrying indeterminate table write: {:#}", indeterminate);
+                                                    tracing::warn!("Retrying indeterminate persist worker write: {:#}", indeterminate);
```
Comment (bkirwi) [inline src/storage-client/src/controller.rs:2178]: ❤️

**Review by bkirwi — APPROVED** [review]
If surfaces is happy I am happy! (And in general I think it makes sense for the caller to handle the conflict, since it has access to the result.)

**Comment by cjubb39** [comment]
I've run a few nightlies with this patch (both in CI and on scratch) and it seems the error is gone!  So I'll go ahead and merge
