### PR TITLE
storage/pg: stream large transactions to persist

### LINKED ISSUE #26257: storage/sources: PostgreSQL transactions are buffered in memory
### What version of Materialize are you using?

v0.92.1

### What is the issue?

PostgreSQL transactions are unexpectedly being buffered in memory, causing small clusters to OOM when receiving large transactions from the upstream database. A user ran into this issue while deleting all rows from a 2GB table. See [this thread](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1711400449670959) for details.

cc @petrosagg

### PR DESCRIPTION
**Pull request by petrosagg**
This PR makes a slight modification to the capability management logic of the postgres source such that the capability that governs the minting of reclock bindings is advanced eagerly, before a transaction is ingested. This has the effect that the data of the transaction will not accumulate in the reclock operator and will instead be passed downstream, where the persist sink operator can stream it to S3 batches.

Fixes #26257

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

File: src/storage/src/source/postgres/replication.rs [hunk 1]
```diff
@@ -355,21 +360,7 @@ pub(crate) fn render<G: Scope<Timestamp = MzOffset>>(
                                         data_output.give(data_cap, update).await;
                                     }
                                 }
-                                assert!(
-                                    new_upper <= commit_lsn,
-                                    "new_upper={} tx_lsn={}",
-                                    new_upper,
-                                    commit_lsn
-                                );
-                                container.push((data, commit_lsn, diff));
```
Comment (guswynn) [inline src/storage/src/source/postgres/replication.rs:364]: we were also buffering the entire transaction pre-reclocking here, apparently

Comment (petrosagg) [reply src/storage/src/source/postgres/replication.rs:364]: Yes, oops!

File: src/storage/src/source/postgres/replication.rs [hunk 2]
```diff
@@ -355,21 +360,7 @@ pub(crate) fn render<G: Scope<Timestamp = MzOffset>>(
...
-                            }
-                            new_upper = commit_lsn + 1;
-                            if container.len() > max_capacity {
-                                data_output
-                                    .give_container(&data_cap_set[0], &mut container)
-                                    .await;
-                                upper_cap_set.downgrade([&new_upper]);
-                                data_cap_set.downgrade([&new_upper]);
```
Comment (rjobanp) [inline src/storage/src/source/postgres/replication.rs:372]: shouldn't we still downgrade the `data_cap_set` capability after producing the last update for this transaction?

**Review by rjobanp — COMMENTED** [review]
This seems fine to me, though I'm less familiar with the reclocking behavior than @guswynn so will defer approval.

File: src/storage/src/source/postgres/replication.rs (hunk 2 above)
Comment (petrosagg) [reply src/storage/src/source/postgres/replication.rs:372]: There is no need to downgrade the capability until we are about to yield, which happens a few lines below and there the capability is downgraded once

**Comment by benesch** [comment]
Can we add a bounded memory test to verify that this works as intended? cc @MaterializeInc/testing

**Comment by nrainer-materialize** [comment]
> Can we add a bounded memory test to verify that this works as intended? cc @MaterializeInc/testing

Sure, happy to do that! We already have Postgres scenarios in the bounded-memory check, is there anything particular that we want to include in the test? Or should I just pick an existing test and add transaction handling to Postgres statements?

I don't need to set any flags, do I?

**Comment by def-** [comment]
You can try running a huge transaction with many individual queries in it, DELETEs seem to work,but INSERTs/UPDATEs should too. Background for this issue: https://materializeinc.slack.com/archives/C01CFKM1QRF/p1711400449670959
Verify that before the PR the bounded memory test runs out of memory for the new scenario and with the PR it stays within reasonable memory limits. Then we have a regression test for this.

**Comment by nrainer-materialize** [comment]
The test is in https://github.com/MaterializeInc/materialize/pull/26287; I can push the commit to this branch once it is final (still tuning the memory config).

**Comment by nrainer-materialize** [comment]
> Can we add a bounded memory test to verify that this works as intended? cc @MaterializeInc/testing

I added https://github.com/MaterializeInc/materialize/pull/26287, which should now merge automatically. Preliminary tests have shown that it should be possible to reduce the memory limit by 0.5Gb with this PR.

**Comment by guswynn** [comment]
fixed the build but git wasn't letting me push to this branch: https://github.com/MaterializeInc/materialize/pull/26366

**Comment by petrosagg** [comment]
@nrainer-materialize this PR is ready, did you want to push a commit that enables your tests?

File: src/storage/src/source/postgres/replication.rs [hunk 3]
```diff
@@ -216,14 +216,12 @@ pub(crate) fn render<G: Scope<Timestamp = MzOffset>>(
...
             super::ensure_replication_slot(&replication_client, slot).await?;
-            let slot_lsn = super::fetch_slot_resume_lsn(&replication_client, slot).await?;
 
             let resume_upper = Antichain::from_iter(
                 subsource_resume_uppers
                     .values()
                     .flat_map(|f| f.elements())
-                    // Advance any upper as far as the slot_lsn.
-                    .map(|t| std::cmp::max(*t, slot_lsn)),
+                    .cloned(),
```
Comment (guswynn) [inline src/storage/src/source/postgres/replication.rs:224]: how was this `fetch_slot_resume_lsn` code originally justified?

File: src/storage/src/source/source_reader_pipeline.rs [hunk 4]
```diff
@@ -896,9 +896,11 @@ where
             if as_of.iter().all(|t| !upper.less_equal(t)) {
                 let committed_upper = frontiers[1].frontier();
                 if as_of.iter().all(|t| !committed_upper.less_equal(t)) {
-                    // Compute the frontier of the binding that is *less than* the committed upper.
+                    // We accumulate all the bindings that are not beyond the committed upper,
+                    // which has the effect of calculating the value of the previous binding than
+                    // the one directly at committed upper.
                     let idx =
-                        ready_times.partition_point(|(_, t, _)| !committed_upper.less_than(t));
+                        ready_times.partition_point(|(_, t, _)| !committed_upper.less_equal(t));
```
Comment (guswynn) [inline src/storage/src/source/source_reader_pipeline.rs:903]: can we add some justification as to why we want the previous binding, as opposed to the one _at_ the upper we are trying to reclock? to me, its unclear

File: src/storage/src/source/postgres/replication.rs (hunk 3 above)
Comment (sploiselle) [reply src/storage/src/source/postgres/replication.rs:224]: When adding a subsource, we needed to move the frontier from `0` to whatever the `slot_lsn` is (i.e. it would be at least this value because of snapshotting).

Comment (rjobanp) [reply src/storage/src/source/postgres/replication.rs:224]: Now that this is removed, will we still correctly hit the case that throws the `SlotCompactedPastResumePoint` below if the slot is in-fact compacted beyond our resume point?

**Comment by nrainer-materialize** [comment]
> @nrainer-materialize this PR is ready, did you want to push a commit that enables your tests?

Yes, sure! The test has already landed on main but let me check if I can tighten its memory constraints with your changes.

File: src/storage/src/source/postgres/replication.rs (hunk 3 above)
Comment (petrosagg) [reply src/storage/src/source/postgres/replication.rs:224]: > When adding a subsource, we needed to move the frontier from 0 to whatever the slot_lsn is (i.e. it would be at least this value because of snapshotting).

I reached the same conclusion yesterday but I don't understand how all tests are passing now that I allow the resume lsn to regress

**Comment by nrainer-materialize** [comment]
> I will evaluate the results once they are ready.

Sorry, something went wrong, I need to retrigger them... I hope to have the results ready in the next few hours.

**Comment by nrainer-materialize** [comment]
> > I will evaluate the results once they are ready.
> 
> Sorry, something went wrong, I need to retrigger them... I hope to have the results ready in the next few hours.
> 
>     * [build before (7192)](https://buildkite.com/materialize/nightlies/builds/7192) and [build before (7197)](https://buildkite.com/materialize/nightlies/builds/7197)
> 
>     * [build after (7191)](https://buildkite.com/materialize/nightlies/builds/7191)

Alright!

Before this change, memory requirements were approx:
* `materialized_memory=4.2Gb`
* `clusterd_memory=2.0Gb`

After this change, they are approx:
* `materialized_memory=3.6Gb`
* `clusterd_memory=1.4Gb`

@petrosagg: Is this in line with your expectations?

The current configuration is:
* `materialized_memory=4.5Gb`
* `clusterd_memory=3.5Gb`

I will change it to the following, keeping some buffer:
* `materialized_memory=4.0Gb`
* `clusterd_memory=1.8Gb`

File: src/storage/src/source/postgres/replication.rs (hunk 3 above)
Comment (petrosagg) [reply src/storage/src/source/postgres/replication.rs]: I re-added this piece of code in this PR since it's unclear of what is going on here

File: src/storage/src/source/source_reader_pipeline.rs (hunk 4 above)
Comment (petrosagg) [reply src/storage/src/source/source_reader_pipeline.rs]: done

**Comment by nrainer-materialize** [comment]
> Before this change, memory requirements were approx:
> 
>     * `materialized_memory=4.2Gb`
>     * `clusterd_memory=2.0Gb`

This memory stuff is completely unpredictable! It was running in main with the default `clusterd_memory` so far, which is `3.5Gb` and still OOMed in the build for the release (https://buildkite.com/materialize/nightlies/builds/7249). (A retry succeeded.)
