### PR TITLE
Don't push `error_if_null` through a Join

### LINKED ISSUE #20769: `pg_has_role` doesn't really work due to eval order issues
### What version of Materialize are you using?

9e480a9d104d6a734937758062a787f4f217a20c

### What is the issue?

```
materialize=> CREATE ROLE r2;
CREATE ROLE
materialize=> select * from (select 'aaa' as aaa) where pg_has_role('r2', aaa, 'USAGE');
ERROR:  role "r2" does not exist
```
(no need to enable RBAC)

One thing that might solve it is if we wouldn't forward errors from a join input when one of the other inputs is empty. Both `FoldConstants` and the rendering currently forwards the error even in this case. It would be easy to make `FoldConstants` not forward, but the rendering is a different question...

We might also approach the problem from this side: https://github.com/MaterializeInc/materialize/issues/5670, which might have a simpler repro (although I'm not really sure whether that is actually the same problem).

Big Slack thread: https://materializeinc.slack.com/archives/C02PPB50ZHS/p1690210975796329

### PR DESCRIPTION
**Pull request by ggevay**
Fixes #20769

Look at the 6th `predicate_pushdown` in this trace (counting from the top of the page): https://gist.github.com/ggevay/6645e66938ae515efb804b6e93fa7e75
It's pushing a predicate that involves `error_if_null` through several Joins. The second Join (the CrossJoin) is an instance of the empty-scalar-subquery-results-in-a-single-null pattern. The bug occurs in the CrossJoin as follows:
- The first input of the CrossJoin is usually empty (i.e., when the scalar subquery is not empty).
- The second Join input has a constant null at the bottom, coming from the above-mentioned pattern.
- Starting from that constant null, we const fold the second join input into an error.
- Unfortunately, both Join const folding and Join rendering will propagate an error from an input even when an other input is empty.

This PR prevents `PredicatePushdown` from pushing any such predicate through a Join that involves `error_if_null`.

@jkosh44, can you please check that the tests make sense (and maybe suggest more tests)?

### Motivation

  * This PR fixes a recognized bug: #20769

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by jkosh44 — APPROVED** [review]
Test makes sense (I haven't looked at non-test code)

File: src/expr/src/scalar/mod.rs [hunk 1]
```diff
@@ -645,6 +645,22 @@ impl MirScalarExpr {
         matches!(self, MirScalarExpr::Literal(Err(_), _typ))
     }
 
+    pub fn contains_error_if_null(&self) -> Result<bool, RecursionLimitError> {
+        let mut result = false;
+        self.visit_post(&mut |expr: &MirScalarExpr| {
```
Comment (aalexandrov) [inline src/expr/src/scalar/mod.rs:650]: nit: I suggest using `MirRelationExpr::visit_pre` (which is not fallable) here. You can also roll your own worklist iteration which will allow you to exit early and not traverse the entire tree once you see an `ErrorIfNull` call.

File: src/transform/src/predicate_pushdown.rs [hunk 2]
```diff
@@ -850,9 +850,18 @@ impl PredicatePushdown {
...
             for (index, push_down) in push_downs.iter_mut().enumerate() {
-                if predicate.is_literal_err() {
+                if predicate.is_literal_err() || predicate.contains_error_if_null()? {
                     // Do nothing. We don't push down literal errors,
                     // as we can't know the join will be non-empty.
+                    //
+                    // We also don't want to push anything that involves `error_if_null`. This is
+                    // for the same reason why in theory we shouldn't really push anything that can
+                    // error, assuming that we want to preserve error semantics. (Because we would
+                    // create a spurious error if an other Join input ends up empty.) We can't fix
```
Comment (aalexandrov) [inline src/transform/src/predicate_pushdown.rs:860]: nit: "an other" ⇒ "another"

**Review by aalexandrov — APPROVED** [review]
Transform changes LGTM.

File: src/expr/src/scalar/mod.rs (hunk 1 above)
Comment (ggevay) [reply src/expr/src/scalar/mod.rs:650]: But this is a `MirScalarExpr`, which doesn't seem to have an infallible `visit_pre`.

Also, I tried writing a worklist iteration, but got stuck:
```
    pub fn contains_error_if_null(&self) -> bool {
        let mut worklist = vec![self];
        while let Some(expr) = worklist.pop() {
            if matches!(
                expr,
                MirScalarExpr::CallVariadic {
                    func: VariadicFunc::ErrorIfNull,
                    ..
                }
            ) {
                return true;
            }
            expr.visit_children(|child| worklist.push(child));
        }
        false
    }
```
This gives me
```
error[E0521]: borrowed data escapes outside of closure
   --> src/expr/src/scalar/mod.rs:660:41
    |
649 |         let mut worklist = vec![self];
    |             ------------ `worklist` declared here, outside of the closure body
...
660 |             expr.visit_children(|child| worklist.push(child));
    |                                  -----  ^^^^^^^^^^^^^^^^^^^^ `child` escapes the closure body here
    |                                  |
    |                                  `child` is a reference that is only valid in the closure body
```
which I guess makes sense, since the compiler can't know that `visit_children` is passing references to stuff that is inside `expr` and not to stuff that it is making up itself.

Note that worklist iterations on `MirRelationExpr` use the `children()` method instead of `visit_children`, but we don't seem to have `children()` on `MirScalarExpr`. Should I maybe write it?

Comment (ggevay) [reply src/expr/src/scalar/mod.rs]: Ok, I implemented `MirScalarExpr::children()`. Could you please check?

**Review by aalexandrov — APPROVED** [review]
LGTM.
