### PR TITLE
coord,dataflow: stop returning canceled responses from compute

### LINKED ISSUE #11507: cluster: SELECTs issues to a non-functional cluster can not be Ctrl+C-ed
### What version of Materialize are you using?

v0.25.1-dev (64e7ea273)

### How did you install Materialize?

Built from source

### What was the issue?

If a `CREATE CLUSTER` is provided with , for example, incorrect hostnames, any SELECTs will hang in a way that is not Ctrl+C-able. This is in contrast with the other ways a `SELECT` can hang, e.g. if the chosen timestamp has not yet arrived, which (mostly) react to Ctrl+C as expected.

```
materialize=>  CREATE CLUSTER default REMOTE replica1 ('dataflowd_compute_1:6876', 'dataflowd_compute_2:6876');
CREATE CLUSTER
materialize=> select * from t1;
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
```

### Relevant log output

```source
...
2022-04-01T12:07:22.451615Z  WARN mz_dataflow_types::client::tcp: Error connecting to dataflowd_compute_2:6876: failed to lookup address information: Temporary failure in name resolution; reconnecting in 1s
2022-04-01T12:07:22.451647Z  WARN mz_dataflow_types::client::tcp: Error connecting to dataflowd_compute_1:6876: failed to lookup address information: Temporary failure in name resolution; reconnecting in 1s
...
```

### PR DESCRIPTION
**Pull request by mjibson**
Change the cancel protocol between coord and controller so that coord
no longer waits for cancel peek messages from the controller. Remove
the entire enum variant and introduce a new type so it is clear that
the compute layer has no ability to send a cancel response.

Fixes #11507

### Motivation

  * This PR fixes a recognized bug. #11507

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - n/a

### CODE REVIEW

File: src/dataflow-types/src/types.rs [hunk 1]
```diff
@@ -51,13 +50,30 @@ impl PeekResponse {
...
+            PeekResponse::Error(_) => {
                 panic!("PeekResponse::unwrap_rows called on {:?}", self)
             }
         }
     }
 }
 
+/// Peek responses that the controller can provide back to the coordinator.
+#[derive(Clone, Debug, Serialize, Deserialize)]
+pub enum CoordPeekResponse {
```
Comment (benesch) [inline src/dataflow-types/src/types.rs:62]: This is a bit of an abstraction violation—can this type get hoisted into the `coord` crate?

**Review by benesch — COMMENTED** [review]
So good! Really glad you were able to get a test working. Can we figure out some way to get the `CoordPeekResponse` type into the `coord` crate though?

File: src/dataflow-types/src/types.rs (hunk 1 above)
Comment (mjibson) [reply src/dataflow-types/src/types.rs:62]: I've also realized it's just...wrong. The controller never sends a Cancel, so it should still be sending a regular PeekResponse, and only the coord gets to see a CoordPeekResponse. Will move.

**Comment by mjibson** [comment]
Moved CoordPeekResponse to coord. Added a second commit that also moves PeekResponseUnary to coord for the same reason, although that change is just code movement and has zero functional change.

**Comment by frankmcsherry** [comment]
Let me take a peek before merging if you don't mind! I want to check that the compute layer still does all the things it needs to do wrt collecting up the peeks and such.

File: src/compute/src/compute_state.rs [hunk 2]
```diff
@@ -190,20 +190,10 @@ impl<'a, A: Allocate, B: ComputeReplay> ActiveComputeState<'a, A, B> {
...
-                        self.send_peek_response(peek, PeekResponse::Canceled);
-                    } else {
-                        self.compute_state.pending_peeks.push(peek);
-                    }
-                }
-            }
+            ComputeCommand::CancelPeeks { uuids } => self
+                .compute_state
+                .pending_peeks
+                .retain(|peek| !uuids.contains(&peek.peek.uuid)),
```
Comment (frankmcsherry) [inline src/compute/src/compute_state.rs:196]: I think this change is not correct, in that sending a peek response of `Canceled` is how we communicate back to the surrounding compute infrastructure that the peek has been dealt with. Not doing that will result I believe in the compute instance retaining the peek indefinitely, and the dataflow on which it depends, and redeploying them to all replicas.

**Review by frankmcsherry — CHANGES_REQUESTED** [review]
The PR makes some changes that will introduce bad behavior for COMPUTE, in that canceled peeks will e.g. not be removed from `ActiveReplication::peeks`, which happens only by way of peek responses returned. It can be changed to happen instead in response to observing peek cancelation commands, but possibly the whole of `ComputeCommandHistory` should be updated in that case.

If there is a smaller change to make instead, perhaps just to ADAPTER, which can be followed by COMPUTE work that changes its own behavior, that would be easier to merge.

**Comment by benesch** [comment]
Oh, good point! The controller itself is smart enough to remove peeks when you call `cancel_peeks`: https://github.com/MaterializeInc/materialize/blob/d06ce5c7d3933aa934fdf1378582831523ae15fb/src/dataflow-types/src/client/controller/compute.rs#L399

But `ActiveReplication` is not. It seems easy enough to amend `ActiveReplication::send` to remove peeks when it observes a `CancelPeek` flowing past, rather than when it observes `PeekResponse::Canceled`? https://github.com/MaterializeInc/materialize/blob/d06ce5c7d3933aa934fdf1378582831523ae15fb/src/dataflow-types/src/client/replicated.rs#L128

**Comment by benesch** [comment]
@frankmcsherry, seems like an easy fix:

```diff
diff --git a/src/dataflow-types/src/client/replicated.rs b/src/dataflow-types/src/client/replicated.rs
index 77f181e24..3c3741f07 100644
--- a/src/dataflow-types/src/client/replicated.rs
+++ b/src/dataflow-types/src/client/replicated.rs
@@ -126,9 +126,17 @@ where
     T: timely::progress::Timestamp + differential_dataflow::lattice::Lattice + std::fmt::Debug,
 {
     async fn send(&mut self, cmd: ComputeCommand<T>) -> Result<(), anyhow::Error> {
-        // Register an interest in the peek.
-        if let ComputeCommand::Peek(Peek { uuid, .. }) = &cmd {
-            self.peeks.insert(*uuid);
+        // Sniff out peek commands to update our peek tracking.
+        match &cmd {
+            ComputeCommand::Peek(Peek { uuid, .. }) => {
+                self.peeks.insert(*uuid);
+            }
+            ComputeCommand::CancelPeeks { uuids } => {
+                for uuid in uuids {
+                    self.peeks.remove(uuid);
+                }
+            }
+            _ => (),
         }
 
         // Initialize any necessary frontier tracking.
```

Would you still prefer to do this over two PRs?

**Comment by frankmcsherry** [comment]
Maybe! The actual work to do is to check out the other parts of the result pipeline, uses of `PeekResponse` and see that there are not other things that need to do work on peek responses such as `PeekResponse::Canceled`. I don't know for sure that this is the only glitch. Imo, still easiest to do the ADAPTER fix, and then file an issue that COMPUTE can optimize the response away.

**Comment by frankmcsherry** [comment]
For example, there is an apparent race now in `partitioned.rs` where a peek cancelation that races with responses may not have all workers return, and so the state will not be cleaned up.

**Comment by benesch** [comment]
> For example, there is an apparent race now in partitioned.rs where a peek cancelation that races with responses may not have all workers return, and so the state will not be cleaned up.

Ah, indeed. 

>  Imo, still easiest to do the ADAPTER fix, and then file an issue that COMPUTE can optimize the response away.

Ack, works for me. I think it'd be ideal to have @mjibson send that PR as a fast follow, since we've all got the context paged in right now.

**Comment by frankmcsherry** [comment]
> Ack, works for me. I think it'd be ideal to have @mjibson send that PR as a fast follow, since we've all got the context paged in right now.

If it ends up being easy, great! However, if @mjibson ends up having to invent a new approach to suppressing peek responses that does not introduce a non-droppable tombstone for each canceled peek, we can also punt on that for now!

**Comment by mjibson** [comment]
I removed the dataflow changes and left only the coord change that immediately sends the cancel response to itself.

**Review by frankmcsherry — APPROVED** [review]
This looks great, thanks!
