### PR TITLE
storage: handle transient errors during decoding

### LINKED ISSUE #6185: Transient issues with the schema registry can cause permanent errors in the source stream
### What version of Materialize are you using?

```
v0.7.2-dev (f63a8eb91)
```

### What was the issue?

The REST API calls that are made to the schema registry when ingesting Avro data are not protected against transient issues. They are not retried so any sort of tranisent error would cause the stream to error out permanently.

### Is the issue reproducible? If so, please provide reproduction instructions.

1. In one terminal, mess with the schema registry:
```
while true ; do pkill -f schema-registry ; sleep 1 ;  confluent local services schema-registry start ; sleep 1; done
```
2. In another terminal, run testdrive:
```
../../target/release/testdrive  avro-resolution*
```

Sometimes this will error out in ```kafka-ingest```, which is OK, but sometimes it willl error out on a ```SELECT```:

```
> SELECT f1 FROM resolution_enums
rows didn't match; sleeping to see if dataflow catches up 125ms 250ms 500ms 1s 2s 4s 2.112008138s
avro-resolution-enums.td:37:1: error: executing query failed: db error: ERROR: Decode error: Text: avro deserialization error: transport: error sending request for url (http://localhost:8081/schemas/ids/41): error trying to connect: tcp connect error: Connection refused (os error 111)
     |
  36 | 
  37 | > SELECT f1 FROM resolution_enums
     | ^
```

Note that the error message here is the more verbose one suggested in #6153 . Without that patch, it will simply say ```Failed to fetch schema with ID 18```

### PR DESCRIPTION
**Pull request by petrosagg**
Change the function signatures of all methods that can fail transiently to be a double `Result` where the outer `Result` represents whether a transient error happened and the inner `Result` is the definite result of decoding the bytes.

This separates things that should be permanently recorded in the shard (the inner errors) from things that should simply restart the dataflow (outer errors). At the same time it makes it easy to propagate a transient error upwards (just using the `?` operator) and hard to accidentally put a transient error in the shard (since you have to manually deconstruct the error and put it there).

This bubbling up of transient errors terminates in the future passed to `build_fallible` which was integrated in #20150 and will restart the ingestion dataflow if a transient error reaches that point.

Fixes #6185

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

File: src/interchange/src/avro/schema.rs [hunk 1]
```diff
@@ -327,14 +327,20 @@ impl ConfluentAvroResolver {
...
+                };
                 bytes = adjusted_bytes;
-                let schema = cache
+                let result = cache
                     .get(schema_id, &self.reader_schema)
-                    .await
-                    .with_context(|| {
-                        format!("failed to resolve Avro schema (id = {})", schema_id)
-                    })?;
+                    .await?
```
Comment (guswynn) [inline src/interchange/src/avro/schema.rs:338]: this is the only transient error right? each place like this should be documented (as well as each function with a nested result)

File: src/interchange/src/avro/decode.rs [hunk 2]
```diff
@@ -91,13 +91,16 @@ impl Decoder {
...
     /// Decodes Avro-encoded `bytes` into a `Row`.
-    pub async fn decode(&mut self, bytes: &mut &[u8]) -> anyhow::Result<Row> {
+    pub async fn decode(&mut self, bytes: &mut &[u8]) -> Result<Result<Row, Error>, Error> {
         // Clear out any bytes that might be left over from
         // an earlier run. This can happen if the
         // `dsr.deserialize` call returns an error,
         // causing us to return early.
         let mut packer = self.row_buf.packer();
-        let (bytes2, resolved_schema, csr_schema_id) = self.csr_avro.resolve(bytes).await?;
+        let (bytes2, resolved_schema, csr_schema_id) = match self.csr_avro.resolve(bytes).await? {
```
Comment (guswynn) [inline src/interchange/src/avro/decode.rs:100]: the `?` should be documented as handling transient errors

File: src/storage/src/decode/mod.rs [hunk 3]
```diff
@@ -100,8 +100,8 @@ pub fn render_decode_cdcv2<G: Scope<Timestamp = Timestamp>>(
                     None => continue,
                 };
                 let (mut data, schema, _) = match resolver.resolve(&*value).await {
-                    Ok(ok) => ok,
-                    Err(e) => {
+                    Ok(Ok(ok)) => ok,
+                    Ok(Err(e)) | Err(e) => {
```
Comment (guswynn) [inline src/storage/src/decode/mod.rs:104]: this is cdcv2, so not as important, but this second case should restart the dataflow right? probably worth a TODO

**Review by guswynn — APPROVED** [review]
a few nits to add comments, but this looks good (and backportable!)!

File: src/interchange/src/avro/decode.rs (hunk 2 above)
Comment (petrosagg) [reply src/interchange/src/avro/decode.rs:100]: What we actually need to do is define a `TransientError` and various `OtherError` types so that `?` doesn't accidentally work with both, but that's something for a future PR

File: src/interchange/src/avro/schema.rs (hunk 1 above)
Comment (petrosagg) [reply src/interchange/src/avro/schema.rs]: done

File: src/interchange/src/avro/decode.rs (hunk 2 above)
Comment (guswynn) [reply src/interchange/src/avro/decode.rs:101]: sounds good!
