### PR TITLE
test: fix `~_protobuf_roundtrip` stack overflows in `cargo test`

### LINKED ISSUE #14543: CI: Stack overflow in Cargo Test mz-compute-client.lib
### What version of Materialize are you using?

`main`

### How did you install Materialize?

Docker image

### What is the issue?

In CI Cargo test sometimes will error with a stack overflow. I've seen it multiple times over the past month, though I'm not sure if it's always the same test. This build failed on `mz-compute-client.lib`: https://buildkite.com/materialize/tests/builds/40627#0182f439-caf5-4760-a3c2-2e61c08e6619

### Relevant log output

```source
mz-compute-client.lib
 
thread 'command::tests::compute_command_protobuf_roundtrip' has overflowed its stack
fatal runtime error: stack overflow
/usr/local/bin/run-tests: line 23:  2327 Aborted                 "/tests/$binary" -Z unstable-options --format json --report-time
{"type":"suite","event":"started","test_count":12}
{"type":"test","event":"started","name":"mz-compute-client::lib::command::tests::compute_command_protobuf_roundtrip"}
{"type":"test","event":"started","name":"mz-compute-client::lib::command::tests::dataflow_description_protobuf_roundtrip"}
{"type":"test","event":"started","name":"mz-compute-client::lib::command::tests::peek_protobuf_roundtrip"}
{"type":"test","event":"started","name":"mz-compute-client::lib::logging::tests::logging_config_protobuf_roundtrip"}
{"type":"test","event":"started","name":"mz-compute-client::lib::plan::join::tests::join_plan_protobuf_roundtrip"}
{"type":"test","event":"started","name":"mz-compute-client::lib::plan::reduce::tests::reduce_plan_protobuf_roundtrip"}
{"type":"test","event":"started","name":"mz-compute-client::lib::plan::tests::available_collections_protobuf_roundtrip"}
{"type":"test","event":"started","name":"mz-compute-client::lib::plan::tests::get_plan_protobuf_roundtrip"}
{"type":"test","event":"started","name":"mz-compute-client::lib::plan::tests::plan_protobuf_roundtrip"}
{"type":"test","event":"started","name":"mz-compute-client::lib::plan::threshold::tests::threshold_plan_protobuf_roundtrip"}
{"type":"test","event":"started","name":"mz-compute-client::lib::plan::top_k::tests::top_k_plan_protobuf_roundtrip"}
{"type":"test","event":"started","name":"mz-compute-client::lib::response::tests::compute_response_protobuf_roundtrip"}
{"type":"test","name":"mz-compute-client::lib::plan::top_k::tests::top_k_plan_protobuf_roundtrip","event":"ok","exec_time":0.160669233}
{"type":"test","name":"mz-compute-client::lib::plan::tests::available_collections_protobuf_roundtrip","event":"ok","exec_time":0.16680263}
{"type":"test","name":"mz-compute-client::lib::plan::tests::get_plan_protobuf_roundtrip","event":"ok","exec_time":0.559234665}
{"type":"test","name":"mz-compute-client::lib::response::tests::compute_response_protobuf_roundtrip","event":"ok","exec_time":1.551700872}
{"type":"test","name":"mz-compute-client::lib::plan::threshold::tests::threshold_plan_protobuf_roundtrip","event":"ok","exec_time":2.6065856590000003}
{"type":"test","name":"mz-compute-client::lib::plan::tests::plan_protobuf_roundtrip","event":"ok","exec_time":5.064032744}
{"type":"test","name":"mz-compute-client::lib::command::tests::peek_protobuf_roundtrip","event":"ok","exec_time":6.051882816}
```

### PR DESCRIPTION
**Pull request by aalexandrov**
Try various things in order to reduce (and hopefully completely eliminate) stack overflows in `~_protobuf_roundtrip` tests.

### Motivation

  * This PR fixes a recognized bug.

Fixes #14543, which is caused due to the problem described in proptest-rs/proptest#249. 

From the analysis of the stacktraces in  #14543 it was evident that the bulk of the stack size was consumed by `TupleUnion::new_value` calls, so the two commits that actually touch code in this PR implement strategies to avoid those (especially for `enum` structs).

### Tips for reviewer

- The first commit bans the use of `prop_oneof!` in favor of `proptest::strategy::Union::new`. The latter is only selected by `prop_oneof!` if the list contains more than 9 entries, so we should avoid using it in order to not create `TupleUnion` constructs. @sploiselle: this might be of interest to you as you are currently touching some code that deals with that.
- The second commit bumps up the `proptest-derive` version and enables the new `boxed_union` feature that [I added to our `proptest` fork today](https://github.com/proptest-rs/proptest/commit/fc9660f0f45ad49949d42341f964597a44e5fce0).
- The third commit re-enables `_protobuf_roundtrip` tests that are currently ignored.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - There are no user-facing behavior changes.

### CODE REVIEW

File: bin/check [hunk 1]
```diff
@@ -185,6 +185,11 @@ extra_lints=(
     # TODO(guswynn): renamed this to `disallowed_methods` when we upgrade
```
Comment (benesch) [inline bin/check:185]:
```suggestion
```

Got fixed here: https://github.com/MaterializeInc/materialize/commit/2e6dea49a20ceab976569f977c5d70fecc8833aa

File: bin/check [hunk 2]
```diff
@@ -185,6 +185,11 @@ extra_lints=(
...
     clippy::disallowed_methods
 
+    # suggest better alternatives
+    # See `clippy.toml` for more info
+    # TODO(guswynn): renamed this to `disallowed_methods` when we upgrade
```
Comment (benesch) [inline bin/check:190]:
```suggestion
```

File: src/compute-client/src/types/sinks.rs [hunk 3]
```diff
@@ -79,12 +79,53 @@ impl RustType<ProtoComputeSinkDesc> for ComputeSinkDesc<CollectionMetadata, mz_r
...
+#[derive(Clone, Debug, Serialize, Deserialize, Eq, PartialEq)]
 pub enum ComputeSinkConnection<S = ()> {
     Subscribe(SubscribeSinkConnection),
     Persist(PersistSinkConnection<S>),
 }
 
+// This is just the expanded macro with an additional `S: 'static` bound on to
+// make the `boxed_union`-based strategy happy. We can remove this code and go
+// back to the derived version if we can afford to put the bound on the enum
+// definition.
```
Comment (benesch) [inline src/compute-client/src/types/sinks.rs:91]: Putting that bound on the `enum` definition is definitely fine. It would be _extremely_ weird if we needed to support borrowed data in this type.

**Review by benesch — APPROVED** [review]

**Comment by aalexandrov** [comment]
I ran all `~_protobuf_roundtrip` tests about ~30 times in debug mode in succession on my machine without hitting a stack overflow. Before the change this was more or less guaranteed every time, so clearly a step in the right direction.

If you encounter problems my suggestion is to revert only the last commit rather than the entire PR.

**Comment by sploiselle** [comment]
@aalexandrov ty for the heads up; this seems just as ergonomic as the macro so 👍
