### PR TITLE
storage: make sure we efficiently batch records from sources

### LINKED ISSUE #17444: regression: OOM, Kafka upsert sources 2x slower after "storage: push native timestamps further"
### What version of Materialize are you using?

6cf2ab2b102ffb18456f5e6c05982919bfa7bc6d

### How did you install Materialize?

Docker image

### What is the issue?

The feature benchmark is reporting the following consistent and reproducible performance regression:

```
Benchmark Report for cycle 5: | 0s
-- | --
  | NAME                      \|    THIS     \|    OTHER    \|  Regression?  \| 'THIS' is:
  | ----------------------------------------------------------------------------------------------------
  | KafkaUpsert               \|       8.167 \|       4.136 \|    !!YES!!    \| 97.5 pct   slower
  | KafkaUpsertUnique         \|       6.798 \|       4.984 \|    !!YES!!    \| 36.4 pct   slower
```

Bisection reported the following commit:

```
6cf2ab2b102ffb18456f5e6c05982919bfa7bc6d is the first bad commit
commit 6cf2ab2b102ffb18456f5e6c05982919bfa7bc6d
Merge: 788a58a74 c2436f733
Author: Petros Angelatos <petrosagg@gmail.com>
Date:   Mon Jan 30 23:36:36 2023 +0100

    Merge pull request #16214 from petrosagg/native-timestamp-ingestion
    
    storage: push native timestamps further
```

@petrosagg FYI

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by petrosagg**
Due to a common pattern in async operators, namely activating the output handle, creating a session, sending a single message, and immediately deactivating the code in `main` was creating one batch per message which had the effect of allocating a ton of small vectors and making performance much worse.

This pattern is used because there is an impedence mismatch between how output handles work and how async operators work. Ideally what we want is a handle that will buffer messages and automatically flushes when the async future gets into a `Pending` state.

This handle doesn't exist (yet) and it's complicated to write.

This PR fixes the immediate issue by rearranging the code so that output handle activation can be done once for all the messages that are currently ready and leaves the specialized async output handle for a Future(ha) date.

Fixes #17444

Link to successful nightly run: https://buildkite.com/materialize/nightlies/builds/1750#01860d93-9264-4cd4-bf41-6fce2f9b20e2

```
KafkaUpsert               |       4.401 |       4.137 |      no       | 6.4 pct   slower
KafkaUpsertUnique         |       5.452 |       4.962 |      no       | 9.9 pct   slower
```

I think some of the remaining slowness is because even though I changed the framework code to batch up messages the sources still manipulate their internal capability per-message which means that there are a lot more progress updates generated. Eventually we'll push a similar batching logic into the sources themselves which should make things a bit faster. For now we can live with a 8% perf hit

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by aljoscha** [comment]
This should fix https://github.com/MaterializeInc/materialize/issues/17444, right?

File: src/storage/src/source/source_reader_pipeline.rs [hunk 1]
```diff
@@ -401,56 +399,66 @@ where
...
+                        match source_stream.next().now_or_never() {
+                            Some(Some(SourceMessageType::Message(message, cap, diff))) => {
+                                let new_status = match message {
+                                    Ok(_) => HealthStatus::Running,
+                                    Err(ref error) => {
+                                        HealthStatus::StalledWithError(error.inner.to_string())
+                                    }
+                                };
+
+                                let new_status_update = HealthStatusUpdate {
```
Comment (aljoscha) [inline src/storage/src/source/source_reader_pipeline.rs:419]: side note (not for this PR): all this status handling per message seems a bit wasteful, but idk.. there's bigger fish to fry 🤷

File: src/storage/src/source/source_reader_pipeline.rs [hunk 2]
```diff
@@ -967,17 +967,12 @@ where
...
-                    let mut ready_upper = timestamper.source_upper();
-                    ready_upper.extend(source_upper.frontier().iter().cloned());
-
                     // Drain all messages that can be reclocked from all the batches
                     let total_buffered: usize = untimestamped_batches.iter().map(|b| b.len()).sum();
                     let msgs = untimestamped_batches
                         .iter_mut()
                         .flat_map(|batch| batch.drain_filter_swapping(|(_, ts, _)| {
-                            !ready_upper.less_equal(ts)
+                            !timestamper.source_upper().less_equal(ts)
```
Comment (aljoscha) [inline src/storage/src/source/source_reader_pipeline.rs:975]: ah yes, as soon as we have the remap information we can reclock and retire, right?

**Review by aljoscha — APPROVED** [review]

**Comment by petrosagg** [comment]
It fixes the bounded memory failure. There is still the perf regression but I think I found the cause. I'll update this PR soon

File: src/storage/src/source/source_reader_pipeline.rs (hunk 2 above)
Comment (petrosagg) [reply src/storage/src/source/source_reader_pipeline.rs:975]: Yes

**Comment by aljoscha** [comment]
> I'll update this PR soon

🍿

File: src/storage/src/source/source_reader_pipeline.rs [hunk 3]
```diff
@@ -454,6 +471,10 @@ where
                     // Now we drop the activated output handle to force timely to emit any pending
                     // batch. It's crucial that this happens before our attempt to yield otherwise
                     // the buffer would get stuck in this operator.
+                    if let Some(emit_cap) = emit_cap.take() {
+                        output.session(&emit_cap).give_container(&mut batch);
+                        batch.clear();
+                    }
```
Comment (aljoscha) [inline src/storage/src/source/source_reader_pipeline.rs:477]: Should we assert that the batch is empty here?

**Review by aljoscha — APPROVED** [review]
The additional changes look good! I had one suggestion about adding an `assert!`

File: src/storage/src/source/source_reader_pipeline.rs (hunk 3 above)
Comment (petrosagg) [reply src/storage/src/source/source_reader_pipeline.rs:477]: sure, will add

Comment (petrosagg) [reply src/storage/src/source/source_reader_pipeline.rs:477]: Yes, I'll add it

**Comment by petrosagg** [comment]
The nightly finished for this and they look good:

```
KafkaUpsert               |       4.401 |       4.137 |      no       | 6.4 pct   slower
KafkaUpsertUnique         |       5.452 |       4.962 |      no       | 9.9 pct   slower
```

I think some of the remaining slowness is because even though I changed the framework code to batch up messages the sources still manipulate their internal capability per-message which means that there are a lot more progress updates generated. Eventually we'll push a similar batching logic into the sources themselves which should make things a bit faster. For now we can live with a 8% perf hit
