### PR TITLE
Move cluster size resolution to the coordinator

### LINKED ISSUE #11968: Crash: Size "8" not specified in allowed cluster sizes map
### What version of Materialize are you using?

85be487e3c77bb828a46141c19f87f4e3017a8f0

### How did you install Materialize?

Built from source

### What was the issue?

Cluster size validation happens in the wrong place:

```
materialize=> drop cluster default cascade;
DROP CLUSTER
materialize=> create cluster default size "8";
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

### Relevant log output

```source
2022-04-21T14:19:47.328900Z ERROR panic: called `Result::unwrap()` on an `Err` value: Size "8" not specified in allowed cluster sizes map
thread: coordinator
location: /home/moritz/dev/repos/materialize/src/coord/src/coord.rs:1889:22
version: 0.26.1-dev (d3b684a1e37f401e18262a144f77130409983ebf)
backtrace:
   0: materialized::handle_panic
             at src/materialized/src/bin/materialized/main.rs:856:21
   1: core::ops::function::Fn::call
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:70:5
   2: std::panicking::rust_panic_with_hook
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:702:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
   5: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   6: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   7: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
   8: core::result::Result<T,E>::unwrap
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1065:23
      mz_coord::coord::Coordinator::sequence_create_compute_instance::{{closure}}
             at src/coord/src/coord.rs:1882:17
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
      mz_coord::coord::Coordinator::sequence_plan::{{closure}}
             at src/coord/src/coord.rs:1529:68
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
      mz_coord::coord::Coordinator::handle_execute::{{closure}}
             at src/coord/src/coord.rs:1365:66
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
      mz_coord::coord::Coordinator::message_command::{{closure}}
             at src/coord/src/coord.rs:971:62
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
      mz_coord::coord::Coordinator::serve::{{closure}}
             at src/coord/src/coord.rs:688:67
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
      tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:54
      tokio::coop::with_budget::{{closure}}
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
      std::thread::local::LocalKey<T>::try_with
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:413:16
      std::thread::local::LocalKey<T>::with
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:389:9
      tokio::coop::with_budget
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
      tokio::coop::budget
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
      tokio::park::thread::CachedParkThread::block_on
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:31
      tokio::runtime::enter::Enter::block_on
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/enter.rs:151:13
  12: tokio::runtime::handle::Handle::block_on
             at /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/handle.rs:355:9
  13: mz_coord::coord::serve::{{closure}}::{{closure}}
             at src/coord/src/coord.rs:4721:17
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:122:18
  14: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/mod.rs:498:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/mod.rs:497:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
  15: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys/unix/thread.rs:108:17
  16: start_thread
             at ./nptl/./nptl/pthread_create.c:481:8
  17: clone
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

materialized encountered an internal error and crashed.

We rely on bug reports to diagnose and fix these errors. Please
copy and paste the above details and file a report at:

    https://materialize.com/s/bug
```
```

### PR DESCRIPTION
**Pull request by umanwizard**
The mapping from strings to replica size config now lives in the coordinator, so that we can validate them before committing the add cluster command.

As part of this, I needed to split `ComputeInstanceConfig` into two types, to be used in different situations: one has a string name (as before) and is used during planning; the other, now called `ConcreteComputeInstanceConfig` has a resolved size and is used in the catalog and downstream of the coordinator. 

### Motivation

Fixes #11968 .

### Testing

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

  - Fix the crash reported in #11968 .

### CODE REVIEW

File: src/coord/src/error.rs [hunk 1]
```diff
@@ -324,6 +328,9 @@ impl fmt::Display for CoordError {
                 value.quoted(),
                 reason,
             ),
+            CoordError::InvalidReplicaSize { size } => {
+                write!(f, "Size {size} not specified in allowed cluster sizes map")
```
Comment (benesch) [inline src/coord/src/error.rs:332]: In Platform, the user won't know what the "allowed cluster sizes map" is, so recommend an error message like:

```suggestion
                write!(f, "unknown cluster size {size}")
```

Can you also add a hint that displays the known cluster sizes?

File: src/coord/src/error.rs [hunk 2]
```diff
@@ -324,6 +329,13 @@ impl fmt::Display for CoordError {
                 value.quoted(),
                 reason,
             ),
+            CoordError::InvalidReplicaSize { size, expected } => {
+                write!(
+                    f,
+                    "unknown cluster size {size}. Expected one of: {}.",
```
Comment (benesch) [inline src/coord/src/error.rs:335]: We try to follow the [PostgreSQL error style guide](https://www.postgresql.org/docs/current/error-style-guide.html) now. The "expected one of" should be in the hint field (see `fn hint` below).

The usual PostgreSQL style for this sort of hint, btw, is: "Valid cluster sizes are:  size1, size2, size3"

**Review by benesch — APPROVED** [review]
