### PR TITLE
sql: Make mz_schema_oid more robust

### LINKED ISSUE #21490: sql: has_schema_privilege will fail if schema is ambiguous
### What version of Materialize are you using?

v0.68.0-dev

### What is the issue?

If there are multiple schemas with the same name, then `has_schema_privilege` will fail.

```
materialize=> CREATE DATABASE d1;
CREATE DATABASE
materialize=> CREATE DATABASE d2;
CREATE DATABASE
materialize=> CREATE SCHEMA d1.s;
CREATE SCHEMA
materialize=> CREATE SCHEMA d2.s;
CREATE SCHEMA
materialize=> SELECT has_schema_privilege('materialize', 's', 'USAGE');
ERROR:  Evaluation error: more than one record produced in subquery
```

`has_schema_privilege` is defined as 

https://github.com/MaterializeInc/materialize/blob/60eeefe3203ffa9dacabc060dca3dfd5ef5cee8b/src/sql/src/func.rs#L2046

`mz_schema_oid` is defined as

https://github.com/MaterializeInc/materialize/blob/60eeefe3203ffa9dacabc060dca3dfd5ef5cee8b/src/sql/src/func.rs#L3837-L3852

The problem is that `(SELECT oid FROM mz_schemas WHERE name = $1)` returns multiple rows when the query is only expecting a single row. As indicated by the comments, it should only ever return a single row by taking into account the search path (or maybe the active database).

### PR DESCRIPTION
**Pull request by jkosh44**
This commit makes mz_schema_oid more robust by only searching for schemas in the current database of the session when a database is not explicitly specified. Additionally, this commit allows callers to specify the database of a schema when calling mz_schema_oid. As a result other functions that call mz_schema_oid, such as has_schema_privilege, also are more robust.

Fixes #21490

### Motivation
This PR fixes a recognized bug.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - Make has_schema_privileges more robust by taking into account the current database and any specified database.

### CODE REVIEW

File: src/sql/src/func.rs [hunk 1]
```diff
@@ -4102,19 +4102,42 @@ pub static MZ_INTERNAL_BUILTINS: Lazy<BTreeMap<&'static str, Func>> = Lazy::new(
...
-                        'schema \"' || $1 || '\" does not exist'
-                    )
+            ELSE
+                mz_unsafe.mz_error_if_null(
+                    (
+                        SELECT
+                            CASE
+                                -- Schema names should only have 2 components, so error if there's
+                                -- three.
+                                WHEN n[1] IS NOT NULL THEN
```
Comment (mjibson) [inline src/sql/src/func.rs:4116]: This took a while to figure out that it's because mz_normalize_object_name always returns an array with 3 items, the left most is indexed as 1, and it's the database. So weird but it works.

**Review by mjibson — APPROVED** [review]

File: src/sql/src/func.rs (hunk 1 above)
Comment (jkosh44) [reply src/sql/src/func.rs:4116]: I'll try and extract this logic into a `normalize_schema_name` function. That should hopefully be more readable and clear things up.
