### PR TITLE
sql: add format_type function

### LINKED ISSUE #4935: Python client via SqlAlchemy Table introspection `get_columns()` fails
### What version of Materialize are you using?

```
$ materialized -v

unstable

```

### How did you install Materialize?

* [x] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [ ] Built from source

### What was the issue?

We can't use the API to DESCRIBE a table and get its columns (which is very useful).
Follow-up of https://github.com/MaterializeInc/materialize/issues/4913

### Is the issue reproducible? If so, please provide reproduction instructions.

```
from sqlalchemy import inspect
from sqlalchemy.engine import create_engine

engine = create_engine('postgresql://localhost:6875/materialize')

inspector = inspect(engine)
inspector.get_columns(table_name='mz_columns', database_name='mz_catalog')
```

### Please attach any applicable log files.

```
>>> inspector.get_columns(table_name='mz_columns', database_name='mz_catalog')
Traceback (most recent call last):
  File "python3.8/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    self.dialect.do_execute(
  File "python3.8/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InternalError_: function "pg_catalog.format_type" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python3.8/site-packages/sqlalchemy/engine/reflection.py", line 372, in get_columns
    col_defs = self.dialect.get_columns(
  File "<string>", line 2, in get_columns
  File "python3.8/site-packages/sqlalchemy/engine/reflection.py", line 56, in cache
    ret = fn(self, con, *args, **kw)
  File "python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2814, in get_columns
    c = connection.execute(s, table_oid=table_oid)
  File "python3.8/site-packages/sqlalchemy/engine/base.py", line 2179, in execute
    return connection.execute(statement, *multiparams, **params)
  File "python3.8/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "python3.8/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "python3.8/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    ret = self._execute_context(
  File "python3.8/site-packages/sqlalchemy/engine/base.py", line 1252, in _execute_context
    self._handle_dbapi_exception(
  File "python3.8/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "python3.8/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "python3.8/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "python3.8/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    self.dialect.do_execute(
  File "python3.8/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.InternalError_) function "pg_catalog.format_type" does not exist

[SQL: 
            SELECT a.attname,
              pg_catalog.format_type(a.atttypid, a.atttypmod),
              (SELECT pg_catalog.pg_get_expr(d.adbin, d.adrelid)
                FROM pg_catalog.pg_attrdef d
               WHERE d.adrelid = a.attrelid AND d.adnum = a.attnum
               AND a.atthasdef)
              AS DEFAULT,
              a.attnotnull, a.attnum, a.attrelid as table_oid,
              pgd.description as comment
            FROM pg_catalog.pg_attribute a
            LEFT JOIN pg_catalog.pg_description pgd ON (
                pgd.objoid = a.attrelid AND pgd.objsubid = a.attnum)
            WHERE a.attrelid = %(table_oid)s
            AND a.attnum > 0 AND NOT a.attisdropped
            ORDER BY a.attnum
        ]
[parameters: {'table_oid': 20045}]
(Background on this error at: http://sqlalche.me/e/2j85)
```

### PR DESCRIPTION
**Pull request by sploiselle**
@romainr Any chance you can take a look and see if this works for you? We're in kind of an odd spot here because our range of supported values for our `numeric` type is much smaller than Postgres'––we only allow values up to 38, and we use a `u8` behind the scenes; PG supports scale and precision to 1000 and seems to use some kind of `u32` for valid typmod values (which they'll print here irrespective of its validity as input). This means we simply cannot output the same values without doing a lot of awkward plumbing. And then they have odd behavior with typmod values less than 4 that I tried to do something helpful with...anyway, it's a bit of a mess but there's a chance it'll do what you need!

Fixes #4935

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5225)

### CODE REVIEW

**Comment by romainr** [comment]
Sure, just is there a docker image with the change somewhere? (makes it easy to test this way)

**Comment by sploiselle** [comment]
@romainr yep, at `materialize/materialized:unstable-c27eafaccc8654ac75762185c0b2e3f2c0361197`

File: src/sql/src/plan/func.rs [hunk 1]
```diff
@@ -1305,6 +1308,70 @@ lazy_static! {
                     Ok(e.call_unary(UnaryFunc::FloorDecimal(s)))
                 })
             },
+            "format_type" => Scalar {
+                params!(Int64, Int64) => Operation::binary(|ecx, oid, typmod| {
+                    let unknown_type = || {
+                        Ok(ScalarExpr::literal(Datum::String("???"), ScalarType::String))
+                    };
+
+                    let oid = match oid.into_literal_int64() {
```
Comment (benesch) [inline src/sql/src/plan/func.rs:1317]: So I have some bad news, which is that using `into_literal_int64()` here is probably a no-go. :( 

Specifically, you won't be able to write a query like

```sql
SELECT format_type(oid, -1) FROM some_data_source
```

where the argument is a reference to an int4 column rather than a literal OID. 

To make this work, it'll need to look more like `pg_table_is_visible`, where it gets planned as a SQL fragment subquery that pulls the name out of `mz_catalog.mz_types`, I think.

To make the typmod stuff work, I think the way to go is to add an internal function binary `mz_internal.mz_render_typemod` or somesuch that plans as `BinaryFunc::MzRenderTypemod` and returns something like "(4, 5)" in the case that the OID is the decimal OID. 

Roughly I think the sql_op would be something like this?

```sql
coalesce((SELECT concat(name, mz_internal.mz_render_typemod($1, $2)) FROM mz_catalog.mz_types WHERE oid = $1), '???')
```

Comment (sploiselle) [reply src/sql/src/plan/func.rs]: ty for the pointers! fixed this and it's now mostly the same as PG (they use the longform array names, ours are prefixed with an underscore)

**Comment by sploiselle** [comment]
@romainr A new fully-PG compatible version will be available at `materialize/materialized:unstable-9f8c40fb8b77519bb2722ad00d1f1888486b5d05`. Let me know how it goes!

**Review by benesch — APPROVED** [review]
This came out super clean! Sorry about the wrench earlier! Let's ship this! 🎉
