### PR TITLE
sql: Fix min(int16)

### LINKED ISSUE #17978: [SQLsmith] thread 'coordinator' panicked at 'Datum::unwrap_int32 called on Int16(0)', src/expr/src/relation/func.rs:265:20
### What version of Materialize are you using?

v0.46.0-dev (659bcc95fb94f8d18cd42c6fabbb81bba90d0b02)

### How did you install Materialize?

Built from source

### What is the issue?

```
materialize=> select min("relchecks") from pg_class;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

### Relevant log output

```source
thread 'coordinator' panicked at 'Datum::unwrap_int32 called on Int16(0)', /home/deen/git/materialize3/src/expr/src/relation/func.rs:265:20
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/panicking.rs:64:14
   2: mz_repr::scalar::Datum::unwrap_int32
             at ./src/repr/src/scalar.rs:446:18
   3: mz_expr::relation::func::min_int32::{{closure}}
             at ./src/expr/src/relation/func.rs:265:18
   4: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/ops/function.rs:310:13
   5: core::option::Option<T>::map
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/option.rs:972:29
   6: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/iter/adapters/map.rs:103:9
   7: core::iter::traits::iterator::Iterator::reduce
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/iter/traits/iterator.rs:2473:21
   8: core::iter::traits::iterator::Iterator::min_by
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/iter/traits/iterator.rs:3152:9
   9: core::iter::traits::iterator::Iterator::min
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/iter/traits/iterator.rs:3032:9
  10: mz_expr::relation::func::min_int32
             at ./src/expr/src/relation/func.rs:266:10
  11: mz_expr::relation::func::AggregateFunc::eval
             at ./src/expr/src/relation/func.rs:1530:40
  12: mz_transform::literal_lifting::LiteralLifting::action::{{closure}}::{{closure}}
             at ./src/transform/src/literal_lifting.rs:542:39
  13: mz_transform::literal_lifting::LiteralLifting::action::{{closure}}
             at ./src/transform/src/literal_lifting.rs:558:37
  14: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  15: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  16: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  17: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  18: mz_transform::literal_lifting::LiteralLifting::action
             at ./src/transform/src/literal_lifting.rs:137:14
  19: mz_transform::literal_lifting::LiteralLifting::action::{{closure}}
             at ./src/transform/src/literal_lifting.rs:256:36
  20: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  21: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  22: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  23: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  24: mz_transform::literal_lifting::LiteralLifting::action
             at ./src/transform/src/literal_lifting.rs:137:14
  25: mz_transform::literal_lifting::LiteralLifting::action::{{closure}}
             at ./src/transform/src/literal_lifting.rs:262:34
  26: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  27: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  28: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  29: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  30: mz_transform::literal_lifting::LiteralLifting::action
             at ./src/transform/src/literal_lifting.rs:137:14
  31: mz_transform::literal_lifting::LiteralLifting::action::{{closure}}
             at ./src/transform/src/literal_lifting.rs:262:34
  32: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  33: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  34: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  35: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  36: mz_transform::literal_lifting::LiteralLifting::action
             at ./src/transform/src/literal_lifting.rs:137:14
  37: mz_transform::literal_lifting::LiteralLifting::action::{{closure}}
             at ./src/transform/src/literal_lifting.rs:262:34
  38: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  39: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  40: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  41: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  42: mz_transform::literal_lifting::LiteralLifting::action
             at ./src/transform/src/literal_lifting.rs:137:14
  43: mz_transform::literal_lifting::LiteralLifting::action::{{closure}}
             at ./src/transform/src/literal_lifting.rs:262:34
  44: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  45: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  46: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  47: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  48: mz_transform::literal_lifting::LiteralLifting::action
             at ./src/transform/src/literal_lifting.rs:137:14
  49: mz_transform::literal_lifting::LiteralLifting::action::{{closure}}
             at ./src/transform/src/literal_lifting.rs:262:34
  50: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  51: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  52: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  53: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  54: mz_transform::literal_lifting::LiteralLifting::action
             at ./src/transform/src/literal_lifting.rs:137:14
  55: <mz_transform::literal_lifting::LiteralLifting as mz_transform::Transform>::transform
             at ./src/transform/src/literal_lifting.rs:67:24
  56: <mz_transform::Fixpoint as mz_transform::Transform>::transform::{{closure}}
             at ./src/transform/src/lib.rs:270:29
  57: tracing::span::Span::in_scope
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/span.rs:1102:9
  58: <mz_transform::Fixpoint as mz_transform::Transform>::transform
             at ./src/transform/src/lib.rs:267:17
  59: mz_transform::Optimizer::transform
             at ./src/transform/src/lib.rs:592:17
  60: mz_transform::dataflow::optimize_dataflow_relations
             at ./src/transform/src/dataflow.rs:195:9
  61: mz_transform::dataflow::optimize_dataflow
             at ./src/transform/src/dataflow.rs:44:5
  62: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::plan_peek
             at ./src/adapter/src/coord/sequencer.rs:2584:9
  63: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_peek_finish::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:2380:29
  64: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_peek_finish::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:2362:5
  65: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_peek_begin::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:2266:21
  66: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_peek_begin::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:2189:5
  67: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_plan::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:315:60
  68: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_plan::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:119:5
  69: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute_inner::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:504:78
  70: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute_inner::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:307:5
  71: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:304:61
  72: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:263:5
  73: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  74: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_command::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:68:21
  75: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_command::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:249:33
  76: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_command::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:246:5
  77: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::handle_message::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:44:63
  78: mz_adapter::coord::Coordinator::serve::{{closure}}
             at ./src/adapter/src/coord.rs:1298:37
  79: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:63
  80: tokio::runtime::coop::with_budget
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:102:5
  81: tokio::runtime::coop::budget
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:68:5
  82: tokio::runtime::park::CachedParkThread::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:31
  83: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/context.rs:315:13
  84: tokio::runtime::handle::Handle::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/handle.rs:264:9
  85: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./src/adapter/src/coord.rs:1477:17
```

ci-regexp: Datum::unwrap_int32 called on Int16\(0\)

### PR DESCRIPTION
**Pull request by andrewrodriguez-m**
Fixes #17978.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

File: src/sql/src/func.rs [hunk 1]
```diff
@@ -2489,7 +2489,7 @@ pub static PG_CATALOG_BUILTINS: Lazy<BTreeMap<&'static str, Func>> = Lazy::new(|
         },
         "min" => Aggregate {
             params!(Bool) => AggregateFunc::MinBool => Bool, oid::FUNC_MIN_BOOL_OID;
-            params!(Int16) => AggregateFunc::MinInt32 => Int16, 2133;
```
Comment (mjibson) [inline src/sql/src/func.rs:2492]: yikes! I've thought for a long time we need a test that executes all functions with some default value for their arguments, to make sure these kinds of things can't happen.

**Review by mjibson — APPROVED** [review]
