### PR TITLE
coord,pgwire: plumb down implicit transaction failures to pgwire

### LINKED ISSUE #7926: peristence: INSERTs allowed to proceed even though they can not be persisted
### What version of Materialize are you using?

```
v0.9.1-dev (ed424518a)
```

### What was the issue?

One is allowed to issue `INSERT` statements against Mz and they will be acknowledged even if the data can not be persisted. This goes against the concept that the database client should receive an acknowledgement only after the data has been persisted to durable storage.

If the data could not be persisted, an error should have been returned to the DML statement or , at the very least, at transaction commit  (which for autocommit statements amounts to the same thing from the viewpoint of the user)

### Is the issue reproducible? If so, please provide reproduction instructions.

1. Start Materialize
2. Create a table
2. remove the `persist` directory
3. Insert some data. Observe that even though the log begins to report:
```
2021-08-19T11:09:30.193597Z  WARN persist::indexed::runtime: error running step: String("failed to commit metadata after appending to future: No such file or directory (os error 2)")    
2021-08-19T11:09:30.193645Z ERROR coord::coord: failed to seal persisted stream to ts 1629371370194: failed to commit metadata after appending to future: No such file or directory (os error 2)    
```

the insert succeeded when it should not have.

### Please attach any applicable log files.
```
materialized v0.9.1-dev (ed424518a) listening on 0.0.0.0:6875...
2021-08-19T11:09:24.675975Z  INFO coord::catalog: create table materialize.public.t1 (u1)    
2021-08-19T11:09:24.676023Z  INFO coord::catalog: create index materialize.public.t1_primary_idx (u2)    
2021-08-19T11:09:30.193597Z  WARN persist::indexed::runtime: error running step: String("failed to commit metadata after appending to future: No such file or directory (os error 2)")    
2021-08-19T11:09:30.193645Z ERROR coord::coord: failed to seal persisted stream to ts 1629371370194: failed to commit metadata after appending to future: No such file or directory (os error 2)    
2021-08-19T11:09:31.193900Z  WARN persist::indexed::runtime: error running step: String("failed to commit metadata after appending to future: No such file or directory (os error 2)")    
2021-08-19T11:09:31.193924Z ERROR coord::coord: failed to seal persisted stream to ts 1629371371194: failed to commit metadata after appending to future: No such file or directory (os error 2)    
2021-08-19T11:09:32.194194Z  WARN persist::indexed::runtime: error running step: String("failed to commit metadata after appending to future: No such file or directory (os error 2)")    
2021-08-19T11:09:32.194214Z ERROR coord::coord: failed to seal persisted stream to ts 1629371372195: failed to commit metadata after appending to future: No such file or directory (os error 2)    
2021-08-19T11:09:33.193711Z  WARN persist::indexed::runtime: error running step: String("failed to commit metadata after appending to future: No such file or directory (os error 2)")    
2021-08-19T11:09:33.193728Z ERROR coord::coord: failed to seal persisted stream to ts 1629371373194: failed to commit metadata after appending to future: No such file or directory (os error 2)    
2021-08-19T11:09:33.993384Z  WARN persist::indexed::runtime: error running step: String("failed to append to future: No such file or directory (os error 2)")    
2021-08-19T11:09:33.993405Z ERROR coord::coord: failed to seal persisted stream to ts 1629371373994: failed to append to future: No such file or directory (os error 2)    
2021-08-19T11:09:34.193877Z  WARN persist::indexed::runtime: error running step: String("failed to commit metadata after appending to future: No such file or directory (os error 2)")    
2021-08-19T11:09:34.193884Z ERROR coord::coord: failed to seal persisted stream to ts 1629371374194: failed to commit metadata after appending to future: No such file or directory (os error 2)    
2021-08-19T11:09:35.194301Z  WARN persist::indexed::runtime: error running step: String("failed to commit metadata after appending to future: No such file or directory (os error 2)")    
2021-08-19T11:09:35.194323Z ERROR coord::coord: failed to seal persisted stream to ts 1629371375195: failed to commit metadata after appending to future: No such file or directory (os error 2)    
2021-08-19T11:09:36.193767Z  WARN persist::indexed::runtime: error running step: String("failed to commit metadata after appending to future: No such file or directory (os error 2)")    
2021-08-19T11:09:36.193775Z ERROR coord::coord: failed to seal persisted stream to ts 1629371376194: failed to commit metadata after appending to future: No such file or directory (os error 2)    
2021-08-19T11:09:37.194148Z  WARN persist::indexed::runtime: error running step: String("failed to commit metadata after appending to future: No such file or directory (os error 2)")    
2021-08-19T11:09:37.194167Z ERROR coord::coord: failed to seal persisted stream to ts 1629371377195: failed to commit metadata after appending to future: No such file or directory (os error 2)    
2021-08-19T11:09:38.193573Z ERROR coord::coord: failed to seal persisted stream to ts 1629371378194: failed to commit metadata after appending to future: No such file or directory (os error 2)    
2021-08-19T11:09:38.193568Z  WARN persist::indexed::runtime: error running step: String("failed to commit metadata after appending to future: No such file or directory (os error 2)")    
```

### PR DESCRIPTION
**Pull request by mjibson**
Previously we weren't sure where to send an error during an implicit
commit (at the end of a Query or Sync message). After direct comparison
with postgres, we have a clearer picture. I'm not sure how to exactly
induce this in postgres (have an INSERT succeed but then the implicit
transaction commit fail), but we can test a few nearby scenarios.

The difference we needed to observe is that for implicit transactions,
we don't care about the ExecuteResponse or tag at all, just that
an error happened. This greatly simplifies the error paths in
sequence_end_transaction and also means we don't need to change the tag
of the action should a failure occur.

Fixes #7926

### CODE REVIEW

**Comment by sploiselle** [comment]
Will look at this on Monday

File: src/coord/src/coord.rs [hunk 1]
```diff
@@ -2206,31 +2206,32 @@ impl Coordinator {
...
         match rx {
             Ok(Some(rx)) => {
                 tokio::spawn(async move {
-                    let tag = match rx.await {
-                        Ok(_) => action.tag(),
-                        // TODO: Try to return this error somehow.
-                        Err(_err) => EndTransactionAction::Rollback.tag(),
-                    };
-                    let result = Ok(ExecuteResponse::TransactionExited { tag, was_implicit });
+                    let result = rx.await.map(|_| response);
```
Comment (ruchirK) [inline src/coord/src/coord.rs:2229]: I'm not really clear on why we are awaiting this channel given that we replace whatever we get with our own pre-determined response. I think a comment would help here?

**Review by ruchirK — APPROVED** [review]
The change mostly looks good to me! I would need to spend a lot more time reading the adjacent coordinator and pgwire code to be able to fully convince myself that its all correct (and even then am not sure if I would be able to because i don't know pgwire that well)

is that needed here / how else can I be helpful? do you want me to rerun the failing insert test?

**Review by sploiselle — APPROVED** [review]
LGTM in the sense that this seems like a reasonable approach, but I did not invest the requisite time to fully understand the coord's transaction API.

File: src/coord/src/coord.rs (hunk 1 above)
Comment (mjibson) [reply src/coord/src/coord.rs:2312]: The output is a `Result<(), CoordError>`, so the `.map` only remaps a `Ok(())` result to `response`, but passes through any Err. Notice the lack of `?`, we aren't ignoring any errors here. Added a comment describing this a bit.

**Comment by mjibson** [comment]
Thanks for the reviews, even though this isn't your normal stuff. We don't have a lot of knowledge about how this part of coord works beyond mostly me and Nikhil, so probably worth a little spreading arorund.
