### PR TITLE
expr: fix underflow in date_trunc week

### LINKED ISSUE #3651: Crashes when calling date_trunc with certain values
### What version of Materialize are you using?

```
$ materialized -v
materialized v0.3.1 (9e4dce4bee6169e8391d9d7a6f5382b998a00625)
```

### How did you install Materialize?

* [ ] Docker image
* [x] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [ ] Built from source

### What was the issue?

`date_trunc` crashes materialized for some dates.

### Is the issue reproducible? If so, please provide reproduction instructions.

```
materialized --w=1 &
psql -h localhost -p 6875 materialize -c "select date_trunc('week', '2020-07-05 19:58:52+00'::timestamptz)"
```

### Please attach any applicable log files.

[materialized.log](https://github.com/MaterializeInc/materialize/files/4941277/materialized.log)

### PR DESCRIPTION
**Pull request by ruchirK**
Closes #3651

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/3656)

### CODE REVIEW

File: src/expr/src/scalar/func.rs [hunk 1]
```diff
@@ -1333,11 +1334,10 @@ pub trait TimestampLike: chrono::Datelike + chrono::Timelike + for<'a> Into<Datu
...
 
     fn truncate_week(&self) -> Self {
-        let num_days_from_monday = self.date().weekday().num_days_from_monday();
-        Self::new(
-            NaiveDate::from_ymd(self.year(), self.month(), self.day() - num_days_from_monday),
-            NaiveTime::from_hms(0, 0, 0),
-        )
+        let num_days_from_monday = self.date().weekday().num_days_from_monday() as i64;
+        let new_date = NaiveDate::from_ymd(self.year(), self.month(), self.day())
+            .add(Duration::days(-num_days_from_monday));
```
Comment (benesch) [inline src/expr/src/scalar/func.rs:1339]: We should probably be using `checked_sub_signed` here and returning an overflow error. But feel free to just punt to a follow-on issue; there are all sorts of similar errors lurking and we might as well try to solve them all at once rather than one-by-one.

File: src/expr/src/scalar/func.rs [hunk 2]
```diff
@@ -10,9 +10,10 @@
 use std::cmp::{self, Ordering};
 use std::convert::{TryFrom, TryInto};
 use std::fmt;
+use std::ops::Add;
```
Comment (benesch) [inline src/expr/src/scalar/func.rs:13]: This is a little odd. It's a bit more idiomatic to just use the `+` operator rather than importing the underlying trait.

Comment (ruchirK) [reply src/expr/src/scalar/func.rs:13]: ok yeah I was wondering about this thanks!
