### PR TITLE
compute: frontier logging for index imports

### LINKED ISSUE #14102: Input -> output latency introspection relations only show `persist` source dependencies, failing to capture index dependencies
### What version of Materialize are you using?

v0.26.1-dev (8dbe5bd60)

### How did you install Materialize?

Built from source

### What is the issue?

Recently, introspection information was deemed necessary to observe the input &rarr; output latency for dataflow updates (see #13885 and #13887). The following catalog relations were added:

- `mz_worker_materialization_delays`, capturing a per-worker histogram of delays in frontier advancements for a dataflow backing an index or materialized view after a frontier advancement from a `persist` storage source instantiation is observed in the context of that dataflow. 
- `mz_worker_materialization_source_frontiers`, capturing the currently known frontier, per worker, of a `persist` storage source instantiation in the context of a dataflow backing an index or materialized view. 
- `mz_materialization_source_frontiers`, aggregating the data in the view above across all workers.

Even though the new catalog relations were scoped to try to characterize the differences and delays in frontiers between dataflows backing indexes and materialized views and persist storage sources, they fail to allow for a complete characterization of the desired input &rarr; output latency for dataflow updates. This is because not only may a dataflow depend on frontier advancements from `persist` sources, but also the frontier advancements of other indexes that it depends on. This complete dependency structure is captured in the catalog relation `mz_materialization_dependencies`, but it is not reflected in the three catalog relations named above. 

To observe this effect, the following commands can be executed:

```
materialize=> CREATE TABLE t1 (a int);
CREATE TABLE
materialize=> CREATE TABLE t2 (a int);
CREATE TABLE
[...]
materialize=> CREATE INDEX i2 ON t2 (a);
CREATE INDEX
materialize=> CREATE MATERIALIZED VIEW mv AS SELECT * FROM t1 JOIN t2 USING (a);
CREATE MATERIALIZED VIEW
materialize=> SELECT global_id, name FROM mz_materializations mats
              JOIN (SELECT id AS global_id, name 
                    FROM mz_indexes 
                    UNION ALL
                    SELECT id AS global_id, name
                    FROM mz_materialized_views)
              USING (global_id);
 global_id | name 
-----------+------
 u4        | i2
 u5        | mv
(2 rows)

materialize=> SELECT id, name FROM mz_tables WHERE id LIKE 'u%';
 id | name 
----+------
 u1 | t1
 u2 | t2
(2 rows)

materialize=> SELECT * FROM mz_materialization_dependencies;
 dataflow | source | worker 
----------+--------+--------
 u4       | u2     |      0
 u5       | u1     |      0
 u5       | u4     |      0
(3 rows)

materialize=> SELECT * FROM mz_materialization_frontiers
              JOIN mz_materialization_source_frontiers
              USING (global_id);
 global_id |     time      | source |     time      
-----------+---------------+--------+---------------
 u4        | 1659697459884 | u2     | 1659697459884
 u5        | 1659697459884 | u1     | 1659697459884
(2 rows)

materialize=> SELECT * FROM mz_worker_materialization_delays;
 global_id | source | worker |  delay_ns  | count 
-----------+--------+--------+------------+-------
 u4        | u2     |      0 |      65536 |   385
 u4        | u2     |      0 |     131072 |   281
 u4        | u2     |      0 |     262144 |    16
 u4        | u2     |      0 |     524288 |     1
 u4        | u2     |      0 |    1048576 |     1
 u4        | u2     |      0 |    2097152 |     1
 u4        | u2     |      0 |      16384 |     9
 u4        | u2     |      0 |      32768 |    59
 u5        | u1     |      0 |   16777216 |    46
 u5        | u1     |      0 |   33554432 |    26
 u5        | u1     |      0 |   67108864 |    41
 u5        | u1     |      0 |  134217728 |    75
 u5        | u1     |      0 |  268435456 |    99
 u5        | u1     |      0 |  536870912 |    86
 u5        | u1     |      0 | 1073741824 |     3
 u5        | u1     |      0 |    1048576 |    24
 u5        | u1     |      0 |    2097152 |   163
 u5        | u1     |      0 |    4194304 |   124
 u5        | u1     |      0 |    8388608 |    54
(19 rows)
```

Note that above, `u5` depends on both `u1` and `u4`. However, since `u4` is an index and not served from `persist`, then this dependency becomes invisible to the catalog relations exposing input &rarr; output frontier lags and delays.

This issue is thus a request that we capture these additional dependencies in the three aforementioned catalog relations. 

Implementation notes: To keep symmetry with how `persist` sources are introspected at the COMPUTE layer, we should consider capturing via COMPUTE logging the frontier advancements of indexes imported into a dataflow, as opposed to capturing the frontiers at index exports. The latter might be achieved with an `inspect_container` operator, similarly to what was implemented for `persist` sources. We take this approach with storage sources as there may be a difference between the frontier as known at the STORAGE layer and the frontier as perceived by different dataflows at the COMPUTE layer (refer also to issue #13489). 

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by teskje**
This PR adds frontiers of index imports to `mz_internal.mz_worker_compute_import_frontiers`.

The approach taken is the same as for source imports, by connecting an `inspect_container` dataflow operator to the output stream of each imported index.

### Motivation

  * This PR fixes a recognized bug.

Fixes #14102.

### Tips for reviewer

Look at the commits separately!

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - Add frontiers of index imports to `mz_internal.mz_worker_compute_import_frontiers`.

### CODE REVIEW

**Review by jkosh44 — APPROVED** [review]
Surfaces code LGTM

**Review by umanwizard — APPROVED** [review]

File: src/compute/src/logging/compute.rs [hunk 1]
```diff
@@ -54,9 +54,18 @@ pub enum ComputeEvent {
...
+        id: GlobalId,
+        time: Timestamp,
+        diff: i64,
+    },
+    /// Available frontier information for dataflow imports.
+    ImportFrontier {
+        import_id: GlobalId,
+        export_id: GlobalId,
+        time: Timestamp,
+        diff: i64,
```
Comment (vmarcos) [inline src/compute/src/logging/compute.rs:71]: Note that the change here to `i64` will likely increase the size of the enum, as noted in https://github.com/MaterializeInc/materialize/pull/14031#discussion_r937486429. I think that the impact here is likely to not be very significant, but just wanted to call it out. This was the reason it was an `i8` previously.

**Review by vmarcos — APPROVED** [review]
LGTM! I have only one minor comment on the first commit, but not a blocker for merging.

File: src/compute/src/logging/compute.rs (hunk 1 above)
Comment (teskje) [reply src/compute/src/logging/compute.rs:71]: Ah, good point! I thought that wouldn't matter since an `i8` would just be padded to 8 bytes anyway, but I did not consider the enum tag. I'll make the diffs `i8`s.
