### PR TITLE
persist: fix correctness bug in snapshot when as_of >= upper

### LINKED ISSUE #12131: persist: snapshot incorrect when as_of >= shard upper
Snapshot is intended to block when given an as_of that is not yet ready, but instead it immediately returns the current data. This is a correctness bug. A similar bug probably exists for persist Listeners

Found during code review of #11911

### PR DESCRIPTION
**Pull request by danhhz**
Snapshot was meant to block until the requested data is ready, but
before this fix, if passed an as_of that was >= upper, it would
immediately return whatever it currently had. This is a correctness bug.

While in here, addressed a related TODO about only fetching state if we
can't immediately serve the snapshot.

When I first saw this, I thought a similar issue might be present in
Listen, but I added test coverage and Listen seems to be okay.

Fixes #12131
Touches #11977

### Motivation

  * This PR fixes a recognized bug.

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - N/A

### CODE REVIEW

**Comment by danhhz** [comment]
To keep @cjubb39 unblocked, I'm going to merge this on green, but @aljoscha please do a post-merge review when you're back. I'm more than happy to address any comments in a followup PR.

File: src/persist-client/src/impl/state.rs [hunk 1]
```diff
@@ -273,13 +273,16 @@ where
...
-                "snapshot with as_of {:?} cannot be served by shard with since: {:?}",
-                as_of,
-                self.collections.since
-            )));
+            return Err(Since(self.collections.since.clone()));
+        }
+        let upper = self.collections.upper();
+        if PartialOrder::less_equal(&upper, as_of) {
+            return Ok(Err(Upper(upper)));
         }
```
Comment (cjubb39) [inline src/persist-client/src/impl/state.rs:286]: It seems like this will prevent any response if `since == upper` -- which as far as I can tell is the initial state for a new collection -- where both equal `Timestamp::minimum()`

I imagine it's more ergonomic to handle that case internally rather than each caller doing a check but what do you think?

Comment (danhhz) [reply src/persist-client/src/impl/state.rs:286]: as far as I understand this behavior is correct (though I agree that it's quite unintuitive). `as_of` is inclusive, while `upper` is exclusive. concretely, this indeed means that a newly initialized shard with upper of `antichain[T::minimum()]` cannot be read as_of `antichain[T::minimum()]`. fwiw, none of this is coming from me. this is what is prescribed by the formalism

in the maelstrom PR, I "initialize" the shard when a process first starts by attempting a cas from `antichain[T::minimum()]` to `antichain[T::minimum()+1]`. this either sets it up the shard to an initial upper of `antichain[T::minimum()+1]` allowing reads as_of `antichain[T::minimum()]`, or if the shard has already been used, returns the upper frontier information. either way, we have an upper now. https://github.com/MaterializeInc/materialize/pull/12108/files#diff-bfde6fe4d24d0f4f78767d45c96169d046ebd064519ab2bc736719ba88825264R125-R144

File: src/persist-client/src/impl/state.rs [hunk 2]
```diff
@@ -313,6 +316,12 @@ where
     }
 }
 
+#[derive(Debug)]
```
Comment (aljoscha) [inline src/persist-client/src/impl/state.rs:319]: 🙌 much safer than just throwing around `Antichains` in `Results`.

**Review by aljoscha — COMMENTED** [review]
Looks good to me!

I'm not super hot on different, hard-coded retry intervals for test/prod but it seems okay for now. Maybe we could get around that by making the retry strategy configurable (on client creation)?
