### PR TITLE
Validate inputs when creating Kafka exactly-once Sinks

### LINKED ISSUE #6121: EOS Kafka sinks should fail at create time if their inputs are nondeterministic
Today we allow creating EOS kafka sinks from kinesis and table sources. Neither of those sources are deterministically replayable, so it doesn't make sense for us to build a sink with eos semantics off of them.

At CREATE SINK time we should validate that EOS sinks only contain kafka or file sources as inputs.

Ideally this check would live somewhere inline with the CREATE SINK statement, similar to our current auth validation - that way we can fail fast and give the user a nice error. That means logic should live somewhere within the coord and not in sources/kafka.rs.

### PR DESCRIPTION
**Pull request by aljoscha**
I'm not married to where the check is performed and to the method being on `SourceConnector`. This seemed sensible to me but I'm open to suggestions.

Also, right now we only allow Kafka + BYO consistency as valid input for Kafka EO Sinks. And the test coverage is not exhaustive, I didn't add File sources, Kinesis, and some others.

This closes #6121.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/6168)

### CODE REVIEW

**Comment by elindsey** [comment]
I'm deferring review on this one - I don't know enough about the catalog to provide much help. The new test coverage looks great though 🙂

File: src/sql/src/plan/statement/ddl.rs [hunk 1]
```diff
@@ -1348,6 +1365,23 @@ pub fn plan_create_sink(
     })
 }
 
+/// Returns only those `CatalogItem`s that don't have any other user
+/// dependencies. Those are the root dependencies.
```
Comment (ruchirK) [inline src/sql/src/plan/statement/ddl.rs:1369]: so what happens if we make a view built on top of system tables / system logs?

**Review by ruchirK — COMMENTED** [review]
did a quick read and this approach seems solid to me. will need a bit more time to look at the catalog / planner stuff to convince myself that everything makes sense

File: src/sql/src/plan/statement/ddl.rs [hunk 2]
```diff
@@ -1110,6 +1111,18 @@ fn kafka_sink_builder(
         bail!("exactly-once requires a consistency topic");
     }
 
+    if include_consistency {
+        for item in root_dependencies.iter() {
+            if item.item_type() == CatalogItemType::Source
```
[the remark this answers is not in the document]
Comment (ruchirK) [reply src/sql/src/plan/statement/ddl.rs:1116]: oh you know what I think you actually want

```
if !item.item_type() == CatalogItemSource || !item.source_connector()?.yields_stable_input() { bail!( ... ) }
```

assuming short circuiting evaluation of the predicate i think this works fine

File: src/sql/src/plan/statement/ddl.rs (hunk 1 above)
Comment (ruchirK) [reply src/sql/src/plan/statement/ddl.rs:1369]: ah i think i see now -- we bail iff theres a dep thats not a source, or is a source but doesnt stably return messages

File: src/sql/src/plan/statement/ddl.rs [hunk 3]
```diff
@@ -1110,6 +1111,18 @@ fn kafka_sink_builder(
...
+                && item.source_connector()?.yields_stable_input()
+            {
+                // it's all good
+            } else {
+                bail!("all transitive inputs of a consistent Kafka Sink must yield stable input, {} does not", item.name());
```
Comment (philip-stoev) [inline src/sql/src/plan/statement/ddl.rs:1121]: Is there a way to word this in a simple way,  with words simpler than "transitive". Also, we do not seem to be defining "stable input" in our documentation.

Users, e.g. those coming from a DBA background would find all of this difficult to understand.

Comment (aljoscha) [reply src/sql/src/plan/statement/ddl.rs:1121]: I think this line is the hardest part in the PR... 🙈 

Maybe `all inputs of a consistent Kafka Sink must be replayable, {} is not`

The problem is the we don't yet have a term for this property of"replayable", or "stable", or "consistent" that we currently need for consistent sinks. @ruchirK any Ideas, because you're currently working on this from the input side?

File: src/sql/src/plan/statement/ddl.rs [hunk 4]
```diff
@@ -1348,6 +1365,23 @@ pub fn plan_create_sink(
     })
 }
 
+/// Returns only those `CatalogItem`s that don't have any other user
+/// dependencies. Those are the root dependencies.
+fn get_root_user_dependencies<'a>(
```
Comment (sploiselle) [inline src/sql/src/plan/statement/ddl.rs:1370]: This function name is a little odd because it could be read as "get [root user] dependencies", i.e. get the root user's dependencies, as opposed to root dependencies in userland. I was very confused why sinks needed "root user" dependencies at first.

Maybe just `get_root_dependencies`?

**Review by sploiselle — APPROVED** [review]
LGTM modulo outstanding comments

File: src/sql/src/plan/statement/ddl.rs (hunk 4 above)
Comment (aljoscha) [reply src/sql/src/plan/statement/ddl.rs:1370]: Will do!

File: src/sql/src/plan/statement/ddl.rs (hunk 3 above)
Comment (aljoscha) [reply src/sql/src/plan/statement/ddl.rs]: I pushed changes that split the error message and change the wording.

File: src/sql/src/plan/statement/ddl.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (aljoscha) [reply src/sql/src/plan/statement/ddl.rs:1116]: I changed the check and now print two different error messages.

File: test/testdrive/kafka-exactly-once-sink.td [hunk 5]
```diff
@@ -0,0 +1,163 @@
...
+  WITH (exactly_once=true, consistency=true)
+  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
+
+! CREATE SINK output5 FROM input_kafka_no_byo_mview
+  INTO KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'output-view-${testdrive.seed}'
+  WITH (exactly_once=true, consistency=true)
+  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
+all input sources of a consistent Kafka sink must be replayable, materialize.public.input_kafka_no_byo is not
+
+> CREATE SINK output5_view FROM input_kafka_no_byo_mview_view
```
Comment (philip-stoev) [inline test/testdrive/kafka-exactly-once-sink.td:112]: i believe the check should be recursive. Creating a view over a non-replayable source should not allow you to create a consistent sink.

File: test/testdrive/kafka-exactly-once-sink.td [hunk 6]
```diff
@@ -0,0 +1,163 @@
...
+  INTO KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'output-view-${testdrive.seed}'
+  WITH (exactly_once=true, consistency=true)
+  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
+all inputs of a consistent Kafka sink must be sources, materialize.public.input_table is not
+
+! CREATE SINK output7 FROM input_values_view
+  INTO KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'output-view-${testdrive.seed}'
+  WITH (exactly_once=true, consistency=true)
+  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
+all inputs of a consistent Kafka sink must be sources, materialize.public.input_values_view is not
```
Comment (philip-stoev) [inline test/testdrive/kafka-exactly-once-sink.td:127]: This should have succeeded I think. Views created as ```CREATE VIEW ... AS VALUES (...),(...)``` can not be modified after the fact.

**Review by philip-stoev — APPROVED** [review]
Thank you for the tests. The only major issue I see is that the check does not seem to be recursive, that is, creating a view over a disallowed input seems to make it allowed.

**Review by sploiselle — APPROVED** [review]
tysm for making those changes. LGTM mod Phillip's comments

File: src/sql/src/plan/statement/ddl.rs [hunk 7]
```diff
@@ -1110,6 +1111,24 @@ fn kafka_sink_builder(
         bail!("exactly-once requires a consistency topic");
     }
 
+    if include_consistency {
+        for item in root_dependencies.iter() {
+            if item.item_type() == CatalogItemType::Source
+                && !item.source_connector()?.yields_stable_input()
+            {
+                bail!(
+                    "all input sources of a consistent Kafka sink must be replayable, {} is not",
```
Comment (ruchirK) [inline src/sql/src/plan/statement/ddl.rs:1120]: why don't we just say

"all input sources to a consistent Kafka sink must be Kafka sources"

I know this isn't exactly true right now but it will be true before users can use it?

**Review by ruchirK — APPROVED** [review]
looks good mod philips stuff (I think if you want its fine to not worry about the static view for now because falsely rejecting is worse than falsely accepting)

File: src/sql/src/plan/statement/ddl.rs (hunk 7 above)
Comment (philip-stoev) [reply src/sql/src/plan/statement/ddl.rs:1120]: I suspect out in the field other exotic sources may need to be brought in to get some query/sink to run by any means necessary:
- a VALUES view
- a File source that has been declared using some future option to be forver present and immutable.

File: test/testdrive/kafka-exactly-once-sink.td (hunk 5 above)
Comment (aljoscha) [reply test/testdrive/kafka-exactly-once-sink.td]: That's a very good catch! I was (naively) assuming that `CatalogItem.uses()` returns all transitive dependencies. I now changed `get_root_dependencies()` to properly recurse into transitive dependencies. PTAL.

File: src/sql/src/plan/statement/ddl.rs (hunk 3 above)
Comment (philip-stoev) [reply src/sql/src/plan/statement/ddl.rs]: Thank you!

File: test/testdrive/kafka-exactly-once-sink.td (hunk 5 above)
Comment (philip-stoev) [reply test/testdrive/kafka-exactly-once-sink.td]: The test now shows that the correct error is returned. Thanks.

**Review by philip-stoev — APPROVED** [review]
Thank you. The transitive issue has been fixed. I do not have a strong feeling about handling the VALUES view so please proceed as you see fit.

**Review by ruchirK — APPROVED** [review]
