### PR TITLE
coord: add only indexed views/sources to timedomains

### LINKED ISSUE #6651: sql: allow SELECTs in transactions with non-materialized sources in the timedomain

### LINKED ISSUE #7167: Cannot query Materialize with psycopg2
### What version of Materialize are you using?

 v0.8.0 (b2fe225f1)

### How did you install Materialize?

curl -L https://binaries.materialize.com/materialized-v0.8.0-x86_64-apple-darwin.tar.gz

### What was the issue?

Psycopg2 returns `psycopg2.errors.InternalError_
psycopg2.errors.InternalError_: Unable to automatically determine a timestamp for your query; this can happen if your query depends on non-materialized sources.`.  Strangely, it works fine over psql.  I've also heard an anecdotal report that this is also happening to Metabase, which leads me to believe it's not specific to psycopg2.  I'm pretty sure other folks have successfully connected via psycopg2 and this works fine for me in 0.7.2, so i suspect this is a regression in 0.7.3 or 0.8

### Is the issue reproducible? If so, please provide reproduction instructions.

psql:
```
materialize=> create table foo(bar int, baz int);
CREATE TABLE
materialize=> insert into foo values(1, 2), (3, 4);
INSERT 0 2
materialize=> select * from foo;
 bar | baz 
-----+-----
   1 |   2
   3 |   4
(2 rows)
```

psycopg2 (over Flask):
```
from flask import Flask, jsonify
import psycopg2
import os

app = Flask(__name__)


try:
    con = psycopg2.connect(
        "host=localhost port=6875 dbname=materialize user=materialize"
        )


    @app.route('/')
    def test_page():
        cur = con.cursor()

        cur.execute('SELECT * FROM foo')
        rows = cur.fetchall()
        print(rows)

        return jsonify(rows)


except Exception as inst:
    print(type(inst))
    print(inst)
except:
    print('Error')
```

### LINKED ISSUE #7193: BI Tool Integration (Metabase, Superset): Regression in v0.8.0
### What version of Materialize are you using?

```
v0.8.0
```

### How did you install Materialize?

* [x] Docker image

### What was the issue?

Running a `SELECT` statement on a materialized view (or source) within Metabase errors out with:

> Unable to automatically determine a timestamp for your query.

While trying to set up Superset with Materialize, the same error was thrown. In both cases, the issue was not present once downgraded to v0.7.0.

### Is the issue reproducible? If so, please provide reproduction instructions.

I first ran into this issue following the [Business Intelligence Demo walkthrough](https://materialize.com/docs/demos/business-intelligence/). Once you hit Metabase, just running: 

```sql
SELECT * FROM query01;
```
will lead to:

Metabase Error

Forcing a timestamp using `AS OF` returns results, but then occasionally fails with:

Metabase 2

### PR DESCRIPTION
**Pull request by mjibson**
This prevents unmaterialized sources joining timedomains when not
requested, which made transactions unusable in that case.

Fixes #6651
Fixes #7193
Fixes #7167

### CODE REVIEW

File: src/coord/src/catalog.rs [hunk 1]
```diff
@@ -1998,26 +1998,41 @@ impl Catalog {
...
+        &self,
+        ids: &[GlobalId],
+        conn_id: u32,
+    ) -> Vec<GlobalId> {
         // Find all relations referenced by the expression. Find their parent schemas
         // and add all tables, views, and sources in those schemas to a set.
-        let mut ids = HashSet::new();
-        for id in sources {
+        let mut relations: HashSet<GlobalId> = HashSet::new();
+        let ids: HashSet<GlobalId> = ids.iter().copied().collect();
```
Comment (ruchirK) [inline src/coord/src/catalog.rs:2010]: did we construct `ids` the HashSet just to dedup the input array? wasn't sure if there was a more fundamental reason we have both `ids` and `relations`

File: test/testdrive/transactions-timedomain-nonmaterialized.td [hunk 2]
```diff
@@ -7,7 +7,7 @@
 # the Business Source License, use of this software will be governed
 # by the Apache License, Version 2.0.
 
-# Test behavior of timedomains with non-materialized sources. Currently they prevent transactions
+# Test behavior of timedomains with non-materialized sources. Currently they prevent transactions.
```
Comment (ruchirK) [inline test/testdrive/transactions-timedomain-nonmaterialized.td:10]: it seems like they no longer prevent transactions is that right?

**Review by ruchirK — APPROVED** [review]
These changes make sense to me. I think its maybe also worth it to test this with unmaterialized views (maybe backed by a materialized source)

Also, I'm still not sure how this connects to the issues with BI tools - would love to know how it all ties together

File: src/coord/src/catalog.rs (hunk 1 above)
Comment (mjibson) [reply src/coord/src/catalog.rs:2010]: Oops, this was from a previous version. Removed.

File: test/testdrive/transactions-timedomain-nonmaterialized.td (hunk 2 above)
Comment (mjibson) [reply test/testdrive/transactions-timedomain-nonmaterialized.td:10]: Fixed.

**Comment by mjibson** [comment]
The BI tools issue is exactly this problem: the tool in that demo creates a transaction, which fails because there's an adjacent unmaterialized source.

**Review by ruchirK — APPROVED** [review]
