### PR TITLE
Retry schema registry requests for up to 30 seconds

### LINKED ISSUE #6185: Transient issues with the schema registry can cause permanent errors in the source stream
### What version of Materialize are you using?

```
v0.7.2-dev (f63a8eb91)
```

### What was the issue?

The REST API calls that are made to the schema registry when ingesting Avro data are not protected against transient issues. They are not retried so any sort of tranisent error would cause the stream to error out permanently.

### Is the issue reproducible? If so, please provide reproduction instructions.

1. In one terminal, mess with the schema registry:
```
while true ; do pkill -f schema-registry ; sleep 1 ;  confluent local services schema-registry start ; sleep 1; done
```
2. In another terminal, run testdrive:
```
../../target/release/testdrive  avro-resolution*
```

Sometimes this will error out in ```kafka-ingest```, which is OK, but sometimes it willl error out on a ```SELECT```:

```
> SELECT f1 FROM resolution_enums
rows didn't match; sleeping to see if dataflow catches up 125ms 250ms 500ms 1s 2s 4s 2.112008138s
avro-resolution-enums.td:37:1: error: executing query failed: db error: ERROR: Decode error: Text: avro deserialization error: transport: error sending request for url (http://localhost:8081/schemas/ids/41): error trying to connect: tcp connect error: Connection refused (os error 111)
     |
  36 | 
  37 | > SELECT f1 FROM resolution_enums
     | ^
```

Note that the error message here is the more verbose one suggested in #6153 . Without that patch, it will simply say ```Failed to fetch schema with ID 18```

### PR DESCRIPTION
**Pull request by cirego**
Instead of returning a failure on the first attempt to resolve a Schema
from the schema registry, retry for up to 30 seconds on the condition
that the schema registry may be restarting.

Fixes #6185

---------------------------------------------------------------------------------------------------

Thoughts when writing this PR:

1. If this fails, even with the additional retry logic, then the source will be permanently errored. However, we don't have an easy way to map "schema registry requests" back to rows that have presented source errors. My thinking is that adding a 30 second retry is better than nothing, we can easily increase this timeout if we feel like it's too small and that mapping resolution errors back to source errors is likely a fair amount of work.
2. I didn't add a test for this, as this is already caught by Antithesis. We could probably add a simple, deterministic test if we teach testdrive how to stop / start services but that would require teaching testdrive about both docker and local confluent services.

### CODE REVIEW

File: src/interchange/src/avro/schema.rs [hunk 1]
```diff
@@ -448,8 +450,11 @@ impl SchemaCache {
                 // An issue with _fetching_ the schema should be returned
                 // immediately, and not cached, since it might get better on the
                 // next retry.
-                // TODO - some sort of exponential backoff or similar logic
-                let response = self.ccsr_client.get_schema_by_id(id).await?;
+                let ccsr_client = &self.ccsr_client;
+                let response = Retry::default()
+                    .max_duration(Duration::from_secs(30))
+                    .retry(|_| async move { ccsr_client.get_schema_by_id(id).await })
```
Comment (philip-stoev) [inline src/interchange/src/avro/schema.rs:456]: I think that each failed attempt needs to be reported in the error log.

File: src/interchange/src/avro/schema.rs [hunk 2]
```diff
@@ -448,8 +450,11 @@ impl SchemaCache {
                 // An issue with _fetching_ the schema should be returned
                 // immediately, and not cached, since it might get better on the
                 // next retry.
-                // TODO - some sort of exponential backoff or similar logic
-                let response = self.ccsr_client.get_schema_by_id(id).await?;
+                let ccsr_client = &self.ccsr_client;
+                let response = Retry::default()
```
Comment (philip-stoev) [inline src/interchange/src/avro/schema.rs:454]: Could there be other cases where calls to  get_schema_by_id will be needed the future? Maybe the retry should be inside get_schema_id?

File: src/interchange/src/avro/schema.rs (hunk 1 above)
Comment (cirego) [reply src/interchange/src/avro/schema.rs:456]: What kind of error message would you propose? Given that this may be a transient error, I'm reluctant to add an error message. We do have an error message for when the fetch fails after the maximum time.

Is there something actionable for the user or would this be noise? Another option would be to add a Prometheus metric that tracks the number of retries and expose that metric?

File: src/interchange/src/avro/schema.rs (hunk 2 above)
Comment (cirego) [reply src/interchange/src/avro/schema.rs:454]: It looks like the only other code that calls this API is test code and we likely don't want to retry in those situations. We could have `get_schema_by_id` take a `Retry` object, or the parameters to a retry object?

File: src/interchange/src/avro/schema.rs (hunk 1 above)
Comment (umanwizard) [reply src/interchange/src/avro/schema.rs:456]: I think it should be a warning at least. This blocks avro decoding, so nothing in the dataflow can run while this is being retried. If someone's trying to debug why their queries are backing up, the fact that their schema registry configuration is flaky is something they'd surely be interested in knowing.

Comment (cirego) [reply src/interchange/src/avro/schema.rs:456]: I can add a warning message if we like and it'll probably look something like this:

```
warn: temporary failure trying to fetch schema by ID
warn: temporary failure trying to fetch schema by ID
error: permanent failure to fetch schema by ID
```

Given the 30 second timeout, I'm not sure how likely it will be that people can catch the warning messages and try to debug it before the error message pops up.

What do you think? I can add the warning messages if that makes sense!

**Comment by benesch** [comment]
Does this have the possibility to block the worker thread for up to 30s? (Not that the current behavior of blocking the worker thread on the HTTP request is great, but at least it's just one HTTP request.)

**Comment by umanwizard** [comment]
@benesch Yes it does - but that's probably not as bad as putting the source into a permanent, unrecoverable errored state.

I think this is fine as a short-term quick fix, but probably the true architecture we would want is to spawn off a separate task that handles querying the CSR and sending messages back to the Avro decode operator, which could put the stream in an errored state if the CSR returns errors, and retract the errored state if and when it comes back up. Meanwhile the operator could yield control back to Timely instead of blocking, so that other dataflows can continue to make progress.

That's a bit of a bigger change, so if you want to land this as a quick win (because I _do_ think it has positive value), @cirego I'm totally fine with doing so as long as we file an issue to get to the ideal state at some point.

(Btw, this is mostly a recording of a conversation I just had verbally with Nikhil)

**Comment by cirego** [comment]
> @benesch Yes it does - but that's probably not as bad as putting the source into a permanent, unrecoverable errored state.
> 
> I think this is fine as a short-term quick fix, but probably the true architecture we would want is to spawn off a separate task that handles querying the CSR and sending messages back to the Avro decode operator, which could put the stream in an errored state if the CSR returns errors, and retract the errored state if and when it comes back up. Meanwhile the operator could yield control back to Timely instead of blocking, so that other dataflows can continue to make progress.
> 
> That's a bit of a bigger change, so if you want to land this as a quick win (because I _do_ think it has positive value), @cirego I'm totally fine with doing so as long as we file an issue to get to the ideal state at some point.
> 
> (Btw, this is mostly a recording of a conversation I just had verbally with Nikhil)

It's interesting to me because, while these functions are async, we call `block_on(method_that_calls_get)`  because `decode_upsert_value` is a sync function. @umanwizard , your suggestion would imply having some bridge that lets us reschedule the work once the blocking call has been completed?

Ideally, this blocking call is made extremely rarely, as it should only be made when the schema isn't cached and schema IDs should change very rarely.

**Comment by umanwizard** [comment]
> It's interesting to me because, while these functions are async, we call `block_on(method_that_calls_get)` because `decode_upsert_value` is a sync function. @umanwizard , your suggestion would imply having some bridge that lets us reschedule the work once the blocking call has been completed?

Basically, yeah. Timely-Dataflow, where the operators run, has its own scheduling logic that doesn't know anything about the Rust `async` system, and this impedance mismatch occasionally causes difficulties (as here).

> Ideally, this blocking call is made extremely rarely, as it should only be made when the schema isn't cached and schema IDs should change very rarely.

Right, my proposal would be useful for the case when the schema registry actually goes permanently down; then the source would be in an errored state but we would periodically retry (forever) without blocking the worker. Then the user could notice the error, fix their schema-registry, and the source would notice and un-error the stream.

File: src/interchange/src/avro/schema.rs (hunk 1 above)
Comment (umanwizard) [reply src/interchange/src/avro/schema.rs:456]: If the retry _succeeds_, you may never get an error message, right? I'm imagining a situation where someone's network is screwed up such that their schema registry sporadically goes down for 1 second at a time. You'd want to see that in the logs, even though there is no permanent error.

So, indeed, I think what you just described sounds good.

Comment (cirego) [reply src/interchange/src/avro/schema.rs:456]: Yes, if the retry succeeds, you'll never see an error message. But each retry will generate a warning, which can serve as a good "when does this issue arise" debugging hint.

Comment (umanwizard) [reply src/interchange/src/avro/schema.rs:456]: Sounds good!

**Comment by cirego** [comment]
Okay, I've updated this PR to print a warning message for any transient errors where we are going to retry the fetch. If we've exceeded our budget, then we'll raise the error up the stack and it will be printed by the calling code.

**Review by philip-stoev — APPROVED** [review]
Thank you for adding the logging. I do not think it is noise because:
- all the other kafka , zookeeper, debezium, schema-registry components will be printing warnings under similar circumstances (X is unable to contact Y)
- having the lines with similar timestamps would allow the user to correlate the logs from all the services to piece together what has happened. Therefore, Materialize should also be doing its part in printing to the log in this circumstance.
- we ourselves print warnings in case of Kafka issues

**Review by umanwizard — APPROVED** [review]

**Comment by cirego** [comment]
> Thank you for adding the logging. I do not think it is noise because:
> 
> * all the other kafka , zookeeper, debezium, schema-registry components will be printing warnings under similar circumstances (X is unable to contact Y)
> * having the lines with similar timestamps would allow the user to correlate the logs from all the services to piece together what has happened. Therefore, Materialize should also be doing its part in printing to the log in this circumstance.
> * we ourselves print warnings in case of Kafka issues

Sounds good to me! I think warning feels like the right level of logging; thanks for suggesting it!
