### PR TITLE
storage: better kafka error reporting

### LINKED ISSUE #12465: sources: a Kafka source with incorrect authentication parameters can be succesfully created, fails to ingest any data
### What version of Materialize are you using?

materialized v0.26.1-dev (d12bfe583)

### How did you install Materialize?

Docker image

### What is the issue?

Against a SSL-enabled Kafka, such as the one started by the `kafka-ssl` test, one can do the following:

```
materialize=>  CREATE MATERIALIZED SOURCE connector_source3 FROM KAFKA BROKER 'kafka:9092'  TOPIC 'testdrive-data-1684546814' FORMAT BYTES;
CREATE SOURCE
```
And this will succeed, with the source forever remaining empty:

```
materialize=> select * from connector_source3;
 data | mz_offset 
------+-----------
(0 rows)
```

The only errors are to be found in the Mz error log.

### Relevant log output

```source
storaged: 2022-05-16T16:28:46.191013Z  INFO librdkafka: FAIL [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 1ms in state APIVERSION_QUERY)
storaged: 2022-05-16T16:28:46.290249Z ERROR mz_kafka_util::client: librdkafka: Global error: BrokerTransportFailure (Local: Broker transport failure): kafka:9092/bootstrap: Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 1ms in state APIVERSION_QUERY)
storaged: 2022-05-16T16:28:46.290263Z ERROR mz_kafka_util::client: librdkafka: Global error: AllBrokersDown (Local: All broker connections are down): 1/1 brokers are down
storaged: 2022-05-16T16:28:46.454988Z  INFO librdkafka: FAIL [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 1ms in state APIVERSION_QUERY, 1 identical error(s) suppressed)
storaged: 2022-05-16T16:28:46.492168Z ERROR mz_kafka_util::client: librdkafka: Global error: BrokerTransportFailure (Local: Broker transport failure): kafka:9092/bootstrap: Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 1ms in state APIVERSION_QUERY, 1 identical error(s) suppressed)
```

### PR DESCRIPTION
**Pull request by petrosagg**
### Motivation

This PR tries to understand what went wrong with a Kafka connection by observing the `librdkafka` error log. Unfortunately there isn't a less ugly way to get information of what happened since librdkafka has very limited error codes.
    
Fixes #12465

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

File: src/kafka-util/src/client.rs [hunk 1]
```diff
@@ -35,8 +36,123 @@ pub const DEFAULT_FETCH_METADATA_TIMEOUT: Duration = Duration::from_secs(30);
...
+            }
+        };
+        match *self.error.lock().unwrap() {
+            // This replacement happens on the basis that internal type errors can be of very low
+            // relevance to our users since librdkafka logs many internal details (e.g
+            // openssl errors) as error logs. Replacing the existing error if it's of the
+            // Internal variant will either result into a new Internal error, or, a known
+            // error variant.
+            Some(ref mut cur @ MzKafkaError::Internal(_)) => *cur = err,
+            // If it's a known error variant we "latch" onto it until it's cleared.
```
Comment (guswynn) [inline src/kafka-util/src/client.rs:68]: still, we may have MULTIPLE real errors, and lose data on later ones

Can we make this a vector/map instead, where it can hold one of each type of error max?

File: src/kafka-util/src/client.rs [hunk 2]
```diff
@@ -35,8 +36,123 @@ pub const DEFAULT_FETCH_METADATA_TIMEOUT: Duration = Duration::from_secs(30);
...
+    /// An internal kafka error
+    #[error("Internal kafka error: {0}")]
+    Internal(String),
+}
+
+impl FromStr for MzKafkaError {
+    type Err = ();
+
+    fn from_str(s: &str) -> Result<Self, Self::Err> {
+        if s.contains("Authentication failed: Invalid username or password") {
```
Comment (guswynn) [inline src/kafka-util/src/client.rs:123]: ohhhh rdkafka...

File: src/storage-client/src/types/connections.rs [hunk 3]
```diff
@@ -516,15 +520,25 @@ impl KafkaConnection {
...
-        .await??;
-        Ok(())
+        .await?;
+        match result {
+            Ok(_) => Ok(()),
+            // The error returned by `fetch_metadata` does not provide any details which makes for
+            // a crappy user facing error message. For this reason we attempt to grab a better
+            // error message from the client context, which should contain any error logs emitted
+            // by librdkafka, and fallback to the generic error if there is nothing there.
+            Err(err) => match consumer.context().inner().take_err() {
```
Comment (guswynn) [inline src/storage-client/src/types/connections.rs:537]: the only place we `take_err` is when fetching metadata...do we have plans to also take errors as part of normal consumption? this ends up being more important in sinks than sources, right?

**Review by guswynn — APPROVED** [review]
this is much better! I have 1 suggestion, to track a list of errors, but your call

File: src/kafka-util/src/client.rs (hunk 1 above)
Comment (petrosagg) [reply src/kafka-util/src/client.rs:68]: The reason this is not a `Vec` is that this context is used in a bunch of places and not all of them are wired up to handle errors from the context, so a Vec could be accumulating data for a long time. I considered a middleground where this is a channel and you can drop the receiver to signal that you don't care about errors which would solve the problem but there is nothing that would use the multiple errors atm.

Comment (guswynn) [reply src/kafka-util/src/client.rs:68]: I suppose this is a better change than nothing, and we can start with it! Definitely might want to leave a `TODO` to use a bounded buffer/channel of some kind though!

Comment (petrosagg) [reply src/kafka-util/src/client.rs]: I implemented the channel! It wasn't that complicated in the end

File: src/kafka-util/src/client.rs [hunk 4]
```diff
@@ -36,7 +38,119 @@ pub const DEFAULT_FETCH_METADATA_TIMEOUT: Duration = Duration::from_secs(30);
 /// context or a custom context that delegates the `log` and `error` methods to
 /// this implementation.
 #[derive(Clone)]
-pub struct MzClientContext;
+pub struct MzClientContext {
+    /// The last observed error log, if any.
```
Comment (guswynn) [inline src/kafka-util/src/client.rs:42]: this might not be quite right anymore haha

**Comment by guswynn** [comment]
channel looks good!

**Comment by benesch** [comment]
This is so great, thank you!
