### PR TITLE
adapter: fix off-by-one in connection id generation

### LINKED ISSUE #24574: panic: chosen ID must not intersect with mask
Sentry Issue: [DATABASE-BACKEND-38Q](https://materializeinc.sentry.io/issues/4898357980/?referrer=github_integration)

```
panic: chosen ID must not intersect with mask
  File "panicking.rs", line 597, in rust_begin_unwind
  File "id_gen.rs", line 133, in mz_ore::id_gen::IdAllocatorInnerBitSet::alloc
  File "id_gen.rs", line 189, in mz_ore::id_gen::IdAllocator<T>::alloc_internal
  File "id_gen.rs", line 296, in mz_ore::id_gen::internal::IdHandleInner<T>::new
  File "id_gen.rs", line 176, in mz_ore::id_gen::IdAllocator<T>::alloc
...
(70 additional frame(s) were not displayed)
```

This was apparently introduced in
```
ommit 634ef422ae64b43cc273aaf065877d39ca7984ad
Author: Matt Jibson <matt.jibson@gmail.com>
Date:   Wed Jan 17 16:54:24 2024 -0700

    environmentd: use part of envid in connid (#24477)
    
    Use the lower 12 bits of the environment id as the upper 12 bits of the
    connection id.
    
    See
    https://github.com/MaterializeInc/materialize/issues/24081#issuecomment-1874880062
```

### PR DESCRIPTION
**Pull request by mjibson**
We were 1 bit high on the max connection id which ended up conflicting with the mask.

Fixes #24574

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

### CODE REVIEW

File: src/ore/src/id_gen.rs [hunk 1]
```diff
@@ -299,12 +302,51 @@ mod internal {
     }
 }
 
+/// Number of bits the org id is offset into a connection id.
+pub const ORG_ID_OFFSET: usize = 19;
+
+/// Number of bits the org id is offset into a connection id.
```
Comment (jkosh44) [inline src/ore/src/id_gen.rs:308]: Is this comment accurate?

**Review by jkosh44 — APPROVED** [review]

File: src/ore/src/id_gen.rs (hunk 1 above)
Comment (mjibson) [reply src/ore/src/id_gen.rs]: Fixed.

**Comment by mjibson** [comment]
I realized that we already had a supposed check for this, but it also had an off by one error. Fixed that as well and added another test that would have found this.
