### PR TITLE
[kafka exactly once sink] Fence consistency topics before determining latest ts

### LINKED ISSUE #8356: bootstrap reuse_topic kafka sinks in parallel
Kafka exactly-once sinks (EOS, ie. those created with reuse_topic) on restart need to read state from Kafka to determine the last written offsets so they know at what point to resume publishing.

That bootstrap process can take a bit of time for a single sink as the consistency topic needs to be scanned from the beginning, but there are ways to speed this up - namely by enabling Kafka compaction on the consistency topic.

A bigger problem is that currently, this process occurs synchronously, bootstrapping one EOS at a time until all have been hydrated. Thus, if bootstrap takes X seconds and there are Y reuse_topic sinks, materialize startup time ends up taking X * Y seconds. This is a particularly bad UX because it occurs during catalog bootstrap, meaning mz is not available and responsive for other work during this time.

This will require some thought and design work. Two initial strawmen to think about (neither of which I claim are ideal):
1. Keep the bootstrap within the coord, but fire off sink creation in parallel. May involve tokio threadpools to allow librdkafka to block if there isn't an async API for what we need, and could be a lot of complexity to take into the coord (an area that is already complex)
2. Push the bootstrap out of the coord and into the Kafka sink itself, modeling it within the sink's state machine. Given the librdkafka API, this would likely cause the workers to block during bootstrap, so we may only achieve `num_workers` level of parallelism. Would also need to think carefully about retries and how to surface errors back to the user.

Relevant code pointers are `coord.rs` bootstrap() fn calling into the coord's `sink_connector.rs` build_kafka().

### LINKED ISSUE #9249: reuse-topic: Fence existing kafka consistency topics before determining latest ts
Frank pointed out the following sequence in slack:
```
1. MZ writes some stuff to the consistency and data topics transactionally,
2. Kafka goes to sleep just before committing this; writes are still enqueued,
3. MZ restarts and attempts to read MAX_OFFSET from Kafka,
4. Kafka wakes up and handles (3.) before (1.).
```

Kafka provides a mechanism to avoid this -- picking a `transactional.id` for the producer -- which allows for linearizability across restarts.

However, we determine the lastest ts we've seen (`get_latest_ts`) _before_ completing the fencing by starting up the producers with the same `transactional.id`s.  This means we could read an inconsistent latest ts.  When doing this, we want to make sure we do not write new data to the producers until we've determined the latest ts.

### LINKED ISSUE #9514: reuse-topic: Timestamp bindings do not begin compacting for exactly once kafka sources until first message written
When running testdrive [`kafka-exactly-once-sink`](https://github.com/MaterializeInc/materialize/blob/89209f64e93ddfa513338bc4d47a327d40968655/test/testdrive/kafka-exactly-once-sink.td), the sink `output2`, connected to source `input_kafka_no_byo` does not ever compact timestamp bindings and the count keeps increasing

```
$ sqlite3 mzdata/catalog
sqlite> SELECT sid, COUNT(*), MIN(timestamp), MAX(timestamp), name FROM timestamps JOIN items ON timestamps.sid = items.gid GROUP BY sid;
{"User":1}|4|1639079019675|1639079023000|input_kafka_no_byo
```

However, if a `kafka-ingest` command is added, the bindings properly compact.

This is because in order to compact the bindings, we need to write out the consistency topic indicating that we've read up to that timestamp.  However, we're not able to do this while the sink is still in the `Init` state (as it will remain until it gets data): `Error writing out progress update: Transaction error: Operation not valid in state Init`

### What version of Materialize are you using?
03b786559; most recent version v0.11.2

### PR DESCRIPTION
**Pull request by cjubb39**
Now that the kafka sink has been asyncified in #10044 , it has become easier to make changes like this.  As described in #9249 and the title, we move fencing before the determination of the last ts to be successfully written to the consistency topic.  We do that by
- Creating an explicit initialization phase of the KafkaSink.  When transitioning out of it, we call `init_transactions` on the kafka producer and then afterwards, create a consumer to read in and determine the most recent timestamp.
- Moving the work for determining most recent timestamp to live within the sink itself rather than being done when creating the sink connector
- Reorganizing how sink state is tracked with a couple new enums and structs.  These are designed in a way to make it impossible to enter into some invalid states.  For example, moving from `KafkaSinkStateEnum::Init` to `KafkaSinkStateEnum::Running` _requires_ a `gate_ts` -- and that `gate_ts` cannot be read before entering the `Running` state because it's not yet saved onto the sink state.

### Motivation

Fixes #9249
Fixes #9514 
Fixes #8356

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### CODE REVIEW

File: src/dataflow/src/sink/kafka.rs [hunk 1]
```diff
@@ -912,31 +1165,59 @@ where
...
-                // soon as the sink starts up.  There isn't anything inherently wrong with this but
-                // we need to update testdrive to be able to check a reasonable condition that this
-                // is correct.  That is, td currently checks we start with a BEGIN and then END.
-                // We'd need to be able to do a search for a BEGIN to properly test were we to
-                // remove this check.  This would fix #9514.
-                && s.ready_rows.front().is_some()
-            {
-                if s.transactional {
-                    retry_txn_with_error!(|s, producer| { producer.init_transactions().await });
+            // XXX(chae): is there a way to find out if we're teh active worker without consuming
```
Comment (cjubb39) [inline src/dataflow/src/sink/kafka.rs:1168]: We should be able to fix #9514 with this change but because we don't identify which worker is active, we don't properly initialize any of them and so we cannot set an initial write frontier to be able to compact timestamps

File: src/dataflow/src/sink/kafka.rs [hunk 2]
```diff
@@ -566,17 +690,185 @@ impl KafkaSinkState {
...
+    async fn determine_latest_consistency_record(
+        &self,
+    ) -> Result<Option<Timestamp>, anyhow::Error> {
+        // Return the list of partition ids associated with a specific topic
+        /// Polls a message from a Kafka Source
+        fn get_next_message(
+            consumer: &mut BaseConsumer,
+            timeout: Duration,
+        ) -> Result<Option<(Vec<u8>, i64)>, anyhow::Error> {
+            if let Some(result) = consumer.poll(timeout) {
```
Comment (petrosagg) [inline src/dataflow/src/sink/kafka.rs:702]: Is this a blocking call?

File: src/dataflow/src/sink/kafka.rs [hunk 3]
```diff
@@ -566,17 +690,185 @@ impl KafkaSinkState {
...
+            config: &ClientConfig,
+            timeout: Duration,
+        ) -> Result<Option<Timestamp>, anyhow::Error> {
+            let mut consumer = config
+                .create::<BaseConsumer>()
+                .context("creating consumer client failed")?;
+
+            // ensure the consistency topic has exactly one partition
+            let partitions =
+                kafka_util::client::get_partitions(consumer.client(), consistency_topic, timeout)
```
Comment (petrosagg) [inline src/dataflow/src/sink/kafka.rs:728]: Is this a blocking call?

File: src/dataflow/src/sink/kafka.rs [hunk 4]
```diff
@@ -566,17 +690,185 @@ impl KafkaSinkState {
...
+        }
+
+        // There may be arbitrary messages in this topic that we cannot decode.  We only
+        // return an error when we know we've found an END message but cannot decode it.
+        fn maybe_decode_consistency_end_record(
+            bytes: &[u8],
+            consistency_topic: &str,
+        ) -> Result<Option<Timestamp>, anyhow::Error> {
+            // The first 5 bytes are reserved for the schema id/schema registry information
+            let mut bytes = &bytes[5..];
```
Comment (petrosagg) [inline src/dataflow/src/sink/kafka.rs:813]: If bytes is malformed this will panic, can you add a length check and return an error if it's < 5?

File: src/dataflow/src/sink/kafka.rs [hunk 5]
```diff
@@ -856,9 +1129,50 @@ where
                     accum.meet(&history.durability_frontier())
                 });
 
+            // Can't use `?` when the return type is a `bool` so use a custom try operator
+            macro_rules! bail_err {
+                ($expr:expr) => {
+                    match $expr {
+                        Ok(val) => val,
+                        Err(_) => {
+                            s.activator.activate();
```
Comment (petrosagg) [inline src/dataflow/src/sink/kafka.rs:1138]: I think I missed this in the previous PR. Why do we have to re-activated immediately on error?

File: src/dataflow/src/sink/kafka.rs [hunk 6]
```diff
@@ -856,9 +1129,50 @@ where
...
+                        Ok(ts) => ts,
+                        Err(e) => {
+                            s.shutdown_flag.store(true, Ordering::SeqCst);
+                            info!("shutting down kafka sink while initializing: {}", e);
+                            return true;
+                        }
+                    };
+                    let consistency_state = init
+                        .as_ref()
+                        .cloned()
```
Comment (petrosagg) [inline src/dataflow/src/sink/kafka.rs:1161]: nit: `.as_ref().cloned()` is the same as just `.clone()`

File: src/dataflow/src/sink/kafka.rs [hunk 7]
```diff
@@ -316,6 +320,91 @@ impl KafkaTxProducer {
...
+    impl KafkaConsistencyGateTs {
+        pub fn new() -> Self {
+            Self {
+                ts: AtomicU64::new(0),
+                init: AtomicBool::new(false),
+            }
+        }
+
+        pub fn get_ts(&self) -> Option<Timestamp> {
+            if self.init.load(Ordering::Relaxed) {
```
[the remark this answers is not in the document]
Comment (cjubb39) [reply src/dataflow/src/sink/kafka.rs:344]: In order for `init` to return `true`, we have to have called `set` -- and if we've called set, then `Some(0)` (the default) is a correct bound -- even if it's not as tight a bound as we'd like `Some(actual_value)`

All that said, I think you're right that `Rc<Cell<Option<Timestamp>>>` is more clear

File: src/dataflow/src/sink/kafka.rs (hunk 2 above)
Comment (cjubb39) [reply src/dataflow/src/sink/kafka.rs:702]: yes -- it's only ever called on a background thread.  It'd be tricky to asyncify because rdkafka doesn't expose an async interface.  Calling it with `tokio::spawn_blocking` seems like overkill / needlessly complex since it's only ever called on one of those threads anyways -- do you think a comment is sufficient?

File: src/dataflow/src/sink/kafka.rs (hunk 6 above)
Comment (cjubb39) [reply src/dataflow/src/sink/kafka.rs:1161]: duh yes thanks

File: src/dataflow/src/sink/kafka.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (petrosagg) [reply src/dataflow/src/sink/kafka.rs:344]: Is the opposite situation also ok? i.e code calls set() and a subsequent get() returns None? Just curious, I agree we should make the code such that it doesn't require this level of analysis

[the remark this answers is not in the document]
Comment (cjubb39) [reply src/dataflow/src/sink/kafka.rs:344]: Hmm actually I'm starting to doubt where what I just said actually is true because of how I've reordered the code as this PR evolved -- either way, yeah, I'll just side step that question

File: src/dataflow/src/sink/kafka.rs (hunk 5 above)
Comment (petrosagg) [reply src/dataflow/src/sink/kafka.rs:1106]: What I'm trying to say is that if there logic expressed in `async_op` needs to describe some sort of "retry if an error happens logic" you could wrap everything in a `loop {}` block (or use one of the existing while loops) to break to (either implicitly or with a label).

The pattern here is as if we're implementing a `break 'start_of_function` using activations

Comment (cjubb39) [reply src/dataflow/src/sink/kafka.rs:1106]: Returning from this function is required to move the frontier forward so I think (for now at least?) this approach is preferable -- what do you think?

**Review by petrosagg — APPROVED** [review]
