### PR TITLE
compute-controller: Fix race between replica crash and drop

### LINKED ISSUE #15735: Panic 'no entry found for key' in ActiveInstance::rehydrate_replica
### What version of Materialize are you using?

main

### How did you install Materialize?

Built from source

### What is the issue?

The Zippy ClusterReplicas scenario sometimes fails with this backtrace:

```
zippy-materialized-1     | thread 'coordinator' panicked at 'no entry found for key', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07d0d4cd59bba8a6c-1/materialize/tests/src/compute-client/src/controller/instance.rs:435:24
zippy-materialized-1     | stack backtrace:
zippy-materialized-1     | storage-u43: 2022-10-27T11:10:48.404562Z  INFO mz_storage::sink::kafka: kafka-u43: sending progress for gate ts: 1666869049000
zippy-materialized-1     | storage-u43: 2022-10-27T11:10:48.415520Z  INFO mz_storage::sink::kafka: kafka-u43: downgrading write frontier to: 1666869049000
zippy-materialized-1     | storage-u14: 2022-10-27T11:10:48.579670Z  INFO mz_storage::sink::kafka: kafka-u14: sending progress for gate ts: 1666869049000
zippy-materialized-1     | storage-u14: 2022-10-27T11:10:48.590691Z  INFO mz_storage::sink::kafka: kafka-u14: downgrading write frontier to: 1666869049000
zippy-materialized-1     | storage-u43: 2022-10-27T11:10:49.397936Z  INFO mz_storage::sink::kafka: kafka-u43: sending progress for gate ts: 1666869050000
zippy-materialized-1     | storage-u43: 2022-10-27T11:10:49.409104Z  INFO mz_storage::sink::kafka: kafka-u43: downgrading write frontier to: 1666869050000
zippy-materialized-1     |    0: rust_begin_unwind
zippy-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
zippy-materialized-1     |    1: core::panicking::panic_fmt
zippy-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
zippy-materialized-1     |    2: core::panicking::panic_display
zippy-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:72:5
zippy-materialized-1     |    3: core::panicking::panic_str
zippy-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:56:5
zippy-materialized-1     |    4: core::option::expect_failed
zippy-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/option.rs:1874:5
zippy-materialized-1     |    5: core::option::Option<T>::expect
zippy-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/option.rs:738:21
zippy-materialized-1     |    6: <std::collections::hash::map::HashMap<K,V,S> as core::ops::index::Index<&Q>>::index
zippy-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/collections/hash/map.rs:1338:9
zippy-materialized-1     |    7: mz_compute_client::controller::instance::ActiveInstance<T>::rehydrate_replica::{{closure}}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07d0d4cd59bba8a6c-1/materialize/tests/src/compute-client/src/controller/instance.rs:435:24
zippy-materialized-1     |    8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
zippy-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
zippy-materialized-1     |    9: mz_compute_client::controller::instance::ActiveInstance<T>::rehydrate_failed_replicas::{{closure}}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07d0d4cd59bba8a6c-1/materialize/tests/src/compute-client/src/controller/instance.rs:446:47
zippy-materialized-1     |   10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
zippy-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
zippy-materialized-1     |   11: mz_compute_client::controller::ActiveComputeController<T>::process::{{closure}}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07d0d4cd59bba8a6c-1/materialize/tests/src/compute-client/src/controller.rs:671:45
zippy-materialized-1     |   12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
zippy-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
zippy-materialized-1     |   13: mz_controller::Controller<T>::process::{{closure}}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07d0d4cd59bba8a6c-1/materialize/tests/src/controller/src/lib.rs:189:63
zippy-materialized-1     |   14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
zippy-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
zippy-materialized-1     |   15: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_message::{{closure}}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07d0d4cd59bba8a6c-1/materialize/tests/src/adapter/src/coord/message_handler.rs:42:59
zippy-materialized-1     |   16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
zippy-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
zippy-materialized-1     |   17: mz_adapter::coord::Coordinator<S>::serve::{{closure}}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07d0d4cd59bba8a6c-1/materialize/tests/src/adapter/src/coord.rs:875:37
zippy-materialized-1     |   18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
zippy-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
zippy-materialized-1     |   19: tokio::park::thread::CachedParkThread::block_on::{{closure}}
zippy-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/park/thread.rs:263:54
zippy-materialized-1     |   20: tokio::coop::with_budget::{{closure}}
zippy-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:102:9
zippy-materialized-1     |   21: std::thread::local::LocalKey<T>::try_with
zippy-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:445:16
zippy-materialized-1     |   22: std::thread::local::LocalKey<T>::with
zippy-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:421:9
zippy-materialized-1     |   23: tokio::coop::with_budget
zippy-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:95:5
zippy-materialized-1     |   24: tokio::coop::budget
zippy-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:72:5
zippy-materialized-1     |   25: tokio::park::thread::CachedParkThread::block_on
zippy-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/park/thread.rs:263:31
zippy-materialized-1     |   26: tokio::runtime::enter::Enter::block_on
zippy-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/enter.rs:152:13
zippy-materialized-1     |   27: tokio::runtime::handle::Handle::block_on
zippy-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/handle.rs:297:9
zippy-materialized-1     |   28: mz_adapter::coord::serve::{{closure}}::{{closure}}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07d0d4cd59bba8a6c-1/materialize/tests/src/adapter/src/coord.rs:1030:17
zippy-materialized-1     | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

This means the compute controller tries to rehydrate a replica that has already been removed.

One possible fix is that we check before rehydration if the replica still exists, and skip it otherwise. But it is not clear how this condition can happen in the first place. We should investigate.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by lluki**
When a replica crashes and at the same time a `DROP REPLICA` is requested, environmentd can crash when it tries to rehydrate the newly removed replica.

When we notice a connection problem with a replica, we delay the rehydration (because of cancellation safety in `.recv()`). We keep a list of dysfunctional replicas in `failed_replicas`. If we remove a replica, we do not remove it from this list.

I probably introduced this bug in #15467 and the failing nightlies  #15735 (zippy create replica ) might be related to this issue.

### Motivation

Which of the following best describes the motivation behind this PR?

  * This PR fixes a known bug.

Fixes #15735.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - None

### CODE REVIEW

File: src/compute-client/src/controller/instance.rs [hunk 1]
```diff
@@ -420,6 +420,11 @@ where
             .remove(&id)
             .expect("replica not found");
 
+        // In case the replica crashes and we receive a drop replica request
+        // at the same time, the cleanup request will race with the rehydration.
+        // Hence we also have to stop a pending rehydration request.
+        self.compute.failed_replicas.remove(&id);
```
Comment (teskje) [inline src/compute-client/src/controller/instance.rs:426]: I think because of this possibility we should definitely move the orchestrator call to drop the service from the replica task into `remove_replica`. It might be that the replica task is not running right now because the replica is failed, in which case there would be nothing to drop the orchestrator service and we would leak it. That cannot happen if we `tokio::spawn` a cleanup task in `remove_replica`.

Comment (lluki) [reply src/compute-client/src/controller/instance.rs:426]: Hm, then it would be better to also move the ensure service there, otherwise a quick `CREATE` followed by `DROP` could swap orders and the service is dropped before it's ensured.

Comment (teskje) [reply src/compute-client/src/controller/instance.rs:426]: Good catch. I think this can happen in any case as long as ensure service and drop service are not executed in-line. Like, if we spawned a task in `add_replica` there would still be no guarantee that that gets scheduled before the task spawned by `remove_replica`.

Okay, alternative proposal: Run a rehydration of failed replicas at the beginning of `remove_replicas`, to ensure the task is actually there to stop the service in the orchestrator. Then I think we also don't need to worry about the race here.

Comment (lluki) [reply src/compute-client/src/controller/instance.rs:426]: Hm running a rehydration only to drop it sounds not very elegant, especially if you want to drop a wedged replica, the task might always give up before you can reach it. If we want to do that, we should have the task wait until it receives a terminate command from Instance. We'd probably need an extra message type: TerminateWithOrchestratorRemove and TerminateWithoutOrchestratorRemoval...

At this point, I think it would be better to have an extra OrchestratorTask and an OrchestratorClient and they send each other messages. The task would serialize all the requests (ok then the initial refactor was a bit pointless, as the orchestrator calls could have stayed in the sequencer...)

Comment (teskje) [reply src/compute-client/src/controller/instance.rs:426]: Hm, true, I didn't consider that the replica task always waits for a successful connection first.

Sounds like an orchestrator task really is the best solution then.

> (ok then the initial refactor was a bit pointless, as the orchestrator calls could have stayed in the sequencer...)
Wait, why would an orchestrator task mean we need to block the sequencer?

**Comment by lluki** [comment]
I think we should merge this for now, @antiguru mentioned that we should tackle the kubernetes ressource leaks soonish. I think the refactor discussed (creating an `OrchestratorTask` + `OrchestratorClient`) is part of that.

**Review by teskje — APPROVED** [review]
LGTM
