### PR TITLE
Handle Avro over Kafka without a schema registry

### LINKED ISSUE #5443: KAFKA+AVRO - Don't know how to serialize key / message
I'm using `materialized v0.6.1 (3247686f8)` and I'm getting this error:

```
ERROR dataflow::decode: avro deserialization error: wrong Confluent-style avro serialization magic: expected 0, got 121
```
This doesn't seem to come from the message but the key. If I add 5 zeroes before the key I get:

```
dataflow::decode: avro deserialization error: IO error: UnexpectedEof
```

I have tried to encode as utf8 as well as avro record with single string. I'm not sure what the correct way is. Please help.

This is what I'm doing to create the source:

```
CREATE SOURCE test
 FROM KAFKA BROKER  'localhost:9092' TOPIC 'test'
 FORMAT AVRO USING SCHEMA '{
     "type": "record",
     "name": "Test",
     "namespace": "test",
     "fields": [
         {
             "name": "test",
             "type": "float"
         }
     ]
 }'
 ENVELOPE UPSERT;
```

P.S. It seems wasteful to prepend every event with 5+5 bytes even if you are defining the schema at CREATE STREAM

### LINKED ISSUE #5859: Avro: Don't require a schema-registry version byte for inline schemas.
Currently we always expect Avro messages in kafka to start with a magic byte generated by confluent encoders, but it is possible for users to not use confluent to encode avro. The code that checks this is [in interchange/../avro.rs](https://github.com/MaterializeInc/materialize/blob/594c35fa469f96ba717d0f63731fe35af69a90d4/src/interchange/src/avro.rs#L2079-L2099).

The fix is not hard, but we need to decide if we should autodetect this, or require some `WITH` parameter, or if there are other options.

### PR DESCRIPTION
**Pull request by quodlibetor**
The magic bytes only make sense and are only included if the user is using a
schema registry, so we should only check for them in that code.

To preserve existing catalogs and be backwards compatible, this defaults to
the old behavior of reading and validating the schema ID, and provides a new
WITH option to _not_ check for schema IDs

Resolves #5859

Also Fixes #5443 and I think the specific problem that caused #2125

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5862)

### CODE REVIEW

**Comment by umanwizard** [comment]
It sounds fine to me in principle - will take a more detailed look tomorrow

File: src/testdrive/src/parser.rs [hunk 1]
```diff
@@ -520,19 +520,21 @@ impl ArgMap {
...
+            if val == "true" {
+                Ok(true)
+            } else if val == "false" {
+                Ok(false)
+            } else {
+                Err(format!("bad value for boolean parameter {}: {}", name, val))
             }
-            None => Ok(false),
-        }
+        })
```
Comment (benesch) [inline src/testdrive/src/parser.rs:537]: These aren't in keeping with the pattern.
  * `opt_string -> Option<String>`
  * `string -> Result<String, String>`
  * `opt_parse -> Result<Option<T>, String>`
  * `parse -> Result<T, String>`

Granted `opt_bool` was already in violation of the rule, but this makes the situation pretty confusing. I recommend that we change `opt_bool` to return `Result<Option<bool>, String>`, and then the one existing call site can change like so:

```
let publish = cmd.args.opt_bool("publish")?.unwrap_or(false);
```

File: src/testdrive/src/action/kafka/ingest.rs [hunk 2]
```diff
@@ -126,6 +147,7 @@ pub fn build_ingest(mut cmd: BuiltinCommand) -> Result<IngestAction, String> {
     let format = match cmd.args.string("format")?.as_str() {
         "avro" => Format::Avro {
             schema: cmd.args.string("schema")?,
+            registry_bytes: cmd.args.bool_("registry-bytes").unwrap_or(Ok(true))?,
```
Comment (benesch) [inline src/testdrive/src/action/kafka/ingest.rs:150]: Once we settle on a name for the `WITH` option, we should use a name here that is the same or very reminiscent of that name. `registry_bytes` and `records_have_schema_id` are very different names for the same thing.

File: src/sql/src/normalize.rs [hunk 3]
```diff
@@ -388,39 +388,44 @@ pub fn create_statement(
...
 }
 
 /// This macro accepts a struct definition and will generate it and a `try_from`
 /// method that takes a `Vec<WithOption>` which will extract and type check
-/// options based on the struct field names and types. Field names must match
-/// exactly the lowercased option name. Supported types are:
+/// options based on the struct field names and types.
+///
+/// All field types will be converted to `Option`, which will be set to `None`
+/// if the field is not present.
```
Comment (benesch) [inline src/sql/src/normalize.rs:425]: minor grammar nit: this says that the field _type_ will be set to `None` which is a category error.

Maybe: "The macro wraps all field types in an `Option` in the generated struct. The `TryFrom` implementation sets fields to `None` if they are not present in the provided `WITH` options."

File: src/sql/src/normalize.rs [hunk 4]
```diff
@@ -388,39 +388,44 @@ pub fn create_statement(
...
-        } else {
-            ::anyhow::bail!("expected Interval");
+        match $name {
+            Some(crate::ast::WithOptionValue::Value(Value::String(value))) => {
+                ::repr::strconv::parse_interval(&value)?
+            }
+            Some(crate::ast::WithOptionValue::Value(Value::Interval(interval))) => {
+                ::repr::strconv::parse_interval(&interval.value)?
+            }
+            _ => ::anyhow::bail!("expected Interval"),
```
Comment (benesch) [inline src/sql/src/normalize.rs:415]: Why did these hunks all change? Just for aesthetics? In the future, please try to keep this stuff to a separate commit, or call it out in the code review as pure code movement. It's hard to review PRs that contain functionality changes, random doc comment improvements, and minor, functionality-preserving aesthetic changes all in the same commit. On my first pass I thought you changed the behavior of this macro, added documentation for the new behavior, and then used that new behavior, but it seems that's not the case.

**Review by benesch — COMMENTED** [review]
Sweet! We've been talking about doing this forever but never got around to it. (See e.g. https://github.com/MaterializeInc/materialize/issues/2125#issuecomment-591638003.) Glad to see it finally get done. I think this design makes sense. Left some comments within.

File: src/sql/src/normalize.rs (hunk 4 above)
Comment (quodlibetor) [reply src/sql/src/normalize.rs]: Ah, I intended to do that, my commits after this comment were made before I saw your response here, fwiw. It got moved to #5869 and added you explicitly as a reviewer on it.

File: doc/user/layouts/partials/create-source/connector/kafka/with-options.html [hunk 5]
```diff
@@ -32,3 +32,14 @@
 `sasl_kerberos_principal` | `text` | Materialize Kerberos principal name. Required for `sasl_plaintext`.
 `sasl_kerberos_service_name` | `text` | Kafka's service name on its host, i.e. the service principal name not including `/hostname@REALM`.
 `sasl_mechanisms` | `text` | The SASL mechanism to use for authentication. Currently, the only supported mechanism is `'GSSAPI'`.
+
+#### Inline schema `WITH` options
+
+Field | Value | Description
+------|-------|------------
+`records_have_schema_id` | `boolean` | Whether to look for the Confluent Schema Registry schema ID within Avro messages.
```
[the remark this answers is not in the document]
Comment (quodlibetor) [reply doc/user/layouts/partials/create-source/connector/kafka/with-options.html:40]: Yeah `confluent_wire_format` seems good and self explanatory.

File: src/testdrive/src/action/kafka/ingest.rs (hunk 2 above)
Comment (quodlibetor) [reply src/testdrive/src/action/kafka/ingest.rs]: these have both been changed to `confluent_wire_format`

File: src/coord/src/catalog/migrate.rs [hunk 6]
```diff
@@ -257,6 +258,62 @@ pub const CONTENT_MIGRATIONS: &[fn(&mut Catalog) -> Result<(), anyhow::Error>] =
...
+            match stmt {
+                Statement::CreateSource(CreateSourceStatement {
+                    format:
+                        Some(Format::Avro(AvroSchema::Schema {
+                            ref mut with_options,
+                            ..
+                        })),
+                    ..
+                }) => {
+                    if with_options.is_empty() {
```
Comment (sploiselle) [inline src/coord/src/catalog/migrate.rs:295]: It seems odd to me that if you've e.g. specified `client_id` or `security_protocol` that we wouldn't need this new default. idk much about these integrations, though, so quite possibly something I misunderstand.

**Review by sploiselle — COMMENTED** [review]
+1: Migration structurally LGTM, though I don't grok the logic inside the migration itself. Not blocking, just noting that I am having a hard time reasoning through it.

File: src/coord/src/catalog/migrate.rs (hunk 6 above)
Comment (quodlibetor) [reply src/coord/src/catalog/migrate.rs:295]: ah, this is specifically the `schema` with options, kafka sources have several divergent/distinct with option pragmas. I'll add a comment. I think this is possibly a larger problem, but I'm not sure how to solve it.

image

Comment (umanwizard) [reply src/coord/src/catalog/migrate.rs:300]: It's probably more clear to the reader if we check whether the options contain `confluent_wire_format` specifically, not just whether they're empty.

File: src/interchange/src/avro.rs [hunk 7]
```diff
@@ -2059,54 +2059,72 @@ impl DebeziumDecodeState {
...
+            }
+            Ok(schema_id)
+        };
         let resolved_schema = match &mut self.writer_schemas {
-            Some(cache) => cache
-                .get(schema_id, &self.reader_schema)
-                .await
-                .with_context(|| format!("Failed to fetch schema with ID {}", schema_id))?,
+            Some(cache) => {
+                let schema_id = extract_schema_id()?;
```
Comment (umanwizard) [inline src/interchange/src/avro.rs:2111]: Can we assert that `confluent_wire_format` is true here (and explain why it must be) ?

**Review by umanwizard — APPROVED** [review]

File: src/interchange/src/avro.rs (hunk 7 above)
Comment (quodlibetor) [reply src/interchange/src/avro.rs:2111]: I'll add it as a debug assert, technically it's just ignored in this branch because we have to use it to resolve with the writer schema, and I don't think that anything can go wrong with processing anything if it's set incorrectly.

File: src/coord/src/catalog/migrate.rs (hunk 6 above)
Comment (sploiselle) [reply src/coord/src/catalog/migrate.rs:300]: ty, Brandon; I didn't even realize we had options in multiple places now so obviously didn't read carefully enough.
