### PR TITLE
adapter: Enforce max connections at pgwire

### LINKED ISSUE #19194: test_max_connections is flaky
### Buildkite link

https://buildkite.com/materialize/tests/builds/55204#018803a9-419d-4a11-8ddb-9c3505faf8fd

### Relevant log output

```source
[2023-05-10T03:30:08Z] thread 'test_max_connections' panicked at 'expect db error: error communicating with the server: Connection reset by peer (os error 104)', src/environmentd/tests/sql.rs:3157:28
[2023-05-10T03:30:08Z] stack backtrace:
[2023-05-10T03:30:08Z]    0: rust_begin_unwind
[2023-05-10T03:30:08Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
[2023-05-10T03:30:08Z]    1: core::panicking::panic_fmt
[2023-05-10T03:30:08Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
[2023-05-10T03:30:08Z]    2: sql::test_max_connections::{closure#1}
[2023-05-10T03:30:08Z]              at ./tests/sql.rs:3157:28
[2023-05-10T03:30:08Z]    3: <core::option::Option<&tokio_postgres::error::DbError>>::unwrap_or_else::<sql::test_max_connections::{closure#1}>
[2023-05-10T03:30:08Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/option.rs:873:21
[2023-05-10T03:30:08Z]    4: sql::test_max_connections
[2023-05-10T03:30:08Z]              at ./tests/sql.rs:3155:13
[2023-05-10T03:30:08Z]    5: sql::test_max_connections::{closure#0}
[2023-05-10T03:30:08Z]              at ./tests/sql.rs:3124:27
[2023-05-10T03:30:08Z]    6: <sql::test_max_connections::{closure#0} as core::ops::function::FnOnce<()>>::call_once
[2023-05-10T03:30:08Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
[2023-05-10T03:30:08Z]    7: core::ops::function::FnOnce::call_once
[2023-05-10T03:30:08Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
[2023-05-10T03:30:08Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Additional thoughts

_No response_

### PR DESCRIPTION
**Pull request by andrewrodriguez-m**
Fixes #19194. It allows us to error out the connection on connect vs the first query. Also removes the test's flakyness

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

File: src/pgwire/src/protocol.rs [hunk 1]
```diff
@@ -243,6 +254,30 @@ where
         .vars_mut()
         .end_transaction(EndTransactionAction::Commit);
 
+    if !session.user().is_internal() && !session.user().is_external_admin() {
```
Comment (mjibson) [inline src/pgwire/src/protocol.rs:257]: This logic also needs to live somewhere in http, so should probably be a method on ConnectionCounter that takes a Session.

File: src/adapter/src/catalog/config.rs [hunk 2]
```diff
@@ -74,6 +75,8 @@ pub struct Config<'a> {
     /// TODO(migration): delete in version v.51 (released in v0.49 + 1
     /// additional release)
     pub connection_context: Option<mz_storage_client::types::connections::ConnectionContext>,
+    /// Global connection limit and count
+    pub active_connection_count: Arc<std::sync::Mutex<ConnectionCounter>>,
```
Comment (mjibson) [inline src/adapter/src/catalog/config.rs:79]: It's unfortunate the shared state needs to live in the catalog and its config, but that does indeed seem to be what's needed for SET and RESET to function.

File: src/adapter/src/catalog/config.rs [hunk 3]
```diff
@@ -13,6 +13,7 @@ use std::sync::Arc;
 use std::time::Duration;
 
 use bytesize::ByteSize;
+use mz_sql::session::vars::ConnectionCounter;
```
Comment (mjibson) [inline src/adapter/src/catalog/config.rs:16]: Many of the imports are mis sorted, could these get fixed? See https://github.com/MaterializeInc/materialize/pull/19244 for an in-progress PR that should be the new standard.

File: src/adapter/src/catalog.rs [hunk 4]
```diff
@@ -2780,13 +2780,13 @@ impl Catalog {
                 cluster_replica_sizes: config.cluster_replica_sizes,
                 default_storage_cluster_size: config.default_storage_cluster_size,
                 availability_zones: config.availability_zones,
-                system_configuration: SystemVars::default(),
+                system_configuration: SystemVars::new(config.active_connection_count),
```
Comment (mjibson) [inline src/adapter/src/catalog.rs:2783]: When reading this value from the stash on bootstrap it should also be sync'd to this, otherwise all restarted envds will be at a 0 limit. I don't think even the LD sync would fix it because LD believes the current announced value to be correct, but it didn't get propagated here at boot.

Edit: ah, I see this was happening in SystemVars::new, more comments there.

File: src/stash-debug/src/main.rs [hunk 5]
```diff
@@ -421,6 +422,7 @@ impl Usage {
             system_parameter_frontend: None,
             storage_usage_retention_period: None,
             connection_context: None,
+            active_connection_count: Arc::new(Mutex::new(ConnectionCounter::new(0))),
```
Comment (mjibson) [inline src/stash-debug/src/main.rs:425]: I'm genuinely not opposed to just having this be an Option to avoid plumbing this business through all the tests. Thoughts?

File: src/sql/src/session/vars.rs [hunk 6]
```diff
@@ -1739,10 +1772,25 @@ impl SystemVars {
...
+
+        if name == MAX_CONNECTIONS.name {
+            self.refresh_state();
+        }
+        Ok(result)
+    }
+
+    /// Refresh the internal state (currently just active_connection_count) when any of
+    /// the system vars that may affect them changes. Today only when MAX_CONNECTIONS changes.
+    fn refresh_state(&mut self) {
```
Comment (mjibson) [inline src/sql/src/session/vars.rs:1789]: This is a bit awkward because it forces callers to check the var name before calling. What about

```
fn propagate_var_change(&mut self, name: &str)
```

which can hold the name check logic one time there. My above This would avoid the need to call this function in `new` as long as it's init'd in catalog open. Is this better or not? Hard to tell. So much shared state here it's not obvious where to put the init step. I do think catalog open is a more logical place than the new system vars though.

File: src/pgwire/src/protocol.rs [hunk 7]
```diff
@@ -83,6 +87,11 @@ pub struct RunParams<'a, A> {
     /// Whether this is an internal server that permits access to restricted
     /// system resources.
     pub internal: bool,
+    /// During handling the query, did we increment the connection count. Used
+    /// during connection teardown to determine if we need to decrement the count.
+    pub incremented_connection_count: &'a mut bool,
```
Comment (mjibson) [inline src/pgwire/src/protocol.rs:92]: I didn't try to fully understand what was going on here (ran out of time tonight), but this seems a bit scary and maybe there's a better design. I'll take a look tomorrow try to make a suggestion.

File: src/adapter/src/catalog/config.rs (hunk 2 above)
Comment (andrewrodriguez-m) [reply src/adapter/src/catalog/config.rs:79]: Yeah we need the global state somewhere. I assume the config is short lived so doesn't matter?

File: src/stash-debug/src/main.rs (hunk 5 above)
Comment (andrewrodriguez-m) [reply src/stash-debug/src/main.rs:425]: Yeah, I had it as an Option and changed it to an Arc... my main reason was that all the production use cases need it. (I initially set it to None for the internal port but realized that that's how the user changes the max_connections so we still need to thread it through, we just don't need to check the user). I think they're both a little awkward; I'm happy to do either

File: src/sql/src/session/vars.rs (hunk 6 above)
Comment (andrewrodriguez-m) [reply src/sql/src/session/vars.rs:1789]: I added propagate_var_change, I think that's nicer. I think doing the initilization in `SystemVars::new` makes sense b/c then you can't mess up and forget to call `refresh_state` in any code paths. I tried adding the call to Catalog::load_system_configuration but the code didn't look like it was obviously important

File: src/pgwire/src/protocol.rs (hunk 7 above)
Comment (andrewrodriguez-m) [reply src/pgwire/src/protocol.rs:92]: Yeah, lemme know. Another idea i had was to protocol.rs's `run` return a `Result<bool, io::Error>` where the bool indicates whether or not we need to decrement the connection count. I was thinking of keeping a bool in that function and changing all the returns to `return blah.await.map(|()| should_decrement_count)` but that seemed wordy

File: src/pgwire/src/protocol.rs (hunk 1 above)
Comment (andrewrodriguez-m) [reply src/pgwire/src/protocol.rs:257]: Chatted offline. I think the plan is to leave this in. Happy to revisit when adding connection caps to http

File: src/adapter/src/catalog/config.rs (hunk 3 above)
Comment (andrewrodriguez-m) [reply src/adapter/src/catalog/config.rs:16]: Fixed

File: src/pgwire/src/protocol.rs (hunk 7 above)
Comment (mjibson) [reply src/pgwire/src/protocol.rs:90]: Ohh oh, this is per connection. Due to the `internal` flag I thought this was the singleton for the whole server and it was sharing this state back and forth like during connection startup or something. I'm ok with this.

**Review by mjibson — APPROVED** [review]
