### PR TITLE
adapter: Validate deferred plan before sequencing

### LINKED ISSUE #20402: parallel-workload: thread 'coordinator' panicked at 'no entry found for key', src/adapter/src/catalog.rs:572:10
### What version of Materialize are you using?

2e088905e27e7846b94f8b70c19904804c14a411

### What is the issue?

Happened in https://buildkite.com/materialize/nightlies/builds/2755#018930d6-6d4f-4d06-a89b-7ea9df2546d0 with my new parallel-workload: https://github.com/MaterializeInc/materialize/pull/20354
```
parallel-workload-materialized-1  | thread 'coordinator' panicked at 'no entry found for key', src/adapter/src/catalog.rs:572:10
parallel-workload-materialized-1  | stack backtrace:
parallel-workload-materialized-1  |    0: rust_begin_unwind
parallel-workload-materialized-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
parallel-workload-materialized-1  |    1: core::panicking::panic_fmt
parallel-workload-materialized-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
parallel-workload-materialized-1  |    2: core::panicking::panic_display
parallel-workload-materialized-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:147:5
parallel-workload-materialized-1  |    3: core::panicking::panic_str
parallel-workload-materialized-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:131:5
parallel-workload-materialized-1  |    4: core::option::expect_failed
parallel-workload-materialized-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/option.rs:1924:5
parallel-workload-materialized-1  |    5: <core::option::Option<&mz_adapter::catalog::CatalogEntry>>::expect
parallel-workload-materialized-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/option.rs:786:21
parallel-workload-materialized-1  |    6: <alloc::collections::btree::map::BTreeMap<mz_repr::global_id::GlobalId, mz_adapter::catalog::CatalogEntry> as core::ops::index::Index<&mz_repr::global_id::GlobalId>>::index
parallel-workload-materialized-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/collections/btree/map.rs:2216:23
parallel-workload-materialized-1  |    7: <mz_adapter::catalog::CatalogState>::get_entry
parallel-workload-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0096274f7b6df3875-1/materialize/tests/src/adapter/src/catalog.rs:572:10
parallel-workload-materialized-1  |    8: <mz_adapter::catalog::ConnCatalog as mz_sql::catalog::SessionCatalog>::get_item
parallel-workload-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0096274f7b6df3875-1/materialize/tests/src/adapter/src/catalog.rs:8251:9
parallel-workload-materialized-1  |    9: mz_adapter::rbac::generate_required_privileges::<mz_adapter::catalog::ConnCatalog>
parallel-workload-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0096274f7b6df3875-1/materialize/tests/src/adapter/src/rbac.rs:940:39
parallel-workload-materialized-1  |   10: mz_adapter::rbac::check_plan::<mz_adapter::catalog::ConnCatalog>
parallel-workload-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0096274f7b6df3875-1/materialize/tests/src/adapter/src/rbac.rs:203:31
parallel-workload-materialized-1  |   11: <mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}::{closure#0}
parallel-workload-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0096274f7b6df3875-1/materialize/tests/src/adapter/src/coord/sequencer.rs:92:25
parallel-workload-materialized-1  |   12: <mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}
parallel-workload-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0096274f7b6df3875-1/materialize/tests/src/adapter/src/coord/sequencer.rs:57:5
parallel-workload-materialized-1  |   13: <mz_adapter::coord::Coordinator>::message_write_lock_grant::{closure#0}::{closure#0}
parallel-workload-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0096274f7b6df3875-1/materialize/tests/src/adapter/src/coord/message_handler.rs:588:25
parallel-workload-materialized-1  |   14: <mz_adapter::coord::Coordinator>::message_write_lock_grant::{closure#0}
parallel-workload-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0096274f7b6df3875-1/materialize/tests/src/adapter/src/coord/message_handler.rs:573:5
parallel-workload-materialized-1  |   15: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
parallel-workload-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0096274f7b6df3875-1/materialize/tests/src/adapter/src/coord/message_handler.rs:70:64
parallel-workload-materialized-1  |   16: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_message::{closure#0}> as core::future::future::Future>::poll
parallel-workload-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
parallel-workload-materialized-1  |   17: <mz_adapter::coord::Coordinator>::serve::{closure#0}
parallel-workload-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0096274f7b6df3875-1/materialize/tests/src/adapter/src/coord.rs:1515:17
parallel-workload-materialized-1  |   18: <tokio::runtime::park::CachedParkThread>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}
parallel-workload-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:63
parallel-workload-materialized-1  |   19: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}>
parallel-workload-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:107:5
parallel-workload-materialized-1  |   20: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}>
parallel-workload-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:73:5
parallel-workload-materialized-1  |   21: <tokio::runtime::park::CachedParkThread>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
parallel-workload-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:31
parallel-workload-materialized-1  |   22: <tokio::runtime::context::BlockingRegionGuard>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
parallel-workload-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/context.rs:315:13
parallel-workload-materialized-1  |   23: <tokio::runtime::handle::Handle>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
parallel-workload-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/handle.rs:264:9
parallel-workload-materialized-1  |   24: mz_adapter::coord::serve::{closure#0}::{closure#1}
parallel-workload-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0096274f7b6df3875-1/materialize/tests/src/adapter/src/coord.rs:1741:17
parallel-workload-materialized-1  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
I tried running it locally, but didn't get the panic: `bin/parallel-workload-test --threads=100 --runtime=7200 --seed=1688741552 --complexity=ddl`, so probably timing-dependent. I'll try to see if I can reproduce this reliably.

There were similar panics before: https://github.com/MaterializeInc/materialize/issues/18996

### PR DESCRIPTION
**Pull request by jkosh44**
The adapter uses a global write lock to linearize read then write statements. If a read then write statement fails to acquire the write lock then it is pushed into a queue of deferred statements. Once the statement has acquired the write lock, it is popped off the queue and sequenced (i.e. executed).

While the deferred statement is on the queue, we allow DDL statements to execute. After we pop the statement off the queue we were not checking to make sure all the statements dependencies still existed. If a dependency was deleted while the statement was in the queue, then the statement would cause a panic during sequencing because it assumed all of its dependencies were validated during planning.

This commit adds a step after the statement is popped off of the queue to revalidate all dependencies and check that they still exist. If a dependency was deleted while it was waiting, then an error is returned to the user.

There are various points in the Coordinator where either a statement or plan is taken off of the main Coordinator thread for some asynchronous processing/waiting. Roughly each point has its own bespoke code for re-validating the statement or plan. Issues like this probably suggest that we should implement a more general framework for taking statements and plans off of the main Coordinator thread. For now another bespoke validation is probably good enough.

Fixes #20402

### Motivation
This PR fixes a recognized bug.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - Removes panics from concurrent DDL and `UPDATE`/`DELETE`/`INSERT INTO SELECT` statements.

### CODE REVIEW

**Comment by jkosh44** [comment]
@def- This seems to resolve the panics in your test, but I'd appreciate a sanity check if you don't mind validating that claim.

**Review by def- — APPROVED** [review]
Great, thanks for quickly fixing this. I can verify it's fixed, will keep it running for a bit just in case, but seems good. Failed much faster before.

Would it be possible to write an explicit test for this or is complex? We shouldn't rely on randomized tests to find regressions. It's quite easy to accidentally reduce coverage in a randomized test.

Now I'm wondering if it would make sense to also add some RBAC operations to the parallel-workload. Maybe CreateUser, DropUser, Grant and using those users instead of just materialize. What do you think @jkosh44?

**Comment by jkosh44** [comment]
> Would it be possible to write an explicit test for this or is complex? We shouldn't rely on randomized tests to find regressions. It's quite easy to accidentally reduce coverage in a randomized test.

I'll try and think of something over the weekend. Something like the following would work, but I'm not sure if it's 100% possible to make it deterministic:
1. Start a thread that executes a long running read then write query like `INSERT INTO t1 SELECT * FROM generate_series(0,100000), t2;`.
2. Start a thread that starts a read then write query after the lock has been acquired by the other thread. Something like `UPDATE t3 SET a = 1;`.
3. Drop the table that step 2 depends on. Something like `DROP TABLE t3;`.

> Now I'm wondering if it would make sense to also add some RBAC operations to the parallel-workload. Maybe CreateUser, DropUser, Grant and using those users instead of just materialize. What do you think @jkosh44?

I think that's a great idea.

File: src/adapter/src/coord/message_handler.rs [hunk 1]
```diff
@@ -581,11 +581,19 @@ impl Coordinator {
             match ready {
                 Deferred::Plan(mut ready) => {
                     ready.ctx.session_mut().grant_write_lock(write_lock_guard);
-                    // Write statements never need to track catalog
-                    // dependencies.
-                    let resolved_ids = ResolvedIds(BTreeSet::new());
-                    self.sequence_plan(ready.ctx, ready.plan, resolved_ids)
-                        .await;
+                    if ready
```
Comment (mjibson) [inline src/adapter/src/coord/message_handler.rs:584]: Can this instead use or extend `PeekValidity`?

Comment (jkosh44) [reply src/adapter/src/coord/message_handler.rs]: Just updated to use this struct. 

Something that I just noticed is that `PeekValidity` does not include types or functions. I'm not really sure if that's an issue or not. I'm not sure what would happen if a type involved in a peek is deleted while that peek is off thread.

**Review by mjibson — APPROVED** [review]

File: src/adapter/src/coord/message_handler.rs (hunk 1 above)
Comment (mjibson) [reply src/adapter/src/coord/message_handler.rs]: I'm also not sure. Would probably panic.

Comment (jkosh44) [reply src/adapter/src/coord/message_handler.rs]: I'll open an issue.
