### PR TITLE
storage: ban start offsets with more partitions that topic

### LINKED ISSUE #23482: storage: START OFFSET should error if larger than partition count
### What version of Materialize are you using?

071643949a

### What is the issue?

Seen in https://buildkite.com/materialize/nightlies/builds/5392#018c120c-8209-496c-b8a1-de5b04c5da8d
```
--- kafka-correctness.td
^^^ +++
kafka-compression.td:70:1: error: non-matching rows: expected:
[["world"]]
got:
[["hello"], ["world"]]
Poor diff:
+ hello

     |
  69 |   FORMAT TEXT
  70 | > SELECT text FROM zstd_fast_forwarded
     | ^
```
This is a regression and reproducible: `bin/mzcompose --find testdrive run default --kafka-default-partitions 5 kafka-compression.td`
I'll bisect it now.

### PR DESCRIPTION
**Pull request by guswynn**
Closes #23482

will document after it merges

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

File: src/sql/src/kafka_util.rs [hunk 1]
```diff
@@ -257,42 +259,60 @@ where
...
-                sql_bail!(
-                    "Expected offsets for {} partitions, but received {}",
-                    num_partitions,
-                    start_offsets.len(),
-                );
+                return Ok(Some(start_offsets));
             }
 
-            Ok(Some(start_offsets))
+            unreachable!()
```
Comment (bkirwi) [inline src/sql/src/kafka_util.rs:315]: This is kind of weird - took me a minute to figure out what was going on with the options above.

Maybe turn the first match into just an assert instead of unpacking, and then we can do a exhaustive match here instead of the two if-lets?

Comment (guswynn) [reply src/sql/src/kafka_util.rs:315]: sounds good!

**Comment by guswynn** [comment]
@bkirwi @benesch bump on this

**Review by bkirwi — APPROVED** [review]
Aside from the comment, this looks good!

**Comment by benesch** [comment]
Ah, sorry, was deferring review to @bkirwi! This is going to conflict badly with #23792, RIP. Wish I'd remembered you had this in flight over the weekend; coulda based #23792 on top of it. Oh well! You should go ahead and merge this because #23792 is going to need a little more work.

**Comment by guswynn** [comment]
@benesch ill fix the comment and merge now

**Comment by benesch** [comment]
@guswynn wanna just push the docs to https://github.com/MaterializeInc/materialize/pull/23793? That PR is already adjusting Kafka sink documentation that's slated to land this week, and so I'm already planning to merge that PR _next_ week when the release goes out.

**Comment by guswynn** [comment]
@benesch yeah ill push em there
