### PR TITLE
Test for a HTML file being served from the envd proxy instead of CSS.

### LINKED ISSUE #25294: test_internal_console_proxy fails
### Buildkite link

https://buildkite.com/materialize/tests/builds/75860#018dadd6-2774-4a3b-a09d-aeb49651fa1c

### Relevant log output

```source
thread 'test_internal_console_proxy' panicked at src/environmentd/tests/server.rs:2015:5:
assertion failed: `left.contains(right)`:
  left: `"text/html; charset=utf-8"`
 right: `"text/css"`
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: test_impl
             at ./tests/server.rs:2015:5
   3: server::test_internal_console_proxy
             at ./tests/server.rs:1997:1
   4: server::test_internal_console_proxy::{closure#0}
             at ./tests/server.rs:1997:1
   5: <server::test_internal_console_proxy::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Additional thoughts

_No response_

### PR DESCRIPTION
**Pull request by arusahni**
### Motivation

  * This PR fixes a recognized bug

The filename `styles.css` is not part of Console's external-facing contract. Instead, let's test for an HTML response from the base internal path.

Fixes #25294 

### Tips for reviewer

:+1:

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by RobinClowers — APPROVED** [review]
Thanks for taking care of this!

**Comment by arusahni** [comment]
(Rebased to ensure no weird merge conflicts with #25295 )

**Comment by nrainer-materialize** [comment]
> (Rebased to ensure no weird merge conflicts with #25295 )

You might want to remove the ignore annotation after the rebase and TODO comment.

**Comment by arusahni** [comment]
Good catch!

File: src/environmentd/tests/server.rs [hunk 1]
```diff
@@ -1997,7 +1997,6 @@ async fn test_concurrent_id_reuse() {
 // TODO: re-enable once we figure out how to do this test without
 // relying on internal resources:
 // <https://github.com/MaterializeInc/materialize/issues/25294>
-#[ignore]
```
Comment (guswynn) [inline src/environmentd/tests/server.rs:2000]: you also want to remove the lines above this!

Comment (arusahni) [reply src/environmentd/tests/server.rs:2000]: :kalispera:
