### PR TITLE
compute: replace dependants of replaced dataflows

### LINKED ISSUE #28961: compute: reconciliation does not consider dependencies
## Summary

When compute reconciliation recreates a dataflow, it does not force downstream dataflows to be recreated as well. This can result in these downstream dataflows keeping alive the original upstream dataflow with an incorrect description.

## Details

Courtesy of @aljoscha on Slack:

> Setup, connect as mz_system, so that we can create indexes on system objects:
> ```
> $ create index tables_idx on mz_tables (id, name);
> $ create index tables_lvl2_idx on mz_tables (id);
> $ set auto_route_catalog_queries = false; -- so we use _our_ indexes
> $ explain timestamp for select id from mz_tables;
>                                  Timestamp                                 
> ---------------------------------------------------------------------------
>                  query timestamp: 1723475109949 (2024-08-12 15:05:09.949) +
>            oracle read timestamp: 1723475109949 (2024-08-12 15:05:09.949) +
>  largest not in advance of upper: 1723475109949 (2024-08-12 15:05:09.949) +
>                            upper:[1723475109950 (2024-08-12 15:05:09.950)]+
>                            since:[1723475108000 (2024-08-12 15:05:08.000)]+
>          can respond immediately: true                                    +
>                         timeline: Some(EpochMilliseconds)                 +
>                session wall time: 1723475110551 (2024-08-12 15:05:10.551) +
>                                                                           +
>  source mz_catalog.tables_idx (u1, compute):                              +
>                    read frontier:[1723475108000 (2024-08-12 15:05:08.000)]+
>                   write frontier:[1723475109950 (2024-08-12 15:05:09.950)]+
>                                                                           +
>  source mz_catalog.tables_lvl2_idx (u2, compute):                         +
>                    read frontier:[1723475108000 (2024-08-12 15:05:08.000)]+
>                   write frontier:[1723475109950 (2024-08-12 15:05:09.950)]+
>  
> (1 row)
> ```
> Also notice in the logs that creating the second index/dataflow uses the first one as input!
> Then, start the new-version deployment with forced/faked builtin migration, let it hydrate, then promote. In the logs, we’ll see that reconciliation only fails for the first index that we created, not the second one! (At least without Nikhils PR).
> Then, check behaviour in SQL:
> ```
> $ set auto_route_catalog_queries = false; -- use our indexes
> $ explain timestamp for select id from mz_tables;
>                                  Timestamp                                 
> ---------------------------------------------------------------------------
>                  query timestamp: 1723475319103 (2024-08-12 15:08:39.103) +
>            oracle read timestamp: 1723475319103 (2024-08-12 15:08:39.103) +
>  largest not in advance of upper: 1723475228583 (2024-08-12 15:07:08.583) +
>                            upper:[1723475228584 (2024-08-12 15:07:08.584)]+
>                            since:[1723475318000 (2024-08-12 15:08:38.000)]+
>          can respond immediately: false                                   +
>                         timeline: Some(EpochMilliseconds)                 +
>                session wall time: 1723475319559 (2024-08-12 15:08:39.559) +
>                                                                           +
>  source mz_catalog.tables_idx (u1, compute):                              +
>                    read frontier:[1723475318000 (2024-08-12 15:08:38.000)]+
>                   write frontier:[1723475319104 (2024-08-12 15:08:39.104)]+
>                                                                           +
>  source mz_catalog.tables_lvl2_idx (u2, compute):                         +
>                    read frontier:[1723475227000 (2024-08-12 15:07:07.000)]+
>                   write frontier:[1723475228584 (2024-08-12 15:07:08.584)]+
>  
> (1 row)
> ```
> Notice how the upper of the second index is stuck in the past! And we’ll also get stuck when trying to query.
>
> I believe that problem is that compute assumes that id mappings are immutable. Say my two indexes are `u1` and `u2`, and `u2` depends on `u1`. Reconciliation will notice that the definition for `u1` fails, discard it and restart. But the definition for `u2` doesn’t change, it still depends on `u1`, so nothing changed, and that dataflow keeps running. And this dataflow in turn is holding on to the `persist_source -> u1 dataflow` flow that was rendered with `mz_tables.txn_shard = None`.

@teskje's assessment:

> If we don't replace dataflows that depend on dataflows that have been replaced, those will keep the replaced dataflows alive. So the replaced dataflow then continues secretly running and consuming resources in the background, while it's replacement is potentially unused. I can imagine that would be confusing.

cc @teskje @jkosh44

### PR DESCRIPTION
**Pull request by teskje**
This PR fixes a bug in compute reconciliation, which would reuse dataflows even when dataflows they were reading from had been replaced. This behavior was undesirable because the reused dataflows would keep discarded dataflows alive, and the installed dataflows wouldn't match the ones requested by the controller anymore.

To fix this we tweak the reconciliation logic to also replace dataflows that depend on replaced dataflows.

### Motivation

  * This PR fixes a recognized bug.

Fixes #28961 

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

File: src/compute/src/server.rs [hunk 1]
```diff
@@ -636,13 +635,20 @@ impl<'w, A: Allocate + 'static> Worker<'w, A> {
...
-                            let subscribe_free = dataflow
-                                .sink_exports
-                                .iter()
-                                .all(|(_id, sink)| !sink.connection.is_subscribe());
-                            if compatible && uncompacted && subscribe_free {
+
+                            // We cannot reconcile subscriptions at the moment, because the
+                            // response buffer is shared, and to a first approximation must be
+                            // completely reformed.
+                            let subscribe_free = dataflow.subscribe_ids().count() == 0;
```
Comment (antiguru) [inline src/compute/src/server.rs:642]: Nit: We don't have `is_empty` for iterators, should we use `peekable().next().is_none()` here? Probably doesn't matter since we have at most one export for each dataflow...

**Review by antiguru — APPROVED** [review]
Looks good, thanks!

File: src/compute/src/server.rs (hunk 1 above)
Comment (teskje) [reply src/compute/src/server.rs:642]: I think just `next().is_none()` should work, no? I have no strong opinion on which is more readable, they both seem fine but not as nice as `is_empty`.

Comment (teskje) [reply src/compute/src/server.rs]: Changed to `.next().is_none()` because it's theoretically more efficient, although as you say it doesn't matter as long as we don't have multi-export dataflows.

**Comment by teskje** [comment]
TFTR!

File: src/compute/src/server.rs (hunk 1 above)
Comment (antiguru) [reply src/compute/src/server.rs]: Yes, still waking up from time off :)
