### PR TITLE
repr,expr,sql: remove ScalarType::Unknown

### LINKED ISSUE #3150: CASE should accept untyped NULL for false
Unsure if anything cares about this, perhaps an easy fix though?

PG:
```sql
postgres=# select case when null then 1 else 2 end;
 case
------
    2
(1 row)
```

Materialize:
```sql
materialize=> select case when null then 1 else 2 end;
ERROR:  CASE expression has non-boolean type Unknown
```

cc SQL language people @sploiselle, @benesch

### PR DESCRIPTION
**Pull request by benesch**
@justinj this fixes #3150 and as a side effect cleans up a long-standing bit of tech debt.

@sploiselle I think we chatted about this a bit last week. Don't worry: I promise to wait until after your function generalization PR! But I think it has the potential to clean up some of the weirdness around `param_types`, since it exposes a function (`plan_coercible_expr`) that plans an expression without mutating `param_types`. And now that I look at it, with this PR and your PR I think literal coercion (#481) will wind up being like <10 lines of code.

/cc @frankmcsherry I think you'll be delighted about the effects on the expr/dataflow layer.

----

ScalarType::Unknown is a Postgresism that has not served us well. It
is best understood as the type of NULL in the following SQL statement

    SELECT NULL

although in recent versions Postgres will assign that NULL a type of
`text` before planning is complete. That is in fact the key insight: the
"unknown" type represents a transient state of the planner. Either the
unknown type will become known by the time planning is complete, or it
will not, and planning the query will fail.

We can isolate the dataflow execution layer from the unknown type by
limiting its existence to the few moments in the planner where it is
needed. To that end, this patch removes the ScalarType::Unknown variant,
and introduces a CoercibleScalarExpr to take its place.

The idea is that the planner has special handling for expressions which
could possibly coerce to another type (i.e., a string literal, list
literal, NULL literal, or query parameter). The expressions will be
coerced at the moment their true types are required; for example calling
a function will coerce any unknown parameters, as will reaching the root
of the expression tree.

All code outside of the `sql` crate gets vastly simpler. The SQL planner
gets simpler in many places too, and a bit different in others--not more
complicated, necessarily, just different.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/3160)

### CODE REVIEW

File: src/sql/expr.rs [hunk 1]
```diff
@@ -145,6 +145,46 @@ pub enum ScalarExpr {
     Select(Box<RelationExpr>),
 }
 
+pub enum CoercibleScalarExpr {
+    Coerced(ScalarExpr),
+    Parameter(usize),
+    LiteralNull,
+    LiteralList(Vec<CoercibleScalarExpr>),
+}
```
[the remark this answers is not in the document]
Comment (benesch) [reply src/sql/expr.rs:153]: Yeah exactly! I didn't include it here to keep clippy happy, but basically you just introduce a `CoercibleScalarExpr::LiteralString(String)`, unconditionally plan string literals as such, and the rest falls out pretty naturally. Like I think you just implement `plan_coerce` for `CoercibleScalarExpr::LiteralString` by calling `plan_cast_internal()` with the desired type.

File: src/sql/src/func.rs [hunk 2]
```diff
@@ -587,52 +584,49 @@ impl<'a> ArgImplementationMatcher<'a> {
...
-            Ok(hinted_expr)
-        } else if ParamType::JsonbAny == *typ {
-            super::query::plan_to_jsonb(self.ecx, self.ident, hinted_expr)
+        if let CoercibleScalarExpr::Coerced(arg) = &arg {
+            if self.ecx.scalar_type(arg) == s {
+                return Ok(arg.clone());
+            }
+        }
+
+        if ParamType::JsonbAny == *typ {
```
Comment (sploiselle) [inline src/sql/src/func.rs:606]: This could be a `match typ` now that we're no longer comparig `arg.is_string_literal()`

File: src/sql/src/func.rs [hunk 3]
```diff
@@ -254,22 +252,30 @@ impl<'a> ArgImplementationMatcher<'a> {
...
         }
 
-        // Exact match
-        let f = if let Some(func) = m.get_implementation(&raw_arg_types) {
-            func
-        } else {
-            // Best match
-            m.best_match(args, &raw_arg_types)?
-        };
+        let f = m.best_match(&exprs)?;
```
Comment (sploiselle) [inline src/sql/src/func.rs:261]: without an attempt at an exact match, `best_match` seems misnamed

File: src/sql/src/query.rs [hunk 4]
```diff
@@ -1799,9 +1846,9 @@ fn plan_aggregate(ecx: &ExprContext, sql_func: &Function) -> Result<AggregateExp
     let (mut expr, mut func) = match (name.as_str(), &sql_func.args) {
         // COUNT(*) is a special case that doesn't compose well
         ("count", FunctionArgs::Star) => (
-            // Ok to use `ScalarType::Unknown` here because this expression
-            // can't ever escape the surrounding reduce.
-            ScalarExpr::literal_null(ScalarType::Unknown),
+            // The scalar type of the null doesn't matter because this
+            // expression can't ever escape the surrounding reduce.
```
Comment (sploiselle) [inline src/sql/src/query.rs:1850]: nit: s/can't ever escape/can't escape/ ...or something grammatically equivalent

File: src/sql/src/query.rs [hunk 5]
```diff
@@ -3076,7 +3109,6 @@ pub fn plan_cast_implicit<'a>(
     let from_scalar_type = ecx.column_type(&expr).scalar_type;
 
     match (&from_scalar_type, &to_scalar_type) {
-        (String, String) | (Unknown, String) => {}
```
Comment (sploiselle) [inline src/sql/src/query.rs:3079]: You'll need to re-add this `(String, String)` line for the time being; I have a refactor for the implicit casts in mind but will wait for this to land.

Comment (benesch) [reply src/sql/src/query.rs:3079]: Oh crap. Did not mean to delete the `(String, String)` bit.

File: src/sql/src/func.rs (hunk 2 above)
Comment (benesch) [reply src/sql/src/func.rs:606]: Sure thing, done.

File: src/sql/src/func.rs (hunk 3 above)
Comment (benesch) [reply src/sql/src/func.rs]: Shoot, I forgot I removed that. I guess it's not strictly necessary given that everything passed without it, but I added it back so that we could follow Postgres's algorithm exactly.

File: src/sql/src/query.rs (hunk 4 above)
Comment (benesch) [reply src/sql/src/query.rs]: Done, but I"m not sure I see what was wrong with the original?

File: src/sql/expr.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (benesch) [reply src/sql/expr.rs]: This is done now!

File: src/sql/expr.rs [hunk 6]
```diff
@@ -145,6 +145,46 @@ pub enum ScalarExpr {
     Select(Box<RelationExpr>),
 }
 
+pub enum CoercibleScalarExpr {
```
[the remark this answers is not in the document]
Comment (benesch) [reply src/sql/expr.rs]: Done!

**Comment by benesch** [comment]
Thanks for dealing with the sloppiness of the revision you saw, @sploiselle! I've cleaned things in func.rs up a good bit, and the set of changes is smaller. Nothing fundamental has shifted, though; just a few more comments and a cleaner separation of responsibility between `coerce_arg_to_type` and `plan_coerce`. I think probably those two functions want to be merged somehow, but I don't think that can happen until we've moved everything over to func.rs.
