### PR TITLE
materialized: disable version check for "-dev" versions

### LINKED ISSUE #4701: Incorrect version upgrade message?
It seems odd to be giving me an upgrade nag for `0.5.0` when i'm on `0.5.1-dev`:
materialized v0.5.1-dev (248528eef) listening on 0.0.0.0:6875...
Nov 03 23:31:51.023  WARN materialized::version_check: A new version of materialized is available: 0.5.0. 

I grabbed the latest version of Materialize (from dev):
curl -L https://downloads.mtrlz.dev/materialized-latest-x86_64-apple-darwin.tar.gz | tar -xzC /usr/local --strip-components=1

### PR DESCRIPTION
**Pull request by benesch**
Versions that end in "-dev" are development versions, so it doesn't make
much sense to warn users about new versions.

Fix #4701.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4702)

### CODE REVIEW

**Comment by rjnn** [comment]
I think we should still check and report, but maybe with a simple informative neutral tone?

E.g. someone may deploy dev in order to incorporate a recent bug fix. At some point once a release lands with that fix they might want to switch back to stable builds.

**Comment by benesch** [comment]
> I think we should still check and report, but maybe with a simple informative neutral tone?
> 
> E.g. someone may deploy dev in order to incorporate a recent bug fix. At some point once a release lands with that fix they might want to switch back to stable builds.

I guess. Done. @mjibson please take a closer look at this than you might have otherwise, since there is a good bit more complexity now.

File: src/materialized/src/version_check.rs [hunk 1]
```diff
@@ -10,30 +10,44 @@
...
+use semver::{Identifier, Version};
 use serde::{Deserialize, Serialize};
 
-use crate::VERSION;
 use ore::retry::RetryBuilder;
 
+use crate::VERSION;
+
 // Runs fetch_latest_version in a backoff loop until it succeeds once, prints a
 // warning if there is another version, then returns.
```
Comment (mjibson) [inline src/materialized/src/version_check.rs:22]: "if there is another version" -> "if there is a newer version" or something

File: src/materialized/src/version_check.rs [hunk 2]
```diff
@@ -10,30 +10,44 @@
...
+            // We assume users running development builds are sophisticated, and
+            // may be intentionally not running the latest release, so downgrade
+            // the message from warn to info level.
+            let level = match current_version.pre.as_slice() {
+                [Identifier::AlphaNumeric(s)] if s == "dev" => Level::Info,
+                _ => Level::Warn,
+            };
+            log!(
+                level,
+                "a new version of materialized is available: {}",
```
Comment (mjibson) [inline src/materialized/src/version_check.rs:45]: The initial `a` has been lowercased here. Was that an intentional change? I'm not sure what is commonly done.

**Review by mjibson — APPROVED** [review]
In addition to the dev message downgrade, the more interesting change here is that only a newer version string, instead of just a different version, will be printed. Can you change the commit message to describe that too?

File: src/materialized/src/version_check.rs (hunk 2 above)
Comment (benesch) [reply src/materialized/src/version_check.rs:45]: Oops, habit. Most of our other log messages at startup are lowercase, ... but that's really just because I wrote most of them. Plenty of the logs in the dataflow package have strayed from that style. I'm not sure. What did Cockroach do? (From a quick glance, seems to be a mishmash there too.)

**Comment by benesch** [comment]
Commit message and comments updated as you suggest. See comment about the capitalization change. Feel free to change that back, or fix all of our log messages one way or another. I'm going to sleep for now, so feel free to hit merge on this if/when it goes green.
