### PR TITLE
environmentd: allow panicking on failed 0dt deployment

### LINKED ISSUE #29328: 0dt/m1: add feature flag to panic when `max_wait` is reached
See: https://github.com/MaterializeInc/materialize/pull/28957#pullrequestreview-2234095613

This will improve the ergonomics of failed tests, as hitting the deployment `max_wait` timeout will produce a more useful panic message, rather than a somewhat vague "test timed out" error.

### PR DESCRIPTION
**Pull request by benesch**
Add a feature flag, `0dt_deployment_panic_after_timeout`, that causes environmentd to panic if the 0dt maximum wait time is reached and preflight checks have not succeeded.

This will be enabled in 0dt tests, to make the cause of test failures more obvious.

Fix #29328.

### Motivation

  * This PR adds a known-desirable feature.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

**Comment by benesch** [comment]
@def- would you mind rigging this up in the test suite and verifying that it works as you expect?

File: src/adapter-types/src/dyncfgs.rs [hunk 1]
```diff
@@ -32,6 +32,12 @@ pub const WITH_0DT_DEPLOYMENT_MAX_WAIT: Config<Duration> = Config::new(
     "How long to wait at most for clusters to be hydrated, when doing a zero-downtime deployment.",
 );
 
+pub const WITH_0DT_DEPLOYMENT_PANIC_AFTER_TIMEOUT: Config<bool> = Config::new(
+    "0dt_panic_after_timeout",
```
Comment (def-) [inline src/adapter-types/src/dyncfgs.rs:36]: Intentional that the name `0dt_panic_after_timeout` is different from `WITH_0DT_DEPLOYMENT_PANIC_AFTER_TIMEOUT`? I thought "with" is for durations, while "enable" is for booleans.

File: src/environmentd/src/lib.rs [hunk 2]
```diff
@@ -466,6 +468,40 @@ impl Listeners {
             );
             computed
         };
+        // Determine whether we shoudl panic if we reach the maximum wait time
```
Comment (def-) [inline src/environmentd/src/lib.rs:471]:
```suggestion
        // Determine whether we should panic if we reach the maximum wait time
```

File: src/catalog/src/durable/initialize.rs [hunk 3]
```diff
@@ -68,6 +68,13 @@ pub(crate) const ENABLE_0DT_DEPLOYMENT: &str = "enable_0dt_deployment";
 /// NOTE: Weird prefix because we can't start with a `0`.
 pub(crate) const WITH_0DT_DEPLOYMENT_MAX_WAIT: &str = "with_0dt_deployment_max_wait";
 
+/// The key used within the "config" collection where we store a mirror of the
+/// `0dt_deployment_panic_after_timeout` "system var" value. This is mirrored so
+/// that we can toggle the flag with LaunchDarkly, but use it in boot before
+/// LaunchDarkly is available.
+pub(crate) const WITH_0DT_DEPLOYMENT_PANIC_AFTER_TIMEOUT: &str =
+    "0dt_deployment_panic_after_timeout";
```
Comment (def-) [inline src/catalog/src/durable/initialize.rs:76]: The name is also different here from `0dt_panic_after_timeout`. Maybe this is the reason that it's not working locally for me. I'll try to push a commit to unify the names.

Comment (def-) [reply src/catalog/src/durable/initialize.rs:76]: Actually based on the comment maybe this is intentional.

**Comment by def-** [comment]
> @def- would you mind rigging this up in the test suite and verifying that it works as you expect?

I just pushed a commit which I'd expect to fall over with a panic during every 0dt deployment, but it's not panicking (locally).

**Review by jkosh44 — APPROVED** [review]

**Review by def- — APPROVED** [review]
Test run was fine.

**Comment by benesch** [comment]
Sweet! Thanks very much, @def-. Going to push up a change that fixes the consistency issue you spotted (using `enable_` instead of `with_` as the prefix) as well as the typo, and then mark for automerge.
