### PR TITLE
orchestrator: move orchestrator calls off the coordinator main thread

### LINKED ISSUE #24813: panic when creating replica due to failing webhook call
Sentry Issue: [DATABASE-BACKEND-391](https://materializeinc.sentry.io/issues/4926216768/?referrer=github_integration)

```
panic: creating replicas must not fail: ApiError: Internal error occurred: failed calling webhook "mservice.elbv2.k8s.aws": failed to call webhook: Post "https://aws-load-balancer-webhook-service.kube-system.svc:443/mutate-v1-service?timeout=10s": EOF: InternalError (ErrorResponse { status: "Failure", message: "Internal error occurred: failed calling webhook \"mservice.elbv2.k8s.aws\": failed to call webhook: Post \"https://aws-load-balancer-webhook-service.kube-system.svc:443/mutate-v1-service?timeout=10s\": EOF", reason: "InternalError", code: 500 })

Caused by:
    Internal error occurred: failed calling webhook "mservice.elbv2.k8s.aws": failed to call webhook: Post "https://aws-load-balancer-webhook-service.kube-system.svc:443/mutate-v1-service?timeout=10s": EOF: InternalError

Stack backtrace:
   0: <mz_orchestrator_kubernetes::NamespacedKubernetesOrchestrator as mz_orchestrator::NamespacedOrchestrator>::ensure_service::{closure#0}
   1: <mz_orchestrator_tracing::NamespacedTracingOrchestrator as mz_orchestrator::NamespacedOrchestrator>::ensure_service::{closure#0}
   2: <futures_util::stream::futures_unordered::FuturesUnordered<<mz_controller::Controller>::create_replicas::{closure#0}::{closure#0}::{closure#0}> as futures_core::stream::Stream>::poll_next
   3: <futures_util::stream::stream::buffer_unordered::BufferUnordered<futures_util::stream::stream::map::Map<futures_util::stream::iter::Iter<alloc::vec::into_iter::IntoIter<mz_controller::clusters::CreateReplicaConfig>>, <mz_controller::Controller>::create_replicas::{closure#0}::{closure#0}>> as futures_util::stream::stream::StreamExt>::poll_next_unpin
   4: <mz_controller::Controller>::create_replicas::{closure#0}
   5: <mz_adapter::coord::Coordinator>::create_cluster_replicas::{closure#0}
   6: <mz_adapter::coord::Coordinator>::create_cluster::{closure#0}
   7: <mz_adapter::coord::Coordinator>::sequence_create_managed_cluster::{closure#0}::{closure#0}
   8: <mz_adapter::coord::Coordinator>::sequence_create_cluster::{closure#0}::{closure#0}
   9: <mz_adapter::coord::Coordinator>::sequence_create_cluster::{closure#0}
  10: <mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}
  11: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}> as core::future::future::Future>::poll
  12: <mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}::{closure#0}
  13: <mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}
  14: <mz_adapter::coord::Coordinator>::handle_execute::{closure#0}::{closure#0}
  15: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_command::{closure#0}> as core::future::future::Future>::poll
  16: <mz_adapter::coord::Coordinator>::message_command::{closure#0}::{closure#0}
  17: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
  18: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_message::{closure#0}> as core::future::future::Future>::poll
  19: <mz_adapter::coord::Coordinator>::serve::{closure#0}
  20: <tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>> as core::future::future::Future>::poll
  21: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>
  22: std::sys_common::backtrace::__rust_begin_short_backtrace::<mz_adapter::coord::serve::{closure#0}::{closure#2}, ()>
  23: <<std::thread::Builder>::spawn_unchecked_<mz_adapter::coord::serve::{closure#0}::{closure#2}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  24: std::sys::unix::thread::Thread::new::thread_start
  25: <unknown>
  26: <unknown>
  File "panicking.rs", line 597, in rust_begin_unwind
  File "cluster.rs", line 525, in mz_adapter::coord::Coordinator::create_cluster_replicas::{closure#0}
  File "cluster.rs", line 370, in mz_adapter::coord::Coordinator::create_cluster::{closure#0}
  File "cluster.rs", line 157, in mz_adapter::coord::Coordinator::sequence_create_managed_cluster::{closure#0}::{closure#0}
  File "cluster.rs", line 99, in mz_adapter::coord::Coordinator::sequence_create_managed_cluster::{closure#0}
...
(49 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by teskje**
This PR makes the `ensure_service` and `drop_service` orchestrator calls non-async and non-blocking. It achieves that by introducing an orchestrator task that runs in the background and asynchronously handles requests for creating and removing services.

### Motivation

  * This PR fixes a recognized bug.

Fixes https://github.com/MaterializeInc/materialize/issues/17414
Fixes #24813

### Tips for reviewer

The diff is unfortunately pretty gnarly, particularly in the second commit. I recommend reviewing with whitespace ignored. The changes to `mz-orchestrator-kubernetes` are actually not that bad, mostly splitting the implementations of the `NamespacedOrchestrator` methods in two and moving parts down into the `OrchestratorWorker`. But somehow the Github diff gets utterly confused about the movement of `get_metrics` and produces a huge change as a result. Git on the CLI handles this better for me.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

File: src/orchestrator-kubernetes/src/lib.rs [hunk 1]
```diff
@@ -437,35 +519,209 @@ fn parse_k8s_quantity(s: &str) -> Result<ScaledQuantity, anyhow::Error> {
...
+        let name = format!("kubernetes-orchestrator:{}", self.config.namespace);
+        mz_ore::task::spawn(|| name, self.run()).abort_on_drop()
+    }
+
+    async fn run(mut self) {
+        while let Some(cmd) = self.command_rx.recv().await {
+            use OrchestratorCommand::*;
+            let result = match cmd {
+                EnsureService { id, config } => self.ensure_service(id, config).await,
+                DropService { id } => self.drop_service(&id).await,
```
Comment (benesch) [inline src/orchestrator-kubernetes/src/lib.rs:667]: I think we want to retry infinitely if either of these fails, rather than taking down envd. (Should also send an `error!` to Sentry because we need to immediately manually remediate.)

File: src/orchestrator/src/lib.rs [hunk 2]
```diff
@@ -196,7 +196,7 @@ pub struct ServiceConfig<'a> {
     /// A function that generates the arguments for each process of the service
     /// given the assigned listen addresses for each named port.
     #[derivative(Debug = "ignore")]
-    pub args: &'a (dyn Fn(&BTreeMap<String, String>) -> Vec<String> + Send + Sync),
+    pub args: Box<dyn Fn(&BTreeMap<String, String>) -> Vec<String> + Send + Sync>,
```
Comment (teskje) [inline src/orchestrator/src/lib.rs:199]: This is necessary because of the process orchestrator, where we send this closure to the `OrchestratorWorker`. For the k8s orchestrator, we can already generate the args before we construct the `WorkerCommand`.

Comment (benesch) [reply src/orchestrator/src/lib.rs:199]: Yeah, seems fine! None of this is perf sensitive at all.

File: src/orchestrator-kubernetes/src/lib.rs [hunk 3]
```diff
@@ -1270,31 +1272,51 @@ impl OrchestratorWorker {
...
+                            tracing::error!(
+                                cmd_type = $cmd_type,
+                                "orchestrator API call failed: {error}"
+                            );
+                            tokio::time::sleep(Duration::from_secs(1)).await;
+                        }
+                    }
                 }
             };
+        }
```
Comment (teskje) [inline src/orchestrator-kubernetes/src/lib.rs:1300]: I tried using the `Retry` helper from `mz-ore` here, but got stuck on async borrowing issues. Also I couldn't implement the retry logic as a loop around `handle_command` because `ListServices` contains a `oneshot` sender and needs to own that to be able to send the result, so the retry needs to be limited to the `list_services` call.

File: src/orchestrator-kubernetes/src/lib.rs [hunk 4]
```diff
@@ -1270,31 +1272,51 @@ impl OrchestratorWorker {
...
+            ($fut:expr, $cmd_type:expr) => {
+                loop {
+                    match $fut.await {
+                        Ok(result) => break result,
+                        Err(error) => {
+                            tracing::error!(
+                                cmd_type = $cmd_type,
+                                "orchestrator API call failed: {error}"
+                            );
+                            tokio::time::sleep(Duration::from_secs(1)).await;
```
Comment (teskje) [inline src/orchestrator-kubernetes/src/lib.rs:1295]: One second might be too aggressive?

File: src/orchestrator-kubernetes/src/lib.rs (hunk 3 above)
Comment (benesch) [reply src/orchestrator-kubernetes/src/lib.rs:1300]: Not sure exactly what borrowing issues you were running into, but there are at least two tricks to working around them.

The first trick is to pass state via [`retry_async_with_state`](https://dev.materialize.com/api/rust/mz_ore/retry/struct.Retry.html#method.retry_async_with_state). The idea is that you specify state to be passed in to every invocation of the retried function. That can help work around borrowing issues if each invocation needs exclusive access to an object. The downside is that you need to return the state on every invocation, which means you can't ergonomically use `?` any more.

The second trick is to ditch the closure and use [`into_retry_stream`]:

```rust
let retry = mz_ore::retry::Retry::new().into_retry_stream();
let mut result = None;
while retry.next().await.is_some() {
    result = do_operation();
}
result.expect("always called once")
```

That's the more nuclear option, as you don't get any nice automatic handling of errors, but you do get the exponential backoff at least.

Comment (teskje) [reply src/orchestrator-kubernetes/src/lib.rs:1302]: > Not sure exactly what borrowing issues you were running into

Well, I also don't remember and it seems to just work on the second try 😅 But thanks for explaining, I'm sure this will be useful down the road!

**Comment by teskje** [comment]
This is ready for review now. In the k8s orchestrator I took the approach of validating the configuration passed to orchestrator calls synchronously, and returning an error if that failed. The only errors that can occur in the background thread are kube API errors, so there is a good chance that retrying these is the right thing to do. We could additionally match on the returned `K8sError` and try to discern those variants that warrant a retry, but this leaves room for false negatives. Logging an error and retrying at least lets us make a manual decision about whether we want to restart, whereas crashing does not.

The process orchestrator doesn't retry and simply crashes. This seems fine for a dev implementation. If it turns out that retrying would be beneficial for, e.g., making CI more robust, we can always add it later.

File: src/controller/src/clusters.rs [hunk 5]
```diff
@@ -355,157 +346,80 @@ where
 
     /// Creates a replica of the specified cluster with the specified identifier
     /// and configuration.
-    ///
-    /// This method is NOT idempotent; It can fail between processing of different
-    /// replicas and leave the controller in an inconsistent state. It is almost
-    /// always wrong to do anything but abort the process on `Err`.
```
Comment (benesch) [inline src/controller/src/clusters.rs:361]: Feels so good to lose this 🦶🏽 🔫.

File: src/controller/src/clusters.rs [hunk 6]
```diff
@@ -355,157 +346,80 @@ where
...
+                };
+                compute_location = ClusterReplicaLocation {
+                    ctl_addrs: service.addresses("computectl"),
+                    dataflow_addrs: service.addresses("compute"),
+                    workers,
+                };
+                metrics_task = Some(metrics_task_join_handle);
+            }
         }
-        drop(replica_stream);
```
Comment (benesch) [inline src/controller/src/clusters.rs:472]: Also feels great to lose this.

File: src/controller/src/clusters.rs [hunk 7]
```diff
@@ -855,7 +765,7 @@ async fn try_remove_past_generation_replicas(
                 replica_id = %name.replica_id,
                 "removing past generation replica",
             );
-            orchestrator.drop_service(&service).await?;
+            orchestrator.drop_service(&service)?;
         }
     }
```
Comment (benesch) [inline src/controller/src/clusters.rs:771]: The code in this file got so much cleaner. 👌🏽 Really makes me feel like we got the abstraction right. Probably shouldn't have embarked on parallelizing the replica creation requests, and instead invested in the background task from the get go. Oh well.

**Review by benesch — APPROVED** [review]
This is really great work. Thanks again for picking this one up, @teskje. I'll sleep better at night with this in place. I think it's likely to make a material dent reducing the occasional unexplained coordinator stalls we've seen in production.

**Comment by teskje** [comment]
TFTR!
