### PR TITLE
qgm: Handle QGM ⇒ MIR lowering of global aggregates

### LINKED ISSUE #10800: qgm: wrong result with aggregates, dataflow graph missing branch dealing with empty collections
### What version of Materialize are you using?

v0.20.1-dev (ca980c050)

### How did you install Materialize?

Built from source

### What was the issue?

With QGM enabled, the plan is missing the branch that deals with empty collections:

```
materialize=> explain SELECT  COUNT( * )  FROM t1  ;
           Optimized Plan           
------------------------------------
 %0 =                              +
 | Get materialize.public.t1 (u289)+
 | Project ()                      +
 | Reduce group=()                 +
 | | agg count(true)               +
```

so, the result is incorrect:
```
materialize=> SELECT  COUNT( * )  FROM t1  ;
 count 
-------
(0 rows)
```

should have returned zero.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by aalexandrov**
qgm: Handle QGM ⇒ MIR lowering of global aggregates
    
Handle both GROUP BY and global aggregate when lowering a `Grouping` box type.

Fixes #10800.

### Motivation

* This PR fixes a recognized bug: [#10800](10800)

### Tips for reviewer

* This is based on the changes in PR [#10679](10679). Only the last commit needs to be reviewed.
* The original PR [#9715](9715) came without migrating the case from [in `lowering.rs`](https://github.com/MaterializeInc/materialize/blob/main/src/sql/src/plan/lowering.rs#L614-L632) that handles default values for global aggregates (as required by the SQL standard).
* This PR migrates this part of the logic and adds a corresponding test.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

File: src/sql/src/query_model/mir.rs [hunk 1]
```diff
@@ -127,10 +127,21 @@ impl<'a> Lowerer<'a> {
                 Self::lower_box_columns(input, &the_box, &column_map, outer_arity, input_arity)
             }
             BoxType::Grouping(grouping) => {
+                // Reduce may contain expressions with correlated subqueries, due to the constraints asserted
+                // by the the HIR ⇒ QGM conversion (aggregate and key are pushed to a preceding Select box and
```
Comment (wangandi) [inline src/sql/src/query_model/mir.rs:131]:
```suggestion
                // by the HIR ⇒ QGM conversion (aggregate and key are pushed to a preceding Select box and
```

File: src/sql/src/query_model/mir.rs [hunk 2]
```diff
@@ -127,10 +127,21 @@ impl<'a> Lowerer<'a> {
                 Self::lower_box_columns(input, &the_box, &column_map, outer_arity, input_arity)
             }
             BoxType::Grouping(grouping) => {
+                // Reduce may contain expressions with correlated subqueries, due to the constraints asserted
```
Comment (wangandi) [inline src/sql/src/query_model/mir.rs:130]:
```suggestion
                // Reduce may not contain expressions with correlated subqueries, due to the constraints asserted
```

File: src/sql/src/query_model/mir.rs [hunk 3]
```diff
@@ -127,10 +127,21 @@ impl<'a> Lowerer<'a> {
...
+                // by the the HIR ⇒ QGM conversion (aggregate and key are pushed to a preceding Select box and
+                // are always trivial in the Grouping box), we know these will be handled by the input call.
```
Comment (wangandi) [inline src/sql/src/query_model/mir.rs:132]:
```suggestion
                // are always trivial in the Grouping box).
```

**Review by wangandi — APPROVED** [review]
