### PR TITLE
adapter: Prevent dropping a Compute Sink more than once

### LINKED ISSUE #17887: Race condition when dropping compute sinks for subscribe
### What version of Materialize are you using?

v0.45.0-dev

### How did you install Materialize?

Built from source

### What is the issue?

When a user issues a `SUBSCRIBE`, the adapter creates a compute sink to serve the results of that `SUBSCRIBE`. The existence of that compute sink lives in two places.
1. A map in the `Coordinator` 
https://github.com/MaterializeInc/materialize/blob/bf77cc18827d116225e15297860c3931e7016afc/src/adapter/src/coord.rs#L479-L480
2. A vector is the `ConnMeta` which lives in a map in the `Coordinator`
https://github.com/MaterializeInc/materialize/blob/bf77cc18827d116225e15297860c3931e7016afc/src/adapter/src/coord.rs#L344-L346
https://github.com/MaterializeInc/materialize/blob/bf77cc18827d116225e15297860c3931e7016afc/src/adapter/src/coord.rs#L439-L441

There are two methods to drop a subscribe:

### The user initiates a commit: 
1. The sink is removed from `conn_meta.drop_sinks` and a message is sent to compute to drop the sinks. 
https://github.com/MaterializeInc/materialize/blob/bf77cc18827d116225e15297860c3931e7016afc/src/adapter/src/coord/sql.rs#L139-L158
2. Eventually Compute sends back a response to indicate that we should drop the subscribe. 
https://github.com/MaterializeInc/materialize/blob/bf77cc18827d116225e15297860c3931e7016afc/src/adapter/src/coord/message_handler.rs#L259-L269
3. The sink is removed from `active_subscribes`.
https://github.com/MaterializeInc/materialize/blob/bf77cc18827d116225e15297860c3931e7016afc/src/adapter/src/coord/sql.rs#L160-L169

### An object that the subscribe relies on is dropped:
1. The sink is removed from `conn_meta.drop_sinks` and a message is sent to compute to drop the sinks. 
https://github.com/MaterializeInc/materialize/blob/bf77cc18827d116225e15297860c3931e7016afc/src/adapter/src/coord/ddl.rs#L220-L238
https://github.com/MaterializeInc/materialize/blob/bf77cc18827d116225e15297860c3931e7016afc/src/adapter/src/coord/ddl.rs#L323-L338
2. Eventually Compute sends back a response to indicate that we should drop the subscribe. 
https://github.com/MaterializeInc/materialize/blob/bf77cc18827d116225e15297860c3931e7016afc/src/adapter/src/coord/message_handler.rs#L259-L269
3. The sink is removed from `active_subscribes`.
https://github.com/MaterializeInc/materialize/blob/bf77cc18827d116225e15297860c3931e7016afc/src/adapter/src/coord/sql.rs#L160-L169

There is a race condition that happens when the following happens in order: 
1. One session has completed step (1) of either method.
2. Another session completes step (1) of method "An object that the subscribe relies on is dropped", before the other session has completed step (2).
 
When this happens, both sessions try and send a message to COMPUTE to drop the same sink. As far as I can tell nothing bad actually happens except that an error is printed.

To reproduce this execute the following in one session:
```
materialize=> CREATE TABLE t1 (a INT);
CREATE TABLE
materialize=> CREATE TABLE t2 (a INT);
CREATE TABLE
materialize=> COPY (SUBSCRIBE (SELECT * FROM t1,t2)) TO STDOUT;
```
and then execute the following in another session:
```
materialize=> DROP TABLE t1; DROP TABLE t2;
```
This relies on a race condition so it doesn't reproduce 100% of the time. If it works you will see two notices in the subscribe session:
```
NOTICE:  subscribe has been terminated because underlying relation materialize.public.t1 was dropped
NOTICE:  subscribe has been terminated because underlying relation materialize.public.t2 was dropped
```

### Relevant log output

```source
environmentd: 2023-03-01T14:07:59.155002Z ERROR execute{portal_name=""}:message_command (execute):handle_execute:sequence_plan:catalog_transact:catalog_transact_with: mz_adapter::coord::ddl: Instructed to drop a compute sink that isn't one
```

### PR DESCRIPTION
**Pull request by parker-timmerman**
### Motivation

* This PR fixes a recognized bug.
  * Fixes #17887 

Currently there is a race where we can ask compute to drop the same sink twice. This PR should fix that by adding a `dropping` field to our `ActiveSubscribe` struct which maintains metadata about our active subscribes, and only sends the request to compute if we haven't already attempted to drop the sink.

I ran through the example provided at the end of #17887 but couldn't repro the race, so while I believe this should fix the issue, I can't prove that it does. What I plan to do though is monitor Sentry to see if the error crops up again, it was already reported once, [example](https://materializeinc.sentry.io/discover/database-backend:931086577c4447cfad18c08f7416ab4d/?field=title&field=event.type&field=project&field=user.display&field=timestamp&homepage=true&name=All+Events&query=Instructed+to+drop+a+compute+sink+that+isn%27t+one&sort=-timestamp&statsPeriod=14d&yAxis=count%28%29).

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

File: src/environmentd/tests/sql.rs [hunk 1]
```diff
@@ -2430,3 +2430,71 @@ fn test_query_on_dropped_source() {
...
+            notice_tx.unbounded_send(notice).unwrap();
+        })
+        .connect(postgres::NoTls)
+        .unwrap();
+
+    let handle_a = std::thread::spawn(move || {
+        client_a.batch_execute("CREATE TABLE t1 (a INT)").unwrap();
+        client_a.batch_execute("CREATE TABLE t2 (a INT)").unwrap();
+
+        create_tx.send(()).unwrap();
```
Comment (jkosh44) [inline src/environmentd/tests/sql.rs:2456]: This can probably all be done outside of the thread so we can avoid synchronizing over the channel.

File: src/environmentd/tests/sql.rs [hunk 2]
```diff
@@ -2430,3 +2430,71 @@ fn test_query_on_dropped_source() {
...
+        let _out = client_a
+            .copy_out("COPY (SUBSCRIBE (SELECT * FROM t1,t2)) TO STDOUT")
+            .unwrap();
+
+        // Keep the subscribe alive until we drop the underlying tables.
+        futures::executor::block_on(drop_rx).unwrap();
+
+        // Drop our client so the notice channel closes.
+        drop(_out);
+        drop(client_a);
```
Comment (jkosh44) [inline src/environmentd/tests/sql.rs:2467]: Is there any difference between explicitly dropping here or just letting them fall out of scope?

File: src/environmentd/tests/sql.rs [hunk 3]
```diff
@@ -2430,3 +2430,71 @@ fn test_query_on_dropped_source() {
...
+    futures::executor::block_on(create_rx).unwrap();
+
+    client_b
+        .batch_execute("INSERT INTO t1 SELECT generate_series(0, 10000)")
+        .unwrap();
+    client_b
+        .batch_execute("INSERT INTO t1 SELECT generate_series(0, 10000)")
+        .unwrap();
+    client_b.batch_execute("DROP TABLE t1").unwrap();
+    client_b.batch_execute("DROP TABLE t2").unwrap();
```
Comment (jkosh44) [inline src/environmentd/tests/sql.rs:2483]: If you combine all of this into a single call to `batch_execute` separated by semi-colons, it will probably increase the likelihood of hitting the race condition.

File: src/environmentd/tests/sql.rs [hunk 4]
```diff
@@ -2430,3 +2430,71 @@ fn test_query_on_dropped_source() {
...
+
+    // Wait until the other thread finishes creating the tables.
+    futures::executor::block_on(create_rx).unwrap();
+
+    client_b
+        .batch_execute("INSERT INTO t1 SELECT generate_series(0, 10000)")
+        .unwrap();
+    client_b
+        .batch_execute("INSERT INTO t1 SELECT generate_series(0, 10000)")
+        .unwrap();
```
Comment (jkosh44) [inline src/environmentd/tests/sql.rs:2481]: Can you add a comment explaining why we are doing this.

File: src/adapter/src/subscribe.rs [hunk 5]
```diff
@@ -43,6 +44,8 @@ pub struct ActiveSubscribe {
     pub depends_on: BTreeSet<GlobalId>,
     /// The time when the subscribe was started.
     pub start_time: EpochMillis,
+    /// Are we already in the process of dropping the resources related to this subscribe.
```
Comment (jkosh44) [inline src/adapter/src/subscribe.rs:47]: Let's format this comment to match the other `bool` field `emit_progress`. I.e. "Whether ..."

File: src/adapter/src/coord/ddl.rs [hunk 6]
```diff
@@ -445,11 +452,29 @@ impl Coordinator {
     pub(crate) fn drop_compute_sinks(&mut self, sinks: impl IntoIterator<Item = ComputeSinkId>) {
         let mut by_cluster: BTreeMap<_, Vec<_>> = BTreeMap::new();
         for sink in sinks {
+            // Filter out sinks that have already been dropped.
+            //
+            // Note: Ideally we'd use .filter(...) on the iterator, but that would
+            // require simultaneously getting an immutable and mutable borrow of self
```
Comment (jkosh44) [inline src/adapter/src/coord/ddl.rs:458]: Somewhere in this function we should add a comment explaining that the sink is not removed from `active_subscribes` until we receive a remove message from compute which is why we need the `dropping` flag.

**Review by jkosh44 — COMMENTED** [review]
I just had a couple of small nits.

File: src/adapter/src/coord/ddl.rs (hunk 6 above)
Comment (parker-timmerman) [reply src/adapter/src/coord/ddl.rs:458]: Good idea, I extended this comment to include an explanation

File: src/adapter/src/subscribe.rs (hunk 5 above)
Comment (parker-timmerman) [reply src/adapter/src/subscribe.rs:47]: Done!

File: src/environmentd/tests/sql.rs (hunk 4 above)
Comment (parker-timmerman) [reply src/environmentd/tests/sql.rs:2481]: Added!

File: src/environmentd/tests/sql.rs (hunk 3 above)
Comment (parker-timmerman) [reply src/environmentd/tests/sql.rs:2483]: I tried that originally but it didn't work. Either the test would hang or I'd get an error, something about being inside of a transaction? FWIW the other uses for `batch_execute(...)` in this file also only have a single statement per function call

File: src/environmentd/tests/sql.rs (hunk 2 above)
Comment (parker-timmerman) [reply src/environmentd/tests/sql.rs:2467]: Good catch, at the time there wasn't, not sure why I had this haha

File: src/environmentd/tests/sql.rs (hunk 1 above)
Comment (parker-timmerman) [reply src/environmentd/tests/sql.rs:2456]: Good call, originally it seemed like the test was hanging until the SUBSCRIBE was dropped, which is why I moved it to a second thread. Moving everything back now and this works

**Review by mjibson — APPROVED** [review]
