### PR TITLE
sql: mark tail descriptors as nullable when PROGRESS is set

### LINKED ISSUE #6522: Debezium: "panic: explicit panic" in src/interchange/src/avro/envelope_debezium/deduplication.rs:317:18 when making a column NOT NULL
### What version of Materialize are you using?

```
materialized v0.7.3-dev (f7bdd05e3)
```

### What was the issue?

If a column is changed from NOT NULL to NULL-able on the Postgres side, the Mz side panics as follows:

```
2021-04-21T11:30:13.186440Z ERROR panic: explicit panic
thread: timely:work-0
location: src/interchange/src/avro/envelope_debezium/deduplication.rs:317:18
version: 0.7.3-dev (f7bdd05e39920a73fd2278dc43e75b3bef66399b)
backtrace:
   0: materialized::handle_panic
             at var/lib/buildkite-agent/builds/buildkite-builders-i-0038eccddeca969a0-1/materialize/tests/src/materialized/src/bin/materialized/main.rs:710:21
   1: core::ops::function::Fn::call
             at usr/local/lib/rustlib/src/rust/library/core/src/ops/function.rs:70:5
   2: std::panicking::rust_panic_with_hook
             at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   3: std::panicking::begin_panic::{{closure}}
             at usr/local/lib/rustlib/src/rust/library/std/src/panicking.rs:520:9
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at usr/local/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:141:18
   5: std::panicking::begin_panic
             at usr/local/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
   6: interchange::avro::envelope_debezium::deduplication::DebeziumDeduplicationState::should_use_record
             at var/lib/buildkite-agent/builds/buildkite-builders-i-0038eccddeca969a0-1/materialize/tests/src/interchange/src/avro/envelope_debezium/deduplication.rs:317:18
   7: interchange::avro::envelope_debezium::deduplication::DebeziumDeduplicationStrategy::render::{{closure}}::{{closure}}
             at var/lib/buildkite-agent/builds/buildkite-builders-i-0038eccddeca969a0-1/materialize/tests/src/interchange/src/avro/envelope_debezium/deduplication.rs:128:21
      core::option::Option<T>::map
             at usr/local/lib/rustlib/src/rust/library/core/src/option.rs:487:29
      interchange::avro::envelope_debezium::deduplication::DebeziumDeduplicationStrategy::render::{{closure}}
             at var/lib/buildkite-agent/builds/buildkite-builders-i-0038eccddeca969a0-1/materialize/tests/src/interchange/src/avro/envelope_debezium/deduplication.rs:125:30
      differential_dataflow::collection::Collection<G,D,R>::flat_map::{{closure}}
             at cargo/git/checkouts/differential-dataflow-d065d23d797aa027/adf4ac7/src/collection.rs:141:50
      <timely::dataflow::stream::Stream<S,D> as timely::dataflow::operators::map::Map<S,D>>::flat_map::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/b619080/timely/src/dataflow/operators/map.rs:79:83
      core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at usr/local/lib/rustlib/src/rust/library/core/src/ops/function.rs:280:13
   8: core::option::Option<T>::map
             at usr/local/lib/rustlib/src/rust/library/core/src/option.rs:487:29
      <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at usr/local/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:99:9
      <core::iter::adapters::fuse::Fuse<I> as core::iter::adapters::fuse::FuseImpl<I>>::next
             at usr/local/lib/rustlib/src/rust/library/core/src/iter/adapters/fuse.rs:420:9
      <core::iter::adapters::fuse::Fuse<I> as core::iter::traits::iterator::Iterator>::next
             at usr/local/lib/rustlib/src/rust/library/core/src/iter/adapters/fuse.rs:67:9
      <core::iter::adapters::flatten::FlattenCompat<I,U> as core::iter::traits::iterator::Iterator>::next
             at usr/local/lib/rustlib/src/rust/library/core/src/iter/adapters/flatten.rs:267:19
      <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
             at usr/local/lib/rustlib/src/rust/library/core/src/iter/adapters/flatten.rs:51:9
      timely::dataflow::channels::pushers::buffer::Session<T,D,P>::give_iterator
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/b619080/timely/src/dataflow/channels/pushers/buffer.rs:105:21
      <timely::dataflow::stream::Stream<S,D> as timely::dataflow::operators::map::Map<S,D>>::flat_map::{{closure}}::{{closure}}::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/b619080/timely/src/dataflow/operators/map.rs:79:17
      timely::dataflow::operators::generic::handles::InputHandle<T,D,P>::for_each
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/b619080/timely/src/dataflow/operators/generic/handles.rs:91:13
      <timely::dataflow::stream::Stream<S,D> as timely::dataflow::operators::map::Map<S,D>>::flat_map::{{closure}}::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/b619080/timely/src/dataflow/operators/map.rs:77:13
      <timely::dataflow::stream::Stream<G,D1> as timely::dataflow::operators::generic::operator::Operator<G,D1>>::unary::{{closure}}::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/b619080/timely/src/dataflow/operators/generic/operator.rs:402:17
      timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/b619080/timely/src/dataflow/operators/generic/builder_rc.rs:122:31
      timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/b619080/timely/src/dataflow/operators/generic/builder_rc.rs:161:26
      <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/b619080/timely/src/dataflow/operators/generic/builder_raw.rs:203:9
   9: timely::progress::subgraph::PerOperatorState<T>::schedule
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/b619080/timely/src/progress/subgraph.rs:684:30
  10: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/b619080/timely/src/progress/subgraph.rs:344:26
      <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/b619080/timely/src/progress/subgraph.rs:310:17
  11: timely::progress::subgraph::PerOperatorState<T>::schedule
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/b619080/timely/src/progress/subgraph.rs:684:30
  12: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/b619080/timely/src/progress/subgraph.rs:344:26
      <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/b619080/timely/src/progress/subgraph.rs:310:17
  13: timely::worker::Wrapper::step::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/b619080/timely/src/worker.rs:749:57
      core::option::Option<T>::map
             at usr/local/lib/rustlib/src/rust/library/core/src/option.rs:487:29
      timely::worker::Wrapper::step
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/b619080/timely/src/worker.rs:749:26
  14: timely::worker::Worker<A>::step_or_park
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/b619080/timely/src/worker.rs:396:38
  15: dataflow::server::Worker<A>::run
             at var/lib/buildkite-agent/builds/buildkite-builders-i-0038eccddeca969a0-1/materialize/tests/src/dataflow/src/server.rs:412:13
  16: dataflow::server::serve::{{closure}}
             at var/lib/buildkite-agent/builds/buildkite-builders-i-0038eccddeca969a0-1/materialize/tests/src/dataflow/src/server.rs:204:13
      timely::execute::execute::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/b619080/timely/src/execute.rs:285:22
      timely_communication::initialize::initialize_from::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/b619080/communication/src/initialize.rs:285:33
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at usr/local/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  17: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at usr/local/lib/rustlib/src/rust/library/std/src/thread/mod.rs:474:17
      <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at usr/local/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
      std::panicking::try::do_call
             at usr/local/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
      std::panicking::try
             at usr/local/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
      std::panic::catch_unwind
             at usr/local/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
      std::thread::Builder::spawn_unchecked::{{closure}}
             at usr/local/lib/rustlib/src/rust/library/std/src/thread/mod.rs:473:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at usr/local/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  18: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
  19: start_thread
  20: __clone
    
```

### Is the issue reproducible? If so, please provide reproduction instructions.

This test will cause the crash, provided that the postgres and mz sides have already been linked through Debezium.

The test is part of a new set of mzcompose-based Debezium tests that are being prepared, so there is no need to commit and push it independently.

```
$ postgres-execute connection=postgres://postgres:postgres@postgres
CREATE TABLE alter_allow_nullability (f1 INTEGER NOT NULL);
ALTER TABLE alter_allow_nullability REPLICA IDENTITY FULL;
INSERT INTO alter_allow_nullability VALUES (123),(234);

> CREATE MATERIALIZED SOURCE alter_allow_nullability
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'postgres.public.alter_allow_nullability'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
  ENVELOPE DEBEZIUM;

> SELECT * FROM alter_allow_nullability;
123
234

$ postgres-execute connection=postgres://postgres:postgres@postgres
ALTER TABLE alter_allow_nullability ALTER COLUMN f1 DROP NOT NULL;
INSERT INTO alter_allow_nullability VALUES (NULL);
UPDATE alter_allow_nullability SET f1 = 456 WHERE f1 = 123;
DELETE FROM alter_allow_nullability WHERE f1 = 234;

> SELECT * FROM alter_allow_nullability;
456
<null>
```

### PR DESCRIPTION
**Pull request by benesch**
Fix #6522.

@mjibson feel free to ditch this in favor of your work. I was fighting with the `RelationDesc` API a lot here.

### CODE REVIEW

File: src/repr/src/relation.rs [hunk 1]
```diff
@@ -253,16 +253,24 @@ impl RelationDesc {
         self
     }
 
-    /// Appends a named column with the specified column type.
-    pub fn with_column<N>(mut self, name: N, column_type: ColumnType) -> Self
+    /// Appends an optionally column with the specified column type.
```
Comment (mjibson) [inline src/repr/src/relation.rs:256]: "optionally named"

**Review by mjibson — APPROVED** [review]

File: src/repr/src/relation.rs (hunk 1 above)
Comment (benesch) [reply src/repr/src/relation.rs:256]: Blugh, thanks, fixed.

**Comment by benesch** [comment]
For posterity: this fixed #6304, not #6522. The original PR description mentioned the wrong issue.
