### PR TITLE
Deduplicate in detect_literal_constraints

### LINKED ISSUE #14548: Duplicates in `detect_literal_constraints` causing duplicate output
### What version of Materialize are you using?

f266c9c109e927e0047adafb3e856730ae1883ab

### How did you install Materialize?

Built from source

### What is the issue?

`SELECT a FROM t1 WHERE b IN ('l1', 'l2') AND (a > 0 OR a < 5)` has wrong results on the fast path when there is an index on `b`.

I have a fix, will open a PR shortly.

This is caught by the nightly-only slt `test/sqllogictest/sqlite/test/index/in/10/slt_good_0.test`.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by ggevay**
The first commit fixes #14548.

The second commit fixes a more tricky bug, which happens in `remove_literal_constraints` when there are contradicting literal constraints.

### Motivation

  * This PR fixes a recognized bug: #14548

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - No

### CODE REVIEW

File: src/transform/src/canonicalize_mfp.rs [hunk 1]
```diff
@@ -285,6 +315,92 @@ impl CanonicalizeMfp {
...
+            if let MirScalarExpr::CallVariadic {
+                func: VariadicFunc::And,
+                exprs: and_args,
+            } = or_arg
+            {
+                if Self::has_duplicates(and_args.clone()) {
+                    changed = true;
+                    and_args.sort();
+                    and_args.dedup();
+                }
```
Comment (wangandi) [inline src/transform/src/canonicalize_mfp.rs:348]: You might as well sort and dedup always and then compare the before to the after.

**Review by wangandi — APPROVED** [review]
Comments may be addressed after.

File: src/expr/src/scalar/mod.rs [hunk 2]
```diff
@@ -1395,10 +1417,8 @@ impl MirScalarExpr {
                     // then push back the result.
                     let mut undistribute_from = MirScalarExpr::CallVariadic {
                         func: (*outer_func).clone(),
-                        exprs: MirScalarExpr::swap_remove_multiple(
-                            outer_operands,
-                            indexes_to_undistribute,
-                        ),
+                        //exprs: MirScalarExpr::swap_remove_multiple(
```
Comment (wangandi) [inline src/expr/src/scalar/mod.rs:1420]: I think this line should be deleted.
