### PR TITLE
Fail fast when trying to create a file source from a directory

### LINKED ISSUE #4674: dataflow: on Linux hosts - able to create csv sources pointing to invalid locations
[mz@compute2 bin]$ uname -a
Linux compute2 4.18.0-193.el8.x86_64 #1 SMP Fri May 8 10:59:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

mz version - 0.5.0

materialize=> CREATE SOURCE "materialize"."public"."category12" ("category", "description") FROM FILE '/home/mz/src/flink-sql-demo' FORMAT CSV WITH 3 columns DELIMITED BY ','
;
CREATE SOURCE
materialize=> select * from category12 as of now();
ERROR: Source error: File IO: Is a directory (os error 21)

### PR DESCRIPTION
**Pull request by umanwizard**
fixes #4674

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4676)

### CODE REVIEW

**Review by benesch — APPROVED** [review]

File: src/sql/src/pure.rs [hunk 1]
```diff
@@ -66,8 +66,11 @@ pub async fn purify(mut stmt: Statement) -> Result<Statement, anyhow::Error> {
             }
             // Report an error if a file cannot be opened.
```
Comment (ruchirK) [inline src/sql/src/pure.rs:67]: super tiny nit but you may want to update this comment?
