### PR TITLE
Transform panic in `uint2` and `uint4` sums under invalid accumulations into SQL-level error

### LINKED ISSUE #17510: Panic on unsigned accumulable aggregation under invalid negative accumulations
A panic will result from aggregating `uint4` or smaller unsigned integer data when there are invalid negative accumulations due to too many retractions in a source.

The following reproduction of the error builds on `test/testdrive/negative-multiplicities.td` and requires us to run Materialize with `--unsafe-mode`. Note that the latter is required to make it easy to create the data with too many retractions; it is also possible to trigger the behaviors below if, e.g., too many retractions get into a source outside of unsafe mode.

First, set up the test data:

```sql
CREATE TABLE base (data uint4, diff bigint);
CREATE MATERIALIZED VIEW data AS SELECT data FROM base, repeat_row(diff);
INSERT INTO base VALUES (1, 1);
INSERT INTO base VALUES (1, -1), (1, -1);
```

Now, you should be able to observe the following:

```sql
materialize=> SELECT SUM(data) FROM data;
NOTICE:  cluster replica default.r1 changed status to "not-ready" at 2023-02-03 11:39:05.463023+00
HINT:  The cluster replica may be restarting or going offline.
NOTICE:  cluster replica default.r1 changed status to "ready" at 2023-02-03 11:39:10.468138+00
NOTICE:  cluster replica default.r1 changed status to "not-ready" at 2023-02-03 11:39:13.480973+00
HINT:  The cluster replica may be restarting or going offline.
^CCancel request sent
ERROR:  canceling statement due to user request
Time: 9546.821 ms (00:09.547)
materialize=> SELECT * FROM data;
NOTICE:  cluster replica default.r1 changed status to "ready" at 2023-02-03 11:39:18.487413+00
ERROR:  Invalid data in source, saw retractions (1) for row that does not exist: [UInt32(1)]
Time: 23.360 ms
```

The logs show the following:

```
thread 'timely:work-0' panicked at 'Invalid accumulated result -1 for unsigned function in dataflow temp-view-t2', src/compute/src/render/reduce.rs:1354:89
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: <differential_dataflow::operators::reduce::history_replay::HistoryReplayer<V1,V2,T,R1,R2> as differential_dataflow::operators::reduce::PerKeyCompute<V1,V2,T,R1,R2>>::compute
   3: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
   4: <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
   5: timely::progress::subgraph::PerOperatorState<T>::schedule
   6: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
   7: timely::progress::subgraph::PerOperatorState<T>::schedule
   8: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
   9: timely::progress::subgraph::PerOperatorState<T>::schedule
  10: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
  11: timely::worker::Wrapper::step
  12: timely::worker::Worker<A>::step_or_park
  13: mz_compute::server::Worker<A>::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
environmentd: 2023-02-03T11:39:05.463013Z ERROR mz_orchestrator_process: cluster-u1-replica-1-0 exited: ExitStatus(unix_wait_status(6)); relaunching in 5s
```

### PR DESCRIPTION
**Pull request by vmarcos**
This PR eliminates a panic raised when a sum aggregation of `uint2` or `uint4` is faced with a negative accumulation. Negative accumulations in reductions can arise due to, e.g., incomplete or invalid source data. The new strategy is to convert the invalid aggregation error into a query-level error instead of a panic by introduction of a map that performs appropriate casts and a projection. The change is carried out at the level of HIR-to-MIR lowering, since the casts may introduce errors and these will be later analyzed by transforms. Additionally, we give the optimizer the possibility to delay evaluation of the casts and projections to enable arrangement reuse. Finally, the PR adjusts the constant-folding behavior to output the same datum type as expected from rendering, thus making the casts sane in both evaluation alternatives.

Fixes #17510.

The approach taken in this PR is a specialized version of a more general approach advocated in a [design document](https://github.com/MaterializeInc/materialize/pull/17597). The PR fixes a panic while testing the waters for the more general implementation. The general implementation, to be pursued in a follow-up PR if the design document is approved, would eventually supersede the current change.

### Motivation

  * This PR fixes a recognized bug. https://github.com/MaterializeInc/materialize/issues/17510

### Tips for reviewer

The commits in this PR can be looked at individually. Note that we should be very careful here before pressing merge, since we want the output types produced by `uint2` and `uint4` aggregations to be exactly the same as before. That way, we do not have to write a migration of user data. I added a check to that effect in the regression test introduced in the PR.

An alternative take of to this PR is presented in #17682, where the casts and projection are introduced at the MIR-to-LIR lowering level. My preference is, however, to merge this PR instead of that alternative, since here we ensure that expressions that can error are analyzed properly and that arrangement reuse is maximized.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
N/A
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - Eliminated a replica crash when source data contained invalid retractions fed into unsigned sum aggregations.

### CODE REVIEW

File: src/expr/src/relation/mod.rs [hunk 1]
```diff
@@ -1194,12 +1194,56 @@ impl MirRelationExpr {
...
+        // needs to accumulate to a signed number to deal with retractions, and we do
+        // not want to panic there (#17510).
+        let unsigned_sums = aggregates
+            .iter()
+            .enumerate()
+            .filter(|(_, agg)| {
+                agg.func == AggregateFunc::SumUInt16 || agg.func == AggregateFunc::SumUInt32
+            })
+            .map(|(idx, _)| idx)
+            .collect::<Vec<_>>();
```
Comment (antiguru) [inline src/expr/src/relation/mod.rs:1208]: I think we can remove this `collect` and replace it by [`peekable`](https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html#method.peekable).

Comment (vmarcos) [reply src/expr/src/relation/mod.rs]: Sounds good, thanks!

File: test/cluster/mzcompose.py [hunk 2]
```diff
@@ -579,6 +580,91 @@ def workflow_test_github_15496(c: Composition) -> None:
...
+            ! SELECT SUM(data2) FROM data;
+            contains:uint8 out of range
+
+            ! SELECT SUM(data4) FROM data;
+            contains:uint8 out of range
+
+            # The following statement succeeds with a negative accumulation,
+            # which is the behavior introduced in https://github.com/MaterializeInc/materialize/pull/16852
+            > SELECT SUM(data8) FROM data;
+            -1
```
Comment (teskje) [inline test/cluster/mzcompose.py:661]: I find this behavior confusing. Should/can we change it to be in line with the smaller integer types (i.e. return an error)?

File: test/cluster/mzcompose.py [hunk 3]
```diff
@@ -579,6 +580,91 @@ def workflow_test_github_15496(c: Composition) -> None:
...
+
+            # Ensure that the output types for uint sums are unaffected.
+            > SELECT c.name, c.type
+              FROM mz_materialized_views mv
+                   JOIN mz_columns c USING (id)
+              WHERE mv.name = 'sum_types'
+              ORDER BY c.type, c.name;
+            sum8 numeric
+            sum2 uint8
+            sum4 uint8
```
Comment (teskje) [inline test/cluster/mzcompose.py:683]: Do you know why the output type of a `uint2` sum is `uint8` and not `uint4`?

([The docs](https://materialize.com/docs/sql/functions/) make it seem like it should be `uint2`: "Returns `bigint` if `x` is `int`, `numeric` if `x` is `bigint`, else returns same type as x.")

File: src/expr/src/relation/func.rs [hunk 4]
```diff
@@ -473,7 +473,7 @@ where
     if datums.peek().is_none() {
         Datum::Null
     } else {
-        let x: u64 = datums.map(|d| u64::from(d.unwrap_uint32())).sum();
+        let x: u128 = datums.map(|d| u128::from(d.unwrap_uint32())).sum();
         Datum::from(x)
     }
 }
```
Comment (teskje) [inline src/expr/src/relation/func.rs:479]: Correct me if I'm wrong, but with this PR, we will:
* Error on negative/invalid unsigned accumulations.
* Error on unsigned accumulations that overflows.
* Wrap around on signed accumulations that underflow.
* Wrap around on signed accumulations that overflow.

Is it right that our overflow behavior is different for signed (wrap around) vs unsigned (error) integers?

File: src/expr/src/relation/mod.rs [hunk 5]
```diff
@@ -1194,12 +1194,58 @@ impl MirRelationExpr {
...
+        let mut unsigned_sums = aggregates
+            .iter()
+            .enumerate()
+            .filter(|(_, agg)| {
+                agg.func == AggregateFunc::SumUInt16 || agg.func == AggregateFunc::SumUInt32
+            })
+            .map(|(idx, _)| idx)
+            .peekable();
+        if unsigned_sums.peek().is_some() {
+            let unsigned_sums = unsigned_sums.collect::<Vec<_>>();
```
Comment (teskje) [inline src/expr/src/relation/mod.rs:1210]: Nit: I usually annotate the variable with a type instead of using the turbofish, if convenient.
```rust
let unsigned_sums: Vec<_> = unsigned_sums.collect();
```

I think that improves readability, but I realize that this might be subjective.

File: test/cluster/mzcompose.py (hunk 2 above)
Comment (vmarcos) [reply test/cluster/mzcompose.py:660]: If we decide to go ahead with what is outlined in [the design document](https://github.com/MaterializeInc/materialize/pull/17597) we discussed recently, then we could, since we'd be able to communicate that there was an invalid accumulation error coming out of the reduction. I tried to revise the text of the design document [here](https://github.com/vmarcos/materialize/blob/17178_design/doc/developer/design/20230209_invalid_accumulations.md#details-for-category-2-errors) also with the observation that this PR is an intermediate step, but one that already allows us to not have the panic on `uint2` and `uint4` aggregations.

File: test/cluster/mzcompose.py (hunk 3 above)
Comment (vmarcos) [reply test/cluster/mzcompose.py:682]: I do not know, but the PR is trying to keep with the existing behavior. Perhaps @jkosh44 can clarify (not today, of course) why this behavior was adopted in the first place? It might be that the intention was to use a wide enough accumulator to avoid overflows in most practical situations?

(Regardless of the original reason, perhaps the documentation needs to reflect the behavior as it is implemented?)

File: src/expr/src/relation/func.rs (hunk 4 above)
Comment (vmarcos) [reply src/expr/src/relation/func.rs:479]: The PR is trying to align the sum behavior under constant folding for `uint2` and `uint4` with the rendering behavior. Previously, we'd accumulate in an `i128` in rendering, then panic if it was outside of the range of a `u64`; however, AFAICT the code would wrap around in a release build under constant folding. So now, we error consistently in both situations.

I am not trying at all to make any changes here to signed behavior, but I'd be happy to discuss what would make sense within the scope of this PR and what would make sense to revisit as follow-up issues. Generally speaking, rendering now will use an `i128` accumulator for all signed integer types. Later, the result is subjected to an `as` conversion to `i64` for sums of `smallint` and `int`, while a `numeric` result is returned for sums of `bigint`. The constant-folding behavior, by contrast, is to use a `sum` over `i64`s for the smaller integer types, which potentially wraps around in release builds. I don't think these two implementations will produce consistent results if the exact same input is represented in, say, a table or as a constant in the query.

Putting aside the differences in constant-folding vs. rendered behavior, we can also ask ourselves if we'd like to have as an outcome that sums wrap around for some types. Not sure what the answer should be here, but I have a feeling that the above might merit a separate issue?

File: src/expr/src/relation/mod.rs (hunk 5 above)
Comment (vmarcos) [reply src/expr/src/relation/mod.rs]: I am pretty spoiled by type annotations in VS Code with rust-analyzer; by changing to the variable annotation, I actually lose some ease of access to the type information in the VS Code rendering, since the variable is no longer directly annotated with its complete type. But I am happy to change to the style you suggest; I saw you were using it in a few other parts of the code, and it's better to keep consistency. Done now!

Comment (teskje) [reply src/expr/src/relation/mod.rs]: I'd argue that it is a failing of rust-analyzer (or the VS Code interface for it) to give up entirely on showing the type when it is partially annotated! But that's a good call out. I'm not using inline type annotations, so I didn't notice this.

File: src/expr/src/relation/func.rs (hunk 4 above)
Comment (teskje) [reply src/expr/src/relation/func.rs:479]: I agree, solving this is definitely out of scope for this PR and probably warrants a design doc!

I *think* in general we'd want to do what postgres does. I don't actually know what it does, but if it wraps around, then we should do so too, rather than erroring, IMO. But regardless of what we decide it would be great if we'd wind up with a good understanding of what the correct behavior should be in each case.

Comment (vmarcos) [reply src/expr/src/relation/func.rs:479]: I created this issue for follow-up work: https://github.com/MaterializeInc/materialize/issues/17758. @jkosh44 may correct me if I'm wrong, but I believe that PostgreSQL will wrap around on signed integer types (https://www.postgresql.org/message-id/3888640A.62BF764E@sferacarta.com) and that it simply does not support unsigned integer types (https://www.postgresql.org/docs/current/datatype-numeric.html) at present.

File: test/cluster/mzcompose.py (hunk 3 above)
Comment (jkosh44) [reply test/cluster/mzcompose.py:682]: This is to match the behavior of signed integers in PostgreSQL.

```
postgres=# CREATE TABLE t (a int2, b int4, c int8);
CREATE TABLE
postgres=# SELECT pg_typeof(sum(a)), pg_typeof(sum(b)), pg_typeof(sum(c)) FROM t;
 pg_typeof | pg_typeof | pg_typeof 
-----------+-----------+-----------
 bigint    | bigint    | numeric
(1 row)
```

You can also see the return types in the documentation: https://www.postgresql.org/docs/current/functions-aggregate.html.

I never really looked into the PostgreSQL rationale for these return types, but @vmarcos's guess sounds reasonable to me.

The docs are definitely wrong though, I can open a separate PR to fix that.

File: src/expr/src/relation/func.rs (hunk 4 above)
Comment (jkosh44) [reply src/expr/src/relation/func.rs:479]: I'm actually not familiar with the PostgreSQL behavior here. Though I agree that we can leave this out of scope for this PR.

File: src/expr/src/relation/func.rs [hunk 6]
```diff
@@ -460,7 +460,7 @@ where
     if datums.peek().is_none() {
         Datum::Null
     } else {
-        let x: u64 = datums.map(|d| u64::from(d.unwrap_uint16())).sum();
+        let x: u128 = datums.map(|d| u128::from(d.unwrap_uint16())).sum();
```
Comment (jkosh44) [inline src/expr/src/relation/func.rs:463]: We might want comments here saying that the value is cast down to a `u64` as part of `reduce`. Though, I'm not sure if that would be too noisy, up to you.

File: test/cluster/mzcompose.py [hunk 7]
```diff
@@ -579,6 +580,124 @@ def workflow_test_github_15496(c: Composition) -> None:
...
+                    COMPUTE ADDRESSES ['clusterd_nopanic:2102'],
+                    WORKERS 2
+                )
+            );
+            -- Set data for test up
+            SET cluster = cluster1;
+            CREATE TABLE base (data2 uint2, data4 uint4, data8 uint8, diff bigint);
+            CREATE MATERIALIZED VIEW data AS
+              SELECT data2, data4, data8
+              FROM base, repeat_row(diff);
```
Comment (jkosh44) [inline test/cluster/mzcompose.py:624]: Is `repeat_row` a Materialize specific function? I couldn't find any info on it for PostgreSQL.

**Review by jkosh44 — APPROVED** [review]
The behavior here seems strictly better than panicking, but it still feels very weird/wrong that we allow tables to get into a state where you can't read from them. Do we have a follow issue anywhere?

File: test/cluster/mzcompose.py (hunk 7 above)
Comment (vmarcos) [reply test/cluster/mzcompose.py:624]: Yes, it is a Materialize-specific function that we can use behind `--unsafe-mode` to control row multiplicities. It is quite handy for testing. It is otherwise a bit tricky to produce too many retractions, for example (though the same effect can be achieved with some source / envelope combinations).

File: src/expr/src/relation/func.rs (hunk 6 above)
Comment (vmarcos) [reply src/expr/src/relation/func.rs:463]: Absolutely, better to make things as clear as possible. Comments added!

**Comment by vmarcos** [comment]
> The behavior here seems strictly better than panicking, but it still feels very weird/wrong that we allow tables to get into a state where you can't read from them. Do we have a follow issue anywhere?

Are you concerned about `repeat_row`? It is gated behing `--unsafe-mode`, so hopefully not posing a risk. We can already get sources in a state where a `SELECT * FROM source` query will fail when they have too many retractions for a row. But things can be fixed if the source data is repaired.

**Comment by jkosh44** [comment]
> > The behavior here seems strictly better than panicking, but it still feels very weird/wrong that we allow tables to get into a state where you can't read from them. Do we have a follow issue anywhere?
> 
> Are you concerned about `repeat_row`? It is gated behing `--unsafe-mode`, so hopefully not posing a risk. We can already get sources in a state where a `SELECT * FROM source` query will fail when they have too many retractions for a row. But things can be fixed if the source data is repaired.

Yeah, knowing that `repeat_row` is unsafe makes me feel a lot better. As long as it's not easy to get into this kind of state, that's fine with me.

**Comment by umanwizard** [comment]
I am not sure if `repeat_row` is even needed anymore. IIRC it was added way back when for the original "source orthogonality" project (planning source envelopes as MIR), which has almost all been reverted. Grepping the codebase, it doesn't seem like it's being used anywhere.

**Comment by vmarcos** [comment]
> I am not sure if `repeat_row` is even needed anymore. IIRC it was added way back when for the original "source orthogonality" project (planning source envelopes as MIR), which has almost all been reverted. Grepping the codebase, it doesn't seem like it's being used anywhere.

I found it being used in a few places under `test`. Perhaps it is no longer needed for core functionality, but it makes it a lot easier to write some kinds of tests!

**Review by teskje — APPROVED** [review]
