### PR TITLE
sql: add support for 'epoch' shorthand

### LINKED ISSUE #1805: Materialize can't handle`SELECT TIMESTAMP 'epoch'`
```
materialized encountered an internal error and crashed.

We rely on bug reports to diagnose and fix these errors. Please
copy and paste the following details and mail them to bugs@materialize.io.
To protect your privacy, we do not collect crash reports automatically.

 thread: <unnamed>
message: index out of bounds: the len is 0 but the index is 0
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at /Users/Test/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.42/src/backtrace/mod.rs:66
   1: backtrace::backtrace::trace
             at /Users/Test/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.42/src/backtrace/mod.rs:53
   2: backtrace::capture::Backtrace::create
             at /Users/Test/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.42/src/capture.rs:164
   3: backtrace::capture::Backtrace::new
             at /Users/Test/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.42/src/capture.rs:128
   4: materialized::handle_panic
             at src/materialized/bin/materialized.rs:223
   5: core::ops::function::Fn::call
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/ops/function.rs:69
   6: std::panicking::rust_panic_with_hook
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:468
   7: std::panicking::continue_panic_fmt
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:373
   8: _rust_begin_unwind
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:302
   9: core::panicking::panic_fmt
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/panicking.rs:139
  10: core::panicking::panic_bounds_check
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/panicking.rs:96
  11: <usize as core::slice::SliceIndex<[T]>>::index
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/slice/mod.rs:2796
  12: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/slice/mod.rs:2647
  13: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/vec.rs:1861
  14: sql_parser::parser::datetime::build_parsed_datetime_timestamp
             at src/sql-parser/src/parser/datetime.rs:45
  15: sql_parser::parser::Parser::parse_timestamp_string
             at src/sql-parser/src/parser.rs:1023
  16: sql_parser::parser::Parser::parse_timestamp_inner
             at src/sql-parser/src/parser.rs:602
  17: sql_parser::parser::Parser::parse_timestamp
             at src/sql-parser/src/parser.rs:590
  18: sql_parser::parser::Parser::parse_prefix
             at src/sql-parser/src/parser.rs:254
  19: sql_parser::parser::Parser::parse_subexpr
             at src/sql-parser/src/parser.rs:214
  20: sql_parser::parser::Parser::parse_expr
             at src/sql-parser/src/parser.rs:208
  21: sql_parser::parser::Parser::parse_select_item
             at src/sql-parser/src/parser.rs:2748
  22: core::ops::function::FnMut::call_mut
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/ops/function.rs:152
  23: sql_parser::parser::Parser::parse_comma_separated
             at src/sql-parser/src/parser.rs:1356
  24: sql_parser::parser::Parser::parse_select
             at src/sql-parser/src/parser.rs:2306
  25: sql_parser::parser::Parser::parse_query_body
             at src/sql-parser/src/parser.rs:2240
  26: sql_parser::parser::Parser::parse_query
             at src/sql-parser/src/parser.rs:2179
  27: sql_parser::parser::Parser::parse_statement
             at src/sql-parser/src/parser.rs:161
  28: sql_parser::parser::Parser::parse_sql
             at src/sql-parser/src/parser.rs:146
  29: sql::parse
             at src/sql/lib.rs:144
  30: coord::coord::Coordinator<C>::handle_parse
             at src/coord/coord.rs:1672
  31: coord::coord::Coordinator<C>::serve::{{closure}}
             at src/coord/coord.rs:397
  32: tokio::runtime::context::enter
             at /Users/Test/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.10/src/runtime/context.rs:72
  33: tokio::runtime::handle::Handle::enter
             at /Users/Test/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.10/src/runtime/handle.rs:34
  34: coord::coord::Coordinator<C>::serve
             at src/coord/coord.rs:292
  35: materialized::serve::{{closure}}
             at src/materialized/lib.rs:265
  36: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/sys_common/backtrace.rs:129
  37: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/mod.rs:469
  38: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panic.rs:317
  39: std::panicking::try::do_call
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:287
  40: ___rust_maybe_catch_panic
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libpanic_unwind/lib.rs:78
  41: std::panicking::try
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:265
  42: std::panic::catch_unwind
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panic.rs:396
  43: std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/mod.rs:468
  44: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/ops/function.rs:227
  45: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/boxed.rs:942
  46: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/boxed.rs:942
  47: __pthread_body
  48: __pthread_start
```

### PR DESCRIPTION
**Pull request by sploiselle**
@quodlibetor I wanted to add something more obviously extensible here, but Clippy was mad about it, so I went with a janky `if`. Once we get infinity support in chronotope, I'll implement the infinity keyword, as well.

Fix #1805

### CODE REVIEW

File: src/repr/scalar/strconv.rs [hunk 1]
```diff
@@ -148,12 +148,25 @@ fn parse_timestamp_string(s: &str) -> Result<(NaiveDate, NaiveTime, &str), failu
...
+    // PostgreSQL special date-time inputs
+    // https://www.postgresql.org/docs/12/datatype-datetime.html#id-1.5.7.13.18.8
+    // We should add support for other values here, e.g. infinity
+    // which @quodlibetor is willing to add to the chrono package.
+    if s == "epoch" {
+        return Ok((
+            NaiveDate::from_ymd(1970, 1, 1),
+            NaiveTime::from_hms(0, 0, 0),
+            "",
+        ));
```
Comment (benesch) [inline src/repr/scalar/strconv.rs]: Extensibility is overrated. This is simple and correct and therefore great!

File: test/sqllogictest/dates-times.slt [hunk 2]
```diff
@@ -832,3 +832,15 @@ query T
...
 ----
 2007-02-01 09:04:05+00
+
+# Test special date-timme inputs from Postgres
+
+query T
+SELECT 'epoch'::timestamp
+----
+1970-01-01 00:00:00
+
```
Comment (benesch) [inline test/sqllogictest/dates-times.slt]: Can you add a test for tstz as well?

Comment (sploiselle) [reply test/sqllogictest/dates-times.slt]: Does the `slt` client run in UTC?
