### PR TITLE
[kafka sink] Retry message send failures

### LINKED ISSUE #10755: sinks: Attempting to write to a missing Kafka broker floods the log with 1 message per record
### What version of Materialize are you using?

v0.20.1-dev (2d4e62eea)

### How did you install Materialize?

Built from source

### What was the issue?

If the Kafka broker is unavailable for a Kafka sink to write into, the log is flooded with messages, 1 message per record, and we may have any number of those.

To reproduce:

1. Clone https://github.com/philip-stoev/materialize.git , branch `gh10755-test`
2. Run `bin/mzcompose --find gh10755 run default`
3. Wait 30 secs for the log to be flooded:
```
docker logs gh10755-materialized_1 2>&1 | wc
110675 2212963 22478384
```

### Relevant log output

```source
2022-02-18T11:21:48.425791Z ERROR mz_dataflow::sink::kafka: received error while writing to kafka sink topic testdrive-wide-data-1645183168: Message production error: MessageTimedOut (Local: Message timed out)
2022-02-18T11:21:48.425803Z ERROR mz_dataflow::sink::kafka: received error while writing to kafka sink topic testdrive-wide-data-1645183168: Message production error: MessageTimedOut (Local: Message timed out)
2022-02-18T11:21:48.425806Z ERROR mz_dataflow::sink::kafka: received error while writing to kafka sink topic testdrive-wide-data-1645183168: Message production error: MessageTimedOut (Local: Message timed out)
2022-02-18T11:21:48.425808Z ERROR mz_dataflow::sink::kafka: received error while writing to kafka sink topic testdrive-wide-data-1645183168: Message production error: MessageTimedOut (Local: Message timed out)
2022-02-18T11:21:48.425810Z ERROR mz_dataflow::sink::kafka: received error while writing to kafka sink topic testdrive-wide-data-1645183168: Message production error: MessageTimedOut (Local: Message timed out)
2022-02-18T11:21:48.425813Z ERROR mz_dataflow::sink::kafka: received error while writing to kafka sink topic testdrive-wide-data-1645183168: Message production error: MessageTimedOut (Local: Message timed out)
2022-02-18T11:21:48.425815Z ERROR mz_dataflow::sink::kafka: received error while writing to kafka sink topic testdrive-wide-data-1645183168: Message production error: MessageTimedOut (Local: Message timed out)
2022-02-18T11:21:48.425817Z ERROR mz_dataflow::sink::kafka: received error while writing to kafka sink topic testdrive-wide-data-1645183168: Message production error: MessageTimedOut (Local: Message timed out)
2022-02-18T11:21:48.425819Z ERROR mz_dataflow::sink::kafka: received error while writing to kafka sink topic testdrive-wide-data-1645183168: Message production error: MessageTimedOut (Local: Message timed out)
2022-02-18T11:21:48.425821Z ERROR mz_dataflow::sink::kafka: received error while writing to kafka sink topic testdrive-wide-data-1645183168: Message production error: MessageTimedOut (Local: Message timed out)
2022-02-18T11:21:48.425824Z ERROR mz_dataflow::sink::kafka: received error while writing to kafka sink topic testdrive-wide-data-1645183168: Message production error: MessageTimedOut (Local: Message timed out)
2022-02-18T11:21:48.425826Z ERROR mz_dataflow::sink::kafka: received error while writing to kafka sink topic testdrive-wide-data-1645183168: Message production error: MessageTimedOut (Local: Message timed out)
2022-02-18T11:21:48.425828Z ERROR mz_dataflow::sink::kafka: received error while writing to kafka sink topic testdrive-wide-data-1645183168: Message production error: MessageTimedOut (Local: Message timed out)
2022-02-18T11:21:48.425830Z ERROR mz_dataflow::sink::kafka: received error while writing to kafka sink topic testdrive-wide-data-1645183168: Message production error: MessageTimedOut (Local: Message timed out)
2022-02-18T11:21:48.425832Z ERROR mz_dataflow::sink::kafka: received error while writing to kafka sink topic testdrive-wide-data-1645183168: Message production error: MessageTimedOut (Local: Message timed out)
2022-02-18T11:21:48.425834Z ERROR mz_dataflow::sink::kafka: received error while writing to kafka sink topic testdrive-wide-data-1645183168: Message production error: MessageTimedOut (Local: Message timed out)
```

### PR DESCRIPTION
**Pull request by cjubb39**
Attempt 2 to replace #10853 

There are two types of failures we can see when sending a message to rdkafka:
1. The `send` call itself.  This enqueues the message on a buffer to be sent later
2. The actual sending itself (which happens on a background thread)

We were handling (1) but not (2).  My current approach is to expand the responsibility of `KafkaSinkState::flush` to make sure that all messages are successfully sent.  This involves two new structures:
1. Retry queue: where the messages to be resent go after they are rejected
2. Tracking of outstanding message sends
We need both of these because the `ProducerContext::delivery` callback is made asynchronously after the message is successfully or unsuccessfully sent.  We need to be able to know when it's no longer possible to get more errors.

### Motivation
Fixes #10755 which alerted me to the fact that we didn't properly handle errors during the actual sending of a message.

### Checklist
- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Comment by philip-stoev** [comment]
The flood of error messages is now gone. I have scheduled an Antithesis run against this branch, will report when the results become available.

File: src/dataflow/src/sink/kafka.rs [hunk 1]
```diff
@@ -185,13 +185,58 @@ impl SinkMetrics {
...
+            q: VecDeque::new(),
+            outstanding_send_count: 0,
+        }
+    }
+    fn record_send(&mut self) {
+        self.outstanding_send_count += 1;
+    }
+    fn record_error(&mut self, msg: OwnedMessage) {
+        self.q.push_back(msg);
+        self.outstanding_send_count -= 1;
```
Comment (guswynn) [inline src/dataflow/src/sink/kafka.rs:213]: we could probably mark this struct as `!Sync`, as logically it cannot be used with a lock, but its not-`pub` so should be fine

File: src/dataflow/src/sink/kafka.rs [hunk 2]
```diff
@@ -210,14 +255,16 @@ impl ProducerContext for SinkProducerContext {
 
     fn delivery(&self, result: &DeliveryResult, _: Self::DeliveryOpaque) {
         match result {
-            Ok(_) => (),
-            Err((e, msg)) => {
+            Ok(_) => self.retry_manager.lock().unwrap().record_success(),
```
Comment (guswynn) [inline src/dataflow/src/sink/kafka.rs:258]: if you wanna avoid these unwraps, you can use `parking_lot` mutexes (but we should probably refactor and use them everywhere in the one big pr

File: src/dataflow/src/sink/kafka.rs [hunk 3]
```diff
@@ -185,13 +185,58 @@ impl SinkMetrics {
...
+    }
+    fn record_error(&mut self, msg: OwnedMessage) {
+        self.q.push_back(msg);
+        self.outstanding_send_count -= 1;
+    }
+    fn record_success(&mut self) {
+        self.outstanding_send_count -= 1;
+    }
+    fn sends_flushed(&mut self) -> bool {
+        self.outstanding_send_count == 0 && self.q.len() == 0
```
Comment (guswynn) [inline src/dataflow/src/sink/kafka.rs:219]: why do we need to check both of these?

File: src/dataflow/src/sink/kafka.rs [hunk 4]
```diff
@@ -626,6 +679,34 @@ impl KafkaSinkState {
...
 
     async fn flush(&self) -> KafkaResult<()> {
+        loop {
+            self.flush_inner().await?;
+            if {
+                let mut guard = self.retry_manager.lock().unwrap();
+                guard.sends_flushed()
+            } {
+                break;
+            }
```
Comment (guswynn) [inline src/dataflow/src/sink/kafka.rs:689]:
```suggestion
       self.flush_inner().await?;
        while !{
                let mut guard = self.retry_manager.lock().unwrap();
                guard.sends_flushed()
            } {
         self.flush_inner().await?;
```
Something like this might be cleaner? idk

**Comment by cjubb39** [comment]
@philip-stoev I'm going to merge since 1) you noticed the log messages going away, 2) I've broken out the task of implemented what was the flaky test from last attempt into a separate issue, 3) I'd like to have a couple days of this running in main so I can catch flakes and action them before I'm out again at the end of the week.

Please do let me know the results of the antithesis testing and I can follow-on with a fix / revert as might be necessary

**Comment by philip-stoev** [comment]
@cjubb39 fine with me. I just got back the Antithesis report for this PR and it looks like there are no branch-specific regressions.

**Comment by cjubb39** [comment]
great news! Thanks Philip
