### PR TITLE
adapter: support multi-valued settings

### LINKED ISSUE #6754: coord: search_path does not behave as in Postgres: wrong default, can not be modified, not used for CREATE
### What version of Materialize are you using?

```
materialized v0.7.4-dev (82ae64f89)
```

### What was the issue?

```search_path``` is not handled correctly in Materialize. In particular, the following does not work:

1. search path can not be changed

```
materialize=> set search_path to 'abc';
ERROR:  parameter "search_path" cannot be changed
```

2.  ```CREATE TABLE``` is supposed to create the table in the first schema of the search path. However, in Mz, the search path is:

```
materialize=> SHOW search_path;
               search_path               
-----------------------------------------
 mz_catalog, pg_catalog, public, mz_temp
```

and yet all the tables are created in the ```public``` schema by default.

3. The default for ```search_path``` is different from the Postgres default, where it is:
```
pstoev=# show search_path;
   search_path   
-----------------
 "$user", public
(1 row)
```

### PR DESCRIPTION
**Pull request by mjibson**
Postgres flattens SET vars into a string based on some of the var's flags, then each var is incharge of splitting it if desired. We can instead pass a `Vec<String>` and ignore flattening rules like whether to quote identifiers.

Fixes #6754

### Motivation

  * This PR adds a known-desirable feature.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - Improve the Postgres-compatibilty of the `search_path` session setting.

### CODE REVIEW

**Review by benesch — APPROVED** [review]
This is so good! Couldn't find any problems in a quick test. We should probably throw @philip-stoev at this, though.

File: src/sql-parser/tests/testdata/show [hunk 1]
```diff
@@ -347,77 +347,98 @@ SET a = b
...
+SET a = b, c, d
+=>
+SetVariable(SetVariableStatement { local: false, variable: Ident("a"), to: Values([Ident(Ident("b")), Ident(Ident("c")), Ident(Ident("d"))]) })
+
+parse-statement
+SET a = 1, '2', 3.0, four
+----
+SET a = 1, '2', 3.0, four
+=>
+SetVariable(SetVariableStatement { local: false, variable: Ident("a"), to: Values([Literal(Number("1")), Literal(String("2")), Literal(Number("3.0")), Ident(Ident("four"))]) })
```
Comment (philip-stoev) [inline src/sql-parser/tests/testdata/show:442]: Can you please add a test where the value itself contains any of the special characters in this context -- comma, single quote and double quote?

**Review by philip-stoev — APPROVED** [review]
Thank you, looks good except the missing test for special characters within the value.

**Review by jkosh44 — APPROVED** [review]
LGTM. Just to clarify, it's just the session vars that support lists but not the system vars? Does that match PostgreSQL or do we just not have any need to support lists for the system vars?

**Comment by mjibson** [comment]
> st to clarify, it's just the session vars that support lists but not the system vars? Does that match PostgreSQL or do we just not have any need to support lists for the system vars?

The test failure here is due to the removal of multi var support to system settings, which I believe was the motivation to add it in the first place, so I'm going to restore multi system settings in a revision of this PR.

**Comment by mjibson** [comment]
Update: this has gotten much harder because we persist the system settings to the stash as a `String` and parse them using the SET parser currently in the main branch that has a bunch of things that were removed in this PR. I think those now have to be added back to support the stash migration to a `Vec<String>` and then removed in a future release.

**Comment by benesch** [comment]
I think I see how to do it, but I don't think I can explain it without trying it. Let me take a stab at it.

**Comment by benesch** [comment]
> I think I see how to do it, but I don't think I can explain it without trying it. Let me take a stab at it.

Update: I prodded at this enough that I think see a path forward, but holding off on spending more time on my branch since @mjibson mentioned he's close!

**Comment by mjibson** [comment]
Phew, got some tests passing for system vars. Added a second commit that restores multi var settings for system vars (will be squished). Would appreciate a review of it since it directly affects the replica settings and I don't want to get it wrong. The intention was to keep the var API as taking multiple strings, and forcing any system settings that can only serialize as a string to do the parsing themselves (which I think is mostly/only launchdarkly).

File: src/sql/src/plan/statement/scl.rs [hunk 2]
```diff
@@ -43,16 +46,56 @@ pub fn plan_set_variable(
...
     Ok(Plan::SetVariable(SetVariablePlan {
-        name: variable.to_string(),
+        name: variable.into_string(),
         value,
         local,
     }))
 }
 
+/// Split a single string into what would be parsed by `SET v TO <string>` into
+/// multpile values.
```
Comment (jkosh44) [inline src/sql/src/plan/statement/scl.rs:61]: `multpile` -> `multiple`

File: src/sql/src/plan/statement/scl.rs [hunk 3]
```diff
@@ -43,16 +46,56 @@ pub fn plan_set_variable(
...
+pub fn parse_set_variable_value(value: &str) -> Result<Vec<String>, PlanError> {
```
Comment (jkosh44) [inline src/sql/src/plan/statement/scl.rs:62]: I think the `plan` module is a bit of an awkward place for this function, because as far as I can tell it's never used during planning. Not a huge deal though, if this is just the easiest place to put it for dependency reasons.

File: src/adapter/src/catalog/storage.rs [hunk 4]
```diff
@@ -1558,13 +1558,11 @@ impl<'a> Transaction<'a> {
     }
 
     /// Upserts persisted system configuration `name` to `value`.
-    pub fn upsert_system_config(&mut self, name: &str, value: &str) -> Result<(), Error> {
+    pub fn upsert_system_config(&mut self, name: &str, value: String) -> Result<(), Error> {
```
Comment (jkosh44) [inline src/adapter/src/catalog/storage.rs:1561]: If this doesn't exist already, then I think we should add some tests where we persist a multi-valued system configuration and then try and read it back after a restart and make sure nothings corrupted.

File: src/sql/src/plan.rs [hunk 5]
```diff
@@ -574,7 +582,8 @@ pub struct AlterSecretPlan {
 #[derive(Debug)]
 pub struct AlterSystemSetPlan {
     pub name: String,
-    pub value: SetVariableValue,
+    // If Some, the flattened SET values. If None, reset to default.
+    pub value: Option<String>,
```
Comment (jkosh44) [inline src/sql/src/plan.rs:586]: Do I understand the life-cycle of this value correctly?
1. During parsing, we parse this into a list of values.
2. During planning we flatten the list into a single string (or `None`).
3. During sequencing, as part of the catalog transaction, we persist the flattened value to the stash.
4. During sequencing, as part of the catalog transaction, we un-flatten the value and pass it to the catalog to update the in-memory state.

If that's true then it might be slightly cleaner to switch to something like this:
1. During parsing, we parse this into a list of values.
2. During planning we **_leave the value as a list_**.
3. During sequencing, as part of the catalog transaction, we **_flatten the list and_** persist the flattened value to the stash.
4. During sequencing, as part of the catalog transaction, we pass **_the list to_** the catalog to update the in-memory state.

That way we get the following benefits:
- `AlterSystemSetPlan` more closely resembles `SetVariablePlan`.
- We avoid an unnecessary un-flattening.

File: src/adapter/src/catalog/storage.rs [hunk 6]
```diff
@@ -1558,13 +1558,11 @@ impl<'a> Transaction<'a> {
...
         let key = ServerConfigurationKey {
             name: name.to_string(),
         };
-        let value = ServerConfigurationValue {
-            value: value.to_string(),
-        };
+        let value = ServerConfigurationValue { value };
```
Comment (jkosh44) [inline src/adapter/src/catalog/storage.rs:1565]: Another thing to consider would be to change `ServerConfigurationValue.name` to be `Vec<String>` instead of `String`. That way you'd never need to unflatten the values and your persisted values would more closely resemble what was actually passed to `SystemVars::set`.

I haven't thought too hard if that makes sense though and if it's even possible with migrations. Just thought I'd float the idea.

**Review by jkosh44 — COMMENTED** [review]
Couple of small nits and ideas, mainly I just want to make sure there's a test that tries to load multi-value system configs from the stash.

File: src/sql/src/plan/statement/scl.rs (hunk 3 above)
Comment (mjibson) [reply src/sql/src/plan/statement/scl.rs:62]: I also really don't like it here, but was not sure where to put it. This was the least bad spot I could find? One choice is the parser crate, but we try real hard to keep sql logic out of the parser.

Comment (mjibson) [reply src/sql/src/plan/statement/scl.rs:62]: Actually: this is only called from adapter, so it can move there.

File: src/adapter/src/catalog/storage.rs (hunk 6 above)
Comment (mjibson) [reply src/adapter/src/catalog/storage.rs:1565]: This was exactly my first implementation, but it fought too much with SynchronizedParameters and I think this is (for now) the better choice. We could still move to that in the future, but I don't think it's necessary for now. I've worked on this long enough I want to get the minimum improvement in first.

File: src/sql/src/plan.rs (hunk 5 above)
Comment (mjibson) [reply src/sql/src/plan.rs:586]: This description leaves out a few steps, which helps explain why the current API exists. We synchronize the system vars in the catalog from the stash, the bootstrap cli args, and launch darkly (https://github.com/MaterializeInc/materialize/blob/d0f12134ccc5193361c2a156ec57e821db100ca4/src/adapter/src/catalog.rs#L2740). Those APIs operate on `String`. I've tried to put the boundary on which things need to parse and flatten such that the lowest level SystemVar type itself gets a `[String]`, but most of the stuff above it is a `String`. There is perhaps a better way, but this way seems fine for now.

File: src/adapter/src/session/vars.rs [hunk 7]
```diff
@@ -1197,46 +1191,47 @@ impl SystemVars {
     /// 2. If `value` does not represent a valid [`SystemVars`] value for
     ///    `name`.
     pub fn is_default(&self, name: &str, value: &str) -> Result<bool, AdapterError> {
```
[the remark this answers is not in the document]
Comment (mjibson) [reply src/adapter/src/session/vars.rs:1193]: Agree, changed.

File: src/adapter/src/catalog/storage.rs (hunk 4 above)
Comment (mjibson) [reply src/adapter/src/catalog/storage.rs:1561]: Added.

**Comment by mjibson** [comment]
RFAL, made the suggested changes.

**Comment by benesch** [comment]
I'd like to take a look at this too if you don't mind! It'll be another day or two though.

**Review by jkosh44 — APPROVED** [review]
LGTM, excited to finally have multi-valued config variables!

**Comment by benesch** [comment]
A couple brief thoughts! Will dig in more tomorrow and Friday.

  * I'm _really_ excited you got this working. Huge to have something that passes tests a base.
  * I know you're probably 100% sick of this PR by now, but if you don't mind waiting another day or two, I think there are a few API improvements we can make that will meaningfully improve the future maintainability of this code. (I worry that if we don't make them now, while it's all fresh in our minds, we won't ever make them, because we'll page out the context, and then the next time we have to touch this code it'll be much more painful.) Happy to help iterate.
  * Exposing the `plan_set_variable_to` method from the planner feels weird. I think we want to do what PostgreSQL does, which is to have a `split_identifier_list` function exposed in the parser. I have an idea of how to do this. Give the `SetVariableValue` type a `value()` method that does the logic of extracting a string value from a variable value. Have `plan_set_variable_to` call the `value()` method. Have `parser::split_identifier_list` call lex, `parse_comma_separated(parse_set_variable_value)`, and `.value()` on the result. This will result in 95% logic sharing between `plan_set_variable_to` and `split_identifier_list`, while avoiding the weird error that exists in `parse_set_variable_value`.
  * The fact that `AlterSystemSetPlan` is not congruous with `SetVariablePlan` is odd. I think it should exactly match, even if the first thing the sequencer does with the `SetVariableValue` is to call `.to_ast_string_stable()` on it. 
  * The `vars` module API feels slightly askew. It seems like `is_default` might want to take a string instead of a slice? Need to think about this more, but I think I see a nice path forward here (with a little more typing). 

Sorry, that's a bit jumbled, but wanted to blat it down while it was fresh.

**Comment by benesch** [comment]
I'm going to push up a few commits to this PR. If we don't like them, can remove them!

File: src/adapter/src/catalog/storage.rs (hunk 6 above)
Comment (benesch) [reply src/adapter/src/catalog/storage.rs:1565]: I actually think that strings are the right long term design too, as that matches PostgreSQL. Variables are always serialized as a flat string, both in the catalog and in LaunchDarkly. They're only deserialized into native Rust types when you load them into a `SystemVars` or a `SessionVars`. Variables can be bools or floats or ints, and we're not trying to serialize _those_ as anything besides strings—so why would we treat string lists and ident lists specially? Lists are just another data type that can be represented easily as a flat string!

The fact that `SET` has dedicated syntax for lists is a weird special case—and I think this whole mess is much clearer if you think of `SET` as a weird special case.

**Comment by benesch** [comment]
Ended up being just one commit. PTAL and let me know what you think. Commit message below:

> **adapter,sql[-parser]: hammer out multi-value variable API**
> This commit improves upon the API used for multi-valued variables:
> 
>   * The `adapter` crate no longer relies on the `plan_set_variable_to`
>     method of the `sql` crate. Instead it uses a new
>     `parse_identifier_list` function from the `sql_parser` crate. This
>     is a clearer separation of responsibilities that avoids some awkward
>     `match` statements that had to handle impossible conditions.
> 
>   * All variable setting-adjacent methods (`Value::parse`, `Var::set`,
>     and `Var::is_default`) take the input value as a new `VarInput`
>     type. This type explicitly encodes whether a variable input is using
>     the flattened representation used by LaunchDarkly and the catalog,
>     or the list representation used by the `SET` statement. This
>     generally improves clarity, and in particular allows `Value::parse`
>     to distinguish between e.g. `SET "a, b"` and loading an on-disk
>     value of "a, b".
> 
>   * The `DateStyle` variable is adapted to use the new logic to
>     correctly accept `SET '"iso", "mdy"'`, as PostgreSQL does.

**Comment by benesch** [comment]
Urgh. The system parameter sync had a latent footgun that would prevent `Vec<Ident>` variables from roundtripping correctly. Pushed up another commit to address that, by having the LaunchDarkly sync use a Rust API with sane semantics, rather than trying to use `SHOW ALL` and `ALTER SYSTEM`.

**Review by mjibson — COMMENTED** [review]
LGTM

**Review by benesch — APPROVED** [review]
🙇🏽
