### PR TITLE
sql: Fix overflow when negating min ints

### LINKED ISSUE #14291: SQL: Negation and absolute value do not properly handle overflow
### What version of Materialize are you using?

`main`

### How did you install Materialize?

Built from source

### What is the issue?

Materialize does not properly handle overflow when performing negations and absolute value functions, which can result in a panic.

Materialize:
```
materialize=> SELECT abs(-32768::int2);
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!?> 

materialize=> SELECT - -32768::int2;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!?> 
```

Postgres:
```
postgres=# SELECT abs(-32768::int2);
ERROR:  smallint out of range
postgres=# SELECT - -32768::int2;
ERROR:  smallint out of range
```

The fix would be to go through the function implementations here: https://github.com/MaterializeInc/materialize/tree/main/src/expr/src/scalar/func/impls and switch all usages of `-` with `.checked_neg()` and `abs()` with `checked_abs()`.

### Relevant log output

```source
Abs Stack Trace:
thread 'coordinator' panicked at 'attempt to negate with overflow', /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/num/mod.rs:203:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:48:5
   3: core::num::<impl i16>::abs
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/num/int_macros.rs:2423:17
   4: mz_expr::scalar::func::impls::int16::abs_int16
             at ./src/expr/src/scalar/func/impls/int16.rs:38:9
   5: <mz_expr::scalar::func::impls::int16::AbsInt16 as mz_expr::scalar::func::EagerUnaryFunc>::call
             at ./src/expr/src/scalar/func/macros.rs:78:21
   6: <T as mz_expr::scalar::func::LazyUnaryFunc>::eval
             at ./src/expr/src/scalar/func.rs:3211:26
   7: mz_expr::scalar::func::UnaryFunc::eval
             at ./src/expr/src/scalar/func/macros.rs:258:41
   8: mz_expr::scalar::MirScalarExpr::eval
             at ./src/expr/src/scalar/mod.rs:1363:56
   9: mz_expr::scalar::MirScalarExpr::reduce::{{closure}}
             at ./src/expr/src/scalar/mod.rs:436:36
  10: mz_expr::scalar::MirScalarExpr::reduce::{{closure}}
             at ./src/expr/src/scalar/mod.rs:492:34
  11: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}
             at ./src/expr/src/visit.rs:662:13
  12: stacker::maybe_grow
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  13: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  14: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit
             at ./src/expr/src/visit.rs:654:9
  15: <T as mz_expr::visit::Visit>::visit_mut_pre_post_nolimit
             at ./src/expr/src/visit.rs:403:9
  16: mz_expr::scalar::MirScalarExpr::reduce
             at ./src/expr/src/scalar/mod.rs:444:13
  17: mz_transform::reduction::FoldConstants::action
             at ./src/transform/src/reduction.rs:163:21
  18: <mz_transform::reduction::FoldConstants as mz_transform::Transform>::transform::{{closure}}
             at ./src/transform/src/reduction.rs:45:13
  19: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}
             at ./src/expr/src/visit.rs:520:13
  20: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  21: stacker::maybe_grow
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  22: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  23: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  24: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post
             at ./src/expr/src/visit.rs:518:9
  25: <T as mz_expr::visit::Visit>::try_visit_mut_post
             at ./src/expr/src/visit.rs:323:9
  26: <mz_transform::reduction::FoldConstants as mz_transform::Transform>::transform
             at ./src/transform/src/reduction.rs:41:9
  27: <mz_transform::FuseAndCollapse as mz_transform::Transform>::transform
             at ./src/transform/src/lib.rs:259:13
  28: <mz_transform::Fixpoint as mz_transform::Transform>::transform
             at ./src/transform/src/lib.rs:163:21
  29: mz_transform::Optimizer::transform
             at ./src/transform/src/lib.rs:450:13
  30: mz_transform::Optimizer::optimize
             at ./src/transform/src/lib.rs:428:9
  31: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_peek::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:1937:22
  32: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  33: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_peek::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:1745:5
  34: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  35: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_plan::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:232:63
  36: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  37: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_plan::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:85:5
  38: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  39: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute_inner::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:450:78
  40: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  41: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute_inner::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:251:5
  42: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  43: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:248:61
  44: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  45: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:228:5
  46: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  47: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.35/src/instrument.rs:272:9
  48: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_command::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:62:38
  49: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  50: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_command::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:138:33
  51: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  52: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_command::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:135:5
  53: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  54: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_message::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:37:63
  55: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  56: mz_adapter::coord::Coordinator<S>::serve::{{closure}}
             at ./src/adapter/src/coord.rs:811:37
  57: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  58: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:54
  59: tokio::coop::with_budget::{{closure}}
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:102:9
  60: std::thread::local::LocalKey<T>::try_with
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/local.rs:445:16
  61: std::thread::local::LocalKey<T>::with
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/local.rs:421:9
  62: tokio::coop::with_budget
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:95:5
  63: tokio::coop::budget
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:72:5
  64: tokio::park::thread::CachedParkThread::block_on
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:31
  65: tokio::runtime::enter::Enter::block_on
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/enter.rs:151:13
  66: tokio::runtime::handle::Handle::block_on
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/handle.rs:296:9
  67: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./src/adapter/src/coord.rs:947:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)


Neg Stack Trace:
thread 'coordinator' panicked at 'attempt to negate with overflow', src/expr/src/scalar/func/impls/int16.rs:24:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:48:5
   3: mz_expr::scalar::func::impls::int16::neg_int16
             at ./src/expr/src/scalar/func/impls/int16.rs:24:9
   4: <mz_expr::scalar::func::impls::int16::NegInt16 as mz_expr::scalar::func::EagerUnaryFunc>::call
             at ./src/expr/src/scalar/func/macros.rs:78:21
   5: <T as mz_expr::scalar::func::LazyUnaryFunc>::eval
             at ./src/expr/src/scalar/func.rs:3211:26
   6: mz_expr::scalar::func::UnaryFunc::eval
             at ./src/expr/src/scalar/func/macros.rs:258:41
   7: mz_expr::scalar::MirScalarExpr::eval
             at ./src/expr/src/scalar/mod.rs:1363:56
   8: mz_expr::scalar::MirScalarExpr::reduce::{{closure}}
             at ./src/expr/src/scalar/mod.rs:436:36
   9: mz_expr::scalar::MirScalarExpr::reduce::{{closure}}
             at ./src/expr/src/scalar/mod.rs:492:34
  10: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}
             at ./src/expr/src/visit.rs:662:13
  11: stacker::maybe_grow
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  12: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  13: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit
             at ./src/expr/src/visit.rs:654:9
  14: <T as mz_expr::visit::Visit>::visit_mut_pre_post_nolimit
             at ./src/expr/src/visit.rs:403:9
  15: mz_expr::scalar::MirScalarExpr::reduce
             at ./src/expr/src/scalar/mod.rs:444:13
  16: mz_transform::reduction::FoldConstants::action
             at ./src/transform/src/reduction.rs:163:21
  17: <mz_transform::reduction::FoldConstants as mz_transform::Transform>::transform::{{closure}}
             at ./src/transform/src/reduction.rs:45:13
  18: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}
             at ./src/expr/src/visit.rs:520:13
  19: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  20: stacker::maybe_grow
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  21: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  22: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  23: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post
             at ./src/expr/src/visit.rs:518:9
  24: <T as mz_expr::visit::Visit>::try_visit_mut_post
             at ./src/expr/src/visit.rs:323:9
  25: <mz_transform::reduction::FoldConstants as mz_transform::Transform>::transform
             at ./src/transform/src/reduction.rs:41:9
  26: <mz_transform::FuseAndCollapse as mz_transform::Transform>::transform
             at ./src/transform/src/lib.rs:259:13
  27: <mz_transform::Fixpoint as mz_transform::Transform>::transform
             at ./src/transform/src/lib.rs:163:21
  28: mz_transform::Optimizer::transform
             at ./src/transform/src/lib.rs:450:13
  29: mz_transform::Optimizer::optimize
             at ./src/transform/src/lib.rs:428:9
  30: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_peek::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:1937:22
  31: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  32: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_peek::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:1745:5
  33: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  34: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_plan::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:232:63
  35: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  36: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_plan::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:85:5
  37: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  38: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute_inner::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:450:78
  39: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  40: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute_inner::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:251:5
  41: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  42: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:248:61
  43: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  44: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:228:5
  45: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  46: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.35/src/instrument.rs:272:9
  47: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_command::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:62:38
  48: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  49: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_command::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:138:33
  50: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  51: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_command::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:135:5
  52: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  53: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_message::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:37:63
  54: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  55: mz_adapter::coord::Coordinator<S>::serve::{{closure}}
             at ./src/adapter/src/coord.rs:811:37
  56: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  57: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:54
  58: tokio::coop::with_budget::{{closure}}
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:102:9
  59: std::thread::local::LocalKey<T>::try_with
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/local.rs:445:16
  60: std::thread::local::LocalKey<T>::with
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/local.rs:421:9
  61: tokio::coop::with_budget
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:95:5
  62: tokio::coop::budget
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:72:5
  63: tokio::park::thread::CachedParkThread::block_on
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:31
  64: tokio::runtime::enter::Enter::block_on
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/enter.rs:151:13
  65: tokio::runtime::handle::Handle::block_on
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/handle.rs:296:9
  66: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./src/adapter/src/coord.rs:947:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

### PR DESCRIPTION
**Pull request by jkosh44**
This commit fixes a panic when trying to negate the minimum value of
some integer type. Integer types are not symmetric with respect to
their positive and negative ranges. There is one more negative number
than positive numbers. Therefore, negating the minimum value of an
integer type will fail.

Fixes #14291

### Motivation
This PR fixes a recognized bug.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Comment by chaas** [comment]
Thanks for fixing this!

File: src/expr/src/scalar/func/impls/int16.rs [hunk 1]
```diff
@@ -20,8 +20,8 @@ use crate::EvalError;
 
 sqlfunc!(
     #[sqlname = "-"]
-    fn neg_int16(a: i16) -> i16 {
-        -a
+    fn neg_int16(a: i16) -> Result<i16, EvalError> {
```
Comment (mjibson) [inline src/expr/src/scalar/func/impls/int16.rs:23]: Whoa the `sqlfunc` macro handles fns that return or do not return errors? Neat.

**Review by mjibson — APPROVED** [review]
