### PR TITLE
sql: Restrict role attribute granting

### LINKED ISSUE #18960: Role without createdb/cluster permission can create roles with createdb/cluster permission
### What version of Materialize are you using?

 v0.53.0-dev (693f5d205)

### How did you install Materialize?

Built from source

### What is the issue?

```
psql postgres://mz_system:materialize@localhost:6877
mz_system=> alter system set enable_ld_rbac_checks to true;
ALTER SYSTEM
mz_system=> alter system set enable_rbac_checks to true;
ALTER SYSTEM
mz_system=> CREATE ROLE regress_role_limited_admin CREATEROLE;
CREATE ROLE
regression=> CREATE ROLE regress_role_limited;
CREATE ROLE
mz_system=> create database regression;
CREATE DATABASE
regression=> select * from mz_roles;
 id |  oid  |            name            | inherit | create_role | create_db | create_cluster
----+-------+----------------------------+---------+-------------+-----------+----------------
 s1 | 20007 | mz_system                  | t       | t           | t         | t
 s2 | 20008 | mz_introspection           | t       | f           | f         | f
 u5 | 20433 | regress_role_limited       | t       | f           | t         | f
 u2 | 20428 | regress_role_limited_admin | t       | t           | f         | f
(4 rows)

psql postgres://regress_role_limited_admin@localhost:6875/regression
regression=> CREATE ROLE regress_nosuch_createdb CREATEDB; -- Expected to fail!
CREATE ROLE
regression=> ALTER ROLE regress_role_limited CREATEDB; -- Expected to fail!
ALTER ROLE
```

In Postgres you require CREATEROLE and CREATEDB permissions to create another role with CREATEDB permissions. If this is an intentional difference we should document it at least: https://materialize.com/docs/sql/create-role/

Edit: Same with CREATECLUSTER. This also works on your own role, so as long as you have CREATEROLE, you have all permissions.

Part of https://github.com/MaterializeInc/materialize/issues/17983

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jkosh44**
In PostgreSQL v16 a role cannot grant an attribute to another role unless the grantor also has the attribute. For example, to execute `CREATE ROLE r1 CREATEDB` the executing roles needs the CREATEROLE and CREATEDB attributes.

This commit updates our role attribute logic to match PostgreSQL v16 logic.

Fixes #18960

### Motivation
This PR adds a known-desirable feature.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - This release makes the ability to grant attributes to roles more restrictive. A role must possess an attribute in order to grant it to another role.

### CODE REVIEW

File: src/adapter/src/rbac.rs [hunk 1]
```diff
@@ -347,6 +387,42 @@ impl fmt::Display for Attribute {
     }
 }
 
+fn attribute_err(unheld_attributes: Vec<Attribute>, plan: &Plan) -> Result<(), UnauthorizedError> {
+    if !unheld_attributes.is_empty() {
```
Comment (mjibson) [inline src/adapter/src/rbac.rs:391]: Super nit, more like a coding preference, so ignore if you like:

```
if unheld_attributes.is_empty() {
    return Ok(());
}
...
```

This pattern reduces overall indentation and IMO increases readability.
```

**Review by mjibson — APPROVED** [review]
