### PR TITLE
rbac: Fix mz_acl_item_contains_privilege

### LINKED ISSUE #21680: Inconsistent schema privileges
### What version of Materialize are you using?

v0.68.3 (27bfc107a)

### What is the issue?

When I check the for create privileges on a specific schema, it returns true:

```sql
SELECT
    s.id,
    s.name,
    d.id AS "databaseId",
    d.name AS "databaseName",
    has_schema_privilege(current_user, s.oid, 'CREATE')
        AS "hasCreatePrivilege"
FROM
    mz_catalog.mz_schemas AS s
        JOIN mz_catalog.mz_databases AS d ON d.id = s.database_id
ORDER BY s.name;

 id |  name  | databaseId | databaseName | hasCreatePrivilege
----+--------+------------+--------------+--------------------
 u3 | public | u1         | materialize  | t
```
But when I query for all schema privileges, I don't get any results:
```sql
SELECT *
FROM mz_internal.mz_show_my_schema_privileges
WHERE privilege_type = 'CREATE';

 grantor | grantee | database | name | privilege_type
---------+---------+----------+------+----------------
(0 rows)
```

### PR DESCRIPTION
**Pull request by jkosh44**
The implementation of mz_acl_item_contains_privilege was incorrectly
checking if the union of two aclmodes were empty instead of checking if
the intersection of two aclmodes were empty. Therefore, it was
incorrectly reporting true on many usages. This was also causing
functions that relied on mz_acl_item_contains_privilege for their
implementation to return the wrong result.

Fixes #21680

### Motivation
This PR fixes a recognized bug.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - Fix RBAC privilege functions.

### CODE REVIEW

File: src/sql/src/func.rs [hunk 1]
```diff
@@ -1686,46 +1686,50 @@ macro_rules! catalog_name_only {
...
+                                        mz_internal.mz_aclitem_grantee(privilege) = mz_roles.id
+                            WHERE
+                                mz_internal.mz_aclitem_grantee(privilege) = '{public_role}' OR pg_has_role($1, mz_roles.oid, 'USAGE')
+                        ),
+                        false
+                    )
+                    END
+                ",
+            )
+    }
```
Comment (jkosh44) [inline src/sql/src/func.rs:1732]: The only changes here are to put the actual variable name in-between the `{}` to make it easier to read. Hide whitespace for better viewing.

**Review by ParkMyCar — APPROVED** [review]
