### PR TITLE
storage: in upsert operator, fix hashing of previous and current updates

### LINKED ISSUE #14273: sources hang with no error if storaged uses --workers > 1
### What version of Materialize are you using?

e852e357c23043850cb235258048fd998079d664

### How did you install Materialize?

Docker image

### What is the issue?

If a storaged is started with --workers 2 , any attempts to select from a source will hang. The log has the stuff printed below.

To reproduce, clone https://github.com/MaterializeInc/materialize/pull/14272 and then run

```
bin/mzcompose --find testdrive run default testdrive.td
```

It works if `--workers 1` is passed to storaged:

```
bin/mzcompose --find testdrive run default --workers 1 testdrive.td
```

### Relevant log output

```source
compute-cluster-1-replica-1: 2022-08-17T08:59:20.334024Z  INFO mz_persist_client::r#impl::machine: snapshot s56d9b374-b447-4d42-ac9c-38fbdf380b12 as of Antichain { elements: [1660726744281] } not yet available for upper Antichain { elements: [1660726741001] } retrying in 16s
compute-cluster-1-replica-1: 2022-08-17T08:59:34.826653Z  INFO mz_persist_client::r#impl::machine: snapshot s56d9b374-b447-4d42-ac9c-38fbdf380b12 as of Antichain { elements: [1660726744281] } not yet available for upper Antichain { elements: [1660726741001] } retrying in 16s
```

### PR DESCRIPTION
**Pull request by aljoscha**
### Motivation

This is one of the issues that @philip-stoev discovered when trying to run CI with `workers > 1` (see #14273)

### Notes for reviewers

It's very important to hash the right thing. We have nested `Option` and `Result` here. And, for example, `Some(key).hashed()` is not the same as `key.hashed()`.

This change makes sure that we hash the same thing for both pervious updates and new updates.

Also: this problem was only showing up when trying to use upsert-style sources with multiple storaged workers.

Partially fixes #14273

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

File: src/storage/src/render/upsert.rs [hunk 1]
```diff
@@ -295,10 +294,23 @@ where
...
+    // updates.
+    //
+    // Also: this problem was only showing up when trying to use upsert-style
+    // sources with multiple storaged workers.
     let result_stream = stream.binary_frontier(
         &previous_ok.inner,
-        Exchange::new(move |DecodeResult { key, .. }| key.hashed()),
-        Exchange::new(|((key, _v), _t, _r)| Ok::<_, Infallible>(key).hashed()),
+        Exchange::new(move |DecodeResult { key, .. }| match key {
+            None => 0,
```
Comment (aljoscha) [inline src/storage/src/render/upsert.rs:310]: note: if we wanted to be fancy we could use sth like `source_id.hashed()` instead, but that would make this change bigger because I have to plumb that through.

**Comment by aljoscha** [comment]
@brennanvincent updated to be what you suggested

**Review by brennanvincent — APPROVED** [review]

**Comment by aljoscha** [comment]
ty!

**Comment by aljoscha** [comment]
@philip-stoev upsert sources should be fixed now

File: src/storage/src/render/upsert.rs [hunk 2]
```diff
@@ -295,10 +294,30 @@ where
...
+            // N.B. We make the expected type explicit here to make sure it
+            // cannot change by accident.
+            let key: &Option<Result<Row, DecodeError>> = key;
+            key.hashed()
+        }),
+        Exchange::new(|((key, _v), _t, _r)| {
+            // N.B.  We make the expected type explicit here to make sure it
+            // cannot change by accident.
+            let key: &Result<Row, DecodeError> = key;
+            Some(key).hashed()
```
Comment (guswynn) [inline src/storage/src/render/upsert.rs:319]: this is hashing a `Option<Result<Row, DecodeError>>` and a `Option<&Result<Row, DecodeError>`

I know they are the same because of https://doc.rust-lang.org/src/core/hash/mod.rs.html#944-949, but if you want to be even more clear you can `as_ref` the first one
