### PR TITLE
persist: asynchronously retract in filter_and_retract_future_updates()

### LINKED ISSUE #9123: persist: Kafka source permanently errored with "At least one input has no complete timestamps yet" if Mz killed within the --timestamp-frequency
### What version of Materialize are you using?

From the shell:

```
materialized v0.9.13-dev (9af55e568) 
```

### What was the issue?

If you kill Mz before the --timestamp-frequency tick has had the chance to happen, the source is permanently errored out after restart. 

Not reproducible without peristent kafka source. Not reproducible with low values of timestamp-frequency (naturally) or when persistent-user-tables is enabled(?)

### Is the issue reproducible? If so, please provide reproduction instructions.

1. Start Mz like this:
```
target/release/materialized --persistent-kafka-upsert-source --disable-persistent-system-tables-test  --experimental  --log-file=stderr 
```
2. Run
```
$ set-sql-timeout duration=5minutes
$ set keyschema={
    "type": "record",
    "name": "Key",
    "fields": [
        {"name": "f1", "type": "long"}
    ]
  }

$ set schema={
        "type" : "record",
        "name" : "test",
        "fields" : [
            {"name":"f1", "type":"long"}
        ]
    }

$ kafka-create-topic topic=s1

$ kafka-ingest format=avro topic=s1 key-format=avro key-schema=${keyschema} schema=${schema} publish=true repeat=100000
{"f1": ${kafka-ingest.iteration}} {"f1": ${kafka-ingest.iteration}}

> CREATE MATERIALIZED SOURCE s1
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-s1-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
  ENVELOPE UPSERT

$ kafka-ingest format=avro topic=s1 key-format=avro key-schema=${keyschema} schema=${schema} publish=true repeat=100000
{"f1": ${kafka-ingest.iteration}} {"f1": ${kafka-ingest.iteration}}
$ kafka-ingest format=avro topic=s1 key-format=avro key-schema=${keyschema} schema=${schema} publish=true repeat=100000
{"f1": ${kafka-ingest.iteration}} {"f1": ${kafka-ingest.iteration}}
```
3. Immediately kil Mz and restart it
4. Source is permanently errored out:
```
materialize=> select count(*) from s1;
ERROR:  At least one input has no complete timestamps yet: [User(2)]
```

### Please attach any applicable log files.

If everything works, post-restart the Mz output has lines like this
```
2021-11-17T08:08:29.093189Z  INFO dataflow::source::kafka: Activating Kafka queue for testdrive-s1-210 [0] (source u1/29) on worker 2    
2021-11-17T08:08:29.656995Z  INFO dataflow::source::kafka: Kafka message before expected offset, skipping: source kafka-u1/29 (reading topic testdrive-s1-210, partition 0) received offset 0 expected offset 300000    
2021-11-17T08:08:29.657089Z  WARN dataflow::source::kafka: Did not fast-forward consumer on partition PID: 0 to the correct Kafka offset. Currently at offset: 1 Expected offset: 300000    
```

If things do not work, the only line post-restart is:

```
2021-11-17T08:09:08.894105Z  INFO dataflow::source::kafka: Activating Kafka queue for testdrive-s1-220 [0] (source u1/29) on worker 2    
```
and that is it.

### PR DESCRIPTION
**Pull request by aljoscha**
Before, we would write retractions individually and block on the write.
This was very slow when retracting larger amounts.

Now, we instead write retractions in batches and asynchronously wait for
the write futures to complete, similarly to how we do it in the
`persist()` operator.

Fixes #9123

@philip-stoev What should I do about the test case? We change the `--timestamping-frequency` for all tests, so probably can't leave that as is. WDYT?

### Motivation

We want to fix the aforementioned #9123.

### Tips for reviewers

The code is almost the same as for `persist()`, except that persist, well, persists all messages and forwards all of them while this operator "persists" a retraction for messages that are not beyond the given filter timestamp and forwards the rest.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [N/A] This PR adds a release note for any
  [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Comment by philip-stoev** [comment]
@aljoscha please do not merge any portions of the test case / framework at this time. In a follow-up PR I will merge all the tests that I have, including a dedicated test for this particular issue.

**Comment by aljoscha** [comment]
Gotcha! I'll remove that commit then and merge once someone has reviewed.

File: src/persist/src/operators/stream.rs [hunk 1]
```diff
@@ -702,19 +709,73 @@ where
...
+                                    let error = format!(
+                                        "In {}, error writing data for time {}: {}",
+                                        &operator_name,
+                                        error_cap.time(),
+                                        e
+                                    );
+                                    log::error!("{}", error);
+
+                                    // TODO: make error retractable? Probably not...
+                                    session.give((error, *error_cap.time(), 1));
```
Comment (danhhz) [inline src/persist/src/operators/stream.rs:762]: if one of these fails, we need to permanently wedge the frontier from advancing, right? otherwise, we could see incorrect duplicates on restart

File: src/persist/src/operators/upsert.rs [hunk 2]
```diff
@@ -128,11 +128,12 @@ where
             let snapshot = persist_config.read_handle.snapshot();
             let (restored_oks, restored_errs) =
                 self.scope().replay(snapshot).ok_err(|x| split_ok_err(x));
-            let restored_upsert_oks = restored_oks.filter_and_retract_future_updates(
-                name,
-                persist_config.write_handle.clone(),
-                persist_config.upper_seal_ts,
-            );
+            let (restored_upsert_oks, _retract_errs) = restored_oks
```
Comment (danhhz) [inline src/persist/src/operators/upsert.rs:131]: i'm not a big fan of throwing away errors. it's unclear to me (as it is to everyone) what our error reporting story is, but is there some good reason we're not concat'ing them in here?

File: src/persist/src/operators/stream.rs (hunk 1 above)
Comment (aljoscha) [reply src/persist/src/operators/stream.rs:762]: Yes, which ties in with your [other comment](https://github.com/MaterializeInc/materialize/pull/9229#discussion_r755216901), right?

File: src/persist/src/operators/upsert.rs (hunk 2 above)
Comment (aljoscha) [reply src/persist/src/operators/upsert.rs]: I don't know what I was thinking here. :see_no_evil: In my other PR I'm expressly wiring through more error streams: https://github.com/MaterializeInc/materialize/pull/9246

Pushing a fix...

**Comment by ruchirK** [comment]
Sorry didn't get a chance to review this one today - will review tomorrow first thing

**Comment by ruchirK** [comment]
I think my lunch will arrive soon but will review this before and after lunch

File: src/persist/src/operators/stream.rs [hunk 3]
```diff
@@ -649,7 +649,10 @@ pub trait RetractFutureUpdates<G: Scope<Timestamp = u64>, K: TimelyData, V: Time
         name: &str,
         write: StreamWriteHandle<K, V>,
         upper_ts: u64,
-    ) -> Stream<G, ((K, V), u64, isize)>;
+    ) -> (
```
Comment (ruchirK) [inline src/persist/src/operators/stream.rs:652]: not this line but I think the comments on line 645 are now out of date?

File: src/persist/src/operators/stream.rs [hunk 4]
```diff
@@ -658,40 +661,44 @@ where
...
-            async_op!(|capabilities, _frontiers| {
-                // Drop initial capabilities
-                capabilities.clear();
+        // An activator that allows futures to re-schedule this operator when ready.
+        let activator = Arc::new(scope.sync_activator_for(&persist_op.operator_info().address[..]));
+
+        let mut pending_futures = VecDeque::new();
+
+        // Reusable buffer for collecting updates that we need to retract. We retract in batches in
+        // order to not make to many persist calls and keep to many write futures around.
```
Comment (ruchirK) [inline src/persist/src/operators/stream.rs:691]: super minor nit: "keep too many write futures around."

File: src/persist/src/operators/stream.rs [hunk 5]
```diff
@@ -702,19 +709,73 @@ where
...
+                    let write_future = write.write(&to_retract);
+                    to_retract.clear();
+
+                    // We are not using the capability for the main output later, but we are
+                    // holding on to it to keep the frontier from advancing because that frontier
+                    // is used downstream to track how far we have persisted. This is used, for
+                    // example, by upsert()/persist()/seal()/conditional_seal() operators
+                    // and await_frontier().
+                    pending_futures.push_back((
+                        cap.delayed(cap.time()),
```
Comment (ruchirK) [inline src/persist/src/operators/stream.rs:727]: Theres two things here that I don't totally get:

1. why are we delaying the cap to its time in line 727? My understanding is that that is a no-op. what am i missing?
2. why do we need to specifically retain the capability for the error output port? (I think there is probably a good reason, I just don't know what it is)

Comment (ruchirK) [reply src/persist/src/operators/stream.rs:727]: And then a 3rd, is this vulnerable to the same kind of issue we found in the conditional_seal operator, where holding onto a cap releases times up to the cap, even though the operation we are waiting on (in this case a write) maybe was not completed yet?

File: src/persist/src/operators/stream.rs (hunk 3 above)
Comment (aljoscha) [reply src/persist/src/operators/stream.rs:652]: Fixing!

File: src/persist/src/operators/stream.rs (hunk 5 above)
Comment (aljoscha) [reply src/persist/src/operators/stream.rs:727]: >  1. why are we delaying the cap to its time in line 727? My understanding is that that is a no-op. what am i missing?

It's to get around a restriction in the interface, `retain()` consumes `self` while `delayed()` takes a `&self`. But I need to have two capabilities.

>   2. why do we need to specifically retain the capability for the error output port? (I think there is probably a good reason, I just don't know what it is)

That's just how timely works, which I learned it the hard way. :sweat_smile: When you go and try to send something on an output that doesn't match the capability you will get a panic. (c.f. here's where that is checked: https://github.com/timelydataflow/timely-dataflow/blob/b619080c6c3d9ec249b2943d56ff4a2d8ce8e121/timely/src/dataflow/operators/generic/handles.rs#L220)

> And then a 3rd, is this vulnerable to the same kind of issue we found in the conditional_seal operator, where holding onto a cap releases times up to the cap, even though the operation we are waiting on (in this case a write) maybe was not completed yet?

I _think_ it is correct but I have been wrong before. My reasoning is this:

- With `seal`, letting the frontier progress to `t` signals that data with `t'` not beyond `t` can be processed downstream, So letting it advance to `t` before we have successfully written that seal to persistence is wrong.
- With `persist` (and its cousin _filter_and_retract_future_updates_, yes naming is not optimal...) holding the frontier at `t` while we write data at time `t` prevents the downstream frontier from advancing past `t`, which prevents downstream operators from working on the data. For example, `await_frontier()` will only release data with time `t` into the rest of dataflow once `t` is not beyond the frontier anymore.

In other words, `seal` has this "t+1-y" nature while `persist` has a "t-y" nature. Not sure that helps... I'm also partially hoping that you can understand this and convince me back. :sweat_smile:

Comment (ruchirK) [reply src/persist/src/operators/stream.rs:729]: gotcha. For 1. i was expecting to see `cap.retain()` or something like that but it makes sense given the current api why its not possible.

for 3. i think the point of confusion for me is that its not clear to me where the frontiers are and where the data is. I think your example suggests that when we write a batch of records with (data, time, diff), the frontier is held back to a time <= all the times for all the records we are writing, aka the writes are all not beyond the frontier we are stashing. I totally believe thats true, I just don't see where thats enforced. In contrast it seems like the seal frontier is somehow leading indicator -- I need to think about the distinction a bit more

Comment (aljoscha) [reply src/persist/src/operators/stream.rs:796]: For posterity: we discussed this "offline" and came to the conclusion that this should work.

Side information: in our case, it's the `replay()` operator that controls what capabilities are used for sending data and what (differential) timestamp they have.
