### PR TITLE
adapter: Update storage usage tables off task

### LINKED ISSUE #26172: Coordinator blocks on storage future for an unexpected amount of time
### What version of Materialize are you using?

v0.90.1, v0.91.0, v0.92.1

### What is the issue?

Running a [version](https://github.com/MaterializeInc/cloud/pull/8884) of the prometheus sql exporter modified to retry collection when a replica times out can cause environmentd to become unresponsive for up to several hours due to the coordinator blocking on a storage future.
So far this has only been reproduced in a personal cloud stack.

A synopsis of the details gathered so far:
>The time there is spent in group_commit_apply::append_fut which is awaiting the future returned from a call to storage.append_table.  This is in a blocking path in the coordinator, and so makes that env unresponsive

[slack](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1710306702498689)

```
     Image:         materialize/environmentd:v0.92.1                                                                                                               │
     Image ID:      docker.io/materialize/environmentd@sha256:3277ba1ef353f1fd87d584c2ca32f2bc0787d84a38786d768124d67c97c8444a
```
This occurs in a personal stack environment which has in many cases smaller resource requests for mz components, and could experience LD drift from what is set in staging and prod.

Relates to https://github.com/MaterializeInc/accounts/issues/58

### Traces
[Trace-1e712d-2024-03-21 14 25 32.json](https://github.com/MaterializeInc/materialize/files/14696650/Trace-1e712d-2024-03-21.14.25.32.json)
[Trace-00548a-2024-03-21 14 26 24.json](https://github.com/MaterializeInc/materialize/files/14696651/Trace-00548a-2024-03-21.14.26.24.json)
[Trace-e48528-2024-03-21 14 21 10.json](https://github.com/MaterializeInc/materialize/files/14696657/Trace-e48528-2024-03-21.14.21.10.json)

### PR DESCRIPTION
**Pull request by jkosh44**
Storage usage updates takes the following steps:

1. Collect new storage usage metrics.
2. Update the catalog with new metrics.
3. Update the builtin tables with new metrics.
4. Schedule the next storage usage collection.

Most expensive operations are run off of the main coordinator task. Previously, step (3), updating the builtin tables, happened on the main coordinator task. The storage usage updates can sometimes be huge and updating the builtin tables would end up blocking the main coord task for a long time. This commit mitigates this issue by running step (3) in an async task.

Resolves #26172

### Motivation
This PR fixes a recognized bug.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - There are no user-facing behavior changes.

### CODE REVIEW

File: src/adapter/src/coord/message_handler.rs [hunk 1]
```diff
@@ -275,10 +278,21 @@ impl Coordinator {
...
         }
 
-        if let Err(err) = self.catalog_transact(None::<&Session>, ops).await {
-            tracing::warn!("Failed to update storage metrics: {:?}", err);
+        match self.catalog_transact_inner(None, ops).await {
+            Ok(table_updates) => {
+                let internal_cmd_tx = self.internal_cmd_tx.clone();
+                task::spawn(|| "storage_usage_update_table_updates", async move {
+                    table_updates
+                        .instrument(info_span!("coord::storage_usage_update::table_updates"))
```
Comment (jkosh44) [inline src/adapter/src/coord/message_handler.rs:286]: I copied and pasted this line and don't understand it at all. So please let me know if this looks wrong.

Comment (jpepin) [reply src/adapter/src/coord/message_handler.rs:286]: This [appears](https://grafana.dev.materialize.com/explore?schemaVersion=1&panes=%7B%222qk%22:%7B%22datasource%22:%22c2718ff3-7d6c-493c-a9ec-214b5dd182ea%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22tempo%22,%22uid%22:%22c2718ff3-7d6c-493c-a9ec-214b5dd182ea%22%7D,%22queryType%22:%22traceqlSearch%22,%22limit%22:20,%22tableType%22:%22traces%22,%22filters%22:%5B%7B%22id%22:%228738c75f%22,%22operator%22:%22%3D%22,%22scope%22:%22span%22%7D,%7B%22id%22:%22service-name%22,%22tag%22:%22service.name%22,%22operator%22:%22%3D%22,%22scope%22:%22resource%22,%22value%22:%5B%22environmentd%22%5D,%22valueType%22:%22string%22%7D,%7B%22id%22:%22span-name%22,%22tag%22:%22name%22,%22operator%22:%22%3D%22,%22scope%22:%22span%22,%22value%22:%5B%22coord::storage_usage_update::table_updates%22%5D,%22valueType%22:%22string%22%7D%5D%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D,%22fk4%22:%7B%22datasource%22:%22c2718ff3-7d6c-493c-a9ec-214b5dd182ea%22,%22queries%22:%5B%7B%22query%22:%22c4a86ed9c72ccf5af8833942eeb1faf4%22,%22queryType%22:%22traceql%22,%22refId%22:%22A%22,%22limit%22:20,%22tableType%22:%22traces%22%7D%5D,%22range%22:%7B%22from%22:%221711054992809%22,%22to%22:%221711058592809%22%7D%7D%7D&orgId=1) as a new top-level trace with no parent spans. Is that what we'd expect from this change? I am not very familiar with this code, but [other spans](https://grafana.dev.materialize.com/explore?schemaVersion=1&panes=%7B%22zrt%22:%7B%22datasource%22:%22c2718ff3-7d6c-493c-a9ec-214b5dd182ea%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22tempo%22,%22uid%22:%22c2718ff3-7d6c-493c-a9ec-214b5dd182ea%22%7D,%22queryType%22:%22traceql%22,%22limit%22:20,%22tableType%22:%22traces%22,%22query%22:%22087e4b18a56f749940b0317f7500548a%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&orgId=1) I've looked at from this component had `coord::handle_message` and `storage_usage_update` etc as parent spans. Maybe @guswynn could help

Comment (guswynn) [reply src/adapter/src/coord/message_handler.rs:286]: We probably want this to a otel child (not a tracing child) of `storage_usage_update`, so we want something like:
```
let mut task_span = info_span!(parent: None, "coord::storage_usage_update::table_updates");
OpenTelemetryContext::obtain().attach_as_parent_to(&mut task_span)
mz_ore::spawn(..., async move { ... }.instrument(task_span)
```

we should probably makes some macros to make this easier!

**Comment by jkosh44** [comment]
Nightlies: https://buildkite.com/materialize/nightlies/builds/7001

File: src/adapter/src/coord/message_handler.rs (hunk 1 above)
Comment (jkosh44) [reply src/adapter/src/coord/message_handler.rs]: Update, thanks!

**Comment by jpepin** [comment]
Looks like the image build is [failing](https://buildkite.com/materialize/tests/builds/78920#018e633b-5657-4ce2-b80b-946d6d20c951) on `OpenTelemetryContext`? I can help test the tracing update once the image gets successfully built!

**Comment by jkosh44** [comment]
> Looks like the image build is [failing](https://buildkite.com/materialize/tests/builds/78920#018e633b-5657-4ce2-b80b-946d6d20c951) on `OpenTelemetryContext`? I can help test the tracing update once the image gets successfully built!

Oops, that's what I get for not testing my changes. Should be fixed now.

**Review by benesch — APPROVED** [review]

**Review by benesch — APPROVED** [review]
