### PR TITLE
persist: chunk up ColumnarRecords construction

### LINKED ISSUE #10071: panic: batch is smaller than 2GB: TryFromIntError(()) when trying to recover a 100M row upsert source
### What version of Materialize are you using?

version: 0.16.1-dev (856630255a9cbb54674073a15ad9cf7c21ed4ab7)

### How did you install Materialize?

Built from source

### What was the issue?

Attempting to recover Mz after ingesting 100M records results in the following:

```
2022-01-17T12:06:39.886273Z  INFO coord::timestamp: Discovered 8 new (8 total) kafka partitions for topic testdrive-kafka-recovery-big-1642420951 (source u1)
2022-01-17T12:06:40.255067Z  INFO dataflow::source::kafka: Activating Kafka queue for testdrive-kafka-recovery-big-1642420951 [5] (source u1/29) on worker 7
2022-01-17T12:08:17.920791Z ERROR panic: batch is smaller than 2GB: TryFromIntError(())
thread: persist:runtime
location: src/persist/src/indexed/columnar.rs:385:54
version: 0.16.1-dev (856630255a9cbb54674073a15ad9cf7c21ed4ab7)
backtrace:
   0: materialized::handle_panic
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0565c89823f7242c0-1/materialize/tests/src/materialized/src/bin/materialized/main.rs:842:21
   1: core::ops::function::Fn::call
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:70:5
   2: std::panicking::rust_panic_with_hook
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:628:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:521:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
   5: rust_begin_unwind
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   6: core::panicking::panic_fmt
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   7: core::result::unwrap_failed
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
   8: persist::indexed::columnar::ColumnarRecordsBuilder::push
   9: <persist::indexed::columnar::ColumnarRecords as core::iter::traits::collect::FromIterator<((K,V),u64,isize)>>::from_iter
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0565c89823f7242c0-1/materialize/tests/src/persist/src/indexed/columnar.rs:139:13
  10: core::iter::traits::iterator::Iterator::collect
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/traits/iterator.rs:1745:9
      persist::indexed::columnar::parquet::encode_trace_parquet
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0565c89823f7242c0-1/materialize/tests/src/persist/src/indexed/columnar/parquet.rs:52:19
  11: <persist::indexed::encoding::BlobTraceBatch as persist_types::Codec>::encode
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0565c89823f7242c0-1/materialize/tests/src/persist/src/indexed/encoding.rs:628:9
      persist::indexed::cache::BlobCache<B>::set_trace_batch
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0565c89823f7242c0-1/materialize/tests/src/persist/src/indexed/cache.rs:267:9
  12: persist::indexed::arrangement::Arrangement::trace_append
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0565c89823f7242c0-1/materialize/tests/src/persist/src/indexed/arrangement.rs:556:36
      persist::indexed::arrangement::Arrangement::unsealed_drain
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0565c89823f7242c0-1/materialize/tests/src/persist/src/indexed/arrangement.rs:390:9
  13: persist::indexed::AppliedState::drain_unsealed
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0565c89823f7242c0-1/materialize/tests/src/persist/src/indexed/mod.rs:906:13
      persist::indexed::Indexed<L,B>::step::{{closure}}
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0565c89823f7242c0-1/materialize/tests/src/persist/src/indexed/mod.rs:723:51
      persist::indexed::Indexed<L,B>::apply_unbatched_cmd
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0565c89823f7242c0-1/materialize/tests/src/persist/src/indexed/mod.rs:322:30
      persist::indexed::Indexed<L,B>::step
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0565c89823f7242c0-1/materialize/tests/src/persist/src/indexed/mod.rs:723:9
  14: persist::runtime::RuntimeImpl<L,B>::work
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0565c89823f7242c0-1/materialize/tests/src/persist/src/runtime.rs:431:29
  15: persist::runtime::start::{{closure}}
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0565c89823f7242c0-1/materialize/tests/src/persist/src/runtime.rs:111:19
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:123:18
  16: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/mod.rs:483:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
      std::panicking::try
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
      std::panic::catch_unwind
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
      std::thread::Builder::spawn_unchecked::{{closure}}
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/mod.rs:482:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
  17: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys/unix/thread.rs:106:17
  18: start_thread
  19: clone
```

To reproduce:

1. Clone the `philip-stoev:test-for-gh10071` branch
2. Run:
```
cd test/feature-benchmark
./mzcompose run feature-benchmark --root-scenario=KafkaRecoveryBig --this-options="--workers 8 --persistent-kafka-upsert-source" --other-options="--workers 8"
```
3. It will fail post-restart like this:
```
$ docker-compose run testdrive-svc --no-reset --seed=1642420951 --initial-backoff=0ms --backoff-factor=0 tmp/tmp-e46u5t3q.td
Creating feature-benchmark_testdrive-svc_run ... done
ERROR: 1
Configuration parameters:
    Kafka address: kafka:9092
    Schema registry URL: http://schema-registry:8081/
    materialized host: Tcp("materialized")
    error limit: 10
--- tmp/tmp-e46u5t3q.td
Running test 1 time(s) ... 
Run 1 ...
> SELECT 1; /* A */
rows match; continuing at ts 1642421201.4950752
> SELECT * FROM s1_is_complete /* B */
rows didn't match; sleeping to see if dataflow catches up
^^^ +++
tmp/tmp-e46u5t3q.td:6:1: error: preparing query failed: connection closed
     |
   5 | 
   6 | > SELECT * FROM s1_is_complete
     | ^
!!! Error Report
1 errors were encountered during execution
files involved: tmp/tmp-e46u5t3q.td
+++ 
mzcompose: error: running docker-compose failed (exit status 1)
```
4. Use `docker ps -a` to fish for the just-terminated Mz container.

### PR DESCRIPTION
**Pull request by danhhz**
ColumnarRecords internally has some size limits (currently that the
total amount of data in keys <= i32::MAX and similarly in vals; in the
future, perhaps additional ones). These were recently introduced in the
parquet work, but we didn't add the necessary bits to prevent
constructing batches that violate these size limits, resulting in a
panic at runtime when testing persist on large data sizes. (This is not
an issue for the background system tables, which deals with data far
smaller than 2GB).

BlobUnsealedBatch already kept a Vec of ColumnarRecords and both the
arrow and parquet formats easily handle the ability to encode a series
of them. BlobTraceBatch only had a single ColumnarRecords but it was
easily fixed in this commit.

So, we simply do the straightforward thing and break up batches as
necessary within a BlobUnsealedBatch/BlobTraceBatch. This allows us to
sidestep the issue of introducing ranges of keys to the descriptions we
use for blob batches. When combined with parquet metadata, it also sets
us up in the future for the ability to fetch individual ColumnarRecords
out of a blob value so we can e.g. compact two very large trace batches
without ever holding them both in memory at once (ditto on disk even).
Though, the details of this are hand-wavey at the moment and it will
require a good bit of code.

Note that this does result in a restriction that each individual key and
value must be <= i32::MAX bytes, but this seems entirely reasonable for
the foreseeable future.

### Motivation

  * This PR fixes a recognized bug:

Closes #10071

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [N/A] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Comment by danhhz** [comment]
ignore this last commit for now, it needs more commentary but I think it'll fix the issue I'm seeing in #10126

**Comment by danhhz** [comment]
got this working with one more local change! just need to clean it all up and push

Results for #10072 with `--num-records=10000000` overridden with an additional 0 (so 100_000_000).

```
Measurement: 581.5293731689453
Measurement: 315.48975944519043
Measurement: 316.53092217445374
Measurement: 327.34756088256836
Measurement: 313.07458329200745
Measurement: 315.5615532398224
Measurement: 319.180810213089
```

File: src/persist/src/indexed/columnar.rs [hunk 1]
```diff
@@ -438,4 +564,31 @@ mod tests {
             .collect();
         assert_eq!(reads, updates);
     }
+
+    #[test]
+    fn vec_builder() {
+        fn testcase(max_len: usize, key_size: usize, num_records: usize) {
+            let key = "x".repeat(key_size);
+            let expected = (0..num_records)
+                .map(|x| ((key.as_bytes(), "".as_bytes()), u64::cast_from(x), 1))
```
Comment (ruchirK) [inline src/persist/src/indexed/columnar.rs:575]: minor nit that this test doesn't exercise the values overflowing the size limit but it seems like it easily could

File: src/persist/src/indexed/columnar.rs [hunk 2]
```diff
@@ -162,6 +168,13 @@ impl<'a> fmt::Debug for ColumnarRecordsRef<'a> {
 
 impl<'a> ColumnarRecordsRef<'a> {
     fn validate(&self) -> Result<(), String> {
+        if self.key_data.len() > KEY_VAL_DATA_MAX_LEN {
+            return Err(format!(
+                "expected key_data len to be less than {} got {}",
```
Comment (ruchirK) [inline src/persist/src/indexed/columnar.rs:173]: nit "less than or equal to" not less than

File: src/persist/src/indexed/columnar.rs [hunk 3]
```diff
@@ -405,6 +444,93 @@ impl ColumnarRecordsBuilder {
...
+        self.current.len() + self.filled.iter().map(|x| x.len()).sum::<usize>()
+    }
+
+    /// Reserve space for `additional` more records, based on `key_size_guess` and
+    /// `val_size_guess`.
+    ///
+    /// The guesses for key and val sizes are best effort, and if they end up being
+    /// too small, the underlying buffers will be resized.
+    pub fn reserve(&mut self, additional: usize, key_size_guess: usize, val_size_guess: usize) {
+        // TODO: This logic very much breaks down if we do end up having to
```
Comment (ruchirK) [inline src/persist/src/indexed/columnar.rs:504]: just to double check this todo - the logic breaks down in that we reserve individually min(max len, additional * key_size guess) for the keys and min(max len, additional * val_size guess) for the vals

more specifically it seems like theres two breakages:
1. we won't always reserve for as much as you ask for
2. if you ask for say 1 thousand 20 MB keys, and 1 thousand 1 MB values - we'll allocate a `ColumnarRecords` that has space for 100 keys and 1000 values, where 90% of the allocated space for values is a memory leak?

Comment (ruchirK) [reply src/persist/src/indexed/columnar.rs:504]: this is all fine for now - i think maybe its worth elaborating in the todo?

File: src/persist/src/indexed/columnar.rs [hunk 4]
```diff
@@ -438,4 +564,31 @@ mod tests {
...
+                assert_eq!(builder.len(), idx + 1);
+            }
+            let columnar = builder.finish();
+            let actual = columnar.iter().flat_map(|x| x.iter()).collect::<Vec<_>>();
+            assert_eq!(actual, expected);
+        }
+
+        testcase(KEY_VAL_DATA_MAX_LEN, 0, 0);
+        testcase(KEY_VAL_DATA_MAX_LEN, 10, 10);
+        testcase(10, 10, 1);
```
Comment (ruchirK) [inline src/persist/src/indexed/columnar.rs:592]: nit: I know for sure that this is mildly annoying so feel free to ignore but i feel like its worth it to have a testcase that validates that `testcase(10, 11, 1)` panics

**Review by ruchirK — APPROVED** [review]
LGTM! left some minor nits and questions (edit: i didn't look at the last commit yet)

File: src/persist/src/indexed/columnar.rs (hunk 1 above)
Comment (danhhz) [reply src/persist/src/indexed/columnar.rs]: done. also added coverage of the number of ColumnarRecords each case is expected to result in

File: src/persist/src/indexed/columnar.rs (hunk 4 above)
Comment (danhhz) [reply src/persist/src/indexed/columnar.rs]: nah i think panic testing is great. however, this would require either a 2GB alloc in a unit test or plumbing the `limit` thing down to ColumnarRecordBuilder, both of which I'd rather not do. I'll do the latter if you insist, though

**Review by danhhz — COMMENTED** [review]
this latest fixup has a decent number of changes if you want to take another look before I merge

**Comment by ruchirK** [comment]
> this latest fixup has a decent number of changes if you want to take another look before I merge

just to sanity check @danhhz this won't merge before I finalize the perf investigation in #9380 right?

File: src/persist/src/indexed/columnar.rs (hunk 4 above)
Comment (ruchirK) [reply src/persist/src/indexed/columnar.rs]: nah thats fine

File: src/persist/src/indexed/columnar.rs [hunk 5]
```diff
@@ -396,6 +411,21 @@ impl ColumnarRecordsBuilder {
         debug_assert_eq!(self.borrow().validate(), Ok(()));
     }
 
+    /// Returns if the given key_offsets+key_data or val_offsets+val_data fits
+    /// in the limits imposed by ColumnarRecords.
+    ///
+    /// Note that limit is always [KEY_VAL_DATA_MAX_LEN] in production. It's
+    /// only override-able here for testing.
+    pub fn can_fit(&self, key: &[u8], val: &[u8], limit: usize) -> bool {
+        let key_data_size = (self.key_offsets.len() + 1) * BYTES_PER_KEY_VAL_OFFSET
```
Comment (ruchirK) [inline src/persist/src/indexed/columnar.rs:420]: I'm going to just say the justification for this expression in a sentence to make sure I understand it correctly and you can tell me if its right

we'll be storing the offsets inline with the key data and in the offsets array. It's `(key_offsets.len() + 1) because we'll need to add a new offset for this new key we're inserting, and its multiplied by `BYTES_PER_KEY_VAL_OFFSET` because `key_offsets` is an array of `i32`.

those bytes are added with the existing key and existing value bytes and the whole thing has to be leq the limit.

File: src/persist/src/indexed/columnar.rs [hunk 6]
```diff
@@ -503,16 +529,24 @@ impl ColumnarRecordsVecBuilder {
     pub fn reserve(&mut self, additional: usize, key_size_guess: usize, val_size_guess: usize) {
         // TODO: This logic very much breaks down if we do end up having to
         // return multiple batches. Tune this later.
+        //
+        // In particular, it can break down in at least the following ways:
+        // - Only the batch currently being built is pre-sized. This can be
+        //   fixed by keeping track on `self` of how much of our reservation (if
+        //   any) didn't fit in the current ColumnarRecords and rolling it over
+        //   to future one if/when we hit them.
+        // - The reservation is blindly truncated at the ColumnarRecrods size
```
Comment (ruchirK) [inline src/persist/src/indexed/columnar.rs:538]: nit: `Recrods`

File: src/persist/src/indexed/columnar.rs (hunk 5 above)
Comment (ruchirK) [reply src/persist/src/indexed/columnar.rs:420]: so are we storing two copies of the key and val offsets?

**Review by ruchirK — APPROVED** [review]
LGTM just had a few questions to sanity check things

**Comment by danhhz** [comment]
> just to sanity check @danhhz this won't merge before I finalize the perf investigation in #9380 right?

I also could rebase it without your changes, which might be the way to go now that I think of it. this PR is fixing a crash which is blocking basically any work on scale out, whereas 9380 is atm a nice to have

File: src/persist/src/indexed/columnar.rs (hunk 6 above)
Comment (danhhz) [reply src/persist/src/indexed/columnar.rs]: done

**Review by danhhz — COMMENTED** [review]
whoops almost missed these last two comments!

I'd really like to get the KafkaRecoveryBig benchmark fixed, so I went ahead and rebased this on top of main without your PR so I can merge it now. happy to help with the conflicts!

TFTR!
