### PR TITLE
coord,dataflow: tie persistence data to catalog versions (cluster_id)

### LINKED ISSUE #4029: Harden source persistence against incorrect catalog modifications
Imagine the following scenario:

A user creates a persisted source (u1) and materialize writes down some data for it.
The user shuts down materialize.
The user blows away their catalog, but keeps the persistence folder -- bad!
The user makes a new, different persistent source (again called u1)
The user tries to read from u1 maybe in a materialized view -- now the user will end up consuming data from the "old" which could be totally different than the current u1

Proposed fix:

Introduce a catalog id / nonce that is created whenever a new catalog is created, but otherwise lives across Materialize restarts. Teach the persister about it.

### PR DESCRIPTION
**Pull request by ruchirK**
Closes #4029

Previously, we had a ABA type of problem in source persistence where a user
could take some previously persisted data, and swap out the corresponding catalog,
at which point its possible that source global ids used in the persistent data
no longer correspond to those in the catalog.

This change makes it so that all persistent data remembers what catalog
version it was created from, and refuses to ingest persistent data that does not
belong to the same catalog.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4367)

### CODE REVIEW

**Review by benesch — APPROVED** [review]

File: src/coord/src/persistence.rs [hunk 1]
```diff
@@ -390,6 +401,18 @@ fn augment_connector_inner(
...
                         if metadata.source_id != source_id {
+                            error!("Ignoring persistence file with invalid source id. Received: {} expected: {} path: {}",
+                                   metadata.source_id,
+                                   source_id,
+                                   path.display());
+                            continue;
+                        }
+
+                        if metadata.cluster_id != cluster_id {
+                            error!("Ignoring persistence file with invalid cluster id. Received: {} expected: {} path {}",
```
Comment (mjibson) [inline src/coord/src/persistence.rs:412]: missing colon after path

**Review by mjibson — APPROVED** [review]

File: src/coord/src/persistence.rs (hunk 1 above)
Comment (ruchirK) [reply src/coord/src/persistence.rs]: thanks!
