### PR TITLE
compute-client: maintain peek read holds long enough

### LINKED ISSUE #15426: storage: cannot serve requested as_of
### What version of Materialize are you using?

 v0.27.0 (218138173)

### How did you install Materialize?

Materialize Cloud

### What is the issue?

1. Created a Kafka source with byte-formatted keys and values
3. Created a new cluster.
4. Created two replicas with differing sizes, `medium` and `xlarge`.
2. Created a materialized view to deserialized the bytes as JSON and then structured them.
3. Explicitly set my cluster to the new cluster.
4. Explicitly set my target replica to `medium`.
5. Queried the materialized view, which succeeded.
6. Explicitly set my target replica to `xlarge`.
7. Queried the materialized view, which never completed.
8. Checked logs in Honeycomb and determined that my worker had panicked:
    ```
    thread 'tokio-runtime-worker' panicked at 'u242: cannot serve requested as_of Antichain { elements: [1665768908791] }: Since(Antichain { elements: [1665769196001] })', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0efb11835bec0ffd2-1/materialize/tests/src/storage/src/source/persist_source.rs:230:24
    ```

### Relevant log output

```source
Honeycomb produces the stack trace upside down--sorry!


compute-cluster-u8-replica-16-0	
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/pool.rs:300:13
compute-cluster-u8-replica-16-0	
  53: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/pool.rs:325:17
compute-cluster-u8-replica-16-0	
  52: tokio::runtime::blocking::pool::Inner::run
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/pool.rs:91:9
compute-cluster-u8-replica-16-0	
  51: tokio::runtime::blocking::pool::Task::run
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/mod.rs:418:9
compute-cluster-u8-replica-16-0	
  50: tokio::runtime::task::UnownedTask<S>::run
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/raw.rs:84:18
compute-cluster-u8-replica-16-0	
  49: tokio::runtime::task::raw::RawTask::poll
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:57:15
compute-cluster-u8-replica-16-0	
  48: tokio::runtime::task::harness::Harness<T,S>::poll
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:104:27
compute-cluster-u8-replica-16-0	
  47: tokio::runtime::task::harness::Harness<T,S>::poll_inner
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:468:18
compute-cluster-u8-replica-16-0	
  46: tokio::runtime::task::harness::poll_future
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
compute-cluster-u8-replica-16-0	
  45: std::panic::catch_unwind
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
compute-cluster-u8-replica-16-0	
  44: std::panicking::try
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
compute-cluster-u8-replica-16-0	
  43: std::panicking::try::do_call
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panic/unwind_safe.rs:271:9
compute-cluster-u8-replica-16-0	
  42: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:480:19
compute-cluster-u8-replica-16-0	
  41: tokio::runtime::task::harness::poll_future::{{closure}}
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:155:13
compute-cluster-u8-replica-16-0	
  40: tokio::runtime::task::core::CoreStage<T>::poll
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/loom/std/unsafe_cell.rs:14:9
compute-cluster-u8-replica-16-0	
  39: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:165:17
compute-cluster-u8-replica-16-0	
  38: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/task.rs:42:21
compute-cluster-u8-replica-16-0	
  37: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:362:45
compute-cluster-u8-replica-16-0	
  36: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:383:5
compute-cluster-u8-replica-16-0	
  35: tokio::runtime::thread_pool::worker::run
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/macros/scoped_tls.rs:61:9
compute-cluster-u8-replica-16-0	
  34: tokio::macros::scoped_tls::ScopedKey<T>::set
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:386:17
compute-cluster-u8-replica-16-0	
  33: tokio::runtime::thread_pool::worker::run::{{closure}}
compute-cluster-u8-replica-16-0	
  32: tokio::runtime::thread_pool::worker::Context::run
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:434:9
compute-cluster-u8-replica-16-0	
  31: tokio::runtime::thread_pool::worker::Context::run_task
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:72:5
compute-cluster-u8-replica-16-0	
  30: tokio::coop::budget
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:95:5
compute-cluster-u8-replica-16-0	
  29: tokio::coop::with_budget
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:421:9
compute-cluster-u8-replica-16-0	
  28: std::thread::local::LocalKey<T>::with
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:445:16
compute-cluster-u8-replica-16-0	
  27: std::thread::local::LocalKey<T>::try_with
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:102:9
compute-cluster-u8-replica-16-0	
  26: tokio::coop::with_budget::{{closure}}
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:458:21
compute-cluster-u8-replica-16-0	
  25: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/mod.rs:381:9
compute-cluster-u8-replica-16-0	
  24: tokio::runtime::task::LocalNotified<S>::run
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/raw.rs:84:18
compute-cluster-u8-replica-16-0	
  23: tokio::runtime::task::raw::RawTask::poll
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:57:15
compute-cluster-u8-replica-16-0	
  22: tokio::runtime::task::harness::Harness<T,S>::poll
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:104:27
compute-cluster-u8-replica-16-0	
  21: tokio::runtime::task::harness::Harness<T,S>::poll_inner
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:468:18
compute-cluster-u8-replica-16-0	
  20: tokio::runtime::task::harness::poll_future
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
compute-cluster-u8-replica-16-0	
  19: std::panic::catch_unwind
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
compute-cluster-u8-replica-16-0	
  18: std::panicking::try
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
compute-cluster-u8-replica-16-0	
  17: std::panicking::try::do_call
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panic/unwind_safe.rs:271:9
compute-cluster-u8-replica-16-0	
  16: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:480:19
compute-cluster-u8-replica-16-0	
  15: tokio::runtime::task::harness::poll_future::{{closure}}
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:155:13
compute-cluster-u8-replica-16-0	
  14: tokio::runtime::task::core::CoreStage<T>::poll
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/loom/std/unsafe_cell.rs:14:9
compute-cluster-u8-replica-16-0	
  13: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:165:17
compute-cluster-u8-replica-16-0	
  12: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
compute-cluster-u8-replica-16-0	
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
compute-cluster-u8-replica-16-0	
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0efb11835bec0ffd2-1/materialize/tests/src/storage/src/source/persist_source.rs:147:55
compute-cluster-u8-replica-16-0	
  10: <mz_storage::source::persist_source::DropSafeLeaseStream as core::ops::drop::Drop>::drop::{{closure}}
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.24/src/stream/stream/next.rs:32:9
compute-cluster-u8-replica-16-0	
   9: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.24/src/stream/stream/mod.rs:1626:9
compute-cluster-u8-replica-16-0	
   8: futures_util::stream::stream::StreamExt::poll_next_unpin
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.24/src/stream.rs:120:9
compute-cluster-u8-replica-16-0	
   7: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.3.3/src/async_stream.rs:53:17
compute-cluster-u8-replica-16-0	
   6: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
compute-cluster-u8-replica-16-0	
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.3.3/src/lib.rs:237:9
compute-cluster-u8-replica-16-0	
   4: mz_storage::source::persist_source::persist_source_core::{{closure}}
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1493:23
compute-cluster-u8-replica-16-0	
   3: core::result::Result<T,E>::unwrap_or_else
compute-cluster-u8-replica-16-0	
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0efb11835bec0ffd2-1/materialize/tests/src/storage/src/source/persist_source.rs:230:24
compute-cluster-u8-replica-16-0	
   2: mz_storage::source::persist_source::persist_source_core::{{closure}}::{{closure}}
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
compute-cluster-u8-replica-16-0	
   1: core::panicking::panic_fmt
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
compute-cluster-u8-replica-16-0	
   0: rust_begin_unwind
```
```

### PR DESCRIPTION
**Pull request by teskje**
This PR changes the compute controller to defer dropping of read holds installed for peeks until all replicas have responded to the peek in some way. This prevents the controller from dropping the read hold too early, namely when the fastest replica has responded to a peek but slow ones might still be reading from the source collections at times that could be compacted away after dropping the read hold.

### Motivation

  * This PR fixes a recognized bug.

Improves on #15426.

This is not a complete fix, as it doesn't work for replica-targeted peeks. See https://github.com/MaterializeInc/materialize/issues/15426#issuecomment-1283812125 for an explanation.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

File: src/compute-client/src/controller/replicated.rs [hunk 1]
```diff
@@ -138,11 +138,27 @@ where
...
 #[derive(Debug)]
 struct PendingPeek {
+    /// Replicas that have yet to respond to this peek.
+    unfinished: BTreeSet<ReplicaId>,
     /// The OpenTelemetry context for this peek.
-    otel_ctx: OpenTelemetryContext,
+    ///
+    /// This value is `Some` as long as we have not yet passed a response up the chain, and `None`
+    /// afterwards.
+    otel_ctx: Option<OpenTelemetryContext>,
```
Comment (lluki) [inline src/compute-client/src/controller/replicated.rs:150]: Hm, `otel_ctx` sound like something that is not functionally important, but just for tracing/logging to me

**Review by lluki — APPROVED** [review]
The only drawback I see is that we (potentially, if we have peeks) keep more state around if we have a replica that is lagging/broken. But we have this problem in other places too.

File: src/compute-client/src/controller/replicated.rs (hunk 1 above)
Comment (teskje) [reply src/compute-client/src/controller/replicated.rs:150]: It is just for tracing. In the beginning I thought we always need it when we construct a response, so this would work nicely to prevent us from producing duplicate responses. But this is actually only the case for cancel responses. For non-cancel responses, we use the otel context from the response we received, so we don't actually use the one stored here.

I thought about adding a separate field `served: bool`, but it seemed more of a hassle this way, because you'd need to remember to check and set an additional field when handling a peek response. But I'm fine with making that change if you feel strongly.

Comment (lluki) [reply src/compute-client/src/controller/replicated.rs:150]: Actually [line 392](https://github.com/MaterializeInc/materialize/pull/15504/files/3fce1170b725651f5274b33721cb56e0bbe09855#diff-3db47df6fd026e8e22e89e37f89c9409552803ba2112c55d881db1b32efb6e39R392) is the one where I thought that the contents of `otel_ctx` determine something functional. Maybe we could just rename it (to like `not_served` as in Some is interpreted as true, and None as false)?  But I'm fine either way :+1:
