### PR TITLE
expr: correctly union types for If exprs

### LINKED ISSUE #9931: expr: panic: assertion failed: then_type.scalar_type.base_eq(&else_type.scalar_type)
### What version of Materialize are you using?

0.15.1-dev (e0f5a7ee4e3af9541a59e8b19cf237f1809ccbb4)

### How did you install Materialize?

Built from source

### What was the issue?

```
SELECT
    t.*, CASE WHEN x IS NULL THEN NULL ELSE t.* END
FROM
    ROWS FROM (
        generate_series(1, 2),
        information_schema._pg_expandarray(ARRAY[100])
    )
        AS t;
```

panics in dev (due to a `debug_assert`) with:

```
location: src/expr/src/scalar/mod.rs:921:17
version: 0.15.1-dev (e0f5a7ee4e3af9541a59e8b19cf237f1809ccbb4)
backtrace:
   0: materialized::handle_panic
             at src/materialized/src/bin/materialized/main.rs:842:21
   1: core::ops::function::Fn::call
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:70:5
   2: std::panicking::rust_panic_with_hook
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:628:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:519:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
   5: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   6: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   7: core::panicking::panic
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:50:5
   8: expr::scalar::MirScalarExpr::typ
             at src/expr/src/scalar/mod.rs:921:17
   9: expr::relation::MirRelationExpr::typ_with_input_types
             at src/expr/src/relation/mod.rs:361:43
  10: <transform::reduction::FoldConstants as transform::Transform>::transform::{{closure}}
             at src/transform/src/reduction.rs:43:37
  11: expr::relation::MirRelationExprVisitor::try_visit_mut_post::{{closure}}
             at src/expr/src/relation/mod.rs:1614:13
```

This is happening because the types are asserted there for `base_eq`, but the use of `NULL` causes the nullable fields of the then and else scalar types to be swapped. I'm not sure if this is a problem in `base_eq` or `nullable()` or somewhere else.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by mjibson**
Previously the debug_assert would trigger if the nullability of Record fields differed.

Fixes #9931

### Motivation

  * This PR fixes a recognized bug: #9931

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/9940)

### CODE REVIEW

File: src/repr/src/scalar.rs [hunk 1]
```diff
@@ -1549,7 +1549,15 @@ impl<'a> ScalarType {
                     custom_oid: oid_b,
                     custom_name: name_b,
                 },
-            ) => fields_a.eq(fields_b) && oid_a == oid_b && name_a == name_b,
+            ) => {
+                oid_a == oid_b
+                    && name_a == name_b
```
Comment (sploiselle) [inline src/repr/src/scalar.rs:1554]: Think this also needs `&& fields_a.len() == fields_b.len()`

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=89b03260b03c8a1ae0bd8943d2270dbb

**Review by sploiselle — COMMENTED** [review]
Is this intending to close out #9931, or is there something left to do to figure out [which nullability value propagate from the conditional evaluation](https://github.com/MaterializeInc/materialize/issues/9931#issuecomment-1007300374)?

**Comment by mjibson** [comment]
https://github.com/MaterializeInc/materialize/blob/fa7c9e00e1981923c547cd79b26429f3b8086a94/src/expr/src/scalar/mod.rs#L923

The nullability field at the top level is already OR'd. Do we also need a function that recursively ORs nullability within Records? I feel like something is off but I'm pretty new to this directory.

**Comment by sploiselle** [comment]
Ah, makes sense! Just wanted to make sure this was closing #9931, but didn't see an auto-close

**Comment by mjibson** [comment]
Oops, it should have had a close note, added. Although the more I think about this I wonder if `base_eq` is fine and we need a thing that does recursive nullability OR'ing.

**Comment by mjibson** [comment]
Ah ha! There's already a method that does this. I've used that and reverted the original change so base_eq is now unchanged. RFAL.

**Review by benesch — APPROVED** [review]
Using `union` here seems fine, good even, but something still leaves me uneasy. It seems wrong that `base_eq` takes record field nullability into account. File a follow up I guess?
