### PR TITLE
push down join equivalences with runtime constants

### LINKED ISSUE #7579: optimization: predicate pushdown unable to push down join equivalences involving only one input
From `predicate_pushdown.rs`:

```
                // The goal is to push
                //   1) equivalences of the form `expr = literal`, where `expr`
                //      comes from a single input.
                //   2) equivalences of the form `expr1 = expr2`, where both
                //      expressions come from the same single input.
```

The first case needs to be generalized so it covers any equality equivalence against any runtime constant.

This issue prevents the creation of views that would otherwise be valid views:

```
materialize=> CREATE MATERIALIZED VIEW v1 AS SELECT * FROM first_ts a WHERE mz_logical_timestamp() = a.ts;
CREATE VIEW
materialize=> CREATE MATERIALIZED VIEW v2 AS SELECT * FROM first_ts a, first_ts b WHERE mz_logical_timestamp() = a.ts;
ERROR:  mz_logical_timestamp cannot be used in static or write queries
materialize=> 
```

### PR DESCRIPTION
**Pull request by asenac**
Pushable predicates can be extract from join equivalences with terms that are constant at runtime, such as mz_logical_timestamp and literals.

This PR generalizes the code that extracted pushable predicates from join equivalences with literals to any type of expression that is constant at runtime. It also covers the case when there are multiple runtime constants within the same equivalence.

Also, do not add `!isnull(expr)` predicates when converting a predicate into a join equivalence if `expr` is from a non-nullable type. This works around a missing transformation that removes them for any non-nullable expression and not just for columns (as ColumnKnowledge does).

Fixes #7579.

### CODE REVIEW

**Comment by asenac** [comment]
Spotted while working on #7174, where predicate pushdown is executed sooner in the list of transformations.

File: src/transform/src/predicate_pushdown.rs [hunk 1]
```diff
@@ -547,25 +556,31 @@ impl PredicatePushdown {
...
-                                MirScalarExpr::CallBinary {
-                                    func: expr::BinaryFunc::Eq,
-                                    expr1: Box::new(expr),
-                                    expr2: Box::new(literal.clone()),
-                                }
+                        .filter(|expr| expr.support().is_empty())
+                        .cloned()
+                        .collect::<Vec<_>>();
+                    if !runtime_constants.is_empty() {
+                        // Case 2: There is at least one in runtime constant the equivalence class
```
Comment (wangandi) [inline src/transform/src/predicate_pushdown.rs:565]: Nit: one runtime

File: src/transform/tests/testdata/predicate-pushdown [hunk 2]
```diff
@@ -0,0 +1,124 @@
...
+----
+%0 =
+| Get x (u0)
+| Filter (#1 = 1), (#1 = mz_logical_timestamp())
+
+%1 =
+| Get x (u0)
+
+%2 =
+| Join %0 %1 (= 1 mz_logical_timestamp())
```
Comment (wangandi) [inline src/transform/tests/testdata/predicate-pushdown:75]: Are these two runtime constants supposed to stay in the equivalence class of the join?

**Comment by philip-stoev** [comment]
Item No 1. The ability to detect that this query is a Constant has been lost:

```
pstoev@Ubuntu-2004-focal-64-minimal:~/randgen$ echo "EXPLAIN  SELECT  FROM t1  LEFT  JOIN t2  ON  TRUE  WHERE  t1.f1  = t1.f2 + 4 AND t1.f1 IS NULL AND NOT t1.f2  = t1.f1" | ~/diff.sh 
--- 6875.out	2021-07-29 09:29:17.820156668 +0200
+++ 16875.out	2021-07-29 09:29:17.864157351 +0200
@@ -1,18 +1,7 @@
                   Optimized Plan                  
---------------------------------------------------
+----------------
  %0 =                                            +
- | Get materialize.public.t1 (####)                +
- | Filter isnull(#0), (#0 = (#1 + 4)), (#0 != #1)+
- | ArrangeBy ()                                  +
-                                                 +
- %1 =                                            +
- | Get materialize.public.t2 (####)                +
-                                                 +
- %2 =                                            +
- | Join %0 %1                                    + <- in this branch
- | | implementation = Differential %1 %0.()      +
- | | demand = ()                                 +
- | Project ()                                    +
+ | Constant                                      + <- in the prior commit 
```

**Comment by asenac** [comment]
Item #1 is addressed by #7336 which extends predicate canonicalization to detect `isnull` on subexpressions which nulls are rejected by other predicates.

**Review by philip-stoev — APPROVED** [review]
There are no wrong results, no panics. Apart from the single Item No1, the plans are all positively impacted -- a Constant condition is being detected now where it previously was not , and the `isnull` check is now closer to the source, so less records to process downstream.

File: src/transform/tests/testdata/predicate-pushdown (hunk 2 above)
Comment (asenac) [reply src/transform/tests/testdata/predicate-pushdown:75]: Good question... I guess it's more correct to lift them as a predicate on top of the join afterwards.

**Comment by asenac** [comment]
I've rebased this branch after merging #7336 and confirmed the issue no 1 no longer happens:

```
materialize=> EXPLAIN  SELECT  FROM t1  LEFT  JOIN t2  ON  TRUE  WHERE  t1.f1  = t1.f2 + 4 AND t1.f1 IS NULL AND NOT t1.f2  = t1.f1
materialize-> ;
 Optimized Plan 
----------------
 %0 =          +
 | Constant    +
 
(1 row)

materialize=>
```

File: src/transform/tests/testdata/predicate-pushdown (hunk 2 above)
Comment (wangandi) [reply src/transform/tests/testdata/predicate-pushdown:75]: Or would it better to just eliminate this equivalence class? 

In the original code, the intent of
```
// For every single-input expression `expr`, we can push
// down `expr = literal` and remove `expr` from the
// equivalence class.
```
is that after this process, the equivalence class will be just `[literal]`. Equivalence classes with less than two expressions then get removed by `canonicalize_equivalences`. 

But in this test case, we are left with two expressions in the equivalence class, so `canonicalize_equivalences` does not know to remove it.

Comment (asenac) [reply src/transform/tests/testdata/predicate-pushdown:75]: Yeah, I think it is safe to assume that if an equivalence class is left only with expressions that don't depend on any input, then it can be removed as an equivalence class.

Comment (asenac) [reply src/transform/tests/testdata/predicate-pushdown]: Just pushed a commit to make `canonicalize_equivalences` cover this case.

Comment (wangandi) [reply src/transform/tests/testdata/predicate-pushdown]: Wouldn't putting the deletion in `canonicalize_equivalences` risk `(= 1 mz_logical_timestamp())` being deleted before predicate pushdown runs? Join fusion and RedundantJoin also call `canonicalize_equivalences`.

Comment (asenac) [reply src/transform/tests/testdata/predicate-pushdown]: `(= 1 mz_logical_timestamp())` should not end up as a join equivalence by itself. Only as the result of merging several equality expressions involving input columns, and then extracting pushable predicates from them. Of course, we can create a unit test where we create such equivalence manually, but there is no code path atm that does that.

Comment (asenac) [reply src/transform/tests/testdata/predicate-pushdown]: However, since there is no way to prevent that equivalence from being created, I could move the removal into `predicate_pushdown`, and remove it only IFF predicates were pushed down.

Comment (asenac) [reply src/transform/tests/testdata/predicate-pushdown]: New commit does that.

However, perhaps what we should do is to push `(1 = mz_logical_timestamp())` to all join inputs instead, to prevent any computation from happening until that condition is true...

Comment (wangandi) [reply src/transform/tests/testdata/predicate-pushdown]: > (= 1 mz_logical_timestamp()) should not end up as a join equivalence by itself. Only as the result of merging several equality expressions involving input columns, and then extracting pushable predicates from them. Of course, we can create a unit test where we create such equivalence manually, but there is no code path atm that does that.

Good point.

> However, perhaps what we should do is to push (1 = mz_logical_timestamp()) to all join inputs instead, to prevent any computation from happening until that condition is true...

Also a good point.

We may also want to put in an issue to investigate how `1 = mz_logical_timestamp()` should interact with join indexes. Right now, our join implementation planning will want to lift this filter `1 = mz_logical_timestamp()` to use the underlying index, but it is probably significantly cheaper to leave the filter in place.

File: src/transform/src/predicate_pushdown.rs [hunk 3]
```diff
@@ -591,14 +606,25 @@ impl PredicatePushdown {
...
                         // equivalence class.
                         for (expr_pos, input, expr) in single_input_exprs.drain(..).rev() {
-                            push_downs[input].push(gen_literal_equality_pred(expr));
+                            push_downs[input].extend(gen_literal_equality_preds(expr));
                             equivalences[equivalence_pos].remove(expr_pos);
                         }
+
+                        // If none of the expressions in the equivalence depend on input
+                        // columns and equality predicates with them are pushed down,
+                        // we can safely remove them from the equivalence.
```
Comment (wangandi) [inline src/transform/src/predicate_pushdown.rs:618]: We could probably add a TODO and/or follow-up issue for:
> However, perhaps what we should do is to push (1 = mz_logical_timestamp()) to all join inputs instead, to prevent any computation from happening until that condition is true...

**Review by wangandi — APPROVED** [review]
