### PR TITLE
Fast follow-ups from #9000

### LINKED ISSUE #8599: Stack exhaustion in coord::coord::dataflow_builder::DataflowBuilder::import_view_into_dataflow with nested non-materialized views
### What version of Materialize are you using?
```materialized v0.9.8-dev (48182cc6b)
```

### What was the issue?

Nested non-materialized views cause stack exhaustion:

```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f4bedcbf859 in __GI_abort () at abort.c:79
#2  0x00005636c7b01c97 in std::sys::unix::abort_internal () at library/std/src/sys/unix/mod.rs:206
#3  0x00005636c7b01112 in std::sys::unix::stack_overflow::imp::signal_handler () at library/std/src/sys/unix/stack_overflow.rs:109
#4  <signal handler called>
#5  0x00005636c59bcc7e in <expr::id::GlobalId as core::hash::Hash>::hash () at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/hash/mod.rs:347
#6  0x00005636c59a08a9 in hashbrown::map::make_hash () at /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.11.0/src/map.rs:256
#7  hashbrown::map::HashMap<K,V,S,A>::get_inner () at /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.11.0/src/map.rs:988
#8  hashbrown::map::HashMap<K,V,S,A>::get () at /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.11.0/src/map.rs:944
#9  std::collections::hash::map::HashMap<K,V,S>::get () at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/collections/hash/map.rs:735
#10 0x00005636c59d76cf in <std::collections::hash::map::HashMap<K,V,S> as core::ops::index::Index<&Q>>::index ()
    at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/collections/hash/map.rs:1148
#11 coord::coord::dataflow_builder::DataflowBuilder::import_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:70
#12 0x00005636c59d84b4 in coord::coord::dataflow_builder::DataflowBuilder::import_view_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:168
#13 0x00005636c59d7a8d in coord::coord::dataflow_builder::DataflowBuilder::import_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:151
#14 0x00005636c59d84b4 in coord::coord::dataflow_builder::DataflowBuilder::import_view_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:168
#15 0x00005636c59d7a8d in coord::coord::dataflow_builder::DataflowBuilder::import_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:151
#16 0x00005636c59d84b4 in coord::coord::dataflow_builder::DataflowBuilder::import_view_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:168
#17 0x00005636c59d7a8d in coord::coord::dataflow_builder::DataflowBuilder::import_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:151
#18 0x00005636c59d84b4 in coord::coord::dataflow_builder::DataflowBuilder::import_view_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:168
#19 0x00005636c59d7a8d in coord::coord::dataflow_builder::DataflowBuilder::import_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:151
#20 0x00005636c59d84b4 in coord::coord::dataflow_builder::DataflowBuilder::import_view_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:168
#21 0x00005636c59d7a8d in coord::coord::dataflow_builder::DataflowBuilder::import_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:151
#22 0x00005636c59d84b4 in coord::coord::dataflow_builder::DataflowBuilder::import_view_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:168
#23 0x00005636c59d7a8d in coord::coord::dataflow_builder::DataflowBuilder::import_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:151
#24 0x00005636c59d84b4 in coord::coord::dataflow_builder::DataflowBuilder::import_view_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:168
#25 0x00005636c59d7a8d in coord::coord::dataflow_builder::DataflowBuilder::import_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:151
#26 0x00005636c59d84b4 in coord::coord::dataflow_builder::DataflowBuilder::import_view_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:168
#27 0x00005636c59d7a8d in coord::coord::dataflow_builder::DataflowBuilder::import_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:151
#28 0x00005636c59d84b4 in coord::coord::dataflow_builder::DataflowBuilder::import_view_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:168
#29 0x00005636c59d7a8d in coord::coord::dataflow_builder::DataflowBuilder::import_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:151
#30 0x00005636c59d84b4 in coord::coord::dataflow_builder::DataflowBuilder::import_view_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:168
#31 0x00005636c59d7a8d in coord::coord::dataflow_builder::DataflowBuilder::import_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:151
#32 0x00005636c59d84b4 in coord::coord::dataflow_builder::DataflowBuilder::import_view_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:168
#33 0x00005636c59d7a8d in coord::coord::dataflow_builder::DataflowBuilder::import_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:151
#34 0x00005636c59d84b4 in coord::coord::dataflow_builder::DataflowBuilder::import_view_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:168
#35 0x00005636c59d7a8d in coord::coord::dataflow_builder::DataflowBuilder::import_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:151
#36 0x00005636c59d84b4 in coord::coord::dataflow_builder::DataflowBuilder::import_view_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:168
#37 0x00005636c59d7a8d in coord::coord::dataflow_builder::DataflowBuilder::import_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:151
#38 0x00005636c59d84b4 in coord::coord::dataflow_builder::DataflowBuilder::import_view_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:168
#39 0x00005636c59d7a8d in coord::coord::dataflow_builder::DataflowBuilder::import_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:151
#40 0x00005636c59d84b4 in coord::coord::dataflow_builder::DataflowBuilder::import_view_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:168
#41 0x00005636c59d7a8d in coord::coord::dataflow_builder::DataflowBuilder::import_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:151
#42 0x00005636c59d84b4 in coord::coord::dataflow_builder::DataflowBuilder::import_view_into_dataflow () at src/coord/src/coord/dataflow_builder.rs:168
```

### Is the issue reproducible? If so, please provide reproduction instructions.

1. Patch materialize to not attempt to resolve stack traces:
```
diff --git a/src/materialized/src/bin/materialized/main.rs b/src/materialized/src/bin/materialized/main.rs
index 6bdeb19a6..89cebae2d 100644
--- a/src/materialized/src/bin/materialized/main.rs
+++ b/src/materialized/src/bin/materialized/main.rs
@@ -354,9 +354,9 @@ fn main() {
 }
 
 fn run(args: Args) -> Result<(), anyhow::Error> {
-    panic::set_hook(Box::new(handle_panic));
-    sys::enable_sigbus_sigsegv_backtraces()?;
-    sys::enable_termination_signal_cleanup()?;
+    // panic::set_hook(Box::new(handle_panic));
+    // sys::enable_sigbus_sigsegv_backtraces()?;
+    // sys::enable_termination_signal_cleanup()?;
 
     if args.version > 0 {
```
 
2. Run attached file [gh8599.td.zip](https://github.com/MaterializeInc/materialize/files/7310404/gh8599.td.zip)

There is no need to push this test anywhere, as a dedicated test framework is being constructed for that sort of stuff.

### LINKED ISSUE #9331: Fix `optimize_dataflow` call in `Coordinator::finalize_dataflow`
With the changes introduced in #9293, the `Coordinator::finalize_dataflow` code now has the following code:

```rust
transform::optimize_dataflow(&mut dataflow, self.catalog.enabled_indexes())
    .expect("Dataflow planning failed; unrecoverable error"); // FIXME
```

We need to widen the result type of `finalize_dataflow` from `DataflowDescription<dataflow_types::Plan>` to `Result<DataflowDescription<dataflow_types::Plan>, CoordError>` and change all clients respectively, so a `TransformError` that is returned by the `optimize_dataflow` is cast and bubbled up properly up the chain.

### LINKED ISSUE #9332: Organize `MirScalarExpr::*visit*` methods like `MirRelationExpr::*visit*`
Organize and rename all `MirScalarExpr::*visit*` similarly to `MirRelationExpr::*visit*`. This entails:

- Use consistent naming for all `MirScalarExpr::*visit*` methods.
- Introduce a dedicated visitor struct `MirScalarExprVisitor` with a `RecursionGuard` field.
- Move `MirScalarExpr::*visit*` implementations to `MirScalarExprVisitor::*visit*`
- Use `MirScalarExpr::*visit*` to delegate to the latter. 
- Revisit the need to annotate delegates with `#[inline(always)]` vs `#inline`.
- Implement `CheckedRecursion` for `MirScalarExprVisitor`.

### PR DESCRIPTION
**Pull request by aalexandrov**
Resolve fast follow-ups after #9000.

### Motivation

- This PR refactors existing code. 
  - Resolves #9331 (see the issue description for details).
  - Resolves #9332 (see the issue description for details).
- This PR fixes a recognized bug. 
  - Fixes #8599.

### Tips for reviewer

The commits are assigned to issues as follows

- Refactorings for [#9332](#9332) (reviewer @asenac)
  - [expr: make `MirScalarExpr::*visit*` method names consistent](https://github.com/MaterializeInc/materialize/pull/9341/commits/4ece5b3b6)
  - [expr: make recursive `MirScalarExpr::*visit*` methods stack safe](https://github.com/MaterializeInc/materialize/pull/9341/commits/a1958c2db)
  - [expr: align visitor logic in `MirScalarExpr*` with `MirRelationExpr`](https://github.com/MaterializeInc/materialize/pull/9341/commits/397bc0fe9)
  - [expr: remove panics from `MirRelationExprVisitor::visit_*`](https://github.com/MaterializeInc/materialize/pull/9341/commits/cb52e81d3)
- Refactorings for [#9331](#9331) (reviewer @sploiselle)
  - [coord: fix `optimize_dataflow` call in `Coordinator::finalize_dataflow`](https://github.com/MaterializeInc/materialize/pull/9341/commits/548e2c199)
- Fix for [#8599](#8599) (reviewer @asenac)
  - [coord: make `DataflowBuilder::import_into_dataflow` stack safe](https://github.com/MaterializeInc/materialize/pull/9341/commits/0ad28128e)

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Review by philip-stoev — APPROVED** [review]
The nightly is now green

https://buildkite.com/materialize/nightlies/builds/515#09c3851c-739c-46e5-92da-ef4129877dcb

As discussed previously, I will, separately:
- close any left-over tickets
- make sure that the test/limits tests with both queries that are expected to succeed and those that are expected to fail.

**Comment by asenac** [comment]
commit message for `coord: make DataflowBuilder::import_into_dataflow stack safe` mentions #8600 instead of #8599, which the one it is meant to fix.

**Comment by asenac** [comment]
As you mentioned offline, perhaps we should log a follow up task for making `MirScalarExpr` and `MirRelationExpr` shared the visit implementations, by making them implement `visit_children*` via a trait.

Also, perhaps that approach could also be used for `Hir{Scalar/Relation}Expr`.

File: src/expr/src/relation/mod.rs [hunk 1]
```diff
@@ -1318,53 +1318,51 @@ impl MirRelationExprVisitor {
         F: FnMut(&'a MirRelationExpr) -> Result<(), E>,
         E: From<RecursionLimitError>,
```
Comment (asenac) [inline src/expr/src/relation/mod.rs:1319]: In theory this constraint could be removed/relaxed now, couldn't it?

**Comment by asenac** [comment]
It took me a while to find the _panics_ commit `expr: remove panics from MirRelationExprVisitor::visit_*` is _removing_. IIUC it's avoiding stack overflow related panics by using `maybe_grow`, isn't it?

**Review by asenac — APPROVED** [review]
Nothing controversial in the code changes. A couple of minor comments about the commit messages.

**Review by philip-stoev — APPROVED** [review]

File: src/expr/src/relation/mod.rs (hunk 1 above)
Comment (aalexandrov) [reply src/expr/src/relation/mod.rs:1319]: Good catch.

**Comment by aalexandrov** [comment]
> IIUC it's avoiding stack overflow related panics by using maybe_grow, isn't it?

Yes, I will refine the commit message to be more precise _how_ we are removing the panics.

**Comment by aalexandrov** [comment]
> > IIUC it's avoiding stack overflow related panics by using maybe_grow, isn't it?
> 
> Yes, I will refine the commit message to be more precise _how_ we are removing the panics.

Describe what needs to be done in #9396.
