### PR TITLE
pgwire,sql: respect client-provided parameter types

### LINKED ISSUE #3625: pgwire: Parse message parameter types are ignored
pgwire clients can choose to specify the types of their parameters when they send a `Parse` message. Any unspecified parameters are inferred by the server using the same rules as for untyped string literals. _Most_ clients choose to leave all parameter types unspecified, including all the clients we test with, I think, and then just ask the database about the OIDs that were inferred. But PgJDBC, notably, explicitly sets these OIDs, at least in some cases.

We currently throw away these OIDs and just use the OIDs we infer. This results in a mismatch down the road, e.g. if we infer an `int8` but the client sends us an `int4`.

This assessment is based on a backtrace provided by a customer, so I don't have conclusive proof. But I bet trying to prepare and execute a query like

```
SELECT int8_col = ? FROM int8_containing_table
```

from within JDBC would tickle the bug.

The fix is to plumb any constrained parameter types from the parse message through to SQL planning. The design of the planner itself should already handle this nicely; we just need to initialize the param_types map according to the client specified values, rather than defaulting to "unspecified" for all parameters.

### PR DESCRIPTION
**Pull request by benesch**
While most PostgreSQL clients leave parameter types unspecified and rely
on the server to perform parameter type inference, the protocol allows
for clients to explicitly specify parameter types. PgJDBC, notably,
always specifies parameter types in its default configuration.

We were previously dropping this information on the floor, which led to
some weird error messages with PgJDBC if the types didn't line up. This
commit fixes that.

Fix #3625.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/3810)

### CODE REVIEW

File: src/pgwire/src/codec.rs [hunk 1]
```diff
@@ -453,32 +453,16 @@ fn decode_parse(mut buf: Cursor) -> Result<FrontendMessage, io::Error> {
...
-    // used in the query string. Another special case is that a parameter's type can be
-    // specified as void (that is, the OID of the void pseudo-type). This is meant to
-    // allow parameter symbols to be used for function parameters that are actually OUT
-    // parameters. Ordinarily there is no context in which a void parameter could be
-    // used, but if such a parameter symbol appears in a function's parameter list, it is
-    // effectively ignored. For example, a function call such as foo($1,$2,$3,$4) could
-    // match a function with two IN and two OUT arguments, if $3 and $4 are specified as
-    // having type void.
-    //
-    // Oh god
```
Comment (JLDLaughlin) [inline src/pgwire/src/codec.rs:467]: 😂

**Comment by benesch** [comment]
🎉 thanks for reviewing!
