### PR TITLE
Coord: Separate capability of storage and compute

### LINKED ISSUE #15887: thread 'coordinator' panicked at 'Dataflow temp-view-t3 requested as_of (Antichain { elements: [1667501333584] }) not >= since (Antichain { elements: [1667501333950] })',
### What version of Materialize are you using?

d95dec641b

### How did you install Materialize?

Docker image

### What is the issue?

Previously seen as : https://github.com/MaterializeInc/materialize/issues/8241
Now seen in: https://buildkite.com/materialize/tests/builds/44464#01843ebc-9dec-40af-9026-84b388be7e7e

### Relevant log output

```source
thread 'coordinator' panicked at 'Dataflow temp-view-t3 requested as_of (Antichain { elements: [1667501333584] }) not >= since (Antichain { elements: [1667501333950] })', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07409f6093c7cd99b-1/materialize/tests/src/adapter/src/coord/dataflows.rs:162:13
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: mz_adapter::coord::dataflows::<impl mz_adapter::coord::Coordinator<S>>::finalize_dataflow
   3: mz_adapter::coord::peek::<impl mz_adapter::coord::Coordinator<S>>::create_peek_plan
   4: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_peek::{{closure}}::{{closure}}
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_plan::{{closure}}::{{closure}}
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_message::{{closure}}
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: std::thread::local::LocalKey<T>::with
  17: tokio::park::thread::CachedParkThread::block_on
  18: tokio::runtime::handle::Handle::block_on
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by jkosh44**
Previously the Coordinator stored the read capability of all objects in
a map whose key was Global ID. For most objects this works fine since
most Global IDs refer to a single object. However for some objects,
such as materialized views and certain introspection sources, a COMPUTE
object and a STORAGE object share the same Global ID. This caused the
two objects to use the same value in the read capability map which led
to various inconsistencies.

This commit updates the Coordinator's state to store COMPUTE and
STORAGE read capabilities separately.

Fixes #15887

### Motivation
This PR fixes a recognized bug.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - N/A

### CODE REVIEW

File: src/adapter/src/coord.rs [hunk 1]
```diff
@@ -381,15 +381,25 @@ pub struct Coordinator<S> {
...
+    storage_read_capability: HashMap<GlobalId, ReadCapability<mz_repr::Timestamp>>,
+    /// For each identifier in COMPUTE, its read policy and any read holds on time.
+    ///
+    /// Transactions should introduce and remove constraints through the methods
+    /// `acquire_read_holds` and `release_read_holds`, respectively. The base
+    /// policy can also be updated, though one should be sure to communicate this
+    /// to the controller for it to have an effect.
+    ///
+    /// Access to this field should be restricted to methods in the [`read_policy`] API.
+    compute_read_capability: HashMap<GlobalId, ReadCapability<mz_repr::Timestamp>>,
```
Comment (teskje) [inline src/adapter/src/coord.rs:401]: Nit, but since we are touching this code anyway: Shouldn't these field names be plural, i.e. `storage_read_capabilities` and `compute_read_capabilities`?

**Review by teskje — APPROVED** [review]
LGTM!

File: src/adapter/src/coord.rs (hunk 1 above)
Comment (jkosh44) [reply src/adapter/src/coord.rs]: Done
