### PR TITLE
adapter: acquire subscribe read holds

### LINKED ISSUE #25375: `SinceViolation` in SUBSCRIBE sequencing
### What version of Materialize are you using?

main

### What is the issue?

Bumping the compute controller's maintenance tick interval from 1s to 10s makes the Parallel Workload nightly job encounter a `SinceViolation` panic sometimes.

```
thread 'coordinator' panicked at src/adapter/src/util.rs:277:23:
dataflow creation cannot fail: SinceViolation(User(46))
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: <core::result::Result<(), mz_compute_client::controller::error::DataflowCreationError> as mz_adapter::util::ResultExt<()>>::unwrap_or_terminate
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05207a1d8149a36ff-1/materialize/tests/src/adapter/src/util.rs:277:23
   3: <mz_adapter::coord::Coordinator>::ship_dataflow::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05207a1d8149a36ff-1/materialize/tests/src/adapter/src/coord.rs:2661:9
   4: <futures_util::future::maybe_done::MaybeDone<<mz_adapter::coord::Coordinator>::ship_dataflow::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/maybe_done.rs:95:38
   5: <futures_util::future::join::Join<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()> + core::marker::Send>>, <mz_adapter::coord::Coordinator>::ship_dataflow::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/join.rs:55:33
   6: <mz_adapter::coord::Coordinator>::subscribe_finish::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05207a1d8149a36ff-1/materialize/tests/src/adapter/src/coord/sequencer/inner/subscribe.rs:322:83
   7: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::subscribe_finish::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
   8: <mz_adapter::coord::Coordinator>::subscribe_finish::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05207a1d8149a36ff-1/materialize/tests/src/adapter/src/coord/sequencer/inner/subscribe.rs:273:5
   9: <mz_adapter::coord::SubscribeStage as mz_adapter::coord::Staged>::stage::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05207a1d8149a36ff-1/materialize/tests/src/adapter/src/coord/sequencer/inner/subscribe.rs:50:81
  10: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<mz_adapter::coord::StageResult<alloc::boxed::Box<mz_adapter::coord::SubscribeStage>>, mz_adapter::error::AdapterError>>>> as core::future::future::Future>::poll
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  11: <tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<mz_adapter::coord::StageResult<alloc::boxed::Box<mz_adapter::coord::SubscribeStage>>, mz_adapter::error::AdapterError>>>>> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  12: <mz_adapter::coord::Coordinator>::sequence_staged::<mz_adapter::coord::SubscribeStage>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05207a1d8149a36ff-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:147:14
  13: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05207a1d8149a36ff-1/materialize/tests/src/adapter/src/coord/message_handler.rs:184:60
  14: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_message::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  15: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  16: <mz_adapter::coord::Coordinator>::serve::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05207a1d8149a36ff-1/materialize/tests/src/adapter/src/coord.rs:2538:48
  17: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  18: <tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  19: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  20: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  21: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  22: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  23: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  24: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:310:13
  25: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::handle::Handle>::block_on<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>::{closure#0}, ()>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  26: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:309:9
  27: mz_adapter::coord::serve::{closure#0}::{closure#3}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05207a1d8149a36ff-1/materialize/tests/src/adapter/src/coord.rs:2991:21
```

https://buildkite.com/materialize/nightlies/builds/6530#_

From the backtrace we see that this happens during SUBSCRIBE sequencing. It seems like adapter doesn't collect appropriate read holds and then when it wants to install the subscribe dataflow the sources are not readable anymore.

ci-regexp: dataflow creation cannot fail: SinceViolation

### PR DESCRIPTION
**Pull request by mjibson**
Previously we would go off thread during optimization, allowing sinces to compact past the determined as_of.

Fixes #25375

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

### CODE REVIEW

**Comment by teskje** [comment]
I tried this fix with the repro described in https://github.com/MaterializeInc/materialize/issues/25375#issuecomment-1954023956 and the panic still occurs.

I think the issue is that when we `DROP INDEX`, we drop all read holds we have installed on that index too: https://github.com/mjibson/materialize/blob/e9a250d1916ac1f0b74d89871cdd722b163b9bec/src/adapter/src/coord/ddl.rs#L600-L604

**Comment by mjibson** [comment]
RFAL. Added a commit that fixes #25388.

File: src/environmentd/tests/server.rs [hunk 1]
```diff
@@ -3542,3 +3542,81 @@ async fn test_connection_id() {
...
+                .unwrap();
+
+            let client2 = server.connect().await.unwrap();
+            mz_ore::task::spawn(|| "test", async move {
+                tokio::time::sleep(Duration::from_secs(1)).await;
+                client2.batch_execute("DROP INDEX idx").await.unwrap();
+            });
+
+            match client1
+                .query("SUBSCRIBE (SELECT *, mz_unsafe.mz_sleep(2) FROM t)", &[])
```
Comment (teskje) [inline src/environmentd/tests/server.rs:3583]: This makes the optimizer sleep? TIL!

File: src/adapter/src/coord/sequencer/inner/subscribe.rs [hunk 2]
```diff
@@ -246,6 +251,8 @@ impl Coordinator {
                 return Err(AdapterError::AbsurdSubscribeBounds { as_of, up_to });
             }
         }
+        self.acquire_read_holds_auto_cleanup(ctx.session(), as_of, &bundle, true)
+            .expect("able to acquire read holds at the time that we just got from `determine_timestamp`");
```
Comment (teskje) [inline src/adapter/src/coord/sequencer/inner/subscribe.rs:255]: The read hold will be cleaned up at the end of the transaction, which for a SUBSCRIBE can be very long running, right? If a SUBSCRIBE runs for a day, we wouldn't want to hold its input frontier back to the initial as-of for the whole day too.

Would it be possible to only hold the read hold until `ship_dataflows`? After the dataflow has been installed with the controller, the controller has its own read holds so adapter can release its own.

**Review by teskje — CHANGES_REQUESTED** [review]
I've confirmed that this PR fixes both https://github.com/MaterializeInc/materialize/issues/25375 and https://github.com/MaterializeInc/materialize/issues/25388. But I think we need to make sure that input compaction isn't disabled for the entire time a SUBSCRIBE is running.

**Comment by teskje** [comment]
Cluster tests are failing because in this query:
```
SELECT h.hydrated
FROM mz_internal.mz_subscriptions s
JOIN mz_internal.mz_compute_hydration_statuses h ON (h.object_id = s.id)
JOIN mz_tables t ON (s.referenced_object_ids = list[t.id])
WHERE t.name = 'mz_tables'
```

... `s.referenced_object_ids` has changed from `{<table-id>}` to `{<table-id>, <index-id>}`. The query needs to be changed to check whether that list _contains_ `<table-id>` instead.

**Comment by mjibson** [comment]
Good find. I jiggered those queries and they seem to work now. We don't have many operators or fns on lists, so I seem to need to unnest it in another join?

**Comment by teskje** [comment]
> We don't have many operators or fns on lists, so I seem to need to unnest it in another join?

Yep, looks like it! I also couldn't find a better way.

File: src/adapter/src/coord/sequencer/inner/subscribe.rs (hunk 2 above)
Comment (mjibson) [reply src/adapter/src/coord/sequencer/inner/subscribe.rs:258]: Fixed. Added an intermediate read hold.
