### PR TITLE
compute-client: avoid incorrect history metrics

### LINKED ISSUE #20242: AssertionError: more dataflows than expected in replica history
### What version of Materialize are you using?

a4710805d5

### What is the issue?

Seen in https://buildkite.com/materialize/tests/builds/58589#018906a3-10fc-4f8f-8bee-540cdb88a1dc
```
mzcompose: test case test-github-15531 failed:
Traceback (most recent call last):
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-0c926df81a9c49462-1/materialize/tests/misc/python/materialize/mzcompose/__init__.py", line 416, in test_case
    yield
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-0c926df81a9c49462-1/materialize/tests/test/cluster/mzcompose.py", line 82, in workflow_default
    c.workflow(name)
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-0c926df81a9c49462-1/materialize/tests/misc/python/materialize/mzcompose/__init__.py", line 332, in workflow
    func(self)
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-0c926df81a9c49462-1/materialize/tests/test/cluster/mzcompose.py", line 384, in workflow_test_github_15531
    assert (
AssertionError: more dataflows than expected in replica history
```
I can reproduce it locally via `while true; do bin/mzcompose --find cluster down && bin/mzcompose --find cluster run test-github-15531 || break; done`, took ~40 minutes. It's probably too difficult to bisect this since it's pretty flaky, but I'll try.

### PR DESCRIPTION
**Pull request by teskje**
This PR changes the way the `ComputeCommandHistory` updates its metrics to ensure that no incorrect states are produced while the `reduce` logic is executing. These incorrect states (like command count transiently becomming 0) could be observed by outside consumers, leading to unnecessary confusion.

### Motivation

  * This PR fixes a recognized bug.

Fixes #20242.

### Tips for reviewer

Unfortunately, the new code is more boiler-platey, since we can't deduplicate metrics updates anymore. I tried my best to condense it without overcomplicating things.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - N/A

### CODE REVIEW

**Comment by teskje** [comment]
On second thought, it might be better to instead count the number of "logical" rather than physical commands in the metrics, the same way as the `reduced_count` is calculated. This seems to be more useful to know as a metric than "There is one `CancelPeeks` command, but it may contain one entry or one million." Also, it would allow us to get rid of the separate dataflow count metric, since that would be just the dataflow count metric filtered on the `create_dataflows` label.

File: src/compute-client/src/protocol/history.rs [hunk 1]
```diff
@@ -180,49 +179,92 @@ where
...
-            self.push_inner(ComputeCommand::Peek(peek));
+            self.reduced_count += 1;
+            self.commands.push(ComputeCommand::Peek(peek));
         }
+
+        let metric = self.metrics.command_counts.cancel_peeks.borrow();
         if !live_cancels.is_empty() {
-            self.push_inner(ComputeCommand::CancelPeeks {
+            metric.set(1);
+            self.reduced_count += live_cancels.len();
```
Comment (vmarcos) [inline src/compute-client/src/protocol/history.rs:240]: As you mentioned in a comment, the metric is increased by only one by the command count in `reduced_count` by the length of `live_cancels`. It would be ideal if we would make this consistent. At least originally, the command history size metric was intended to count the physical number of commands in the history, while other logical metrics (like dataflow count or in the future live dataflow count or live peek count) could be used to complement it. That way, we get a a picture of how the representation looks like.

File: src/compute-client/src/protocol/history.rs [hunk 2]
```diff
@@ -180,49 +179,92 @@ where
...
+        } else {
+            metric.set(0);
         }
+
         // Allow compaction only after emmitting peek commands.
+        let metric = self.metrics.command_counts.allow_compaction.borrow();
         if !final_frontiers.is_empty() {
-            self.push_inner(ComputeCommand::AllowCompaction(
+            metric.set(1);
+            self.reduced_count += final_frontiers.len();
```
Comment (vmarcos) [inline src/compute-client/src/protocol/history.rs:252]: Same issue as above: ISTM here that the way we count commands differs between the metric and the `reduced_count` variable.

File: src/compute-client/src/protocol/history.rs [hunk 3]
```diff
@@ -180,49 +179,92 @@ where
...
-
-        self.metrics.reset();
+        // For commands that batch multiple entries, we count the number of entries instead of the
+        // number of commands. This is to ensure that history reduction is not invoked too often.
+        self.reduced_count = 0;
 
         // Reconstitute the commands as a compact history.
+        // When we update `self.metrics`, we need to be careful to not transiently report incorrect
+        // counts, as they would be ovservable by other threads.
+
```
Comment (vmarcos) [inline src/compute-client/src/protocol/history.rs:189]: Above, you probably want to say "observable" instead of "ovservable". Not sure why GH did not show me the suggestion button, sigh.

File: test/cluster/mzcompose.py [hunk 4]
```diff
@@ -380,12 +380,14 @@ def find_command_history_metrics(c: Composition) -> Tuple[int, int, int, int]:
...
     assert (
-        controller_dataflow_count < 5
+        controller_dataflow_count == 1
     ), "more dataflows than expected in controller history"
     assert (
         replica_command_count < 100
     ), "replica history grew more than expected after peeks"
-    assert replica_dataflow_count < 5, "more dataflows than expected in replica history"
+    assert (
+        replica_dataflow_count == 1
```
Comment (vmarcos) [inline test/cluster/mzcompose.py:389]: By the argument in https://github.com/MaterializeInc/materialize/pull/20251#issue-1781218423, it is not clear to me if a simple revert here is enough. For the argument of the PR, ISTM that it is important to ensure here that we do not observe zero. So it would be good to assert that we have at least 1 dataflow in the history (live or not), but we could have more and still be correct?

The test itself could potentially leave 2 dataflows behind after a reduction if it just happens that we sent a `CreateDataflows` and reduced the history before receiving the corresponding `Peek` and `AllowCompaction` for the slow-path `SELECT`. So to avoid a future flake, we might want to refine the condition here compared to what it was previously.

File: src/compute-client/src/protocol/history.rs (hunk 3 above)
Comment (teskje) [reply src/compute-client/src/protocol/history.rs]: Probably because the you get the suggestion button only in the "Files changed" tab, not if you view the per-commit diff.

File: test/cluster/mzcompose.py (hunk 4 above)
Comment (teskje) [reply test/cluster/mzcompose.py]: You are right. I've adjusted the test now to check for >0 as well. It's not clear to me why we couldn't have more than 2 dataflows too, if compaction is sufficiently delayed, so I left the <5 as is.

**Comment by teskje** [comment]
I've rebased the PR on the current main. Now that commands are not batched anymore there is no more confusion about whether we should count physical or logical commands, making this quite straightforward.

**Review by antiguru — APPROVED** [review]

**Comment by teskje** [comment]
TFTR!
