### PR TITLE
adapter: wrap materialized view optimization in `catch_unwind`

### LINKED ISSUE #16324: Catch panics in the optimizer
With https://github.com/MaterializeInc/materialize/pull/16263 merged, we are now able to catch panics in Materialize code. Use that ability to wrap optimizer calls in `catch_unwind`s, to prevent panics in the optimizer from crashing the entire `environmentd` process. Instead, such panics should be converted to optimization/query planning errors and reported to the user.

### PR DESCRIPTION
**Pull request by aalexandrov**
Fixes #16324.
 
### Motivation

  * This PR adds a known-desirable feature.

This fixes #16324 as proposed in an issue -- by wrapping all `optimize` calls in `catch_unwind`. However, fixing this will introduces some test failures because now tests that rely on `mz_unsafe.mz_panic('forced panic')` to break `environmentd` will fail.

### Tips for reviewer

This is ready for review, but needs some more work to fix the broken tests before it can be merged.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by nrainer-materialize** [comment]
> This is ready for review, but needs some more work to fix the broken tests before it can be merged.

Please let QA know when this is resolved. Thanks!

**Comment by aalexandrov** [comment]
I propose to change `FoldConstants` to return new `TransformError` kind if it is about evaluate a map that contains `mz_unsafe.mz_panic(msg)` with a literal `msg` argument. I can then catch this error in all `mz_adapter::coord::sequencer::inner::catch_unwind` and promote it into a panic.

**Comment by aalexandrov** [comment]
I propose to change `FoldConstants` to return new `TransformError` kind if it is about evaluate a map that contains `mz_unsafe.mz_panic(msg)` with a literal `msg` argument. I can then catch this error in all `mz_adapter::coord::sequencer::inner::catch_unwind` and promote it into a panic.

@teskje / @benesch / @frankmcsherry any concerns with that approach?

**Comment by benesch** [comment]
I don't have a strong opinion here, other than that the semantics of `mz_panic` are a persistent thorn in our side, and we should consider in the long term rewriting those tests to find some other way of injecting faults that has more well defined semantics. I'm comfortable continuing to special case it in the short to medium term, as long you feel good about the complexity that introduces, @aalexandrov.

**Comment by aalexandrov** [comment]
Long term it seems more reasonable to me if we can have a dedicated statement that inserts a panic can only be executed if we have special permissions.

```sql
PANIC environmentd;
PANIC CLUSTER REPLICA environmentd;
```

File: src/adapter/src/coord/sequencer/inner.rs [hunk 1]
```diff
@@ -2145,9 +2145,13 @@ impl Coordinator {
             mut optimizer,
         }: PeekStageOptimize,
     ) -> Result<PeekStageRealTimeRecency, AdapterError> {
-        let local_mir_plan = optimizer.optimize(source)?;
-        let local_mir_plan = local_mir_plan.resolve(session, stats);
-        let global_mir_plan = optimizer.optimize(local_mir_plan)?;
+        let global_mir_plan = catch_unwind(true, "peek", || {
+            let local_mir_plan = optimizer.optimize(source)?;
```
Comment (ParkMyCar) [inline src/adapter/src/coord/sequencer/inner.rs:2149]: Overall I like this change, the fewer chances `environmentd` panics the better!

From a design perspective I'm wondering if it might be nice to put the `catch_unwind` inside of the `Optimize` trait? e.g. something like:

```
// private trait
trait OptimizeInternal {
  fn optimize_plan(...) -> Result<_, OptimizerError>
}

// public trait
pub trait Optimize {
  fn optimize(...) -> Result<_, OptimizeError>;
}

impl<T: OptimizeInternal> Optimize for T {
  fn optimize(...) -> Result<_, OptimizerError> {
    catch_unwind(|| self.optimize_plan(...))
  }
}
```
this way we never forget to wrap a call to optimize in `catch_unwind`?

**Review by ParkMyCar — APPROVED** [review]
Overall looks good! Not going to block on the design aspect

File: src/adapter/src/coord/sequencer/inner.rs (hunk 1 above)
Comment (aalexandrov) [reply src/adapter/src/coord/sequencer/inner.rs:2149]: I like that. I'll extend the `Optimize` API tomorrow as proposed.

Comment (ParkMyCar) [reply src/adapter/src/coord/sequencer/inner.rs:2149]: Sounds good to me!

Comment (aalexandrov) [reply src/adapter/src/coord/sequencer/inner.rs]: Finally I just added a second method `catch_unwind_optimize` with default implementation as you proposed in the `Optimize` trait. Once I fix off-thread optimization for the `sequence_explain_~` paths I might reconsider the split between public and internal traits, but for the moment I still need the `optimize` calls in the `explain_~` methods.

**Comment by aalexandrov** [comment]
@nrainer-materialize this should maintain the `mz_unsafe.mz_panic(<literal>)` semantics as long as  `<liter> = 'forced panic'`. AFAICT this means that all the tests will still pass.

**Comment by nrainer-materialize** [comment]
I have triggered a [coverage build](https://buildkite.com/materialize/coverage/builds/340) and will report on the results when they are ready.

**Review by nrainer-materialize — APPROVED** [review]
