### PR TITLE
adapter: correct initial timestamp determination in transactions

### LINKED ISSUE #19398: sentry: panic: Unknown collection identifier u47
Sentry Issue: [DATABASE-BACKEND-2R9](https://materializeinc.sentry.io/issues/4194899611/?referrer=github_integration)

```
panic: Unknown collection identifier u47
  File "panicking.rs", line 575, in rust_begin_unwind
  File "controller.rs", line 2031, in mz_storage_client::controller::Controller<T>::update_read_capabilities
  File "instance.rs", line 890, in mz_compute_client::controller::instance::ActiveInstance<T>::update_write_frontiers
  File "instance.rs", line 1106, in mz_compute_client::controller::instance::ActiveInstance<T>::handle_frontier_uppers
  File "instance.rs", line 1039, in mz_compute_client::controller::instance::ActiveInstance<T>::handle_response
...
(27 additional frame(s) were not displayed)
```

### LINKED ISSUE #19743: panic when transactional workload is mixed with concurrent DDL: cannot fail to peek: CollectionMissing or Dataflow requested as_of not >= since
### What version of Materialize are you using?

v0.58.0-dev (e015c3ee4)

### What is the issue?

When running a concurrent workload that mixes transactional statements, SELECTs and DDLs, the coordinator will panic either like this:

```
thread 'coordinator' panicked at 'cannot fail to peek: CollectionMissing(User(139))', /var/lib/buildkite-agent/builds/buildkite-buil
ders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/util.rs:273:23
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: <core::result::Result<(), mz_compute_client::controller::error::PeekError> as mz_adapter::util::ResultExt<()>>::unwrap_or_term
inate
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/
util.rs:273:23
   3: <mz_adapter::coord::Coordinator>::implement_peek_plan::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/
coord/peek.rs:446:9
   4: <mz_adapter::coord::Coordinator>::implement_peek_plan::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/
coord/peek.rs:296:5
   5: <mz_adapter::coord::Coordinator>::peek_stage_finish::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/
coord/sequencer/inner.rs:2361:13
   6: <mz_adapter::coord::Coordinator>::peek_stage_finish::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/
coord/sequencer/inner.rs:2314:5
   7: <mz_adapter::coord::Coordinator>::sequence_peek_stage::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/
coord/sequencer/inner.rs:2067:74
   8: <mz_adapter::coord::Coordinator>::sequence_peek::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/
coord/sequencer/inner.rs:2026:9
   9: <mz_adapter::coord::Coordinator>::sequence_peek::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/
coord/sequencer/inner.rs:2008:5
  10: <mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/
coord/sequencer.rs:254:70
  11: <mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/
coord/sequencer.rs:51:5
  12: <mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/
coord/command_handler.rs:553:78
  13: <mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/
coord/command_handler.rs:353:5
  14: <mz_adapter::coord::Coordinator>::handle_execute::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/
coord/command_handler.rs:350:61
  15: <mz_adapter::coord::Coordinator>::handle_execute::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/
coord/command_handler.rs:293:5
  16: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_execute::{closure#0}> as core::future::future::Fut
ure>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  17: <mz_adapter::coord::Coordinator>::handle_command::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/
coord/command_handler.rs:79:21
  18: <mz_adapter::coord::Coordinator>::message_command::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/
coord/message_handler.rs:226:33
  19: <mz_adapter::coord::Coordinator>::message_command::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/
coord/message_handler.rs:223:5
  20: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/
coord/message_handler.rs:42:63
  21: <mz_adapter::coord::Coordinator>::serve::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/
coord.rs:1393:37
  22: <tokio::runtime::park::CachedParkThread>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:63
  23: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<<mz_adapter
::coord::Coordinator>::serve::{closure#0}>::{closure#0}>
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:107:5
  24: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<<mz_adapter::coo
rd::Coordinator>::serve::{closure#0}>::{closure#0}>
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:73:5
  25: <tokio::runtime::park::CachedParkThread>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:31
  26: <tokio::runtime::context::BlockingRegionGuard>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/context.rs:315:13
  27: <tokio::runtime::handle::Handle>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/handle.rs:264:9
  28: mz_adapter::coord::serve::{closure#0}::{closure#1}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/
coord.rs:1614:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

or like this:

```
thread 'coordinator' panicked at 'Dataflow oneshot-select-t1065 requested as_of (Antichain { elements: [1686041434420] }) not >= since (Antichain { elements: [1686041435099] })', src/adapter/src/coord/dataflows.rs:260:13
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: <mz_adapter::coord::Coordinator>::finalize_dataflow
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/coord/dataflows.rs:260:13
   3: <mz_adapter::coord::Coordinator>::create_peek_plan::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/coord/peek.rs:279:28
   4: <core::option::Option<mz_adapter::coord::peek::FastPathPlan>>::map_or_else::<core::result::Result<mz_adapter::coord::peek::PeekPlan, mz_adapter::error::AdapterError>, <mz_adapter::coord::Coordinator>::create_peek_plan::{closure#0}, <mz_adapter::coord::Coordinator>::create_peek_plan::{closure#1}>
             at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/option.rs:1064:21
   5: <mz_adapter::coord::Coordinator>::create_peek_plan
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/coord/peek.rs:266:25
   6: <mz_adapter::coord::Coordinator>::plan_peek
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:2494:25
   7: <mz_adapter::coord::Coordinator>::peek_stage_finish::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:2341:25
   8: <mz_adapter::coord::Coordinator>::peek_stage_finish::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:2314:5
   9: <mz_adapter::coord::Coordinator>::sequence_peek_stage::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:2067:74
  10: <mz_adapter::coord::Coordinator>::sequence_peek::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:2026:9
  11: <mz_adapter::coord::Coordinator>::sequence_peek::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:2008:5
  12: <mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/coord/sequencer.rs:254:70
  13: <mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/coord/sequencer.rs:51:5
  14: <mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/coord/command_handler.rs:553:78
  15: <mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/coord/command_handler.rs:353:5
  16: <mz_adapter::coord::Coordinator>::handle_execute::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/coord/command_handler.rs:350:61
  17: <mz_adapter::coord::Coordinator>::handle_execute::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/coord/command_handler.rs:293:5
  18: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_execute::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  19: <mz_adapter::coord::Coordinator>::handle_command::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/coord/command_handler.rs:79:21
  20: <mz_adapter::coord::Coordinator>::message_command::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/coord/message_handler.rs:226:33
  21: <mz_adapter::coord::Coordinator>::message_command::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/coord/message_handler.rs:223:5
  22: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/coord/message_handler.rs:42:63
  23: <mz_adapter::coord::Coordinator>::serve::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/coord.rs:1393:37
  24: <tokio::runtime::park::CachedParkThread>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:63
  25: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}>
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:107:5
  26: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}>
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:73:5
  27: <tokio::runtime::park::CachedParkThread>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:31
  28: <tokio::runtime::context::BlockingRegionGuard>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/context.rs:315:13
  29: <tokio::runtime::handle::Handle>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/handle.rs:264:9
  30: mz_adapter::coord::serve::{closure#0}::{closure#1}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02d3dc3c9ce9a81d6-1/materialize/tests/src/adapter/src/coord.rs:1614:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### LINKED ISSUE #19897: sentry: panic: id does not exist: IdentifierMissing(User(4))
Sentry Issue: [DATABASE-BACKEND-2S8](https://materializeinc.sentry.io/issues/4245748033/?referrer=github_integration)

```
panic: id does not exist: IdentifierMissing(User(4))
  File "panicking.rs", line 575, in rust_begin_unwind
  File "read_policy.rs", line 501, in mz_adapter::coord::Coordinator::update_read_hold
  File "timeline.rs", line 903, in mz_adapter::coord::Coordinator::advance_timelines::{closure#0}::{closure#0}
  File "timeline.rs", line 878, in mz_adapter::coord::Coordinator::advance_timelines::{closure#0}
  File "message_handler.rs", line 68, in mz_adapter::coord::Coordinator::handle_message::{closure#0}
...
(26 additional frame(s) were not displayed)
```

### LINKED ISSUE #20197: sentry: panic: failed to create a delayed capability, the current set does not have an element less than or equa...
Sentry Issue: [DATABASE-BACKEND-2T6](https://materializeinc.sentry.io/issues/4279739726/?referrer=github_integration)

```
panic: failed to create a delayed capability, the current set does not have an element less than or equal to 1687930325000
  File "panicking.rs", line 575, in rust_begin_unwind
  File "capability.rs", line 456, in timely::dataflow::operators::capability::CapabilitySet<T>::delayed::delayed_panic
  File "capability.rs", line 464, in timely::dataflow::operators::capability::CapabilitySet<T>::delayed::{closure#0}
  File "capability.rs", line 463, in timely::dataflow::operators::capability::CapabilitySet<T>::delayed
  File "source_reader_pipeline.rs", line 1224, in mz_storage::source::source_reader_pipeline::handle_message::<T>::{closure#0}
...
(38 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by mjibson**
In #19026 various timestamp functions were refactored to allow `EXPLAIN TIMESTAMP` to reflect (and effect) the current transaction. This is tricky code and the refactor incorrectly changed the behavior of transactions. In a transaction our intention is to find a timestamp during the first statement that will be valid for any other object a user might query later in the transaction, then aquire read holds on all those referenced objects. In that change, the first statement only used the referenced IDs when determining a timestamp, not all nearby (objects in the same schema) IDs. Read holds were still correctly aquired on all nearby objects.

This could cause the transaction's timestamp to not be in advance of the since of other nearby objects. For example, take two objects in the table. At the first query, object A has a since of 10, object B has a since of 20. A first query in the transaction `SELECT * FROM A` would choose 10 as its timestamp, then aquire read holds on A and B at 10. A later query in the transaction `SELECT * FROM B` would choose 10 as its timestamp (which it fetched from the in-progress transaction state), and panic because B's since is in advance of 10.

One of the reasons this happened is the transaction metadata only held on to the TimestampContext. `EXPLAIN TIMESTAMP` needs a larger struct, a TimestampDetermination. Teach the session metadata to track this outer struct so EXPLAIN can use it. This allows us to now only call determine_timestamp once during transaction start, instead of during each query in a transaction. Refactor some of the other read handling code to look more like it did pre-19026.

After this code, the test repro from 19743 no longer causes crashes.

Fixes #19743
Fixes #19897
Fixes #19398

### Motivation

  * This PR fixes a recognized bug.

### Tips for reviewer

* Looking at the code right before 19026 is useful: https://github.com/MaterializeInc/materialize/blob/0e5efd4f537b9a78ba71a76b2e15e0c3191b6c67/src/adapter/src/coord/sequencer/inner.rs#L2242

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - Fix timestamp generation for transactions with multiple statements that could lead to crashes.

### CODE REVIEW

**Comment by mjibson** [comment]
There's no tests for this yet because there weren't before and writing a test scenario for exactly this is not currently within the realm of what our test code can do deterministically. We should add tests for this (both randomized and deterministic), but those may take some days to write and I think it may be better to get this into the release before those because we're already in a known broken state. The by-hand tests I did worked, so *some* tests have been done, just none automated.

**Review by def- — APPROVED** [review]
Based on Philip's local repro the issue seems fixed. A deterministic test would be even better of course.

**Comment by jkosh44** [comment]
I understand how the problem described leads to the errors in #19743, but I'm having trouble figuring out how they lead to the identifier missing errors in the other issues. Would you be able to include a description of that in your explanation?

File: src/adapter/src/coord/sequencer/inner.rs [hunk 1]
```diff
@@ -2116,67 +2116,99 @@ impl Coordinator {
...
         }
 
+        let mut transaction_determination = determination.clone();
+        if !when.is_transactional() {
+            // If the query uses AS OF, ignore the timestamp so that this query can be executed in
+            // this transaction and also to prevent future statements from being locked to this
+            // timestamp.
+            transaction_determination.timestamp_context = TimestampContext::NoTimestamp;
+        };
+        session.add_transaction_ops(TransactionOps::Peeks(transaction_determination))?;
```
Comment (jkosh44) [inline src/adapter/src/coord/sequencer/inner.rs:2210]: Previously we would not call this function if 

`!when.is_transactional() && !matches!(session.transaction(), &TransactionStatus::InTransaction(_))`.

Now we do call this function in this scenario, which is, I believe, why the test are now failing in `transaction.slt`. You're change seems like the correct behavior, but we did seem to intentionally not call this function in implicit transactions when the query was `AS OF` and I can't remember why.

Comment (jkosh44) [reply src/adapter/src/coord/sequencer/inner.rs:2210]: I pushed two commits which fix the tests. The test failure happened because implicit transactions used to skip this call when the current query used `AS OF`. which means that implicit transactions allowed the following scenarios:

- Timestamp independent peeks in a subscribe transaction.
- Timestamp independent subscribes in a peek transaction.

However, these weren't allowed in explicit transactions, because we'd call this function in explicit transactions.


With your changes, we always call this function, so those scenarios were not allowed in both implicit transactions and explicit transactions. The tests were testing theses scenarios in implicit transactions so they started to fail.

My commits update `add_transaction_ops` to allow the mentioned scenarios in both implicit transactions and explicit transactions. This seems more correct that only calling `add_transaction_ops` for explicit transaction. Though the old behavior seemed so intentional that it's a bit confusing.

File: src/adapter/src/coord/sequencer/inner.rs [hunk 2]
```diff
@@ -2116,67 +2116,99 @@ impl Coordinator {
         when: &QueryWhen,
         cluster_id: ClusterId,
         timeline_context: TimelineContext,
-        id_bundle: &CollectionIdBundle,
+        source_bundle: &CollectionIdBundle,
         source_ids: &BTreeSet<GlobalId>,
```
[the remark this answers is not in the document]
Comment (jkosh44) [reply src/adapter/src/coord/sequencer/inner.rs:2120]: Not at all important for this PR, I just wanted to call it out.

File: src/adapter/src/coord/sequencer/inner.rs [hunk 3]
```diff
@@ -2116,67 +2116,99 @@ impl Coordinator {
...
+        // them.
+        let (determination, potential_read_holds) =
+            match session.get_transaction_timestamp_determination() {
+                // If the session already has a timestamp, use that.
+                Some(
+                    determination @ TimestampDetermination {
+                        timestamp_context: TimestampContext::TimelineTimestamp(_, _),
+                        ..
+                    },
+                ) => (determination, None),
```
[the remark this answers is not in the document]
Comment (jkosh44) [reply src/adapter/src/coord/sequencer/inner.rs:2136]: If we have some queries like:
```
BEGIN;
SELECT * FROM t1;
SELECT * FROM t2 AS OF <time>;
```

I think the `AS OF` query will produce the wrong determination here.

File: src/adapter/src/coord/sequencer/inner.rs (hunk 1 above)
Comment (jkosh44) [reply src/adapter/src/coord/sequencer/inner.rs:2210]: As per the our discussion over slack, it's probably best to revert my commits and update this so `add_transaction_ops` is not called for implicit transactions, which matches the old behavior. We can then address the differences between implicit and explicit transactions in a followup PR.

**Comment by benesch** [comment]
You had marked this as closing #20197 but I'm not seeing how that issue is connected to this PR, so I removed that from the PR description. Let me know if I've erred.

File: src/adapter/src/coord/sequencer/inner.rs (hunk 1 above)
Comment (mjibson) [reply src/adapter/src/coord/sequencer/inner.rs]: Reverted this code to what it was before and added a todo.

File: src/adapter/src/coord/sequencer/inner.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (mjibson) [reply src/adapter/src/coord/sequencer/inner.rs]: Concur. Added.

**Comment by jkosh44** [comment]
> I understand how the problem described leads to the errors in https://github.com/MaterializeInc/materialize/issues/19743, but I'm having trouble figuring out how they lead to the identifier missing errors in the other issues. Would you be able to include a description of that in your explanation?

Just wanted to bump this comment. I'm still a bit confused about this.

**Review by jkosh44 — APPROVED** [review]
LGTM

**Comment by mjibson** [comment]
> I understand how the problem described leads to the errors in #19743, but I'm having trouble figuring out how they lead to the identifier missing errors in the other issues. Would you be able to include a description of that in your explanation?

I don't have an explanation about *why* this error happened or why this PR no longer is producing that error. My best guess is that those objects were dropped in other connections, and because the read hold was made for a time in the future, the controller thought it was safe to remove them. Then later when a query comes along for them, they don't exist.
