### PR TITLE
adapter: Drop subscribes when dependencies drop

### LINKED ISSUE #6293: Interrupted TAIL causes an already-deleted source to keep reading from a non-existing Kafka topic
### What version of Materialize are you using?

```
v0.7.2-dev (375d3a5a7)
```

### What was the issue?

This is really weird, but after a TAIL in progress been interrupted, deleting the source and the topic does not seem to prevent MZ from continuing to attempt to read from said topic. The log fills with messages such as:

```
2021-04-01T10:14:43.355211Z ERROR rdkafka::client: librdkafka: Global error: UnknownTopicOrPartition (Broker: Unknown topic or partition): testdrive-tail-source-error-3454290716 [0]: topic does not exist (Broker: Unknown topic or partition)    
```
even though the source has been deleted.

I guess a proper long-term fix for this would require client timeouts and transactional DDL:
- killing TAIL should properly abort and clean up on the server side
- DROPing the source should block or error out if there are pending queries/tails against that source.

### Is the issue reproducible? If so, please provide reproduction instructions.

To reproduce:

1. run this test:

```
$ set int={"type": "record", "name": "field_int", "fields": [ {"name": "f1", "type": "int"} ] }

$ kafka-create-topic topic=tail-source-error

> CREATE MATERIALIZED SOURCE source_error
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-tail-source-error-${testdrive.seed}'
  FORMAT AVRO USING SCHEMA '${int}'
  ENVELOPE NONE

! COPY (TAIL source_error) TO STDOUT;
abc
```
2. As the first execution hangs in COPY, use Ctrl +C to abort the test

3. Run the same test again. This will cause testdrive to delete both the source and the topic as being leftovers from the previous test.

4. Yet, observe as the log fills with lines such as:
```
2021-04-01T10:14:43.355211Z ERROR rdkafka::client: librdkafka: Global error: UnknownTopicOrPartition (Broker: Unknown topic or partition): testdrive-tail-source-error-3454290716 [0]: topic does not exist (Broker: Unknown topic or partition)    
```

### PR DESCRIPTION
**Pull request by jkosh44**
This commit adds the feature that when an object is dropped, all subscribes that depend on that object are also dropped.

Fixes #6293

### Motivation
This PR fixes a recognized bug.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

File: src/sql/src/plan/statement/ddl.rs [hunk 1]
```diff
@@ -3482,13 +3482,16 @@ pub fn plan_drop_item(
...
                 if dependency_prevents_drop(object_type, dep) {
+                    // TODO: Add a hint to add cascade.
                     sql_bail!(
                         "cannot drop {}: still depended upon by catalog item '{}'",
                         scx.catalog.resolve_full_name(catalog_entry.name()),
                         scx.catalog.resolve_full_name(dep.name())
                     );
                 }
             }
+            // TODO(jkosh44) It would be nice to also check if any active subscribe relies on
```
Comment (jkosh44) [inline src/sql/src/plan/statement/ddl.rs:3493]: One way to solve this would be to copy the Global Ids of all subscribe dependencies into `scx`. I just wanted to get some opinions on whether or not that would be wort it before implementing it.

Comment (mjibson) [reply src/sql/src/plan/statement/ddl.rs:3493]: What happens in this case? Does the SUBSCRIBE stall forever?

File: src/environmentd/tests/sql.rs [hunk 2]
```diff
@@ -2309,3 +2309,80 @@ fn test_emit_tracing_notice() {
...
+                    } else {
+                        Ok(())
+                    }
+                })
+                .await
+                .unwrap();
+
+            for table in &tables {
+                client
+                    .batch_execute(&format!("DROP TABLE {table};"))
```
Comment (mjibson) [inline src/environmentd/tests/sql.rs:2360]: This PR looks like it drops subscribes while they are pending. Have the subscribes already exited pending by the time we're running the DROP? That is: what does this test do without the code changes?

File: src/sql/src/plan/statement/ddl.rs (hunk 1 above)
Comment (jkosh44) [reply src/sql/src/plan/statement/ddl.rs:3493]: What happens with this PR is that, even if `CASCADE` is not specified, we allow people to drop an object that a SUBSCRIBE depends on and we stop the SUBSCRIBE. To answer the question directly, no the SUBSCRIBE does not stall forever.

Ideally (I think) we'd like to prevent users from dropping an object that a SUBSCRIBE depends on, unless they specify `CASCADE`.

File: src/environmentd/tests/sql.rs (hunk 2 above)
Comment (jkosh44) [reply src/environmentd/tests/sql.rs:2360]: Without the code changes, this test hangs forever because the subscribe is never dropped.

Comment (jkosh44) [reply src/environmentd/tests/sql.rs:2360]: I think pending is a bit of a misleading term used in the Coordinator, and a better name would have been `active_subscribes`. Once a subscribe enters the `pending_subscribes` map, then a sink has been created for it and it will serve results. The subscribe doesn't leave the `pending_subscribes` map until the subscribe has been cancelled or committed.

Comment (mjibson) [reply src/environmentd/tests/sql.rs:2360]: Ah, I thought it was like peeks. Ok.

**Review by mjibson — APPROVED** [review]

File: src/environmentd/tests/sql.rs (hunk 2 above)
Comment (jkosh44) [reply src/environmentd/tests/sql.rs:2360]: I'm honestly considering changing the name to `active_subscribes` as part of this PR. Would you be on board for that?

Comment (mjibson) [reply src/environmentd/tests/sql.rs:2360]: Yes.

**Comment by philip-stoev** [comment]
I will work on this tomorrow, Friday.

File: src/adapter/src/notice.rs [hunk 3]
```diff
@@ -163,6 +166,12 @@ impl fmt::Display for AdapterNotice {
                     IsolationLevel::Serializable.as_str()
                 )
             }
+            AdapterNotice::DroppedSubscribe { dropped_name } => {
+                write!(
+                    f,
+                "subscribe has been dropped because underlying relation {dropped_name} was dropped"
```
Comment (philip-stoev) [inline src/adapter/src/notice.rs:172]: has been terminated?

**Review by philip-stoev — APPROVED** [review]
Thank you for the test! Works as expected when tried manually in various ways.

If you could extend your test to also assert that the `NOTICE` has been served on the connection that does `SUBSCRIBE` that would be much appreciated.

File: src/adapter/src/notice.rs (hunk 3 above)
Comment (jkosh44) [reply src/adapter/src/notice.rs]: Yeah, I like that wording much better. Just updated it, thanks for the suggestion!

**Comment by jkosh44** [comment]
> If you could extend your test to also assert that the `NOTICE` has been served on the connection that does `SUBSCRIBE` that would be much appreciated.

Just added this to the test.
