### PR TITLE
Plumb librdkafka log level through storage layer

### LINKED ISSUE #10441: Proposal: remove our usage of `log::log_enabled!` using a global `Targets` in `ore`
(This is primarily aimed at @benesch)

The way that `log::log_enabled!` (and my soon-to-be-landed `tracing::enabled!`) work with "per-layer filtering" in tracing means that they return `true` if ANY layer in the subscriber stack returns true. For enabling `rdkafka` `debug` mode, we want to check if only the fmt layer is enabled for the `rdkafka` `target`. The way we currently work around this is by cloning the fmt layer's `target` filter onto all our tracing layers. My understanding is that a primary reason we have seen regressions in the past is because of https://github.com/MaterializeInc/materialize/blob/d10ac1e556d2edb7221cad0146ca041c364273a0/src/dataflow/src/source/kafka.rs#L539 accidentally being enabled.

I suggested https://github.com/tokio-rs/tracing/pull/1889 to the tracing team to create a version of `enabled!` that returned false if ANY of the layers were disabled, but instead they suggested that I just keep a copy of my `Targets` layer around and query that.

So I propose we do the following:

- I implement this api: https://github.com/guswynn/tracing/commit/4890c81a52b218a9746b9e43e8957fa9fe26d59a#diff-c190c4f696381edb3ee10b89ceb505f047616fd2478ce3eb0d24868e356b74c8R341, which I have confirmed will be merged by the tracing folks
- We add a `static FMT_FILTER: once_cell::OnceCell<Targets>` global into `ore`
- materialized main clones the fmt layer's `Targets` and called `OnceCell::set` with it
- We replace the `log_enabled!` lines with `FMT_FILTER.get().map(|t| t.enabled_for("rdkafka", tracing::Level::DEBUG)).unwrap_or(false);`
- We bypass https://github.com/fede1024/rust-rdkafka/blob/master/src/config.rs#L288-L298 in rdkafka by using the https://docs.rs/rdkafka/latest/rdkafka/config/struct.ClientConfig.html#method.set_log_level to set it correctly using the same global
- We then can remove the target filter from the Metrics layer (and in the future, dont worry about the console layer, and the opentel layer)

I think we can ALSO optionally add global `EnvFilter` if we really want field-level filtering, but `EnvFilter` only works globally, for special debugging scenarios.

### Alternatives
- We do nothing, and leave the filters on all layers
  - The tokio-console layer SHOULD already filter out spans that aren't from tokio, so it MAY work as we want it to, but I have not tested how this interacts with `enabled!`
- We come up with some other way to communicate the debug state to rdkafka

### PR DESCRIPTION
**Pull request by benesch**
This is a retooling of #10875 to be as targeted (heh) as possible. Changes from that PR include:

  * Renaming `librdkafka_debug` to `librdkafka_log_level` everywhere, to reflect that the type is now a log level rather than a `bool`.
  * Removal of most changes in src/compute, to avoid needing the compute team's sign off. Only the sink code is touched now, which is meant to be in the storage layer anyway.
  * A single `ConnectorContext` is plumbed throughout the codebase, rather than the coordinator/storage layers using separate context types. I believe the fundamental abstraction here is this `ConnectorContext`. There is a bag of connector-specific options that is configured via CLI parameters rather than `CREATE SOURCE` parameters; both the storage layer and the coordinator need to carry around this same bag, since they both instantiate connectors.

Supersedes #10875.
Fixes #10441.

### Motivation

  * This PR fixes a recognized bug.

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - n/a

### CODE REVIEW

File: src/dataflow-types/src/types.rs [hunk 1]
```diff
@@ -486,6 +486,34 @@ impl Arbitrary for DataflowDescription<Plan, CollectionMetadata, mz_repr::Timest
...
+
+impl ConnectorContext {
+    /// Constructs a connector context from a log filter describing what log
+    /// targets and levels are of interest.
+    pub fn from_log_filter(filter: &tracing_subscriber::filter::Targets) -> ConnectorContext {
+        ConnectorContext {
+            librdkafka_log_level: mz_ore::tracing::target_level(filter, "librdkafka"),
+        }
+    }
+}
```
Comment (benesch) [inline src/dataflow-types/src/types.rs:507]: This new helper method centralizes the logic for extracting the librdkafka level from a `Targets`.

File: src/kafka-util/src/client.rs [hunk 2]
```diff
@@ -90,3 +91,94 @@ pub fn get_partitions<C: ClientContext>(
...
+        assert!(matches!(
+            log_level_from_tracing(Level::INFO),
+            RDKafkaLogLevel::Info
+        ));
+        assert!(matches!(
+            log_level_from_tracing(Level::ERROR),
+            RDKafkaLogLevel::Error
+        ));
+    }
+}
```
Comment (benesch) [inline src/kafka-util/src/client.rs:184]: I'm not convinced this test is worth it. It's just double bookkeeping on `log_level_from_tracing`.

File: src/storage/src/source/kafka.rs [hunk 3]
```diff
@@ -88,13 +87,12 @@ impl SourceReader for KafkaSourceReader {
         _: AwsExternalId,
         restored_offsets: Vec<(PartitionId, Option<MzOffset>)>,
         _: SourceDataEncoding,
-        base_metrics: SourceBaseMetrics,
+        ctx: SourceContext,
```
Comment (benesch) [inline src/storage/src/source/kafka.rs:90]: @guswynn I'm not sure this `SourceContext` type is that valuable? Like, why bundle together the metrics and the librdkafka log level, but none of the other fields?

Comment (benesch) [reply src/storage/src/source/kafka.rs:90]: Oh, also, the AWS external ID should totally go in the connector context! I'll fix that tomorrow.

Comment (guswynn) [reply src/storage/src/source/kafka.rs:90]: yes, I was about to say! after this merges I was gonna move that in!

File: src/dataflow-types/src/types.rs (hunk 1 above)
Comment (guswynn) [reply src/dataflow-types/src/types.rs:507]: looks good!

File: src/kafka-util/src/client.rs (hunk 2 above)
Comment (guswynn) [reply src/kafka-util/src/client.rs:184]: you can remove if you want!

Comment (guswynn) [reply src/kafka-util/src/client.rs:184]: you can remove if you want!

**Review by guswynn — COMMENTED** [review]
looks like good changes on top of my pr! I will add the aws_external_id change on top!

**Comment by benesch** [comment]
Thanks for the additional commit @guswynn! I banged on things a bit more to use `ConnectorContext` in more places throughout the coordinator and SQL layers. Merging!
