### PR TITLE
adapter: prevent OOM found by SQLsmit

### LINKED ISSUE #17898: [SQLsmith] thread 'tokio:work-2' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:525:5
### What version of Materialize are you using?

v0.45.0-dev (486332472)

### How did you install Materialize?

Built from source

### What is the issue?

This panic happened one time after about an hour of SQLsmith running. The query itself was harmless and couldn't reproduce it. So far in other runs I haven't seen this panic. If it happens again, I'll post a Rust backtrace.

Is this expected as an out of memory or does this indicate that we try to allocate an unreasonably large amount of memory?

### Relevant log output

```
thread 'tokio:work-2' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:525:5
```

### PR DESCRIPTION
**Pull request by parker-timmerman**
### Motivation

* This PR fixes a recognized bug:
    * Fixes #17898 

SQLsmith found a bug where we attempt to a `Vec` that wouldn't fit in memory, when returning some results. To fix this we use some heuristics to determine if we think our results would fit in memory, if we don't think this lower bound will fit, then we return an error

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

File: src/expr/src/relation/mod.rs [hunk 1]
```diff
@@ -2769,7 +2769,23 @@ impl RowSetFinishing {
...
+            return Err(format!(
+                "result would exceed max size of {}",
+                ByteSize::b(u64::cast_from(max_result_size))
+            ));
+        }
+
+        // The return Vec can sometimes be quite large, so we'll use the
+        // failable allocation APIs to prevent a panic
+        let mut ret = Vec::new();
+        ret.try_reserve(return_size).map_err(|e| e.to_string())?;
```
Comment (umanwizard) [inline src/expr/src/relation/mod.rs:2787]: I don't agree with this reasoning. In general, any time environmentd OOMs, it is considered a bug. I would rather we panic loudly here to detect OOMs if indeed there are any.

Also, failed allocations crashes, OOMs, and panics are three different things, so even if you kept this logic, you would need to change the comment.

```
~/test_rust ❯❯❯ cat src/bin/test_rust.rs                                                                       ✘ 134 
fn main() {
    let mut v = Vec::<usize>::with_capacity(1_000_000_000_000_000);

    v[100_000_000_000] = 42;

    println!("{v:?}");
}
~/test_rust ❯❯❯ cargo run --release
warning: unused manifest key: lints
    Finished release [optimized] target(s) in 0.03s
     Running `target/release/test_rust`
memory allocation of 8000000000000000 bytes failed
[1]    514248 IOT instruction  cargo run --release
```

Not sure what to call this, but it's not a panic in the Rust sense.

File: src/expr/src/relation/mod.rs [hunk 2]
```diff
@@ -2769,7 +2769,23 @@ impl RowSetFinishing {
             })
             .unwrap_or(limit);
 
-        let mut ret = Vec::with_capacity(return_size);
+        // Bail early if we know our results won't fit into our Vec
+        // 
+        // Note: this check is a _lower bound_ as to how much memory
+        // we'll need for results. Calculating the actual answer would
+        // require us to iterate through all of the rows
+        if return_size * std::mem::size_of::<Row>() > max_result_size {
```
Comment (umanwizard) [inline src/expr/src/relation/mod.rs:2777]: I think this multiplication can overflow, no?

File: src/expr/src/relation/mod.rs (hunk 1 above)
Comment (umanwizard) [reply src/expr/src/relation/mod.rs:2787]: If you don't want to panic, we should at the very least log with `tracing::error` (someday soon, I hope, we will make it so that errors ping the on-call)

File: src/expr/src/relation/mod.rs (hunk 2 above)
Comment (parker-timmerman) [reply src/expr/src/relation/mod.rs]: Great call, updated this to use `saturating_mul` which will saturate at the `usize::MAX`

File: src/expr/src/relation/mod.rs (hunk 1 above)
Comment (parker-timmerman) [reply src/expr/src/relation/mod.rs]: Makes sense to me! I returned this to the prior state where we'll panic if we fail to allocate

**Review by umanwizard — APPROVED** [review]

File: src/expr/src/relation/mod.rs [hunk 3]
```diff
@@ -2769,6 +2769,18 @@ impl RowSetFinishing {
             })
             .unwrap_or(limit);
 
+        // Bail early if we know our results won't fit into our Vec
+        //
+        // Note: this check is a _lower bound_ as to how much memory
+        // we'll need for results. Calculating the actual answer would
+        // require us to iterate through all of the rows
+        if return_size.saturating_mul(std::mem::size_of::<Row>()) >= max_result_size {
```
Comment (jkosh44) [inline src/expr/src/relation/mod.rs:2777]: Small nit, below we use `>` instead of `>=`.

> `if total_bytes > max_result_size {`

Can we use `>` here too? I think you'll have to switch to `checked_mul` to handle the rare case of `max_result_size == usize::MAX`.

Also while you're in here, I think the `total_bytes += new_row.byte_len();` can also overflow. Would you mind updating that one too.

File: src/expr/src/relation/mod.rs [hunk 4]
```diff
@@ -2769,6 +2769,18 @@ impl RowSetFinishing {
             })
             .unwrap_or(limit);
 
+        // Bail early if we know our results won't fit into our Vec
+        //
+        // Note: this check is a _lower bound_ as to how much memory
+        // we'll need for results. Calculating the actual answer would
+        // require us to iterate through all of the rows
```
Comment (antiguru) [inline src/expr/src/relation/mod.rs:2776]: Wait, we're actually iterating through all the rows in the `try_fold` above!

**Review by antiguru — APPROVED** [review]
This seems fine, but it seems we could inline this check with the `try_fold` above (or refactor that part?)

File: src/expr/src/relation/mod.rs (hunk 4 above)
Comment (parker-timmerman) [reply src/expr/src/relation/mod.rs]: ah ha! updated!

File: src/expr/src/relation/mod.rs (hunk 3 above)
Comment (parker-timmerman) [reply src/expr/src/relation/mod.rs]: updated this logic to use just `>`!

as discussed offline, we're okay with not checking for overflow of `total_bytes += new_row.byte_len()`

File: src/expr/src/relation/mod.rs [hunk 5]
```diff
@@ -2757,19 +2757,30 @@ impl RowSetFinishing {
...
+                // if we have more rows or more bytes than we can handle, bail
+                if new_rows > limit || new_bytes > max_result_size {
                     None
                 } else {
-                    Some(new_sum)
+                    Some((new_rows, new_bytes))
                 }
             })
-            .unwrap_or(limit);
+            .unwrap_or((limit, usize::MAX));
```
Comment (jkosh44) [inline src/expr/src/relation/mod.rs:2773]: I'm not sure that this is correct. If `new_rows > limit`, then `num_bytes` may still be less than `max_result_size`. In that case it would be something like `limit * size_of_rows`, however in this code we will have returned `usize::MAX`.

Comment (parker-timmerman) [reply src/expr/src/relation/mod.rs]: Great catch!

Talked offline, updated to not use the `try_fold(...)` and instead `return` and `break` which should give us everything we want

File: src/expr/src/relation/mod.rs [hunk 6]
```diff
@@ -2748,26 +2748,29 @@ impl RowSetFinishing {
...
-            })
-            .unwrap_or(limit);
+        // Count how many rows we'd expand into, returning early from the whole function
+        // if we don't have enough memory to expand the result, or break early from the
+        // iteration once we pass our limit.
+        let mut num_rows = 0;
+        let mut num_bytes = 0;
+        for (row, count) in &rows[offset_nth_row..] {
+            num_rows += count.get();
+            num_bytes += row.byte_len();
```
[the remark this answers is not in the document]
Comment (parker-timmerman) [reply src/expr/src/relation/mod.rs:2758]: Ahh, so `row.byte_len()`is just a size of the single row, so we'd need to multiply it by `count.get()` because that's how many rows we'd end up creating?

[the remark this answers is not in the document]
Comment (umanwizard) [reply src/expr/src/relation/mod.rs]: yes, exactly
