### PR TITLE
persist-txn: Make apply idempotent on closed shard

### LINKED ISSUE #23964: regression: thread 'coordinator' panicked at src/persist-txn/src/lib.rs:485:10: shard should not be closed
### What version of Materialize are you using?

580d2e024d

### What is the issue?

Several Nightly tests have started panicking as follows:

```
legacy-upgrade-materialized-1     | thread 'coordinator' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a2a2b95c29cb0a53-1/materialize/tests/src/persist-txn/src/lib.rs:485:10: shard should not be closed
```

https://buildkite.com/materialize/nightlies/builds/5635

ci-regexp: shard should not be closed

### PR DESCRIPTION
**Pull request by jkosh44**
Applying a transaction is meant to be idempotent, i.e. applying a
transaction multiple times should succeed and not affect the
correctness of the system. Previously, if someone tried to apply a
transaction on a data shard after closing that data shard, then the
system would panic. This commit fixes the described issue by returning
successfully from application on a closed shard.

We know that if a data shard is closed, then all transactions must have
already been applied, so it's safe to return immediately.

Fixes #23964

### Motivation
This PR fixes a recognized bug.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - There are no user-facing behavior changes.

### CODE REVIEW

File: src/persist-txn/src/lib.rs [hunk 1]
```diff
@@ -479,10 +479,10 @@ pub(crate) async fn empty_caa<S, F, K, V, T, D>(
 {
     let name = name();
     let empty: &[((&K, &V), &T, D)] = &[];
-    let mut upper = txns_or_data_write
-        .shared_upper()
-        .into_option()
-        .expect("shard should not be closed");
+    let Some(mut upper) = txns_or_data_write.shared_upper().into_option() else {
+        // Shard is closed.
```
Comment (danhhz) [inline src/persist-txn/src/lib.rs:483]: nit: "Shard is closed, which means the upper must be past init_ts" (and similar below)

**Review by danhhz — APPROVED** [review]
Nice! Great job tracking down the fix!
