### PR TITLE
comm: fix flakes in test_pingpong

### LINKED ISSUE #2291: test_pingpong intermittently fails
It appears to fail about every 30 builds or so.

Log from the buildkite 2288:
```
thread 'test_pingpong' panicked at 'Unexpected failure.
--
  | code-101
  | stderr=```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }', src/libcore/result.rs:1188:5
  | stack backtrace:
  | 0:     0x5597f086f634 - backtrace::backtrace::libunwind::trace::he25250f78ba1020d
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
  | 1:     0x5597f086f634 - backtrace::backtrace::trace_unsynchronized::hd7e25f35da233a1e
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
  | 2:     0x5597f086f634 - std::sys_common::backtrace::_print_fmt::h5578a566a4c2ae4e
  | at src/libstd/sys_common/backtrace.rs:84
  | 3:     0x5597f086f634 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4f87054ec86e936
  | at src/libstd/sys_common/backtrace.rs:61
  | 4:     0x5597f088e19c - core::fmt::write::h393d55821fa8e2cb
  | at src/libcore/fmt/mod.rs:1025
  | 5:     0x5597f086b4a7 - std::io::Write::write_fmt::hc6645302c23e4504
  | at src/libstd/io/mod.rs:1426
  | 6:     0x5597f087174e - std::sys_common::backtrace::_print::he8a0a3ebec70e1d6
  | at src/libstd/sys_common/backtrace.rs:65
  | 7:     0x5597f087174e - std::sys_common::backtrace::print::hc2635fd6c7743ade
  | at src/libstd/sys_common/backtrace.rs:50
  | 8:     0x5597f087174e - std::panicking::default_hook::{{closure}}::h9849388798b72b2b
  | at src/libstd/panicking.rs:193
  | 9:     0x5597f0871441 - std::panicking::default_hook::h66e3afff11b02e47
  | at src/libstd/panicking.rs:210
  | 10:     0x5597f0871e2b - std::panicking::rust_panic_with_hook::hf6d05969fcffff03
  | at src/libstd/panicking.rs:471
  | 11:     0x5597f08719de - rust_begin_unwind
  | at src/libstd/panicking.rs:375
  | 12:     0x5597f088ae9e - core::panicking::panic_fmt::he794217b0df3f806
  | at src/libcore/panicking.rs:84
  | 13:     0x5597f088af97 - core::result::unwrap_failed::hd0067606b17039db
  | at src/libcore/result.rs:1188
  | 14:     0x5597f070ff4a - core::result::Result<T,E>::unwrap::h97b32521172ade1e
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/result.rs:956
  | 15:     0x5597f0716a19 - <tokio::net::tcp::stream::TcpStream as comm::protocol::Connection>::addr::h783e00eb262b0d76
  | at src/comm/protocol.rs:108
  | 16:     0x5597f062a7f2 - comm::protocol::BasicPool<C>::put::h3751e6e382d93224
  | at /workdir/src/comm/protocol.rs:234
  | 17:     0x5597f062543a - comm::protocol::Pool<C>::put::{{closure}}::hc2cb8614ddd81545
  | at /workdir/src/comm/protocol.rs:259
  | 18:     0x5597f06fb7be - std::thread::local::LocalKey<T>::try_with::hdfa266821edaf9ce
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/thread/local.rs:262
  | 19:     0x5597f06f8a9f - std::thread::local::LocalKey<T>::with::hdd6d974a57529423
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/thread/local.rs:239
  | 20:     0x5597f0625232 - comm::protocol::Pool<C>::put::h68878b1826657811
  | at /workdir/src/comm/protocol.rs:259
  | 21:     0x5597f0631f8e - <comm::protocol::Encoder<C,D> as futures_sink::Sink<D>>::poll_close::h679d16ba6d3ecc48
  | at /workdir/src/comm/protocol.rs:522
  | 22:     0x5597f0630baa - <&mut S as futures_sink::Sink<Item>>::poll_close::h82ca5577b3a21ab0
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:133
  | 23:     0x5597f06ae4f7 - <futures_util::sink::close::Close<Si,Item> as core::future::future::Future>::poll::h1372821476b4e460
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/sink/close.rs:36
  | 24:     0x5597f05f9d82 - futures_executor::local_pool::block_on::{{closure}}::h7913381863e73598
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.4/src/local_pool.rs:317
  | 25:     0x5597f05f969b - futures_executor::local_pool::run_executor::{{closure}}::h1f87e34aa16a974f
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.4/src/local_pool.rs:87
  | 26:     0x5597f06f9961 - std::thread::local::LocalKey<T>::try_with::h1df6e6ae9d4e7ef3
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/thread/local.rs:262
  | 27:     0x5597f06f89e2 - std::thread::local::LocalKey<T>::with::hbb800e932e4b495c
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/thread/local.rs:239
  | 28:     0x5597f05f943e - futures_executor::local_pool::run_executor::h7743526dac648b9f
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.4/src/local_pool.rs:83
  | 29:     0x5597f05f9b5f - futures_executor::local_pool::block_on::h09dc939fd7405e54
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.4/src/local_pool.rs:317
  | 30:     0x5597f0630ea0 - <comm::protocol::Encoder<C,D> as core::ops::drop::Drop>::drop::h135eee1533611d3d
  | at /workdir/src/comm/protocol.rs:538
  | 31:     0x5597f05ba361 - core::ptr::real_drop_in_place::h60adfb429c12f0f2
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/ptr/mod.rs:182
  | 32:     0x5597f05b6248 - core::ptr::real_drop_in_place::h008dc54c83e8d2df
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/ptr/mod.rs:182
  | 33:     0x5597f05bab61 - core::ptr::real_drop_in_place::h6a7646707637225d
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/ptr/mod.rs:182
  | 34:     0x5597f05b8aca - core::ptr::real_drop_in_place::h35099050311d4359
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/ptr/mod.rs:182
  | 35:     0x5597f05b6248 - core::ptr::real_drop_in_place::h008dc54c83e8d2df
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/ptr/mod.rs:182
  | 36:     0x5597f05bab61 - core::ptr::real_drop_in_place::h6a7646707637225d
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/ptr/mod.rs:182
  | 37:     0x5597f05bc369 - core::ptr::real_drop_in_place::h944073e9435304cb
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/ptr/mod.rs:182
  | 38:     0x5597f05bfeb1 - core::ptr::real_drop_in_place::hf17b4aceafe6d417
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/ptr/mod.rs:182
  | 39:     0x5597f05a37a1 - pingpong::leader::{{closure}}::hc9b47ca663334fd8
  | at src/comm/examples/pingpong.rs:92
  | 40:     0x5597f05d247f - <std::future::GenFuture<T> as core::future::future::Future>::poll::habb6584d93b511db
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:43
  | 41:     0x5597f05cf8fa - std::future::poll_with_tls_context::h05b954c7ad925c81
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:99
  | 42:     0x5597f05a245a - pingpong::main::{{closure}}::h65c08e9942553554
  | at src/comm/examples/pingpong.rs:59
  | 43:     0x5597f05d1caf - <std::future::GenFuture<T> as core::future::future::Future>::poll::h7adde14ec9b612ab
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:43
  | 44:     0x5597f06e1004 - tokio::runtime::enter::Enter::block_on::hf1aea59b92067f9d
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/enter.rs:101
  | 45:     0x5597f068fb6c - tokio::runtime::thread_pool::ThreadPool::block_on::h48c682a0aff8541f
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/thread_pool/mod.rs:93
  | 46:     0x5597f05c5db4 - tokio::runtime::Runtime::block_on::{{closure}}::h0fcf3d2ef82affde
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/mod.rs:415
  | 47:     0x5597f069dade - tokio::runtime::context::enter::h2460dd7e417f8586
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/context.rs:72
  | 48:     0x5597f06b8ab0 - tokio::runtime::handle::Handle::enter::hefbcfec1703ecac7
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/handle.rs:34
  | 49:     0x5597f05c5c10 - tokio::runtime::Runtime::block_on::h8da5c96f42346e66
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/mod.rs:410
  | 50:     0x5597f060f172 - pingpong::main::h2f2f9288f0b3fa17
  | at src/comm/examples/pingpong.rs:55
  | 51:     0x5597f06118f0 - std::rt::lang_start::{{closure}}::h5efec837b6618f9a
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/rt.rs:67
  | 52:     0x5597f0871873 - std::rt::lang_start_internal::{{closure}}::h4aedff5d9863b36b
  | at src/libstd/rt.rs:52
  | 53:     0x5597f0871873 - std::panicking::try::do_call::h0630fe3da32a089b
  | at src/libstd/panicking.rs:292
  | 54:     0x5597f0874dfa - __rust_maybe_catch_panic
  | at src/libpanic_unwind/lib.rs:78
  | 55:     0x5597f08722c0 - std::panicking::try::hdfbe2fd873ac646c
  | at src/libstd/panicking.rs:270
  | 56:     0x5597f08722c0 - std::panic::catch_unwind::hd7a9c10fa2bee1bc
  | at src/libstd/panic.rs:394
  | 57:     0x5597f08722c0 - std::rt::lang_start_internal::hb8081e0e7e42ac0d
  | at src/libstd/rt.rs:51
  | 58:     0x5597f06118c9 - std::rt::lang_start::h9f3b5d51c3873901
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/rt.rs:67
  | 59:     0x5597f060f9ba - main
  | 60:     0x7fc8ad8fdb97 - __libc_start_main
  | 61:     0x5597f058b9b9 - _start
  | 62:                0x0 - <unknown>
  | ```
  | code=101
  | stdout=```listening on 127.0.0.1:6876...
  | ```
  | stderr=```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }', src/libcore/result.rs:1188:5
  | stack backtrace:
  | 0:     0x5597f086f634 - backtrace::backtrace::libunwind::trace::he25250f78ba1020d
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
  | 1:     0x5597f086f634 - backtrace::backtrace::trace_unsynchronized::hd7e25f35da233a1e
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
  | 2:     0x5597f086f634 - std::sys_common::backtrace::_print_fmt::h5578a566a4c2ae4e
  | at src/libstd/sys_common/backtrace.rs:84
  | 3:     0x5597f086f634 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4f87054ec86e936
  | at src/libstd/sys_common/backtrace.rs:61
  | 4:     0x5597f088e19c - core::fmt::write::h393d55821fa8e2cb
  | at src/libcore/fmt/mod.rs:1025
  | 5:     0x5597f086b4a7 - std::io::Write::write_fmt::hc6645302c23e4504
  | at src/libstd/io/mod.rs:1426
  | 6:     0x5597f087174e - std::sys_common::backtrace::_print::he8a0a3ebec70e1d6
  | at src/libstd/sys_common/backtrace.rs:65
  | 7:     0x5597f087174e - std::sys_common::backtrace::print::hc2635fd6c7743ade
  | at src/libstd/sys_common/backtrace.rs:50
  | 8:     0x5597f087174e - std::panicking::default_hook::{{closure}}::h9849388798b72b2b
  | at src/libstd/panicking.rs:193
  | 9:     0x5597f0871441 - std::panicking::default_hook::h66e3afff11b02e47
  | at src/libstd/panicking.rs:210
  | 10:     0x5597f0871e2b - std::panicking::rust_panic_with_hook::hf6d05969fcffff03
  | at src/libstd/panicking.rs:471
  | 11:     0x5597f08719de - rust_begin_unwind
  | at src/libstd/panicking.rs:375
  | 12:     0x5597f088ae9e - core::panicking::panic_fmt::he794217b0df3f806
  | at src/libcore/panicking.rs:84
  | 13:     0x5597f088af97 - core::result::unwrap_failed::hd0067606b17039db
  | at src/libcore/result.rs:1188
  | 14:     0x5597f070ff4a - core::result::Result<T,E>::unwrap::h97b32521172ade1e
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/result.rs:956
  | 15:     0x5597f0716a19 - <tokio::net::tcp::stream::TcpStream as comm::protocol::Connection>::addr::h783e00eb262b0d76
  | at src/comm/protocol.rs:108
  | 16:     0x5597f062a7f2 - comm::protocol::BasicPool<C>::put::h3751e6e382d93224
  | at /workdir/src/comm/protocol.rs:234
  | 17:     0x5597f062543a - comm::protocol::Pool<C>::put::{{closure}}::hc2cb8614ddd81545
  | at /workdir/src/comm/protocol.rs:259
  | 18:     0x5597f06fb7be - std::thread::local::LocalKey<T>::try_with::hdfa266821edaf9ce
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/thread/local.rs:262
  | 19:     0x5597f06f8a9f - std::thread::local::LocalKey<T>::with::hdd6d974a57529423
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/thread/local.rs:239
  | 20:     0x5597f0625232 - comm::protocol::Pool<C>::put::h68878b1826657811
  | at /workdir/src/comm/protocol.rs:259
  | 21:     0x5597f0631f8e - <comm::protocol::Encoder<C,D> as futures_sink::Sink<D>>::poll_close::h679d16ba6d3ecc48
  | at /workdir/src/comm/protocol.rs:522
  | 22:     0x5597f0630baa - <&mut S as futures_sink::Sink<Item>>::poll_close::h82ca5577b3a21ab0
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:133
  | 23:     0x5597f06ae4f7 - <futures_util::sink::close::Close<Si,Item> as core::future::future::Future>::poll::h1372821476b4e460
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/sink/close.rs:36
  | 24:     0x5597f05f9d82 - futures_executor::local_pool::block_on::{{closure}}::h7913381863e73598
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.4/src/local_pool.rs:317
  | 25:     0x5597f05f969b - futures_executor::local_pool::run_executor::{{closure}}::h1f87e34aa16a974f
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.4/src/local_pool.rs:87
  | 26:     0x5597f06f9961 - std::thread::local::LocalKey<T>::try_with::h1df6e6ae9d4e7ef3
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/thread/local.rs:262
  | 27:     0x5597f06f89e2 - std::thread::local::LocalKey<T>::with::hbb800e932e4b495c
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/thread/local.rs:239
  | 28:     0x5597f05f943e - futures_executor::local_pool::run_executor::h7743526dac648b9f
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.4/src/local_pool.rs:83
  | 29:     0x5597f05f9b5f - futures_executor::local_pool::block_on::h09dc939fd7405e54
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.4/src/local_pool.rs:317
  | 30:     0x5597f0630ea0 - <comm::protocol::Encoder<C,D> as core::ops::drop::Drop>::drop::h135eee1533611d3d
  | at /workdir/src/comm/protocol.rs:538
  | 31:     0x5597f05ba361 - core::ptr::real_drop_in_place::h60adfb429c12f0f2
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/ptr/mod.rs:182
  | 32:     0x5597f05b6248 - core::ptr::real_drop_in_place::h008dc54c83e8d2df
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/ptr/mod.rs:182
  | 33:     0x5597f05bab61 - core::ptr::real_drop_in_place::h6a7646707637225d
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/ptr/mod.rs:182
  | 34:     0x5597f05b8aca - core::ptr::real_drop_in_place::h35099050311d4359
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/ptr/mod.rs:182
  | 35:     0x5597f05b6248 - core::ptr::real_drop_in_place::h008dc54c83e8d2df
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/ptr/mod.rs:182
  | 36:     0x5597f05bab61 - core::ptr::real_drop_in_place::h6a7646707637225d
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/ptr/mod.rs:182
  | 37:     0x5597f05bc369 - core::ptr::real_drop_in_place::h944073e9435304cb
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/ptr/mod.rs:182
  | 38:     0x5597f05bfeb1 - core::ptr::real_drop_in_place::hf17b4aceafe6d417
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/ptr/mod.rs:182
  | 39:     0x5597f05a37a1 - pingpong::leader::{{closure}}::hc9b47ca663334fd8
  | at src/comm/examples/pingpong.rs:92
  | 40:     0x5597f05d247f - <std::future::GenFuture<T> as core::future::future::Future>::poll::habb6584d93b511db
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:43
  | 41:     0x5597f05cf8fa - std::future::poll_with_tls_context::h05b954c7ad925c81
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:99
  | 42:     0x5597f05a245a - pingpong::main::{{closure}}::h65c08e9942553554
  | at src/comm/examples/pingpong.rs:59
  | 43:     0x5597f05d1caf - <std::future::GenFuture<T> as core::future::future::Future>::poll::h7adde14ec9b612ab
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:43
  | 44:     0x5597f06e1004 - tokio::runtime::enter::Enter::block_on::hf1aea59b92067f9d
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/enter.rs:101
  | 45:     0x5597f068fb6c - tokio::runtime::thread_pool::ThreadPool::block_on::h48c682a0aff8541f
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/thread_pool/mod.rs:93
  | 46:     0x5597f05c5db4 - tokio::runtime::Runtime::block_on::{{closure}}::h0fcf3d2ef82affde
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/mod.rs:415
  | 47:     0x5597f069dade - tokio::runtime::context::enter::h2460dd7e417f8586
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/context.rs:72
  | 48:     0x5597f06b8ab0 - tokio::runtime::handle::Handle::enter::hefbcfec1703ecac7
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/handle.rs:34
  | 49:     0x5597f05c5c10 - tokio::runtime::Runtime::block_on::h8da5c96f42346e66
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/mod.rs:410
  | 50:     0x5597f060f172 - pingpong::main::h2f2f9288f0b3fa17
  | at src/comm/examples/pingpong.rs:55
  | 51:     0x5597f06118f0 - std::rt::lang_start::{{closure}}::h5efec837b6618f9a
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/rt.rs:67
  | 52:     0x5597f0871873 - std::rt::lang_start_internal::{{closure}}::h4aedff5d9863b36b
  | at src/libstd/rt.rs:52
  | 53:     0x5597f0871873 - std::panicking::try::do_call::h0630fe3da32a089b
  | at src/libstd/panicking.rs:292
  | 54:     0x5597f0874dfa - __rust_maybe_catch_panic
  | at src/libpanic_unwind/lib.rs:78
  | 55:     0x5597f08722c0 - std::panicking::try::hdfbe2fd873ac646c
  | at src/libstd/panicking.rs:270
  | 56:     0x5597f08722c0 - std::panic::catch_unwind::hd7a9c10fa2bee1bc
  | at src/libstd/panic.rs:394
  | 57:     0x5597f08722c0 - std::rt::lang_start_internal::hb8081e0e7e42ac0d
  | at src/libstd/rt.rs:51
  | 58:     0x5597f06118c9 - std::rt::lang_start::h9f3b5d51c3873901
  | at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/rt.rs:67
  | 59:     0x5597f060f9ba - main
  | 60:     0x7fc8ad8fdb97 - __libc_start_main
  | 61:     0x5597f058b9b9 - _start
  | 62:                0x0 - <unknown>
  | ```
  | ', /cargo/registry/src/github.com-1ecc6299db9ec823/assert_cmd-0.12.0/src/assert.rs:154:13
  | stack backtrace:
  | 0:     0x55af73ef0334 - <unknown>
  | 1:     0x55af73f13bdc - core::fmt::write::h393d55821fa8e2cb
  | 2:     0x55af73e2eaf5 - <unknown>
  | 3:     0x55af73eeab61 - <unknown>
  | 4:     0x55af73ef25ee - <unknown>
  | 5:     0x55af73ef2288 - <unknown>
  | 6:     0x55af73ef2ccb - std::panicking::rust_panic_with_hook::hf6d05969fcffff03
  | 7:     0x55af73ef287e - rust_begin_unwind
  | 8:     0x55af73ef27c0 - std::panicking::begin_panic_fmt::h0ba4167e9ba9b09d
  | 9:     0x55af73ec0f54 - <unknown>
  | 10:     0x55af73e25c30 - <unknown>
  | 11:     0x55af73e2c97e - <unknown>
  | 12:     0x55af73e282ae - <unknown>
  | 13:     0x55af73e3980f - <unknown>
  | 14:     0x55af73efa33a - __rust_maybe_catch_panic
  | 15:     0x55af73e54ac7 - <unknown>
  | 16:     0x55af73e2dfb6 - <unknown>
  | 17:     0x55af73e323b6 - <unknown>
  | 18:     0x55af73efa33a - __rust_maybe_catch_panic
  | 19:     0x55af73e32ce6 - <unknown>
  | 20:     0x55af73ee6b0f - <unknown>
  | 21:     0x55af73ef94b0 - <unknown>
  | 22:     0x7f6c4205b6db - start_thread
  | 23:     0x7f6c41b6c88f - __clone
  | 24:                0x0 - <unknown>
  |  
  |  
  | failures:
  | test_pingpong
  |  
  | test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

```

### PR DESCRIPTION
**Pull request by benesch**
When a comm channel closes, the switchboard attempts to recycle the
underlying `TCPStream` for use by a future comm channel. Recycling
involves calling `peer_addr()` on this `TCPStream` so that the
connection can be sorted into the correct pool.

If the peer closes the connection before the call to `peer_addr()`, the
call to `peer_addr()` will fail with an error like "transport endpoint
is not connected." We would previously panic upon receiving this error,
which caused occasional flakes in test_pingpong in CI (see #2291).

This wasn't a problem in actual deployments of Materialize, as all
workers are long-lived and no peers ever attempt to terminate
connections.

This patch allows the comm::Connection::addr method to return an error,
and the connection pool simply declines to recycle a connection if
retriving its peer address results in an error.

Fix #2291.

### CODE REVIEW

File: src/comm/protocol.rs [hunk 1]
```diff
@@ -138,12 +139,9 @@ impl Connection for UnixStream {
...
     }
 
-    fn addr(&self) -> Self::Addr {
+    fn addr(&self) -> Result<Self::Addr, io::Error> {
         self.peer_addr()
-            .unwrap()
-            .as_pathname()
-            .unwrap()
-            .to_path_buf()
+            .map(|a| a.as_pathname().unwrap().to_path_buf())
```
Comment (ruchirK) [inline src/comm/protocol.rs]: I know this isnt the context where we found the error but should we use expect / check for error instead of this call to unwrap too?

Comment (frankmcsherry) [reply src/comm/protocol.rs]: I'm a fan of this too. I tried to look up how `as_pathname()` could fail, couldn't figure it out in a few minutes, walked away. But, an `expect("something")` would at least document what is up locally so that readers don't need to wonder.

Comment (benesch) [reply src/comm/protocol.rs]: Ack, rewritten with an explanatory comment about why we expect `as_pathname` to return `Some`.
