### PR TITLE
Combine epoch gen bug fix

### LINKED ISSUE #29199: 0dt upgrades: environmentd: fatal: incompatible persist version 0.115.0-dev.0, current: 0.114.0, make sure to upgrade the catalog one version forward at a time
### What version of Materialize are you using?

75a54f5bac

### What is the issue?

I believe what is happening is that https://github.com/MaterializeInc/materialize/pull/29025 and https://github.com/MaterializeInc/materialize/pull/29035 don't work together
#29025 tries to exit with 0 when a deployment has been fenced out, but #29035 again causes us to panic (exit code 134), so environmentd is rebooted again and again. This causes the upgrade test failures in https://buildkite.com/materialize/nightly/builds/9225
```
platform-checks-mz_2-1              | environmentd: fatal: incompatible persist version 0.115.0-dev.0, current: 0.114.0, make sure to upgrade the catalog one version forward at a time
platform-checks-mz_2-1              | thread 'main' panicked at src/environmentd/src/bin/environmentd/main.rs:604:9: environmentd: fatal: incompatible persist version 0.115.0-dev.0, current: 0.114.0, make sure to upgrade the catalog one version forward at a time
```
I'm not sure what the cleanest way to fix this in code is, maybe the catalog version check should use `exit!(0, ...` instead of panicking. Or the `exit!(0, "this deployment has been fenced out");` should happen earlier? The tests still seem to run fine, the old environmentd just keeps restarting and panicking causing logs to fill up with garbage, so for now from testing side I'll silence the panics until we have a better solution

This started occurring now because the release version was bumped and thus the older version we pick also contains #29035 . This is a general problem where we only notice problems with the catalog versioning when we actually bump the release version. Maybe we should have a test that creates a new build with the next version and tries upgrading to it, so that we can catch those issues earlier. I'm not that worried about test issues, but product issues could also hide like that. I'll give it a try.

### PR DESCRIPTION
**Pull request by jkosh44**
This reverts commit b45627abb8f08360a971e272631d38328ca04729, reversing
changes made to d05bdaa2d544a9c44f8cb037cb7dc9db6909322a.

Fixes #29199

### Motivation
This PR fixes a recognized bug.

### Tips for reviewer

The first commit is a revert of a previous revert. The second commit is new logic, that fixes a small issue.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

File: src/catalog/src/durable/persist.rs [hunk 1]
```diff
@@ -220,6 +220,21 @@ impl FenceableToken {
...
+    fn durable_epoch(&self) -> Option<Epoch> {
+        match self {
+            FenceableToken::Initializing {
+                durable_token,
+                legacy_durable_epoch,
+                ..
+            } => durable_token
+                .clone()
+                .map(|token| token.epoch)
+                .or(legacy_durable_epoch.clone()),
```
Comment (jkosh44) [inline src/catalog/src/durable/persist.rs:233]: This branch is technically never taken in the code, meaning this change is technically a no-op. Still, better safe than sorry.

**Review by benesch — APPROVED** [review]
LGTM assuming this is a pure unrevert.
