### PR TITLE
Do not propagate error literals through join inputs

### LINKED ISSUE #6943: panic: called `Result::unwrap()` on an `Err` value: MultipleRowsFromSubquery with valid scalar subquery, impossible WHERE condition
```
2021-06-04T07:56:40.133124Z ERROR panic: called `Result::unwrap()` on an `Err` value: MultipleRowsFromSubquery
thread: <unnamed>
location: src/transform/src/map_lifting.rs:499:63
version: 0.7.4-dev (6b6b217c889591117a91bdbebee6eaea008afcfa)
backtrace:
   0: materialized::handle_panic
             at src/materialized/src/bin/materialized/main.rs:710:21
   1: core::ops::function::Fn::call
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:70:5
   2: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   5: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   6: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   7: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   8: core::result::Result<T,E>::unwrap
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/result.rs:1037:23
      transform::map_lifting::LiteralLifting::action::{{closure}}
             at src/transform/src/map_lifting.rs:499:36
   9: transform::map_lifting::LiteralLifting::action
             at src/transform/src/map_lifting.rs:552:53
  10: transform::map_lifting::LiteralLifting::action
             at src/transform/src/map_lifting.rs:229:32
  11: <transform::map_lifting::LiteralLifting as transform::Transform>::transform
             at src/transform/src/map_lifting.rs:43:24
  12: <transform::Fixpoint as transform::Transform>::transform
             at src/transform/src/lib.rs:114:17
  13: transform::Optimizer::transform
             at src/transform/src/lib.rs:235:13
      transform::Optimizer::optimize
             at src/transform/src/lib.rs:333:9
  14: coord::coord::Coordinator::prep_relation_expr
             at src/coord/src/coord.rs:2893:16
  15: coord::coord::Coordinator::sequence_explain
             at src/coord/src/coord.rs:2597:21
  16: coord::coord::Coordinator::sequence_plan::{{closure}}
             at src/coord/src/coord.rs:1330:25
```

Query:

```
EXPLAIN SELECT  MIN( o_orderkey  )
FROM lineitem  JOIN orders  ON ( l_extendedprice  = o_totalprice  )
WHERE l_commitDATE  = '1997-01-25'
AND o_orderkey  BETWEEN  38  AND  195
AND o_orderdate  = l_commitDATE  + ' 7 MONTHS '
AND o_orderkey  = (  SELECT l_orderkey  FROM lineitem  WHERE l_orderkey  =  1308  )
```

_Originally posted by @philip-stoev in https://github.com/MaterializeInc/materialize/issues/6936#issuecomment-854472196_

### PR DESCRIPTION
**Pull request by asenac**
That may result in them being evaluated before they should, resulting in queries with impossible conditions returning errors, rather than empty results.

Fixes #6943

### CODE REVIEW

File: src/transform/src/map_lifting.rs [hunk 1]
```diff
@@ -494,10 +494,11 @@ impl LiteralLifting {
 
                 let eval_constant_aggr = |aggr: &expr::AggregateExpr| {
                     let temp = repr::RowArena::new();
-                    let eval = aggr
-                        .func
-                        .eval(Some(aggr.expr.eval(&[], &temp).unwrap()), &temp);
-                    MirScalarExpr::literal_ok(
+                    let mut eval = aggr.expr.eval(&[], &temp);
```
Comment (asenac) [inline src/transform/src/map_lifting.rs:508]: This was the original suggested fix, but this code is not exercised anymore. I guess it doesn't hurt, but it would be good to find a way of exercising it.

File: src/transform/src/map_lifting.rs [hunk 2]
```diff
@@ -398,7 +398,18 @@ impl LiteralLifting {
...
+                            .into_iter()
+                            .partition(|f| f.is_literal_ok());
+
+                    // Do not propagate error literals beyond join inputs, since that may result
+                    // in them being propagated to other inputs of the join and evaluated when
+                    // they should not.
+                    if !err_literals.is_empty() {
+                        *input = input.take_dangerous().map(err_literals);
+                    }
+                    input_literals.push(ok_literals);
```
Comment (frankmcsherry) [inline src/transform/src/map_lifting.rs:412]: Won't this potentially change the order of literals? Like, if I have `map([lit, err])` this would lift `lit` and push `err` back down, changing their order.

Comment (asenac) [reply src/transform/src/map_lifting.rs:412]: oh, right, sorry :facepalm:

Comment (frankmcsherry) [reply src/transform/src/map_lifting.rs:412]: I'm happy with the not-very-clever "if there is a single error do nothing", but otherwise I think we only want to strip from the end, or consider some permutation. But imo, this is probably a rare-ish case and optimizing the query may not be worth it for other than personal reasons. :D

Comment (asenac) [reply src/transform/src/map_lifting.rs:412]: I guess the only option here is to do:

```
                // lift literals from each input
                let mut input_literals = Vec::new();
                for input in inputs.iter_mut() {
                    let literals = self.action(input, gets);

                    // Do not propagate error literals beyond join inputs, since that may result
                    // in them being propagated to other inputs of the join and evaluated when
                    // they should not.
                    if literals.iter().any(|l| l.is_literal_err()) {
                        *input = input.take_dangerous().map(literals);
                    } else {
                        input_literals.push(literals);
                    }
                }
```

File: src/transform/src/map_lifting.rs (hunk 1 above)
Comment (frankmcsherry) [reply src/transform/src/map_lifting.rs:508]: Idk if it fights with column_knowledge, but probably
```sql
select sum(1/x) from (select y, 0 as x from table)
```
might do it? The `table` prevents constant folding from applying, and either `map_lifting` or `column_knowledge` gets to do the work.

Comment (asenac) [reply src/transform/src/map_lifting.rs:508]: Oh, good one. Although `sum` doesn't make it crash because we don't consider it as a constant expression when the parameter is a literal, since it still depends on the number of input rows. However, `min` does the job and makes the system crash without this fix:

```sql
select min(1/x) from (select a as y, 0 as x from a);
```

I wonder if we should treat any aggregate function with an error parameter as a constant expression. Diff would be:

```
diff --git a/src/expr/src/relation/mod.rs b/src/expr/src/relation/mod.rs
index f2f0478a7..8ff1810e0 100644
--- a/src/expr/src/relation/mod.rs
+++ b/src/expr/src/relation/mod.rs
@@ -1400,7 +1400,7 @@ impl AggregateExpr {
             | AggregateFunc::MinTimestampTz
             | AggregateFunc::Any
             | AggregateFunc::All => self.expr.is_literal(),
-            _ => false,
+            _ => self.expr.is_literal_err(),
         }
     }
 }
```

Any thoughts on that?

Comment (wangandi) [reply src/transform/src/map_lifting.rs:507]: I'd be in favor of this change since if we have multiple rows in a group, we don't need multiple copies of the error or to sum the error into a super-error.

**Comment by philip-stoev** [comment]
Item No1 . In this branch, I get "internal transform error" for this degenerate query:


```
materialize=> DROP TABLE IF EXISTS t1 CASCADE;
DROP TABLE
materialize=> CREATE TABLE t1 (f1 DOUBLE PRECISION, f2 DOUBLE PRECISION NOT NULL);
CREATE TABLE
materialize=> SELECT * FROM t1 AS a1 JOIN t1 AS a2 ON (a2 . f2 = (SELECT 6 FROM t1)) WHERE a2 . f2 = 9;
ERROR:  internal transform error: fixpoint looped too many times Fixpoint {
```

This is not reproducible with the prior commit.

**Comment by asenac** [comment]
Interesting... in debug mode I get an stack overflow. It seems the plan ends up with a pile of nested arrangements

```
(gdb) frame 89
#89 0x00005555586e3745 in transform::map_lifting::LiteralLifting::action (self=0x1, relation=0x7fffd50f6ee0, gets=0x7fffd5ba8070) at /home/asenac/work/asenac-materialize/src/transform/src/map_lifting.rs:290
290                     let mut literals = self.action(input, gets);
(gdb) print **input
$6 = expr::relation::MirRelationExpr::ArrangeBy{input: 0x7fffd50b0ec0, keys: Vec(size=1) = {Vec(size=0)}}
(gdb) down
#88 0x00005555586e1234 in transform::map_lifting::LiteralLifting::action (self=0x1, relation=0x7fffd50b0d80, gets=0x7fffd5ba8070) at /home/asenac/work/asenac-materialize/src/transform/src/map_lifting.rs:650
650                     let literals = self.action(input, gets);
(gdb) print **input
$7 = expr::relation::MirRelationExpr::ArrangeBy{input: 0x7fffd50b0f60, keys: Vec(size=1) = {Vec(size=0)}}
(gdb) print $7.input
$8 = (*mut expr::relation::MirRelationExpr) 0x7fffd50b0f60
(gdb) print *$7.input
$9 = expr::relation::MirRelationExpr::ArrangeBy{input: 0x7fffd50d0be0, keys: Vec(size=1) = {Vec(size=0)}}
(gdb) print *$9.input
$10 = expr::relation::MirRelationExpr::ArrangeBy{input: 0x7fffd50d1040, keys: Vec(size=1) = {Vec(size=0)}}
(gdb) print *$10.input
$11 = expr::relation::MirRelationExpr::ArrangeBy{input: 0x7fffd50d1860, keys: Vec(size=1) = {Vec(size=0)}}
(gdb) print *$11.input
$12 = expr::relation::MirRelationExpr::ArrangeBy{input: 0x7fffd50d1b80, keys: Vec(size=1) = {Vec(size=0)}}
(gdb) print *$12.input
$13 = expr::relation::MirRelationExpr::ArrangeBy{input: 0x7fffd50d1c20, keys: Vec(size=1) = {Vec(size=0)}}
(gdb)
```

**Comment by asenac** [comment]
LiteralLifting and JoinImplementation are fighting against each other: the former lifts the error literal on top of the arrangement, the latter puts another arrangement on top of the map with the literal, and so on:

```
------------------------------------------------------------------------------------------------------------------------------------------------                                                                
JoinImplementation                                                                                      
------------------------------------------------------------------------------------------------------------------------------------------------                                                                
%0 =                                                               
| Get ? (u57)                                                                                                                                                                                                   
| ArrangeBy ()                                                                                          
                                                                                                                                                                                                                
%1 =                                                                                                    
| Get ? (u57)                                                                                                                                                                                                   
| Filter (#1 = 9)                                                                                       
                                                                                                        
%2 =                                                                                                                                                                                                            
| Get ? (u57)                                                                                                                                                                                                   
| Reduce group=()                                                                                                                                                                                               
| | agg count(true)                                                                                                                                                                                             
| Filter (err: more than one record produced in subquery), (#0 > 1)                                     
| ArrangeBy ()                                                                                                                                                                                                  
| ArrangeBy ()                                                                                          
| ArrangeBy ()                                                                                                                                                                                                  
| ArrangeBy ()                                                                                          
| ArrangeBy ()                                                                                                                                                                                                  
| ArrangeBy ()                                                                                          
| ArrangeBy ()                                                                                                                                                                                                  
| ArrangeBy ()                                                                                          
| ArrangeBy ()                                                                                                                                                                                                  
| ArrangeBy ()                                                                                          
| ArrangeBy ()                                                                                                                                                                                                  
| ArrangeBy ()                                                                                          
| ArrangeBy ()                                                                                                                                                                                                  
| ArrangeBy ()                                                                                          
| ArrangeBy ()                                                                                                                                                                                                  
| ArrangeBy ()                                                     
| ArrangeBy ()                                                                                                                                                                                                  
| ArrangeBy ()                                                                                          
| Map (err: more than one record produced in subquery)                                                                                                                                                          
| ArrangeBy ()                                                                                                                                                                                                  
                                                                                                                                                                                                                
%3 =                                                                                                                                                                                                            
| Join %0 %1 %2                                                                                         
| | implementation = Differential %1 %2.() %0.()                                                        
| | demand = (#0..#3)                                                                                                                                                                                           
| Project (#0..#3)                                                                                      
                                                                                                                                                                                                                
------------------------------------------------------------------------------------------------------------------------------------------------                                                                
LiteralLifting                                                                                                                                                                                                  
------------------------------------------------------------------------------------------------------------------------------------------------                                                                
%0 =                                                                                                                                                                                                            
| Get ? (u57)                                                                                           
| ArrangeBy ()                                                                                                                                                                                                  
                                                                                                        
%1 =                                                                                                                                                                                                            
| Get ? (u57)                                                                                                                                                                                                   
| Filter (#1 = 9)                                                                                                                                                                                               
                                                                                                                                                                                                                
%2 =                                                                                                                                                                                                            
| Get ? (u57)                                                                                           
| Reduce group=()                                                                                                                                                                                               
| | agg count(true)                                                                                     
| Filter (err: more than one record produced in subquery), (#0 > 1)                                                                                                                                             
| ArrangeBy ()                                                     
| ArrangeBy ()                                                                                                                                                                                                  
| ArrangeBy ()                                                                                          
| ArrangeBy ()                                                                                                                                                                                                  
| ArrangeBy ()                                                                                          
| ArrangeBy ()                                                                                                                                                                                                  
| ArrangeBy ()                                                                                          
| ArrangeBy ()                                                                                          
| ArrangeBy ()                                                                                                                                                                                                  
| ArrangeBy ()                                                                                                                                                                                                  
| ArrangeBy ()                                                                                                                                                                                                  
| ArrangeBy ()                                                                                                                                                                                                  
| ArrangeBy ()                                                                                          
| ArrangeBy ()                                                                                                                                                                                                  
| ArrangeBy ()                                                                                          
| ArrangeBy ()                                                                                                                                                                                                  
| ArrangeBy ()                                                                                          
| ArrangeBy ()                                                                                                                                                                                                  
| ArrangeBy ()                                                                                          
| Map (err: more than one record produced in subquery)                                                                                                                                                          
                                                                                                        
%3 =                                                                                                    
| Join %0 %1 %2                                                                                         
| | implementation = Differential %1 %2.() %0.()                                                                                                                                                                
| | demand = (#0..#3)                                                                                   
| Project (#0..#3)                                                                                                                                                                                              
```

**Review by philip-stoev — APPROVED** [review]
From the randomized workload:
- the one panic is now fixed
- no wrong results
- the EXPLAIN plans are unchanged
- this branch and the prior commit agree about which queries deserve the  "more than 1 row returned" error

File: src/transform/src/map_lifting.rs (hunk 1 above)
Comment (asenac) [reply src/transform/src/map_lifting.rs:513]: Agreed. I've added this change.

**Review by wangandi — APPROVED** [review]
