### PR TITLE
repr: fix memory unsafety in RowArena again

### LINKED ISSUE #7168: panic: assertion failed: data.len() >= *offset + size_of::<T>()
This only happens with some minimum-length data. I was not able to reduce either the column count or even any of the json lists here, otherwise it would not repro. I wonder if it has something to do with smallvec/Row encode stuff? Testdrive:

```
$ file-append path=static.csv
93457529,596,9911,30001389,"[3634, 3651]",[21857],null,null,null,"[596, 21857, 3634, 3651]"

> create source fits_data
  (killmail, ship, cost, solarsystem, hi, med, low, rig, sub, items)
  from file '${testdrive.temp-dir}/static.csv'
  format csv with 10 columns

> create materialized view fits as select
  killmail::int4,
  ship::int4,
  cost::int8,
  solarsystem::int4,
  hi::jsonb,
  med::jsonb,
  low::jsonb,
  rig::jsonb,
  sub::jsonb,
  items::jsonb
  from fits_data

> select * from fits
```

```
2021-06-24T21:01:52.732177Z ERROR panic: assertion failed: data.len() >= *offset + size_of::<T>()
thread: tokio:work-30
location: src/repr/src/row.rs:240:5
version: 0.8.1-dev (d645fe2c4a308550e299dc80ea8d2b7c6c59aacf)
backtrace:
   0: materialized::handle_panic
             at src/materialized/src/bin/materialized/main.rs:685:21
   1: core::ops::function::Fn::call
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:70:5
   2: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:495:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   5: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   6: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   7: core::panicking::panic
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:50:5
   8: repr::row::read_copy
             at src/repr/src/row.rs:240:5
      repr::row::read_untagged_bytes
             at src/repr/src/row.rs:255:15
   9: repr::row::read_datum
             at src/repr/src/row.rs:373:25
  10: <repr::row::DatumListIter as core::iter::traits::iterator::Iterator>::next
             at src/repr/src/row.rs:1138:27
  11: core::fmt::builders::DebugList::entries
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/builders.rs:655:22
  12: <repr::row::DatumList as core::fmt::Debug>::fmt
             at src/repr/src/row.rs:169:9
  13: <&T as core::fmt::Debug>::fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/mod.rs:2014:62
  14: core::fmt::builders::DebugTuple::field::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/builders.rs:345:17
      core::result::Result<T,E>::and_then
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/result.rs:704:22
      core::fmt::builders::DebugTuple::field
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/builders.rs:332:23
  15: <repr::scalar::Datum as core::fmt::Debug>::fmt
             at src/repr/src/scalar.rs:30:23
  16: <&T as core::fmt::Debug>::fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/mod.rs:2014:62
  17: core::fmt::write
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/mod.rs:1096:17
  18: core::fmt::Write::write_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/mod.rs:182:9
      alloc::fmt::format
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/fmt.rs:578:5
  19: pgwire::protocol::StateMachine<A>::send_rows::{{closure}}
             at src/pgwire/src/protocol.rs:1231:45
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/future/mod.rs:80:19
  21: pgwire::protocol::StateMachine<A>::send_execute_response::{{closure}}
             at src/pgwire/src/protocol.rs:1014:25
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/future/mod.rs:80:19
  23: pgwire::protocol::StateMachine<A>::execute::{{closure}}
             at src/pgwire/src/protocol.rs:677:29
...
```

### LINKED ISSUE #7169: panic: internal error: entered unreachable code: not a json-compatible datum: Null
This issue is almost identical to #7168 except that the error message is different so I thought it deserved its own issue. The testdrive case is the same except it's a 1000 line file instead of 1 line. Attached instead of inlined due to size.

[testdrive.txt](https://github.com/MaterializeInc/materialize/files/6712193/testdrive.txt)

```
thread: tokio:work-31
location: /home/mjibson/materialize/src/repr/src/adt/jsonb.rs:504:18
version: 0.8.1-dev (d645fe2c4a308550e299dc80ea8d2b7c6c59aacf)
backtrace:
   0: materialized::handle_panic
             at src/materialized/src/bin/materialized/main.rs:685:21
   1: core::ops::function::Fn::call
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:70:5
   2: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   5: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   6: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   7: <repr::adt::jsonb::JsonbDatum as serde::ser::Serialize>::serialize
             at src/repr/src/adt/jsonb.rs:504:18
   8: <serde_json::ser::Compound<W,F> as serde::ser::SerializeSeq>::serialize_element
             at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.64/src/ser.rs:551:22
   9: <repr::adt::jsonb::JsonbDatum as serde::ser::Serialize>::serialize
             at src/repr/src/adt/jsonb.rs:493:21
  10: serde_json::ser::to_writer
             at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.64/src/ser.rs:2158:10
  11: repr::adt::jsonb::JsonbRef::to_writer
             at src/repr/src/adt/jsonb.rs:182:9
  12: <pgrepr::value::jsonb::Jsonb as postgres_types::ToSql>::to_sql
             at src/pgrepr/src/value/jsonb.rs:28:9
  13: pgrepr::value::Value::encode_binary
             at src/pgrepr/src/value.rs:338:33
  14: pgrepr::value::Value::encode
             at src/pgrepr/src/value.rs:259:31
  15: <pgwire::codec::Codec as tokio_util::codec::encoder::Encoder<pgwire::message::BackendMessage>>::encode
             at src/pgwire/src/codec.rs:283:25
  16: <tokio_util::codec::framed_impl::FramedImpl<T,U,W> as futures_sink::Sink<I>>::start_send
             at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-util-0.6.7/src/codec/framed_impl.rs:238:9
  17: <tokio_util::codec::framed::Framed<T,U> as futures_sink::Sink<I>>::start_send
             at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-util-0.6.7/src/codec/framed.rs:279:9
  18: futures_util::sink::buffer::Buffer<Si,Item>::try_empty_buffer
             at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/sink/buffer.rs:41:13
  19: <futures_util::sink::buffer::Buffer<Si,Item> as futures_sink::Sink<Item>>::poll_ready
             at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/sink/buffer.rs:80:17
  20: <&mut S as futures_sink::Sink<Item>>::poll_ready
             at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.15/src/lib.rs:118:9
  21: <ore::future::Enqueue<Si,Item> as core::future::future::Future>::poll
             at src/ore/src/future.rs:447:19
  22: pgwire::codec::FramedConn<A>::send::{{closure}}
             at src/pgwire/src/codec.rs:124:12
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/future/mod.rs:80:19
  24: pgwire::codec::FramedConn<A>::send_all::{{closure}}
             at src/pgwire/src/codec.rs:140:13
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/future/mod.rs:80:19
  26: pgwire::protocol::StateMachine<A>::send_rows::{{closure}}
             at src/pgwire/src/protocol.rs:1252:21
  27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/future/mod.rs:80:19
  28: pgwire::protocol::StateMachine<A>::send_execute_response::{{closure}}
             at src/pgwire/src/protocol.rs:1014:25
...
```

### PR DESCRIPTION
**Pull request by benesch**
When we switched Row to use a SmallVec as its backing store (#3248), we
accidentally made RowArena unsound. It is NOT valid for the RowArena to
hand out references to a SmallVec, as the SmallVec might be using inline
storage, and the address of that inline storage will change if the
vector containing the SmallVec reallocates.

Fix the unsafety by forcing the SmallVec to spill to the heap, and
storing *that* vector in the RowArena.

In practice, the memory safety was only observed when packing wide rows
that contained small lists, but still scary to think how long this has
been present.

Fix #7168.
Fix #7169.

### CODE REVIEW

File: src/repr/src/row.rs [hunk 1]
```diff
@@ -1256,17 +1247,18 @@ impl RowArena {
...
+            //   * We only ever append to self.inner, so the row data will live
             //     as long as the arena.
-            //   * We return a reference to the heap allocation inside the row,
-            //     so it's okay if self.owned_rows reallocates and moves the
-            //     row.
-            //   * We don't allow access to the row itself, so row.data will
+            //   * We force the row data into its own heap allocation--
+            //     importantly, we do NOT store the SmallVec, which might be
+            //     storing data inline on the stack--so it's okay if self.inner=
+            //     reallocates and moves the row.
```
Comment (frankmcsherry) [inline src/repr/src/row.rs:1258]: Just to check my understanding, is the problem stack storage, or that when the vector resizes it may invalidate the (heap allocated) `SmallVec` itself, when it moves it to a new allocation?

**Review by frankmcsherry — APPROVED** [review]
I think this looks good, but I didn't notice the problem before. I guess, general rule of thumb is don't allow unsafe code that relies on other types whose implementations could change.

If we want in the future, the `ColumnarStack` from `columnation` solves the same problem, but with a logarithmic number of allocations rather than linear. But, probably good to go double check that it doesn't do the same sort of thing (I suspect my PR that tries it out does for our backing storage does).

File: src/repr/src/row.rs (hunk 1 above)
Comment (benesch) [reply src/repr/src/row.rs]: Oops, I got this right in the commit message but not here. Sorry, it's late. The issue was that if the `SmallVec` was using inline storage, that inline storage would move around as the outer `Vec` reallocated. And we were just happily handing out a pointer to that moveable inline storage. That data wasn't actually on the stack; it was just part of the outer heap allocation instead of an independent heap allocation.

Comment (frankmcsherry) [reply src/repr/src/row.rs]: That makes sense, and I just wanted to make sure I understood. Thanks!
