### PR TITLE
storage: relax check on dependency since when upper.is_empty()

### LINKED ISSUE #28634: parallel-workload: 0dt: thread 'coordinator' panicked at src/storage-controller/src/lib.rs:686:17: dependency since has advanced past dependent (u182) upper
### What version of Materialize are you using?

6fcb05b2b0

### What is the issue?

Seen in [Parallel Workload (0dt deploy)](https://buildkite.com/materialize/nightly/builds/8866#01910369-1584-4867-9d53-62acb20de9c9):
```
thread 'coordinator' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00d97154d6ec58e92-1/materialize/test/src/storage-controller/src/lib.rs:686:17:
dependency since has advanced past dependent (u182) upper 

                            dependent (u182): upper Antichain { elements: [] } 

                            dependency since Antichain { elements: [] }
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: <mz_storage_controller::Controller<mz_repr::timestamp::Timestamp> as mz_storage_client::controller::StorageController>::create_collections::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00d97154d6ec58e92-1/materialize/test/src/storage-controller/src/lib.rs:686:17
   3: <tracing::instrument::Instrumented<<mz_storage_controller::Controller<mz_repr::timestamp::Timestamp> as mz_storage_client::controller::StorageController>::create_collections::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
   4: <mz_storage_controller::Controller<mz_repr::timestamp::Timestamp> as mz_storage_client::controller::StorageController>::create_collections::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00d97154d6ec58e92-1/materialize/test/src/storage-controller/src/lib.rs:491:5
   5: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(), mz_storage_types::controller::StorageError<mz_repr::timestamp::Timestamp>>>>> as core::future::future::Future>::poll
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
   6: <mz_adapter::coord::Coordinator>::bootstrap_storage_collections::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00d97154d6ec58e92-1/materialize/test/src/adapter/src/coord.rs:2333:14
   7: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::bootstrap_storage_collections::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
   8: <mz_adapter::coord::Coordinator>::bootstrap_storage_collections::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00d97154d6ec58e92-1/materialize/test/src/adapter/src/coord.rs:2238:5
   9: <mz_adapter::coord::Coordinator>::bootstrap::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00d97154d6ec58e92-1/materialize/test/src/adapter/src/coord.rs:1819:46
  10: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::bootstrap::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  11: <mz_adapter::coord::Coordinator>::bootstrap::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00d97154d6ec58e92-1/materialize/test/src/adapter/src/coord.rs:1725:5
  12: mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00d97154d6ec58e92-1/materialize/test/src/adapter/src/coord.rs:3589:60
  13: <tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  14: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:63
  15: tokio::runtime::coop::with_budget::<core::task::poll::Poll<core::result::Result<(), mz_adapter::error::AdapterError>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:107:5
  16: tokio::runtime::coop::budget::<core::task::poll::Poll<core::result::Result<(), mz_adapter::error::AdapterError>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:73:5
  17: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:31
  18: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/blocking.rs:66:9
  19: <tokio::runtime::handle::Handle>::block_on::<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/handle.rs:310:22
  20: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::handle::Handle>::block_on<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}>::{closure#0}, core::result::Result<(), mz_adapter::error::AdapterError>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/runtime.rs:65:16
  21: <tokio::runtime::handle::Handle>::block_on::<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/handle.rs:309:9
  22: mz_adapter::coord::serve::{closure#0}::{closure#2}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-00d97154d6ec58e92-1/materialize/test/src/adapter/src/coord.rs:3588:33
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
This didn't cause a test failure. Is this another panic we should just ignore in CI during 0dt deploys?
ci-regexp: dependency since has advanced past dependent

### PR DESCRIPTION
**Pull request by aljoscha**
Fixes #28634

Apparently, this can happen! But when the upper is empty, we don't really care about what dependency since we get: we don't write anymore.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

File: src/storage-client/src/storage_collections.rs [hunk 1]
```diff
@@ -1554,6 +1554,7 @@ where
                         // as far the dependent's upper.
                         mz_ore::soft_assert_or_log!(
                             write_frontier.elements() == &[T::minimum()]
+                                || write_frontier.is_empty()
                                 || PartialOrder::less_than(&dependency_since, write_frontier),
```
Comment (teskje) [inline src/storage-client/src/storage_collections.rs:1558]: I'm not fully understanding the context of this check, but reading the comment above I wonder why this isn't using `PartialOrder::less_equal`? The comment says that the dependency since can not be "in advance of"/"past" the upper, both of which I think mean that the since cannot be _greater_ than the upper.

Is them being equal fine? If so, we can change the check to `less_equal` and can drop the `write_frontier.is_empty()` check. If it's not fine, can we update the comment to say why?

Comment (aljoscha) [reply src/storage-client/src/storage_collections.rs:1558]: It's using "advanced" they way timely/dd often usex "beyond", where

> "A time is beyond a frontier" == frontier.less_equal(time)

Though I think that meaning is less clearly defined/used when talking about two frontiers, maybe.

And it's important here that the since of dependencies _not_ be beyond the upper of the dependent. In practice, the dependency here will be a remap shard and the dependent will be a source/source exports. If the since is beyond (including if it's equal) we cannot differentiate between updates that have already been written to the source/export shard and new ones.

We try and uphold this requirement by using a `step_back` read policy here, for example: https://github.com/MaterializeInc/materialize/blob/f55491fa36fa5a9d18cd6dc4f7312a38c677b5c3/src/storage-controller/src/lib.rs#L763

Comment (teskje) [reply src/storage-client/src/storage_collections.rs:1558]: > It's using "advanced" they way timely/dd often usex "beyond", where

I was aware of that usage of "beyond" but didn't know that "in advance of" and "past" mean the same thing. Is there any word for `frontier.less_than(time)`? "Strictly in advance of"?

> If the since is beyond (including if it's equal) we cannot differentiate between updates that have already been written to the source/export shard and new ones.

Makes sense! Would be cool if you could update the comment to also say this. The current explanation ("If the  dependency since advanced past the dependent's upper, the dependent cannot read data from the dependency at its upper.") would not require that the since is strictly less than the upper.

Also could you update the comment to explain the new `write_frontier.is_empty()` edge case?

Comment (aljoscha) [reply src/storage-client/src/storage_collections.rs:1565]: pushed the change! ptal 🙏

**Review by teskje — APPROVED** [review]
Looks great, thanks!
