### PR TITLE
sql: Prevent SHOW commands in views

### LINKED ISSUE #20188: Creating matviews of SHOWs causes error: corrupt catalog: failed to deserialize item u2 (u2.u7.mat_connections): no schema has been selected to create in
### What version of Materialize are you using?

661a46e23be610acfbb44feec32b23a4888cb5ee

### What is the issue?

```
$ cat test/testdrive/x.td
> CREATE MATERIALIZED VIEW mat_clusters AS SELECT name FROM (SHOW CLUSTERS);
> CREATE MATERIALIZED VIEW mat_connections AS SELECT name, type FROM (SHOW CONNECTIONS);
> CREATE MATERIALIZED VIEW mat_databases AS SELECT name FROM (SHOW DATABASES);
> CREATE MATERIALIZED VIEW mat_objects AS SELECT name FROM (SHOW OBJECTS);
> CREATE MATERIALIZED VIEW mat_schemas AS SELECT name FROM (SHOW SCHEMAS);
> CREATE MATERIALIZED VIEW mat_secrets AS SELECT name FROM (SHOW SECRETS);
> CREATE MATERIALIZED VIEW mat_sinks AS SELECT name, type, size FROM (SHOW SINKS);
> CREATE MATERIALIZED VIEW mat_sources AS SELECT name, type, size FROM (SHOW SOURCES);
> CREATE MATERIALIZED VIEW mat_tables AS SELECT name FROM (SHOW TABLES);
> CREATE MATERIALIZED VIEW mat_views AS SELECT name FROM (SHOW VIEWS);

> DROP MATERIALIZED VIEW mat_clusters
> DROP MATERIALIZED VIEW mat_connections
> DROP MATERIALIZED VIEW mat_databases
> DROP MATERIALIZED VIEW mat_objects
> DROP MATERIALIZED VIEW mat_schemas
> DROP MATERIALIZED VIEW mat_secrets
> DROP MATERIALIZED VIEW mat_sinks
> DROP MATERIALIZED VIEW mat_sources
> DROP MATERIALIZED VIEW mat_tables
> DROP MATERIALIZED VIEW mat_views

$ bin/mzcompose --find testdrive down && bin/mzcompose --find testdrive run default x.td
[...]
> DROP MATERIALIZED VIEW mat_clusters
rows match; continuing at ts 1687884795.6343117
^^^ +++
x.td:12:1: error: corrupt catalog: failed to deserialize item u2 (u2.u6.mat_connections): no schema has been selected to create in
     |
  11 |
  12 | > DROP MATERIALIZED VIEW mat_clusters
     | ^
+++ !!! Error Report
1 errors were encountered during execution
files involved: x.td
```
But from outside of testdrive (via psql) this works fine, so I'm a bit confused.

### PR DESCRIPTION
**Pull request by jkosh44**
When a view is created with a SHOW command, the create SQL definition will have the explicit `SHOW` command in it. Many `SHOW` commands will expand into a sub-query that involves the current schema of the executing user. When Materialize restarts and tries to re-plan these queries, it will only have access to the raw `SHOW` command and have no idea what schema to use. As a result Materialize will fail to boot.

Some `SHOW` commands are ok, like `SHOW CLUSTERS`, and there are probably other ways around this issue. Such as expanding the `SHOW` command in the SQL definition. Or explicitly using an unmaterializable function in the HIR to prevent problematic views. For now, we just disallow any `SHOW` commands in views since the issue exists in prod and can corrupt catalogs.

This is a potentially breaking change since some existing views with
`SHOW` might exist in production.

Fixes #20188

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - Prevent creating views and materializable views with `SHOW` commands.

### CODE REVIEW

**Review by def- — APPROVED** [review]
Seems to work.

File: src/testdrive/src/action/sql.rs [hunk 1]
```diff
@@ -127,6 +127,7 @@ pub async fn run_sql(mut cmd: SqlCommand, state: &mut State) -> Result<ControlFl
         | Statement::CreateSource { .. }
         | Statement::CreateTable { .. }
         | Statement::CreateView { .. }
+        | Statement::CreateMaterializedView { .. }
```
Comment (mjibson) [inline src/testdrive/src/action/sql.rs:130]: Ergh hard to believe this wasn't here before.

File: src/sql/src/plan/query.rs [hunk 2]
```diff
@@ -1469,9 +1469,27 @@ fn plan_set_expr(
...
+            // Some `SHOW` commands are ok, like `SHOW CLUSTERS`, and there are probably other ways
+            // around this issue. Such as expanding the `SHOW` command in the SQL definition. For
+            // now we just disallow any `SHOW` commands in views.
+            //
+            // Ideally, the `SHOW` commands that use the current schema would expand to use the
+            // `current_schema()` function, instead of hard-coding the current schema id, so that
+            // planning can correctly identify that they are unmaterializable. However, that's a
+            // little tricky because `current_schema()` returns a schema name not id, which is what
+            // we need.
+            if qcx.lifetime == QueryLifetime::Static {
```
Comment (mjibson) [inline src/sql/src/plan/query.rs:1487]: Wait how does this still allow `SELECT` statements to continue working? Don't those also call this planning function?

Comment (jkosh44) [reply src/sql/src/plan/query.rs:1487]: For `SELECT` the `qcx.lifetime` will be `QueryLifetime::OneShot`.

Comment (mjibson) [reply src/sql/src/plan/query.rs:1487]: Ohh right. I'm not sure what I was thinking?

**Review by mjibson — APPROVED** [review]

**Comment by jkosh44** [comment]
There are currently no views that use `SHOW` commands in production so I'm merging this PR.
