### PR TITLE
adapter: fix explain timestamp during transactional contexts

### LINKED ISSUE #18950: adapter: `EXPLAIN TIMESTAMP` is not run transactionally
### What version of Materialize are you using?

v.0.53.0-dev

### How did you install Materialize?

Built from source

### What is the issue?

When `EXPLAIN TIMESTAMP` is run as part of a transaction, it should do the following three things:
- Select a transaction timestamp if one hasn't been selected yet.
- Acquire read holds if they haven't been acquired yet.
- Always return the same value for `query timestamp`.

Currently it doesn't do those three things.

### Relevant log output

```source
materialize=> CREATE TABLE t (a INT);
CREATE TABLE
materialize=> BEGIN;
BEGIN
materialize=*> EXPLAIN TIMESTAMP FOR SELECT * FROM t;
                                 Timestamp                                 
---------------------------------------------------------------------------
                 query timestamp: 1682438637118 (2023-04-25 16:03:57.118) +
           oracle read timestamp: 1682438637118 (2023-04-25 16:03:57.118) +
 largest not in advance of upper: 1682438637118 (2023-04-25 16:03:57.118) +
                           upper:[1682438637119 (2023-04-25 16:03:57.119)]+
                           since:[1682438636000 (2023-04-25 16:03:56.000)]+
         can respond immediately: true                                    +
                        timeline: Some(EpochMilliseconds)                 +
                                                                          +
 source materialize.public.t (u1, storage):                               +
                   read frontier:[1682438636000 (2023-04-25 16:03:56.000)]+
                  write frontier:[1682438637119 (2023-04-25 16:03:57.119)]+
 
(1 row)

materialize=*> EXPLAIN TIMESTAMP FOR SELECT * FROM t;
                                 Timestamp                                 
---------------------------------------------------------------------------
                 query timestamp: 1682438638120 (2023-04-25 16:03:58.120) +
           oracle read timestamp: 1682438638120 (2023-04-25 16:03:58.120) +
 largest not in advance of upper: 1682438638120 (2023-04-25 16:03:58.120) +
                           upper:[1682438638121 (2023-04-25 16:03:58.121)]+
                           since:[1682438637000 (2023-04-25 16:03:57.000)]+
         can respond immediately: true                                    +
                        timeline: Some(EpochMilliseconds)                 +
                                                                          +
 source materialize.public.t (u1, storage):                               +
                   read frontier:[1682438637000 (2023-04-25 16:03:57.000)]+
                  write frontier:[1682438638121 (2023-04-25 16:03:58.121)]+
 
(1 row)
```

### PR DESCRIPTION
**Pull request by rkrishn7**
### Motivation

Resolves #18950

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

File: src/adapter/src/coord/sequencer/inner.rs [hunk 1]
```diff
@@ -2842,15 +2838,55 @@ impl Coordinator {
...
+            if !timedomain_id_bundle.is_empty() && !self.txn_reads.contains_key(&session.conn_id())
+            {
+                if let Some(timestamp) = determination.timestamp_context.timestamp() {
+                    let read_holds =
+                        self.acquire_read_holds(timestamp.clone(), &timedomain_id_bundle);
+                    self.txn_reads.insert(session.conn_id(), read_holds);
+                }
+            }
+        }
+
```
Comment (jkosh44) [inline src/adapter/src/coord/sequencer/inner.rs:2889]: All of this logic makes sense to me, I'm assuming you got it from the sequence peek methods? I'm slightly concerned about duplicating this logic between peeks and explain timestamps. The logic is a bit nuanced and it will be easy for it to accidentally diverge in the future. Is there some way to avoid duplicating this?

File: src/environmentd/tests/sql.rs [hunk 2]
```diff
@@ -1291,6 +1291,71 @@ fn test_explain_timestamp_json() {
...
+            assert_eq!(timestamp, *explain_timestamp);
+        } else {
+            query_timestamp = Some(*explain_timestamp);
+        }
+
+        for source in &explain.sources {
+            for timestamp in &source.read_frontier {
+                assert_eq!(*timestamp, query_timestamp.unwrap());
+            }
+        }
```
[the remark this answers is not in the document]
Comment (rkrishn7) [reply src/environmentd/tests/sql.rs:1342]: Ah, yeah. I previously incorrectly assumed that acquiring read holds as of T is guaranteed to work. However, it looks like in the case that T is beyond a source's `read_frontier`, we acquire a hold at that time instead. I hadn't considered this, but defaulting to acquiring the hold at the lowest possible time that the source supports makes sense to me.

Thanks for catching that! I'll try and update the test case accordingly

File: src/environmentd/tests/sql.rs [hunk 3]
```diff
@@ -1291,6 +1291,71 @@ fn test_explain_timestamp_json() {
...
+
+        std::thread::sleep(Duration::from_millis(5 * i));
```
[the remark this answers is not in the document]
Comment (rkrishn7) [reply src/environmentd/tests/sql.rs:1344]: Yeah that's what I'm attempting to do. 

However, I'm not sure if sleeping by such a small amount sufficiently increases this likelihood, given that I believe it's dependent on `t1`'s read frontier advancing. Will leave a comment at the very least, but definitely open to suggestions on how we can fortify this if you feel its likely to be flaky.

File: src/adapter/src/coord/sequencer/inner.rs (hunk 1 above)
Comment (rkrishn7) [reply src/adapter/src/coord/sequencer/inner.rs:2889]: Definitely, was thinking that as well. I think both paths share pretty much all of this logic so I'll try factoring it out

File: src/environmentd/tests/sql.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (jkosh44) [reply src/environmentd/tests/sql.rs:1342]: Ah ok, yeah in general acquiring the read hold isn't guaranteed to work, though I think in this particular scenario we know that it will work because we chose the read hold time based on the read frontier's of the objects. On the other hand, if we do successfully acquire a read hold at time `t` on object `o`, then we cannot assert `o`'s read frontier is equal to `t`. We can only assert that the read frontier is less than or equal to `t`.

File: src/adapter/src/coord/sequencer/inner.rs (hunk 1 above)
Comment (rkrishn7) [reply src/adapter/src/coord/sequencer/inner.rs]: @jkosh44 Did a couple things:

1. Lifted the logic to use transactional timestamp context to `determine_timestamp`. Feels like this is an appropriate place for it, but let me know if I’m missing something.
2. Factored out common logic around determining a query’s timestamp, acquiring read holds, and tracking txn ops into `sequence_peek_timestamp`. I couldn’t quite see reusing `sequence_peek_stage` as the planning stage deals with dataflow-specific logic that `EXPLAIN TIMESTAMP` doesn’t depend on.

Appreciate any and all feedback!

File: src/environmentd/tests/sql.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (rkrishn7) [reply src/environmentd/tests/sql.rs]: > if we do successfully acquire a read hold at time t on object o, then we cannot assert o's read frontier is equal to t. We can only assert that the read frontier is less than or equal to t.

The first sentence here makes sense to me, but not the second. If `o` has already compacted past `t`, then we acquire the hold at `o`'s read frontier, right? That's what I gathered from: https://github.com/MaterializeInc/materialize/blob/fa6bb00645617ac4dc9ccbff26f9181ef1d3c5fa/src/adapter/src/coord/read_policy.rs#L389-L432

Definitely could be reading that incorrectly, though.

I've updated the test to check that the initially reported read frontier does not change on subsequent iterations. If my logic is right above, then this is the most meaningful assertion I can think of.

File: src/environmentd/tests/sql.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (rkrishn7) [reply src/environmentd/tests/sql.rs]: Makes sense! Updated

File: src/environmentd/tests/sql.rs
[the remark this answers is not in the document]
Comment (rkrishn7) [reply src/environmentd/tests/sql.rs:1]: Hmm, do we just want to ensure the `EXPLAIN` behavior is the same in this case? I don't quite see what additional assertions we would make since we only get information on sources and timestamps via `EXPLAIN`.

Can definitely do just want to understand what additional guardrails it would be providing.

[the remark this answers is not in the document]
Comment (jkosh44) [reply src/environmentd/tests/sql.rs:1]: Yes, the `EXPLAIN` behavior should be exactly the same in this case. Another way to get the timestamp is via `mz_now()`. So you could do something like 
1. `BEGIN;`
2. `SELECT * FROM t;`
3. `SELECT mz_internal.mz_now();`
4. `EXPLAIN TIMESTAMP FOR SELECT * FROM t;`
5. Assert that `mz_now()` returns the same timestamp as `EXPLAIN`.

File: src/adapter/src/coord/sequencer/inner.rs [hunk 4]
```diff
@@ -2221,114 +2202,95 @@ impl Coordinator {
...
         typ: RelationType,
     ) -> Result<PlannedPeek, AdapterError> {
-        let mut read_holds = None;
         let conn_id = session.conn_id();
-        // For transactions that do not use AS OF, get the timestamp context of the
-        // in-progress transaction or create one. If this is an AS OF query, we
-        // don't care about any possible transaction timestamp context. If this is a
-        // single-statement transaction (TransactionStatus::Started), we don't
-        // need to worry about preventing compaction or choosing a valid
-        // timestamp context for future queries.
```
Comment (rkrishn7) [inline src/adapter/src/coord/sequencer/inner.rs:2247]: @jkosh44 Something I updated from this refactor is that an `AS OF` query inside a txn will now place read holds on objects in its timedomain. It looks like previously this wasn't the case as acquiring read holds was only done if `when == QueryWhen::Immediately`

This seems right to me? But just wanted to point that out in case I'm missing something and this needs to be reverted to the original behavior

File: src/environmentd/tests/sql.rs [hunk 5]
```diff
@@ -1291,6 +1291,132 @@ fn test_explain_timestamp_json() {
...
+            &[],
+        )
+        .unwrap_err();
+
+    assert!(format!("{}", error)
+        .contains("Transactions can only reference objects in the same timedomain"));
+
+    client_reads.batch_execute("COMMIT").unwrap();
+
+    client_reads.query_one("SELECT mz_now();", &[]).unwrap();
```
Comment (jkosh44) [inline src/environmentd/tests/sql.rs:1395]: What is this query for?

File: src/environmentd/tests/sql.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (jkosh44) [reply src/environmentd/tests/sql.rs]: >The first sentence here makes sense to me, but not the second.

Let's say that an object `o` has a read frontier of `t - 100`, then we a acquire a read hold on object `o` at time `t`. The read frontier of `o` is not forcibly compacted up to `t`. It may remain at `t - 100` or some value less than `t` for some time. We're only guaranteed that the read frontier will not compact past `t`.

> If o has already compacted past t, then we acquire the hold at o's read frontier, right?

This is also correct.

File: src/adapter/src/coord/sequencer/inner.rs (hunk 4 above)
Comment (rkrishn7) [reply src/adapter/src/coord/sequencer/inner.rs:2247]: Ah, that's fair. Reverted

File: src/environmentd/tests/sql.rs (hunk 5 above)
Comment (rkrishn7) [reply src/environmentd/tests/sql.rs:1399]: Ah, I pulled that from here:

https://github.com/MaterializeInc/materialize/blob/f42f05b745a9ceaf0232219711f7f47f78af1d68/test/sqllogictest/timedomain.slt#L12-L17

 Updated with a comment here as well

File: src/environmentd/tests/sql.rs [hunk 6]
```diff
@@ -1291,6 +1291,132 @@ fn test_explain_timestamp_json() {
...
+            .read_frontier
+            .first()
+            .unwrap();
+
+        // Ensure `t1` does not undergo compaction
+        if let Some(timestamp) = t1_read_frontier {
+            assert_eq!(timestamp, *explain_t1_read_frontier);
+        } else {
+            t1_read_frontier = Some(explain_t1_read_frontier.clone());
+        }
```
[the remark this answers is not in the document]
Comment (rkrishn7) [reply src/environmentd/tests/sql.rs:1370]: Can you explain why? My thinking here is we should be testing that the read frontier of the source isn't advancing

File: src/environmentd/tests/sql.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (rkrishn7) [reply src/environmentd/tests/sql.rs]: Ah I see what you were saying now. Makes sense, thanks for clarifying!

File: src/environmentd/tests/sql.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (jkosh44) [reply src/environmentd/tests/sql.rs:1370]: If the read frontier started as less than the query timestamp, then it can advance up to the query timestamp. So maybe a better assertion would be that the read frontier remains less than or equal to the query timestamp.

For a concrete example, let's say `t` has a read frontier of `10` and the query timestamp is `20`. Then the read frontier can advance up to `20`.

**Comment by jkosh44** [comment]
@rkrishn7 Sorry, I've been slow on giving this a full review, it's been a busy week. I'll finish up on Monday. Thanks again for the PR!

File: src/environmentd/tests/sql.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (rkrishn7) [reply src/environmentd/tests/sql.rs]: Ahh right, that makes sense. Updated

File: src/adapter/src/coord/sequencer/inner.rs [hunk 7]
```diff
@@ -2221,114 +2202,100 @@ impl Coordinator {
...
+        // acquire read holds.
+        if in_immediate_multi_stmt_txn {
+            self.check_txn_timedomain_conflicts(
+                session,
+                &determination.timestamp_context,
+                id_bundle,
+            )?;
+
+            let timedomain_id_bundle =
+                self.timedomain_for(source_ids, &timeline_context, session.conn_id(), cluster_id)?;
```
Comment (jkosh44) [inline src/adapter/src/coord/sequencer/inner.rs:2257]: This seems like it would fit better on line 2262 right before `let read_holds = ...`. That way we only generate this is we actually use it.

File: src/adapter/src/coord/sequencer/inner.rs [hunk 8]
```diff
@@ -2221,114 +2202,100 @@ impl Coordinator {
...
+        if matches!(session.transaction(), &TransactionStatus::InTransaction(_))
+            || when == &QueryWhen::Immediately
+        {
+            session.add_transaction_ops(TransactionOps::Peeks(
+                determination.timestamp_context.clone(),
+            ))?;
+        }
+
+        let in_immediate_multi_stmt_txn = session.transaction().is_in_multi_statement_transaction()
+            && when == &QueryWhen::Immediately;
```
Comment (jkosh44) [inline src/adapter/src/coord/sequencer/inner.rs:2239]: I'm not a huge fan of having to generate this value out here and inside `determine_timestamp`. Is it possible to only generate this once?

File: src/adapter/src/coord/sequencer/inner.rs [hunk 9]
```diff
@@ -2221,114 +2202,100 @@ impl Coordinator {
...
+            timeline_context.clone(),
+            real_time_recency_ts,
+        )?;
+
+        // We only track the peeks in the session if the query doesn't use AS
+        // OF or we're inside an explicit transaction. The latter case is
+        // necessary to support PG's `BEGIN` semantics, whose behavior can
+        // depend on whether or not reads have occurred in the txn.
+        if matches!(session.transaction(), &TransactionStatus::InTransaction(_))
+            || when == &QueryWhen::Immediately
```
Comment (jkosh44) [inline src/adapter/src/coord/sequencer/inner.rs:2231]: I know that you copied this from somewhere else, but I can't seem to figure out why this isn't `if in_immediate_multi_stmt_txn { ... }`

File: src/adapter/src/coord/sequencer/inner.rs (hunk 8 above)
Comment (rkrishn7) [reply src/adapter/src/coord/sequencer/inner.rs:2239]: Yeah, I agree it's not ideal.

It does feel a little weird to pass it as a parameter when it can be computed trivially from existing references, though. Personally I think it's fine to leave it to each method to figure out if we're in a transaction and attempting to perform the query immediately.

But happy to change if you feel strongly otherwise!

File: src/adapter/src/coord/sequencer/inner.rs (hunk 9 above)
Comment (rkrishn7) [reply src/adapter/src/coord/sequencer/inner.rs:2231]: Yeah, I wasn't too sure either so I left it the same. I'm thinking the intention is to track _all_ peeks within a transaction? For example:

```sql
BEGIN;

SELECT * FROM tbl AS OF AT LEAST t1;

SELECT * FROM tbl AS OF AT LEAST t2;
```

In this case, if t1 and t2 are different, adding the peek fails. Whereas we wouldn't end up attempting to track these operations if it was under `if in_immediate_multi_stmt_txn { ... }`.

Side note: Filed https://github.com/MaterializeInc/materialize/issues/19178 as this example ends up crashing the server

Comment (jkosh44) [reply src/adapter/src/coord/sequencer/inner.rs:2231]: Interesting. For the `SELECT ... AS OF ...` I think want to track that a peek happened, but we don't actually want to track it's timestamp. I have a sneaking suspicion that this is related to the panic you found. This is maybe more evidence that we should disallow `AS OF` in multi-statement transactions.

Either way I think this is getting out of scope for this PR. For now this is fine since it's existing behavior.

**Review by jkosh44 — APPROVED** [review]
LGTM
