### PR TITLE
catalog: take boot_ts into account when chosing initial oracle timestamps

### LINKED ISSUE #25075: thread 'coordinator' panicked at src/catalog/src/durable/impls/stash.rs:1201:13: global timestamp must always go up
### What version of Materialize are you using?

a190d69c46

### What is the issue?

Seen in https://buildkite.com/materialize/nightlies/builds/6355#018d88b3-6ae3-46d6-abc2-812d1f6f061c I'm retrying to see if it's a flake.

```
thread 'coordinator' panicked at src/catalog/src/durable/impls/stash.rs:1201:13:
global timestamp must always go up
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: <mz_catalog::durable::impls::stash::Connection as mz_catalog::durable::DurableCatalogState>::set_timestamp::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-061aa9d6a6c96a023-1/materialize/tests/src/catalog/src/durable/impls/stash.rs:1201:13
   3: <mz_catalog::durable::impls::stash::Connection as mz_catalog::durable::DurableCatalogState>::set_timestamp::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-061aa9d6a6c96a023-1/materialize/tests/src/catalog/src/durable/impls/stash.rs:1186:5
   4: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<core::option::Option<mz_storage_types::controller::PersistTxnTablesImpl>, mz_catalog::durable::error::CatalogError>> + core::marker::Send>> as core::future::future::Future>::poll
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
   5: <futures_util::future::maybe_done::MaybeDone<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<core::option::Option<mz_storage_types::controller::PersistTxnTablesImpl>, mz_catalog::durable::error::CatalogError>> + core::marker::Send>>> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/maybe_done.rs:95:38
   6: <futures_util::future::join::Join<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(), mz_catalog::durable::error::CatalogError>> + core::marker::Send>>, core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(), mz_catalog::durable::error::CatalogError>> + core::marker::Send>>> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/join.rs:55:33
   7: <mz_catalog::durable::impls::shadow::ShadowCatalogState as mz_catalog::durable::DurableCatalogState>::set_timestamp::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-061aa9d6a6c96a023-1/materialize/tests/src/catalog/src/durable/impls/shadow.rs:579:9
   8: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(), mz_catalog::durable::error::CatalogError>> + core::marker::Send>> as core::future::future::Future>::poll
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
   9: <mz_adapter::catalog::Catalog>::persist_timestamp::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-061aa9d6a6c96a023-1/materialize/tests/src/adapter/src/catalog.rs:806:14
  10: <mz_adapter::coord::catalog_oracle::CatalogTimestampPersistence as mz_adapter::coord::catalog_oracle::TimestampPersistence<mz_repr::timestamp::Timestamp>>::persist_timestamp::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-061aa9d6a6c96a023-1/materialize/tests/src/adapter/src/coord/catalog_oracle.rs:277:14
  11: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(), mz_catalog::memory::error::Error>> + core::marker::Send>> as core::future::future::Future>::poll
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  12: <mz_adapter::coord::catalog_oracle::CatalogTimestampOracle<mz_repr::timestamp::Timestamp, mz_ore::now::NowFn>>::maybe_allocate_new_timestamps::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-061aa9d6a6c96a023-1/materialize/tests/src/adapter/src/coord/catalog_oracle.rs:206:18
  13: <mz_adapter::coord::catalog_oracle::CatalogTimestampOracle<mz_repr::timestamp::Timestamp, mz_ore::now::NowFn>>::new::<mz_adapter::coord::catalog_oracle::CatalogTimestampPersistence>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-061aa9d6a6c96a023-1/materialize/tests/src/adapter/src/coord/catalog_oracle.rs:186:58
  14: <mz_adapter::coord::Coordinator>::ensure_timeline_state_with_initial_time::<mz_adapter::coord::catalog_oracle::CatalogTimestampPersistence>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-061aa9d6a6c96a023-1/materialize/tests/src/adapter/src/coord/timeline.rs:305:26
  15: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::ensure_timeline_state_with_initial_time<mz_adapter::coord::catalog_oracle::CatalogTimestampPersistence>::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  16: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::ensure_timeline_state_with_initial_time<mz_adapter::coord::catalog_oracle::CatalogTimestampPersistence>::{closure#0}>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  17: tokio::runtime::coop::with_budget::<core::task::poll::Poll<&mut mz_adapter::coord::timeline::TimelineState<mz_repr::timestamp::Timestamp>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::ensure_timeline_state_with_initial_time<mz_adapter::coord::catalog_oracle::CatalogTimestampPersistence>::{closure#0}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  18: tokio::runtime::coop::budget::<core::task::poll::Poll<&mut mz_adapter::coord::timeline::TimelineState<mz_repr::timestamp::Timestamp>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::ensure_timeline_state_with_initial_time<mz_adapter::coord::catalog_oracle::CatalogTimestampPersistence>::{closure#0}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  19: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::ensure_timeline_state_with_initial_time<mz_adapter::coord::catalog_oracle::CatalogTimestampPersistence>::{closure#0}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  20: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::ensure_timeline_state_with_initial_time<mz_adapter::coord::catalog_oracle::CatalogTimestampPersistence>::{closure#0}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  21: <tokio::runtime::handle::Handle>::block_on::<<mz_adapter::coord::Coordinator>::ensure_timeline_state_with_initial_time<mz_adapter::coord::catalog_oracle::CatalogTimestampPersistence>::{closure#0}>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:310:13
  22: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::handle::Handle>::block_on<<mz_adapter::coord::Coordinator>::ensure_timeline_state_with_initial_time<mz_adapter::coord::catalog_oracle::CatalogTimestampPersistence>::{closure#0}>::{closure#0}, &mut mz_adapter::coord::timeline::TimelineState<mz_repr::timestamp::Timestamp>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  23: <tokio::runtime::handle::Handle>::block_on::<<mz_adapter::coord::Coordinator>::ensure_timeline_state_with_initial_time<mz_adapter::coord::catalog_oracle::CatalogTimestampPersistence>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:309:9
  24: mz_adapter::coord::serve::{closure#0}::{closure#2}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-061aa9d6a6c96a023-1/materialize/tests/src/adapter/src/coord.rs:2901:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
ci-regexp: global timestamp must always go up

### PR DESCRIPTION
**Pull request by aljoscha**
Fixes #25075

### CODE REVIEW

File: src/adapter/src/coord.rs [hunk 1]
```diff
@@ -2858,6 +2858,37 @@ pub fn serve(
             .expect("missing EpochMillisseconds timestamp")
             .clone();
 
+        // Choose a time at which to boot. This is the time at which we will run
+        // internal migrations.
```
Comment (jkosh44) [inline src/adapter/src/coord.rs:2862]: > This is the time at which we will run internal migrations.

This used to be true, and I thought it was currently true, but looking through the code it doesn't actually look like this is true anymore.

File: src/adapter/src/catalog/open.rs [hunk 2]
```diff
@@ -264,24 +252,16 @@ impl Catalog {
...
-                boot_ts
-            };
+            if !is_read_only {
+                // WIP: @joe, we're only persisting a boot_ts for the Catalog
+                // oracle, not for the Postgres oracle. We do it later though,
+                // when initializing the postgres oracle with an initial
+                // timestamp based on the boot_ts. It's not atomic with any
+                // catalog migrations and the like.
+                // IMPORTANT: we durably record the new timestamp before using it.
+                txn.set_timestamp(Timeline::EpochMilliseconds, boot_ts)?;
```
Comment (jkosh44) [inline src/adapter/src/catalog/open.rs:263]: It does seem wrong to me that we set only the catalog timestamp without even checking which implementation to use.

File: src/adapter/src/coord.rs [hunk 3]
```diff
@@ -2858,6 +2858,37 @@ pub fn serve(
...
+        //
+        // This time is usually the current system time, but with protection
+        // against backwards time jumps, even across restarts.
+        let boot_ts = {
+            // WIP: @joe we have a chicken-and-egg problem here. Ideally we'd
+            // only use monotonic_now when we know we're using the Catalog
+            // oracle, and when using the Postgres oracle we'd only advance the
+            // timestamp by one. But we can only know that once we opened the
+            // Catalog.
```
Comment (jkosh44) [inline src/adapter/src/coord.rs:2871]: We have the same issue with `catalog_kind` and `persist_txn`. The solution is to store a copy of the system variable in the config collection, which we can read before opening the catalog.

Comment (jkosh44) [reply src/adapter/src/coord.rs:2871]: I can point you in the direction of where that code is if you want.

File: src/adapter/src/coord.rs [hunk 4]
```diff
@@ -2858,6 +2858,37 @@ pub fn serve(
...
+        // turn make sure that we initialize timestamp oracles at the `boot_ts`,
+        // which in turn will make sure that the next `boot_ts` is beyond the
+        // current boot_ts.
+        initial_timestamps
+            .entry(Timeline::EpochMilliseconds)
+            .and_modify(|ts| {
+                *ts = std::cmp::max(*ts, boot_ts);
+            })
+            .or_insert(boot_ts);
+
```
Comment (jkosh44) [inline src/adapter/src/coord.rs:2891]: I think we need to move the code for persisting the timestamp up here so that we persist the timestamp before using it.

```
for (timeline, initial_timestamp) in initial_timestamps {
                    let persistence =
                        CatalogTimestampPersistence::new(timeline.clone(), Arc::clone(&catalog));
                    handle.block_on(Coordinator::ensure_timeline_state_with_initial_time(
                        &timeline,
                        initial_timestamp,
                        coord_now.clone(),
                        timestamp_oracle_impl,
                        persistence,
                        pg_timestamp_oracle_config.clone(),
                        &mut timestamp_oracles,
                    ));
}
```

File: src/adapter/src/coord.rs (hunk 1 above)
Comment (jkosh44) [reply src/adapter/src/coord.rs:2862]: Then we can remove the call to `txn.set_timestamp` from `open.rs`.

**Comment by jkosh44** [comment]
> BUT, I have a tepid take: `boot_ts` is _only_ used in this call:
> 
> https://github.com/MaterializeInc/materialize/blob/582eac48526acfb75af0f16c577788853217d1cc/src/adapter/src/catalog/open.rs#L1002
> 
> For that, I don't think we need the guarantees we try and give right now.
> 
> We could lift the `monotonic_now` call into the `CatalogOracle`, here:
> 
> https://github.com/MaterializeInc/materialize/blob/5b990beaf32eede6a746d1cf9147a4be527510e5/src/adapter/src/coord/catalog_oracle.rs#L186
> 
> And then remove it alltogether once we remove the catalog oracle. What do you think?

Well here's the one issue that we're currently protected against:

1. `environmentd` clock jumps ahead of the actual time by a large amount.
2. We mistakenly prune all/some of storage usage events.

If we don't think that's a realistic issue then I say we can go ahead with your plan. If we do think that's a realistic scenario then we may be exposing ourselves to accidental deletions of storage usage events.

Personally, I'd err on the side of caution. It's pretty bad to delete storage usage events since they're used for billing and a 5 second jump every restart (which currently happens roughly once a week) isn't that bad. Using the config collection approach you can probably also avoid the 5 second jump when using the shareable oracle. However, I can probably be convinced the other way too.

File: src/adapter/src/coord.rs (hunk 4 above)
Comment (jkosh44) [reply src/adapter/src/coord.rs:2891]: Then we can remove the call to `txn.set_timestamp` in `open.rs`.

**Comment by ParkMyCar** [comment]
Going to remove myself as a reviewer since this is right in @jkosh44's wheel house, feel free to re-add me if need be though!

**Review by jkosh44 — APPROVED** [review]
LGTM!
