### PR TITLE
coord: Protect timestamp from crash loop

### LINKED ISSUE #16007: `ERROR mz_adapter::coord::timeline: Setting local read timestamp to 1668084017068 which is ahead of now, 1668084008628` after restarting MZ
### What version of Materialize are you using?

9c189a419f70c0aac0113b5bbed90352b55b6da5

### How did you install Materialize?

Docker image

### What is the issue?

The Zippy tests restart Mz. After that second, I think, restart, the log has several of the log lines below.

To reproduce:

1.

```
cd test/zippy
./mzcompose down -v ; ./mzcompose run default --scenario=KafkaSources 
```

2. In another window, repeatedly run:
```
docker logs zippy-materialized-1 2>&1 | grep ERROR
```
until the log lines appear.

### Relevant log output

```source
environmentd: 2022-11-10T12:40:08.628914Z ERROR mz_adapter::coord::timeline: Setting local read timestamp to 1668084017068 which is ahead of now, 1668084008628
environmentd: 2022-11-10T12:40:08.650687Z ERROR mz_adapter::coord::timeline: Setting local read timestamp to 1668084017069 which is ahead of now, 1668084008650
environmentd: 2022-11-10T12:40:08.671811Z ERROR mz_adapter::coord::timeline: Setting local read timestamp to 1668084017070 which is ahead of now, 1668084008671
environmentd: 2022-11-10T12:40:08.708988Z ERROR mz_adapter::coord::timeline: Setting local read timestamp to 1668084017071 which is ahead of now, 1668084008708
environmentd: 2022-11-10T12:40:08.730461Z ERROR mz_adapter::coord::timeline: Setting local read timestamp to 1668084017072 which is ahead of now, 1668084008730
environmentd: 2022-11-10T12:40:08.752634Z ERROR mz_adapter::coord::timeline: Setting local read timestamp to 1668084017073 which is ahead of now, 1668084008752
environmentd: 2022-11-10T12:40:08.785149Z ERROR mz_adapter::coord::timeline: Setting local read timestamp to 1668084017074 which is ahead of now, 1668084008785
environmentd: 2022-11-10T12:40:08.815320Z ERROR mz_adapter::coord::timeline: Setting local read timestamp to 1668084017075 which is ahead of now, 1668084008815
environmentd: 2022-11-10T12:40:08.829883Z ERROR mz_adapter::coord::timeline: Setting local read timestamp to 1668084017077 which is ahead of now, 1668084008829
environmentd: 2022-11-10T12:40:08.829926Z ERROR mz_adapter::coord::timeline: Setting local read timestamp to 1668084017076 which is ahead of now, 1668084008829
```

### PR DESCRIPTION
**Pull request by jkosh44**
Whenever a new Coordinator starts it resserves a new timestamp range in
the stash, larger than any previous timestamp range. This usually
results in the Coordinator resrving a range ahead of the system clock's
current time, because the range with the current time is owned by the
previous Coordinator. This will usually correct itself fairly quickly
because the Coordinator can advance it's timestamp much slower than
real time. However, if the Coordinator enters a crash loop, then the
the persisted timestamp can start to significantly exceed the system
clock as each new Coordinator reserves an even greater timestamp range.

This commit prevents a new Coordinator from starting with a timestamp
larger than a certain amount ahead of the system clock. Instead the
Coordinator sleeps and waits for the system clock to catch up. The
range was selected so that startup is not affected in the common case,
but in a crash loop or other error scenario no permanent damage is done
to the persisted timestamp.

Additionally, while running if the timestamp exceeds the system clock
by that same amount, we print an error.

Fixes #16007
Works towards resolving #14899

### Motivation
This PR fixes a recognized bug.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - N/A

### CODE REVIEW

File: src/adapter/src/coord/timeline.rs [hunk 1]
```diff
@@ -138,12 +138,25 @@ impl<T: TimestampManipulation> TimestampOracle<T> {
...
         .as_millis()
         .try_into()
-        .expect("15 seconds can fit into `Timestamp`")
+        .expect("5 seconds can fit into `Timestamp`")
 });
 
+/// The Coordinator tries to prevent the persisted timestamp from exceeding
+/// a value [`TIMESTAMP_INTERVAL_UPPER_BOUND`] times [`TIMESTAMP_PERSIST_INTERVAL`]
+/// larger than the current system time.
+pub const TIMESTAMP_INTERVAL_UPPER_BOUND: u64 = 2;
```
Comment (jkosh44) [inline src/adapter/src/coord/timeline.rs:150]: I settled on 2, because there's some tests that use a deterministic clock that need at least two intervals. Specifically this allows us to start a second instance immediately without blocking, if that second instance's clock happens to be behind the first instance.

File: src/environmentd/tests/sql.rs [hunk 2]
```diff
@@ -1961,3 +1959,58 @@ fn test_idle_in_transaction_session_timeout() -> Result<(), Box<dyn Error>> {
...
+        let mut client = server.connect(postgres::NoTls).unwrap();
+
+        client.query("SELECT 1", &[]).unwrap();
+        tx.send(()).unwrap();
+    });
+
+    let server_started = Retry::default()
+        .max_duration(Duration::from_secs(1))
+        .retry(|_| rx.try_recv());
+    assert!(server_started.is_err(), "server should be blocked");
```
Comment (mjibson) [inline src/environmentd/tests/sql.rs:2008]: Can you assert that the error message contains some expected string? Want to make sure we are failing for a vaguely correct reason.

**Review by mjibson — APPROVED** [review]

File: src/environmentd/tests/sql.rs (hunk 2 above)
Comment (jkosh44) [reply src/environmentd/tests/sql.rs:2008]: How do you capture the logs in the test? `server_started` is just going to be a `TryRecvError` (https://doc.rust-lang.org/std/sync/mpsc/struct.Receiver.html#method.try_recv) because the channel is empty.

Comment (mjibson) [reply src/environmentd/tests/sql.rs:2008]: Can you do `tx.send(client.query("select 1", &[]).map(|_| ()))` to send the query error through the channel?

Comment (jkosh44) [reply src/environmentd/tests/sql.rs:2008]: It won't be a query error, the task will just be blocked on `let server = util::start_server(config.clone()).unwrap();` as it waits for the server to start up without ever making it to the query.

Comment (mjibson) [reply src/environmentd/tests/sql.rs:2008]: Ok, then don't worry about it.
