### PR TITLE
storage: guard against `build_fallible` footgun

### LINKED ISSUE #23287: Postgres CDC test is stuck: postgres: slot overcompacted. Requested LSN 22640040 but only LSNs >= 22640096 are available"
### What version of Materialize are you using?

5503f58b6d1a

### What is the issue?

Seen in normal tests: https://buildkite.com/materialize/tests/builds/69054#018bde95-d655-424a-99c6-e9f7bb667c82
```
> SELECT * FROM tb;
```
The query got stuck until timeout. services.log is interesting:
```
pg-cdc-materialized-1  | cluster-u3-replica-u3: 2023-11-17T19:15:01.659399Z ERROR mz_storage::source::postgres::replication: timely-3 (u14) slot overcompacted. Requested LSN 22640040 but only LSNs >= 22640096 are available
pg-cdc-materialized-1  | cluster-u3-replica-u3: 2023-11-17T19:15:01.667367Z  INFO mz_storage::healthcheck: Health transition for source u14: Some(Starting) -> Some(Stalled { error: "postgres: slot overcompacted. Requested LSN 22640040 but only LSNs >= 22640096 are available", hints: {}, namespaced_errors: {Postgres: "slot overcompacted. Requested LSN 22640040 but only LSNs >= 22640096 are available"} })
pg-cdc-materialized-1  | cluster-u3-replica-u3: 2023-11-17T19:15:01.675602Z  INFO mz_storage::healthcheck: Health transition for source u21: Some(Starting) -> Some(Stalled { error: "postgres: slot overcompacted. Requested LSN 22640040 but only LSNs >= 22640096 are available", hints: {}, namespaced_errors: {Postgres: "slot overcompacted. Requested LSN 22640040 but only LSNs >= 22640096 are available"} })
pg-cdc-materialized-1  | cluster-u3-replica-u3: 2023-11-17T19:15:01.686040Z  INFO mz_storage::healthcheck: Health transition for source u22: Some(Starting) -> Some(Stalled { error: "postgres: slot overcompacted. Requested LSN 22640040 but only LSNs >= 22640096 are available", hints: {}, namespaced_errors: {Postgres: "slot overcompacted. Requested LSN 22640040 but only LSNs >= 22640096 are available"} })
pg-cdc-materialized-1  | cluster-u3-replica-u3: 2023-11-17T19:15:01.696847Z  INFO mz_storage::healthcheck: Health transition for source u12: Some(Starting) -> Some(Stalled { error: "postgres: slot overcompacted. Requested LSN 22640040 but only LSNs >= 22640096 are available", hints: {}, namespaced_errors: {Postgres: "slot overcompacted. Requested LSN 22640040 but only LSNs >= 22640096 are available"} })
pg-cdc-materialized-1  | cluster-u3-replica-u3: 2023-11-17T19:15:01.708471Z  INFO mz_storage::healthcheck: Broadcasting suspend-and-restart command because of Some((Postgres, Stalled { error: "slot overcompacted. Requested LSN 22640040 but only LSNs >= 22640096 are available", hint: None, should_halt: true })) after 30s delay
```
This appears to be a flake (restarted the test to check). @petrosagg are you the right assignee?

### PR DESCRIPTION
**Pull request by petrosagg**
### Motivation

Because the capabilities that we retained were stored in a btree map which was part of the future state, when we encountered an error and returned from the future those were dropped and created bogus frontiers that propagated down the dataflow. This can cause incorrect data to be persisted. Until `build_fallible` is fixed we must implement this ugly workaround.

Fixes #23287

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by petrosagg** [comment]
Kicked off a nightly build too

File: src/storage/src/source/postgres/replication.rs [hunk 1]
```diff
@@ -171,97 +172,98 @@ pub(crate) fn render<G: Scope<Timestamp = MzOffset>>(
...
                 subsource_resume_uppers
                     .values()
                     .flat_map(|f| f.elements())
-                    // Advance any upper as far as the slot_lsn.
-                    .map(|t|std::cmp::max(*t, slot_lsn))
+                    .copied()
+                    // If a resume upper of a subsource is zero it means it will be snapshotted and
+                    // the requirement on the overall resume upper will come from its corresponding
+                    // rewind request, so it's safe to ignore it here.
+                    .filter(|t| t != &MzOffset::minimum())
```
Comment (guswynn) [inline src/storage/src/source/postgres/replication.rs:221]: this is equivalent to: https://github.com/MaterializeInc/materialize/commit/9105f9aa25404a86d92519b4d4c63acdac8d7559 right?

File: src/storage/src/source/postgres/replication.rs [hunk 2]
```diff
@@ -171,97 +172,98 @@ pub(crate) fn render<G: Scope<Timestamp = MzOffset>>(
...
-            trace!(%id, "timely-{worker_id} replication reader started lsn={}", resume_lsn);
-
-
             let mut rewinds = BTreeMap::new();
             while let Some(event) = rewind_input.next_mut().await {
-                if let AsyncEvent::Data(cap, data) = event {
-                    let cap = cap.retain_for_output(0);
+                if let AsyncEvent::Data(_cap, data) = event {
+                    // We can't retain this capability due to build_fallible so simulate holding it
+                    // by accounting for it in the progress mutable antichain
```
Comment (guswynn) [inline src/storage/src/source/postgres/replication.rs:227]: more thoroughly explaining _why_ we can hold it would be nice

i think the subtlety is why retaining a data cap is bad if we also have the `data_cap_set` above?

File: src/storage/src/source/postgres/replication.rs [hunk 3]
```diff
@@ -171,97 +172,98 @@ pub(crate) fn render<G: Scope<Timestamp = MzOffset>>(
...
+                    let created = data.len().try_into().unwrap();
+                    fake_progress.update_iter([(MzOffset::minimum(), created)]);
                     for req in data.drain(..) {
-                        assert!(
-                            resume_lsn <= req.snapshot_lsn + 1,
-                            "slot compacted past snapshot point. snapshot consistent point={} resume_lsn={resume_lsn}", req.snapshot_lsn + 1
-                        );
-                        rewinds.insert(req.oid, (cap.clone(), req));
```
Comment (guswynn) [inline src/storage/src/source/postgres/replication.rs:213]: i prefer leaving this assert behind for clarity

File: src/storage/src/source/postgres/replication.rs [hunk 4]
```diff
@@ -171,97 +172,98 @@ pub(crate) fn render<G: Scope<Timestamp = MzOffset>>(
...
+            }
 
-            let resume_upper = Antichain::from_iter(
+            // This is an ugly hack that we need to do until because the `build_fallible`
+            // constructor (which we use here) is unsafe in the presence of retained input
+            // capabiltities (which we also use for the rewind requests). The mutable antichain is
+            // initialized with one copy of the minimum capability which represents the initial
+            // capability of this operator.
+            let mut fake_capability = MzOffset::minimum();
+            let mut fake_progress = MutableAntichain::new_bottom(MzOffset::minimum());
```
Comment (guswynn) [inline src/storage/src/source/postgres/replication.rs:208]: I don't really like the name `fake_` here, what about `synthesized` or something?

File: src/storage/src/source/postgres/replication.rs (hunk 1 above)
Comment (petrosagg) [reply src/storage/src/source/postgres/replication.rs:221]: Yes

File: src/storage/src/source/postgres/replication.rs (hunk 3 above)
Comment (petrosagg) [reply src/storage/src/source/postgres/replication.rs:213]: The assert causes the whole cluster to fail, which is bad. This PR will still error out the dataflow immediately after starting the raw stream

File: src/storage/src/source/postgres/replication.rs (hunk 4 above)
Comment (petrosagg) [reply src/storage/src/source/postgres/replication.rs:208]: sure, I'll change the name

**Comment by petrosagg** [comment]
@sploiselle @guswynn I pushed a commit that removes the fake capability stuff with a simpler approach, please take a look

**Review by guswynn — APPROVED** [review]
current version of the code looks much nicer!

**Review by sploiselle — APPROVED** [review]
