### PR TITLE
bootstrap: fix as-of selection for compute reconciliation

### LINKED ISSUE #26155: compute: Restarting environmentd can cause unexpected re-hydrations
### What version of Materialize are you using?

v0.92.0

### What is the issue?

Recently we had to restart an instance of `environmentd`, this caused a few (but not all) `clusterd`s to restart, requiring dataflows to rehydrate. Interestingly I didn't observe any downtime from k9s, i.e. the pods themselves didn't restart, so this seems more like a compute issue than a cloud issue.

We would like to solve this because restarting `environmentd` can already be disruptive to the customer, but should only last ~1 minute. Re-hydrating dataflows on the other hand can take almost arbitrarily long and thus is _much_ more disruptive.

See more discussion around the referenced instance [here in Slack](https://materializeinc.slack.com/archives/C06Q94A843D/p1710859044755659).

### PR DESCRIPTION
**Pull request by teskje**
This PR fixes another issue with dataflow as-of bootstrapping that could disable compute reconciliation. The oversight here was that an envd restart can make index write frontiers regress (since they are reset to their newly selected read frontiers), which makes it likely that using these frontiers to determine an as-of for compute dataflows will produce an as-of that is earlier than the frontiers already installed dataflows have been allowed to compact to.

The solution to this issue is to select as-ofs based on the frontiers of (transitive) storage dependencies instead. Storage frontiers cannot regress, so they are guaranteed to provide an as-of that is far enough advanced for reconciliation to succeed.

The knowledge about transitive storage dependencies was not yet available during bootstrapping, so this PR adds it by converting the "index dependent MVs" collection step into a more generic "storage constraints" collection step that gathers all storage dependencies and storage dependants needed to constrain the initial timestamp for each dataflow.

Finally, this PR also merges the two `bootstrap_*_as_of` methods into a single one, to get rid of all the accumulated code and comment duplication.

### Motivation

  * This PR fixes a recognized bug.

Fixes #26155 

### Tips for reviewer

I have not attempted to keep the changes minimal, so it's probably easier to review the two versions side-by-side, rather than as a line-by-line diff.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - N/A

### CODE REVIEW

**Comment by teskje** [comment]
Nightlies look good. The failing output consistency checks are unrelated.

File: src/adapter/src/coord.rs [hunk 1]
```diff
@@ -2131,178 +2140,203 @@ impl Coordinator {
...
+        // materialized view.
+        let write_frontier;
+        let candidate_as_of = match dataflow.sink_exports.keys().at_most_one() {
+            // Materialized view dataflow.
+            Ok(Some(sink_id)) => {
+                // If the target storage collection of a materialized view is already sealed, there
+                // is no need to install a dataflow in the first place.
+                write_frontier = self.storage_write_frontier(*sink_id).clone();
+                if write_frontier.is_empty() {
+                    Antichain::new()
```
Comment (ggevay) [inline src/adapter/src/coord.rs:2284]: The `max_as_of` should also be empty in this case, right? Maybe you could assert that here.

File: src/adapter/src/coord.rs [hunk 2]
```diff
@@ -2131,178 +2140,203 @@ impl Coordinator {
...
+        // their `as_of` is selected earlier.
+        let storage_dependencies = storage_constraints.dependencies_bundle();
+        let warmup_frontier = self.greatest_available_read(&storage_dependencies);
+
+        // Apply additional constraints based on whether this dataflow exports an index or a
+        // materialized view.
+        let write_frontier;
+        let candidate_as_of = match dataflow.sink_exports.keys().at_most_one() {
+            // Materialized view dataflow.
+            Ok(Some(sink_id)) => {
```
Comment (ggevay) [inline src/adapter/src/coord.rs:2279]: Maybe assert that `dataflow.index_exports.is_empty()`. It sometimes comes up that at some point we might want to have dataflows that create a materialized view as well as export an index. In that case an assert here would alert us that we'd probably need to modify this code.

Also, in the index case, maybe assert that `index_exports` is not empty.

Comment (ggevay) [reply src/adapter/src/coord.rs:2279]: And one more question: Looking at `ComputeSinkConnection`, a sink is not necessarily an MV, but it can also be a subscribe or a copy-to-s3. But I think these cases are not important, because we lose subscribes and copy-to-s3s when restarting envd, right? (If it's not too much hassle, then you could maybe assert that the `ComputeSinkConnection` is `Persist`.)

**Review by ggevay — COMMENTED** [review]
I wrote some small comments. Will finish the review tomorrow.

File: src/adapter/src/coord.rs (hunk 1 above)
Comment (teskje) [reply src/adapter/src/coord.rs]: Yep! In fact `write_frontier` and `max_as_of` should always be equal for MVs since an MV dataflow is always depended on only by its target storage collection. Added a `soft_assert`.

File: src/adapter/src/coord.rs (hunk 2 above)
Comment (teskje) [reply src/adapter/src/coord.rs]: Good point. I added asserts that ensure that there is only a single export and it is either an index or a persist sink.

File: src/adapter/src/coord.rs [hunk 3]
```diff
@@ -2131,178 +2140,217 @@ impl Coordinator {
...
+                // the future.
+                min_as_of.clone()
+            }
+        } else if let Some(sink_id) = dataflow.persist_sink_ids().next() {
+            // Materialized view dataflow.
+
+            write_frontier = self.storage_write_frontier(sink_id).clone();
+            // Materialized view dataflows are only depended on by their target storage collection,
+            // so `write_frontier` and `max_as_of` should always be equal.
+            soft_assert_eq_or_log!(write_frontier, max_as_of);
```
Comment (ggevay) [inline src/adapter/src/coord.rs:2319]: This is not exactly true: when the MV's storage write frontier is still at 0, the `max_as_of` will be >0, because of the `join` in the `max_as_of` determination.

Maybe just assert that `PartialOrder::less_equal(&write_frontier, &max_as_of)`. This would still cover my original suggestion (if `write_frontier.is_empty()` then also `max_as_of.is_empty()`).

Comment (ggevay) [reply src/adapter/src/coord.rs:2319]: (Btw. `3d.` in `workflow_test_refresh_mv_restart` catches this, but it's not run in CI at the moment, because it's ignored due to an unrelated bug making some other test interfere with it. But it's possible to run it just by itself locally: `bin/mzcompose --dev --find cluster run test-refresh-mv-restart`)

Comment (teskje) [reply src/adapter/src/coord.rs]: Uff, good catch. Fixed!

File: test/cluster/mzcompose.py [hunk 4]
```diff
@@ -1794,6 +1793,23 @@ def fetch_reconciliation_metrics() -> tuple[int, int]:
         """
     )
 
+    # Replace the `mz_introspection` replica with an unorchestrated one so we
```
[the remark this answers is not in the document]
Comment (teskje) [reply test/cluster/mzcompose.py:1830]: Thanks! Added a couple more variations involving `REFRESH` MVs as well.

[the remark this answers is not in the document]
Comment (ggevay) [reply test/cluster/mzcompose.py:1830]: Great, thank you!

**Review by ggevay — APPROVED** [review]
LGTM!

**Comment by teskje** [comment]
TFTR!
