### PR TITLE
dataflow: prefer hashing positions when distributing uniformly across workers

### LINKED ISSUE #4197: Delay of ~2 minutes in scheduling some kafka source operators
When you create a kafka source reading a multipartition (tested with 4) topic with a lot of records, one of the kafka source operators is not scheduled as often as the rest, for the first roughly two - four minutes of the source's existence. This happens deterministically (when run on a 4 partition topic with 4 workers, worker 2 is always delayed in being scheduled). This happens regardless of the number of workers (I tested it with 2, 3, 4, 6, 11 workers). When run with 11 workers, worker 9 is the one delayed. In this case, worker 9 is not reading any data, but it is still not being scheduled as frequently as the other non-reading operators.

Notably, it does not seem to manifest when Materialize is run with exactly one worker, nor does it seem to manifest when the source has exactly one partition (I tested this with kafka sources with 1 and 4 partitions).

It reproduces if you create the source right after restart, and also if you a while after Materialize has started before you create your source.

To reproduce this yourself -- head over to the upsert demo 

```
cd test/performance/perf-upsert
``` 

I changed the demo to not do upsert using this diff

```
diff --git a/test/performance/perf-upsert/src/main.rs b/test/performance/perf-upsert/src/main.rs
index 1ccd5e6a..3e16a4ae 100644
--- a/test/performance/perf-upsert/src/main.rs
+++ b/test/performance/perf-upsert/src/main.rs
@@ -142,12 +142,9 @@ async fn create_upsert_text_source(
     );

     let query = if enable_persistence {
-        format!(
-            "{} WITH (persistence = true) FORMAT TEXT ENVELOPE UPSERT",
-            query_prefix
-        )
+        format!("{} WITH (persistence = true) FORMAT TEXT", query_prefix)
     } else {
-        format!("{} FORMAT TEXT ENVELOPE UPSERT", query_prefix)
+        format!("{} FORMAT TEXT", query_prefix)
     };
     log::debug!("creating source=> {}", query);

altaria-2:perf-upsert Test$
```

but I don't think its relevant to the bug (famous last words)

Now, create a 4 partition topic with the following invocation

```
cargo run --release -- --message-count 25000000 --messages-per-second 50000 --create-topic --kafka-topic perf-upsert-4-part --partitions 4 --replication-factor 1
```

this creates a 4 partition topic named `perf-upsert-4-part` with 25MM messages and will take approximately 500 seconds to fill it with 25 MM messages.

verify that each of the partitions have roughly equivalent amounts of data in them by running
```
kafkacat -b localhost:9092 -C -o -1 -f "[partition: %p] offset: %o\n" -t perf-upsert-4-part
```

each topic should end at an offset ~= 6.25 MM

now, start up Materialize in release mode (I used main at `e9683151e`), and make it ingest the source by either typing in:

```
CREATE SOURCE "materialize"."public"."perf_upsert_source" FROM KAFKA BROKER 'localhost:9092' TOPIC 'perf-upsert-4-part' FORMAT TEXT
```

to psql, or running the demo again with message-count=0

At this point, if you look at the `mz_operator_scheduled_total` metric, you should see one of the worker's scheduled count is suspiciously low.

Screen Shot 2020-09-12 at 3 20 17 PM
Screen Shot 2020-09-12 at 3 09 30 PM

With grafana it should look something like the screenshots attached.

As it stands currently, this quirk has the potential to blow up memory usage for BYO sources, because if we are ingesting from all partitions but 1, we may not be able to downgrade capabilities for a while. This is also problematic for persistent sources.

cc: @justinj

### PR DESCRIPTION
**Pull request by ruchirK**
Closes #4197

Previously, when we wanted to distribute records across workers uniformly
randomly, we distributed them based on the hash of their values. The reasoning
behind this was that in many potential sources, the distribution of keys might
be sufficiently skewed (or keys may not even exist) which makes keys a poor
choice uniformly distributing data (except in cases where we need records
with the same key to go to the same worker).

Unfortunately, all of those same arguments apply for values as well. This commit
changes the behavior to distribute records based on the hash of the position if
the position exists and otherwise fall back to a hash on the value. The
distribution of positions is much better known to us than the distribution of
potential values, and its more likely to be amenable to what we are trying to
accomplish.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4267)

### CODE REVIEW

File: src/dataflow/src/source/mod.rs [hunk 1]
```diff
@@ -139,13 +139,20 @@ where
     {
         Exchange::new(|x: &Self| x.key.hashed())
     }
-    /// A parallelization contract that hashes by values.
+    /// A parallelization contract that hashes by positions (if available)
+    /// and otherwise falls back to hashing by value.
```
Comment (umanwizard) [inline src/dataflow/src/source/mod.rs:143]: Can you explain in the comment why we're doing this / what problems we ran into distributing just by value?

**Review by umanwizard — APPROVED** [review]

**Review by frankmcsherry — APPROVED** [review]
Looks good!

File: src/dataflow/src/source/mod.rs (hunk 1 above)
Comment (ruchirK) [reply src/dataflow/src/source/mod.rs:143]: sure ill add that

**Review by benesch — APPROVED** [review]
