### PR TITLE
parser: print expressions correctly; improve roundtrip testing

### LINKED ISSUE #20572: EXTRACT and OPERATOR don't work in AST Displayer
### What version of Materialize are you using?

main

### What is the issue?

See https://github.com/MaterializeInc/materialize/pull/20562#pullrequestreview-1531110231

This is not the same. `OPERATOR(+)` has a different grouping from `+`, example:
```
materialize=> select 2 OPERATOR(*) 2 + 2;
 ?column?
----------
        8
(1 row)

materialize=> select 2 * 2 + 2;
 ?column?
----------
        6
(1 row)
```

as well as

```
materialize=> select extract('year', 'foo');
ERROR:  Expected FROM, found comma
LINE 1: select extract('year', 'foo')
                             ^
```

### PR DESCRIPTION
**Pull request by mjibson**
Fixes #20572

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

### CODE REVIEW

File: src/sql-parser/src/ast/defs/expr.rs [hunk 1]
```diff
@@ -816,6 +819,33 @@ pub struct Function<T: AstInfo> {
 
 impl<T: AstInfo> AstDisplay for Function<T> {
     fn fmt<W: fmt::Write>(&self, f: &mut AstFormatter<W>) {
+        // This block handles printing function calls that have special parsing. In stable mode, the
+        // name is quoted and so won't get the special parsing. We only need to print the special
+        // formats in non-stable mode.
+        if !f.stable() {
```
Comment (mjibson) [inline src/sql-parser/src/ast/defs/expr.rs:825]: This whole block is kinda janky because it only triggers in non-stable mode. I tried some other ideas but this one felt the least bad. If anyone has others would be happy to hear.

Comment (ParkMyCar) [reply src/sql-parser/src/ast/defs/expr.rs:825]: From a code perspective everything looks good. I'm not sure what "stable mode" is for the parser though. When are we in stable mode and why do we only want to print the special formats in non-stable mode?

Comment (ParkMyCar) [reply src/sql-parser/src/ast/defs/expr.rs:825]: When would we not be in stable mode? What I'm trying to understand are what are the real world scenarios in which we print these functions in a special way? Since it seems like we want both `extract(<arg>, <arg>)` and `extract(<arg> FROM <arg>)` to both be valid?

Comment (mjibson) [reply src/sql-parser/src/ast/defs/expr.rs:825]: `extract(<arg>, <arg>)` isn't valid because the `extract` keyword parses special, `"extract"(<arg>, <arg>)` however is valid because `"<x>"` parses an identifier with function arguments following, but doesn't care what the identifier is.

Normal mode is used for generating error messages and when generating statements that the postgres source executes.

Comment (ParkMyCar) [reply src/sql-parser/src/ast/defs/expr.rs:825]: Ahhhh, I got it now, thank you for the context!
