### PR TITLE
expr,repr: handle zero-dimensional arrays per PostgreSQL

### LINKED ISSUE #5545: Array dimension lengths seem incorrect
### What was the issue?

The incorrect behaviour can be observed using `array_upper`, `array_lower`, and `array_length`. There might be more functions affected though:

postgres:

```sql
postgres=# SELECT array_upper(array[[]]::integer[], 1);
 array_upper
-------------

(1 row)

postgres=# SELECT array_lower(array[[]]::integer[], 1);
 array_lower
-------------

(1 row)
```

materialize:

```sql
petrosagg=> SELECT array_upper(array[[]]::integer[], 1);
 array_upper
-------------
           1
(1 row)

petrosagg=> SELECT array_lower(array[[]]::integer[], 1);
 array_lower
-------------
           1
(1 row)
```

I think the offending logic is here https://github.com/MaterializeInc/materialize/blob/c2314d251d4dd839ffaf5c6e03a1d865aa9b8a7a/src/expr/src/scalar/func.rs#L3689

### PR DESCRIPTION
**Pull request by benesch**
Per PostgreSQL, arrays with no elements are represented as having zero
dimensions, rather than having one dimension of zero length.

We don't need to mention this in the release notes because these sorts
of details about arrays are intentionally undocumented.

Fix #5545.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5761)

### CODE REVIEW

File: src/expr/src/scalar/func.rs [hunk 1]
```diff
@@ -3738,18 +3748,26 @@ fn array_create_multidim<'a>(
...
 fn array_create_scalar<'a>(
     datums: &[Datum<'a>],
     temp_storage: &'a RowArena,
 ) -> Result<Datum<'a>, EvalError> {
-    let dims = &[ArrayDimension {
+    let mut dims = &[ArrayDimension {
         lower_bound: 1,
         length: datums.len(),
-    }];
+    }][..];
```
Comment (petrosagg) [inline src/expr/src/scalar/func.rs:3764]: Why is this additional index required? Does it replace the 'static lifetime with the local one?

**Review by petrosagg — APPROVED** [review]

File: src/expr/src/scalar/func.rs (hunk 1 above)
Comment (benesch) [reply src/expr/src/scalar/func.rs:3764]: Not quite! It forces a coercion from `&[ArrayDimension; 1]` to `&[ArrayDimension]`, i.e., a coercion from an array type to a slice type. Something is funky about Rust's type inference, and it can't always inject that coercion automatically.

**Review by benesch — COMMENTED** [review]
Thanks very much for absurdly speedy review on a Saturday!

**Comment by benesch** [comment]
And also thanks for noticing the underlying weirdness when you went to implement `array_length`!

File: src/expr/src/scalar/func.rs (hunk 1 above)
Comment (petrosagg) [reply src/expr/src/scalar/func.rs:3764]: Ah, right of course. Thanks for the explanation!
