### PR TITLE
sql: disallow count(distinct *)

### LINKED ISSUE #9150: select count(distinct *) is interpreted as select count(distinct true)
```
explain raw plan for select count(distinct *) from foo;
                Raw Plan                
----------------------------------------
 %0 =                                  +
 | Get materialize.public.foo (u46)    +
 | Reduce group=() count(distinct true)+
```

I don't know what the expected behavior is, but treating this query as a `select count(distinct true) from foo` seems wrong. Fwiw Postgres considers this query as invalid and containing a syntax error.

### PR DESCRIPTION
**Pull request by sploiselle**
### Motivation

This PR fixes a recognized bug. Fixes #9150.

Also fixed a minor difference between MZ and PG where we allowed calling DISTINCT on a 0-column table.

### Reviewer notes

The first iteration of this PR bailed on planning, but this should bail in parsing because no function takes `DISTINCT *` as valid arguments.

Because I did a little cleanup in the first iteration of the PR I left it in the first commit but I think it can be mostly ignored.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR adds a release note for any
  [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

File: src/sql/src/plan/query.rs [hunk 1]
```diff
@@ -3349,7 +3359,7 @@ fn plan_function<'a>(
         distinct,
     }: &'a Function<Aug>,
 ) -> Result<HirScalarExpr, anyhow::Error> {
-    let unresolved_name = normalize::unresolved_object_name(name.clone())?;
+    let unresolved_name = dbg!(normalize::unresolved_object_name(name.clone())?);
```
Comment (mjibson) [inline src/sql/src/plan/query.rs]: leftover

**Review by mjibson — APPROVED** [review]

**Comment by sploiselle** [comment]
@mjibson ptal again if you don't mind--realized this morning this ought to be a parser error as it is in PG.

**Review by mjibson — APPROVED** [review]
