### PR TITLE
[kafka sink] Don't emit updates until input frontier passes AS OF

### LINKED ISSUE #14754: regression: storaged crash loop: some element of the Sink as_of frontier is too far advanced for our output-gating timestamp"
### What version of Materialize are you using?

78a4e9e95d319e224af4b2df20c19591de054d4a

### How did you install Materialize?

Docker image

### What is the issue?

The Zippy kafka sources test has started failing . The test creates a sink based on a materialized view based on one or more Kafka sources. The test also kills and restarts storageds

https://buildkite.com/materialize/nightlies/builds/1147#01832df6-7a81-4cce-8c7a-6e11dbbef095

The logs indicate that the panic below has happened 64 times, so it is a crash loop type of situation.

### Relevant log output

```source
zippy-materialized-1     | thread 'timely:work-0' panicked at 'some element of the Sink as_of frontier is too far advanced for our output-gating timestamp: as_of Antichain { elements: [1662896751762] }, gate_ts: 1662896751761', src/storage/src/sink/kafka.rs:1157:25
zippy-materialized-1     | stack backtrace:
zippy-materialized-1     |    0: rust_begin_unwind
zippy-materialized-1     |              at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
zippy-materialized-1     |    1: core::panicking::panic_fmt
zippy-materialized-1     |              at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
zippy-materialized-1     |    2: mz_storage::sink::kafka::produce_to_kafka::{{closure}}::{{closure}}::{{closure}}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02dcec3a2b709fcad-1/materialize/tests/src/storage/src/sink/kafka.rs:1157:25
zippy-materialized-1     |    3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
zippy-materialized-1     |              at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
zippy-materialized-1     |    4: mz_storage::sink::kafka::produce_to_kafka::{{closure}}::{{closure}}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02dcec3a2b709fcad-1/materialize/tests/src/timely-util/src/operators_async_ext.rs:201:36
zippy-materialized-1     |    5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
zippy-materialized-1     |              at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
zippy-materialized-1     |    6: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
zippy-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.24/src/future/future/fuse.rs:86:37
zippy-materialized-1     |    7: <core::pin::Pin<P> as core::future::future::Future>::poll
zippy-materialized-1     |              at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/future.rs:124:9
zippy-materialized-1     |    8: <timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G> as mz_timely_util::operators_async_ext::OperatorBuilderExt<G>>::build_async::{{closure}}::{{closure}}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02dcec3a2b709fcad-1/materialize/tests/src/timely-util/src/operators_async_ext.rs:165:43
zippy-materialized-1     |    9: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
zippy-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/dataflow/operators/generic/builder_rc.rs:162:26
zippy-materialized-1     |   10: <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
zippy-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/dataflow/operators/generic/builder_raw.rs:204:9
zippy-materialized-1     |   11: timely::progress::subgraph::PerOperatorState<T>::schedule
zippy-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/progress/subgraph.rs:684:30
zippy-materialized-1     |   12: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
zippy-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/progress/subgraph.rs:344:26
zippy-materialized-1     |   13: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
zippy-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/progress/subgraph.rs:310:17
zippy-materialized-1     |   14: timely::progress::subgraph::PerOperatorState<T>::schedule
zippy-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/progress/subgraph.rs:684:30
zippy-materialized-1     |   15: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
zippy-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/progress/subgraph.rs:344:26
zippy-materialized-1     |   16: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
zippy-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/progress/subgraph.rs:310:17
zippy-materialized-1     |   17: timely::worker::Wrapper::step::{{closure}}
zippy-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/worker.rs:754:57
zippy-materialized-1     |   18: core::option::Option<T>::map
zippy-materialized-1     |              at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/option.rs:929:29
zippy-materialized-1     |   19: timely::worker::Wrapper::step
zippy-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/worker.rs:754:26
zippy-materialized-1     |   20: timely::worker::Worker<A>::step_or_park
zippy-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/worker.rs:396:38
zippy-materialized-1     |   21: mz_storage::storage_state::Worker<A>::run_client
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02dcec3a2b709fcad-1/materialize/tests/src/storage/src/storage_state.rs:134:17
zippy-materialized-1     |   22: mz_storage::storage_state::Worker<A>::run
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02dcec3a2b709fcad-1/materialize/tests/src/storage/src/storage_state.rs:110:33
zippy-materialized-1     |   23: mz_storage::protocol::server::serve::{{closure}}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02dcec3a2b709fcad-1/materialize/tests/src/storage/src/protocol/server.rs:94:9
zippy-materialized-1     |   24: timely::execute::execute::{{closure}}
zippy-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/execute.rs:287:22
zippy-materialized-1     |   25: timely_communication::initialize::initialize_from::{{closure}}
zippy-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/communication/src/initialize.rs:316:33
zippy-materialized-1     | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
zippy-materialized-1     | environmentd: 2022-09-11T11:47:49.424093Z ERROR mz_orchestrator_process: storage-u50 exited: Ok(ExitStatus(unix_wait_status(6))); relaunching in 5s
```

### PR DESCRIPTION
**Pull request by cjubb39**
The following sequence causes a crash:
- `CREATE SINK sink FROM source with AS OF t1`.  The input frontier from `source` also equals `t1`.
- With the input frontier equal to `t1`, no rows at `t1` are moved from `pending_rows` to `ready_rows` in the kafka implementation
- We do, however, call `maybe_emit_progress` and write out `t1 - 1` indicating that all future writes to the topic will happen at `t1` or later
- Some error occurs and we crash
- We restart.  The input frontier hasn't moved forward so we re-run the `CREATE SINK` command with the same `AS OF = t1`.
- We read that the gate_ts (highest timestamp written to the progress topic) equals `t1 - 1` but the AS OF is `t1`.  This trips an assert

Distilled down, the issue here is that we write out times to the progress topic that are earlier than the initial AS OF meaning that it is possible to trip the assert that the gate_ts is at or after the AS OF.  However, we don't actually need to record this -- so we should better handle this boundary condition.

To address this, we avoid writing out to the progress topic until the input frontier has passed the AS OF.  Currently this invariant exists for progress updates that accompany a data write -- so we're just delaying those periodic progress messages that are linked only to the input frontier advancing.

### Motivation
Fixes #14754 

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - I've done some zippy testing and didn't see a failure.  We don't have a great framework (yet!) to inject a fault at a specific point so it's hard to write a test for this specific failure.

### CODE REVIEW

**Comment by bkirwi** [comment]
> This has the beneficial side effect of not writing out anything to the progress topic until there is actual data written out. Consider the situation where the user creates an empty source and then a sink based on that source. Before this PR, we would begin writing out to the progress topic immediately. Now, we delay writing out until we write out the first timestamp of data. After that, we continue writing out progress updates periodically.

Are we sure this is beneficial? When we were discussing the progress topic design, I got a lot of feedback that it was important to report progress especially when there was no other output being written -- since that way it's possible to distinguish between "correctly reporting no output" and "accidentally failed to write output that later got compacted away". This would break that property, while still having a bunch of otherwise-unnecessary progress reports when the sunk collection was quiescent.

In either case, it sounds to me like the assert is a bit bogus, and it's totally fine if the gating timestamp is `as_of-1`. (Since there's no "gap" between the two that would indicate missing data.) Does that sound right?

**Comment by cjubb39** [comment]
> I got a lot of feedback that it was important to report progress especially when there was no other output being written
Is this still true _before any data was ever written out_?  With this PR, we'll still continue to report progress as we did before if we've _ever_ written data to the topic

> it sounds to me like the assert is a bit bogus, and it's totally fine if the gating timestamp is as_of-1
As things currently work (pre-PR, that is), it's permissible for the gating timestamp to be `as_of - 1` but ONLY if we've never written data out.  If we've written any data out, this is an incorrect state where we will potentially miss writing out other data

File: src/storage/src/sink/kafka.rs [hunk 1]
```diff
@@ -399,15 +400,15 @@ struct KafkaSinkState {
...
+    /// Timestamp of the latest progress record that was written out to Kafka.
     latest_progress_ts: Timestamp,
 
     /// Write frontier of this sink.
     ///
     /// The write frontier potentially blocks compaction of timestamp bindings
-    /// in upstream sources. The latest written `END` record is used when
+    /// in upstream sources. The latest written progress record is used when
     /// restarting the sink to gate updates with a lower timestamp. We advance
-    /// the write frontier in lockstep with writing out END records. This
```
Comment (bkirwi) [inline src/storage/src/sink/kafka.rs:410]: 🙏

File: src/storage/src/sink/kafka.rs [hunk 2]
```diff
@@ -1169,7 +1175,7 @@ where
 
                     if let Some(gate) = latest_ts {
                         assert!(
-                            as_of.frontier.iter().all(|ts| *ts <= gate),
+                            PartialOrder::less_equal(&as_of.frontier, &Antichain::from_elem(gate)),
```
Comment (bkirwi) [inline src/storage/src/sink/kafka.rs:1178]: This is equivalent but more principled, right?

File: src/storage/src/sink/kafka.rs [hunk 3]
```diff
@@ -881,17 +882,22 @@ impl KafkaSinkState {
...
-    /// *NOTE*: `END` records will only be emitted when
+    /// *NOTE*: Progress records will only be emitted when
     /// `KafkaSinkConnection.consistency` points to a progress topic. The
     /// write frontier will be advanced regardless.
     async fn maybe_emit_progress(
         &mut self,
         input_frontier: AntichainRef<'_, Timestamp>,
+        as_of: &SinkAsOf<Timestamp>,
     ) -> anyhow::Result<bool> {
+        if !PartialOrder::less_equal(&as_of.frontier.borrow(), &input_frontier) {
```
Comment (bkirwi) [inline src/storage/src/sink/kafka.rs:897]: Nonblocking: may be helpful to capture some of yesterday's reasoning here... might not be obvious from the code that this is handling the startup case.

**Review by bkirwi — APPROVED** [review]
This looks good!

File: src/storage/src/sink/kafka.rs (hunk 2 above)
Comment (cjubb39) [reply src/storage/src/sink/kafka.rs:1178]: that's right! I made the change so it's parallel to the change above

File: src/storage/src/sink/kafka.rs (hunk 3 above)
Comment (cjubb39) [reply src/storage/src/sink/kafka.rs:897]: ahh yes, will add a comment -- thanks

File: src/storage/src/sink/kafka.rs [hunk 4]
```diff
@@ -881,33 +882,43 @@ impl KafkaSinkState {
...
     ) -> anyhow::Result<bool> {
+        input_frontier.extend(self.pending_rows.keys().min().cloned());
+        let min_frontier = input_frontier;
+
+        // If we emit a progress record before the as_of, we open ourselves to the possibility that
+        // we restart the sink with a gate timestamp behind the ASOF.  If that happens, we're unable
+        // to tell the difference between some records we've already written out and those that we
+        // still need to write out. (This is because asking for records with a given ASOF will fast
+        // forward all records at or before to the requested ASOF.)
+        if !PartialOrder::less_equal(&as_of.frontier, &min_frontier) {
```
Comment (cjubb39) [inline src/storage/src/sink/kafka.rs:905]: In `2702130f950533ce9e5cdbf713d2cae6402411aa`, I moved this comparison so it includes `self.pending_rows.keys().min()`.  That isn't strictly necessary since that value can never be before the ASOF -- but I think it's much more clear this way so you don't have to think about that invariant when reading this code

File: src/storage/src/sink/kafka.rs [hunk 5]
```diff
@@ -1316,11 +1328,10 @@ where
             // While we still have ready rows that we're emitting, hold the write
             // frontier at the previous time.
             //
-            // Only ever emit progress records if this operator/worker received
-            // updates. Only on worker receives all the updates and we don't want
-            // the other workers to also emit END records.
+            // Only one worker receives all the updates and we don't want the
```
Comment (aljoscha) [inline src/storage/src/sink/kafka.rs:1331]: 🙌

File: src/storage/src/sink/kafka.rs (hunk 4 above)
Comment (bkirwi) [reply src/storage/src/sink/kafka.rs:904]: Cool. I believe this is safe because:
- The antichain extend takes the min timestamp, so the value of `min_frontier` has not changed.
- The `if` condition here will be true whenever the old condition was true.

File: src/storage/src/sink/kafka.rs (hunk 2 above)
Comment (aljoscha) [reply src/storage/src/sink/kafka.rs:1182]: I think it might not be strictly equivalent, but also correct here. `PartialOrder::less_equals(as_of, gate)` says "for all elements g of gate, there must be an element a of as_of where a <= g".

What we had here previously was saying "for all elements a of as_of it must be that a <= gate"

File: src/storage/src/sink/kafka.rs (hunk 4 above)
Comment (aljoscha) [reply src/storage/src/sink/kafka.rs:904]: Chae and I just discussed, we think it should be `less_than`, and not `less_equal` because we subtract `1` below when calculating the timestamp that we emit.

Comment (bkirwi) [reply src/storage/src/sink/kafka.rs]: Interesting! It sounds like this was another lurking bug then?

File: src/storage/src/sink/kafka.rs [hunk 6]
```diff
@@ -881,36 +881,57 @@ impl KafkaSinkState {
...
             .cloned();
 
-        let min_pending_ts = self.pending_rows.keys().min().cloned();
-
-        let min_frontier = input_frontier.into_iter().chain(min_pending_ts).min();
-
         if let Some(min_frontier) = min_frontier {
-            // a frontier of `t` means we still might receive updates with `t`.
-            // The progress frontier we emit is a strict frontier, so subtract `1`.
+            // A frontier of `t` means we still might receive updates with `t`. The progress
```
Comment (aljoscha) [inline src/storage/src/sink/kafka.rs:925]: Excellent! I like how this is way more commentary than actual changes. 😅

**Review by aljoscha — APPROVED** [review]
I think this is good to merge now! I'll try and reproduce the original problem locally and then verify that your changes fix it.
