### PR TITLE
materialized: fix panic with closed HTTP connections

### LINKED ISSUE #6278: materialized: panic in HTTP server
```
thread: tokio:work-9
location: src/coord/src/client.rs:430:13
version: 0.7.2-dev (46eba05b72cdb1464b9e181129765bf84f7b6cf1)
backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/Test/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/backtrace/libunwind.rs:90:5
      backtrace::backtrace::trace_unsynchronized
             at /Users/Test/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/backtrace/mod.rs:66:5
      backtrace::backtrace::trace
             at /Users/Test/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/backtrace/mod.rs:53:14
   1: backtrace::capture::Backtrace::create
             at /Users/Test/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/capture.rs:176:9
      backtrace::capture::Backtrace::new
             at /Users/Test/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/capture.rs:140:22
   2: materialized::handle_panic
             at src/materialized/src/bin/materialized/main.rs:652:21
   3: core::ops::function::Fn::call
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:70:5
   4: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   5: std::panicking::begin_panic::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:520:9
   6: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   7: std::panicking::begin_panic
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:519:12
   8: <coord::client::SessionClient as core::ops::drop::Drop>::drop
             at src/coord/src/client.rs:430:13
   9: core::ptr::drop_in_place<coord::client::SessionClient>
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ptr/mod.rs:179:1
  10: core::ptr::drop_in_place<materialized::http::Server::handle_connection<tokio::net::tcp::stream::TcpStream>::{{closure}}::{{closure}}::{{closure}}>
             at src/materialized/src/http.rs:184:13
  11: core::ptr::drop_in_place<core::future::from_generator::GenFuture<materialized::http::Server::handle_connection<tokio::net::tcp::stream::TcpStream>::{{closure}}::{{closure}}::{{closure}}>>
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ptr/mod.rs:179:1
  12: core::ptr::drop_in_place<core::option::Option<core::future::from_generator::GenFuture<materialized::http::Server::handle_connection<tokio::net::tcp::stream::TcpStream>::{{closure}}::{{closure}}::{{closure}}>>>
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ptr/mod.rs:179:1
  13: core::ptr::drop_in_place<alloc::boxed::Box<core::option::Option<core::future::from_generator::GenFuture<materialized::http::Server::handle_connection<tokio::net::tcp::stream::TcpStream>::{{closure}}::{{closure}}::{{closure}}>>>>
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ptr/mod.rs:179:1
  14: core::ptr::drop_in_place<core::pin::Pin<alloc::boxed::Box<core::option::Option<core::future::from_generator::GenFuture<materialized::http::Server::handle_connection<tokio::net::tcp::stream::TcpStream>::{{closure}}::{{closure}}::{{closure}}>>>>>
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ptr/mod.rs:179:1
  15: core::ptr::drop_in_place<hyper::proto::h1::dispatch::Server<hyper::service::util::ServiceFn<materialized::http::Server::handle_connection<tokio::net::tcp::stream::TcpStream>::{{closure}}::{{closure}},hyper::body::body::Body>,hyper::body::body::Body>>
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ptr/mod.rs:179:1
  16: core::ptr::drop_in_place<hyper::proto::h1::dispatch::Dispatcher<hyper::proto::h1::dispatch::Server<hyper::service::util::ServiceFn<materialized::http::Server::handle_connection<tokio::net::tcp::stream::TcpStream>::{{closure}}::{{closure}},hyper::body::body::Body>,hyper::body::body::Body>,hyper::body::body::Body,hyper_openssl::MaybeHttpsStream<ore::netio::stream::SniffedStream<tokio::net::tcp::stream::TcpStream>>,hyper::proto::h1::role::Server>>
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ptr/mod.rs:179:1
  17: core::ptr::drop_in_place<hyper::server::conn::ProtoServer<hyper_openssl::MaybeHttpsStream<ore::netio::stream::SniffedStream<tokio::net::tcp::stream::TcpStream>>,hyper::body::body::Body,hyper::service::util::ServiceFn<materialized::http::Server::handle_connection<tokio::net::tcp::stream::TcpStream>::{{closure}}::{{closure}},hyper::body::body::Body>>>
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ptr/mod.rs:179:1
  18: core::ptr::drop_in_place<core::option::Option<hyper::server::conn::ProtoServer<hyper_openssl::MaybeHttpsStream<ore::netio::stream::SniffedStream<tokio::net::tcp::stream::TcpStream>>,hyper::body::body::Body,hyper::service::util::ServiceFn<materialized::http::Server::handle_connection<tokio::net::tcp::stream::TcpStream>::{{closure}}::{{closure}},hyper::body::body::Body>>>>
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ptr/mod.rs:179:1
  19: core::ptr::drop_in_place<hyper::server::conn::Connection<hyper_openssl::MaybeHttpsStream<ore::netio::stream::SniffedStream<tokio::net::tcp::stream::TcpStream>>,hyper::service::util::ServiceFn<materialized::http::Server::handle_connection<tokio::net::tcp::stream::TcpStream>::{{closure}}::{{closure}},hyper::body::body::Body>>>
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ptr/mod.rs:179:1
  20: core::ptr::drop_in_place<futures_util::future::try_future::into_future::IntoFuture<hyper::server::conn::Connection<hyper_openssl::MaybeHttpsStream<ore::netio::stream::SniffedStream<tokio::net::tcp::stream::TcpStream>>,hyper::service::util::ServiceFn<materialized::http::Server::handle_connection<tokio::net::tcp::stream::TcpStream>::{{closure}}::{{closure}},hyper::body::body::Body>>>>
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ptr/mod.rs:179:1
  21: <pin_project_lite::__private::UnsafeDropInPlaceGuard<T> as core::ops::drop::Drop>::drop
             at /Users/Test/.cargo/registry/src/github.com-1ecc6299db9ec823/pin-project-lite-0.2.4/src/lib.rs:1717:17
  22: core::ptr::drop_in_place<pin_project_lite::__private::UnsafeDropInPlaceGuard<futures_util::future::try_future::into_future::IntoFuture<hyper::server::conn::Connection<hyper_openssl::MaybeHttpsStream<ore::netio::stream::SniffedStream<tokio::net::tcp::stream::TcpStream>>,hyper::service::util::ServiceFn<materialized::http::Server::handle_connection<tokio::net::tcp::stream::TcpStream>::{{closure}}::{{closure}},hyper::body::body::Body>>>>>
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ptr/mod.rs:179:1
  23: core::ptr::drop_in_place<(pin_project_lite::__private::UnsafeDropInPlaceGuard<futures_util::future::try_future::into_future::IntoFuture<hyper::server::conn::Connection<hyper_openssl::MaybeHttpsStream<ore::netio::stream::SniffedStream<tokio::net::tcp::stream::TcpStream>>,hyper::service::util::ServiceFn<materialized::http::Server::handle_connection<tokio::net::tcp::stream::TcpStream>::{{closure}}::{{closure}},hyper::body::body::Body>>>>,())>
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ptr/mod.rs:179:1
  24: futures_util::future::future::map::_::<impl futures_util::future::future::map::Map<Fut,F>>::project_replace
             at /Users/Test/.cargo/registry/src/github.com-1ecc6299db9ec823/pin-project-lite-0.2.4/src/lib.rs:1213:29
  25: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/Test/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/future/map.rs:56:23
  26: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/Test/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/lib.rs:102:13
  27: <futures_util::future::try_future::MapErr<Fut,F> as core::future::future::Future>::poll
             at /Users/Test/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/lib.rs:102:13
  28: <futures_util::future::try_future::ErrInto<Fut,E> as core::future::future::Future>::poll
             at /Users/Test/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/lib.rs:102:13
  29: materialized::http::Server::handle_connection::{{closure}}
             at src/materialized/src/http.rs:187:9
  30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/future/mod.rs:80:19
  31: <materialized::http::Server as materialized::mux::ConnectionHandler>::handle_connection::{{closure}}
             at src/materialized/src/mux.rs:159:9
```

The reproduction instructions have something to do with #6205, followed by loading the memory visualization? I haven't been able to repro myself. @ruchirK got us this stack trace, but the initial report was from @aljoscha and a prospect.

### PR DESCRIPTION
**Pull request by benesch**
An HTTP connection that closes at the wrong time can cause Materialize
to panic. The cause is that Hyper was drops HTTP connection handler
futures when the client goes away, in an effort to avoid doing
unnecessary work. But we have important cleanup work that must be
performed when a connection closes; failing to do that work is in fact
panicworthy.

Unfortunately Hyper does not allow you to request that all futures be
polled to completion, even if the client goes away.  So this commit
fixes the bug by introducing a new `spawn_if_canceled` future
combinator. The idea is that we can use the `Drop` implementation of
this combinator to call `tokio::spawn` to poll the original future to
completion. It's a bit weird, but it seems to work well.

An alternative solution is to use an `Arc<Mutex<SessionClient>>` to
share the SessionClient outside of the future, so that code outside the
future could perform the necessary cleanup. That turns out to be much
messier, though, and has to be done for every type inside the future
that requires this sort of cleanup, which includes a channel deep inside
the "/sql" endpoint handler.

The "correct" solution to this problem would use asynchronous
destructors (i.e., `AsyncDrop`), but that's not presently a thing in
Rust, and probably won't be for years.

Huge thank you to @ruchirK and @antifuchs for helping to track this
down.

Fix #6278.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/6284)

### CODE REVIEW

File: src/materialized/src/http.rs [hunk 1]
```diff
@@ -181,7 +182,27 @@ impl Server {
...
+            // Not observing this rule leads to invariant violations that panic;
+            // see #6278 for an example.
+            //
+            // The fix here is to wrap the future in a combinator that will call
+            // `tokio::spawn` to poll it to completion if Hyper gives up on it.
+            // A bit weird, but it works, and hides this messiness from the code
+            // in the future itself. If Rust ever supports asynchronous
+            // destructors ("AsyncDrop"), those will admit a more natural
+            // solution to the problem.
+            future.spawn_if_canceled()
```
Comment (antifuchs) [inline src/materialized/src/http.rs:205]: It's funny to me that this is basically what less-sophisticated web frameworks do in scripting languages, too: On a hangup they'll just keep going and then discard the response.

Seems like the right thing to do, though (and allows for a decent mental model of what is going on).

File: src/ore/src/future.rs [hunk 2]
```diff
@@ -135,6 +152,62 @@ where
...
+    T: Send + 'static,
+{
+    type Output = T;
+
+    fn poll(mut self: Pin<&mut Self>, cx: &mut Context) -> Poll<T> {
+        match &mut self.inner {
+            None => panic!("SpawnIfCanceled polled after completion"),
+            Some(f) => match f.as_mut().poll(cx) {
+                Poll::Pending => Poll::Pending,
+                Poll::Ready(res) => {
```
Comment (antifuchs) [inline src/ore/src/future.rs:174]: It took me a bit to reason through that where we use it, it only hits once the task is completed. Could you adjust the docs/leave a comment to say that this will end the inner future as soon as it turns ready (which for a task means, as soon as it's finished...).

**Review by antifuchs — COMMENTED** [review]
nice fix - I have one request!

File: src/materialized/src/http.rs (hunk 1 above)
Comment (benesch) [reply src/materialized/src/http.rs:205]: Hah, I know, right?

File: src/ore/src/future.rs (hunk 2 above)
Comment (benesch) [reply src/ore/src/future.rs:174]: Sorry, @antifuchs, I'm afraid I don't know quite what you mean! Once a future returns `Poll::Ready` you're not allowed to call `poll` on it again (unless it happens to be fused), but this doesn't do anything to end the inner future early?

Comment (antifuchs) [reply src/ore/src/future.rs:174]: Ah, that requirement to not call `poll` again was what I meant - I mixed up fused & un-fused futures in my head, apparently... and phrased the suggestion above weirdly. Somehow in my head, I assumed that the future returning "Ready" would mean it could get polled again. Since that's not the case, I think you can consider this resolved (:

**Review by antifuchs — APPROVED** [review]
Looks like a good solution!

File: src/ore/src/future.rs (hunk 2 above)
Comment (benesch) [reply src/ore/src/future.rs:174]: Ah, gotcha! Sounds good!
