### PR TITLE
storage: in reclock::compact, turn assert into no-op

### LINKED ISSUE #13974: Load generator source crashed and failed to restart
### What version of Materialize are you using?

v0.27.0-alpha.8

### How did you install Materialize?

Materialize Cloud

### What is the issue?

I created an auction load generator source:

```sql
CREATE SOURCE lg FROM LOAD GENERATOR auction;
```

I let it run for about 30m. It crashed. I don’t have the logs from the first crash, unfortunately. Kubernetes doesn’t save them and I can’t find them in Honeycomb. Upon restart the `storaged` process entered a crash loop:

```
2022-07-30T06:43:34.749299Z  INFO storaged: about to bind to 0.0.0.0:2100
2022-07-30T06:43:34.749324Z  INFO storaged: serving internal HTTP server on 0.0.0.0:6878
2022-07-30T06:43:34.752799Z  INFO mz_service::grpc: Starting to listen on 0.0.0.0:2100
2022-07-30T06:43:56.166688Z  INFO mz_service::grpc: GrpcServer: remote client connected
2022-07-30T06:43:56.186778Z  INFO send_operation{operation="GetObject" service="s3"}:provide_credentials{provider=default_chain}: aws_config::meta::credentials::chain: provider in chain did not provide credentials provider=Environment context=environment variable not set
2022-07-30T06:43:56.186824Z  INFO send_operation{operation="GetObject" service="s3"}:provide_credentials{provider=default_chain}: aws_config::meta::credentials::chain: provider in chain did not provide credentials provider=Profile context=No profiles were defined
2022-07-30T06:43:56.187093Z  INFO send_operation{operation="GetObject" service="s3"}:provide_credentials{provider=default_chain}:send_operation{operation="AssumeRoleWithWebIdentity" service="sts"}: aws_http::auth: provider returned CredentialsNotLoaded, ignoring
2022-07-30T06:43:56.413516Z  INFO send_operation{operation="GetObject" service="s3"}:provide_credentials{provider=default_chain}: aws_config::meta::credentials::chain: loaded credentials provider=WebIdentityToken
2022-07-30T06:43:56.811398Z  INFO tokio_postgres::connection: NOTICE: relation "consensus" already exists, skipping    
thread 'timely:work-0' panicked at 'invalid as_of: as_of(Antichain { elements: [0] }) < since(Antichain { elements: [1659163020001] })', src/storage/src/source/reclock.rs:92:9
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
   2: mz_storage::source::reclock::ReclockOperator::new::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0dc80afdafce99961-1/materialize/tests/src/storage/src/source/reclock.rs:92:9
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
   4: mz_storage::source::create_raw_source::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0dc80afdafce99961-1/materialize/tests/src/storage/src/source/mod.rs:742:41
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
   6: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.3.3/src/async_stream.rs:53:17
   7: mz_storage::source::create_raw_source::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0dc80afdafce99961-1/materialize/tests/src/storage/src/source/mod.rs:890:50
   8: mz_storage::source::util::source::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0dc80afdafce99961-1/materialize/tests/src/storage/src/source/util.rs:103:17
   9: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ee65cdc/timely/src/dataflow/operators/generic/builder_rc.rs:123:31
  10: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ee65cdc/timely/src/dataflow/operators/generic/builder_rc.rs:162:26
  11: <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ee65cdc/timely/src/dataflow/operators/generic/builder_raw.rs:204:9
  12: timely::progress::subgraph::PerOperatorState<T>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ee65cdc/timely/src/progress/subgraph.rs:684:30
  13: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ee65cdc/timely/src/progress/subgraph.rs:344:26
  14: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ee65cdc/timely/src/progress/subgraph.rs:310:17
  15: timely::progress::subgraph::PerOperatorState<T>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ee65cdc/timely/src/progress/subgraph.rs:684:30
  16: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ee65cdc/timely/src/progress/subgraph.rs:344:26
  17: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ee65cdc/timely/src/progress/subgraph.rs:310:17
  18: timely::worker::Wrapper::step::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ee65cdc/timely/src/worker.rs:754:57
  19: core::option::Option<T>::map
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/option.rs:909:29
  20: timely::worker::Wrapper::step
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ee65cdc/timely/src/worker.rs:754:26
  21: timely::worker::Worker<A>::step_or_park
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ee65cdc/timely/src/worker.rs:396:38
  22: mz_storage::storage_state::Worker<A>::run_client
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0dc80afdafce99961-1/materialize/tests/src/storage/src/storage_state.rs:109:13
  23: mz_storage::storage_state::Worker<A>::run
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0dc80afdafce99961-1/materialize/tests/src/storage/src/storage_state.rs:93:33
  24: mz_storage::protocol::server::serve::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0dc80afdafce99961-1/materialize/tests/src/storage/src/protocol/server.rs:87:9
  25: timely::execute::execute::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ee65cdc/timely/src/execute.rs:287:22
  26: timely_communication::initialize::initialize_from::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ee65cdc/communication/src/initialize.rs:316:33
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Stream closed EOF for environment-4777bfc1-2bd8-4a13-a5dd-a44928652335-0/storage-u1-0 (default)
```

I suspect that load generator sources do not restart correctly. Hopefully this readily repros locally.

cc @mjibson

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by aljoscha**
As long as the assertion about `as_of` and `since` on creation are correct, it is fine to ignore these compaction requests if they don't advance the since.

We have seen at least one occurrence of the assert firing in production, which is not good.

Fixes #13974

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Comment by petrosagg** [comment]
This PR scares me. The implication "assertion on creation implies everything is fine later on" is only true with bug-less code. But bug-less code would never get the since frontier wrong either and would never trigger the assertion so the fact that we see it might be an indication of a bug.

**Comment by guswynn** [comment]
I am also quite nervous about this, but if its a bandaid im fine with it merging for a bit. Can we add an error log whenever it happens with as many pieces of info as possible? that way we can track in sentry in production and possibly debug it from there

**Review by benesch — APPROVED** [review]

File: src/storage/src/source/reclock.rs [hunk 1]
```diff
@@ -320,7 +320,20 @@ impl ReclockFollower {
 
 impl ReclockFollowerInner {
     pub fn compact(&mut self, new_since: Antichain<Timestamp>) {
-        assert!(PartialOrder::less_equal(&self.since, &new_since));
+        if PartialOrder::less_equal(&new_since, &self.since) {
```
Comment (petrosagg) [inline src/storage/src/source/reclock.rs:323]: I think you meant  `if !PartialOrder::less_equal(&self.since, &new_since) {` here?

File: src/storage/src/source/reclock.rs [hunk 2]
```diff
@@ -320,7 +320,20 @@ impl ReclockFollower {
...
+            // As long as the assertion about `as_of` and `since` on creation
+            // are correct, it is fine to ignore these compaction requests if
+            // they don't advance the since.
+            tracing::error!(
+                ?new_since,
+                ?self.since,
+                "We are forced to skip the compaction in \
+                the _ReclockFollower_ because the `new_since` >= the `since`. \
```
Comment (guswynn) [inline src/storage/src/source/reclock.rs:331]: this should have been `<=`

File: src/storage/src/source/reclock.rs (hunk 1 above)
Comment (aljoscha) [reply src/storage/src/source/reclock.rs:323]: it's flipped from before, we return when `new_since <= since`. Isn't that right? But the logging message does need fixing... 🙈

Comment (aljoscha) [reply src/storage/src/source/reclock.rs:323]: @petrosagg not sure you're seeing this ☝️
